import Link from 'next/link';
import {requireAdmin} from '@/lib/admin/access';
import {sql,withDbRetry} from '@/lib/db';
export const dynamic='force-dynamic';
export default async function AssignmentMemoryAdmin(){
 await requireAdmin();
 const rows=await withDbRetry(()=>sql`SELECT u.id,u.full_name,u.email,sp.class_level,COUNT(DISTINCT ua.id)::int assignments,COUNT(aq.id)::int questions,COUNT(aq.id) FILTER(WHERE aq.needs_confirmation=true)::int needs_review,COUNT(aq.id) FILTER(WHERE aq.needs_confirmation=false AND aq.active_for_review=true AND aq.next_review_at<=now())::int due FROM users u JOIN student_profiles sp ON sp.user_id=u.id LEFT JOIN uploaded_assignments ua ON ua.student_id=u.id LEFT JOIN assignment_questions aq ON aq.assignment_id=ua.id WHERE u.role='STUDENT' GROUP BY u.id,sp.class_level ORDER BY needs_review DESC,due DESC,u.full_name`);
 const totals=rows.reduce((a:any,r:any)=>({assignments:a.assignments+Number(r.assignments),questions:a.questions+Number(r.questions),review:a.review+Number(r.needs_review),due:a.due+Number(r.due)}),{assignments:0,questions:0,review:0,due:0});
 return <main className="shell admin-assignment-memory"><header className="admin-hero"><div><span className="eyebrow">SCHOOL-WORK MEMORY</span><h1>Keep every learner’s real work useful after the homework is over.</h1><p>Review converted questions before they enter revision, see what is due to return, and make sure AVORA’s future tests are grounded in each learner’s actual school work as well as the curriculum.</p></div><Link href="/admin">Admin overview →</Link></header><section className="admin-kpis"><div><span>Assignments</span><strong>{totals.assignments}</strong><small>retained school-work sets</small></div><div><span>Questions</span><strong>{totals.questions}</strong><small>original questions preserved</small></div><div><span>Needs review</span><strong>{totals.review}</strong><small>cannot resurface yet</small></div><div><span>Due again</span><strong>{totals.due}</strong><small>confirmed revision questions</small></div></section><section className="admin-memory-table"><header><span className="section-kicker">LEARNERS</span><h2>Assignment memory by student</h2></header>{rows.map((r:any)=><article key={r.id}><div><strong>{r.full_name}</strong><small>{r.class_level} · {r.email}</small></div><div><b>{r.assignments}</b><span>sets</span></div><div><b>{r.questions}</b><span>questions</span></div><div><b>{r.needs_review}</b><span>review</span></div><div><b>{r.due}</b><span>due</span></div></article>)}</section></main>
}
