import Link from 'next/link';import {notFound} from 'next/navigation';import {requireAdmin} from '@/lib/admin/access';import {sql,withDbRetry} from '@/lib/db';
export const dynamic='force-dynamic';
export default async function Student({params}:{params:Promise<{id:string}>}){await requireAdmin();const {id}=await params;const [u]=await withDbRetry(()=>sql`SELECT u.full_name,u.email,sp.class_level,sp.target_exam,sp.preferred_subject FROM users u LEFT JOIN student_profiles sp ON sp.user_id=u.id WHERE u.id=${id} AND u.role='STUDENT'`);if(!u)notFound();const [attempts,skills,live,taught]=await Promise.all([
withDbRetry(()=>sql`SELECT a.created_at,a.mode,a.is_correct,a.diagnosis,q.prompt,t.name topic,s.name skill FROM attempts a JOIN questions q ON q.id=a.question_id JOIN skills s ON s.id=q.skill_id JOIN topics t ON t.id=s.topic_id WHERE a.student_id=${id} ORDER BY a.created_at DESC LIMIT 100`),
withDbRetry(()=>sql`SELECT t.name topic,s.name skill,ROUND(m.score*100)::int score,m.evidence_count,m.last_practiced_at FROM mastery m JOIN skills s ON s.id=m.skill_id JOIN topics t ON t.id=s.topic_id WHERE m.student_id=${id} ORDER BY m.score ASC,m.evidence_count DESC LIMIT 30`),
withDbRetry(()=>sql`SELECT l.title,l.subject_name,l.scheduled_at,p.status,p.parent_confirmed,p.score,p.submitted_at,r.strongest_topic,r.weakest_topic,r.recommended_topic,r.summary FROM live_assessment_participants p JOIN live_assessments l ON l.id=p.assessment_id LEFT JOIN live_assessment_reports r ON r.assessment_id=p.assessment_id AND r.student_id=p.student_id WHERE p.student_id=${id} ORDER BY l.scheduled_at DESC LIMIT 30`),
withDbRetry(()=>sql`SELECT topic_name,coverage_complete,last_unit_title,last_interaction_at FROM tutor_topic_progress WHERE student_id=${id} ORDER BY updated_at DESC LIMIT 30`)]);
const done=attempts.length,correct=attempts.filter((x:any)=>x.is_correct).length,avg=done?Math.round(correct/done*100):0,mastered=skills.filter((x:any)=>x.score>=80&&x.evidence_count>=7).length,weak=skills.filter((x:any)=>x.score<50).length;
return <main className="shell admin-v103"><header className="student-profile-head"><div><Link href="/admin/students">← Students</Link><span className="eyebrow">{u.class_level||'STUDENT'} · {u.preferred_subject||'LEARNING PROFILE'}</span><h1>{u.full_name}</h1><p>{u.email}</p></div><div className="profile-score"><strong>{avg}%</strong><span>recent attempt accuracy</span></div></header><section className="admin-kpis"><div><span>Attempts</span><strong>{done}</strong><small>latest evidence shown</small></div><div><span>Mastered</span><strong>{mastered}</strong><small>skills with strong evidence</small></div><div><span>Needs attention</span><strong>{weak}</strong><small>skills below 50%</small></div><div><span>Topics taught</span><strong>{taught.filter((x:any)=>x.coverage_complete).length}</strong><small>completed Tutor coverage</small></div></section><section className="admin-detail-grid"><article className="admin-panel"><header><span>PROGRESS</span><h2>Weakest evidence first</h2></header>{skills.length?skills.slice(0,10).map((x:any)=><div className="evidence-admin-row" key={`${x.topic}-${x.skill}`}><span><small>{x.topic}</small><b>{x.skill}</b></span><strong>{x.score}%</strong><em>{x.evidence_count} answers</em></div>):<p>No mastery evidence yet.</p>}</article><article className="admin-panel"><header><span>LIVE ASSESSMENTS</span><h2>Parent-supervised history</h2></header>{live.length?live.map((x:any,i:number)=><div className="evidence-admin-row" key={i}><span><small>{x.subject_name}</small><b>{x.title}</b></span><strong>{x.score==null?'—':`${Math.round(Number(x.score)*100)}%`}</strong><em>{x.parent_confirmed?'Parent confirmed':'Unconfirmed'}{x.recommended_topic?` · Next: ${x.recommended_topic}`:''}</em></div>):<p>No live assessment yet.</p>}</article></section><section className="admin-panel attempts-panel"><header><span>ATTEMPT HISTORY</span><h2>Every recent independent answer</h2></header>{attempts.map((x:any,i:number)=><div className="attempt-admin-row" key={i}><span><small>{x.mode} · {new Date(x.created_at).toLocaleString('en-NG')}</small><b>{x.topic} · {x.skill}</b><p>{x.prompt}</p></span><strong className={x.is_correct?'attempt-ok':'attempt-no'}>{x.is_correct?'Correct':'Needs review'}</strong></div>)}</section></main>}
