import {learningAccessDenial} from '@/lib/apiAccess';
import {NextResponse} from 'next/server';
import {getSession} from '@/lib/auth';
import {sql,withDbRetry} from '@/lib/db';
import {z} from 'zod';
import {subjectSlug,profileSubjectValue} from '@/lib/subjects';
import {trialAssessmentCount,trialQuestionUsage,reserveTrialQuestions,TRIAL_JSS_FULL_MOCK_LIMIT} from '@/lib/trialLimits';
import {assessmentAliases} from '@/lib/masterTopicAliases';
import {isExamReadyQuestion} from '@/lib/questionQuality';
const schema=z.object({subject:z.enum(['Mathematics','English Language']),assessmentType:z.enum(['FULL_MOCK','QUICK_10','TOPIC_TEST','WEAKNESS_TEST','PAST_YEAR_PRACTICE','AUTHORED_MOCK']).default('FULL_MOCK'),mockSet:z.number().int().min(1).max(2).optional(),topic:z.string().optional(),pastYear:z.number().int().min(2010).max(2035).optional()});
function normalizeOptions(v:any):string[]|null{if(Array.isArray(v))return v.map(String);if(typeof v==='string'){try{return normalizeOptions(JSON.parse(v))}catch{return null}}if(v&&typeof v==='object'){if(Array.isArray(v.options))return v.options.map(String);if(Array.isArray(v.choices))return v.choices.map(String)}return null}
function shuffle<T>(a:T[]){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function usable(r:any){const prompt=String(r.prompt||'').trim(),options=normalizeOptions(r.options);return prompt.length>=8&&(r.question_type!=='MULTIPLE_CHOICE'||Boolean(options&&options.length>=2))}
function buildTopicBlocks(good:any[],needed:number){const picked:any[]=[],by=new Map<string,any[]>();for(const r of good){const a=by.get(r.topic)||[];a.push(r);by.set(r.topic,a)}const order=[...by.keys()].sort((a,b)=>Number((by.get(a)||[])[0]?.topic_order||999)-Number((by.get(b)||[])[0]?.topic_order||999));const offsets=new Map(order.map(t=>[t,0]));let cycles=0;while(picked.length<needed&&cycles<30){let added=0;for(const t of order){const pool=by.get(t)||[],start=offsets.get(t)||0,block=pool.slice(start,start+3).sort((a,b)=>Number(a.difficulty||1)-Number(b.difficulty||1));if(!block.length)continue;picked.push(...block.slice(0,needed-picked.length));offsets.set(t,start+block.length);added+=block.length;if(picked.length>=needed)break}if(!added)break;cycles++}return picked}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:'Please sign in again.'},{status:401});const accessDenied=await learningAccessDenial(s);if(accessDenied)return accessDenied;try{
 const d=schema.parse(await req.json()),subSlug=subjectSlug(d.subject),profileSubject=profileSubjectValue(d.subject);
 const trial=await trialQuestionUsage(s.userId);if(trial.isTrial&&['FULL_MOCK','AUTHORED_MOCK'].includes(d.assessmentType)){const count=await trialAssessmentCount(s.userId,'JSS_FULL_MOCK');if(count>=TRIAL_JSS_FULL_MOCK_LIMIT)return NextResponse.json({error:'Your 14-day trial includes one complete full mock assessment. Subscribe to unlock further full mocks.',code:'TRIAL_MOCK_LIMIT',trial},{status:402});}
 const [profile]=await withDbRetry(()=>sql`SELECT class_level FROM student_profiles WHERE user_id=${s.userId}`);const classLevel=String(profile?.class_level||'JSS3');const effectiveExam=classLevel==='JSS3'?'BECE':`${classLevel}_CURRICULUM`;
 if(d.assessmentType==='AUTHORED_MOCK'&&!d.mockSet)return NextResponse.json({error:'Choose Mock Set 1 or Mock Set 2.'},{status:400});
 if(d.assessmentType==='PAST_YEAR_PRACTICE'&&classLevel!=='JSS3')return NextResponse.json({error:'Past-year BECE practice is reserved for JSS3. Use Full Mock, Quick 10 or Topic Test for your class curriculum.'},{status:409});
 let yearRef:any=null;if(d.assessmentType==='PAST_YEAR_PRACTICE'){const requestedYear=d.pastYear;if(!requestedYear)return NextResponse.json({error:'Choose a past-question year first.'},{status:400});const refs=await withDbRetry(()=>sql`SELECT r.*,a.provider,a.title source_title FROM exam_year_registry r LEFT JOIN academic_source_registry a ON a.source_key=r.source_key WHERE r.exam_name='BECE' AND r.exam_year=${requestedYear} AND r.subject_name=${d.subject} AND r.questions_available=true LIMIT 1`);yearRef=refs[0];if(!yearRef)return NextResponse.json({error:`AVORA has not verified a BECE ${d.subject} reference for ${requestedYear} yet.`},{status:409})}
 const topicAliases=d.topic?assessmentAliases(classLevel,d.subject,String(d.topic)).map(x=>x.toLowerCase()):[];
 const rows=await withDbRetry(()=>sql`SELECT q.id,q.prompt,q.question_type,q.options,q.correct_answer,q.difficulty,q.mock_question_number,COALESCE(q.exam_topic,t.name) topic,COALESCE(hist.times_seen,0)::int times_seen,hist.last_seen,COALESCE(hist.correct_seen,0)::int correct_seen,t.order_index topic_order FROM questions q JOIN skills sk ON sk.id=q.skill_id JOIN topics t ON t.id=sk.topic_id JOIN subjects sub ON sub.id=t.subject_id LEFT JOIN (SELECT a.question_id,count(*) times_seen,max(a.created_at) last_seen,count(*) FILTER(WHERE a.is_correct) correct_seen FROM attempts a WHERE a.student_id=${s.userId} GROUP BY a.question_id) hist ON hist.question_id=q.id WHERE q.status='PUBLISHED' AND q.quality_status='REVIEWED' AND q.class_level=${classLevel} AND sub.slug=${subSlug} AND (${classLevel}<>'JSS3' OR q.exam_name='BECE' OR q.exam_name IS NULL) AND (( ${d.assessmentType}='AUTHORED_MOCK' AND q.assessment_kind='AUTHORED_MOCK' AND q.mock_set=${d.mockSet||null}) OR (${d.assessmentType}<>'AUTHORED_MOCK' AND COALESCE(q.assessment_kind,'')<>'AUTHORED_MOCK')) AND (${d.topic||null}::text IS NULL OR lower(COALESCE(q.exam_topic,t.name))=ANY(${topicAliases}) OR lower(t.name)=ANY(${topicAliases})) ORDER BY COALESCE(hist.times_seen,0),hist.last_seen NULLS FIRST,q.difficulty,random()`);
 const good=d.assessmentType==='AUTHORED_MOCK'?rows.filter(usable):rows.filter(usable).filter(isExamReadyQuestion),needed=d.assessmentType==='AUTHORED_MOCK'?good.length:d.assessmentType==='QUICK_10'?10:d.assessmentType==='TOPIC_TEST'?Math.min(20,good.length):40,minimum=d.assessmentType==='TOPIC_TEST'?Math.min(5,needed):needed;if(good.length<minimum)return NextResponse.json({error:`The ${classLevel} ${d.subject} bank has ${good.length} reviewed usable questions for this selection; ${minimum} are required.`},{status:409});
 let picked:any[]=[];if(d.assessmentType==='AUTHORED_MOCK')picked=[...good].sort((a,b)=>Number(a.mock_question_number||0)-Number(b.mock_question_number||0));else if(d.assessmentType==='WEAKNESS_TEST'){const byTopic=new Map<string,{rows:any[];accuracy:number}>();for(const r of good){const x=byTopic.get(r.topic)||{rows:[],accuracy:1};x.rows.push(r);const seen=Number(r.times_seen||0);if(seen)x.accuracy=Math.min(x.accuracy,Number(r.correct_seen||0)/seen);byTopic.set(r.topic,x)}const ordered=[...byTopic.entries()].sort((a,b)=>a[1].accuracy-b[1].accuracy);let round=0;while(picked.length<Math.min(needed,good.length)&&round<50){for(const [,x] of ordered)if(x.rows[round]&&picked.length<needed)picked.push(x.rows[round]);round++}}else if(d.assessmentType==='FULL_MOCK'||d.assessmentType==='PAST_YEAR_PRACTICE')picked=buildTopicBlocks(good,needed);else picked=good.slice(0,needed);if(!['FULL_MOCK','PAST_YEAR_PRACTICE','AUTHORED_MOCK'].includes(d.assessmentType))picked=shuffle(picked);picked=picked.slice(0,needed);if(picked.length<minimum)return NextResponse.json({error:'AVORA could not build a complete reviewed paper from this class bank yet.'},{status:409});
 const ids=picked.map(x=>x.id);const reserved=await reserveTrialQuestions(s.userId,'JSS_EXAM',ids.map(String));if(!reserved.allowed)return NextResponse.json({error:`Your AVORA trial includes ${reserved.limit} self-service assessment questions. You have ${reserved.remaining} remaining, but this assessment needs ${reserved.needed}. Subscribe to continue without the trial limit.`,code:'TRIAL_QUESTION_LIMIT',trial:reserved},{status:402});const duration=d.assessmentType==='QUICK_10'?900:d.assessmentType==='TOPIC_TEST'?1800:d.assessmentType==='AUTHORED_MOCK'?(d.subject==='Mathematics'?(classLevel==='JSS1'?5400:classLevel==='JSS2'?6900:7200):(classLevel==='JSS1'?5400:classLevel==='JSS2'?6300:7200)):2700;const mockPaperKey=d.assessmentType==='AUTHORED_MOCK'?`${classLevel.toLowerCase()}-${d.subject.toLowerCase().replace(/ /g,'-')}-mock-${d.mockSet}`:null;const [x]=await withDbRetry(()=>sql`INSERT INTO exam_sessions(student_id,exam_name,subject_name,question_ids,duration_seconds,assessment_type,topic_focus,past_year,source_key,mock_paper_key) VALUES(${s.userId},${effectiveExam},${d.subject},${ids},${duration},${d.assessmentType},${d.topic||null},${d.pastYear||null},${yearRef?.source_key||null},${mockPaperKey}) RETURNING id,started_at,duration_seconds`);
 await withDbRetry(()=>sql`UPDATE student_profiles SET target_exam='BECE',preferred_subject=${profileSubject},updated_at=now() WHERE user_id=${s.userId}`);const reference=yearRef?{year:Number(yearRef.exam_year),paperStructure:yearRef.paper_structure,sourceLabel:yearRef.source_label||yearRef.source_title,sourceUrl:yearRef.source_url,rights:yearRef.rights_status,directReproductionAllowed:Boolean(yearRef.direct_reproduction_allowed),note:yearRef.direct_reproduction_allowed?'This session may use cleared past-paper content.':'This session uses AVORA-original standard questions aligned to the referenced exam year; exact copyrighted wording is not reproduced.'}:null;
 const extendedTasks=d.assessmentType==='AUTHORED_MOCK'?await withDbRetry(()=>sql`SELECT task_key,task_number,task_type,prompt,max_marks,required_count FROM authored_mock_extended_tasks WHERE paper_key=${mockPaperKey} AND status='PUBLISHED' ORDER BY task_number`):[];return NextResponse.json({sessionId:x.id,startedAt:x.started_at,durationSeconds:x.duration_seconds,total:picked.length,assessmentType:d.assessmentType,classLevel,examLabel:classLevel==='JSS3'?'BECE':`${classLevel} Curriculum Assessment`,reference,extendedTasks:extendedTasks.map((t:any)=>({taskKey:t.task_key,number:Number(t.task_number),type:t.task_type,prompt:t.prompt,maxMarks:Number(t.max_marks),requiredCount:Number(t.required_count)})),questions:picked.map((q,i)=>({number:i+1,id:q.id,prompt:String(q.prompt).trim(),type:q.question_type==='MULTIPLE_CHOICE'&&normalizeOptions(q.options)?.length?'MULTIPLE_CHOICE':'SHORT_ANSWER',options:normalizeOptions(q.options),topic:q.topic}))});
 }catch(e:any){console.error('exam start',e);if(e instanceof z.ZodError)return NextResponse.json({error:'Please choose a valid subject and assessment type.'},{status:400});return NextResponse.json({error:'Could not prepare this assessment. Please retry.'},{status:503})}}