import {NextResponse} from 'next/server';
import {getSession} from '@/lib/auth';
import {sql,withDbRetry} from '@/lib/db';
import {z} from 'zod';
const schema=z.object({title:z.string().trim().min(1).max(160),body:z.string().max(50000).default(''),classLevel:z.enum(['JSS1','JSS2','JSS3']),subject:z.enum(['Mathematics','English Language']),topicId:z.string().max(220).nullable().optional(),sourceKind:z.enum(['PERSONAL_NOTE','CLASS_NOTE']).default('CLASS_NOTE')});
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:'Sign in required.'},{status:401});const notes=await withDbRetry(()=>sql`SELECT n.*,COUNT(i.id)::int image_count FROM learner_notes n LEFT JOIN learner_note_images i ON i.note_id=n.id WHERE n.student_id=${s.userId} GROUP BY n.id ORDER BY n.updated_at DESC LIMIT 100`);return NextResponse.json({notes})}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:'Sign in required.'},{status:401});try{const d=schema.parse(await req.json());const [n]=await withDbRetry(()=>sql`INSERT INTO learner_notes(student_id,title,body,class_level,subject_name,curriculum_topic_id,source_kind) VALUES(${s.userId},${d.title},${d.body},${d.classLevel},${d.subject},${d.topicId||null},${d.sourceKind}) RETURNING *`);return NextResponse.json({note:n},{status:201})}catch(e){return NextResponse.json({error:'Enter a title, class and supported subject.'},{status:400})}}
export async function PATCH(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:'Sign in required.'},{status:401});const b=await req.json(),id=String(b.id||'');const [n]=await withDbRetry(()=>sql`UPDATE learner_notes SET title=COALESCE(${b.title||null},title),body=COALESCE(${typeof b.body==='string'?b.body:null},body),curriculum_topic_id=COALESCE(${b.topicId||null},curriculum_topic_id),updated_at=now() WHERE id=${id} AND student_id=${s.userId} RETURNING *`);if(!n)return NextResponse.json({error:'Note not found.'},{status:404});return NextResponse.json({note:n})}
export async function DELETE(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:'Sign in required.'},{status:401});const id=new URL(req.url).searchParams.get('id');const rows=await withDbRetry(()=>sql`DELETE FROM learner_notes WHERE id=${id} AND student_id=${s.userId} RETURNING id`);return rows.length?NextResponse.json({deleted:true}):NextResponse.json({error:'Note not found.'},{status:404})}
