import {NextResponse} from 'next/server';import {requireAdmin} from '@/lib/admin/access';import {sql,withDbRetry} from '@/lib/db';
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const admin=await requireAdmin();const {id}=await params;const body=await req.json();const instruction=String(body.instruction||'').trim();
 const [exam]=await withDbRetry(()=>sql`SELECT * FROM weekly_exam_blueprints WHERE id=${id}`);if(!exam)return NextResponse.json({error:'Weekly exam blueprint not found.'},{status:404});
 if(!['DRAFT','IN_REVIEW'].includes(String(exam.status)))return NextResponse.json({error:'This exam is already approved, scheduled or closed. Create a new version instead.'},{status:409});
 const scope=await withDbRetry(()=>sql`SELECT s.*,jsonb_agg(jsonb_build_object('id',o.id,'day',o.day_index,'title',o.title,'objective',o.objective_text) ORDER BY o.day_index,o.sort_order) FILTER(WHERE o.id IS NOT NULL) AS objectives FROM weekly_exam_scope s LEFT JOIN academic_daily_objectives o ON o.schedule_id=s.schedule_id AND o.status IN ('REVIEWED','LIVE') WHERE s.blueprint_id=${id} GROUP BY s.blueprint_id,s.schedule_id,s.objective_id,s.subject_name,s.curriculum_topic_id,s.target_questions,s.target_difficulty,s.skill_requirements`);
 if(!scope.length||scope.some((x:any)=>!Array.isArray(x.objectives)||!x.objectives.length))return NextResponse.json({error:'The weekly scope is incomplete. Every topic needs approved daily objectives before AI generation.'},{status:409});
 const [job]=await withDbRetry(()=>sql`INSERT INTO academic_ai_jobs(requested_by,job_kind,instruction,requested_count,status,result_summary) VALUES(${admin.userId},'GENERATE_QUESTIONS',${instruction||'Generate a rigorous weekly assessment from the approved scope.'},${Number(exam.question_count)},'QUEUED',${JSON.stringify({kind:'WEEKLY_EXAM',blueprintId:String(exam.id),classLevel:exam.class_level,term:exam.term,week:exam.week_number,scope})}::jsonb) RETURNING id`);
 await withDbRetry(()=>sql`UPDATE weekly_exam_blueprints SET status='GENERATING',updated_at=now() WHERE id=${id}`);
 return NextResponse.json({jobId:String(job.id),message:'Weekly exam AI request queued. No learner can see a paper until review and approval are complete.'},{status:202});
}