import {NextResponse} from 'next/server';import {requireAdmin} from '@/lib/admin/access';import {sql,withDbRetry} from '@/lib/db';import {generateWeeklyPaper} from '@/lib/weeklyExamGenerator';
export const maxDuration=60;
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){const admin=await requireAdmin();const {id}=await params;const body=await req.json().catch(()=>({}));const jobId=String(body.jobId||'');
 const [exam]=await withDbRetry(()=>sql`SELECT * FROM weekly_exam_blueprints WHERE id=${id}`);if(!exam)return NextResponse.json({error:'Blueprint not found.'},{status:404});
 const [job]=jobId?await withDbRetry(()=>sql`SELECT * FROM academic_ai_jobs WHERE id=${jobId} AND requested_by=${admin.userId} AND status='QUEUED'`):[];
 if(!job)return NextResponse.json({error:'A queued generation request from this admin is required.'},{status:409});
 const scope=await withDbRetry(()=>sql`SELECT s.*,jsonb_agg(jsonb_build_object('id',o.id,'day',o.day_index,'title',o.title,'objective',o.objective_text) ORDER BY o.day_index,o.sort_order) FILTER(WHERE o.id IS NOT NULL) AS objectives FROM weekly_exam_scope s LEFT JOIN academic_daily_objectives o ON o.schedule_id=s.schedule_id AND o.status IN ('REVIEWED','LIVE') WHERE s.blueprint_id=${id} GROUP BY s.blueprint_id,s.schedule_id,s.objective_id,s.subject_name,s.curriculum_topic_id,s.target_questions,s.target_difficulty,s.skill_requirements`);
 await withDbRetry(()=>sql`UPDATE academic_ai_jobs SET status='RUNNING' WHERE id=${job.id}`);
 const generated=await generateWeeklyPaper({classLevel:String(exam.class_level),term:Number(exam.term),week:Number(exam.week_number),questionCount:Number(exam.question_count),durationMinutes:Number(exam.duration_minutes),scope,adminInstruction:String(job.instruction||'')});
 if(!generated.ok){await withDbRetry(()=>sql`UPDATE academic_ai_jobs SET status='FAILED',completed_at=now(),result_summary=${JSON.stringify({error:generated.error})}::jsonb WHERE id=${job.id}`);await withDbRetry(()=>sql`UPDATE weekly_exam_blueprints SET status='DRAFT',updated_at=now() WHERE id=${id}`);return NextResponse.json({error:'AI paper failed academic validation. Nothing was added to the exam.'},{status:422});}
 const skillRows=await withDbRetry(()=>sql`SELECT DISTINCT ON (curriculum_topic_id) curriculum_topic_id,skill_id FROM questions WHERE class_level=${exam.class_level} AND curriculum_topic_id=ANY(${scope.map((x:any)=>String(x.curriculum_topic_id))}::text[]) AND skill_id IS NOT NULL ORDER BY curriculum_topic_id,created_at DESC`);const skillMap=new Map(skillRows.map((x:any)=>[String(x.curriculum_topic_id),String(x.skill_id)]));const unmapped=scope.filter((x:any)=>!skillMap.has(String(x.curriculum_topic_id)));if(unmapped.length){await withDbRetry(()=>sql`UPDATE academic_ai_jobs SET status='FAILED',completed_at=now(),result_summary=${JSON.stringify({error:'UNMAPPED_CURRICULUM_SKILL',topics:unmapped.map((x:any)=>x.curriculum_topic_id)})}::jsonb WHERE id=${job.id}`);await withDbRetry(()=>sql`UPDATE weekly_exam_blueprints SET status='DRAFT',updated_at=now() WHERE id=${id}`);return NextResponse.json({error:'Some weekly curriculum topics are not mapped to an AVORA skill yet. Map them before generating the paper.'},{status:409})}
 const result=await withDbRetry(()=>sql.begin(async tx=>{const [n]=await tx`SELECT COALESCE(MAX(version_number),0)+1::int AS n FROM weekly_exam_versions WHERE blueprint_id=${id}`;const [v]=await tx`INSERT INTO weekly_exam_versions(blueprint_id,version_number,status,generated_by,generation_job_id) VALUES(${id},${Number(n.n)},'IN_REVIEW','AI',${job.id}) RETURNING id,version_number`;
  let pos=0;for(const q of generated.json!.questions){pos++;const scopeItem:any=scope.find((x:any)=>String(x.curriculum_topic_id)===q.topicId);const objective:any=(scopeItem?.objectives||[]).find((o:any)=>String(o.objective)===q.objective);
   const [row]=await tx`INSERT INTO questions(skill_id,prompt,question_type,options,correct_answer,explanation,difficulty,status,content_origin,curriculum_objective,quality_status,solution_steps,micro_skill,rights_status,class_level,curriculum_topic_id,assessment_kind,review_version) VALUES(${skillMap.get(q.topicId)!},${q.prompt},${q.questionType}::question_type,${JSON.stringify(q.options)}::jsonb,${JSON.stringify(q.correctAnswer)}::jsonb,${q.solution},${q.difficulty==='FOUNDATION'?1:q.difficulty==='STANDARD'?2:3},'DRAFT'::question_status,'AI_WEEKLY_DRAFT',${q.objective},'DRAFT',${JSON.stringify([q.solution])}::jsonb,${q.skill},'ORIGINAL_AI_DRAFT',${exam.class_level},${q.topicId},'WEEKLY_EXAM',${'weekly-v'+v.version_number}) RETURNING id`;
   await tx`INSERT INTO weekly_exam_version_questions(version_id,question_id,position,subject_name,curriculum_topic_id,objective_id,relevance_status,answer_status,difficulty_band) VALUES(${v.id},${row.id},${pos},${q.subject},${q.topicId},${objective?.id||null},'PENDING','PENDING',${q.difficulty})`;
  }return v;}));
 await withDbRetry(()=>sql`UPDATE academic_ai_jobs SET status='COMPLETED',provider=${generated.usage.provider},model=${generated.usage.model},completed_at=now(),result_summary=${JSON.stringify({versionId:String(result.id),versionNumber:result.version_number,coverageSummary:generated.json!.coverageSummary})}::jsonb WHERE id=${job.id}`);
 await withDbRetry(()=>sql`UPDATE weekly_exam_blueprints SET status='IN_REVIEW',updated_at=now() WHERE id=${id}`);
 return NextResponse.json({versionId:String(result.id),versionNumber:result.version_number});
}