import Link from 'next/link';
export default function Home(){return <main className="marketing-home">
 <section className="shell investor-hero"><div className="hero-copy"><span className="marketing-kicker">A clearer path to real understanding</span><h1>Every learner deserves teaching that <em>notices.</em></h1><p>AVORA combines exam preparation, interactive teaching and mastery evidence in one calm learning experience—so students know what to do, parents can see progress, and teachers can see where support is needed.</p><div className="hero-actions"><Link href="/register">Start learning <span>→</span></Link><Link href="/login">Sign in</Link></div><div className="hero-proof"><div><b>Exam-aware</b><span>Structured around the exam a learner chooses.</span></div><div><b>Interactive</b><span>Students act, answer and solve—not just watch.</span></div><div><b>Mastery-led</b><span>Progress comes from repeated evidence.</span></div></div></div>
 <div className="product-stage" aria-label="AVORA product preview"><div className="stage-top"><span>BECE · MATHEMATICS</span><b>Today’s learning route</b></div><div className="stage-focus"><small>AVORA NOTICED</small><strong>Negative signs are slowing you down.</strong><p>We’ll fix that before moving deeper into simultaneous equations.</p></div><div className="stage-flow"><span className="done">Exam evidence</span><i></i><span className="active">Tutor session</span><i></i><span>Reassess</span><i></i><span>Mastery</span></div><div className="stage-question"><small>AVORA</small><b>When you subtract −4, what operation are you really doing?</b><div><span>Subtract 4</span><span className="selected">Add 4</span></div></div></div>
 </section>

 <section id="how" className="shell value-section"><header><span className="marketing-kicker">HOW AVORA WORKS</span><h2>From exam pressure to a clear next step.</h2><p>One connected system instead of separate videos, question banks, tutors and progress reports.</p></header><div className="value-flow"><article><span>01</span><h3>Choose the exam</h3><p>The learner sees the full subject and topic map before starting.</p></article><article><span>02</span><h3>Measure the pattern</h3><p>Balanced questions reveal strengths and specific weak areas.</p></article><article><span>03</span><h3>Teach personally</h3><p>Live board teaching, clear explanations and step-by-step interaction adapt to the learner.</p></article><article><span>04</span><h3>Prove mastery</h3><p>Fresh independent questions confirm that understanding has actually improved.</p></article></div></section>

 <section id="people" className="stakeholder-band"><div className="shell"><header><span className="marketing-kicker">ONE PRODUCT. THREE REASONS TO TRUST IT.</span><h2>Built to make sense to everyone around the learner.</h2></header><div className="stakeholder-grid"><article><span>STUDENTS</span><h3>“I know exactly what to do next.”</h3><p>Fast navigation, focused sessions, clear exam routes and teaching that responds without overwhelming.</p></article><article id="parents"><span>PARENTS</span><h3>“I can see whether learning is improving.”</h3><p>Meaningful topic and skill progress instead of activity counts that look impressive but say little.</p></article><article id="schools"><span>TEACHERS & SCHOOLS</span><h3>“I can see where support is needed.”</h3><p>Evidence by topic, skill and misconception gives human teachers useful context for intervention.</p></article></div></div></section>

 <section className="shell closing-cta"><span className="marketing-kicker">LEARNING THAT UNDERSTANDS YOU</span><h2>Less guessing. More understanding.</h2><p>AVORA is building a learning experience that feels simple to use because the intelligence stays underneath.</p><Link href="/register">Create your learning profile <span>→</span></Link></section>
</main>}
