'use client'; import React from 'react';
const W=({q,children}:{q:string;children:React.ReactNode})=><div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>;
const L=({children,strong=false}:{children:React.ReactNode;strong?:boolean})=><div className={strong?'math-line math-result':'math-line'}>{children}</div>;
function NL({start,end,label}:{start:number;end:number;label:string}){const nums=[-5,-4,-3,-2,-1,0,1,2,3,4,5],x=(n:number)=>55+(n+5)*55;return <div className="numberline-card"><svg viewBox="0 0 660 145"><line x1="45" y1="78" x2="615" y2="78" className="nl-axis"/>{nums.map(n=><g key={n}><line x1={x(n)} y1="68" x2={x(n)} y2="88" className="nl-tick"/><text x={x(n)} y="110" textAnchor="middle">{n}</text></g>)}<circle cx={x(start)} cy="78" r="7" className="nl-start"/><path d={'M '+x(start)+' 60 Q '+((x(start)+x(end))/2)+' 20 '+x(end)+' 60'} className="nl-move"/><text x={(x(start)+x(end))/2} y="18" textAnchor="middle">{label}</text></svg></div>}
export default function AdditionSubtractionLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson directed-lesson"><header className="wn-hero"><span>JSS1 MATHEMATICS · BASIC OPERATIONS</span><h1>Addition and Subtraction</h1><p>Calculate whole numbers accurately and use the number line to understand directed numbers.</p></header>
<section className="wn-objectives"><h2>NERDC-Aligned Objectives</h2><ul><li>Add and subtract numbers up to four digits.</li><li>State place values in results.</li><li>Solve word problems.</li><li>Use the number line for directed numbers.</li><li>Add and subtract positive and negative integers.</li><li>Apply directed numbers to movement and temperature.</li></ul></section>
<section className="wn-section"><h3>1. Four-Digit Addition</h3><W q="Add 2,468 + 1,357."><L>Align equal place values.</L><L>Units: 8 + 7 = 15; write 5, carry 1.</L><L>Tens: 6 + 5 + 1 = 12; write 2, carry 1.</L><L>Hundreds: 4 + 3 + 1 = 8.</L><L>Thousands: 2 + 1 = 3.</L><L strong>Answer = 3,825</L></W></section>
<section className="wn-section"><h3>2. Four-Digit Subtraction</h3><W q="Find 4,203 − 2,786."><L>Align place values and regroup across the zero.</L><L>Units: 13 − 6 = 7.</L><L>Tens: 9 − 8 = 1.</L><L>Hundreds: 11 − 7 = 4.</L><L>Thousands: 3 − 2 = 1.</L><L strong>Answer = 1,417</L><L>Check: 2,786 + 1,417 = 4,203.</L></W></section>
<section className="wn-section"><h3>3. Directed Numbers on the Number Line</h3><p>Positive numbers are to the right of zero; negative numbers are to the left.</p><NL start={0} end={4} label="+4: right"/><NL start={0} end={-3} label="−3: left"/></section>
<section className="wn-section"><h3>4. Addition on the Number Line</h3><W q="Find −2 + 5."><L>Start at −2. Adding +5 means move 5 places right.</L><NL start={-2} end={3} label="+5"/><L strong>−2 + 5 = 3</L></W><W q="Find 3 + (−5)."><L>Start at 3. Adding −5 means move 5 places left.</L><NL start={3} end={-2} label="add −5"/><L strong>3 + (−5) = −2</L></W></section>
<section className="wn-section"><h3>5. Subtraction on the Number Line</h3><W q="Find 2 − 6."><L>Start at 2 and move 6 places left.</L><NL start={2} end={-4} label="subtract 6"/><L strong>2 − 6 = −4</L></W><W q="Find −3 − (−4)."><L>Subtracting a negative reverses direction: move 4 places right.</L><NL start={-3} end={1} label="subtract −4"/><L strong>−3 − (−4) = 1</L></W></section>
<section className="wn-section"><h3>6. Real-Life Direction</h3><W q="Temperature is 3°C and falls by 7°C. Find the new temperature."><L>3 − 7 = −4.</L><L strong>New temperature = −4°C</L></W><W q="A hiker is 2 m above a reference point and moves 5 m downward."><L>+2 − 5 = −3.</L><L strong>The hiker is 3 m below the reference point.</L></W></section>
<section className="wn-section"><h3>7. Word Problem</h3><W q="A library had 3,875 books, received 946, then removed 528 damaged books. How many remain?"><L>3,875 + 946 = 4,821.</L><L>4,821 − 528 = 4,293.</L><L strong>4,293 books remain.</L></W></section>
<section className="wn-section"><h3>8. Common Mistakes</h3><div className="lesson-rule"><span>Align place values.</span><span>Regroup carefully across zeros.</span><span>Start at the first number on the number line.</span><span>Positive movement goes right; negative movement goes left.</span><span>Translate rise/fall and forward/backward before calculating.</span></div></section>
<div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}