'use client';
import React from 'react';

const objectives=[
'measure an angle correctly in degrees using a protractor',
'identify the vertex and arms of an angle',
'identify and explain adjacent angles',
'identify vertically opposite angles and use the fact that they are equal',
'identify corresponding angles formed by a transversal across parallel lines and use their equality',
'identify alternate angles formed by a transversal across parallel lines and use their equality',
'identify angles on a straight line and use their sum of 180°',
'identify angles at a point and use their sum of 360°',
'explain angle relationships from diagrams and real-life situations',
'solve every unknown-angle problem with a stated reason and a complete calculation'
];

function Fig({label,children}:{label:string;children:React.ReactNode}){return <figure className="geometry-figure angle-figure"><svg viewBox="0 0 420 260" role="img" aria-label={label}>{children}</svg><figcaption>{label}</figcaption></figure>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}

function BasicAngle(){return <Fig label="Angle AOB: O is the vertex; OA and OB are the arms"><line x1="85" y1="205" x2="205" y2="120" className="geo-result"/><line x1="205" y1="120" x2="350" y2="205" className="geo-result"/><path d="M163 150 A55 55 0 0 0 253 148" className="angle-arc"/><circle cx="205" cy="120" r="4" className="geo-fill"/><text x="70" y="222">A</text><text x="200" y="108">O</text><text x="355" y="222">B</text><text x="205" y="174" textAnchor="middle">∠AOB</text></Fig>}
function Protractor(){return <Fig label="Measure from the 0° line that lies on the starting arm"><line x1="70" y1="205" x2="350" y2="205" className="geo-line"/><line x1="210" y1="205" x2="290" y2="88" className="geo-result"/><path d="M80 205 A130 130 0 0 1 340 205" className="protractor-shell"/>{[0,30,60,90,120,150,180].map((d,i)=>{const a=Math.PI-(d*Math.PI/180),x=210+130*Math.cos(a),y=205-130*Math.sin(a);return <text key={d} x={x} y={y} textAnchor="middle">{d}°</text>})}<circle cx="210" cy="205" r="4" className="geo-fill"/><path d="M260 205 A50 50 0 0 0 238 164" className="angle-arc"/><text x="258" y="165">55°</text></Fig>}
function Vertical(){return <Fig label="Two intersecting lines form two equal pairs of vertically opposite angles"><line x1="65" y1="215" x2="350" y2="45" className="geo-result"/><line x1="65" y1="45" x2="350" y2="215" className="geo-result"/><circle cx="207" cy="130" r="4" className="geo-fill"/><path d="M171 109 A42 42 0 0 1 243 109 M243 151 A42 42 0 0 1 171 151" className="angle-arc"/><text x="204" y="88">x</text><text x="204" y="183">68°</text><text x="195" y="126">O</text></Fig>}
function Straight(){return <Fig label="Adjacent angles on a straight line add to 180°"><line x1="55" y1="190" x2="365" y2="190" className="geo-result"/><line x1="210" y1="190" x2="280" y2="65" className="geo-result"/><path d="M160 190 A50 50 0 0 1 235 146 M235 146 A50 50 0 0 1 260 190" className="angle-arc"/><text x="170" y="158">125°</text><text x="265" y="163">x</text><text x="45" y="215">A</text><text x="205" y="215">O</text><text x="365" y="215">B</text></Fig>}
function AtPoint(){return <Fig label="Angles around a point make one complete turn: 360°"><line x1="210" y1="130" x2="210" y2="30" className="geo-result"/><line x1="210" y1="130" x2="345" y2="110" className="geo-result"/><line x1="210" y1="130" x2="285" y2="230" className="geo-result"/><line x1="210" y1="130" x2="75" y2="205" className="geo-result"/><line x1="210" y1="130" x2="80" y2="65" className="geo-result"/><text x="250" y="77">70°</text><text x="282" y="165">85°</text><text x="203" y="213">95°</text><text x="113" y="151">60°</text><text x="145" y="78">x</text><circle cx="210" cy="130" r="4" className="geo-fill"/></Fig>}
function Adjacent(){return <Fig label="Adjacent angles share a vertex and one common arm without overlapping"><line x1="70" y1="210" x2="205" y2="125" className="geo-result"/><line x1="205" y1="125" x2="205" y2="35" className="geo-result"/><line x1="205" y1="125" x2="350" y2="195" className="geo-result"/><path d="M170 147 A42 42 0 0 1 205 83 M205 83 A42 42 0 0 1 243 143" className="angle-arc"/><text x="163" y="103">a</text><text x="242" y="105">b</text><text x="198" y="139">O</text></Fig>}
function Parallel({mode}:{mode:'corresponding'|'alternate'}){return <Fig label={mode==='corresponding'?'Corresponding angles occupy matching corners when a transversal crosses parallel lines':'Alternate angles lie between the parallel lines on opposite sides of the transversal'}><line x1="55" y1="75" x2="365" y2="75" className="geo-result"/><line x1="55" y1="205" x2="365" y2="205" className="geo-result"/><line x1="115" y1="245" x2="300" y2="30" className="geo-result"/><path d="M185 70l12 5-12 5 M185 200l12 5-12 5" className="geo-mark"/>{mode==='corresponding'?<><path d="M250 75 A34 34 0 0 0 228 101 M138 205 A34 34 0 0 0 160 179" className="angle-highlight"/><text x="251" y="109">72°</text><text x="125" y="174">x</text></>:<><path d="M228 101 A34 34 0 0 1 204 75 M160 179 A34 34 0 0 1 184 205" className="angle-highlight"/><text x="198" y="111">64°</text><text x="175" y="171">x</text></>}</Fig>}

export default function AnglesLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson geometry-premium-lesson angles-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS · MENSURATION & GEOMETRY</span><h1>Angles</h1><p>Measure, recognise and reason with angles. AVORA will show exactly what the diagram is telling you, which property applies, and why each calculation is valid.</p></header>
<section className="wn-objectives"><h2>NERDC-Aligned Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>

<section className="wn-section"><h3>1. What Is an Angle?</h3><BasicAngle/><p>An angle measures the amount of turn between two rays or line segments meeting at a common point. The common point is the <b>vertex</b>; the two lines forming the angle are its <b>arms</b>.</p><div className="lesson-rule"><span>∠AOB means the angle with vertex O.</span><span>The middle letter names the vertex.</span><span>Angles are measured in degrees, written °.</span></div></section>

<section className="wn-section"><h3>2. Measuring an Angle with a Protractor</h3><Protractor/><div className="lesson-rule"><span><b>Step 1:</b> place the protractor centre exactly on the vertex.</span><span><b>Step 2:</b> align its 0° baseline with one arm.</span><span><b>Step 3:</b> start reading from the 0° on that same arm.</span><span><b>Step 4:</b> read where the other arm crosses the scale.</span><span><b>Step 5:</b> sense-check whether the measured angle looks smaller than, equal to, or larger than a right angle.</span></div><Work q="The second arm crosses the correct protractor scale at 55°. What is the measured angle?"><Line>The protractor centre is on the vertex.</Line><Line>The starting arm is aligned with 0°.</Line><Line>The other arm crosses at 55°.</Line><Line strong>Angle = 55°</Line><Line>Check: 55° is less than 90°, and the diagram indeed shows an angle smaller than a right angle. ✓</Line></Work></section>

<section className="wn-section"><h3>3. Adjacent Angles</h3><Adjacent/><p>Adjacent angles lie next to each other. They have the same vertex and share one common arm, but their interiors do not overlap.</p><div className="lesson-rule"><span>Being adjacent does <b>not</b> automatically mean the angles are equal.</span><span>If adjacent angles also lie on a straight line, then their sum is 180°.</span></div></section>

<section className="wn-section"><h3>4. Vertically Opposite Angles</h3><Vertical/><p>When two straight lines intersect, the angles directly opposite each other are called vertically opposite angles. Each opposite pair is equal.</p><Work q="In the diagram, x is vertically opposite 68°. Find x."><Line>Vertically opposite angles are equal.</Line><Line>x = 68°</Line><Line strong>x = 68°</Line><Line>Reason: x and 68° lie directly opposite each other at the same intersection. ✓</Line></Work></section>

<section className="wn-section"><h3>5. Angles on a Straight Line</h3><Straight/><p>A straight angle is 180°. Therefore adjacent angles that together form a straight line add to 180°.</p><Work q="125° and x are adjacent angles on a straight line. Find x."><Line>125° + x = 180°</Line><Line>x = 180° − 125°</Line><Line strong>x = 55°</Line><Line>Check: 125° + 55° = 180°. ✓</Line></Work></section>

<section className="wn-section"><h3>6. Angles at a Point</h3><AtPoint/><p>One complete turn around a point is 360°. So all the angles meeting around the same point add to 360°.</p><Work q="Angles around O are 70°, 85°, 95°, 60° and x. Find x."><Line>70° + 85° + 95° + 60° + x = 360°</Line><Line>310° + x = 360°</Line><Line>x = 360° − 310°</Line><Line strong>x = 50°</Line><Line>Check: 70 + 85 + 95 + 60 + 50 = 360°. ✓</Line></Work></section>

<section className="wn-section"><h3>7. Parallel Lines and a Transversal</h3><p>Before corresponding and alternate angles make sense, identify the diagram correctly. The two lines marked with matching arrows are parallel. The third line crossing both is called a <b>transversal</b>.</p><div className="lesson-rule"><span><b>Important:</b> the equal-angle rules below depend on the two lines being parallel.</span><span>Never assume lines are parallel just because they look parallel. Look for the arrow marks or a statement in the question.</span></div></section>

<section className="wn-section"><h3>8. Corresponding Angles</h3><Parallel mode="corresponding"/><p>Corresponding angles occupy matching positions at the two intersections of a transversal with parallel lines. A useful visual idea is “same corner”. Corresponding angles are equal when the lines are parallel.</p><Work q="The marked angles are corresponding. One is 72°. Find x."><Line>The two horizontal lines are parallel.</Line><Line>x and 72° are corresponding angles.</Line><Line>Corresponding angles between parallel lines are equal.</Line><Line strong>x = 72°</Line></Work></section>

<section className="wn-section"><h3>9. Alternate Angles</h3><Parallel mode="alternate"/><p>Alternate angles lie between the parallel lines and on opposite sides of the transversal. A useful visual idea is a “Z” shape. Alternate angles are equal when the lines are parallel.</p><Work q="The marked alternate angle is 64°. Find x."><Line>The two horizontal lines are parallel.</Line><Line>x and 64° are alternate angles.</Line><Line>Alternate angles between parallel lines are equal.</Line><Line strong>x = 64°</Line></Work></section>

<section className="wn-section"><h3>10. Do Not Mix Up the Relationships</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>Relationship</th><th>How to recognise it</th><th>Property used</th></tr></thead><tbody><tr><td>Adjacent</td><td>Beside each other; common vertex and arm</td><td>No automatic equality</td></tr><tr><td>Vertically opposite</td><td>Directly opposite at an intersection</td><td>Equal</td></tr><tr><td>Corresponding</td><td>Matching corners across a transversal</td><td>Equal if lines are parallel</td></tr><tr><td>Alternate</td><td>Between parallel lines, opposite sides of transversal</td><td>Equal if lines are parallel</td></tr><tr><td>Straight line</td><td>Angles together make a straight line</td><td>Sum = 180°</td></tr><tr><td>At a point</td><td>Angles complete one turn around a point</td><td>Sum = 360°</td></tr></tbody></table></div></section>

<section className="wn-section"><h3>11. Multi-Step Worked Example</h3><Vertical/><Work q="At an intersection, one angle is 68°. Find the vertically opposite angle and either adjacent angle."><Line>Step 1: vertically opposite angle = 68°.</Line><Line>Step 2: an adjacent angle and 68° form a straight line.</Line><Line>68° + adjacent angle = 180°</Line><Line>Adjacent angle = 180° − 68°</Line><Line strong>Adjacent angle = 112°</Line><Line>Check: the other vertically opposite pair is therefore also 112°. Around the point: 68 + 112 + 68 + 112 = 360°. ✓</Line></Work></section>

<section className="wn-section"><h3>12. Real-Life Angle Situations</h3><div className="lesson-rule"><span><b>Road intersection:</b> crossing straight roads model vertically opposite angles.</span><span><b>Railway tracks crossed by a road:</b> parallel rails and the crossing road model a transversal with corresponding/alternate angles.</span><span><b>Clock hands:</b> two hands form an angle at the centre.</span><span><b>Door opening:</b> the amount a door turns from its closed position forms an angle.</span><span><b>Straight road:</b> opposite directions along one straight road form 180°.</span></div></section>

<section className="wn-section"><h3>13. Common Mistakes</h3><div className="lesson-rule"><span><b>Wrong protractor scale:</b> begin from the 0° lying on the starting arm.</span><span><b>Wrong vertex:</b> in ∠ABC, B is the vertex because it is the middle letter.</span><span><b>Adjacent ≠ equal:</b> adjacent only describes position.</span><span><b>Corresponding/alternate:</b> equality requires parallel lines.</span><span><b>Straight line:</b> use 180°, not 360°.</span><span><b>At a point:</b> use 360°, not 180°.</span><span><b>No reason given:</b> in angle problems, state the property before calculating.</span></div></section>

<section className="wn-section"><h3>14. AVORA Angle-Solving Method</h3><div className="lesson-rule"><span><b>1. LOOK:</b> identify the lines, vertex, arrow marks and angle labels.</span><span><b>2. NAME:</b> decide the relationship—vertical, adjacent, corresponding, alternate, straight line or point.</span><span><b>3. STATE:</b> write the property in words.</span><span><b>4. EQUATE:</b> write the correct equality or sum.</span><span><b>5. SOLVE:</b> show every arithmetic/algebra step.</span><span><b>6. ANSWER:</b> include the degree symbol.</span><span><b>7. CHECK:</b> test the answer against 180°, 360° or the relevant equality.</span></div></section>

<section className="wn-section"><h3>15. Mastery Check</h3><p>You have mastered the NERDC JSS1 Angles objective when you can measure a given angle correctly with a protractor; identify adjacent, vertically opposite, corresponding and alternate angles from an appropriate diagram; state the property you are using; solve unknown angles on straight lines and around a point; and connect these angle relationships to real-life situations.</p></section>

<div className="lesson-action"><button type="button" className="primary-btn" onClick={onExercise}>Go to Exercise →</button></div>
</article>}
