'use client';
import {useEffect,useState} from 'react';

export default function AssignmentReviewClient(){
 const [data,setData]=useState<any>({students:[],questions:[]}),[student,setStudent]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(id=student){setBusy(true);setError('');try{const r=await fetch('/api/admin/assignment-review'+(id?'?studentId='+encodeURIComponent(id):''),{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load('')},[]);
 async function save(q:any,form:HTMLFormElement){const fd=new FormData(form),type=String(fd.get('type')),options=[1,2,3,4].map(n=>String(fd.get('option'+n)||'').trim()).filter(Boolean);let rubric:any[]=[];try{rubric=JSON.parse(String(fd.get('rubric')||'[]'))}catch{return setError('Rubric must be valid JSON, for example [{"point":"Correct method","marks":2}].')}setBusy(true);setError('');try{const r=await fetch('/api/admin/assignment-review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:q.id,curriculumTopicId:String(fd.get('topic')),questionType:type,options,correctAnswer:String(fd.get('correct')||''),rubric,maxMarks:Number(fd.get('maxMarks')||0),modelSolution:String(fd.get('solution')||'')})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load(student)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function confirm(q:any,form:HTMLFormElement){const topic=String(new FormData(form).get('topic')||'');setBusy(true);setError('');try{const r=await fetch('/api/assignments/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:q.id,curriculumTopicId:topic})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load(student)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="assignment-review-console"><header><span className="section-kicker">ACADEMIC REVIEW QUEUE</span><h2>Nothing enters revision without a human-checkable academic record.</h2><p>The learner’s original wording is locked. Review the curriculum match, assessment form, answer/rubric and worked solution; then confirm it for future resurfacing.</p></header>{error&&<p className="form-error">{error}</p>}<div className="review-student-picker"><select value={student} onChange={e=>{setStudent(e.target.value);load(e.target.value)}}><option value="">Choose a learner</option>{data.students.map((s:any)=><option key={s.id} value={s.id}>{s.full_name} · {s.class_level} · {s.retained_question_count} questions</option>)}</select></div>{busy&&<p>Updating academic record…</p>}{student&&data.questions.map((q:any)=><form key={q.id} className={q.needs_confirmation?'assignment-review-card needs-review':'assignment-review-card confirmed'} onSubmit={e=>{e.preventDefault();save(q,e.currentTarget)}}><div className="review-original"><small>ORIGINAL SCHOOL QUESTION · LOCKED</small><p>{q.original_text}</p><span>{q.label||'School work'} · {q.subject_name}</span></div><div className="review-grid"><label>Curriculum topic ID<input name="topic" defaultValue={q.curriculum_topic_id||''} required/></label><label>Assessment form<select name="type" defaultValue={q.question_type}><option value="MULTIPLE_CHOICE">Multiple choice</option><option value="THEORY">Theory</option></select></label></div><fieldset><legend>MCQ options</legend>{[0,1,2,3].map(n=><input key={n} name={'option'+(n+1)} defaultValue={q.options?.[n]||''} placeholder={'Option '+(n+1)}/>)}<label>Correct answer<input name="correct" defaultValue={q.correct_answer||''}/></label></fieldset><fieldset><legend>Theory marking</legend><label>Maximum marks<input name="maxMarks" type="number" min="1" defaultValue={q.max_marks||''}/></label><label>Rubric JSON<textarea name="rubric" rows={4} defaultValue={q.rubric?JSON.stringify(q.rubric,null,2):'[]'}/></label></fieldset><label>Worked model solution<textarea name="solution" rows={7} defaultValue={q.model_solution||''} required/></label><div className="review-meta"><span>{q.classification_confidence}</span><span>{q.attempt_count} attempts</span><span>{q.resurfaced_count} resurfacing events</span><span>{q.next_review_at?'Next '+new Date(q.next_review_at).toLocaleDateString():'Not scheduled'}</span></div><div className="review-actions"><button type="submit" disabled={busy}>Save reviewed content</button>{q.needs_confirmation?<button type="button" disabled={busy} onClick={e=>confirm(q,e.currentTarget.form!)}>Confirm for revision</button>:<strong>Confirmed for revision ✓</strong>}</div></form>)}</section>
}
