'use client';
const objectives=['recall binary place values using powers of 2','state and explain the four binary multiplication facts','multiply binary numbers by 0₂ and 1₂','multiply multi-digit binary numbers vertically','explain why shifting left multiplies a binary value by 2','form and align partial products by place value','add partial products using binary addition','verify products with complete powers-of-two conversions','identify and correct common binary-multiplication errors'];
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
function Multiply({top,bottom,partials=[],answer}:{top:string;bottom:string;partials?:string[];answer:string}){return <div className="column-operation binary-multiplication" aria-label={top+' multiplied by '+bottom+' equals '+answer}><div className="column-operands"><div className="column-row"><span className="column-sign"></span><span>{top}</span></div><div className="column-row"><span className="column-sign">×</span><span>{bottom}</span></div></div>{partials.length>0&&<div className="column-partials">{partials.map((p,i)=><div className="column-row" key={i}><span className="column-sign">{i===partials.length-1?'+':''}</span><span>{p}</span></div>)}</div>}<div className="column-answer"><span className="column-sign"></span><span>{answer}</span></div></div>}
function Convert({binary,powers,values,total}:{binary:string;powers:string;values:string;total:string}){return <div className="math-working"><Line>{binary}</Line><Line>= {powers}</Line><Line>= {values}</Line><Line strong>= {total}</Line></div>}
export default function BinaryMultiplicationLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson binary-addition-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS</span><h1>Multiplication of Numbers in Base Two</h1><p>Multiply binary numbers vertically, align every partial product by place value, and verify every result with complete conversion working.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>
<section className="wn-section"><h3>1. Recall Binary Place Value</h3><p>From right to left, binary places are 2⁰, 2¹, 2², 2³, 2⁴, ... with values 1, 2, 4, 8, 16, ... .</p><Convert binary="101₂" powers="(1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="4 + 0 + 1" total="5₁₀"/></section>
<section className="wn-section"><h3>2. Binary Multiplication Facts</h3><div className="lesson-rule"><span>0 × 0 = 0</span><span>0 × 1 = 0</span><span>1 × 0 = 0</span><span>1 × 1 = 1</span></div><p>Binary has only the digits 0 and 1, so these four facts are enough for every binary multiplication.</p></section>
<section className="wn-section"><h3>3. Multiplying by Zero and One</h3><Work q="Multiply 101₂ by 0₂."><Multiply top="101₂" bottom="0₂" answer="000₂"/><Line strong>101₂ × 0₂ = 0₂</Line></Work><Work q="Multiply 101₂ by 1₂."><Multiply top="101₂" bottom="1₂" answer="101₂"/><Line>1 × 1 = 1; 1 × 0 = 0; 1 × 1 = 1.</Line><Line strong>101₂ × 1₂ = 101₂</Line></Work><h4>Check every conversion</h4><Convert binary="101₂" powers="(1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="4 + 0 + 1" total="5₁₀"/><Convert binary="1₂" powers="1 × 2⁰" values="1 × 1" total="1₁₀"/><Line>5 × 1 = 5</Line></section>
<section className="wn-section"><h3>4. Multiplying by 10₂</h3><Work q="Multiply 101₂ by 10₂."><Multiply top="101₂" bottom="10₂" partials={['000₂','1010₂']} answer="1010₂"/><Line>The rightmost 0 gives a zero partial product.</Line><Line>The next digit is 1 in the 2¹ place, so 101₂ × 1₂ is shifted one place left: 1010₂.</Line><Line strong>101₂ × 10₂ = 1010₂</Line></Work><p>The left shift is place value, not a decorative zero: every digit moves to a place worth twice as much.</p><h4>Check every conversion</h4><Convert binary="101₂" powers="(1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="4 + 0 + 1" total="5₁₀"/><Convert binary="10₂" powers="(1 × 2¹) + (0 × 2⁰)" values="2 + 0" total="2₁₀"/><Line>5 × 2 = 10</Line><Convert binary="1010₂" powers="(1 × 2³) + (0 × 2²) + (1 × 2¹) + (0 × 2⁰)" values="8 + 0 + 2 + 0" total="10₁₀"/></section>
<section className="wn-section"><h3>5. Multi-Digit Vertical Multiplication</h3><Work q="Multiply 101₂ by 11₂."><Multiply top="101₂" bottom="11₂" partials={['0101₂','1010₂']} answer="1111₂"/><Line>Rightmost 1: 101₂ × 1₂ = 101₂.</Line><Line>Next 1 is in the 2¹ place: 101₂ × 1₂ = 101₂, shifted one place left → 1010₂.</Line><Line>Add the vertically aligned partial products using binary addition.</Line><Line strong>101₂ × 11₂ = 1111₂</Line></Work><h4>Check every conversion</h4><Convert binary="101₂" powers="(1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="4 + 0 + 1" total="5₁₀"/><Convert binary="11₂" powers="(1 × 2¹) + (1 × 2⁰)" values="2 + 1" total="3₁₀"/><Line>5 × 3 = 15</Line><Convert binary="1111₂" powers="(1 × 2³) + (1 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="8 + 4 + 2 + 1" total="15₁₀"/></section>
<section className="wn-section"><h3>6. A Multiplier Containing Zero</h3><Work q="Multiply 110₂ by 101₂."><Multiply top="00110₂" bottom="00101₂" partials={['00110₂','00000₂','11000₂']} answer="11110₂"/><Line>Rightmost 1 gives 00110₂.</Line><Line>The middle 0 gives 00000₂.</Line><Line>The leftmost 1 is in the 2² place, so shift 110₂ two places left → 11000₂.</Line><Line>Add all partial products vertically.</Line><Line strong>110₂ × 101₂ = 11110₂</Line></Work><h4>Check every conversion</h4><Convert binary="110₂" powers="(1 × 2²) + (1 × 2¹) + (0 × 2⁰)" values="4 + 2 + 0" total="6₁₀"/><Convert binary="101₂" powers="(1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="4 + 0 + 1" total="5₁₀"/><Line>6 × 5 = 30</Line><Convert binary="11110₂" powers="(1 × 2⁴) + (1 × 2³) + (1 × 2²) + (1 × 2¹) + (0 × 2⁰)" values="16 + 8 + 4 + 2 + 0" total="30₁₀"/></section>
<section className="wn-section"><h3>7. Another Vertical Example</h3><Work q="Multiply 111₂ by 10₂."><Multiply top="111₂" bottom="10₂" partials={['0000₂','1110₂']} answer="1110₂"/><Line>Rightmost 0 gives 0.</Line><Line>The 1 in the 2¹ place gives 111₂ shifted one place left → 1110₂.</Line><Line strong>111₂ × 10₂ = 1110₂</Line></Work><h4>Check every conversion</h4><Convert binary="111₂" powers="(1 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="4 + 2 + 1" total="7₁₀"/><Convert binary="10₂" powers="(1 × 2¹) + (0 × 2⁰)" values="2 + 0" total="2₁₀"/><Line>7 × 2 = 14</Line><Convert binary="1110₂" powers="(1 × 2³) + (1 × 2²) + (1 × 2¹) + (0 × 2⁰)" values="8 + 4 + 2 + 0" total="14₁₀"/></section>
<section className="wn-section"><h3>8. Larger Vertical Multiplication</h3><Work q="Multiply 1011₂ by 11₂."><Multiply top="01011₂" bottom="00011₂" partials={['01011₂','10110₂']} answer="100001₂"/><Line>Rightmost 1 gives 01011₂.</Line><Line>The next 1 is in the 2¹ place, so shift 1011₂ one place left → 10110₂.</Line><Line>Add the partial products using binary addition.</Line><Line strong>1011₂ × 11₂ = 100001₂</Line></Work><h4>Check every conversion</h4><Convert binary="1011₂" powers="(1 × 2³) + (0 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="8 + 0 + 2 + 1" total="11₁₀"/><Convert binary="11₂" powers="(1 × 2¹) + (1 × 2⁰)" values="2 + 1" total="3₁₀"/><Line>11 × 3 = 33</Line><Convert binary="100001₂" powers="(1 × 2⁵) + (0 × 2⁴) + (0 × 2³) + (0 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="32 + 0 + 0 + 0 + 0 + 1" total="33₁₀"/></section>
<section className="wn-section"><h3>9. Why Partial Products Shift</h3><p>Multiplier digits occupy 2⁰, 2¹, 2², ... places. A partial product from 2⁰ starts normally; from 2¹ it shifts one place left; from 2² it shifts two places left. The shift represents place value.</p></section>
<section className="wn-section"><h3>Common Misconceptions</h3><div className="lesson-rule"><span><b>Use binary facts only.</b> The digits are 0 and 1.</span><span><b>Multiply vertically.</b> Every worked multiplication keeps the factors and partial products in aligned columns.</span><span><b>Shift each new partial product.</b> Moving left in the multiplier changes place value.</span><span><b>Align partial products correctly.</b> Misalignment changes the value.</span><span><b>Add partial products in binary.</b> Remember 1+1=10₂ and 1+1+1=11₂.</span><span><b>Horizontal rules belong after complete groups.</b> Both factors first; then the rule. Partial products are then stacked vertically and the answer follows their addition rule.</span><span><b>Never skip conversion working.</b> Show digit × power of 2, evaluate, add, then state the decimal value.</span></div></section>
<section className="wn-section"><h3>AVORA Binary Multiplication Method</h3><div className="lesson-rule"><span>1. Arrange both factors vertically and align them from the right.</span><span>2. Put × on the final operand, then draw the first horizontal rule.</span><span>3. Multiply by the rightmost multiplier digit first.</span><span>4. Write every partial product vertically.</span><span>5. Shift each new partial product one additional place left.</span><span>6. After all partial products are stacked, add them vertically using binary addition.</span><span>7. State the product below the final rule.</span><span>8. Verify both factors and the product using complete powers-of-two conversions.</span></div></section>
<section className="wn-section"><h3>Mastery Check</h3><ul><li>State all four binary multiplication facts.</li><li>Explain why multiplying by 10₂ shifts a number one place left.</li><li>Multiply binary numbers using genuine vertical working.</li><li>Form and align partial products correctly.</li><li>Add partial products using binary addition.</li><li>Verify the result using complete powers-of-two conversion working.</li></ul></section>
<div className="teacher-actions"><button type="button" className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}