'use client';
const objectives=['recall binary place values using powers of 2','explain the basic rules of binary subtraction','subtract binary numbers without borrowing','explain why borrowing 1 gives 10₂ in the next lower place','subtract binary numbers involving borrowing','handle borrowing across zero correctly','arrange binary subtraction vertically with one rule after the final operand','check answers with complete powers-of-two conversions','identify and correct common binary-subtraction errors'];
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
function Sub({top,bottom,answer}:{top:string;bottom:string;answer:string}){return <div className="column-operation" aria-label={top+' minus '+bottom+' equals '+answer}><div className="column-operands"><div className="column-row"><span className="column-sign"></span><span>{top}</span></div><div className="column-row"><span className="column-sign">−</span><span>{bottom}</span></div></div><div className="column-answer"><span className="column-sign"></span><span>{answer}</span></div></div>}
function Convert({binary,powers,values,total}:{binary:string;powers:string;values:string;total:string}){return <div className="math-working"><Line>{binary}</Line><Line>= {powers}</Line><Line>= {values}</Line><Line strong>= {total}</Line></div>}
export default function BinarySubtractionLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson binary-addition-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS</span><h1>Subtraction of Numbers in Base Two</h1><p>Subtract vertically, borrow correctly in base two, and verify every result with complete conversion working.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>
<section className="wn-section"><h3>1. Recall the Place Values</h3><p>From right to left, binary place values are 2⁰, 2¹, 2², 2³, 2⁴, ... with values 1, 2, 4, 8, 16, ... .</p><Convert binary="1101₂" powers="(1 × 2³) + (1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="8 + 4 + 0 + 1" total="13₁₀"/></section>
<section className="wn-section"><h3>2. Basic Binary Subtraction Rules</h3><div className="lesson-rule"><span>0 − 0 = 0</span><span>1 − 0 = 1</span><span>1 − 1 = 0</span></div><p>When we meet 0 − 1, we must borrow from the next available binary place.</p></section>
<section className="wn-section"><h3>3. What Borrowing Means in Base Two</h3><p>In base ten, borrowing 1 from the next place gives ten units of the current place. In base two, borrowing 1 from the next place gives <b>10₂</b> in the current place.</p><div className="math-working"><Line>10₂ = 2₁₀</Line><Line>10₂ − 1₂ = 1₂</Line><Line strong>So for 0 − 1, borrow 1 from the next available binary place.</Line></div></section>
<section className="wn-section"><h3>4. Subtraction Without Borrowing</h3><Work q="Subtract 101₂ from 111₂."><Sub top="111₂" bottom="101₂" answer="010₂"/><Line>Right: 1 − 1 = 0</Line><Line>Middle: 1 − 0 = 1</Line><Line>Left: 1 − 1 = 0</Line><Line strong>111₂ − 101₂ = 010₂ = 10₂</Line></Work><h4>Check every conversion</h4><Convert binary="111₂" powers="(1 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="4 + 2 + 1" total="7₁₀"/><Convert binary="101₂" powers="(1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="4 + 0 + 1" total="5₁₀"/><Sub top="7" bottom="5" answer="2"/><Convert binary="010₂" powers="(0 × 2²) + (1 × 2¹) + (0 × 2⁰)" values="0 + 2 + 0" total="2₁₀"/></section>
<section className="wn-section"><h3>5. Subtraction With Borrowing</h3><Work q="Subtract 1₂ from 10₂."><Sub top="10₂" bottom="01₂" answer="01₂"/><Line>Right: 0 − 1 cannot be done directly.</Line><Line>Borrow 1 from the next column; in this column it becomes 10₂.</Line><Line>10₂ − 1₂ = 1₂.</Line><Line>The lending 1 has been used, so the left column becomes 0.</Line><Line strong>10₂ − 01₂ = 01₂ = 1₂</Line></Work><h4>Check every conversion</h4><Convert binary="10₂" powers="(1 × 2¹) + (0 × 2⁰)" values="2 + 0" total="2₁₀"/><Convert binary="01₂" powers="(0 × 2¹) + (1 × 2⁰)" values="0 + 1" total="1₁₀"/><Sub top="2" bottom="1" answer="1"/></section>
<section className="wn-section"><h3>6. Borrowing in a Larger Number</h3><Work q="Subtract 11₂ from 101₂."><Sub top="101₂" bottom="011₂" answer="010₂"/><Line>Right: 1 − 1 = 0.</Line><Line>Middle: 0 − 1 requires borrowing from the left.</Line><Line>The borrowed 1 becomes 10₂ in the middle column.</Line><Line>10₂ − 1₂ = 1₂; the leftmost lending 1 becomes 0.</Line><Line strong>101₂ − 011₂ = 010₂ = 10₂</Line></Work><h4>Check every conversion</h4><Convert binary="101₂" powers="(1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="4 + 0 + 1" total="5₁₀"/><Convert binary="011₂" powers="(0 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="0 + 2 + 1" total="3₁₀"/><Sub top="5" bottom="3" answer="2"/><Convert binary="010₂" powers="(0 × 2²) + (1 × 2¹) + (0 × 2⁰)" values="0 + 2 + 0" total="2₁₀"/></section>
<section className="wn-section"><h3>7. Borrowing Across a Zero</h3><Work q="Subtract 1₂ from 100₂."><Sub top="100₂" bottom="001₂" answer="011₂"/><Line>Right: 0 − 1 requires borrowing, but the next column is also 0.</Line><Line>Move left to the first available 1. The 1 in the 2² place lends one group to the 2¹ place.</Line><Line>That gives 10₂ groups in the 2¹ place. One of those groups is passed to the 2⁰ place, leaving 1 in the 2¹ place.</Line><Line>The rightmost place now has 10₂, so 10₂ − 1₂ = 1₂.</Line><Line>Middle: 1 − 0 = 1. Left: 0 − 0 = 0.</Line><Line strong>100₂ − 001₂ = 011₂ = 11₂</Line></Work><h4>Check every conversion</h4><Convert binary="100₂" powers="(1 × 2²) + (0 × 2¹) + (0 × 2⁰)" values="4 + 0 + 0" total="4₁₀"/><Convert binary="001₂" powers="(0 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="0 + 0 + 1" total="1₁₀"/><Sub top="4" bottom="1" answer="3"/><Convert binary="011₂" powers="(0 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="0 + 2 + 1" total="3₁₀"/></section>
<section className="wn-section"><h3>8. Larger Example</h3><Work q="Subtract 1011₂ from 1101₂."><Sub top="1101₂" bottom="1011₂" answer="0010₂"/><Line>First: 1 − 1 = 0.</Line><Line>Second: 0 − 1 requires borrowing. Borrow from the next 1; 10₂ − 1₂ = 1₂.</Line><Line>The lending column becomes 0, so third: 0 − 0 = 0.</Line><Line>Fourth: 1 − 1 = 0.</Line><Line strong>1101₂ − 1011₂ = 0010₂ = 10₂</Line></Work><h4>Check every conversion</h4><Convert binary="1101₂" powers="(1 × 2³) + (1 × 2²) + (0 × 2¹) + (1 × 2⁰)" values="8 + 4 + 0 + 1" total="13₁₀"/><Convert binary="1011₂" powers="(1 × 2³) + (0 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="8 + 0 + 2 + 1" total="11₁₀"/><Sub top="13" bottom="11" answer="2"/><Convert binary="0010₂" powers="(0 × 2³) + (0 × 2²) + (1 × 2¹) + (0 × 2⁰)" values="0 + 0 + 2 + 0" total="2₁₀"/></section>
<section className="wn-section"><h3>9. Align Numbers From the Right</h3><Work q="Subtract 11₂ from 1010₂."><Line>Write 11₂ as 0011₂ so equal place values line up.</Line><Sub top="1010₂" bottom="0011₂" answer="0111₂"/><Line strong>1010₂ − 0011₂ = 0111₂</Line></Work><h4>Check every conversion</h4><Convert binary="1010₂" powers="(1 × 2³) + (0 × 2²) + (1 × 2¹) + (0 × 2⁰)" values="8 + 0 + 2 + 0" total="10₁₀"/><Convert binary="0011₂" powers="(0 × 2³) + (0 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="0 + 0 + 2 + 1" total="3₁₀"/><Sub top="10" bottom="3" answer="7"/><Convert binary="0111₂" powers="(0 × 2³) + (1 × 2²) + (1 × 2¹) + (1 × 2⁰)" values="0 + 4 + 2 + 1" total="7₁₀"/></section>
<section className="wn-section"><h3>Common Misconceptions</h3><div className="lesson-rule"><span><b>Borrow in base two, not base ten.</b> A borrowed unit becomes 10₂ in the next lower place.</span><span><b>Reduce the lending column.</b> You cannot borrow and leave it unchanged.</span><span><b>A zero cannot lend.</b> Move left to the next available 1 and regroup through intervening zeros.</span><span><b>Align from the right.</b> Equal place values must be in the same column.</span><span><b>One line only.</b> Both numbers first, then the horizontal rule after the number being subtracted, then the answer.</span><span><b>Never skip conversion working.</b> Show digit × power of 2, evaluate, add, then state the base-ten value.</span></div></section>
<section className="wn-section"><h3>AVORA Binary Subtraction Method</h3><div className="lesson-rule"><span>1. Align the numbers from the right.</span><span>2. Write the number being subtracted underneath and put − on that final operand.</span><span>3. Draw one horizontal line only after the final operand.</span><span>4. Start from the rightmost column.</span><span>5. Use 0−0=0, 1−0=1 and 1−1=0.</span><span>6. For 0−1, borrow from the next available binary place; the borrowed unit becomes 10₂ in the lower place.</span><span>7. Regroup carefully across zeros and reduce every lending place correctly.</span><span>8. Verify by showing complete powers-of-two conversions.</span></div></section>
<section className="wn-section"><h3>Mastery Check</h3><ul><li>Explain why 10₂ − 1₂ = 1₂.</li><li>Subtract with and without borrowing.</li><li>Borrow correctly across a zero.</li><li>Align numbers of different lengths from the right.</li><li>Use one horizontal rule only after the final operand.</li><li>Show complete powers-of-two conversion working when checking answers.</li></ul></section>
<div className="teacher-actions"><button type="button" className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}