'use client';
import React from 'react';
const objectives=['explain geometrical construction as accurate drawing','use a ruler, set square, compass and sharp pencil correctly','construct a line parallel to a given line','construct a line perpendicular to a given line','bisect a given line segment accurately','construct a 60° angle with ruler and compass','construct a 90° angle with ruler and compass','retain construction marks and verify each completed construction'];
function Fig({label,children}:{label:string;children:React.ReactNode}){return <figure className="geometry-figure construction-figure"><svg viewBox="0 0 420 250" role="img" aria-label={label}>{children}</svg><figcaption>{label}</figcaption></figure>}
function Step({n,title,children,fig}:{n:number;title:string;children:React.ReactNode;fig:React.ReactNode}){return <div className="construction-step"><div className="construction-step-head"><b>{n}</b><div><small>STEP {n}</small><h4>{title}</h4></div></div><div className="construction-step-body"><p>{children}</p>{fig}</div></div>}
function BaseLine({a='A',b='B'}:{a?:string;b?:string}){return <><line x1="65" y1="155" x2="355" y2="155" className="geo-line"/><circle cx="100" cy="155" r="3" className="geo-fill"/><circle cx="320" cy="155" r="3" className="geo-fill"/><text x="94" y="178">{a}</text><text x="316" y="178">{b}</text></>}
function BisectFig({stage}:{stage:number}){return <Fig label={stage===1?'Begin with line segment AB':stage===2?'Draw equal-radius arcs from A':stage===3?'Without changing the compass, draw arcs from B':'Join the arc intersections P and Q; M is the midpoint'}><BaseLine/>{stage>=2&&<><path d="M100 155 A150 150 0 0 1 205 35 M100 155 A150 150 0 0 0 205 235" className="geo-arc"/></>}{stage>=3&&<><path d="M320 155 A150 150 0 0 0 215 35 M320 155 A150 150 0 0 1 215 235" className="geo-arc"/><circle cx="210" cy="39" r="4" className="geo-fill"/><circle cx="210" cy="231" r="4" className="geo-fill"/><text x="218" y="42">P</text><text x="218" y="235">Q</text></>}{stage>=4&&<><line x1="210" y1="35" x2="210" y2="235" className="geo-result"/><circle cx="210" cy="155" r="4" className="geo-fill"/><text x="216" y="148">M</text><path d="M210 155h15v-15" className="geo-mark"/></>}</Fig>}
function SixtyFig({stage}:{stage:number}){return <Fig label={stage===1?'Draw ray AB':stage===2?'With A as centre, draw an arc through B':stage===3?'With B as centre and the same radius, cut the first arc at C':'Join A to C; angle BAC is 60°'}><line x1="70" y1="190" x2="355" y2="190" className="geo-line"/><circle cx="105" cy="190" r="3" className="geo-fill"/><circle cx="235" cy="190" r="3" className="geo-fill"/><text x="98" y="214">A</text><text x="230" y="214">B</text>{stage>=2&&<path d="M235 190 A130 130 0 0 0 40 77" className="geo-arc"/>}{stage>=3&&<><path d="M235 190 A130 130 0 0 0 170 77" className="geo-arc"/><circle cx="170" cy="77" r="4" className="geo-fill"/><text x="177" y="72">C</text></>}{stage>=4&&<><line x1="105" y1="190" x2="170" y2="77" className="geo-result"/><path d="M145 190 A40 40 0 0 0 125 155" className="geo-mark"/><text x="145" y="157">60°</text></>}</Fig>}
function NinetyFig({stage}:{stage:number}){return <Fig label={stage===1?'Draw a straight line through A':stage===2?'Mark equal points P and Q on both sides of A':stage===3?'Draw equal arcs from P and Q to meet at R':'Join A to R; the new line is perpendicular and makes 90°'}><line x1="45" y1="190" x2="375" y2="190" className="geo-line"/><circle cx="210" cy="190" r="4" className="geo-fill"/><text x="204" y="214">A</text>{stage>=2&&<><circle cx="120" cy="190" r="4" className="geo-fill"/><circle cx="300" cy="190" r="4" className="geo-fill"/><text x="113" y="214">P</text><text x="294" y="214">Q</text><path d="M120 190 A90 90 0 0 1 210 100 M300 190 A90 90 0 0 0 210 100" className="geo-arc"/></>}{stage>=3&&<><path d="M120 190 A145 145 0 0 1 210 52 M300 190 A145 145 0 0 0 210 52" className="geo-arc"/><circle cx="210" cy="52" r="4" className="geo-fill"/><text x="218" y="50">R</text></>}{stage>=4&&<><line x1="210" y1="52" x2="210" y2="225" className="geo-result"/><path d="M210 190h18v-18" className="geo-mark"/><text x="235" y="174">90°</text></>}</Fig>}
function ParallelFig({stage}:{stage:number}){return <Fig label={stage===1?'Place one set-square edge along line AB':stage===2?'Hold a ruler firmly against the set square':'Slide the set square without rotating it, then draw CD'}><line x1="55" y1="185" x2="365" y2="185" className="geo-line"/><text x="50" y="208">A</text><text x="360" y="208">B</text><path d="M130 185L250 185L130 80Z" className="tool-set-square"/>{stage>=2&&<rect x="115" y="55" width="30" height="145" rx="4" className="tool-ruler"/>}{stage>=3&&<><path d="M130 90L250 90L130 -15Z" className="tool-set-square ghost"/><line x1="55" y1="90" x2="365" y2="90" className="geo-result"/><text x="50" y="82">C</text><text x="360" y="82">D</text><path d="M185 180l12 5-12 5 M185 85l12 5-12 5" className="geo-mark"/></>}</Fig>}
function PerpFig({stage}:{stage:number}){return <Fig label={stage===1?'Given line AB and point P':stage===2?'Place a set-square edge along AB':'Slide the set square until its perpendicular edge passes through P, then draw'}><line x1="55" y1="190" x2="365" y2="190" className="geo-line"/><text x="50" y="214">A</text><text x="360" y="214">B</text><circle cx="235" cy="65" r="4" className="geo-fill"/><text x="243" y="62">P</text>{stage>=2&&<><path d="M105 190L245 190L105 70Z" className="tool-set-square"/><rect x="90" y="52" width="30" height="155" rx="4" className="tool-ruler"/></>}{stage>=3&&<><path d="M235 190L355 190L235 85Z" className="tool-set-square ghost"/><line x1="235" y1="45" x2="235" y2="225" className="geo-result"/><path d="M235 190h18v-18" className="geo-mark"/><text x="260" y="175">90°</text></>}</Fig>}
export default function ConstructionLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson geometry-premium-lesson construction-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS · MENSURATION & GEOMETRY</span><h1>Construction</h1><p>Work as if your mathematics teacher is beside you. Do not rush to the finished drawing: place each instrument, make each mark, and understand what that mark does.</p></header>
<section className="wn-objectives"><h2>NERDC-Aligned Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>
<section className="wn-section"><h3>1. What Construction Means</h3><p>In geometry, construction means drawing a geometrical figure accurately using suitable mathematical instruments. A rough sketch shows an idea; a construction creates the required relationship accurately.</p><div className="lesson-rule"><span><b>Ruler/straightedge:</b> draw straight lines and measure when a length is specified.</span><span><b>Compass:</b> transfer equal distances and draw arcs.</span><span><b>Set square:</b> guide parallel and perpendicular lines.</span><span><b>Sharp pencil:</b> keeps lines and arc intersections precise.</span></div><p><b>AVORA rule:</b> never erase useful construction arcs before the work is checked. The arcs are evidence of how you obtained the answer.</p></section>
<section className="wn-section"><h3>2. Before You Touch the Instruments</h3><div className="lesson-rule"><span>Keep the pencil sharp.</span><span>Do not change the compass opening when a step says “same radius”.</span><span>Put the compass needle exactly on the named point.</span><span>Draw light arcs first; darken the final required line.</span><span>Label points immediately so you do not confuse them.</span></div></section>
<section className="wn-section"><h3>3. Construct Parallel Lines — Teacher-Guided</h3><p><b>Goal:</b> draw CD parallel to AB. Parallel lines stay the same distance apart and never meet, however far they are extended.</p>
<Step n={1} title="Set the first direction" fig={<ParallelFig stage={1}/>}>Draw the given straight line AB. Place one straight edge of the set square exactly along AB. Do not allow a gap between the set square and the line.</Step>
<Step n={2} title="Lock the guide" fig={<ParallelFig stage={2}/>}>Place the ruler firmly against another edge of the set square. Hold the ruler still. The ruler is now the track along which the set square will slide.</Step>
<Step n={3} title="Slide — do not rotate" fig={<ParallelFig stage={3}/>}>Slide the set square along the fixed ruler to the required position. Do not turn it. Draw along the same edge of the set square and label the new line CD. Because the set square kept the same direction while sliding, CD is parallel to AB.</Step>
<div className="lesson-rule"><span><b>Check:</b> AB ∥ CD. If the lines are extended, they should not move toward one another.</span><span><b>Common mistake:</b> rotating the set square while sliding destroys the parallel direction.</span></div></section>
<section className="wn-section"><h3>4. Construct a Perpendicular Line — Teacher-Guided</h3><p><b>Goal:</b> draw a line through P perpendicular to AB. Perpendicular lines meet at exactly 90°.</p>
<Step n={1} title="Read the task" fig={<PerpFig stage={1}/>}>Locate the given line AB and the point P. Your final line must pass through P and meet AB at a right angle.</Step>
<Step n={2} title="Prepare the right-angle guide" fig={<PerpFig stage={2}/>}>Place one edge of the set square along AB and hold a ruler against the set square as a sliding guide. The two short edges forming the set square's right angle are perpendicular.</Step>
<Step n={3} title="Slide to P and draw" fig={<PerpFig stage={3}/>}>Slide the set square without rotating it until its perpendicular edge passes exactly through P. Hold everything firmly and draw through P to meet AB. Mark the right angle. The new line is perpendicular to AB.</Step>
<div className="lesson-rule"><span><b>Verification:</b> the angle at the intersection is 90°.</span><span><b>Symbol:</b> if line PR meets AB at R at 90°, write PR ⟂ AB.</span></div></section>
<section className="wn-section"><h3>5. Bisect a Given Line Segment — Compass Construction</h3><p><b>Worked construction:</b> bisect AB. “Bisect” means divide into two equal parts. We will construct the midpoint M, not guess it with our eyes.</p>
<Step n={1} title="Draw the segment" fig={<BisectFig stage={1}/>}>Draw the given segment AB and label both endpoints clearly.</Step>
<Step n={2} title="Arcs from A" fig={<BisectFig stage={2}/>}>Open the compass to a radius greater than half of AB. Put the needle exactly at A. Without moving A, draw one arc above AB and another below AB.</Step>
<Step n={3} title="Same opening, arcs from B" fig={<BisectFig stage={3}/>}>Do not change the compass opening. Put the needle at B. Draw arcs above and below AB so that they cut the first pair. Label the upper intersection P and lower intersection Q.</Step>
<Step n={4} title="Join the intersections" fig={<BisectFig stage={4}/>}>Use the ruler to draw the straight line PQ. It cuts AB at M. M is the midpoint, so AM = MB. PQ is also perpendicular to AB, so the construction has produced the perpendicular bisector of AB.</Step>
<div className="lesson-rule"><span><b>Why must the compass radius exceed half AB?</b> If it is too small, the arcs from A and B will not meet.</span><span><b>Check:</b> measure AM and MB. They must be equal. Also check that PQ meets AB at 90°.</span></div></section>
<section className="wn-section"><h3>6. Fully Worked Example — Bisect a 6 cm Segment</h3><div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>Draw AB = 6 cm and construct its midpoint.</strong></div><div className="math-stack"><div className="math-line">1. Use the ruler to draw AB = 6 cm.</div><div className="math-line">2. Open the compass to more than 3 cm, because 3 cm is half of AB.</div><div className="math-line">3. From A, draw arcs above and below AB.</div><div className="math-line">4. Keep the same compass opening. From B, draw arcs cutting the first arcs at P and Q.</div><div className="math-line">5. Join P to Q. Let PQ cut AB at M.</div><div className="math-line">6. Therefore AM = MB.</div><div className="math-line math-result">AM = MB = 3 cm</div><div className="math-line">Verification: 3 cm + 3 cm = 6 cm, the original length. ✓</div></div></div></section>
<section className="wn-section"><h3>7. Construct a 60° Angle — Compass Construction</h3><p>This construction uses the fact that equal compass radii form an equilateral triangle, whose three angles are 60°.</p>
<Step n={1} title="Draw the first arm" fig={<SixtyFig stage={1}/>}>Draw ray AB. A will be the vertex of the required angle.</Step>
<Step n={2} title="Make the first arc" fig={<SixtyFig stage={2}/>}>Put the compass needle at A. Choose a convenient radius and draw an arc cutting ray AB at B. Keep this compass opening.</Step>
<Step n={3} title="Transfer the same radius" fig={<SixtyFig stage={3}/>}>Without changing the compass radius, put the needle at B and draw an arc that cuts the first arc. Label the intersection C.</Step>
<Step n={4} title="Join the vertex to C" fig={<SixtyFig stage={4}/>}>Use the ruler to join A to C. AB, AC and BC are equal compass radii, so triangle ABC is equilateral. Therefore angle BAC = 60°.</Step>
<div className="lesson-rule"><span><b>Final answer:</b> ∠BAC = 60°.</span><span><b>Do not:</b> change the compass opening between the two arcs; equality of the radii is what makes the construction work.</span></div></section>
<section className="wn-section"><h3>8. Construct a 90° Angle — Compass Construction</h3><p><b>Goal:</b> construct a right angle at A without measuring 90° with a protractor.</p>
<Step n={1} title="Draw the straight baseline" fig={<NinetyFig stage={1}/>}>Draw a straight line through A. The required perpendicular will rise from A.</Step>
<Step n={2} title="Mark equal points around A" fig={<NinetyFig stage={2}/>}>With A as centre, draw an arc cutting the line at P and Q so that AP = AQ. P and Q are now equally distant from A.</Step>
<Step n={3} title="Make intersecting arcs" fig={<NinetyFig stage={3}/>}>Open the compass wider than AP. With P as centre draw an arc above the line. Without changing the radius, repeat from Q so the arcs meet at R.</Step>
<Step n={4} title="Draw the perpendicular" fig={<NinetyFig stage={4}/>}>Join A to R. Since R is equally distant from P and Q and A is the midpoint of PQ, AR is the perpendicular bisector of PQ. Therefore AR meets the baseline at 90°.</Step>
<div className="lesson-rule"><span><b>Final answer:</b> ∠PAR = ∠QAR = 90°.</span><span><b>Check:</b> the right-angle square at A records the result; a protractor may be used afterwards only to verify it.</span></div></section>
<section className="wn-section"><h3>9. How the Constructions Connect</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>NERDC task</th><th>Key idea</th><th>What proves success?</th></tr></thead><tbody><tr><td>Parallel lines</td><td>Preserve direction while sliding set square</td><td>AB ∥ CD</td></tr><tr><td>Perpendicular lines</td><td>Use a right-angle edge</td><td>Intersection = 90°</td></tr><tr><td>Bisect segment</td><td>Equal-radius arcs from both endpoints</td><td>AM = MB</td></tr><tr><td>60° angle</td><td>Three equal radii form an equilateral triangle</td><td>Constructed angle = 60°</td></tr><tr><td>90° angle</td><td>Construct a perpendicular bisector through the vertex</td><td>Constructed angle = 90°</td></tr></tbody></table></div></section>
<section className="wn-section"><h3>10. Common Mistakes — Fix Them Before They Happen</h3><div className="lesson-rule"><span><b>Compass slips:</b> return the needle exactly to the labelled centre and redraw.</span><span><b>Changing radius:</b> when a step says same radius, lock your fingers and do not adjust the compass.</span><span><b>Arcs do not meet:</b> the compass opening is too small; increase it appropriately.</span><span><b>Thick pencil:</b> thick intersections make the exact point uncertain; sharpen the pencil.</span><span><b>Erasing arcs:</b> keep them until the construction is checked.</span><span><b>Set square rotates:</b> hold the ruler firmly and slide rather than turn.</span><span><b>Guessing 90° or 60°:</b> construction is not freehand drawing. Follow the geometric steps.</span></div></section>
<section className="wn-section"><h3>11. AVORA Construction Routine</h3><div className="lesson-rule"><span><b>READ:</b> What exactly must be constructed?</span><span><b>LABEL:</b> Mark every given point.</span><span><b>PLACE:</b> Put the instrument exactly where the step says.</span><span><b>LOCK:</b> Keep a required compass radius or ruler guide unchanged.</span><span><b>DRAW:</b> Make light arcs/lines accurately.</span><span><b>CONNECT:</b> Join only the required intersection points.</span><span><b>VERIFY:</b> check equality, parallelism or the required angle.</span><span><b>KEEP EVIDENCE:</b> leave the useful construction marks visible.</span></div></section>
<section className="wn-section"><h3>12. Mastery Check</h3><p>You have mastered the NERDC JSS1 Construction objective when, with your own mathematical set, you can independently construct parallel and perpendicular lines, bisect a line segment, and construct 60° and 90° angles; explain every instrument movement; preserve the necessary construction marks; and verify why the completed figure satisfies the requirement.</p></section>
<div className="lesson-action"><button type="button" className="primary-btn" onClick={onExercise}>Go to Exercise →</button></div>
</article>}
