'use client';
import React from 'react';

const objectives=[
'state the purposes of statistics',
'explain why reliable data is needed before planning',
'use simple collected information to make a sensible planning decision',
'explain chance events in everyday life',
'describe probability informally using impossible, unlikely, equally likely, likely and certain',
'give everyday examples where chance and probability are useful',
'explain how past and present data can support prediction',
'distinguish a data-based prediction from a guarantee'
];

function DataBars(){const rows=[['JSS1A',42,84],['JSS1B',38,76],['JSS1C',45,90]];return <div className="stats-card"><h4>Planning example: Mathematics workbooks</h4><div className="stats-bars">{rows.map(([n,v,p])=><div className="stats-bar-row" key={String(n)}><span>{n}</span><div><i style={{width:p+'%'}}/></div><b>{v}</b></div>)}</div><p className="stats-caption">Total learners = 42 + 38 + 45 = <b>125</b>. The school needs at least 125 workbooks if every learner is to receive one.</p></div>}
function ChanceScale(){return <div className="chance-scale" aria-label="Chance scale from impossible to certain"><div><b>Impossible</b><span>0</span><small>Sun rises in the west tomorrow</small></div><div><b>Unlikely</b><span>low chance</span><small>Rolling a 6 twice in a row</small></div><div><b>Equally likely</b><span>½</span><small>Head on a fair coin</small></div><div><b>Likely</b><span>high chance</span><small>Rain during a very wet period</small></div><div><b>Certain</b><span>1</span><small>A week has 7 days</small></div></div>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}

export default function DataCollectionLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson statistics-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS · EVERYDAY STATISTICS</span><h1>Data Collection</h1><p>Statistics becomes useful when information helps us understand a situation, plan wisely, think about chance, or make a reasonable prediction.</p></header>
<section className="wn-objectives"><h2>NERDC-Aligned Learning Objectives</h2><ul><li>collect simple data in the classroom for a stated purpose.</li><li>identify the information needed before collecting it.</li><li>record observations carefully so no response is lost or counted twice.</li><li>use tallies for an accurate running count.</li><li>check collected data for missing, duplicate or suspicious entries.</li><li>produce a clean record ready for Data Presentation.</li></ul></section>
<section className="wn-section"><h3>1. What Is Data Collection?</h3><p><b>Data collection</b> is deliberately gathering and recording information needed to answer a question. NERDC makes this topic practical: the learner should actually collect data in the class.</p><div className="lesson-rule"><span><b>Question first:</b> know what you want to find out.</span><span><b>Relevant data:</b> collect information that answers that question.</span><span><b>Record immediately:</b> do not rely on memory.</span></div></section>
<section className="wn-section"><h3>2. Decide What You Need</h3><div className="fraction-working"><div className="example-question"><span>GUIDED INVESTIGATION</span><strong>We want to know how 20 learners usually travel to school. What should we collect?</strong></div><div className="math-stack"><div className="math-line">Ask one clear question: How do you usually travel to school?</div><div className="math-line">Possible responses: Walk, Bus, Car, Motorcycle/Tricycle, Bicycle, Other.</div><div className="math-line">Record one usual method from each learner.</div><div className="math-line math-result">Do not collect unrelated information.</div></div></div></section>
<section className="wn-section"><h3>3. Ways to Collect Classroom Data</h3><div className="stats-purpose-grid"><div><b>Ask / Interview</b><p>Ask each learner a clear question and record the answer.</p></div><div><b>Questionnaire</b><p>Give the same written question to several learners.</p></div><div><b>Observe and Count</b><p>Watch an event and record each occurrence.</p></div><div><b>Existing Records</b><p>With permission, use relevant class records such as score sheets.</p></div></div><p>NERDC specifically lists student bio-data, marks, score sheets, dice and coins as resources for classroom collection activities.</p></section>
<section className="wn-section"><h3>4. Raw Data</h3><p><b>Raw data</b> are observations in the form first collected, before summarising them.</p><div className="raw-data-strip"><span>39</span><span>40</span><span>38</span><span>41</span><span>40</span><span>39</span><span>42</span><span>40</span><span>38</span><span>39</span></div><p>Record what was actually observed. If an entry looks wrong, verify it instead of silently changing it.</p></section>
<section className="wn-section"><h3>5. Tally Marks</h3><p>A tally gives one mark for each response. Group the fifth mark across the previous four so groups of five are easy to count.</p><div className="tally-text-demo"><span>1: |</span><span>2: ||</span><span>3: |||</span><span>4: ||||</span><span>5: <b>||||/</b></span></div><div className="lesson-rule"><span>One response means one tally.</span><span>Never count the same learner twice.</span><span>Total frequency must equal the number of valid responses.</span></div></section>
<section className="wn-section"><h3>6. Complete Classroom Investigation</h3><p><b>Question:</b> How do 20 learners usually travel to school?</p><div className="collection-flow"><div><b>1</b><span><strong>Define</strong>Ask one question.</span></div><div><b>2</b><span><strong>Ask</strong>One learner at a time.</span></div><div><b>3</b><span><strong>Record</strong>One tally immediately.</span></div><div><b>4</b><span><strong>Count</strong>Find each frequency.</span></div><div><b>5</b><span><strong>Check</strong>Total must be 20.</span></div></div><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>Method</th><th>Tally</th><th>Frequency</th></tr></thead><tbody><tr><td>Walk</td><td>||||/ ||</td><td>7</td></tr><tr><td>Bus</td><td>||||/</td><td>5</td></tr><tr><td>Car</td><td>||||</td><td>4</td></tr><tr><td>Motorcycle/Tricycle</td><td>|||</td><td>3</td></tr><tr><td>Bicycle</td><td>|</td><td>1</td></tr></tbody><tfoot><tr><th>Total</th><th></th><th>20</th></tr></tfoot></table></div><div className="fraction-working"><div className="example-question"><span>CHECK THE COLLECTION</span><strong>Have we obviously lost or duplicated a response?</strong></div><div className="math-stack"><div className="math-line">7 + 5 + 4 + 3 + 1 = 20</div><div className="math-line">Learners questioned = 20</div><div className="math-line math-result">Recorded responses = learners questioned = 20 ✓</div></div></div></section>
<section className="wn-section"><h3>7. Numerical Data From Class Records</h3><p>Data can also be numerical. Suppose a score sheet gives ten quiz scores out of 10:</p><div className="raw-data-strip"><span>7</span><span>5</span><span>9</span><span>6</span><span>8</span><span>7</span><span>10</span><span>4</span><span>8</span><span>6</span></div><p>Copy each score exactly. Do not replace a score with what you expected the learner to obtain.</p></section>
<section className="wn-section"><h3>8. Generate Data With a Coin</h3><p>NERDC includes coins and dice because repeated trials generate data that learners can record.</p><div className="fraction-working"><div className="example-question"><span>WORKED COLLECTION</span><strong>A coin is tossed 12 times: H, T, H, H, T, T, H, T, H, H, T, H. Record the frequencies.</strong></div><div className="math-stack"><div className="math-line">Scan one outcome at a time.</div><div className="math-line">Heads occurs 7 times.</div><div className="math-line">Tails occurs 5 times.</div><div className="math-line">Check: 7 + 5 = 12 trials.</div><div className="math-line math-result">Heads = 7; Tails = 5 ✓</div></div></div></section>
<section className="wn-section"><h3>9. Check Before Using the Data</h3><div className="stats-card"><h4>Spot the suspicious entry</h4><div className="raw-data-strip"><span>12</span><span>13</span><span>12</span><span className="data-warning">130</span><span>13</span><span>12</span></div><p>If these are ages of JSS1 learners in years, 130 needs verification. Do not automatically change it to 13; return to the source and check.</p></div><div className="lesson-rule"><span><b>Missing:</b> did anyone fail to answer?</span><span><b>Duplicate:</b> was anyone recorded twice?</span><span><b>Suspicious:</b> does an entry need checking?</span><span><b>Units:</b> are measurements in the same unit?</span><span><b>Total:</b> does the number of records match the expected number?</span></div></section>
<section className="wn-section"><h3>10. Collect Responsibly</h3><p>For classroom statistics, collect only information needed for the activity. If names are unnecessary, do not attach names to the data.</p><div className="lesson-rule"><span>Do not invent responses for absent learners.</span><span>Do not alter answers to get a preferred result.</span><span>Do not ask unnecessary private questions.</span><span>Follow the teacher's instructions when records are used.</span></div></section>
<section className="wn-section"><h3>11. Full Teacher-Guided Task</h3><div className="fraction-working"><div className="example-question"><span>FROM START TO FINISH</span><strong>Find which library period learners prefer: Monday, Tuesday, Wednesday or Thursday.</strong></div><div className="math-stack"><div className="math-line"><b>1. Purpose:</b> find the preferred library period.</div><div className="math-line"><b>2. Question:</b> Which ONE period do you prefer?</div><div className="math-line"><b>3. Collect:</b> ask each participating learner once.</div><div className="math-line"><b>4. Record:</b> add one tally beside the selected day immediately.</div><div className="math-line"><b>5. Count:</b> convert tallies to frequencies.</div><div className="math-line"><b>6. Check:</b> frequencies must total the valid responses.</div><div className="math-line math-result">The result is a checked data set ready for presentation.</div></div></div></section>
<section className="wn-section"><h3>12. Common Mistakes</h3><div className="lesson-rule"><span><b>No purpose:</b> start with a question.</span><span><b>Vague wording:</b> use one clear meaning.</span><span><b>Double counting:</b> one response, one record.</span><span><b>Recording later:</b> record immediately.</span><span><b>Changing answers:</b> preserve what was actually collected.</span><span><b>Ignoring errors:</b> verify suspicious entries.</span></div></section>
<section className="wn-section"><h3>13. AVORA Collection Routine</h3><div className="lesson-rule"><span><b>ASK:</b> What question am I answering?</span><span><b>CHOOSE:</b> What data are relevant?</span><span><b>METHOD:</b> How will I obtain them?</span><span><b>RECORD:</b> Capture each response once.</span><span><b>CHECK:</b> Find missing, duplicate or suspicious entries.</span><span><b>COUNT:</b> Confirm the total number of records.</span><span><b>READY:</b> Keep the clean data for the next topic—Data Presentation.</span></div></section>
<section className="wn-section"><h3>14. NERDC Mastery Activity</h3><p>You have mastered this objective when you can carry out a small approved data-collection activity in your class and produce a complete, checked record. The official evaluation asks learners to collect student bio-data with given characteristics; coin/die trials and class scores are also listed as learning resources.</p></section>
<div className="lesson-action"><button type="button" className="primary-btn" onClick={onExercise}>Go to Exercise →</button></div>
</article>}
