'use client'; import React from 'react';
const W=({q,children}:{q:string;children:React.ReactNode})=><div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>;
const L=({children,strong=false}:{children:React.ReactNode;strong?:boolean})=><div className={strong?'math-line math-result':'math-line'}>{children}</div>;
const Rule=({children}:{children:React.ReactNode})=><div className="lesson-rule">{children}</div>;
export default function HCFLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson"><header className="wn-hero"><span>JSS1 MATHEMATICS · WHOLE NUMBERS</span><h1>Highest Common Factor (HCF)</h1><p>Build HCF from the meaning of factors, common factors and prime factors, then apply it to JSS1 problems.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul><li>Explain factor and common factor.</li><li>Find factors systematically using factor pairs.</li><li>Express whole numbers as products of prime factors.</li><li>Find HCF by factor lists and prime factorisation.</li><li>Distinguish HCF from LCM and solve quantitative problems.</li></ul></section>
<section className="wn-section"><h3>1. Foundation: What Is a Factor?</h3><p>A <b>factor</b> of a whole number divides it exactly. Another way to find factors is to look for multiplication pairs that produce the number.</p><W q="Find all factors of 28 using factor pairs."><L>1 × 28 = 28 → 1 and 28 are factors.</L><L>2 × 14 = 28 → 2 and 14 are factors.</L><L>3 does not divide 28 exactly.</L><L>4 × 7 = 28 → 4 and 7 are factors.</L><L>After this the pairs begin to repeat in reverse order, so stop.</L><L strong>Factors of 28: 1, 2, 4, 7, 14, 28.</L></W></section>
<section className="wn-section"><h3>2. Common Factors</h3><p>A <b>common factor</b> is a factor shared by two or more numbers.</p><W q="Find the common factors of 18 and 24."><L>Factors of 18: 1, 2, 3, 6, 9, 18.</L><L>Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24.</L><L strong>Common factors: 1, 2, 3, 6.</L></W></section>
<section className="wn-section"><h3>3. Highest Common Factor</h3><p>The <b>Highest Common Factor</b> is the greatest number that divides all the given numbers exactly.</p><W q="Find the HCF of 18 and 24 from their factor lists."><L>Common factors: 1, 2, 3, 6.</L><L>The greatest common factor is 6.</L><L strong>HCF(18,24) = 6.</L><L>Check: 18 ÷ 6 = 3 and 24 ÷ 6 = 4.</L></W></section>
<section className="wn-section"><h3>4. Prime Numbers and Prime Factors — Build This First</h3><p>A <b>prime number</b> is a whole number greater than 1 with exactly two positive factors: 1 and itself. Examples include 2, 3, 5, 7, 11 and 13. The number 1 is not prime. Numbers such as 4, 6, 8, 9 and 12 are composite because they have more than two factors.</p><W q="Is 7 prime? Is 9 prime?"><L>7 has factors 1 and 7 only, so 7 is prime.</L><L>9 has factors 1, 3 and 9, so 9 is composite.</L></W><p>A <b>prime factor</b> is a factor that is also a prime number. The factors of 12 are 1, 2, 3, 4, 6 and 12. Among them, 2 and 3 are prime, so 2 and 3 are the prime factors of 12.</p><p><b>Prime factorisation</b> means writing a whole number completely as a product of prime numbers. A reliable method is repeated division: divide by the smallest prime that goes in exactly and continue with the quotient until 1.</p><W q="Express 60 as a product of prime factors."><L>60 ÷ 2 = 30.</L><L>30 ÷ 2 = 15.</L><L>15 ÷ 3 = 5.</L><L>5 ÷ 5 = 1.</L><L>60 = 2 × 2 × 3 × 5.</L><L strong>60 = 2² × 3 × 5.</L><L>Check: 4 × 3 × 5 = 60.</L></W><W q="Express 84 as a product of prime factors."><L>84 ÷ 2 = 42.</L><L>42 ÷ 2 = 21.</L><L>21 ÷ 3 = 7.</L><L>7 ÷ 7 = 1.</L><L strong>84 = 2² × 3 × 7.</L></W><h4>Why use prime factors for HCF?</h4><p>Prime factors are the basic multiplicative building blocks of whole numbers. Writing each number completely in primes shows exactly which building blocks every number shares. For HCF, keep only prime factors shared by all the numbers and use the smallest shared number of copies. That produces the greatest factor that divides every original number exactly.</p><Rule><span>Prime number: exactly two positive factors.</span><span>Prime factor: a factor that is prime.</span><span>Prime factorisation: a number written completely as a product of primes.</span><span>HCF: shared prime factors only, using the lowest shared powers.</span></Rule></section>
<section className="wn-section"><h3>5. HCF by Prime Factorisation</h3><p>Write each number as prime factors. Keep only the prime factors common to every number. If a shared prime is repeated, use only the number of copies shared by all—in index form, the lowest shared power.</p><W q="Find the HCF of 36 and 48."><L>36 = 2 × 2 × 3 × 3 = 2² × 3².</L><L>48 = 2 × 2 × 2 × 2 × 3 = 2⁴ × 3.</L><L>Both numbers contain 2 and 3.</L><L>For 2, the lower shared power is 2².</L><L>For 3, the lower shared power is 3¹.</L><L>HCF = 2² × 3</L><L>= 4 × 3</L><L strong>HCF = 12.</L><L>Check: 36 ÷ 12 = 3; 48 ÷ 12 = 4.</L></W></section>
<section className="wn-section"><h3>6. HCF of Three Numbers</h3><W q="Find the HCF of 24, 36 and 60."><L>24 = 2³ × 3</L><L>36 = 2² × 3²</L><L>60 = 2² × 3 × 5</L><L>2 and 3 occur in all three numbers; 5 does not.</L><L>Lowest shared powers: 2² and 3¹.</L><L>HCF = 2² × 3 = 4 × 3.</L><L strong>HCF = 12.</L></W></section>
<section className="wn-section"><h3>7. Co-prime Numbers</h3><p>Sometimes the only common factor is 1. Such numbers are called co-prime.</p><W q="Find the HCF of 8 and 15."><L>Factors of 8: 1, 2, 4, 8.</L><L>Factors of 15: 1, 3, 5, 15.</L><L>The only common factor is 1.</L><L strong>HCF(8,15) = 1.</L></W></section>
<section className="wn-section"><h3>8. HCF in a Real Situation</h3><W q="24 oranges and 36 mangoes are arranged into the greatest possible number of identical baskets with none left. How many baskets can be made?"><L>The number of baskets must divide both 24 and 36 exactly.</L><L>24 = 2³ × 3.</L><L>36 = 2² × 3².</L><L>HCF = 2² × 3 = 12.</L><L strong>12 identical baskets can be made.</L><L>Each basket contains 24 ÷ 12 = 2 oranges and 36 ÷ 12 = 3 mangoes.</L></W></section>
<section className="wn-section"><h3>9. Quantitative Reasoning</h3><W q="If 28 = 2² × 7 and 84 = 3 × 28, express 84 as a product of prime factors."><L>84 = 3 × 28.</L><L>= 3 × (2² × 7).</L><L strong>84 = 2² × 3 × 7.</L></W></section>
<section className="wn-section"><h3>10. HCF Versus LCM</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>Idea</th><th>HCF</th><th>LCM</th></tr></thead><tbody><tr><td>Meaning</td><td>greatest shared factor</td><td>lowest shared multiple</td></tr><tr><td>Prime factors</td><td>shared primes only; lowest shared powers</td><td>all primes needed; highest powers</td></tr><tr><td>Typical situation</td><td>largest equal groups or pieces</td><td>first meeting of repeating cycles</td></tr></tbody></table></div></section>
<section className="wn-section"><h3>11. Common Mistakes</h3><Rule><span>Do not confuse factors with multiples.</span><span>For HCF, a prime must occur in every number before it can be used.</span><span>Use the lowest shared prime power, not the highest.</span><span>Your HCF must divide every original number exactly.</span></Rule></section>
<section className="wn-section"><h3>12. Mastery Check</h3><p>You should now be able to explain factors and common factors, find HCF by lists and prime factors, work with two or three numbers, recognise HCF situations, distinguish HCF from LCM and justify your answer.</p></section><div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}