'use client';
import React,{useState} from 'react';
type Q={q:string;options:string[];answer:number;why:string;skill:string};
const qs:Q[]=[
{q:"Which best describes fluent reading?",options:["Reading as fast as possible","Reading accurately, at an appropriate pace, with expression and understanding","Reading every word at the same pitch","Skipping difficult words"],answer:1,why:"Fluency combines accuracy, appropriate speed, prosody and comprehension.",skill:"Fluency"},
{q:"What is accurate word recognition?",options:["Identifying printed words correctly","Guessing from the first letter","Reading only familiar words","Replacing words freely"],answer:0,why:"Accuracy requires reading the word actually printed, not a guessed substitute.",skill:"Accuracy"},
{q:"Why is maximum speed not the goal?",options:["Speed must suit the text and preserve accuracy and understanding","Slow reading is always best","Fast readers cannot understand","Timing never matters"],answer:0,why:"Appropriate pace changes with text difficulty and purpose; comprehension must remain intact.",skill:"Pace"},
{q:"What should a full stop normally signal in oral reading?",options:["Continue without pause","A meaningful sentence boundary and pause","Shout","Skip the next word"],answer:1,why:"Punctuation helps readers phrase ideas and communicate sentence structure.",skill:"Punctuation"},
{q:"What is prosody?",options:["Expressive reading using suitable stress, rhythm, phrasing and intonation","Counting words","Silent spelling","Reading backwards"],answer:0,why:"Prosody is the expressive pattern that helps spoken reading sound meaningful rather than mechanical.",skill:"Prosody"},
{q:"Which reading best respects a question mark?",options:["Use an intonation appropriate to the question","Ignore it completely","Always whisper","Stop before the question"],answer:0,why:"Punctuation guides phrasing and intonation; a question should sound like the kind of question being asked.",skill:"Intonation"},
{q:"Why read in phrases rather than isolated words?",options:["Phrases group words into meaningful units","It makes punctuation unnecessary","It permits skipping words","Every phrase has three words"],answer:0,why:"Meaning is carried by groups of related words, so phrase reading supports natural pace and comprehension.",skill:"Phrasing"},
{q:"What is regressive reading?",options:["Repeatedly moving back to reread material unnecessarily","Reading a heading first","Answering questions","Reading aloud"],answer:0,why:"Unnecessary backward eye movement can interrupt flow; purposeful rereading for clarification is different.",skill:"Reading habit"},
{q:"Which is an example of useful rereading rather than harmful regression?",options:["Returning to a difficult sentence because its meaning was unclear","Jumping backwards after every word from habit","Restarting every line automatically","Looking back without purpose"],answer:0,why:"Strategic rereading serves comprehension; habitual regression disrupts fluency.",skill:"Reading habit"},
{q:"What does increasing eye span mean?",options:["Taking in meaningful groups of words in a fixation rather than processing only one word at a time","Opening the eyes wider","Skipping a whole paragraph","Reading without seeing"],answer:0,why:"A broader functional eye span supports phrase reading and smoother progress through text.",skill:"Eye span"},
{q:"Which practice involves a model reading a portion and learners repeating it?",options:["Echo reading","Silent examination","Dictation","Free writing"],answer:0,why:"Echo reading lets learners imitate accurate pronunciation, phrasing and expression.",skill:"Practice method"},
{q:"What is choral reading?",options:["A group reads a passage aloud together","One learner reads silently","A learner memorises definitions","Everyone writes a summary"],answer:0,why:"Choral reading provides supported repeated practice as learners read together.",skill:"Practice method"},
{q:"What is a useful purpose of paired reading?",options:["Learners practise and support each other's fluency","One learner does all the work","To avoid comprehension","To race without accuracy"],answer:0,why:"Paired reading gives repeated practice, feedback and collaborative support.",skill:"Collaboration"},
{q:"A reader pronounces every word correctly but cannot answer a basic question about the passage. Is the fluency goal fully met?",options:["Yes, pronunciation alone is fluency","No, NERDC includes reading with understanding and answering questions","Yes, if reading was fast","No, because reading must always be slow"],answer:1,why:"Fluent reading in this curriculum includes comprehension, not sound production alone.",skill:"Comprehension"},
{q:"Which action best helps with an unfamiliar word during fluency practice?",options:["Break it into recognisable parts, use context, confirm pronunciation, then reread the phrase","Invent a replacement","Skip every difficult word","Repeat the wrong pronunciation faster"],answer:0,why:"Word analysis and context support accurate recognition; rereading restores the phrase's flow.",skill:"Word recognition"},
{q:"Why should a reader observe commas?",options:["They often mark meaningful boundaries or brief pauses within a sentence","They always end paragraphs","They mean shout","They have no effect on reading"],answer:0,why:"Commas often help organise clauses and phrases, though the exact pause depends on meaning.",skill:"Punctuation"},
{q:"Which shows confidence without sacrificing accuracy?",options:["Clear audible reading with controlled pace and recovery from errors","Pretending not to make mistakes","Rushing","Guessing difficult words loudly"],answer:0,why:"Confidence is controlled, understandable delivery, not speed or concealment of errors.",skill:"Confidence"},
{q:"What is the best response after noticing a misread word?",options:["Correct it and reread the phrase smoothly","Ignore every error","Restart the entire passage every time","Change the printed sentence"],answer:0,why:"Self-correction protects accuracy; rereading the phrase restores meaning and fluency.",skill:"Self-correction"},
{q:"When timing reading practice, what should improve together?",options:["Appropriate pace, accuracy and comprehension","Speed only","Volume only","Number of skipped words"],answer:0,why:"A faster time is not progress if errors increase or understanding falls.",skill:"Monitoring"},
{q:"What demonstrates mastery of reading fluency?",options:["Reading a new suitable passage accurately, expressively, at an appropriate pace and answering comprehension questions","Memorising the definition of fluency","Reading one practised sentence quickly","Knowing punctuation names only"],answer:0,why:"NERDC expects actual fluent reading plus correct responses to questions on the passage.",skill:"Mastery"}
];
const sections=[
["1. What fluent reading really means",["Fluent reading is smooth, accurate and meaningful reading. It brings together correct word recognition, appropriate speed, good pronunciation, phrasing, expression, intonation, confidence and understanding.","A learner who races through a passage but changes words is not fluent. A learner who pronounces every word slowly and separately but cannot follow the message has not yet reached full fluency either.","The goal is accurate reading that sounds like meaningful language and leaves enough attention for comprehension."]],
["2. The four pillars: accuracy, pace, prosody, comprehension",["ACCURACY: read the words actually printed. PACE: move at a suitable speed—not rushed and not unnecessarily slow. PROSODY: use phrasing, stress, rhythm, pronunciation and intonation to express meaning. COMPREHENSION: understand what the text communicates.","These skills support one another. When word recognition becomes more automatic, the mind has more attention available for meaning and expression."]],
["3. Accurate word recognition",["Do not guess a whole word from its first letter. Compare the letters, syllables and surrounding sentence. If you read 'discipline' as 'discussion', the sentence may change completely.","When a word is difficult, slow down briefly, break it into manageable parts, pronounce it carefully, check whether it fits the sentence, then reread the whole phrase smoothly.","Accuracy comes before impressive speed. Practising an error repeatedly only makes the error more familiar."]],
["4. Pronunciation",["Pronunciation is producing a word clearly and acceptably so that the listener can recognise it. Pay attention to sounds, syllables and the stressed part of longer words.","For practice, say: COM-mu-ni-ty → community; en-VI-ron-ment → environment; re-SPON-si-ble → responsible. The capitalised syllable shows the stronger stress in this teaching model.","After practising the word alone, return it to a sentence. Fluent reading requires accurate words inside meaningful phrases, not isolated pronunciation drills only."]],
["5. Appropriate reading speed",["Fluency does not mean 'fastest wins'. A simple narrative may permit a quicker pace than a dense explanatory paragraph. Important or difficult information may require a slight slowdown.","If speed causes substitutions, skipped endings or lost understanding, reduce it. If every familiar word is separated by a long pause, practise grouping words and recognising them more automatically.","Your best pace is the quickest comfortable pace at which accuracy, expression and comprehension remain strong."]],
["6. Punctuation guides meaning",["A full stop marks the end of a sentence and normally calls for a meaningful boundary. A comma often separates parts within a sentence. A question mark signals a question. An exclamation mark may signal strong feeling or emphasis. Quotation marks can indicate direct speech.","Do not turn punctuation into mechanical counting—'comma equals exactly one second'. Read according to both punctuation and meaning.","Compare: 'After the meeting, the students returned to class.' A slight boundary after 'meeting' helps the listener understand the opening phrase."]],
["7. Reading in phrases",["Weakly segmented reading: 'The / students / in / our / class / worked / together.' Better phrasing: 'The students in our class / worked together.'","Words form meaningful groups. Reading phrase by phrase makes speech smoother and helps the listener hear relationships between ideas.","Use slash marks during practice to discover sensible groups, but do not pause at every slash unnaturally. The marks are training aids."]],
["8. Expression and intonation",["Expression means the voice reflects the meaning rather than remaining mechanically flat. Intonation is the pattern of pitch movement across speech.","Read 'Did you lock the door?' as a genuine question, not as a flat list of words. Read 'Stop!' with the urgency the context requires. Read a sad description differently from a joyful announcement.","Expression must come from understanding. Exaggerated acting that contradicts the text is not good prosody."]],
["9. Stress and emphasis",["Within words, some syllables receive greater stress. Within sentences, important words may receive emphasis. Compare: 'SHE borrowed the book' and 'She borrowed the BOOK.' The emphasis can shift what the speaker highlights.","When reading aloud, first understand which idea matters. Then let your voice support that meaning naturally.","Do not stress every word. If everything is emphasised, nothing stands out."]],
["10. Reading with confidence",["Confidence means an audible, controlled voice, steady posture, willingness to attempt unfamiliar material and the ability to recover after an error.","Confidence does not mean pretending errors never happen. Skilled readers sometimes self-correct. If you misread a word, correct it and reread enough of the phrase to restore the meaning.","Repeated successful practice builds genuine confidence."]],
["11. Reading with understanding",["NERDC explicitly connects fluency with comprehension. After reading, you should be able to explain the main idea, important details and straightforward inferences appropriate to the passage.","Before reading, glance at the title. During reading, follow the ideas. After a paragraph, ask yourself: What did that paragraph tell me?","If you reach the bottom of a page and realise you understood nothing, speed alone has not helped you."]],
["12. Avoid unnecessary word vocalisation in silent reading",["For silent reading, excessive word-by-word vocalisation can slow progress. The curriculum encourages learners to move beyond needing to pronounce every single word aloud internally or with visible lip movement.","This does not mean pronunciation practice is bad. Oral reading deliberately uses the voice. The point is that silent reading and oral fluency practice have different immediate demands.","Train yourself to take in meaningful phrases when reading silently while still understanding them."]],
["13. Regressive reading",["Regressive reading means repeatedly moving your eyes backwards over words you have already read, often from habit rather than need. Frequent unnecessary regression can interrupt flow.","But purposeful rereading is different. If a difficult sentence genuinely did not make sense, going back strategically is a comprehension skill.","The target is to remove automatic, needless backward movement—not to forbid intelligent rereading."]],
["14. Increasing eye span",["A developing reader may focus on one word at a time. With practice, the eyes can take in larger meaningful groups during each fixation.","Instead of processing 'The / young / players / entered / the / field', practise seeing 'The young players / entered the field.' This supports phrase reading and smoother pace.","Never increase eye span by simply skipping unknown words. The words still have to be recognised and understood."]],
["15. Physical conditions for reading",["The NERDC content mentions good eyesight as a condition supporting fluent reading. A learner must be able to see the print clearly. Suitable lighting, readable text and a comfortable reading position also help sustained attention.","If print remains blurred or difficult to see, moving closer or trying to read faster is not a reliable solution; tell a responsible adult or teacher so the difficulty can be addressed appropriately.","Fluency instruction should not confuse a visibility problem with laziness or lack of intelligence."]],
["16. Teacher/model reading",["A useful model lets learners hear what accurate pronunciation, suitable pace, punctuation, phrasing and expression sound like together.","Do not merely enjoy the model. Listen analytically: Where did the reader pause? Which words were emphasised? How did the voice change at the question? Why?","Then imitate a short section and compare your reading with the model."]],
["17. Echo reading",["In echo reading, a fluent model reads a manageable sentence or phrase and learners repeat it, trying to reproduce accurate pronunciation, phrasing and expression.","Example model: 'After the heavy rain, / the residents cleared the blocked drains.' Learners echo the whole meaningful pattern rather than repeating isolated words.","As skill improves, increase the length of the chunk and reduce dependence on the model."]],
["18. Choral reading",["In choral reading, learners read a passage aloud together. It provides supported practice and can reduce anxiety for developing readers.","The goal is not to hide individual difficulty inside the group. Follow choral practice with individual or paired reading so each learner's accuracy and comprehension can be checked.","The group should keep a shared pace and observe punctuation rather than becoming a race."]],
["19. Paired reading",["NERDC includes paired reading, with stronger readers supporting weaker readers. Partners can alternate paragraphs, read together, or use a model-and-repeat pattern.","Useful feedback is specific: 'Try that word again'; 'Pause at the full stop'; 'These words belong together'; 'What did that sentence mean?'","A partner supports; a partner does not ridicule, dominate or supply every answer immediately."]],
["20. Timed practice—use time correctly",["A clock or timing device can help monitor progress, but time must never be the only score. Record accuracy and comprehension as well.","Suppose you read a passage in 90 seconds with 12 errors, then later in 100 seconds with only 2 errors and much better understanding. The second performance may represent stronger fluency despite taking ten seconds longer.","As accuracy becomes secure, appropriate speed can gradually improve."]],
["21. Worked fluency passage A",["PASSAGE: 'On Saturday morning, several students gathered beside the school garden. They had noticed that plastic waste was collecting near the drainage channel. With their teacher's guidance, they separated recyclable materials, cleared the channel and placed labelled bins nearby. When rain fell later that afternoon, water flowed freely through the drain.'","PHRASING MODEL: 'On Saturday morning, / several students gathered / beside the school garden.' Observe the comma, group words by meaning, and avoid pausing after every individual word.","COMPREHENSION CHECK: Why did the students clear the channel? Because plastic waste was collecting near it and could obstruct drainage. What later showed the benefit? Rainwater flowed freely through the drain."]],
["22. Worked fluency passage B — dialogue",["PASSAGE: '“Have you completed the science project?” Bisi asked. “Not yet,” Tayo replied, “but I have collected the materials.” “Then let's finish it after lunch!”'","Your voice should help listeners distinguish the question, the reply and the enthusiastic suggestion. Observe quotation marks and punctuation, but keep the dialogue natural.","COMPREHENSION: Tayo has not completed the project; he has collected the materials. The two plan to continue after lunch. Fluency and understanding are checked together."]],
["23. Standard pronunciation and difficult-word routine",["When you meet a difficult word: LOOK carefully at all its letters; BREAK it into useful sound/syllable parts; SAY it slowly; CHECK its pronunciation from a reliable model or teacher when needed; PUT it back into the phrase; REREAD smoothly.","Practice set: responsibility, communication, environmental, cooperation, pronunciation, accurate, comprehension, expression, confidence, punctuation.","Do not stop after pronouncing the list. Use the words in connected sentences so accurate pronunciation becomes part of fluent reading."]],
["24. Error clinic",["ERROR: racing. REPAIR: reduce pace until accuracy and meaning recover. ERROR: robotic word-by-word reading. REPAIR: mark and practise phrases. ERROR: ignoring punctuation. REPAIR: identify how each mark structures meaning.","ERROR: guessing unfamiliar words. REPAIR: analyse the whole word and context. ERROR: flat expression. REPAIR: understand the sentence, then practise stress and intonation. ERROR: repeated unnecessary backtracking. REPAIR: keep the eyes moving forward in meaningful groups unless clarification is genuinely needed.","ERROR: answering comprehension from memory of a similar topic rather than this passage. REPAIR: return to what the actual text says."]],
["25. Fluency practice ladder",["ROUND 1 — teacher/model reading: listen for accuracy and expression. ROUND 2 — echo reading: imitate manageable chunks. ROUND 3 — choral reading: practise with support. ROUND 4 — paired reading: receive specific feedback. ROUND 5 — independent reading: demonstrate the skill alone.","At every stage, ask comprehension questions. We are not training a voice that sounds fluent while the mind is absent.","Repeat difficult sections purposefully, then transfer the skill to a new passage."]],
["26. NERDC mastery task",["Take a new JSS2-appropriate passage that you have not memorised. Read it aloud at an appropriate pace with accurate word recognition, clear pronunciation, observance of punctuation, meaningful phrasing, expression, intonation and confidence.","Then answer questions about the passage. If you cannot explain what you read, return to the text and improve comprehension rather than merely increasing speed.","Mastery means these skills transfer to new reading—not that one practised paragraph can be performed from memory."]]
] as const;
export default function JSS2ReadingFluencyLesson({onExercise}:{onExercise?:()=>void}){const[show,setShow]=useState(false),[a,setA]=useState<Record<number,number>>({});return <section className="fractions-premium-lesson"><header className="premium-lesson-hero"><p className="lesson-kicker">JSS2 English Studies · Reading</p><h1>Reading with Fluency</h1><p>Read accurately, at an appropriate pace, with clear pronunciation, meaningful phrasing, expression, confidence and understanding.</p></header><article className="premium-section"><h2>Learning objectives</h2><ul><li>Recognise and pronounce words accurately.</li><li>Read at a pace appropriate to the text and purpose.</li><li>Observe punctuation and read in meaningful phrases.</li><li>Use expression and intonation to communicate meaning.</li><li>Reduce unnecessary regression and develop phrase-level eye span.</li><li>Practise through model, echo, choral and paired reading.</li><li>Read with understanding and answer questions on passages.</li></ul></article>{sections.map(([t,ps],i)=><article className="premium-section" key={i}><h2>{t}</h2>{ps.map((p,j)=><p key={j}>{p}</p>)}</article>)}<article className="premium-section"><h2>Independent practice · 20 questions</h2><button type="button" className="primary" onClick={()=>setShow(v=>!v)}>{show?'Hide practice':'Open practice'}</button>{show&&<div>{qs.map((x,i)=><div className="premium-example" key={i}><h3>{i+1}. {x.q}</h3><p><b>Skill:</b> {x.skill}</p>{x.options.map((o,k)=><button type="button" key={k} onClick={()=>setA(v=>({...v,[i]:k}))} style={{display:'block',margin:'8px 0'}}>{String.fromCharCode(65+k)}. {o}</button>)}{a[i]!==undefined&&<p><b>{a[i]===x.answer?'Correct.':'Not yet.'}</b> {x.why}</p>}</div>)}</div>}{onExercise&&<button type="button" className="primary" onClick={onExercise}>Continue to AVORA exercise mode →</button>}</article></section>}
