'use client';
import React,{useState} from 'react';

type Q={q:string;options:string[];answer:number;why:string;skill:string};
const qs:Q[]=[
{q:"What should a listener try to understand first from an oral passage?",options:["Every word exactly","The main idea","Only the title","The longest sentence"],answer:1,why:"The main idea is the central message. Details become easier to organise once the listener knows what the passage is mainly about.",skill:"Main idea"},
{q:"Before listening to a passage titled 'Saving Before Spending', what is the best prediction?",options:["It may discuss planning money and setting some aside","It must be about football","It will list English tenses","It cannot contain examples"],answer:0,why:"A sensible prediction uses the title and prior knowledge without pretending to know the passage already.",skill:"Prediction"},
{q:"A speaker says, 'The road was flooded, so commuters had to seek an alternative route.' What does alternative most likely mean?",options:["more expensive","another possible","dangerous","permanent"],answer:1,why:"The cause-and-effect context shows commuters needed another route because the usual one was flooded.",skill:"Context clues"},
{q:"Which is a supporting detail rather than a main idea?",options:["Budgeting helps people make better spending decisions.","A learner wrote down the price of transport before buying snacks.","The passage mainly explains responsible budgeting.","Planning money can reduce careless spending."],answer:1,why:"The learner's action is a specific example supporting the broader idea about budgeting.",skill:"Main idea vs detail"},
{q:"A speaker says slowly, 'Sadly, the fire destroyed everything the family owned.' Which mood is most likely?",options:["sorrowful","playful","excited","proud"],answer:0,why:"The word sadly and the loss described both support a sorrowful mood.",skill:"Mood"},
{q:"A principal says firmly, 'From Monday, every learner must be seated before assembly begins.' The tone is mainly…",options:["commanding/firm","joking","uncertain","celebratory"],answer:0,why:"The firm instruction and must indicate authority and seriousness.",skill:"Tone"},
{q:"A short radio message explains symptoms of malaria and tells listeners when to visit a clinic. Its likely purpose is to…",options:["inform and advise","entertain with a comedy","sell a school uniform","describe a football match"],answer:0,why:"The content gives health information and guidance, so informing/advising is the best-supported purpose.",skill:"Purpose"},
{q:"Why is listening for key words useful?",options:["Key words can signal important ideas and relationships","Every key word is always the answer","It removes the need to understand meaning","It allows the listener to ignore the speaker"],answer:0,why:"Important nouns, verbs, repeated terms and signal expressions can help a listener follow the structure and central ideas.",skill:"Listening strategy"},
{q:"Which note is best during a short oral passage?",options:["Write every sentence word for word","Write brief key ideas and important details","Stop listening while making full paragraphs","Write only unfamiliar words"],answer:1,why:"Brief notes reduce memory load without making the learner stop listening to the continuing passage.",skill:"Note-taking"},
{q:"The speaker says, 'Although Musa was exhausted, he continued working until the task was complete.' Exhausted most likely means…",options:["very tired","very rich","confused","angry"],answer:0,why:"Continuing to work despite the condition suggests he was very tired.",skill:"Context clues"},
{q:"Which question best tests the main idea?",options:["What colour was the speaker's bag?","What is the passage mainly explaining?","How many letters are in the title?","What was the third word spoken?"],answer:1,why:"A main-idea question asks for the central message rather than a minor detail.",skill:"Question generation"},
{q:"Which is an inference?",options:["Repeating an exact sentence from the audio","Using clues in the passage to reach a reasonable conclusion not stated directly","Guessing without evidence","Changing the speaker's words"],answer:1,why:"Inference combines what is heard with logical clues to understand an implied meaning.",skill:"Inference"},
{q:"If you miss one word while listening, what should you usually do?",options:["Stop listening completely","Keep following the surrounding ideas and use context","Assume the passage is impossible","Invent the word"],answer:1,why:"Good listeners maintain the flow. Later context may reveal the missed word's meaning or show that it was not essential.",skill:"Listening resilience"},
{q:"A passage lists forced begging, hawking and exploitative labour after discussing human trafficking. These are most likely…",options:["examples supporting the topic","unrelated jokes","titles of books","verb tenses"],answer:0,why:"They are examples that develop the broader issue rather than separate main ideas.",skill:"Organisation"},
{q:"Which clue can help identify tone?",options:["Word choice, pace, emphasis and intonation","Only the speaker's name","Only the passage length","Only punctuation on a transcript"],answer:0,why:"Tone is heard through how something is said as well as the words selected.",skill:"Tone"},
{q:"A speaker describes neighbours from different backgrounds solving a community problem together and repeatedly stresses respect. The likely central idea is…",options:["peaceful coexistence benefits a community","all neighbours must have the same background","problems should be ignored","respect prevents people from cooperating"],answer:0,why:"The repeated emphasis on cooperation and respect supports peaceful coexistence as the central idea.",skill:"Main idea"},
{q:"Why preview 3–5 key words before listening?",options:["To activate likely meanings and reduce vocabulary barriers","To reveal every answer","To replace listening","To memorise a dictionary"],answer:0,why:"NERDC's activity uses vocabulary preview so learners can predict meanings before hearing the words in context.",skill:"Pre-listening"},
{q:"Which student-generated question is strongest after a passage about tax?",options:["Why does the speaker say tax supports public services?","Was the passage made of words?","Did somebody speak?","Is tax a three-letter word?"],answer:0,why:"A useful comprehension question targets an important idea and requires understanding of the passage.",skill:"Question generation"},
{q:"A speaker begins calmly but becomes urgent when describing an approaching danger. What should a careful listener notice?",options:["The change in tone may signal increasing seriousness","Tone never changes meaning","Only the first sentence matters","Urgency proves the speaker is angry"],answer:0,why:"Changes in pace, emphasis and intonation can reveal how the speaker's attitude or urgency develops.",skill:"Tone shift"},
{q:"What is the strongest evidence that you understood an oral passage?",options:["You heard every sound","You can explain its main idea, important details, implied meanings, tone and purpose accurately","You copied the title","You remember one unusual word"],answer:1,why:"Comprehension is demonstrated by constructing the meaning of the passage, not merely hearing its sounds.",skill:"Mastery"}
];

const sections=[
["1. Listening is more than hearing",["Hearing happens when sound reaches your ears. Listening for comprehension means deliberately attending to spoken language and constructing meaning from it.","In Oral Comprehension, your job is not to memorise every sentence. You listen for the central message, important supporting information, relationships between ideas, clues to unfamiliar vocabulary, and what the speaker's voice and language reveal.","A strong listener can later explain what the passage was mainly about and support that explanation with what was actually heard."]],
["2. Before listening: prediction",["NERDC asks learners to participate in prediction before hearing the passage. Prediction prepares the mind; it is not pretending to know the answer.","If the title is 'Budgeting for Better Savings and Spending Decisions', you might predict that the passage will mention income, needs, wants, saving or planning expenditure. These are hypotheses. While listening, you confirm, modify or reject them.","Good prediction uses the title and prior knowledge. Poor prediction invents details and then forces the passage to fit them."]],
["3. Before listening: vocabulary preview",["NERDC recommends previewing three to five key words. First attempt their meanings, then listen for how the speaker uses them.","Context may define a word directly, give an example, contrast it with another idea, show a cause and effect, or surround it with familiar words that narrow the meaning.","The goal is not to stop at a dictionary definition. Ask: what does this word mean HERE?"]],
["4. First listening: catch the big picture",["On the first listening, resist the temptation to chase every small detail. Ask: Who or what is being discussed? What is the central issue? What does the speaker mainly want me to understand?","A main idea is broad enough to cover the important parts of the passage but specific enough to say something meaningful about them.","For example, if a passage gives several examples of how planning transport, food and savings helps a learner use pocket money responsibly, the main idea is not 'transport'. Transport is one supporting detail."]],
["5. Main idea and supporting details",["The main idea is the central message. Supporting details explain, illustrate, prove or develop it.","Imagine an oral passage says a school improved discipline by making rules clear, rewarding punctuality and applying fair consequences. 'The school used several consistent measures to improve discipline' captures the whole passage. 'The school rewarded punctuality' is only one detail.","A useful check is: does my proposed main idea cover most of the important information, or only one sentence?"]],
["6. Second listening: listen for important details",["Once you understand the big picture, listen again for names, reasons, causes, effects, examples, sequence, comparisons, numbers or other details that develop it.","Do not write full sentences while the audio continues. Brief notes such as 'save first → emergency fund' or 'late coming ↓ after rule' preserve meaning without stealing too much attention.","Details matter because they let you justify your understanding instead of guessing."]],
["7. Signal words help you follow structure",["Speakers often signal relationships. 'First', 'next' and 'finally' show sequence. 'Because' and 'therefore' connect cause and result. 'However' signals contrast. 'For example' introduces support. 'The main reason' signals importance.","When you hear a signal word, do not merely memorise it. Ask what relationship it is announcing between ideas."]],
["8. Inferring unfamiliar words from context",["To infer means to reach a reasonable meaning from clues. Suppose you hear: 'The family was destitute; they had no money for food, rent or school materials.' Even if destitute is unfamiliar, the examples strongly suggest extreme poverty.","Use a disciplined process: identify the unknown word; keep listening; collect clues around it; propose a meaning; substitute your meaning into the sentence; check whether the whole passage still makes sense.","Do not choose a meaning merely because it is a familiar definition of the word. Context controls meaning."]],
["9. Worked context example",["Listen to this sentence mentally: 'Because the bridge was unsafe, the council prohibited heavy vehicles from using it.' What might prohibited mean?","The reason is that the bridge is unsafe. The action affects whether heavy vehicles may use it. A sensible meaning is 'forbade' or 'did not allow'. Substitute it: 'the council did not allow heavy vehicles to use it.' The sentence remains logical.","That is context-based inference: clue → possible meaning → substitution → check."]],
["10. Explicit information and inference",["Some answers are stated directly. Others must be inferred. If a speaker says, 'Kemi took an umbrella because dark clouds had covered the sky,' the passage explicitly states that she took an umbrella. You may infer that she expected rain.","An inference must have evidence. 'Kemi was going to Lagos' would be an unsupported guess unless another clue points to Lagos.","Ask: which words in the passage support my conclusion? If you cannot point to a clue, reconsider the inference."]],
["11. Mood and tone are related but not identical",["Mood is the feeling or atmosphere created for the listener: joyful, tense, sorrowful, hopeful, frightening and so on. Tone is the speaker's attitude or manner toward the subject or audience: serious, angry, humorous, approving, doubtful, urgent, respectful and others.","A passage about a dangerous flood may create a tense mood while the newsreader maintains a serious, controlled tone.","Do not label mood or tone from one word alone. Combine word choice with pace, emphasis, intonation and the situation."]],
["12. How the voice gives clues",["A speaker may slow down to emphasise a warning, raise or lower pitch, stress important words, pause before a key point or change volume. These features can help reveal attitude and purpose.","Suppose a principal says firmly, 'This must stop today.' The modal 'must', the short sentence and firm emphasis support a commanding or serious tone.","But avoid over-reading. A loud voice does not automatically mean anger; context matters."]],
["13. Identifying the speaker's purpose",["Purpose answers: Why is the speaker communicating this? Common purposes include to inform, explain, persuade, advise, warn, instruct, entertain or describe.","A health announcement that lists symptoms and tells listeners when to seek medical care mainly informs and advises. An advertisement encouraging listeners to buy a product mainly persuades. A story told for amusement may mainly entertain.","Sometimes a passage has more than one purpose. Choose the purpose best supported by its dominant content and language."]],
["14. When you miss a word",["Real listening continues in time. You cannot always pause a teacher, radio announcement or conversation. If one word escapes you, do not abandon the next five sentences while worrying about it.","Keep listening for the surrounding idea. Ask whether the missing word is essential. Later information may clarify it. If you are allowed another listening, return to that section with a purpose.","This habit builds listening resilience and prevents one unfamiliar word from destroying comprehension of an entire passage."]],
["15. Effective note-taking",["Notes are memory supports, not transcripts. Record key nouns, actions, numbers, causes, effects and contrasts. Use arrows and abbreviations that you understand.","For example: 'budget → needs first → save 20% → wants later' is more useful during continuous listening than trying to write four polished sentences.","After listening, expand the notes in your own words. If you cannot explain a note, it may be too vague."]],
["16. Generating your own comprehension questions",["NERDC requires learners to generate questions for classmates. This is powerful because writing a good question requires you to decide what information matters.","Use several levels: direct detail—'What caused the delay?'; main idea—'What is the passage mainly about?'; vocabulary—'What does X mean as used in the passage?'; inference—'Why can we infer that…?'; tone/purpose—'Why does the speaker sound concerned?'","A weak question may test something trivial or unrelated. A strong question has an answer supported by the oral passage."]],
["17. Listening Passage A — Budgeting wisely",["FIRST LISTENING: Imagine this is being read aloud once. 'When thirteen-year-old Femi received his monthly allowance, he used to spend much of it during the first week. Transport fares, snacks and small online purchases quickly consumed the money. His older sister suggested a simple budget. Femi first wrote down essential expenses such as transport and school materials. Next, he set aside part of the allowance as savings before planning what remained for other wants. Two months later, an unexpected school project required materials. Instead of borrowing, Femi used part of his savings. He realised that budgeting was not about refusing every enjoyable purchase; it was about deciding in advance what mattered most.'","MAIN IDEA: A simple budget helped Femi control spending, save and prepare for an unexpected need. DETAILS: he previously spent early; listed essentials; saved before wants; later used savings for a school project. PURPOSE: mainly to explain, through an example, how budgeting supports better decisions.","CONTEXT: 'essential' is clarified by examples such as transport and school materials—things he needs. 'Consumed the money' does not mean ate it; context shows the purchases used up the money."]],
["18. Passage A — deeper listening questions",["Why did Femi change his spending method? Which action happened before he planned for wants? What event tested whether his savings were useful? What can you infer about his attitude to budgeting at the end?","Possible inference: at first he may have thought budgeting meant restriction, but by the end he understands it as planning priorities. The final sentence supports this; we are not inventing the inference.","Generate your own question now. Check that someone who heard the passage carefully could answer it from the passage or a reasonable inference from it."]],
["19. Listening Passage B — Peaceful coexistence",["'Two groups of residents used the same community field but often argued about when each group could hold activities there. At first, every disagreement ended with accusations. The community leader invited representatives from both groups to a meeting. Instead of deciding for them, she asked each group to explain its needs while the other listened without interruption. They discovered that most clashes occurred on only two evenings each week. Together they prepared a timetable and agreed on a procedure for requesting changes. In the following weeks, disagreements did not disappear completely, but they were handled without insults or threats.'","MAIN IDEA: respectful communication and agreed procedures helped the groups manage conflict peacefully. A detail such as 'two evenings' supports the explanation but is not the main idea.","TONE: measured and constructive rather than celebratory; the passage admits disagreements remained. PURPOSE: to show how listening, cooperation and an agreed process can support peaceful coexistence."]],
["20. Listening Passage C — Human trafficking awareness",["'A recruiter promised Chika's family that she would receive good training and safe work in another city. He insisted that they decide immediately and refused to give a clear address for the supposed employer. Chika's aunt became suspicious. She asked for written details and contacted a trusted organisation for advice. The organisation warned that traffickers sometimes use attractive promises to move people into exploitation such as forced labour, begging or sexual exploitation. The family stopped the arrangement and reported the recruiter.'","MAIN IDEA: suspicious recruitment promises and missing information can be warning signs, and seeking trusted help can prevent exploitation. PURPOSE: to inform and warn. TONE: serious and cautionary.","INFERENCE: the aunt did not know with certainty at first that the recruiter was a trafficker; 'became suspicious' shows she noticed warning signs and checked before acting. That distinction prevents us from claiming more than the passage states."]],
["21. Listening Passage D — Discipline in school",["'For several weeks, lateness increased at Unity Junior School. The principal initially reminded students during assembly, but the problem continued. The school then investigated why learners were late. Some admitted leaving home too late, while others said the gate became congested shortly before assembly. The school opened a second entry point and asked families to help learners plan earlier journeys. Teachers also began recognising classes with consistent punctuality. By the end of the month, lateness had fallen considerably.'","The passage does not say punishment alone solved the problem. Its central idea is that the school investigated causes and used several practical measures to improve punctuality.","This is why careful listeners separate what they actually heard from what they expected to hear."]],
["22. Three-pass listening strategy",["PASS 1 — GIST: What is this mainly about? Who is involved? What is happening? PASS 2 — DETAIL: What reasons, examples, sequence, causes, effects and key words matter? PASS 3 — INTERPRETATION: What can I infer? What is the tone, mood and purpose? Which answers can I support with evidence?","If only one listening is available, use the same priorities mentally: big picture first, important details next, interpretation from evidence.","This strategy prevents a learner from collecting isolated words without understanding the passage as a whole."]],
["23. Common mistakes",["Mistake: trying to remember every word. Repair: listen for meaning and structure. Mistake: choosing a main idea that is only one detail. Repair: test whether it covers the passage broadly. Mistake: guessing vocabulary from the word alone. Repair: collect surrounding clues.","Mistake: calling every serious passage 'angry'. Repair: distinguish serious, concerned, urgent, disapproving and other tones using evidence. Mistake: inventing an inference. Repair: point to the clue. Mistake: writing notes so long that you stop listening. Repair: shorten them.","Mistake: answering from prior knowledge instead of the passage. Repair: your answer must reflect what this speaker actually communicated."]],
["24. NERDC mastery task",["Choose or play a short oral passage on one of the NERDC suggested issues: religious tolerance; purposes/exploitation associated with human trafficking; budgeting; discipline in school; peaceful coexistence; or why citizens should pay tax.","Before listening, predict likely content and attempt 3–5 key vocabulary items. During listening, identify the main idea and important details. Afterwards, infer one unfamiliar word from context, describe the speaker's mood/tone and purpose with evidence, and write at least three comprehension questions for a classmate.","Mastery means you can do these things from spoken material—not merely explain the definitions of 'tone' and 'main idea' when no passage is playing."]]
] as const;

export default function JSS2OralComprehensionLesson({onExercise}:{onExercise?:()=>void}){
 const [practice,setPractice]=useState(false),[ans,setAns]=useState<Record<number,number>>({});
 return <section className="fractions-premium-lesson"><header className="premium-lesson-hero"><p className="lesson-kicker">JSS2 English Studies · Listening and Speaking</p><h1>Oral Comprehension</h1><p>Listen for meaning: predict, identify main ideas and details, infer vocabulary, interpret tone and purpose, and create strong comprehension questions.</p></header>
 <article className="premium-section"><h2>Learning objectives</h2><ul><li>Listen attentively to a short oral passage.</li><li>Identify its main idea and important supporting details.</li><li>Infer unfamiliar words from context.</li><li>Distinguish explicit information from reasonable inference.</li><li>Interpret mood, tone and speaker purpose using evidence.</li><li>Take brief useful listening notes.</li><li>Generate meaningful comprehension questions from an oral passage.</li></ul></article>
 {sections.map(([t,ps],i)=><article className="premium-section" key={i}><h2>{t}</h2>{ps.map((p,j)=><p key={j}>{p}</p>)}</article>)}
 <article className="premium-section"><h2>Independent practice · 20 questions</h2><p>The bank checks actual listening-comprehension concepts across prediction, gist, detail, context, inference, mood, tone, purpose, note-taking and question generation.</p><button type="button" className="primary" onClick={()=>setPractice(v=>!v)}>{practice?'Hide practice':'Open practice'}</button>{practice&&<div>{qs.map((x,i)=><div className="premium-example" key={i}><h3>{i+1}. {x.q}</h3><p><b>Skill:</b> {x.skill}</p>{x.options.map((o,k)=><button type="button" key={k} onClick={()=>setAns(a=>({...a,[i]:k}))} style={{display:'block',margin:'8px 0'}}>{String.fromCharCode(65+k)}. {o}</button>)}{ans[i]!==undefined&&<p><b>{ans[i]===x.answer?'Correct.':'Not yet.'}</b> {x.why}</p>}</div>)}</div>}{onExercise&&<button type="button" className="primary" onClick={onExercise}>Continue to AVORA exercise mode →</button>}</article></section>
}
