'use client';
import React,{useState} from 'react';
type Q={q:string;options:string[];answer:number;why:string;skill:string};
const qs:Q[]=[
{q:"What is a writer's purpose?",options:["The reason the writer produced the text","The number of paragraphs","The title only","The reader's favourite sentence"],answer:0,why:"Purpose is what the writer is trying to achieve through the text.",skill:"Meaning"},
{q:"A leaflet explains symptoms of an illness and where to seek help. Its main purpose is likely to…",options:["inform","annoy","entertain with fiction","hide information"],answer:0,why:"The text supplies factual guidance, so informing is strongly supported.",skill:"Inform"},
{q:"An advert says, 'Switch today and enjoy lower transfer charges.' Its purpose is mainly to…",options:["persuade","describe a historical event","irritate","summarise a novel"],answer:0,why:"The command and promised benefit encourage the reader to take an action.",skill:"Persuade"},
{q:"Which expression most clearly signals a warning?",options:["Act now before it is too late","Once upon a time","For example","The table has four legs"],answer:0,why:"The expression stresses danger and urgency.",skill:"Key expressions"},
{q:"Why should purpose be supported with evidence?",options:["The same topic can be written for different purposes","Every passage has the same purpose","Purpose depends only on length","Titles always state purpose directly"],answer:0,why:"Topic alone is insufficient; wording, selection of details and calls to action reveal intention.",skill:"Evidence"},
{q:"A road-safety article gives accident figures, explains causes, and urges drivers to slow down. Which answer is strongest?",options:["It informs and also persuades readers to adopt safer behaviour","It only entertains","It has no purpose","It aims to annoy every driver"],answer:0,why:"Texts may have more than one purpose; here information supports a persuasive safety message.",skill:"Multiple purposes"},
{q:"What does 'dissuade' mean?",options:["Discourage someone from doing something","Force someone to laugh","Give neutral information only","Describe scenery"],answer:0,why:"To dissuade is to persuade someone not to take a particular action.",skill:"Vocabulary"},
{q:"Which feature is strongest evidence of persuasive purpose?",options:["A clear call to action supported by reasons","A page number","A character's name","A comma"],answer:0,why:"Persuasive writing commonly gives reasons and seeks a response or change in belief/action.",skill:"Persuasion"},
{q:"A writer presents a difficult question, gives contrasting viewpoints and leaves readers to consider them. The purpose may be to…",options:["stimulate thought","give cooking instructions","annoy deliberately","list phone numbers"],answer:0,why:"Inviting reflection without demanding one conclusion can stimulate thought.",skill:"Stimulate thought"},
{q:"Which is an inference about purpose?",options:["Using clues in the text to conclude what the writer aims to achieve","Copying the title","Counting words","Guessing without reading"],answer:0,why:"Purpose is often inferred from textual evidence rather than explicitly announced.",skill:"Inference"},
{q:"Why can prior experience help?",options:["It helps readers recognise familiar situations and likely communicative aims, but textual evidence must still confirm the inference","It allows readers to ignore the text","It guarantees every guess","It replaces key expressions"],answer:0,why:"Prior knowledge is useful when checked against the actual passage.",skill:"Prior experience"},
{q:"Which sentence most likely aims to convince?",options:["Because helmets reduce the risk of serious head injury, every rider should wear one.","The helmet is on the table.","Yesterday was Monday.","The story has six paragraphs."],answer:0,why:"It supplies a reason and a recommended conclusion.",skill:"Convince"},
{q:"A humorous story about a student's embarrassing mistake mainly makes readers laugh. Its purpose is likely to…",options:["entertain","indoctrinate","give first-aid instructions","dissuade from banking"],answer:0,why:"Humorous narrative features support entertainment as the dominant purpose.",skill:"Entertain"},
{q:"What is wrong with deciding purpose from topic alone?",options:["A writer can inform, persuade, warn or entertain about the same topic","Topics never matter","Purpose is always hidden","Every topic has one fixed intention"],answer:0,why:"Purpose depends on how and why the topic is presented.",skill:"Reasoning"},
{q:"An article repeatedly uses 'must', 'should' and 'we cannot continue like this'. What should a reader do?",options:["Treat them as clues and examine the surrounding argument for persuasive intention","Assume entertainment immediately","Ignore them","Decide only from font size"],answer:0,why:"Modal verbs and urgent evaluative language can point toward persuasion, but context confirms the purpose.",skill:"Language clues"},
{q:"Which statement about writer's purpose is correct?",options:["A text can have a main purpose and secondary purposes","Every text has exactly one possible effect","Purpose and topic are identical","The reader's reaction always proves the writer's intention"],answer:0,why:"A text may inform while also persuading, for example; identify the dominant aim from evidence.",skill:"Multiple purposes"},
{q:"A writer describes corruption using strongly disapproving words and urges citizens to report it. The dominant purpose is likely to…",options:["persuade/dissuade readers from tolerating corruption","entertain only","teach pronunciation","describe weather"],answer:0,why:"Evaluative language plus a call to action indicates an attempt to influence attitudes and behaviour.",skill:"Contemporary issues"},
{q:"Which is the best evidence statement in an answer?",options:["The writer aims to warn readers because expressions about 'serious risk' and 'protect yourself now' stress danger and urgent action.","I just feel it is a warning.","The passage is long.","My friend chose warning."],answer:0,why:"A strong answer names the purpose and connects it to specific textual clues.",skill:"Evidence"},
{q:"What does 'indoctrinate' most closely mean in this lesson?",options:["Seek to make people accept a set of beliefs, often without encouraging critical examination","Tell a joke","Give directions to a shop","Summarise neutrally"],answer:0,why:"NERDC lists indoctrinate as a possible intention; the term refers to inculcating beliefs in a one-sided way.",skill:"Vocabulary"},
{q:"What demonstrates mastery?",options:["Identifying a writer's likely purpose in a new passage and justifying it with key expressions and relevant context","Memorising a list of purposes only","Guessing from the title","Always answering 'to inform'"],answer:0,why:"NERDC expects learners to identify expressions pointing to intention and infer purpose from passages.",skill:"Mastery"}
];
const sections=[
["1. Topic is not the same as purpose",["A topic tells you WHAT a text is about. Purpose tells you WHY the writer wrote it.","Two writers may both discuss road safety. One may explain traffic rules to inform readers. Another may urge motorcyclists to wear helmets, mainly to persuade. A third may tell a humorous fictional story set on a road, mainly to entertain.","Therefore, never answer a purpose question merely by naming the subject."]],
["2. What is a writer's purpose?",["A writer's purpose or intention is the effect or response the writer is trying to achieve through the text: perhaps to give information, change an opinion, encourage or discourage an action, entertain, please, provoke thought, or communicate another intention.","Writers do not always announce, 'My purpose is to persuade you.' Readers infer purpose from the writer's choices.","Your conclusion should therefore follow evidence: purpose → key words/expressions → explanation of how they reveal the intention."]],
["3. NERDC purposes you must recognise",["The curriculum specifically gives purposes such as: to persuade, inform, convince, irritate, annoy, please, entertain, dissuade, stimulate thought or indoctrinate.","These words are not interchangeable. INFORM gives knowledge or explanation. PERSUADE/CONVINCE seeks acceptance of a view or action. DISSUADE seeks to discourage an action. ENTERTAIN seeks enjoyment. STIMULATE THOUGHT invites reflection.","IRRITATE or ANNOY describes an intention to provoke displeasure; PLEASE seeks a favourable or enjoyable response. INDOCTRINATE seeks acceptance of a body of beliefs, typically through one-sided inculcation rather than open critical examination."]],
["4. Purpose is inferred from clues",["Look for repeated ideas, commands, questions, emotional language, facts and statistics, explanations, humour, warnings, promises, praise, criticism and calls to action.","No single word is magical. 'Should' often appears in persuasion, but you must read the sentence and passage. 'The teacher explained that drivers should stop at red lights' may simply report information.","Use clusters of evidence, not isolated guessing."]],
["5. Key words and expressions",["Persuasive clues may include 'you should', 'we must', 'act now', 'the best choice', 'do not allow'. Informative clues may include definitions, explanations, factual descriptions, sequences and neutral examples.","Warning/dissuasion may use 'danger', 'risk', 'avoid', 'never', 'protect yourself', 'before it is too late'. Thought-provoking texts may ask difficult questions, compare positions or leave a challenge for reflection.","The important skill is not memorising phrases; it is explaining what the phrases DO in that particular passage."]],
["6. Inform",["A writer who informs mainly helps readers know or understand something. An article might explain how electronic banking works, describe first-aid steps, or present causes of inflation.","Informative writing can still contain opinions or recommendations, but ask what dominates the text.","Example: 'Electronic transfers allow customers to send money between accounts without exchanging physical cash.' This sentence primarily explains."]],
["7. Persuade and convince",["Persuasive writing seeks to influence belief, attitude or action. It often combines a claim with reasons, evidence, benefits, consequences or a call to action.","Example: 'Every rider should wear a helmet because it greatly reduces exposure to serious head injury during a crash.' The writer states what readers should do and gives a reason.","To CONVINCE is closely related: the writer attempts to make the reader accept a claim as reasonable or true."]],
["8. Dissuade",["To dissuade is to persuade someone NOT to do something.","Example: 'Do not give your bank password or one-time code to anyone who calls you, no matter how urgent the request sounds.' The writer seeks to prevent unsafe behaviour.","When identifying dissuasion, state the action the writer wants the reader to avoid."]],
["9. Entertain and please",["A text designed mainly to entertain may use humour, suspense, imaginative events, engaging characters or playful language. A writer may seek to please through enjoyable, reassuring or appreciative language.","Do not assume every story is only entertainment. A story can also teach, persuade or stimulate thought. Examine what dominates and how the ending functions.","Likewise, a factual text can contain a joke without entertainment becoming its main purpose."]],
["10. Stimulate thought",["Some writers want readers to examine an issue rather than immediately accept a command. They may present a dilemma, ask probing questions, contrast viewpoints or reveal consequences.","Example: 'If technology can make decisions faster than humans, which decisions should humans never surrender to machines?' The question invites reflection.","A thought-provoking passage may still lean toward a position; identify whether reflection itself or persuasion is dominant."]],
["11. Irritate or annoy",["NERDC includes irritate and annoy among possible intentions. A writer may deliberately use taunting, provocative or repetitive language to upset or provoke a target.","Be careful: a text that annoys YOU was not necessarily written in order to annoy. Reader reaction and writer intention are different.","To justify this purpose, find evidence that deliberate provocation is part of the writer's communicative strategy."]],
["12. Indoctrinate",["NERDC also lists indoctrinate. In this context, it means seeking to make people accept a set of beliefs or ideas, often through repeated one-sided presentation that does not encourage critical examination.","Do not label ordinary persuasion as indoctrination simply because you disagree with it. Look for sustained insistence on unquestioned acceptance and exclusion of alternatives.","This distinction develops critical reading: identify what the text is doing rather than attacking the writer."]],
["13. Main and secondary purposes",["A passage can have more than one purpose. A road-safety article may INFORM readers about accident causes and PERSUADE them to slow down.","When a question asks for THE writer's purpose, identify the dominant purpose—the aim that best explains the text as a whole.","Then mention a secondary purpose only if it improves the answer and is supported by evidence."]],
["14. Purpose versus effect",["A writer may intend to make readers laugh, yet one reader may not find the text funny. The reader's reaction does not automatically change the writer's likely purpose.","Similarly, a persuasive advert may fail to convince you. Its purpose can still be persuasion.","Infer intention from textual design, not merely from whether the intended effect worked on you."]],
["15. Prior experience as a clue",["NERDC asks learners to recount prior experience to infer intention. If you have seen advertisements before, you may recognise price offers, commands and promises as persuasive features. If you have read safety notices, you may recognise warnings and prohibited actions.","Prior experience gives you a hypothesis, not the final answer. Confirm it from the actual passage.","Strong reading combines what you already know with what the writer actually wrote."]],
["16. Worked Passage A — electronic banking",["'Why spend valuable time carrying cash from one place to another? With QuickPay, you can transfer funds in seconds from your phone. Register today and enjoy your first five transfers without service charges.'","TOPIC: electronic banking. PURPOSE: mainly to persuade readers to register for the service. CLUES: rhetorical question, direct address 'you', promised benefit, and command 'Register today'.","It contains information about transfers, but that information supports the larger persuasive aim."]],
["17. Worked Passage B — first aid",["'A minor burn should first be cooled under clean, cool running water for an appropriate period. Do not apply substances such as butter or toothpaste. If the burn is severe or covers a large area, seek professional medical attention.'","TOPIC: first aid for burns. PURPOSE: mainly to inform/instruct readers about immediate actions and warn against unsafe responses.","CLUES: procedural statements, direct safety instruction and conditions for seeking further help. The passage is not selling a product or telling a story."]],
["18. Worked Passage C — road safety",["'Last year, our community recorded several crashes near the school gate. Drivers, reducing your speed for this short stretch can protect children crossing the road. Slow down before another family receives terrible news.'","PURPOSE: mainly to persuade drivers to slow down and warn them about consequences. CLUES: direct address 'Drivers', recommendation, emotional consequence and urgent imperative 'Slow down'.","The accident information supports the persuasion; it is not merely presented for neutral knowledge."]],
["19. Worked Passage D — environmental issue",["'Each rainy season, plastic waste appears again in the drainage channel. We clear it, photograph the clean street and celebrate. Weeks later, the drain is blocked again. Are we solving the problem, or only cleaning the evidence of our habits?'","PURPOSE: to stimulate thought about waste behaviour, with an implied challenge to change. CLUES: contrast between repeated cleaning and repeated blockage, plus the final reflective question.","A reader may also feel persuaded to change behaviour, but the passage's method strongly foregrounds reflection."]],
["20. Contemporary issues and neutral analysis",["NERDC suggests passages on inflation, HIV/AIDS, human trafficking risks, food risks, first aid, environmental issues, mobile communication, e-banking, corruption and road safety.","These topics can carry strong feelings. Your task is still textual: identify what this writer is trying to do in this passage and prove it from language.","Do not replace analysis with your personal opinion about the issue."]],
["21. A reliable four-step method",["STEP 1 — Identify the topic. STEP 2 — Ask what response the writer appears to want: know, believe, do, avoid, enjoy, reflect? STEP 3 — underline key expressions and structural features that support that answer. STEP 4 — explain the connection.","Answer frame: 'The writer's main purpose is to ____. This is shown by expressions such as ____ and ____, which ____.'","This structure prevents unsupported one-word answers."]],
["22. Weak versus strong answers",["WEAK: 'The purpose is to persuade because I think so.' STRONG: 'The writer aims to persuade residents to stop dumping waste because the commands “Use the bins” and “Keep refuse out of the drains” directly call for changed behaviour.'","WEAK: 'It is about malaria.' That gives the topic, not the purpose. STRONG: 'The writer informs readers about malaria prevention by explaining how mosquito nets and removal of stagnant water reduce exposure.'","Always connect purpose to evidence."]],
["23. Group investigation",["In a group, read one advertisement, one newspaper extract and one informational article. Each learner first decides the likely purpose independently.","Compare answers. Where you disagree, quote the expressions that support your interpretation. Decide which explanation accounts for the most important features of the whole text.","Then present the group's conclusion: topic, dominant purpose, key evidence and explanation."]],
["24. Error clinic",["ERROR: purpose = topic. REPAIR: ask WHY the writer discusses the topic. ERROR: choosing purpose from one word. REPAIR: use multiple clues and the whole passage. ERROR: 'It annoyed me, so the writer intended to annoy.' REPAIR: separate effect from intention.","ERROR: calling every text informative because it contains facts. REPAIR: ask what the facts are being used to achieve. ERROR: calling every command persuasive without context. REPAIR: inspect the surrounding communicative situation.","ERROR: using prior experience to overwrite the passage. REPAIR: prior knowledge suggests possibilities; textual evidence decides."]],
["25. Guided practice",["Passage: 'Fraudsters sometimes send messages claiming that your bank account will be closed immediately unless you reveal a code. A genuine security practice is never to disclose your password or one-time code to an unknown caller. If you receive a suspicious message, contact your bank through an official channel.'","TOPIC: e-banking security. Likely purposes: to inform readers about a fraud pattern, warn them, and dissuade them from revealing security information. Dominant aim can reasonably be expressed as warning/advising against unsafe disclosure.","Evidence includes 'never disclose', 'suspicious message' and the instruction to use an official channel."]],
["26. Mastery task",["Choose a fresh JSS2-appropriate newspaper extract, advertisement or article. State the topic separately from the purpose. Identify at least two expressions that reveal intention. Explain exactly how each expression supports your inference.","Then ask whether a secondary purpose is present and whether prior experience helped you recognise the text type. Keep your conclusion anchored in the passage.","Mastery means you can infer purpose in unfamiliar texts—not merely recite the list of purposes."]]
] as const;
export default function JSS2WritersPurposeLesson({onExercise}:{onExercise?:()=>void}){const[show,setShow]=useState(false),[a,setA]=useState<Record<number,number>>({});return <section className="fractions-premium-lesson"><header className="premium-lesson-hero"><p className="lesson-kicker">JSS2 English Studies · Reading</p><h1>Reading to Understand the Writer's Purpose</h1><p>Discover why a text was written by tracing key words, expressions, structure and context—not by guessing from the topic alone.</p></header><article className="premium-section"><h2>Learning objectives</h2><ul><li>Distinguish a text's topic from its writer's purpose.</li><li>Recognise purposes specified by NERDC, including informing, persuading, convincing, entertaining, dissuading and stimulating thought.</li><li>Identify words and expressions that point to intention.</li><li>Use prior experience carefully to infer purpose.</li><li>Recognise that a text may have dominant and secondary purposes.</li><li>Justify an inference about purpose with textual evidence.</li></ul></article>{sections.map(([t,ps],i)=><article className="premium-section" key={i}><h2>{t}</h2>{ps.map((p,j)=><p key={j}>{p}</p>)}</article>)}<article className="premium-section"><h2>Independent practice · 20 questions</h2><button type="button" className="primary" onClick={()=>setShow(v=>!v)}>{show?'Hide practice':'Open practice'}</button>{show&&<div>{qs.map((x,i)=><div className="premium-example" key={i}><h3>{i+1}. {x.q}</h3><p><b>Skill:</b> {x.skill}</p>{x.options.map((o,k)=><button type="button" key={k} onClick={()=>setA(v=>({...v,[i]:k}))} style={{display:'block',margin:'8px 0'}}>{String.fromCharCode(65+k)}. {o}</button>)}{a[i]!==undefined&&<p><b>{a[i]===x.answer?'Correct.':'Not yet.'}</b> {x.why}</p>}</div>)}</div>}{onExercise&&<button type="button" className="primary" onClick={onExercise}>Continue to AVORA exercise mode →</button>}</article></section>}
