// @ts-nocheck
'use client';
import React,{useState} from 'react';

type Q={q:string;options:string[];answer:number;why:string;skill:string};
const questions:Q[]=[
{q:"What is a debate?",options:["A quarrel in which people insult one another","A formal discussion in which opposing sides present reasons on a motion","A story read aloud by two people","A private conversation"],answer:1,why:"A debate is organised around a motion and opposing positions. Speakers support their positions with reasons rather than personal attacks.",skill:"Meaning of debate"},
{q:"The statement being argued about in a debate is called the…",options:["motion","posture","register","vote"],answer:0,why:"The motion is the proposition or statement that the two sides debate.",skill:"Terminology"},
{q:"Which side supports the motion?",options:["Opposition","Proposition","Audience","Timekeeper"],answer:1,why:"The proposition (or proposing side) argues for the motion; the opposition argues against it.",skill:"Roles"},
{q:"What is the chairperson's main duty?",options:["To argue for both sides","To control proceedings and call speakers in order","To decide every speaker's opinion","To provide all evidence"],answer:1,why:"The chairperson/moderator manages the procedure fairly, introduces the motion and calls speakers.",skill:"Procedure"},
{q:"Which is the best formal opening?",options:["Guys, listen to me.","Mr Chairman, panel of judges, co-debaters, ladies and gentlemen…","You people must agree with me.","Hey! My opponents are wrong."],answer:1,why:"A formal debate uses respectful forms of address and an appropriate public-speaking register.",skill:"Register"},
{q:"Which is a developed argument?",options:["Homework is bad. That's all.","Homework should be reduced because excessive tasks can remove time needed for rest; for example, a learner who works late every night may arrive tired for class.","I hate homework.","Everybody knows homework is useless."],answer:1,why:"A developed argument gives a clear point, explains it and supports it with a relevant example or evidence.",skill:"Argument development"},
{q:"What is a rebuttal?",options:["A greeting at the start","A reasoned response that challenges an opposing argument","The final vote","A gesture"],answer:1,why:"A rebuttal listens to a specific opposing claim and explains why it is weak, incomplete or outweighed.",skill:"Rebuttal"},
{q:"Which response disagrees respectfully?",options:["That is nonsense.","You clearly know nothing.","I understand that point; however, it overlooks the cost to families.","Keep quiet."],answer:2,why:"Debate attacks ideas, not people. Formal disagreement acknowledges the claim and responds to it calmly.",skill:"Respectful register"},
{q:"Why should a speaker define important words in a motion?",options:["To waste time","To make clear what the team understands the motion to mean","To avoid giving arguments","To replace the chairperson"],answer:1,why:"A clear definition fixes the meaning being debated and reduces confusion.",skill:"Motion analysis"},
{q:"Which sentence uses tense consistently?",options:["Yesterday the team prepares its points and presented them.","Yesterday the team prepared its points and presented them.","Yesterday the team will prepare its points and presented them.","Yesterday the team preparing its points."],answer:1,why:"Both completed actions happened yesterday, so the simple past is appropriate for both verbs.",skill:"Tense control"},
{q:"Which body language is most suitable?",options:["Turning your back on the audience","Pointing aggressively at opponents","Standing confidently, making natural eye contact and using controlled gestures","Reading every word with your head down"],answer:2,why:"Controlled posture, eye contact and purposeful gestures support clear, respectful delivery.",skill:"Non-verbal delivery"},
{q:"A speaker says, 'School uniforms reduce distraction.' What should normally come next?",options:["A reason or example explaining the claim","An insult","An unrelated joke","The final vote"],answer:0,why:"A claim becomes persuasive when it is developed with reasoning and support.",skill:"Argument development"},
{q:"Which is evidence rather than a bare assertion?",options:["Phones are terrible.","I just know phones are bad.","Our class record showed that repeated phone interruptions reduced time available for the lesson.","Anyone who disagrees is wrong."],answer:2,why:"Evidence supplies information or an example that can support a claim; the other options merely assert.",skill:"Evidence"},
{q:"Why must a debater listen while the other side speaks?",options:["Only to wait for time to pass","To identify claims that may require a rebuttal","To copy every sentence","Because the speaker must agree"],answer:1,why:"Rebuttal depends on accurately hearing and understanding the opponent's actual argument.",skill:"Active listening"},
{q:"Which sentence links an argument back to a motion about limiting phones in class?",options:["That is my second point.","Therefore, limiting phones during lessons would protect learning time.","Phones come in many colours.","Thank you for listening."],answer:1,why:"The sentence explains how the preceding reasoning supports the team's position on the motion.",skill:"Linking"},
{q:"Which statement is a personal attack rather than a rebuttal?",options:["That claim ignores learners who lack internet access.","The evidence given does not show that the policy works.","My opponent is foolish, so her point is wrong.","That example concerns adults, not JSS learners."],answer:2,why:"Calling the opponent foolish attacks the person. A proper rebuttal addresses the reasoning or evidence.",skill:"Debate ethics"},
{q:"What is the purpose of a conclusion?",options:["To introduce an entirely new case","To summarise the strongest case and reinforce the team's position","To insult the opposition","To change the motion"],answer:1,why:"A conclusion brings the case together and reminds listeners why the team's position follows from its main arguments.",skill:"Speech structure"},
{q:"Which order is strongest for one argument?",options:["Example → unrelated story → claim","Point → explanation → evidence/example → link to motion","Greeting → vote → motion","Insult → repetition → conclusion"],answer:1,why:"The sequence develops an idea logically instead of leaving it as an unsupported assertion.",skill:"Argument structure"},
{q:"The motion is 'Students should wear uniforms every school day.' Which point is relevant?",options:["Uniforms may reduce visible clothing competition among learners.","Nigeria has many rivers.","Football has eleven players.","Some fruits contain seeds."],answer:0,why:"A relevant argument must bear directly on whether students should wear uniforms every school day.",skill:"Relevance"},
{q:"Which speaker behaviour best shows respect?",options:["Interrupting whenever you disagree","Listening, waiting for your turn and responding to the idea","Laughing at a mistake","Refusing to address the chair"],answer:1,why:"Respect is shown through attentive listening, orderly participation and idea-focused responses.",skill:"Debate conduct"},
{q:"If the motion says 'AI does more harm than good in education', the proposition must mainly…",options:["show why educational harms outweigh benefits","list every type of computer","argue that AI has no uses anywhere","change the topic to social media"],answer:0,why:"The proposition must address the comparison made by the motion: harm versus good in education.",skill:"Motion analysis"},
{q:"Which phrase signals a counter-argument?",options:["First, let me define…","The opposition may argue that…, but…","Good morning everyone.","In conclusion…"],answer:1,why:"It explicitly introduces an opposing view before responding to it.",skill:"Rebuttal language"},
{q:"A good debater discovers that an opponent made a strong point. What should the debater do?",options:["Pretend it was never said","Misquote it","Acknowledge it accurately, then explain its limitation or why another consideration outweighs it","Attack the speaker"],answer:2,why:"Fair debate engages the strongest version of an opposing point and answers it with reasoning.",skill:"Critical listening"},
{q:"Which performance shows mastery of the NERDC Debate topic?",options:["Memorising the definition only","Naming proposition and opposition only","Explaining procedure and elements, using suitable language and delivery, and participating in a structured debate","Writing a story about a debate"],answer:2,why:"NERDC requires both knowledge of debate and actual engagement using appropriate register and delivery.",skill:"Mastery"}
];

const sections=[
["1. What a debate really is",["A debate is a formal, organised discussion of a stated issue. The issue is expressed as a motion. One side—the proposition—supports the motion; the other side—the opposition—argues against it.","A debate is not the same as a quarrel. In a quarrel, people may react emotionally or attack one another. In a debate, speakers are expected to give reasons, listen, respond to ideas and respect the procedure.","The goal is not simply to speak loudly. A strong debater makes a position understandable and supports it so that an audience can judge the reasoning."]],
["2. Essential vocabulary before we proceed",["Motion: the statement to be debated. Proposition: the side supporting the motion. Opposition: the side arguing against it. Chairperson or moderator: the person who controls proceedings. Speaker: a person presenting a case. Audience or house: listeners who may later contribute or vote.","Argument: a reasoned point supporting a position. Evidence: information, facts, examples or experience used to support a point. Counter-argument: an argument from the other side. Rebuttal: a reasoned response to an opposing argument. Conclusion or summing-up: the closing stage that brings the case together.","These words have different jobs. For example, a rebuttal is not simply another prepared argument; it responds to something the other side has actually said."]],
["3. Understanding the motion",["Before preparing points, read the motion carefully. Ask: What exactly is being proposed? Which words need clarification? What must the proposition show? What must the opposition challenge?","Example motion: “Students should not use mobile phones during lessons.” The debate is not about whether phones exist or whether all technology is bad. The key question is whether phone use during lessons should be restricted.","A team that misunderstands the motion may speak confidently but still fail to address the real issue."]],
["4. The people and their responsibilities",["The chairperson opens the debate, states the motion, calls speakers in the agreed order, maintains order and helps enforce time. The chairperson should be fair rather than secretly debating for one side.","The proposition speakers build the case for the motion. The opposition speakers build the case against it. Supporting speakers develop further reasons and respond to the other side. A timekeeper helps speakers obey the agreed time. The audience listens critically and may contribute if the format allows.","Teamwork matters: speakers should not merely repeat one another. Each speaker should know which part of the team's case he or she will develop."]],
["5. A clear classroom debate procedure",["A practical JSS2 procedure is: the chairperson calls the meeting to order and announces the motion; the first proposition speaker presents the opening case; the first opposition speaker responds and presents the opposing case; supporting speakers alternate; the floor may be opened for further contributions; the principal speakers sum up; then the audience or judges decide according to the agreed rules.","Different schools may use slightly different debate formats. The important JSS2 skill is to understand and follow the chosen procedure consistently.","Time limits create fairness. A speaker should plan a speech that fits the available time instead of rushing at the end."]],
["6. Formal register: language that fits a debate",["Register means the kind of language suitable for a particular situation. A classroom debate is more formal than chatting with friends. A speaker may begin, “Mr Chairman, panel of judges, co-debaters, ladies and gentlemen…” and then state a clear position.","Useful expressions include: “I rise to support the motion…”, “I rise to oppose the motion…”, “My first reason is…”, “The opposition has argued that…, however…”, “I respectfully disagree because…”, and “For these reasons, I urge the house to support/oppose the motion.”","Avoid insults, slang that weakens clarity, threats and statements about the opponent's character. Debate the idea, not the person."]],
["7. Grammar matters: sentences and tenses",["NERDC includes appropriate words, sentences and tenses among the elements of debate. Grammar is therefore part of successful delivery, not a separate decoration.","Use complete, clear sentences. Keep tense consistent with time: “Last year the school introduced…” describes a past event; “Students currently use…” describes a present situation; “The policy will reduce…” makes a future claim.","Pronouns should also remain clear. If “they” could refer to teachers or students, name the group instead. Precision prevents the audience from guessing what you mean."]],
["8. Building an argument instead of making an assertion",["A bare assertion is only a claim: “School uniforms are good.” A developed argument explains why the claim matters and supports it.","Use a learner-friendly chain: POINT → EXPLAIN → SUPPORT → LINK. Point: state the reason. Explain: show how or why it works. Support: give a relevant example, fact or experience. Link: connect the reasoning back to the motion.","Example: Point—uniforms can reduce visible clothing competition. Explain—when everyone wears similar school clothing, fashion differences are less prominent during lessons. Support—a learner is less likely to be judged in class for not wearing an expensive casual outfit. Link—therefore uniforms can help keep attention on school rather than clothing competition."]],
["9. Evidence: what counts as support?",["Evidence does not mean inventing impressive numbers. A learner may use a verifiable fact, a relevant example, an observation, a comparison or information obtained from a reliable source.","Ask three questions: Is it relevant to my point? Is it believable or verifiable? Have I explained how it supports my point? Evidence without explanation can still leave the audience unsure why it matters.","Never invent a survey, expert or percentage merely to sound convincing. If you do not know a statistic, use an honest example or explain the reasoning directly."]],
["10. Listening and rebuttal",["Debating is also listening. While the other side speaks, identify the exact claim, the reason offered and the support given. Then decide what really needs an answer.","A useful rebuttal pattern is: ACCURATELY STATE THE CLAIM → IDENTIFY THE PROBLEM → EXPLAIN WHY → RETURN TO THE MOTION.","Example: “The opposition argues that phones always improve research. Phones can provide information, but this does not show that unrestricted use during a lesson improves learning. Notifications and unrelated apps can interrupt the same lesson. Therefore the research benefit does not by itself justify unrestricted classroom use.”"]],
["11. Weak rebuttal versus strong rebuttal",["Weak: “That is wrong.” Nothing has been explained. Weak: “My opponent does not understand school.” That attacks a person. Weak: repeating your original speech without answering the new point.","Stronger: “The proposition says a complete ban prevents distraction. However, a complete ban also removes teacher-directed uses such as supervised research. A controlled-use rule could address distraction without removing useful learning activities.”","Notice that the stronger response identifies the opponent's actual idea, exposes a limitation and offers reasoning."]],
["12. Gesture, posture, eye contact and voice",["NERDC explicitly includes gestures and posture. Stand in a balanced, confident way. Face the audience. Use natural eye contact across the room. Let hand gestures emphasise important ideas without becoming distracting or aggressive.","Voice matters too. Speak loudly enough to be heard, pronounce words carefully, vary emphasis naturally and pause at useful points. Speaking extremely fast may hide meaning; speaking in a flat monotone may weaken an otherwise strong argument.","Do not point threateningly at opponents, turn your back on listeners, laugh at another speaker or read every line without looking up. Non-verbal behaviour should support respect and clarity."]],
["13. Preparing a complete debate speech",["A useful speech has four parts. Opening: greet appropriately, state your side and clarify the motion if necessary. Argument section: present developed points in a logical order. Response: where appropriate, rebut important opposing claims. Conclusion: summarise why your reasons support your position.","Preparation should begin with brainstorming, not immediately writing a long speech. Generate possible points, remove weak or irrelevant ones, group similar ideas, find support, anticipate the opposition and assign arguments among team members.","Cue cards should contain key ideas rather than every word. This helps the speaker maintain eye contact and respond naturally."]],
["14. Full worked model — from weak point to developed point",["Motion: “Homework should be reduced for JSS students.” Weak point: “Homework is stressful.” This is not enough because the listener still needs to know how, when and why the stress matters.","Develop it: “Homework should be reduced when the amount is so large that learners lose necessary rest. A learner who spends several late-night hours completing tasks may arrive tired and struggle to concentrate the next morning. Reducing excessive homework—not removing useful practice—can therefore protect both practice time and readiness to learn.”","Notice the qualification. The argument does not pretend all homework is harmful. Precise claims are easier to defend than exaggerated ones."]],
["15. Full worked mini-debate",["Motion: “Students should be allowed to use phones during lessons for learning.” Proposition point: supervised phones can give quick access to dictionaries, calculators and research materials when a teacher deliberately includes them in a lesson.","Opposition rebuttal: access to useful tools does not prove unrestricted phone use is necessary; the same device also carries messages, games and social media, so the rule should address distraction. Proposition response: that criticism targets unrestricted use, while the motion can be defended through teacher-controlled educational use if the terms are clearly defined.","The lesson: strong debate often depends on precise wording. One side may expose an overstatement; the other may clarify the narrower claim it can actually defend."]],
["16. Common debate mistakes and how to repair them",["Mistake: repeating one point in different words. Repair: develop fewer points with explanation and support. Mistake: shouting instead of reasoning. Repair: strengthen the argument, not the volume. Mistake: attacking the speaker. Repair: quote or paraphrase the claim and answer it.","Mistake: inventing evidence. Repair: use information you can support. Mistake: ignoring the motion. Repair: end each major argument by linking it back. Mistake: reading without audience contact. Repair: practise from cue points.","Mistake: using a memorised rebuttal before hearing the opposition. Repair: prepare possible responses, but listen and adapt to what was actually said."]],
["17. Guided practice — you build the argument",["Motion: “Every school should have a weekly sports period.” Start with the point: regular physical activity supports learners' wellbeing. Now explain the connection, give a realistic example and link it to why a weekly school period matters.","Next prepare the opposition: a compulsory weekly period may reduce time available for other school priorities. Develop that point fairly. Then ask what the proposition could say in rebuttal.","AVORA should not train a learner to see only one side. Preparing both sides improves reasoning and makes rebuttal more intelligent."]],
["18. Performance task — conduct the debate",["Motion: “The use of Artificial Intelligence does more harm than good in our educational system.” This is the example motion supplied by the revised NERDC curriculum. Divide roles into chairperson, proposition, opposition and timekeeper.","Preparation: define the important terms; brainstorm both benefits and harms; select the strongest arguments; find credible support; predict counter-arguments; plan formal openings and conclusions; rehearse delivery.","During the debate, assess five things separately: relevance and strength of ideas; development/support; response to the other side; language/register and grammatical control; delivery through voice, gesture and posture. Respect is required throughout."]],
["19. Mastery check",["You have mastered this topic when you can explain what a debate is; identify the motion, proposition, opposition and chairperson; describe the procedure; choose an appropriate register; build a supported argument; listen and rebut respectfully; control sentences and tenses; use effective posture, gesture, eye contact and voice; and participate in a structured debate.","Knowing the definition alone is not mastery. NERDC's outcome is effective oral communication, so AVORA ends with performance: the learner must actually prepare and deliver part of a debate."]]
] as const;

export default function JSS2DebateLesson({onExercise}:{onExercise?:()=>void}){
 const [showPractice,setShowPractice]=useState(false);const [answers,setAnswers]=useState<Record<number,number>>({});
 return <section className="fractions-premium-lesson">
  <header className="premium-lesson-hero"><p className="lesson-kicker">JSS2 English Studies · Listening and Speaking</p><h1>Debate</h1><p>Learn how to understand a motion, build and support arguments, rebut ideas respectfully, use formal English and deliver a debate confidently.</p></header>
  <article className="premium-section"><h2>Learning objectives</h2><ul><li>Explain the meaning, purpose, procedure and essential elements of debate.</li><li>Identify the roles of the chairperson, proposition, opposition, supporting speakers, timekeeper and audience.</li><li>Analyse a motion and distinguish relevant from irrelevant arguments.</li><li>Use appropriate debate register, sentences and tenses.</li><li>Build clear arguments with explanation and support.</li><li>Listen actively and give respectful rebuttals.</li><li>Use suitable gesture, posture, eye contact, pronunciation, pace and emphasis.</li><li>Prepare and participate effectively in a structured class debate.</li></ul></article>
  {sections.map(([title,paras],i)=><article className="premium-section" key={i}><h2>{title}</h2>{paras.map((p,j)=><p key={j}>{p}</p>)}</article>)}
  <article className="premium-section"><h2>Independent practice · 24 questions</h2><p>These questions check meaning, procedure, register, grammar, argument construction, evidence, rebuttal, delivery and actual mastery—not recall alone.</p><button type="button" className="primary" onClick={()=>setShowPractice(v=>!v)}>{showPractice?'Hide practice':'Open practice'}</button>
  {showPractice&&<div>{questions.map((x,i)=><div className="premium-example" key={i}><h3>{i+1}. {x.q}</h3><p><b>Skill:</b> {x.skill}</p>{x.options.map((o,k)=><button type="button" key={k} onClick={()=>setAnswers(a=>({...a,[i]:k}))} style={{display:'block',margin:'8px 0'}}>{String.fromCharCode(65+k)}. {o}</button>)}{answers[i]!==undefined&&<p><b>{answers[i]===x.answer?'Correct.':'Not yet.'}</b> {x.why}</p>}</div>)}</div>}
  {onExercise&&<button type="button" className="primary" onClick={onExercise}>Continue to AVORA exercise mode →</button>}</article>
 </section>
}
