'use client';
import React,{useState} from 'react';
type Q={q:string;options:string[];answer:number;why:string;skill:string};
const qs:Q[]=[
{q:"What is the main purpose of an oral summary?",options:["Repeat every sentence exactly","Give the essential meaning of what was heard briefly and accurately","Add new opinions","List only unfamiliar words"],answer:1,why:"A summary preserves the central meaning and important supporting ideas while leaving out unnecessary detail.",skill:"Meaning of summary"},
{q:"What should you identify before writing or saying a summary?",options:["The main idea","Every adjective","The speaker's clothing","The number of letters"],answer:0,why:"The main idea provides the centre around which the essential supporting points are organised.",skill:"Main idea"},
{q:"Which detail is most likely removable?",options:["A key cause of the problem","The passage's central recommendation","A decorative example that repeats an already clear point","An essential result"],answer:2,why:"Repeated or illustrative detail can often be omitted when it adds no new essential meaning.",skill:"Selecting details"},
{q:"A good summary should normally be…",options:["longer than the original","brief but complete enough to preserve essential meaning","full of personal opinions","copied word for word"],answer:1,why:"Summarising compresses the source without destroying its core meaning.",skill:"Conciseness"},
{q:"Why should a listener avoid copying every sentence?",options:["Because a summary selects and compresses essential ideas","Because details are never important","Because listening is unnecessary","Because all passages have one sentence"],answer:0,why:"A transcript records wording; a summary represents essential meaning.",skill:"Summary vs transcript"},
{q:"Which opening best summarises a passage mainly about preventing lateness?",options:["The speaker explains practical ways students can reduce lateness.","Yesterday was Tuesday.","The speaker used many words.","I personally hate lateness."],answer:0,why:"It captures the passage's likely central idea without irrelevant information or personal opinion.",skill:"Topic sentence"},
{q:"If three examples all show the same idea, a summary should usually…",options:["repeat all three in full","combine them under the general idea","invent a fourth","omit the idea completely"],answer:1,why:"Grouping related examples under their shared idea is an important compression technique.",skill:"Generalisation"},
{q:"Which statement adds an inappropriate opinion?",options:["The passage explains that saving before spending can improve planning.","The speaker gives two reasons for keeping records.","I think the speaker is obviously brilliant.","The passage recommends setting priorities."],answer:2,why:"A faithful summary reports the source rather than inserting the summariser's personal judgement.",skill:"Objectivity"},
{q:"What does paraphrasing mean?",options:["Changing the source's meaning","Expressing the same idea accurately in your own words","Copying every word","Adding an example"],answer:1,why:"Paraphrasing changes wording while preserving meaning.",skill:"Paraphrase"},
{q:"Which note-taking style best supports oral summary?",options:["brief key ideas and relationships","a full transcript while the speaker continues","random words","personal reactions only"],answer:0,why:"Short notes preserve important ideas without making the learner miss the continuing audio.",skill:"Listening notes"},
{q:"A passage gives problem → causes → solutions. A good summary should…",options:["preserve that important relationship","mix the ideas randomly","mention only the title","add a different problem"],answer:0,why:"Important logical relationships are part of meaning and should survive compression.",skill:"Organisation"},
{q:"Which is safest when you cannot remember a minor number from the passage?",options:["Invent a likely number","Leave out the minor number unless essential","Double it","Change the whole message"],answer:1,why:"A summary must remain accurate. Never manufacture forgotten details.",skill:"Accuracy"},
{q:"After drafting a summary, what should you check first?",options:["Whether it preserves the source's main meaning accurately","Whether it contains the most difficult words","Whether it is as long as possible","Whether it includes your opinion"],answer:0,why:"Accuracy to the source is fundamental; brevity is useless if the meaning is distorted.",skill:"Checking"},
{q:"Which pair of ideas can often be combined?",options:["Two details that express the same broader point","Two unrelated passages","A fact and an invented claim","The title and your favourite hobby"],answer:0,why:"Combining related details into a broader accurate statement reduces repetition.",skill:"Combining"},
{q:"A speaker says: 'The school planted trees, installed bins and organised weekly clean-ups to improve its environment.' Best summary?",options:["The school used several practical measures to improve its environment.","The school planted a mango tree beside a blue bin every Tuesday.","Bins are my favourite school equipment.","The school did nothing."],answer:0,why:"It accurately compresses the three related actions into their shared purpose.",skill:"Compression"},
{q:"What is the difference between a main idea and a supporting detail?",options:["The main idea expresses the central message; a detail develops it.","There is no difference.","A detail is always longer.","The main idea is always the first sentence."],answer:0,why:"Position and length do not define importance; function does.",skill:"Idea hierarchy"},
{q:"Why listen to an oral passage a second time when permitted?",options:["To confirm essential points and correct misunderstandings","To replace the first passage","To add opinions","To memorise punctuation"],answer:0,why:"A second listening can verify the main idea, key support and relationships before summarising.",skill:"Listening strategy"},
{q:"Which summary is most objective?",options:["The speaker argues that regular exercise can support health and gives examples of simple daily activity.","The speaker is amazing and everyone must agree.","Exercise is boring, in my opinion.","I would have given a different speech."],answer:0,why:"It reports the speaker's message without evaluating the speaker or inserting personal preference.",skill:"Objectivity"},
{q:"When summarising in a group, what is most useful?",options:["Compare essential points and resolve differences by referring to what was heard","Let the loudest student invent the summary","Combine every sentence everyone remembers","Ignore disagreements"],answer:0,why:"Collaboration improves accuracy when learners justify selections from the source.",skill:"Collaboration"},
{q:"What shows mastery of oral summary?",options:["Defining summary only","Listening to a new passage and producing a concise, accurate account of its essential ideas","Copying a written paragraph","Memorising one model answer"],answer:1,why:"NERDC's skill is performance: listen and summarise an oral text.",skill:"Mastery"}
];
const sections=[
["1. What oral summary means",["An oral summary is a brief, accurate account of the essential meaning of something you have listened to. You may give the summary orally or write it after listening; the source itself is spoken.","A summary is not a transcript. A transcript tries to preserve nearly every spoken word. A summary selects the central idea and the supporting points necessary to understand it.","The challenge is therefore double: first understand what you hear, then compress it without changing its meaning."]],
["2. The three rules: accurate, essential, concise",["ACCURATE means your summary must not change what the speaker said. ESSENTIAL means you retain the ideas necessary for the message. CONCISE means you express those ideas without unnecessary repetition or examples.","A very short summary can still be poor if it leaves out the central message. A long summary can also be poor if it retells every example. Good summarising balances completeness of essential meaning with economy of words."]],
["3. Listen for the main idea first",["Before deciding what to remove, identify what the passage is mainly communicating. Ask: If I could tell someone only one thing about this passage, what would it be?","Do not assume the first sentence is always the main idea. Sometimes a speaker begins with an example or question and reveals the central message later.","Once you have the main idea, supporting points can be judged by whether they explain, cause, illustrate, contrast with or result from that idea."]],
["4. Main points versus examples",["Suppose a speaker explains that planning money helps learners avoid careless spending, then gives examples involving transport, lunch and airtime. The examples matter while teaching the idea, but a short summary may combine them as 'essential and optional expenses'.","Do not delete every detail automatically. If a detail introduces an essential cause, result, condition or recommendation, it may need to remain.","Ask: If I remove this information, will the reader or listener misunderstand the central message?"]],
["5. A practical listening method",["FIRST LISTENING — understand the topic and central message. SECOND LISTENING, if available — confirm the major supporting points and their relationships. AFTER LISTENING — organise the essential ideas before composing the summary.","If only one listening is available, keep the same priorities mentally: central message first, major support second, minor illustration last.","Do not allow one unfamiliar word to make you lose the rest of the passage. Keep following the overall meaning."]],
["6. Take notes without transcribing",["Use short notes such as 'problem: lateness', 'causes: late departure + gate congestion', 'actions: 2nd gate + earlier journeys', 'result: lateness ↓'.","These notes preserve the structure while allowing you to continue listening. Trying to write polished sentences while the speaker continues can make you miss later ideas.","After listening, expand the notes into connected language."]],
["7. Remove repetition",["Speakers naturally repeat ideas for emphasis. A summary usually states the idea once.","If a passage says, 'Planning helps us control spending. A plan prevents careless purchases. With a plan, we think before buying,' the shared idea can be compressed to: 'Planning helps people control careless spending.'","Compression is not deleting meaning; it is expressing repeated meaning efficiently."]],
["8. Generalise related examples",["If a passage lists rice, beans, vegetables and fruit as things a family budgets for, a summary may use the broader expression 'food expenses' when the individual items are not essential.","Generalisation must remain faithful. Do not turn 'rice and beans' into 'all household expenses' if the passage never discussed rent, transport or other costs.","The broader term must genuinely cover the details you combine."]],
["9. Paraphrase without changing meaning",["Paraphrasing means expressing an idea accurately in your own words. Original idea: 'The heavy rainfall prevented the match from continuing.' Possible paraphrase: 'The match could not continue because of the heavy rain.'","The wording changes, but the cause-and-effect relationship remains.","Do not replace words merely to sound sophisticated. Clear, accurate language is better than a difficult synonym that changes the meaning."]],
["10. Preserve important relationships",["A summary should retain relationships such as cause and effect, problem and solution, sequence, comparison and contrast when they are central.","If the source says flooding blocked the road, causing commuters to use another route, do not summarise it as 'Commuters used another route and flooding occurred.' That wording hides the causal relationship.","Useful connectors include because, therefore, as a result, however, while, first, later and finally—but use only those supported by the passage."]],
["11. Keep your opinion out",["A summary reports the source. It is not the place to decide whether the speaker is intelligent, foolish, exciting or boring unless the task specifically asks for evaluation.","Source: 'The speaker recommends saving part of one's income before spending on wants.' Summary: 'The speaker recommends prioritising savings before optional spending.'","Not summary: 'This is the best financial advice anyone has ever given.' That is your judgement, not the source's message."]],
["12. Worked Passage A — School discipline",["Listen mentally: 'For several weeks, lateness increased at Unity Junior School. The school investigated and discovered that some learners left home too late while congestion at the gate delayed others. It opened a second entrance, asked families to encourage earlier journeys and recognised classes that arrived punctually. By the end of the month, lateness had fallen considerably.'","Step 1 — main idea: the school reduced lateness through measures based on identified causes. Step 2 — essential support: causes were investigated; several corrective actions followed; lateness decreased. Step 3 — remove the school's name and minor wording if unnecessary.","MODEL SUMMARY: 'After investigating the causes of increasing lateness, the school introduced practical measures including easier entry and earlier travel, and lateness decreased considerably.'"]],
["13. Why that summary works",["It does not retell every sentence. It preserves the problem, the investigation, the response and the result.","It does not claim punishment solved the problem because the passage did not say that. It does not invent a percentage for the reduction. Accuracy is more important than sounding detailed.","It also preserves sequence: investigation came before the measures, and improvement followed them."]],
["14. Worked Passage B — Saving",["'Ada used to spend nearly all her weekly allowance on snacks and small purchases by Wednesday. She began writing down her essential expenses and setting aside a small amount before buying optional items. After several weeks, she had enough savings to replace a damaged school bag without borrowing.'","Key ideas: Ada spent too quickly; she began prioritising essentials and saving first; the new habit later helped her meet an unexpected need.","MODEL SUMMARY: 'After repeatedly spending her allowance too quickly, Ada began budgeting for essentials and saving before optional purchases, which later enabled her to replace a damaged school bag without borrowing.'"]],
["15. Weak versus strong summary",["WEAK: 'Ada had money. She bought snacks. Wednesday came. Her bag was damaged. She saved money.' The statements are disconnected and fail to show the important relationships.","TOO DETAILED: retelling every purchase and every time expression would defeat compression.","STRONG: identify the change in Ada's financial behaviour and the result. A summary should reconstruct the meaning, not produce a pile of remembered facts."]],
["16. Worked Passage C — Peaceful coexistence",["'Residents who shared a community field often argued over its use. Representatives met, listened to each group's needs and discovered that most clashes involved only two evenings. They created a timetable and a procedure for requesting changes. Disagreements continued occasionally, but they were handled without threats or insults.'","MODEL SUMMARY: 'Residents reduced conflict over a shared field by discussing their needs and agreeing on a timetable and procedure, allowing later disagreements to be handled peacefully.'","Notice how several actions are compressed while the central problem → solution → result structure remains."]],
["17. Summary length",["There is no single magical number of sentences for every oral summary unless the question specifies a length. The summary should be proportionate to the source and task.","If the instruction says 'in two sentences', obey it. If no length is given, aim to include all essential ideas with no unnecessary material.","Never remove a crucial idea simply to make the answer impressively short."]],
["18. Accuracy when memory is uncertain",["If you remember that the speaker said 'many learners' but cannot remember an exact number, do not invent one. If the number is not essential, omit it; if it is essential and another listening is allowed, verify it.","Summarising tests understanding, not creative reconstruction. Everything presented as source information should be defensible from what was heard."]],
["19. Collaborative oral summary",["NERDC specifically includes group listening and summarising. After a passage, each learner can state what they believe the main idea and essential points were. The group then compares selections.","Disagreement can be useful: ask, 'What did we hear that supports this?' The group should resolve differences by returning to the oral text when possible, not by following the loudest person.","Finally, combine agreed essential points into one concise summary in clear language."]],
["20. Guided Practice A",["Passage: 'A neighbourhood experienced repeated flooding because rubbish blocked several drains. Residents first blamed the heavy rain alone, but an inspection showed that waste had prevented water from flowing freely. Community volunteers cleared the drains and local leaders placed bins at busy points. During the next heavy rain, water drained more quickly.'","Before reading the model, identify: problem; discovered cause; actions; result.","MODEL: 'After discovering that rubbish-blocked drains contributed to repeated flooding, residents cleared the drains and improved waste disposal, allowing water to flow more quickly during later heavy rain.'"]],
["21. Guided Practice B",["Passage: 'A school library noticed that many books were returned late. Rather than immediately increasing penalties, the librarian asked students why. Some forgot due dates, while others could not visit during the short break period. The library began sending reminders and extended its return desk hours. Late returns fell.'","Your summary needs the problem, investigation, solution and result. Minor details may be compressed.","MODEL: 'After investigating frequent late book returns, the library introduced reminders and longer return hours to address the identified causes, and late returns decreased.'"]],
["22. Error clinic",["ERROR: adding a moral the speaker never gave. FIX: report only supported meaning. ERROR: listing examples instead of their general idea. FIX: combine related examples. ERROR: copying whole phrases unnecessarily. FIX: paraphrase clearly.","ERROR: losing cause and effect. FIX: preserve important relationships. ERROR: removing so much that the message becomes vague. FIX: retain essential support. ERROR: inventing forgotten details. FIX: omit non-essential uncertainty or verify when another listening is allowed."]],
["23. A five-question self-check",["After producing a summary ask: (1) Did I state the central idea? (2) Did I include the essential supporting points? (3) Did I remove repetition and minor examples? (4) Did I preserve the speaker's meaning and important relationships? (5) Did I avoid adding my own opinion or invented information?","If any answer is no, revise before submitting."]],
["24. NERDC mastery task",["Listen to a fresh short oral passage read by a teacher, classmate or audio recording. Do not read a transcript first. Take brief notes, identify the central message and essential supporting ideas, then give a concise oral or written summary in your own words.","In a group version, compare summaries respectfully and justify which ideas are essential from evidence in the passage.","Mastery means you can summarise a NEW oral passage accurately. Memorising one model summary is not mastery."]]
] as const;
export default function JSS2OralSummaryLesson({onExercise}:{onExercise?:()=>void}){const [show,setShow]=useState(false),[a,setA]=useState<Record<number,number>>({});return <section className="fractions-premium-lesson"><header className="premium-lesson-hero"><p className="lesson-kicker">JSS2 English Studies · Listening and Speaking</p><h1>Oral Summary</h1><p>Listen, identify what matters, compress it accurately, and retell the essential meaning without distortion or unnecessary detail.</p></header><article className="premium-section"><h2>Learning objectives</h2><ul><li>Listen attentively to a short oral passage.</li><li>Identify its main idea and essential supporting points.</li><li>Distinguish essential information from repetition and minor examples.</li><li>Take brief useful notes while listening.</li><li>Paraphrase and combine related ideas without changing meaning.</li><li>Preserve important relationships such as cause and effect.</li><li>Produce concise, accurate oral summaries individually and collaboratively.</li></ul></article>{sections.map(([t,ps],i)=><article className="premium-section" key={i}><h2>{t}</h2>{ps.map((p,j)=><p key={j}>{p}</p>)}</article>)}<article className="premium-section"><h2>Independent practice · 20 questions</h2><button type="button" className="primary" onClick={()=>setShow(v=>!v)}>{show?'Hide practice':'Open practice'}</button>{show&&<div>{qs.map((x,i)=><div className="premium-example" key={i}><h3>{i+1}. {x.q}</h3><p><b>Skill:</b> {x.skill}</p>{x.options.map((o,k)=><button type="button" key={k} onClick={()=>setA(v=>({...v,[i]:k}))} style={{display:'block',margin:'8px 0'}}>{String.fromCharCode(65+k)}. {o}</button>)}{a[i]!==undefined&&<p><b>{a[i]===x.answer?'Correct.':'Not yet.'}</b> {x.why}</p>}</div>)}</div>}{onExercise&&<button type="button" className="primary" onClick={onExercise}>Continue to AVORA exercise mode →</button>}</article></section>}
