'use client'; import React from 'react';
const W=({q,children}:{q:string;children:React.ReactNode})=><div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>;
const L=({children,strong=false}:{children:React.ReactNode;strong?:boolean})=><div className={strong?'math-line math-result':'math-line'}>{children}</div>;
const Rule=({children}:{children:React.ReactNode})=><div className="lesson-rule">{children}</div>;
export default function LCMLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson"><header className="wn-hero"><span>JSS1 MATHEMATICS · WHOLE NUMBERS</span><h1>Lowest Common Multiple (LCM)</h1><p>Build the idea from factors and multiples, then find the first multiple shared by two or more whole numbers.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul><li>Explain factor, multiple and common multiple.</li><li>List multiples systematically.</li><li>Find LCM by listing multiples and by prime factorisation.</li><li>Find LCM of two or three whole numbers.</li><li>Distinguish LCM from HCF and solve simple quantitative problems.</li></ul></section>
<section className="wn-section"><h3>1. Foundation: Factors</h3><p>A <b>factor</b> divides a number exactly, leaving no remainder. Factors are the numbers that can make a number by multiplication.</p><W q="Find the factors of 12."><L>1 × 12 = 12</L><L>2 × 6 = 12</L><L>3 × 4 = 12</L><L strong>Factors of 12: 1, 2, 3, 4, 6, 12.</L></W><Rule><span>A factor of a positive whole number cannot be greater than the number.</span><span>Every positive whole number has 1 and itself as factors.</span></Rule></section>
<section className="wn-section"><h3>2. Foundation: Multiples</h3><p>A <b>multiple</b> is obtained by multiplying a number by 1, 2, 3, 4, ... . Unlike factors, the list of multiples continues without end.</p><W q="Write the first six positive multiples of 4."><L>4 × 1 = 4</L><L>4 × 2 = 8</L><L>4 × 3 = 12</L><L>4 × 4 = 16</L><L>4 × 5 = 20</L><L>4 × 6 = 24</L><L strong>4, 8, 12, 16, 20, 24</L></W><Rule><span>Factors divide a number.</span><span>Multiples come from multiplying a number.</span><span>A number is both a factor and a multiple of itself.</span></Rule></section>
<section className="wn-section"><h3>3. Common Multiples and LCM</h3><p>A <b>common multiple</b> belongs to the multiple lists of all the numbers being compared. The <b>Lowest Common Multiple</b> is the smallest positive common multiple.</p><W q="Find the LCM of 4 and 6 by listing multiples."><L>Multiples of 4: 4, 8, 12, 16, 20, 24, ...</L><L>Multiples of 6: 6, 12, 18, 24, ...</L><L>Common multiples include 12 and 24.</L><L>12 is the first positive common multiple.</L><L strong>LCM(4, 6) = 12.</L></W></section>
<section className="wn-section"><h3>4. Listing Method</h3><W q="Find the LCM of 8 and 12."><L>Multiples of 8: 8, 16, 24, 32, 40, 48, ...</L><L>Multiples of 12: 12, 24, 36, 48, ...</L><L>The first common multiple is 24.</L><L strong>LCM(8, 12) = 24.</L><L>Check: 24 ÷ 8 = 3 and 24 ÷ 12 = 2.</L></W></section>
<section className="wn-section"><h3>5. Prime Numbers and Prime Factors — Build This First</h3><p>A <b>prime number</b> is a whole number greater than 1 with exactly two positive factors: 1 and itself. Examples are 2, 3, 5, 7, 11, 13, 17 and 19. The number 1 is not prime. Numbers such as 4, 6, 8, 9 and 12 are composite because they have more than two factors.</p><W q="Decide whether 7 and 9 are prime."><L>Factors of 7 are 1 and 7 only, so 7 is prime.</L><L>Factors of 9 are 1, 3 and 9, so 9 is composite.</L></W><p>A <b>prime factor</b> is a factor that is itself prime. The factors of 12 are 1, 2, 3, 4, 6 and 12; among them, 2 and 3 are prime. Therefore 2 and 3 are the prime factors of 12.</p><p><b>Prime factorisation</b> means breaking a whole number completely into prime factors. Divide by the smallest prime that goes in exactly, record it, and continue with the quotient until the quotient is 1.</p><W q="Express 60 as a product of prime factors."><L>60 ÷ 2 = 30.</L><L>30 ÷ 2 = 15.</L><L>15 ÷ 3 = 5.</L><L>5 ÷ 5 = 1.</L><L>60 = 2 × 2 × 3 × 5.</L><L strong>60 = 2² × 3 × 5.</L><L>Check: 4 × 3 × 5 = 60.</L></W><W q="Express 84 as a product of prime factors."><L>84 ÷ 2 = 42.</L><L>42 ÷ 2 = 21.</L><L>21 ÷ 3 = 7.</L><L>7 ÷ 7 = 1.</L><L strong>84 = 2² × 3 × 7.</L></W><h4>Why use prime factors for LCM?</h4><p>Prime factors are the basic multiplicative building blocks of whole numbers. Once each number is written with those building blocks, we can see exactly what is required to build every number. For LCM we take every prime needed, with the greatest number of copies required by any original number. This makes prime factorisation especially useful when listing multiples would become long.</p><Rule><span>Prime number: exactly two positive factors.</span><span>Prime factor: a factor that is prime.</span><span>Prime factorisation: write a number completely as a product of primes.</span><span>LCM: use all required prime building blocks at their greatest required powers.</span></Rule></section>
<section className="wn-section"><h3>6. LCM by Prime Factors</h3><p>For LCM, keep enough copies of every prime factor to build each original number. In index form, this means using the greatest power of each prime that appears.</p><W q="Find the LCM of 12 and 18."><L>12 = 2² × 3</L><L>18 = 2 × 3²</L><L>Highest power of 2 needed: 2².</L><L>Highest power of 3 needed: 3².</L><L>LCM = 2² × 3²</L><L>= 4 × 9</L><L strong>LCM = 36.</L><L>Check: 36 ÷ 12 = 3; 36 ÷ 18 = 2.</L></W></section>
<section className="wn-section"><h3>7. LCM of Three Numbers</h3><W q="Find the LCM of 6, 8 and 12."><L>6 = 2 × 3</L><L>8 = 2³</L><L>12 = 2² × 3</L><L>Highest power of 2 is 2³; highest power of 3 is 3.</L><L>LCM = 2³ × 3 = 8 × 3.</L><L strong>LCM = 24.</L><L>24 is divisible by 6, 8 and 12.</L></W></section>
<section className="wn-section"><h3>8. LCM in a Real Situation</h3><W q="A bell rings every 6 minutes and another every 8 minutes. They ring together now. After how many minutes will they next ring together?"><L>We need the first time that is a multiple of both 6 and 8.</L><L>6: 6, 12, 18, 24, ...</L><L>8: 8, 16, 24, ...</L><L strong>LCM(6,8) = 24, so they ring together again after 24 minutes.</L></W></section>
<section className="wn-section"><h3>9. LCM or HCF?</h3><Rule><span><b>LCM:</b> asks when repeating groups/events first meet, or for the smallest quantity divisible by all given numbers.</span><span><b>HCF:</b> asks for the greatest factor or largest equal grouping that divides fixed quantities exactly.</span></Rule></section>
<section className="wn-section"><h3>10. Common Mistakes</h3><Rule><span>Do not choose just any common multiple; choose the lowest positive one.</span><span>Do not confuse factors with multiples.</span><span>For prime-factor LCM, do not keep only shared primes; include every prime needed to contain all the original numbers.</span><span>Always check that every original number divides the proposed LCM exactly.</span></Rule></section>
<section className="wn-section"><h3>11. Mastery Check</h3><p>You should now be able to explain factors and multiples, identify common multiples, find LCM by listing and prime factors, work with two or three numbers, distinguish LCM from HCF and explain why your answer is correct.</p></section><div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}