'use client';import {useState} from 'react';import Link from 'next/link';
type Q={number:number;id:string;paper:string;domain:string;topic:string;prompt:string;options:string[]};
export default function NceeMockClient(){const [mock,setMock]=useState(1),[sid,setSid]=useState(''),[qs,setQs]=useState<Q[]>([]),[answers,setAnswers]=useState<Record<string,string>>({}),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[paper,setPaper]=useState<'Paper I'|'BREAK'|'Paper II'>('Paper I');
async function start(){setBusy(true);const r=await fetch('/api/common-entrance/mock/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mockNumber:mock})});const d=await r.json();setBusy(false);if(!r.ok)return alert(d.error);setSid(d.sessionId);setQs(d.questions);setResult(null);setPaper('Paper I');scrollTo(0,0)}
async function choose(id:string,a:string){setAnswers(x=>({...x,[id]:a}));await fetch('/api/common-entrance/mock/answer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:sid,questionId:id,answer:a})})}
async function submit(){if(!confirm('Submit your complete AVORA NCEE mock?'))return;setBusy(true);const r=await fetch('/api/common-entrance/mock/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:sid})});const d=await r.json();setBusy(false);if(!r.ok)return alert(d.error);setResult(d);scrollTo(0,0)}
if(result)return <section className="ncee-result"><span>MOCK {mock} COMPLETE</span><h2>{result.score}% · {result.readiness}</h2><p>{result.correct} of {result.total} questions correct.</p><div className="ncee-domain-results">{Object.entries(result.domains).map(([name,d]:any)=><article key={name}><b>{name}</b><strong>{d.percent}%</strong><p>{d.correct}/{d.total} correct</p>{Object.keys(d.weakTopics||{}).slice(0,2).map(t=><Link key={t} href={'/common-entrance/learn?domain='+encodeURIComponent(name)}>Reteach: {t} →</Link>)}</article>)}</div><button onClick={()=>{setSid('');setQs([]);setAnswers({});setResult(null)}}>Choose another mock</button></section>;
if(!sid)return <section className="ncee-mock-launch"><h2>Eight full AVORA Common Entrance mocks</h2><p>Each form covers all six tested areas. Questions are AVORA-original; historical papers remain reference-only unless reproduction rights are verified.</p><div className="ncee-mock-picker">{Array.from({length:8},(_,i)=><button className={mock===i+1?'active':''} key={i} onClick={()=>setMock(i+1)}>Mock {i+1}</button>)}</div><button disabled={busy} onClick={start}>{busy?'Preparing…':`Start Mock ${mock}`}</button></section>;
const shown=qs.filter(q=>q.paper===paper);return <section className="ncee-running"><div className="ncee-paper-switch"><button className={paper==='Paper I'?'active':''} onClick={()=>setPaper('Paper I')}>Paper I · 130 min</button><button onClick={()=>setPaper('BREAK')}>Break</button><button className={paper==='Paper II'?'active':''} onClick={()=>setPaper('Paper II')}>Paper II · 80 min</button></div>{paper==='BREAK'?<div className="ncee-break"><h2>Paper I complete?</h2><p>Take a short supervised break. When ready, continue to Paper II. Your answers are already saved.</p><button onClick={()=>setPaper('Paper II')}>Continue to Paper II</button></div>:shown.map(q=><article className="ncee-question" key={q.id}><small>{q.domain} · {q.topic}</small><h3>{q.number}. {q.prompt}</h3>{q.options.map(o=><button className={answers[q.id]===o?'selected':''} key={o} onClick={()=>choose(q.id,o)}>{o}</button>)}</article>)}{paper==='Paper II'&&<button className="ncee-submit" disabled={busy} onClick={submit}>{busy?'Marking…':'Submit complete mock'}</button>}</section>}
