'use client';
import React from 'react';

const objectives=[
'state the purposes of statistics',
'explain why reliable data is needed before planning',
'use simple collected information to make a sensible planning decision',
'explain chance events in everyday life',
'describe probability informally using impossible, unlikely, equally likely, likely and certain',
'give everyday examples where chance and probability are useful',
'explain how past and present data can support prediction',
'distinguish a data-based prediction from a guarantee'
];

function DataBars(){const rows=[['JSS1A',42,84],['JSS1B',38,76],['JSS1C',45,90]];return <div className="stats-card"><h4>Planning example: Mathematics workbooks</h4><div className="stats-bars">{rows.map(([n,v,p])=><div className="stats-bar-row" key={String(n)}><span>{n}</span><div><i style={{width:p+'%'}}/></div><b>{v}</b></div>)}</div><p className="stats-caption">Total learners = 42 + 38 + 45 = <b>125</b>. The school needs at least 125 workbooks if every learner is to receive one.</p></div>}
function ChanceScale(){return <div className="chance-scale" aria-label="Chance scale from impossible to certain"><div><b>Impossible</b><span>0</span><small>Sun rises in the west tomorrow</small></div><div><b>Unlikely</b><span>low chance</span><small>Rolling a 6 twice in a row</small></div><div><b>Equally likely</b><span>½</span><small>Head on a fair coin</small></div><div><b>Likely</b><span>high chance</span><small>Rain during a very wet period</small></div><div><b>Certain</b><span>1</span><small>A week has 7 days</small></div></div>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}

export default function NeedForStatisticsLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson statistics-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS · EVERYDAY STATISTICS</span><h1>Need for Statistics</h1><p>Statistics becomes useful when information helps us understand a situation, plan wisely, think about chance, or make a reasonable prediction.</p></header>
<section className="wn-objectives"><h2>NERDC-Aligned Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>

<section className="wn-section"><h3>1. Start With a Real Decision</h3><p>Imagine your school wants to buy Mathematics workbooks. Should the principal simply guess how many to buy? No. The school first needs information such as the number of learners in each class.</p><DataBars/><p>The class numbers are <b>data</b>. Once the data are collected, organised and interpreted for a purpose, they help people make better decisions. This is one major reason we need statistics.</p></section>

<section className="wn-section"><h3>2. What Do We Mean by Statistics?</h3><p>At this level, think of <b>statistics</b> as working with data so that the information can help us understand situations and make decisions. The work may involve collecting, organising, presenting, interpreting and using data.</p><div className="lesson-rule"><span><b>Data:</b> facts or information collected about people, objects or events.</span><span><b>Statistics:</b> methods used to turn data into useful information.</span><span><b>Important:</b> numbers without a purpose are not enough; we must know what question the data are helping us answer.</span></div></section>

<section className="wn-section"><h3>3. Purposes of Statistics</h3><div className="stats-purpose-grid"><div><b>Describe</b><p>Show what is happening now—for example, class attendance.</p></div><div><b>Compare</b><p>Compare groups or periods—for example, attendance this term and last term.</p></div><div><b>Plan</b><p>Estimate resources needed—for example, books, classrooms or buses.</p></div><div><b>Predict</b><p>Use patterns in available data to make a reasonable expectation about what may happen.</p></div></div><p>Statistics can also help governments, schools, hospitals, businesses and communities monitor problems and evaluate whether actions are working.</p></section>

<section className="wn-section"><h3>4. Why Planning Needs Data</h3><p>Planning without data can lead to too little, too much or the wrong kind of resource. Good planning begins by asking a clear question and collecting information relevant to that question.</p><Work q="A school has 42 learners in JSS1A, 38 in JSS1B and 45 in JSS1C. How many JSS1 Mathematics workbooks should it plan for if each learner needs one?"><Line>Required data: number of learners in each JSS1 class.</Line><Line>Total = 42 + 38 + 45</Line><Line>Total = 125 learners</Line><Line>Each learner needs 1 workbook.</Line><Line strong>Minimum workbooks required = 125</Line><Line>Decision: ordering fewer than 125 would leave at least one learner without a workbook. ✓</Line></Work></section>

<section className="wn-section"><h3>5. Planning Situations Around You</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>Planner</th><th>Data needed</th><th>Decision supported</th></tr></thead><tbody><tr><td>School</td><td>Number of learners</td><td>Books, desks and classrooms needed</td></tr><tr><td>Hospital/clinic</td><td>Number and types of cases seen</td><td>Staff and supplies to prepare</td></tr><tr><td>Transport operator</td><td>Passenger numbers by time</td><td>When more vehicles may be needed</td></tr><tr><td>Community</td><td>Population and water use</td><td>Water facilities required</td></tr><tr><td>Shop</td><td>Past demand for products</td><td>How much stock to order</td></tr></tbody></table></div><p>Notice the pattern: <b>question → relevant data → interpretation → decision</b>.</p></section>

<section className="wn-section"><h3>6. Statistics and Public Information</h3><p>NERDC also uses examples such as voter education, consumer education, environmental education and information about social or health problems to show that statistics is useful beyond the classroom. In each case, data can show the size or pattern of an issue and help organisations decide where attention or resources are needed.</p><div className="lesson-rule"><span><b>Example:</b> environmental data can show which areas produce more waste and therefore where more collection resources may be needed.</span><span><b>Example:</b> survey data can show how many people have received a public-information message and where further education may be required.</span></div></section>

<section className="wn-section"><h3>7. Chance Events in Everyday Life</h3><p>Some events are certain; some are impossible; many have uncertain outcomes. A <b>chance event</b> is an event whose outcome is not known with certainty beforehand. Probability gives us a way to describe how likely an event is.</p><ChanceScale/><p>For a probability written as a number, <b>0 means impossible</b> and <b>1 means certain</b>. Values between 0 and 1 represent different degrees of chance.</p></section>

<section className="wn-section"><h3>8. Four Everyday Applications of Probability</h3><div className="stats-purpose-grid"><div><b>Weather</b><p>A probability of rain helps people decide whether to prepare for wet weather.</p></div><div><b>Games</b><p>Coin, card and dice outcomes help us reason about fair and unfair games.</p></div><div><b>Insurance and risk</b><p>Past frequencies help organisations estimate the chance of certain losses or events.</p></div><div><b>Planning under uncertainty</b><p>Businesses and organisations consider possible demand or outcomes before committing resources.</p></div></div></section>

<section className="wn-section"><h3>9. Worked Chance Example</h3><Work q="A fair coin is tossed once. Is getting a head impossible, unlikely, equally likely, likely or certain?"><Line>A fair coin has two possible outcomes: Head and Tail.</Line><Line>Neither outcome is favoured.</Line><Line>Probability of Head = 1 out of 2 = ½.</Line><Line strong>Getting a head is equally likely to getting a tail.</Line><Line>It is not certain because Tail can occur, and it is not impossible because Head can occur. ✓</Line></Work></section>

<section className="wn-section"><h3>10. Statistics for Prediction</h3><p>A prediction is a statement about what may happen in the future. Statistics can support prediction when past or present data reveal a useful pattern. A prediction based on data is more informed than a random guess—but it is still not automatically certain.</p><div className="stats-card"><h4>School canteen demand</h4><div className="mini-data"><span>Mon <b>76</b></span><span>Tue <b>81</b></span><span>Wed <b>79</b></span><span>Thu <b>84</b></span><span>Fri <b>80</b></span></div><p>Recent daily demand stays roughly around 80 meals. Planning approximately 80 meals for a similar school day is supported by the data, although actual demand can still change.</p></div></section>

<section className="wn-section"><h3>11. Worked Prediction Example</h3><Work q="A canteen served 76, 81, 79, 84 and 80 meals on five comparable school days. Is planning around 80 meals for another comparable day a data-based prediction or a guarantee?"><Line>The five observations are all close to 80.</Line><Line>The data therefore provide evidence for planning around that level.</Line><Line>But tomorrow's demand has not happened yet and may differ.</Line><Line strong>It is a data-based prediction, not a guarantee.</Line><Line>Good statistical language avoids claiming certainty where the data only support an expectation. ✓</Line></Work></section>

<section className="wn-section"><h3>12. Bad Data Can Produce Bad Decisions</h3><p>Statistics is useful only when the data are relevant and reasonably reliable. If a school counts only one class but pretends the result represents the whole school, its plan may be wrong. If old information is used for a rapidly changing situation, the prediction may also be poor.</p><div className="lesson-rule"><span>Ask: <b>What question are we answering?</b></span><span>Ask: <b>What data do we actually need?</b></span><span>Ask: <b>Are the data relevant and current enough?</b></span><span>Ask: <b>Does the conclusion go beyond what the data can support?</b></span></div></section>

<section className="wn-section"><h3>13. AVORA Statistics Thinking Routine</h3><div className="lesson-rule"><span><b>QUESTION:</b> What do we need to know?</span><span><b>DATA:</b> What information will answer it?</span><span><b>ORGANISE:</b> Make the information understandable.</span><span><b>INTERPRET:</b> What pattern or fact does it show?</span><span><b>USE:</b> Is the purpose description, comparison, planning or prediction?</span><span><b>CHECK:</b> Is our conclusion actually supported by the data?</span></div></section>

<section className="wn-section"><h3>14. NERDC Mastery Check</h3><p>You have mastered this lesson when you can list at least three purposes of statistics; give situations where data collection is needed for planning; give at least four everyday applications of probability/chance; identify situations where statistics is used for prediction; and explain why a statistical prediction should not automatically be treated as a certainty.</p></section>
<div className="lesson-action"><button type="button" className="primary-btn" onClick={onExercise}>Go to Exercise →</button></div>
</article>}
