'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
export default function NotesClient({classLevel}:{classLevel:string}){
 const [notes,setNotes]=useState<any[]>([]),[title,setTitle]=useState(''),[body,setBody]=useState(''),[subject,setSubject]=useState('Mathematics'),[topic,setTopic]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){const r=await fetch('/api/notes',{cache:'no-store'});const d=await r.json();if(r.ok)setNotes(d.notes||[])}
 useEffect(()=>{load()},[]);
 async function create(){setBusy(true);setError('');try{const r=await fetch('/api/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,body,classLevel,subject,topicId:topic||null,sourceKind:'CLASS_NOTE'})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTitle('');setBody('');setTopic('');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="notes-workspace"><header><span className="section-kicker">MY NOTES</span><h2>Keep what your teacher taught you — permanently.</h2><p>Type with your phone keyboard or save a classroom-note image. Your original note remains yours; when AVORA later creates practice from it, verified curriculum remains the academic authority.</p></header><div className="notes-compose"><div className="notes-fields"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Note title — e.g. Factors and Multiples"/><select value={subject} onChange={e=>setSubject(e.target.value)}><option>Mathematics</option><option>English Language</option></select><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Topic (optional)"/></div><textarea inputMode="text" autoCapitalize="sentences" autoCorrect="on" spellCheck value={body} onChange={e=>setBody(e.target.value)} rows={12} placeholder="Type your class note here exactly as you wrote or understood it…"/><button className="premium-primary" disabled={busy||!title.trim()} onClick={create}>{busy?'Saving…':'Save note permanently →'}</button>{error&&<p className="form-error">{error}</p>}</div><div className="notes-library"><header><strong>{notes.length} saved notes</strong><span>Available whenever you return to your account.</span></header>{notes.length?notes.map(n=><Link key={n.id} href={'/school-work/notes/'+n.id}><div><small>{n.subject_name} · {n.class_level}</small><strong>{n.title}</strong><p>{n.body||'Image/class note'}</p></div><span>{n.image_count?n.image_count+' image'+(n.image_count===1?'':'s'):'Typed note'} →</span></Link>):<div className="school-work-empty"><h3>Your notebook is empty.</h3><p>Save a typed class note first, then open it to add permanent note images.</p></div>}</div></section>
}
