'use client';
import {useState} from 'react'; import {useRouter} from 'next/navigation'; import {readJson} from '@/lib/clientFetch';
export default function OnboardingClient({firstName}:{firstName:string}){
 const router=useRouter(); const [step,setStep]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const [data,setData]=useState({classLevel:'JSS3',targetExam:'BECE',preferredSubject:'Mathematics',learningGoal:'Understand difficult topics and prepare confidently for my exam',dailyGoalMinutes:20,confidenceLevel:3});
 const screens=[
  <div key="a"><span className="flow-label">FIRST, YOUR DIRECTION</span><h1>What are you learning for?</h1><p className="flow-copy">AVORA uses this to choose the right level, examples and practice — not to put you in a box.</p><div className="choice-line">{['Primary 5','Primary 6','JSS1','JSS2','JSS3'].map(x=><button key={x} className={data.classLevel===x?'choice active':'choice'} onClick={()=>setData({...data,classLevel:x,targetExam:x.startsWith('Primary')?'NCEE':'BECE'})}>{x}</button>)}</div><label className="flow-field">Target <select value={data.targetExam} disabled aria-label="Target exam"><option value="NCEE">National Common Entrance (NCEE)</option><option value="BECE">BECE</option></select><small>{data.classLevel.startsWith('Primary')?'Primary 5 and Primary 6 use AVORA Common Entrance Prep across every tested NCEE domain.':'JSS1–JSS3 follow the secondary learning path toward BECE.'}</small></label></div>,
  <div key="b"><span className="flow-label">MAKE IT YOURS</span><h1>What should AVORA help you change?</h1><p className="flow-copy">There is no wrong answer. This becomes part of your learning direction.</p><label className="flow-field">My main goal<textarea value={data.learningGoal} onChange={e=>setData({...data,learningGoal:e.target.value})}/></label><div className="choice-line">{(data.classLevel.startsWith('Primary')?['Mathematics','English']:['Mathematics','English']).map(x=><button key={x} className={data.preferredSubject===x?'choice active':'choice'} onClick={()=>setData({...data,preferredSubject:x})}>{x}</button>)}</div></div>,
  <div key="c"><span className="flow-label">YOUR PACE</span><h1>How should learning fit your day?</h1><p className="flow-copy">Small, consistent sessions beat long sessions you cannot maintain.</p><div className="choice-line">{[10,20,30,45].map(x=><button key={x} className={data.dailyGoalMinutes===x?'choice active':'choice'} onClick={()=>setData({...data,dailyGoalMinutes:x})}>{x} min</button>)}</div><p className="flow-question">How confident do you feel in {data.preferredSubject} right now?</p><div className="confidence">{[1,2,3,4,5].map(x=><button key={x} className={data.confidenceLevel===x?'confidence-dot active':'confidence-dot'} onClick={()=>setData({...data,confidenceLevel:x})} aria-label={`Confidence ${x}`}>{x}</button>)}</div><div className="confidence-ends"><span>Need help</span><span>Very confident</span></div></div>
 ];
 async function next(){if(step<2){setStep(step+1);return} setBusy(true);setError(''); try{const r=await fetch('/api/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); const d=await readJson<any>(r); if(!r.ok)throw new Error(d.error||'Could not save'); router.replace('/home');router.refresh()}catch(e:any){setError(e.message||'Could not save');setBusy(false)}}
 return <main className="learning-flow"><div className="flow-progress"><span style={{width:`${((step+1)/3)*100}%`}}/></div><section className="flow-shell"><div className="flow-greeting">{step===0?`Hi ${firstName}. Before we teach, we listen.`:'AVORA is learning how to teach you.'}</div>{screens[step]}{error&&<p className="flow-error">{error}</p>}<div className="flow-actions">{step>0&&<button className="quiet-action" onClick={()=>setStep(step-1)}>Back</button>}<button className="primary-action" onClick={next} disabled={busy}>{busy?'Saving…':step===2?'Enter my learning home →':'Continue →'}</button></div><small className="flow-count">{step+1} of 3</small></section></main>
}
