'use client';
import React from 'react';

const objectives=[
'identify and describe square, rectangle, triangle, trapezium, parallelogram and circle',
'compare the similarities and differences among common plane shapes',
'use side, vertex, angle, parallel-side, perpendicular-side and curved-boundary information correctly',
'explain perimeter as the total distance around a plane shape',
'calculate the perimeter of square, rectangle, triangle, trapezium and parallelogram',
'calculate the circumference of a circle using its radius or diameter',
'explain area as the amount of flat surface covered by a shape',
'calculate areas of squares, rectangles, triangles, parallelograms and trapezia',
'estimate or determine area using square-grid reasoning',
'find areas of simple irregular or composite plane figures',
'apply perimeter and area to real-life objects and state correct units'
];

function Svg({children,label}:{children:React.ReactNode;label:string}){return <figure className="geometry-figure"><svg viewBox="0 0 360 230" role="img" aria-label={label}>{children}</svg><figcaption>{label}</figcaption></figure>}
function Square({side='5 cm'}:{side?:string}){return <Svg label="Square — four equal sides and four right angles"><rect x="95" y="35" width="150" height="150" rx="2" className="geo-shape"/><path d="M95 35h18v18H95 M227 35v18h18 M95 167h18v18 M227 185v-18h18" className="geo-mark"/><path d="M160 30l5 10 5-10 M160 180l5 10 5-10 M90 105l10 5-10 5 M240 105l10 5-10 5" className="geo-mark"/><text x="170" y="212" textAnchor="middle">{side}</text><text x="84" y="30">A</text><text x="250" y="30">B</text><text x="250" y="202">C</text><text x="84" y="202">D</text></Svg>}
function Rectangle(){return <Svg label="Rectangle — opposite sides equal and parallel; four right angles"><rect x="55" y="60" width="250" height="115" rx="2" className="geo-shape"/><path d="M55 60h18v18H55 M287 60v18h18 M55 157h18v18 M287 175v-18h18" className="geo-mark"/><text x="180" y="205" textAnchor="middle">8 cm</text><text x="38" y="122" textAnchor="middle" transform="rotate(-90 38 122)">4 cm</text><text x="45" y="53">A</text><text x="309" y="53">B</text><text x="309" y="191">C</text><text x="45" y="191">D</text></Svg>}
function Triangle(){return <Svg label="Triangle — three straight sides and three vertices"><path d="M180 35 L55 185 L305 185 Z" className="geo-shape"/><text x="180" y="24" textAnchor="middle">A</text><text x="42" y="202">B</text><text x="310" y="202">C</text><text x="110" y="105">5 cm</text><text x="250" y="105">6 cm</text><text x="180" y="210" textAnchor="middle">7 cm</text></Svg>}
function Parallelogram(){return <Svg label="Parallelogram — both pairs of opposite sides are parallel"><path d="M95 55 L300 55 L255 180 L50 180 Z" className="geo-shape"/><path d="M102 48l12 7-12 7 M236 173l12 7-12 7 M67 106l7 10-12 2 M282 106l7 10-12 2" className="geo-mark"/><path d="M95 55V180" className="geo-dash"/><path d="M88 163h17v17" className="geo-mark"/><text x="197" y="208" textAnchor="middle">base = 8 cm</text><text x="83" y="120" textAnchor="end">h = 5 cm</text></Svg>}
function Trapezium(){return <Svg label="Trapezium — one pair of opposite sides is parallel"><path d="M105 50 L255 50 L310 180 L45 180 Z" className="geo-shape"/><path d="M168 43l12 7-12 7 M168 173l12 7-12 7" className="geo-mark"/><path d="M105 50V180" className="geo-dash"/><path d="M98 163h17v17" className="geo-mark"/><text x="180" y="37" textAnchor="middle">6 cm</text><text x="180" y="208" textAnchor="middle">10 cm</text><text x="92" y="118" textAnchor="end">h = 4 cm</text></Svg>}
function Circle(){return <Svg label="Circle — radius, diameter and circumference"><circle cx="180" cy="115" r="80" className="geo-shape"/><circle cx="180" cy="115" r="3" className="geo-fill"/><line x1="100" y1="115" x2="260" y2="115" className="geo-line"/><line x1="180" y1="115" x2="235" y2="57" className="geo-line"/><text x="180" y="105" textAnchor="middle">O</text><text x="210" y="80">r</text><text x="180" y="140" textAnchor="middle">diameter d = 2r</text></Svg>}
function Composite(){return <Svg label="Composite L-shape — split into rectangles to find area"><path d="M65 35 H285 V100 H190 V190 H65 Z" className="geo-shape"/><line x1="190" y1="100" x2="65" y2="100" className="geo-dash"/><text x="175" y="25" textAnchor="middle">10 m</text><text x="48" y="115" textAnchor="middle" transform="rotate(-90 48 115)">7 m</text><text x="240" y="90" textAnchor="middle">3 m</text><text x="128" y="120" textAnchor="middle">Rectangle 2</text><text x="175" y="75" textAnchor="middle">Rectangle 1</text></Svg>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}

export default function PlaneShapesLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson geometry-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS · MENSURATION & GEOMETRY</span><h1>Plane Shapes</h1><p>Recognise, compare, measure and solve problems with flat two-dimensional shapes. Every diagram below is part of the mathematics: read its sides, markings, dimensions and labels carefully.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>

<section className="wn-section"><h3>1. What Is a Plane Shape?</h3><p>A plane shape is a flat, two-dimensional figure. It has length and width but no thickness or volume. A drawing on paper, the face of a floor tile, the top of a rectangular table and the circular face of a clock can all model plane shapes.</p><div className="lesson-rule"><span><b>2D means two-dimensional:</b> we measure across the flat surface.</span><span><b>Boundary:</b> the line or curve around the shape.</span><span><b>Vertex:</b> a corner where straight sides meet. The plural is vertices.</span><span><b>Parallel lines:</b> straight lines in the same plane that remain the same distance apart and never meet.</span><span><b>Perpendicular lines:</b> lines that meet at a right angle, 90°.</span></div></section>

<section className="wn-section"><h3>2. Square</h3><Square/><div className="geometry-properties"><span>4 straight sides</span><span>All 4 sides equal</span><span>4 vertices</span><span>4 right angles</span><span>Opposite sides parallel</span></div><p>A square is a special quadrilateral. The small corner marks in the diagram indicate right angles; matching side marks indicate equal lengths.</p></section>

<section className="wn-section"><h3>3. Rectangle</h3><Rectangle/><div className="geometry-properties"><span>4 straight sides</span><span>Opposite sides equal</span><span>4 vertices</span><span>4 right angles</span><span>Opposite sides parallel</span></div><p>A square and rectangle are similar because both have four right angles and two pairs of parallel opposite sides. They differ because a square must have all four sides equal, while a rectangle requires each pair of opposite sides to be equal.</p></section>

<section className="wn-section"><h3>4. Triangle</h3><Triangle/><div className="geometry-properties"><span>3 straight sides</span><span>3 vertices</span><span>3 interior angles</span><span>No diagonal</span></div><p>A triangle is different from the quadrilaterals above because it has three sides rather than four. Its boundary is still made entirely of straight line segments.</p></section>

<section className="wn-section"><h3>5. Parallelogram</h3><Parallelogram/><div className="geometry-properties"><span>4 sides</span><span>Opposite sides equal</span><span>Both pairs of opposite sides parallel</span><span>Opposite angles equal</span></div><p>The sloping side does not change the definition. The dashed line marked h is the <b>perpendicular height</b>. For area, use this perpendicular height—not the sloping side.</p></section>

<section className="wn-section"><h3>6. Trapezium</h3><Trapezium/><div className="geometry-properties"><span>4 sides</span><span>4 vertices</span><span>One pair of opposite sides parallel</span></div><p>The two parallel sides are often called the parallel sides or bases. The height is the perpendicular distance between them.</p></section>

<section className="wn-section"><h3>7. Circle</h3><Circle/><div className="geometry-properties"><span>One continuous curved boundary</span><span>No straight side</span><span>No vertex</span><span>Every point on the circle is the same distance from the centre</span></div><p>The distance from the centre O to the circle is the <b>radius r</b>. A straight line through the centre joining two points on the circle is a <b>diameter d</b>.</p><div className="lesson-rule"><span>d = 2r</span><span>r = d ÷ 2</span><span>The distance around a circle is called its circumference.</span></div></section>

<section className="wn-section"><h3>8. Compare the Shapes</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>Shape</th><th>Sides/boundary</th><th>Vertices</th><th>Parallel sides</th><th>Important feature</th></tr></thead><tbody><tr><td>Square</td><td>4 straight</td><td>4</td><td>2 pairs</td><td>All sides equal; 4 right angles</td></tr><tr><td>Rectangle</td><td>4 straight</td><td>4</td><td>2 pairs</td><td>Opposite sides equal; 4 right angles</td></tr><tr><td>Triangle</td><td>3 straight</td><td>3</td><td>Not required</td><td>Three-sided polygon</td></tr><tr><td>Parallelogram</td><td>4 straight</td><td>4</td><td>2 pairs</td><td>Opposite sides and angles equal</td></tr><tr><td>Trapezium</td><td>4 straight</td><td>4</td><td>1 pair</td><td>One pair of opposite sides parallel</td></tr><tr><td>Circle</td><td>1 curved boundary</td><td>0</td><td>None</td><td>All boundary points equidistant from centre</td></tr></tbody></table></div></section>

<section className="wn-section"><h3>9. Perimeter — Distance Around a Shape</h3><p>Perimeter is the total distance around a closed plane figure. Imagine walking exactly once around its boundary. Add every outside side length. Perimeter is measured in ordinary length units such as mm, cm or m—not square units.</p><div className="lesson-rule"><span>Square: P = 4s</span><span>Rectangle: P = 2(l + w)</span><span>Triangle: P = a + b + c</span><span>Parallelogram: P = 2(a + b)</span><span>Trapezium: add all four sides</span><span>Circle: circumference C = 2πr = πd</span></div></section>

<section className="wn-section"><h3>10. Perimeter of a Square</h3><Square side="side = 5 cm"/><Work q="Find the perimeter of a square whose side is 5 cm."><Line>P = 4s</Line><Line>= 4 × 5 cm</Line><Line strong>= 20 cm</Line></Work></section>

<section className="wn-section"><h3>11. Perimeter of a Rectangle</h3><Rectangle/><Work q="Find the perimeter of a rectangle 8 cm long and 4 cm wide."><Line>P = 2(l + w)</Line><Line>= 2(8 + 4)</Line><Line>= 2 × 12</Line><Line strong>= 24 cm</Line></Work></section>

<section className="wn-section"><h3>12. Perimeter of a Triangle</h3><Triangle/><Work q="The triangle has sides 5 cm, 6 cm and 7 cm. Find its perimeter."><Line>P = 5 + 6 + 7</Line><Line strong>= 18 cm</Line></Work></section>

<section className="wn-section"><h3>13. Circumference of a Circle</h3><Circle/><p>For JSS1 calculations, use the value of π specified in the question; common classroom approximations are 22/7 or 3.142.</p><Work q="Find the circumference of a circle of radius 7 cm. Use π = 22/7."><Line>C = 2πr</Line><Line>= 2 × 22/7 × 7</Line><Line>= 2 × 22</Line><Line strong>= 44 cm</Line></Work><div className="lesson-rule"><span><b>Common mistake:</b> do not confuse radius and diameter. If d = 14 cm, then r = 7 cm.</span></div></section>

<section className="wn-section"><h3>14. Area — Surface Covered</h3><p>Area measures how much flat surface lies inside a boundary. Imagine covering the shape completely with 1 cm by 1 cm squares without gaps or overlaps. Each small square has area 1 cm². That is why area uses <b>square units</b>.</p><div className="lesson-rule"><span>Perimeter → distance around → cm, m</span><span>Area → surface inside → cm², m²</span></div></section>

<section className="wn-section"><h3>15. Area from a Square Grid</h3><div className="grid-area-demo" aria-label="A rectangle made from 24 unit squares">{Array.from({length:24},(_,i)=><span key={i}>{i+1}</span>)}</div><p>This rectangle contains 6 columns and 4 rows of equal unit squares.</p><div className="math-working"><Line>Area = number of unit squares</Line><Line>= 6 × 4</Line><Line strong>= 24 square units</Line></div><p>This practical counting idea explains the rectangle formula rather than asking you to memorise it blindly.</p></section>

<section className="wn-section"><h3>16. Area of a Square</h3><Work q="Find the area of a square with side 5 cm."><Line>A = side × side</Line><Line>= 5 × 5</Line><Line strong>= 25 cm²</Line></Work></section>

<section className="wn-section"><h3>17. Area of a Rectangle</h3><Work q="Find the area of a rectangle 8 cm by 4 cm."><Line>A = length × width</Line><Line>= 8 × 4</Line><Line strong>= 32 cm²</Line></Work></section>

<section className="wn-section"><h3>18. Area of a Triangle</h3><p>A triangle with base b and perpendicular height h occupies half the area of a corresponding parallelogram or rectangle with the same base and height.</p><Work q="Find the area of a triangle with base 10 cm and perpendicular height 6 cm."><Line>A = ½ × base × height</Line><Line>= ½ × 10 × 6</Line><Line>= 5 × 6</Line><Line strong>= 30 cm²</Line></Work></section>

<section className="wn-section"><h3>19. Area of a Parallelogram</h3><Parallelogram/><Work q="Find the area when base = 8 cm and perpendicular height = 5 cm."><Line>A = base × perpendicular height</Line><Line>= 8 × 5</Line><Line strong>= 40 cm²</Line></Work><div className="lesson-rule"><span><b>Do not use the sloping side as the height.</b> Height must meet the base at 90°.</span></div></section>

<section className="wn-section"><h3>20. Area of a Trapezium</h3><Trapezium/><Work q="The parallel sides are 6 cm and 10 cm and the perpendicular height is 4 cm. Find the area."><Line>A = ½(a + b)h</Line><Line>= ½(6 + 10) × 4</Line><Line>= ½ × 16 × 4</Line><Line strong>= 32 cm²</Line></Work></section>

<section className="wn-section"><h3>21. Irregular and Composite Plane Shapes</h3><p>An irregular figure may not have one direct formula. A reliable method is to split it into familiar shapes, calculate each area, then add or subtract as required.</p><Composite/><Work q="The L-shaped floor is 10 m across the top and 7 m high. The top strip is 3 m high, and the lower left part is 5 m wide. Find its total area."><Line>Split the L-shape along the dashed line into Rectangle 1 and Rectangle 2.</Line><Line>Rectangle 1: length = 10 m, width = 3 m</Line><Line>Area 1 = 10 × 3 = 30 m²</Line><Line>Rectangle 2 height = 7 − 3 = 4 m</Line><Line>Rectangle 2: length = 5 m, width = 4 m</Line><Line>Area 2 = 5 × 4 = 20 m²</Line><Line>Total area = Area 1 + Area 2</Line><Line>= 30 + 20</Line><Line strong>= 50 m²</Line><Line>Check: the L-shape is smaller than the enclosing 10 m × 7 m rectangle (70 m²), so 50 m² is reasonable.</Line></Work><p>Notice that we did not guess the missing height. We derived it from the full height: 7 m − 3 m = 4 m.</p></section>

<section className="wn-section"><h3>22. Real-Life Application — Tiling a Floor</h3><Work q="A rectangular classroom floor is 8 m long and 6 m wide. Find the floor area to be tiled."><Line>A = l × w</Line><Line>= 8 × 6</Line><Line strong>= 48 m²</Line></Work><p>Area answers how much surface must be covered. If the question instead asks for skirting around the room, that is a perimeter problem.</p></section>

<section className="wn-section"><h3>23. Real-Life Application — Fencing</h3><Work q="A rectangular garden is 12 m by 7 m. How much fencing is needed to go once around it?"><Line>P = 2(l + w)</Line><Line>= 2(12 + 7)</Line><Line>= 2 × 19</Line><Line strong>= 38 m</Line></Work><p>Fencing follows the boundary, so use perimeter rather than area.</p></section>

<section className="wn-section"><h3>24. Similarities and Differences — Think Like a Geometer</h3><div className="lesson-rule"><span><b>Square & rectangle:</b> both have four right angles and opposite sides parallel; only the square requires all four sides equal.</span><span><b>Rectangle & parallelogram:</b> both have opposite sides equal and parallel; a rectangle has four right angles, while a general parallelogram need not.</span><span><b>Parallelogram & trapezium:</b> both are quadrilaterals; a parallelogram has two pairs of parallel opposite sides, while a trapezium here is identified by one pair.</span><span><b>Triangle & quadrilaterals:</b> a triangle has 3 sides and 3 vertices; a quadrilateral has 4 sides and 4 vertices.</span><span><b>Circle & polygons:</b> a circle has a curved boundary and no vertices; polygons are bounded by straight line segments.</span></div></section>

<section className="wn-section"><h3>25. Common Mistakes</h3><div className="lesson-rule"><span><b>Perimeter vs area:</b> perimeter is around; area is inside.</span><span><b>Units:</b> write cm or m for perimeter, but cm² or m² for area.</span><span><b>Parallelogram:</b> use perpendicular height for area, not the sloping side.</span><span><b>Circle:</b> radius is half the diameter.</span><span><b>Missing sides:</b> do not invent measurements on irregular figures; derive them only when the diagram provides enough information.</span><span><b>Diagram reading:</b> a drawing that looks square is not proof that all sides are equal; rely on dimensions and mathematical markings.</span></div></section>

<section className="wn-section"><h3>26. AVORA Geometry Method</h3><div className="lesson-rule"><span><b>1. Identify</b> the shape or split a composite figure into known shapes.</span><span><b>2. Read</b> every label, side mark, right-angle mark and parallel mark.</span><span><b>3. Decide</b> whether the question asks for boundary distance or surface area.</span><span><b>4. Write</b> the correct formula before inserting numbers.</span><span><b>5. Substitute</b> the measurements with consistent units.</span><span><b>6. Calculate</b> one step at a time.</span><span><b>7. State</b> the final answer with the correct unit.</span><span><b>8. Sense-check</b> whether the result is reasonable for the diagram.</span></div></section>

<section className="wn-section"><h3>27. Mastery Check</h3><p>You are ready for the exercise when you can identify and compare all six required plane shapes, explain their important properties from a diagram, calculate their perimeters, distinguish radius from diameter, calculate areas using the correct base and perpendicular height, use square-grid reasoning, solve simple irregular/composite-area problems, and decide whether a real-life problem requires perimeter or area.</p></section>
<div className="lesson-action"><button type="button" className="primary-btn" onClick={onExercise}>Go to Exercise →</button></div>
</article>}
