'use client';
const objectives=['explain algebraic expressions, terms, variables, constants and coefficients','identify positive and negative coefficients, including the hidden coefficients 1 and −1','distinguish like terms from unlike terms','add and subtract like terms correctly','collect several groups of like terms and constants','remove brackets preceded by + or − correctly','expand brackets using the distributive law','simplify expressions after expanding brackets','insert brackets by taking out a common numerical factor','translate simple everyday situations into algebraic expressions','solve bracket and quantitative-reasoning problems','identify and correct common simplification errors'];
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
export default function SimplificationAlgebraLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson algebra-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS</span><h1>Simplification of Algebraic Expressions</h1><p>Learn the language of algebra, recognise genuine like terms, handle signs and brackets correctly, and reduce expressions to their simplest correct form.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>
<section className="wn-section"><h3>1. What is an Algebraic Expression?</h3><p>Algebra uses letters to represent numbers or quantities. Examples of algebraic expressions include 3x + 5, 7a, 4m + 3, 6x − 2y and 5p + 3q − 8. An expression has no equality sign. For example, 3x + 5 is an expression, while 3x + 5 = 17 is an equation.</p></section>
<section className="wn-section"><h3>2. Terms and Their Signs</h3><p>Terms are the chunks separated by + or − signs, and the sign belongs to the term that follows it.</p><div className="math-working"><Line>5x + 3y − 7</Line><Line>Terms: 5x, 3y, −7</Line><Line>8a − 4b + 6</Line><Line strong>Terms: 8a, −4b, 6</Line></div></section>
<section className="wn-section"><h3>3. Variables, Constants and Coefficients</h3><p>In 7x + 4, x is the variable, 4 is a constant, and 7 is the coefficient of x. The sign is part of the coefficient: in −8m, the coefficient is −8.</p><div className="lesson-rule"><span>x = 1x, so the coefficient of x is 1.</span><span>−y = −1y, so the coefficient of y is −1.</span></div></section>
<section className="wn-section"><h3>4. Like and Unlike Terms</h3><p>Like terms have exactly the same variable part, including the same powers. Their coefficients may differ.</p><div className="lesson-rule"><span>3x, 7x, −2x and x are like terms.</span><span>5xy, −2xy and 8xy are like terms.</span><span>3x and 5y are unlike terms.</span><span>2x and 2x² are unlike terms.</span><span>3xy and 3x are unlike terms.</span></div><p>Only like terms can be combined. Think of 3x + 4x as three of one kind plus four more of the same kind, giving 7x. But 3x + 4y must remain separate.</p></section>
<section className="wn-section"><h3>5. Adding and Subtracting Like Terms</h3><Work q="Simplify 4x + 5x."><Line>4x + 5x</Line><Line>= (4 + 5)x</Line><Line strong>= 9x</Line></Work><Work q="Simplify 6a + 3a + a."><Line>a = 1a</Line><Line>= (6 + 3 + 1)a</Line><Line strong>= 10a</Line></Work><Work q="Simplify 12p − 5p − 3p."><Line>= (12 − 5 − 3)p</Line><Line strong>= 4p</Line></Work></section>
<section className="wn-section"><h3>6. Positive and Negative Coefficients</h3><Work q="Simplify 3x − 8x + 6x."><Line>= (3 − 8 + 6)x</Line><Line>= 1x</Line><Line strong>= x</Line></Work><Work q="Simplify 4y − 9y."><Line>= (4 − 9)y</Line><Line strong>= −5y</Line></Work></section>
<section className="wn-section"><h3>7. Collect Several Groups of Like Terms</h3><Work q="Simplify 4a + 3b + 2a + 5b."><Line>Group like terms:</Line><Line>(4a + 2a) + (3b + 5b)</Line><Line strong>= 6a + 8b</Line></Work><Work q="Simplify 5x + 7 + 3x − 2."><Line>(5x + 3x) + (7 − 2)</Line><Line strong>= 8x + 5</Line></Work><Work q="Simplify 7x + 4y − 2x + 3 − 6y + 5."><Line>(7x − 2x) + (4y − 6y) + (3 + 5)</Line><Line strong>= 5x − 2y + 8</Line></Work></section>
<section className="wn-section"><h3>8. Brackets with a Positive Sign</h3><p>A + sign before a bracket does not change the signs inside.</p><Work q="Simplify (4x + 3) + (2x + 5)."><Line>4x + 3 + 2x + 5</Line><Line>(4x + 2x) + (3 + 5)</Line><Line strong>= 6x + 8</Line></Work></section>
<section className="wn-section"><h3>9. Brackets with a Negative Sign</h3><p>A minus sign before a bracket changes the sign of every term inside the bracket.</p><Work q="Simplify 7x − (3x + 4)."><Line>7x − 3x − 4</Line><Line strong>= 4x − 4</Line></Work><Work q="Simplify 10a − (4a − 3)."><Line>−(4a − 3) becomes −4a + 3</Line><Line>10a − 4a + 3</Line><Line strong>= 6a + 3</Line></Work><div className="lesson-rule"><span><b>Critical rule:</b> when a whole bracket is subtracted, change every sign inside it.</span></div></section>
<section className="wn-section"><h3>10. Multiplying Through a Bracket</h3><p>The number or term outside a bracket multiplies every term inside. This is the distributive law.</p><Work q="Expand 3(x + 4)."><Line>3 × x + 3 × 4</Line><Line strong>= 3x + 12</Line></Work><Work q="Expand 5(x − 2)."><Line>5 × x − 5 × 2</Line><Line strong>= 5x − 10</Line></Work><Work q="Expand −3(2x − 5)."><Line>(−3)(2x) + (−3)(−5)</Line><Line strong>= −6x + 15</Line></Work></section>
<section className="wn-section"><h3>11. Expand, Then Collect</h3><Work q="Simplify 2(x + 3) + 4x."><Line>2x + 6 + 4x</Line><Line>(2x + 4x) + 6</Line><Line strong>= 6x + 6</Line></Work><Work q="Simplify 3(2a + 4) − 5a."><Line>6a + 12 − 5a</Line><Line strong>= a + 12</Line></Work><Work q="Simplify (14m − 8) + (6m + 5)."><Line>14m − 8 + 6m + 5</Line><Line>(14m + 6m) + (−8 + 5)</Line><Line strong>= 20m − 3</Line></Work><Work q="Simplify (9x + 7) − (4x + 2)."><Line>9x + 7 − 4x − 2</Line><Line>(9x − 4x) + (7 − 2)</Line><Line strong>= 5x + 5</Line></Work></section>
<section className="wn-section"><h3>12. Inserting Brackets</h3><p>Brackets can show a common factor. If every term has the same numerical factor, take that factor outside.</p><div className="math-working"><Line>3x + 6 = 3(x + 2)</Line><Line>Check: 3(x + 2) = 3x + 6</Line><Line>4a − 12 = 4(a − 3)</Line><Line strong>Check: 4(a − 3) = 4a − 12</Line></div></section>
<section className="wn-section"><h3>13. Algebra from Everyday Situations</h3><Work q="One exercise book costs ₦x. What is the total cost of 5 books, a ₦200 pen, and another 2 books?"><Line>5x + 200 + 2x</Line><Line>(5x + 2x) + 200</Line><Line strong>= 7x + 200</Line></Work><Work q="A girl has x oranges. Her brother gives her 3x oranges and her mother gives her 4 more. Simplify the total."><Line>x + 3x + 4</Line><Line strong>= 4x + 4</Line></Work><Work q="A school buys 3 packets containing x + 5 pencils each. Simplify the total."><Line>3(x + 5)</Line><Line strong>= 3x + 15</Line></Work></section>
<section className="wn-section"><h3>14. Quantitative Reasoning with Brackets</h3><Work q="If 2(□ + 3) = 14, find □."><Line>2□ + 6 = 14</Line><Line>2□ = 8</Line><Line>□ = 4</Line><Line>Check: 2(4 + 3) = 14</Line><Line strong>Therefore □ = 4.</Line></Work><p>This prepares you for the next curriculum topic, Simple Equations, without replacing that lesson.</p></section>
<section className="wn-section"><h3>15. Common Misconceptions</h3><div className="lesson-rule"><span><b>Do not combine unlike terms:</b> 3x + 4y cannot become 7xy.</span><span><b>Keep the hidden coefficient:</b> x = 1x and −x = −1x.</span><span><b>Keep every sign attached to its term:</b> in 5x − 7y, the coefficient of y is −7.</span><span><b>Minus before a bracket changes every sign:</b> −(2x − 5) = −2x + 5.</span><span><b>Multiply every term in a bracket:</b> 3(x + 4) = 3x + 12, not 3x + 4.</span><span><b>Do not change the variable power:</b> 2x + 3x = 5x, not 5x².</span></div></section>
<section className="wn-section"><h3>AVORA Simplification Method</h3><div className="lesson-rule"><span>1. Identify every term and keep its sign.</span><span>2. Identify each coefficient and variable part.</span><span>3. Remove or expand brackets correctly.</span><span>4. Group terms with exactly the same variable part.</span><span>5. Add or subtract their coefficients.</span><span>6. Keep unlike terms separate.</span><span>7. Check that no more like terms remain.</span></div></section>
<section className="wn-section"><h3>Mastery Check</h3><ul><li>Explain why 4x + 3x = 7x but 4x + 3y cannot be combined.</li><li>Identify coefficients including 1, −1 and other negative coefficients.</li><li>Explain why −(2x − 5) = −2x + 5.</li><li>Expand a bracket by multiplying every term inside.</li><li>Simplify expressions containing variables, constants and brackets.</li><li>Translate a simple everyday situation into an algebraic expression.</li></ul></section>
<div className="teacher-actions"><button type="button" className="primary" onClick={onExercise}>Go to Exercise →</button></div>
</article>}