'use client';
const objectives=['explain what an equation means and distinguish an expression from an equation','identify the unknown and explain the equality sign as balance','translate word sentences into mathematical equations and equations into words','solve one-step equations involving addition, subtraction, multiplication and division','solve simple two-step equations','simplify like terms when necessary before solving','solve simple equations containing brackets','form and solve equations from everyday word problems','cross-check every solution by substitution'];
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
export default function SimpleEquationsLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson algebra-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS</span><h1>Simple Equations</h1><p>Understand equations as balanced mathematical statements, form them from words, solve them step by step, and prove every answer by substitution.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>
<section className="wn-section"><h3>1. What is an Equation?</h3><p>An algebraic expression such as 3x + 5 has no equality sign. An equation such as 3x + 5 = 20 states that the value on the left is equal to the value on the right.</p><div className="lesson-rule"><span>Expression: 3x + 5</span><span>Equation: 3x + 5 = 20</span></div><p>Think of an equation as a balanced scale: whatever valid operation is performed on one side must also be performed on the other side to preserve equality.</p></section>
<section className="wn-section"><h3>2. The Unknown and the Equality Sign</h3><p>In x + 4 = 11, x is the unknown. Solving means finding the value that makes the equation true. The sign = means that both sides have the same value; it does not merely mean “write the answer next.”</p><div className="math-working"><Line>x + 4 = 11</Line><Line>7 + 4 = 11</Line><Line strong>Therefore x = 7.</Line></div></section>
<section className="wn-section"><h3>3. Inverse Operations</h3><p>We isolate an unknown by undoing the operation acting on it. Addition and subtraction are inverse operations; multiplication and division are inverse operations.</p><div className="lesson-rule"><span>Addition ↔ Subtraction</span><span>Multiplication ↔ Division</span><span>Do not rely on “move across and change sign.” The real reason is that the same balancing operation is performed on both sides.</span></div></section>
<section className="wn-section"><h3>4. Equations Involving Addition</h3><Work q="Solve x + 5 = 12."><Line>x + 5 = 12</Line><Line>x + 5 − 5 = 12 − 5</Line><Line strong>x = 7</Line><Line>Check: 7 + 5 = 12 ✓</Line></Work></section>
<section className="wn-section"><h3>5. Equations Involving Subtraction</h3><Work q="Solve x − 6 = 9."><Line>x − 6 = 9</Line><Line>x − 6 + 6 = 9 + 6</Line><Line strong>x = 15</Line><Line>Check: 15 − 6 = 9 ✓</Line></Work></section>
<section className="wn-section"><h3>6. The Unknown May Appear on Either Side</h3><Work q="Solve 18 = x + 7."><Line>18 = x + 7</Line><Line>18 − 7 = x + 7 − 7</Line><Line>11 = x</Line><Line strong>x = 11</Line></Work></section>
<section className="wn-section"><h3>7. Equations Involving Multiplication</h3><p>Remember that 5x means 5 × x.</p><Work q="Solve 5x = 30."><Line>5x = 30</Line><Line>5x ÷ 5 = 30 ÷ 5</Line><Line strong>x = 6</Line><Line>Check: 5(6) = 30 ✓</Line></Work></section>
<section className="wn-section"><h3>8. Equations Involving Division</h3><Work q="Solve x/4 = 7."><Line>x/4 = 7</Line><Line>4 × (x/4) = 7 × 4</Line><Line strong>x = 28</Line><Line>Check: 28/4 = 7 ✓</Line></Work></section>
<section className="wn-section"><h3>9. Two-Step Equations</h3><p>When more than one operation acts on the unknown, undo the operations carefully while keeping both sides balanced.</p><Work q="Solve 2x + 3 = 11."><Line>2x + 3 = 11</Line><Line>2x = 8</Line><Line>x = 4</Line><Line strong>Check: 2(4) + 3 = 11 ✓</Line></Work><Work q="Solve 3x − 5 = 16."><Line>3x − 5 = 16</Line><Line>3x = 21</Line><Line>x = 7</Line><Line strong>Check: 3(7) − 5 = 16 ✓</Line></Work></section>
<section className="wn-section"><h3>10. Collect Like Terms Before Solving</h3><Work q="Solve 2x + 3x = 20."><Line>2x + 3x = 20</Line><Line>5x = 20</Line><Line>x = 4</Line><Line strong>Check: 2(4) + 3(4) = 20 ✓</Line></Work></section>
<section className="wn-section"><h3>11. Equations Containing Brackets</h3><Work q="Solve 2(x + 3) = 14."><Line>2(x + 3) = 14</Line><Line>x + 3 = 7</Line><Line>x = 4</Line><Line strong>Check: 2(4 + 3) = 14 ✓</Line></Work><p>You may also expand first: 2x + 6 = 14, then 2x = 8, so x = 4. Both methods preserve equality.</p><Work q="Solve 3(x − 5) = 30."><Line>3(x − 5) = 30</Line><Line>x − 5 = 10</Line><Line>x = 15</Line><Line strong>Check: 3(15 − 5) = 30 ✓</Line></Work></section>
<section className="wn-section"><h3>12. Translate Words into Equations</h3><p>NERDC expects you to represent word sentences using equations. Choose a letter for the unknown, translate each relationship carefully, then solve.</p><div className="lesson-rule"><span>A number increased by 6 is 15 → x + 6 = 15</span><span>A number decreased by 4 is 10 → x − 4 = 10</span><span>Three times a number is 21 → 3x = 21</span><span>Five more than twice a number is 17 → 2x + 5 = 17</span><span>Four less than three times a number is 20 → 3x − 4 = 20</span><span>One-third of a number is 8 → x/3 = 8</span></div><p>Order matters: “5 less than a number” means x − 5, not 5 − x.</p></section>
<section className="wn-section"><h3>13. Translate Equations Back into Words</h3><div className="lesson-rule"><span>x + 7 = 20 → Seven added to a number gives twenty.</span><span>4x = 28 → Four times a number is twenty-eight.</span><span>2x − 3 = 11 → Three subtracted from twice a number gives eleven.</span></div></section>
<section className="wn-section"><h3>14. Word Problem — Pencils</h3><Work q="Tunde has some pencils. His friend gives him 5 more. He now has 12. How many did he have?"><Line>Let the original number be x.</Line><Line>x + 5 = 12</Line><Line>x = 7</Line><Line strong>Tunde originally had 7 pencils.</Line><Line>Check: 7 + 5 = 12 ✓</Line></Work></section>
<section className="wn-section"><h3>15. Word Problem — Books</h3><Work q="Three identical books cost ₦1,500. Find the cost x of one book."><Line>3x = 1500</Line><Line>x = 1500 ÷ 3</Line><Line strong>x = ₦500</Line><Line>Check: 3 × 500 = 1500 ✓</Line></Work></section>
<section className="wn-section"><h3>16. Word Problem — Transport</h3><Work q="A taxi costs ₦200 plus ₦100 per kilometre. The total is ₦700. Find the distance."><Line>Let the distance be x km.</Line><Line>100x + 200 = 700</Line><Line>100x = 500</Line><Line>x = 5</Line><Line strong>The journey was 5 km.</Line><Line>Check: 100(5) + 200 = 700 ✓</Line></Work></section>
<section className="wn-section"><h3>17. Word Problem Requiring Simplification</h3><Work q="A boy has x marbles. His sister has twice as many. Together they have 24. How many does the boy have?"><Line>x + 2x = 24</Line><Line>3x = 24</Line><Line>x = 8</Line><Line strong>The boy has 8 marbles; his sister has 16.</Line><Line>Check: 8 + 16 = 24 ✓</Line></Work></section>
<section className="wn-section"><h3>18. Cross-Checking by Substitution</h3><p>Cross-checking is part of the curriculum objective. Substitute your solution into the original equation and verify that both sides have the same value.</p><Work q="Check x = 6 for 4x + 3 = 27."><Line>4(6) + 3</Line><Line>= 24 + 3</Line><Line>= 27</Line><Line strong>27 = 27 ✓, so x = 6 is correct.</Line></Work></section>
<section className="wn-section"><h3>19. Detect a Wrong Answer by Checking</h3><Work q="A learner says x = 3 solves 3x + 2 = 14. Check and correct it."><Line>3(3) + 2 = 11</Line><Line>11 ≠ 14, so x = 3 is wrong.</Line><Line>3x + 2 = 14</Line><Line>3x = 12</Line><Line>x = 4</Line><Line strong>Check: 3(4) + 2 = 14 ✓</Line></Work></section>
<section className="wn-section"><h3>20. Common Misconceptions</h3><div className="lesson-rule"><span><b>Equality:</b> = means both sides have the same value, not simply “the answer comes next.”</span><span><b>Balance:</b> do not alter only one side of an equation.</span><span><b>Reason, not a trick:</b> “cross over and change sign” hides the real inverse operation being performed.</span><span><b>Coefficient:</b> 3x means 3 × x.</span><span><b>Brackets:</b> every term inside must be handled correctly.</span><span><b>Check:</b> always substitute into the original equation.</span></div></section>
<section className="wn-section"><h3>21. AVORA Equation Method</h3><div className="lesson-rule"><span><b>1.</b> Identify the unknown and understand the statement.</span><span><b>2.</b> Form the equation carefully.</span><span><b>3.</b> Simplify first if necessary: collect like terms or handle brackets.</span><span><b>4.</b> Preserve balance using inverse operations.</span><span><b>5.</b> Isolate the unknown.</span><span><b>6.</b> State the solution clearly.</span><span><b>7.</b> Substitute into the original equation and cross-check.</span></div></section>
<section className="wn-section"><h3>22. Mastery Check</h3><p>You are ready for the exercise when you can explain equation balance, form equations from words, solve one-step and two-step equations, handle simple brackets and like terms, solve contextual problems, and verify every answer by substitution.</p></section>
<div className="lesson-action"><button type="button" className="primary-btn" onClick={onExercise}>Go to Exercise →</button></div>
</article>}
