'use client';
import {FormEvent,useEffect,useState} from 'react';

export default function StudentParentConnect(){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[inviteBusy,setInviteBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){const r=await fetch('/api/parent-link-code',{cache:'no-store'}),d=await r.json();if(r.ok)setData(d);else setError(d.error||'Could not create link code.')}
 useEffect(()=>{load()},[]);
 async function renew(){setBusy(true);setError('');setNotice('');const r=await fetch('/api/parent-link-code',{method:'POST'}),d=await r.json();setBusy(false);if(r.ok)setData(d);else setError(d.error||'Could not refresh code.')}
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();setInviteBusy(true);setError('');setNotice('');const f=new FormData(e.currentTarget);const r=await fetch('/api/parent-link-code/invite',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({parentEmail:f.get('parentEmail')})});const d=await r.json();setInviteBusy(false);if(!r.ok){setError(d.error||'Could not invite your parent.');return}setData({code:d.code,expires_at:d.expires_at});setNotice(d.message||'Invitation prepared.');}
 return <main className="shell parent-connect-page"><section className="student-parent-connect"><span className="section-kicker">PARENT CONNECTION</span><h1>Connect your parent in one clear step.</h1><p>Your learner account stays yours. A parent or guardian gets a separate AVORA Parent account and can see progress, assessment evidence and next steps without answering work for you.</p>
  <div className="parent-connect-choice-grid">
   <form className="parent-connect-invite" onSubmit={invite}><span>RECOMMENDED</span><h2>Invite my parent by email</h2><p>Enter your parent or guardian’s email. AVORA sends them the secure connection code and tells them exactly what to do. They must still sign in and accept the connection.</p><label>Parent / guardian email<input type="email" name="parentEmail" required autoComplete="email" placeholder="parent@example.com"/></label><button className="premium-primary" disabled={inviteBusy}>{inviteBusy?'Sending invitation…':'Invite my parent →'}</button></form>
   <div className="parent-connect-code-panel"><span>OR USE A CODE</span><h2>Show this code to my parent</h2><p>If you are together, your parent can create or sign in to a Parent account, open <b>Children</b>, and enter this code.</p>{data?<div className="parent-code-card"><small>ONE-TIME LINK CODE</small><strong>{data.code}</strong><span>Expires {new Date(data.expires_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</span></div>:<div className="parent-code-card"><span>Preparing your secure code…</span></div>}<button type="button" onClick={renew} disabled={busy}>{busy?'Creating…':'Generate a new code'}</button><a href="/parent/register">Parent needs an account? Create one →</a></div>
  </div>
  {notice&&<p className="notice success">{notice}</p>}{error&&<p className="form-error">{error}</p>}
  <aside className="parent-connect-explainer"><b>Two supported family flows</b><p><strong>Child starts:</strong> you invite your parent or show them a code; the parent signs in and accepts it. <strong>Parent starts:</strong> the parent creates a Parent account and can either create your learner profile (if you are new) or enter your existing learner code. AVORA never creates a duplicate child account just because a family is connecting.</p><p><strong>Seat and trial rule:</strong> once linked, your learner identity uses one of the family’s three learner seats. Linking to a parent does not restart or extend your existing learner trial.</p></aside>
 </section></main>}
