'use client';
import {FormEvent,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';

type Thread={id:string;title:string;category:string;subject?:string|null;status:string;priority:string;current_topic_snapshot?:string|null;last_message_at:string;last_message?:string|null;last_sender?:string|null};
type Message={id:string;sender_role:string;body:string;created_at:string;sender_name?:string|null};

export default function SupportChat(){
 const streamEndRef=useRef<HTMLDivElement|null>(null);
 const [threads,setThreads]=useState<Thread[]>([]),[active,setActive]=useState<string>(''),[messages,setMessages]=useState<Message[]>([]),[thread,setThread]=useState<any>(null),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(''),[showNew,setShowNew]=useState(false);
 const activeThread=useMemo(()=>threads.find(t=>t.id===active),[threads,active]);
 async function loadThreads(){const r=await fetch('/api/support',{cache:'no-store'});const d=await r.json();if(r.ok){setThreads(d.threads||[]);if(!active&&d.threads?.[0])setActive(d.threads[0].id)}else setError(d.error||'Could not load support.')}
 async function loadMessages(id=active){if(!id)return;const r=await fetch(`/api/support/${id}/messages`,{cache:'no-store'});const d=await r.json();if(r.ok){setMessages(d.messages||[]);setThread(d.thread)}else setError(d.error||'Could not load conversation.')}
 useEffect(()=>{loadThreads().finally(()=>setLoading(false))},[]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(active)loadMessages(active)},[active]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!active)return;const timer=setInterval(()=>{loadMessages(active);loadThreads()},5000);return()=>clearInterval(timer)},[active]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{streamEndRef.current?.scrollIntoView({block:'end',behavior:'smooth'})},[active,messages.length]);
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!active)return;const f=new FormData(e.currentTarget),message=String(f.get('message')||'').trim();if(!message)return;setSending(true);setError('');const r=await fetch(`/api/support/${active}/messages`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message})});const d=await r.json();setSending(false);if(!r.ok){setError(d.error||'Could not send message.');return}e.currentTarget.reset();await Promise.all([loadMessages(active),loadThreads()])}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setSending(true);setError('');const r=await fetch('/api/support',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:f.get('title'),category:f.get('category'),subject:f.get('subject'),message:f.get('message')})});const d=await r.json();setSending(false);if(!r.ok){setError(d.error||'Could not start conversation.');return}setShowNew(false);await loadThreads();setActive(d.id)}
 if(loading)return <div className="support-loading">Opening your AVORA support space…</div>;
 return <div className="support-layout">
  <aside className="support-list-panel">
   <div className="support-list-head"><div><span>YOUR CONVERSATIONS</span><b>Human assistance</b></div><button type="button" onClick={()=>setShowNew(true)}>New</button></div>
   <p className="support-assurance">Ask for learning help or account assistance. A real AVORA support person can reply inside the app.</p>
   <div className="support-thread-list">{threads.length?threads.map(t=><button key={t.id} type="button" className={active===t.id?'active':''} onClick={()=>setActive(t.id)}><span className="support-thread-top"><b>{t.title}</b><em className={`support-status support-${t.status.toLowerCase().replaceAll('_','-')}`}>{t.status.replaceAll('_',' ')}</em></span><small>{t.subject||t.category.replaceAll('_',' ')}{t.current_topic_snapshot?` · ${t.current_topic_snapshot}`:''}</small><p>{t.last_message||'Conversation started'}</p><time>{new Date(t.last_message_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</time></button>):<div className="support-empty-small"><b>No conversation yet.</b><span>Start one whenever you need a human.</span></div>}</div>
  </aside>
  <section className="support-chat-panel">{activeThread&&thread?<>
   <header className="support-chat-head"><div><span>{thread.subject||thread.category?.replaceAll('_',' ')}</span><h2>{thread.title}</h2><p>{thread.current_topic_snapshot?`Learning context: ${thread.current_topic_snapshot}`:'AVORA human support'}</p></div><em className={`support-status support-${thread.status.toLowerCase().replaceAll('_','-')}`}>{thread.status.replaceAll('_',' ')}</em></header>
   <div className="support-message-stream" aria-live="polite">{messages.map(m=><article key={m.id} className={`support-bubble ${m.sender_role==='STUDENT'?'mine':'theirs'}`}><div><b>{m.sender_role==='STUDENT'?'You':m.sender_name||'AVORA Support'}</b><time>{new Date(m.created_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</time></div><p>{m.body}</p></article>)}<div ref={streamEndRef} aria-hidden="true" /></div>
   {thread.status==='CLOSED'?<div className="support-closed">This conversation is closed. Start a new conversation if you still need help.</div>:<form className="support-compose" onSubmit={send}><label htmlFor="support-message">Message AVORA Support</label><textarea id="support-message" name="message" maxLength={4000} placeholder="Explain what you need help with…" required/><div><small>Support can see your class and recent learning context so you do not have to explain everything again.</small><button disabled={sending}>{sending?'Sending…':'Send message'}</button></div></form>}
  </>:<div className="support-empty-main"><span>HUMAN SUPPORT</span><h2>AVORA is not only an automated tutor.</h2><p>When you need a real person, start a conversation here. Your learning context can travel with the request so support understands where you are.</p><button type="button" onClick={()=>setShowNew(true)}>Start a conversation</button><Link href="/home">Return home</Link></div>}</section>
  {showNew&&<div className="support-modal-backdrop"><form className="support-new-modal" onSubmit={create}><header><div><span>NEW SUPPORT REQUEST</span><h2>How can we help?</h2></div><button type="button" onClick={()=>setShowNew(false)} aria-label="Close">×</button></header><label>Type<select name="category" defaultValue="LEARNING_HELP"><option value="LEARNING_HELP">Learning help</option><option value="ACCOUNT_HELP">Account help</option><option value="LIVE_ASSESSMENT">Live assessment</option><option value="PARENT_SCHOOL">Parent / school</option><option value="OTHER">Other</option></select></label><label>Subject<select name="subject" defaultValue="Mathematics"><option>Mathematics</option><option>English Language</option><option value="">General / account</option></select></label><label>Short subject<input name="title" maxLength={160} placeholder="e.g. I still do not understand linear equations" required/></label><label>Tell us what is happening<textarea name="message" maxLength={4000} placeholder="Describe the problem clearly…" required/></label>{error&&<p className="form-error">{error}</p>}<footer><button type="button" onClick={()=>setShowNew(false)}>Cancel</button><button className="premium-primary" disabled={sending}>{sending?'Starting…':'Start conversation'}</button></footer></form></div>}
  {error&&!showNew&&<div className="support-toast">{error}</div>}
 </div>
}
