'use client';
import React from 'react';
const objectives=['explain the difference between two-dimensional and three-dimensional figures','identify cubes, cuboids, pyramids, cones, cylinders and spheres from diagrams and real objects','identify faces or surfaces, edges and vertices correctly','state and compare the basic properties of the required three-dimensional figures','distinguish flat faces from curved surfaces','recognise cube and cuboid nets as arrangements of faces','explain volume as the space occupied by a solid','derive the volume rule for a cuboid from unit cubes','calculate the volume of cubes and cuboids','find a missing dimension of a cube or cuboid when enough information is given','apply volume to practical containers, cartons and blocks','use cubic units correctly and check whether an answer is reasonable'];
function Svg({children,label}:{children:React.ReactNode;label:string}){return <figure className="geometry-figure solid-figure"><svg viewBox="0 0 380 250" role="img" aria-label={label}>{children}</svg><figcaption>{label}</figcaption></figure>}
function Cube(){return <Svg label="Cube — 6 equal square faces, 12 edges and 8 vertices"><path d="M85 75h155v135H85z M140 35h155v135H240 M85 75l55-40 M240 75l55-40 M240 210l55-40" className="geo-shape"/><text x="72" y="72">A</text><text x="244" y="72">B</text><text x="244" y="225">C</text><text x="72" y="225">D</text><text x="132" y="28">E</text><text x="300" y="32">F</text><text x="300" y="180">G</text><text x="130" y="172">H</text></Svg>}
function Cuboid(){return <Svg label="Cuboid — 6 rectangular faces, 12 edges and 8 vertices"><path d="M55 85h220v120H55z M110 45h220v120H275 M55 85l55-40 M275 85l55-40 M275 205l55-40" className="geo-shape"/><text x="165" y="228" textAnchor="middle">length</text><text x="39" y="150" transform="rotate(-90 39 150)" textAnchor="middle">height</text><text x="307" y="194" transform="rotate(-37 307 194)" textAnchor="middle">width</text></Svg>}
function Pyramid(){return <Svg label="Square-based pyramid — one square base and four triangular faces"><path d="M190 28L55 180L235 218L325 145Z M190 28L235 218 M55 180L325 145" className="geo-shape"/><path d="M190 28L190 181" className="geo-dash"/><text x="196" y="24">apex</text><text x="186" y="196">square base</text></Svg>}
function Cone(){return <Svg label="Cone — one circular base, one curved surface and one vertex"><ellipse cx="190" cy="190" rx="105" ry="30" className="geo-shape"/><path d="M190 35L85 190 M190 35L295 190" className="geo-shape"/><path d="M190 35V190" className="geo-dash"/><text x="198" y="32">vertex</text><text x="202" y="118">height</text><text x="190" y="226" textAnchor="middle">circular base</text></Svg>}
function Cylinder(){return <Svg label="Cylinder — two equal parallel circular faces and one curved surface"><ellipse cx="190" cy="55" rx="100" ry="30" className="geo-shape"/><path d="M90 55V190 M290 55V190" className="geo-shape"/><ellipse cx="190" cy="190" rx="100" ry="30" className="geo-shape"/><path d="M190 55V190" className="geo-dash"/><text x="205" y="125">height</text></Svg>}
function Sphere(){return <Svg label="Sphere — one continuous curved surface; no edges and no vertices"><circle cx="190" cy="125" r="92" className="geo-shape"/><ellipse cx="190" cy="125" rx="92" ry="28" className="geo-dash"/><path d="M190 33c-40 32-40 152 0 184 M190 33c40 32 40 152 0 184" className="geo-dash"/><circle cx="190" cy="125" r="3" className="geo-fill"/><text x="200" y="119">centre</text></Svg>}
function UnitCuboid(){return <Svg label="Cuboid built from unit cubes — 4 × 3 × 2 = 24 unit cubes"><path d="M70 85h200v105H70z M120 50h200v105H270 M70 85l50-35 M270 85l50-35 M270 190l50-35" className="geo-shape"/>{[120,170,220].map(x=><line key={'v'+x} x1={x} y1="85" x2={x} y2="190" className="geo-grid"/>) }{[120,155].map(y=><line key={'h'+y} x1="70" y1={y} x2="270" y2={y} className="geo-grid"/>) }<text x="170" y="220" textAnchor="middle">4 units</text><text x="53" y="140" textAnchor="middle" transform="rotate(-90 53 140)">3 units</text><text x="300" y="183" textAnchor="middle">2 units deep</text></Svg>}
function Work({q,children}:{q:string;children:React.ReactNode}){return <div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>}
function Line({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <div className={strong?'math-line math-result':'math-line'}>{children}</div>}
export default function ThreeDimensionalFiguresLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson geometry-premium-lesson solids-premium-lesson">
<header className="wn-hero"><span>JSS1 MATHEMATICS · MENSURATION & GEOMETRY</span><h1>Three-Dimensional Figures</h1><p>Move from flat shapes to solids. Learn to read professional 3D diagrams, identify faces, surfaces, edges and vertices, compare common solids, and calculate the volume of cubes and cuboids completely.</p></header>
<section className="wn-objectives"><h2>Learning Objectives</h2><ul>{objectives.map(x=><li key={x}>{x}.</li>)}</ul></section>
<section className="wn-section"><h3>1. From 2D Shapes to 3D Solids</h3><p>A plane shape is flat and has two dimensions, such as length and width. A three-dimensional figure has length, width and height or depth. It occupies space and can be viewed from different directions.</p><div className="lesson-rule"><span><b>2D:</b> square, rectangle, triangle, circle.</span><span><b>3D:</b> cube, cuboid, pyramid, cone, cylinder, sphere.</span><span>A square can be a face of a cube. A rectangle can be a face of a cuboid. A circle forms the flat base of a cone and the two flat ends of a cylinder.</span></div></section>
<section className="wn-section"><h3>2. The Language of Solids</h3><div className="lesson-rule"><span><b>Face:</b> a flat surface of a solid.</span><span><b>Curved surface:</b> a surface that bends rather than lying flat.</span><span><b>Edge:</b> a boundary where faces/surfaces meet.</span><span><b>Vertex:</b> a corner point where edges meet; plural: vertices.</span><span><b>Base:</b> a face used as a reference or on which a solid may stand.</span></div><p>When curved solids are discussed, textbooks sometimes use “face” and “surface” differently. AVORA will state explicitly whether a part is a flat face or curved surface so the learner understands the geometry rather than memorising an ambiguous count.</p></section>
<section className="wn-section"><h3>3. Cube</h3><Cube/><div className="geometry-properties"><span>6 equal square faces</span><span>12 edges</span><span>8 vertices</span><span>All edges equal</span></div><p>A cube has the same length, width and height. Dice and some small boxes are familiar cube-like objects.</p></section>
<section className="wn-section"><h3>4. Cuboid</h3><Cuboid/><div className="geometry-properties"><span>6 rectangular faces</span><span>Opposite faces equal</span><span>12 edges</span><span>8 vertices</span></div><p>A cuboid does not require every edge to be equal. A cereal carton, brick or rectangular storage box is approximately cuboidal.</p></section>
<section className="wn-section"><h3>5. Cube and Cuboid Compared</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>Property</th><th>Cube</th><th>Cuboid</th></tr></thead><tbody><tr><td>Faces</td><td>6 equal squares</td><td>6 rectangles; opposite faces equal</td></tr><tr><td>Edges</td><td>12, all equal</td><td>12, grouped by length/width/height</td></tr><tr><td>Vertices</td><td>8</td><td>8</td></tr><tr><td>Dimensions</td><td>l = w = h</td><td>l, w and h may differ</td></tr></tbody></table></div></section>
<section className="wn-section"><h3>6. Pyramid</h3><Pyramid/><p>A pyramid has one polygonal base. Triangular faces rise from the edges of the base and meet at one point called the apex. The exact number of faces, edges and vertices depends on the shape of the base.</p><div className="lesson-rule"><span><b>Square-based pyramid:</b> 1 square base + 4 triangular faces = 5 faces.</span><span>It has 8 edges and 5 vertices.</span><span>Do not assume every pyramid has the same count; identify the base first.</span></div></section>
<section className="wn-section"><h3>7. Cone</h3><Cone/><div className="geometry-properties"><span>1 circular flat base</span><span>1 curved surface</span><span>1 vertex/apex</span><span>1 circular boundary edge</span></div><p>A party hat or traffic cone gives the general idea. The surface narrows continuously from the circular base to the vertex.</p></section>
<section className="wn-section"><h3>8. Cylinder</h3><Cylinder/><div className="geometry-properties"><span>2 equal circular flat faces</span><span>1 curved surface</span><span>2 circular boundary edges</span><span>0 vertices</span></div><p>The two circular ends are parallel and equal. A food can or straight pipe is approximately cylindrical.</p></section>
<section className="wn-section"><h3>9. Sphere</h3><Sphere/><div className="geometry-properties"><span>1 continuous curved surface</span><span>0 flat faces</span><span>0 edges</span><span>0 vertices</span></div><p>Every point on a perfect sphere is the same distance from its centre. A ball is a familiar approximation of a sphere. A sphere has no corner and no flat base.</p></section>
<section className="wn-section"><h3>10. Compare the Required Solids</h3><div className="geometry-table-wrap"><table className="geometry-table"><thead><tr><th>Solid</th><th>Flat face/base</th><th>Curved surface</th><th>Edges</th><th>Vertices</th></tr></thead><tbody><tr><td>Cube</td><td>6 square faces</td><td>No</td><td>12</td><td>8</td></tr><tr><td>Cuboid</td><td>6 rectangular faces</td><td>No</td><td>12</td><td>8</td></tr><tr><td>Square pyramid</td><td>5 faces total</td><td>No</td><td>8</td><td>5</td></tr><tr><td>Cone</td><td>1 circular base</td><td>Yes</td><td>1 circular boundary</td><td>1</td></tr><tr><td>Cylinder</td><td>2 circular faces</td><td>Yes</td><td>2 circular boundaries</td><td>0</td></tr><tr><td>Sphere</td><td>None</td><td>Yes</td><td>0</td><td>0</td></tr></tbody></table></div></section>
<section className="wn-section"><h3>11. Reading a 3D Drawing Correctly</h3><p>A 3D diagram is still drawn on a flat screen. Slanting lines suggest depth; they do not automatically mean those edges are physically slanted. Hidden edges may be omitted or shown with dashed lines. Use labels and dimensions, not appearance alone.</p><div className="lesson-rule"><span>A cuboid may look like a parallelogram in parts of a perspective drawing, but its rectangular faces still meet at right angles.</span><span>A circle drawn in perspective may look like an ellipse on the screen.</span></div></section>
<section className="wn-section"><h3>12. Nets — Opening a Solid</h3><p>A net is a flat arrangement of faces that can be folded to form a solid. A cube net contains six equal squares; a cuboid net contains six rectangular faces arranged so matching edges meet after folding.</p><div className="cube-net" aria-label="A valid cube net made of six equal squares"><span></span><span></span><span></span><span></span><span></span><span></span></div><p>Nets help us connect the plane shapes from the previous lesson with the faces of three-dimensional figures.</p></section>
<section className="wn-section"><h3>13. What Is Volume?</h3><p>Volume measures the amount of three-dimensional space occupied by a solid. We measure it using cubic units because a unit of volume is a cube measuring 1 unit × 1 unit × 1 unit.</p><div className="lesson-rule"><span>Length → cm or m</span><span>Area → cm² or m²</span><span>Volume → cm³ or m³</span></div></section>
<section className="wn-section"><h3>14. Deriving Cuboid Volume with Unit Cubes</h3><UnitCuboid/><p>Suppose one layer contains 4 × 3 = 12 unit cubes. If there are 2 such layers, the total number of unit cubes is 12 × 2 = 24.</p><div className="math-working"><Line>Volume = length × width × height</Line><Line>= 4 × 3 × 2</Line><Line strong>= 24 cubic units</Line></div><p>This is why the cuboid formula is V = l × w × h. It counts how many unit cubes fill the solid.</p></section>
<section className="wn-section"><h3>15. Volume of a Cuboid</h3><Cuboid/><Work q="A cuboid is 8 cm long, 5 cm wide and 3 cm high. Find its volume."><Line>V = l × w × h</Line><Line>= 8 cm × 5 cm × 3 cm</Line><Line>= 40 × 3</Line><Line strong>= 120 cm³</Line><Line>Check: 8 × 5 gives 40 unit cubes in one layer; 3 layers give 120 unit cubes.</Line></Work></section>
<section className="wn-section"><h3>16. Volume of a Cube</h3><Cube/><p>For a cube, length = width = height = side s. Therefore V = s × s × s = s³.</p><Work q="Find the volume of a cube whose edge is 4 cm."><Line>V = s³</Line><Line>= 4 × 4 × 4</Line><Line>= 16 × 4</Line><Line strong>= 64 cm³</Line><Line>Check: a 4-by-4 layer contains 16 unit cubes; 4 layers contain 64.</Line></Work></section>
<section className="wn-section"><h3>17. Do Not Confuse Area and Volume</h3><Work q="A box has length 6 cm, width 4 cm and height 3 cm. A learner calculates 6 × 4 = 24 cm². Has the learner found the volume?"><Line>6 × 4 uses only two dimensions.</Line><Line>24 cm² is the area of a 6 cm by 4 cm rectangular face.</Line><Line>For volume, include the height:</Line><Line>V = 6 × 4 × 3</Line><Line strong>= 72 cm³</Line></Work></section>
<section className="wn-section"><h3>18. Find a Missing Dimension</h3><Work q="A cuboid has volume 120 cm³, length 10 cm and width 4 cm. Find its height."><Line>V = l × w × h</Line><Line>120 = 10 × 4 × h</Line><Line>120 = 40h</Line><Line>h = 120 ÷ 40</Line><Line strong>h = 3 cm</Line><Line>Check: 10 × 4 × 3 = 120 cm³ ✓</Line></Work></section>
<section className="wn-section"><h3>19. Find the Edge of a Cube</h3><Work q="A cube has volume 125 cm³. Find its edge length."><Line>V = s³</Line><Line>s × s × s = 125</Line><Line>5 × 5 × 5 = 125</Line><Line strong>s = 5 cm</Line><Line>Check: 5³ = 125 cm³ ✓</Line></Work><p>At this level, recognise familiar perfect cubes from multiplication rather than using an unexplained advanced method.</p></section>
<section className="wn-section"><h3>20. Real-Life Example — Carton</h3><Work q="A rectangular carton measures 50 cm by 30 cm by 20 cm. Find the space inside it, treating it as a cuboid."><Line>V = l × w × h</Line><Line>= 50 × 30 × 20</Line><Line>= 1500 × 20</Line><Line strong>= 30,000 cm³</Line><Line>Check: all three measurements are in centimetres, so the volume unit is cm³.</Line></Work></section>
<section className="wn-section"><h3>21. Real-Life Example — Building Blocks</h3><Work q="A solid rectangular block measures 12 cm × 5 cm × 4 cm. What is its volume?"><Line>V = 12 × 5 × 4</Line><Line>= 60 × 4</Line><Line strong>= 240 cm³</Line><Line>If each unit cube were 1 cm³, exactly 240 such cubes would fill the same volume.</Line></Work></section>
<section className="wn-section"><h3>22. Real-Life Identification</h3><div className="lesson-rule"><span><b>Dice:</b> cube-like.</span><span><b>Brick/carton:</b> cuboid-like.</span><span><b>Egyptian-style monument model:</b> pyramid-like.</span><span><b>Traffic cone:</b> cone-like.</span><span><b>Tin can:</b> cylinder-like.</span><span><b>Football:</b> sphere-like.</span></div><p>Real objects are often only approximations. For example, a football has panels and a tin can has thickness, but their overall forms help us recognise the mathematical solids.</p></section>
<section className="wn-section"><h3>23. Common Mistakes</h3><div className="lesson-rule"><span><b>Face vs edge:</b> a face is a surface; an edge is a boundary.</span><span><b>Edge vs vertex:</b> an edge is a line/boundary; a vertex is a corner point.</span><span><b>Cube vs cuboid:</b> both have 6 faces, 12 edges and 8 vertices, but a cube has six equal square faces.</span><span><b>Cylinder:</b> it has no vertices.</span><span><b>Sphere:</b> it has no flat face, edge or vertex.</span><span><b>Volume:</b> use all three dimensions and cubic units.</span><span><b>Diagram:</b> never infer a measurement just because an edge looks longer on the screen.</span></div></section>
<section className="wn-section"><h3>24. AVORA Solid-Figure Method</h3><div className="lesson-rule"><span><b>1. Identify</b> the solid from its defining properties.</span><span><b>2. Inspect</b> flat faces, curved surfaces, edges and vertices.</span><span><b>3. Read</b> every dimension and its unit.</span><span><b>4. Decide</b> whether the task is identification, property counting or volume.</span><span><b>5. For volume, write</b> V = lwh for a cuboid or V = s³ for a cube.</span><span><b>6. Substitute</b> the dimensions.</span><span><b>7. Calculate</b> completely.</span><span><b>8. State</b> cubic units and sense-check the result.</span></div></section>
<section className="wn-section"><h3>25. Mastery Check</h3><p>You are ready for the exercise when you can identify all six required solids from their properties and diagrams, correctly discuss faces/surfaces, edges and vertices, explain why volume uses cubic units, derive cuboid volume from unit cubes, calculate cube and cuboid volumes, find a missing dimension in simple cases, and fully explain your answer rather than stopping at a formula.</p></section>
<div className="lesson-action"><button type="button" className="primary-btn" onClick={onExercise}>Go to Exercise →</button></div>
</article>}
