'use client';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import type {TutorPlan} from '@/lib/tutorCurriculum';
import {textbookChapters,siyavulaAttribution} from '@/lib/textbookScope';
import {deepExamples} from '@/lib/deepTeaching';
import {mathTeachingPack} from '@/lib/mathDeepTeaching';
import {groundingFor,mbsseAttribution} from '@/lib/academicGrounding';
import {teachingDepthProfile,termReason,exampleReasoningPrompt} from '@/lib/universalTeaching';
import {composeLearnerSourceMoments,factorizationFoundation} from '@/lib/lessonPresentation';
import VisualBoard from '@/components/VisualBoard';
import {visualFor} from '@/lib/visualTeaching';
import {cacheTutorLesson,getCachedTutorLesson,queueSyncAction,flushQueuedActions,countPendingSyncActions} from '@/lib/offline';
import {trackEvent} from '@/lib/telemetry';
import {learnerSessionTitle,learnerTopicTitle} from '@/lib/learnerPresentation';
import {officialNerdc2025Topic} from '@/lib/nerdc2025Official';

type Topic={name:string;questions:number};
type Q={id:string;prompt:string;type:string;options:string[];hint:string;explanation:string;difficulty:number;skill:string;topic:string};
type Feedback={correct:boolean;hint?:string;explanation?:string;feedback?:string;correctAnswer?:string;questionHelp?:string};
type BoardEvent={stepId:string;label:string;spoken:string;lines:string[];kind:'intro'|'term'|'idea'|'example'|'mistake'|'check';question?:string;expectation?:string;modelAnswer?:string;boardAction?:'WRITE'|'DRAW'|'HIGHLIGHT'|'CLEAR_SECTION'|'ASK'|'PAUSE';pauseAfterMs?:number};
type ChatTurn={role:'student'|'teacher';text:string};
type StructuredExample={title:string;problem:string;steps:string[];why:string;check:string;verification?:string;difficulty?:number;curriculumFocus?:string};
type Phase='probe'|'teach'|'guided'|'exercise'|'success';
const VOICE_TEACHING_ENABLED=process.env.NEXT_PUBLIC_VOICE_TEACHING_ENABLED==='true';
type GuidanceMeta={reguideStepId?:string|null;assistanceLevel?:'HINT'|'RETEACH'|'ANSWER';requiresFreshEvidence?:boolean};

async function parseJson(r:Response,label:string){const text=await r.text();if(!text.trim())throw new Error(`${label} returned no data.`);let d:any;try{d=JSON.parse(text)}catch{throw new Error(`${label} returned an invalid response.`)}if(r.status===401){const e:any=new Error('Session expired.');e.code='SESSION_EXPIRED';throw e}if(!r.ok)throw new Error(d.error||`${label} failed.`);return d}
function splitSentences(text:string){return text.split(/(?<=[.!?])\s+/).map(x=>x.trim()).filter(Boolean)}
function narrationSegments(text:string){
 const out:string[]=[];
 for(const sentence of splitSentences(verbalize(text))){
  if(sentence.length<=210){out.push(sentence);continue}
  const parts=sentence.split(/(?<=[,;:])\s+/).map(x=>x.trim()).filter(Boolean);let bucket='';
  for(const part of parts){const next=bucket?`${bucket} ${part}`:part;if(next.length>210&&bucket){out.push(bucket);bucket=part}else bucket=next}
  if(bucket)out.push(bucket)
 }
 return out.length?out:[verbalize(text)]
}
type VoiceChoice={uri:string;name:string;lang:string;local:boolean};
function voiceScore(v:SpeechSynthesisVoice){const lang=v.lang.toLowerCase();let score=0;if(lang==='en-ng')score+=120;else if(lang.startsWith('en-gb'))score+=90;else if(lang.startsWith('en-us'))score+=75;else if(lang.startsWith('en-'))score+=60;if(/natural|neural|premium|enhanced|online|google|microsoft/i.test(v.name))score+=35;if(v.localService)score+=5;return score}
function preferredVoice(voices:SpeechSynthesisVoice[]){return [...voices].filter(v=>/^en(-|_)/i.test(v.lang)).sort((a,b)=>voiceScore(b)-voiceScore(a)||a.name.localeCompare(b.name))[0]||voices[0]}
function authoredExample(text:string,index:number):StructuredExample{const chunks=String(text||'').split(/(?:\s*→\s*|;\s+|(?<=[.!?])\s+)/).map(x=>x.trim()).filter(Boolean);const problem=chunks[0]||String(text||'');const steps=(chunks.length>1?chunks.slice(1):chunks).slice(0,8);return {title:`AUTHORED EXAMPLE ${index+1}`,problem,steps:steps.length?steps:[problem],why:'AVORA shows the evidence, calculation or transformation rather than jumping from the question to an answer.',check:'Explain the decisive rule, evidence or transformation in this example, then apply it to a fresh case.'}}
function verbalize(text:string){return text.replace(/([01]+)₂/g,(_,digits:string)=>`${digits.split('').join('-')} base two`).replace(/([0-9]+)₁₀/g,(_,digits:string)=>`${digits} base ten`).replace(/cm²/g,'square centimetres').replace(/cm³/g,'cubic centimetres').replace(/kg/g,'kilograms').replace(/cm/g,'centimetres').replace(/÷/g,' divided by ').replace(/×/g,' times ').replace(/=/g,' equals ').replace(/→/g,' then ').replace(/π/g,'pi').replace(/√/g,'square root of ')}

function words(text:string){return new Set(String(text||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\s+/).filter(x=>x.length>3&&!['this','that','with','from','what','your','then','into','when','where','which','using','question','answer'].includes(x)))}
function questionFit(q:Q|undefined,unit:any){if(!q||!unit)return 0;const target=words([unit.title,unit.explain,(unit.terms||[]).map((x:any)=>x[0]).join(' '),(unit.outcomes||[]).join(' ')].join(' '));const source=words([q.skill,q.prompt,q.topic].join(' '));let score=0;for(const w of source)if(target.has(w))score++;return score}
function questionInstruction(q:Q){if(q.type==='MULTIPLE_CHOICE')return 'Choose the option you believe is correct. Work it out first if needed, then tap one answer. AVORA will tell you clearly whether you got it and explain why.';return 'Work through the question, then type your answer or reasoning. AVORA will check it and explain what to improve.'}

function buildEvents(unit:any,topic:string,subject:string,classLevel:string):BoardEvent[]{
 if(!unit)return [];
 const events:Array<Omit<BoardEvent,'stepId'>&{stepId?:string}>=[];
 const depth=teachingDepthProfile(unit,subject);
 const mathPack=subject==='Mathematics'?mathTeachingPack(classLevel,topic):undefined;
 // Source-backed lessons are authoritative. Once a unit has structured source steps, do not
 // surround them with generic tutor templates, duplicate examples, synthetic misconceptions or
 // stock prompts. Those additions made AVORA drift away from the authored curriculum and could
 // make a complete lesson sound repetitive or unrelated. Teach the supplied content, in order,
 // and treat only authored checks[] as learner questions.
 if(Array.isArray(unit.structuredSteps)&&unit.structuredSteps.length){
  const sourceEvents:BoardEvent[]=composeLearnerSourceMoments(unit.structuredSteps).map(moment=>({
   stepId:moment.id,kind:moment.kind,label:moment.label,spoken:moment.spoken,
   question:moment.requiresLearnerResponse?moment.lines.slice(1).join(' '):undefined,
   modelAnswer:undefined,
   expectation:moment.requiresLearnerResponse?'Attempt the authored curriculum check. Show the reasoning or working the question asks for.':undefined,
   lines:moment.lines,boardAction:moment.boardAction,pauseAfterMs:moment.pauseAfterMs
  }));
  return sourceEvents;
 }
 events.push({kind:'intro',label:'WHY THIS MATTERS',spoken:unit.why||`We are going to understand ${unit.title}, not just memorize a rule.`,lines:[unit.title,unit.why||`This is a required part of ${topic}.`]});
 events.push({kind:'idea',label:'WHAT YOU WILL UNDERSTAND',spoken:`By the end of this section, you should be able to explain the idea, apply it and justify your reasoning.`,lines:['By the end, you should be able to:',...depth.outcomes.map((x:string)=>`• ${x}`)]});
 events.push({kind:'idea',label:'BUILD THE FOUNDATION FIRST',spoken:`Before examples, we connect the knowledge this lesson depends on. ${depth.prerequisites.join('. ')}. If one of these is unclear, interrupt me and we will rebuild it.`,lines:['Foundation first:',...depth.prerequisites.map((x:string)=>`• ${x}`)]});
 if(mathPack?.terms.length){
  events.push({kind:'idea',label:'WORDS MUST MEAN SOMETHING BEFORE WE USE THEM',spoken:`Before working, we define the mathematical language for ${topic}.`,lines:['Terms first — no unexplained vocabulary']});
  for(const def of mathPack.terms){
   events.push({kind:'term',label:`TERM — ${def.term.toUpperCase()}`,spoken:`${def.term}. ${def.simple}. More formally: ${def.formal} Example: ${def.example} Contrast: ${def.contrast} In this lesson: ${def.use}`,lines:[def.term,`Simple meaning: ${def.simple}`,`Formal meaning: ${def.formal}`,`Example: ${def.example}`,`Not this: ${def.contrast}`,`Why we need it: ${def.use}`]});
  }
 }
 for(const [term,meaning] of unit.terms||[]){
   events.push({kind:'term',label:'KEY WORD — MEANING',spoken:termReason(term,meaning,subject),lines:[term,meaning]});
   events.push({kind:'idea',label:'WHY THAT WORD MATTERS',spoken:termReason(term,meaning,subject),lines:[`When you see “${term}”…`,subject==='English Language'?'Find the exact language role or evidence it describes.':'Connect the word to the quantity, symbol, relationship or operation it describes.','Do not continue until the word makes sense.']});
 }
 if(Array.isArray(unit.teachingTypes)&&unit.teachingTypes.length){
  events.push({kind:'idea',label:'THE TYPES YOU MUST BE ABLE TO HANDLE',spoken:`This topic has different forms. Learning one easy example is not complete coverage. We will recognise the important types and what changes between them.`,lines:['Required forms / types:',...unit.teachingTypes.map((x:string)=>`• ${x}`)]});
 }
 // Internal authoring/no-jump notes guide the runtime, but are never read aloud or shown as learner content.
 // High-risk concepts can inject a carefully authored conceptual bridge before examples.
 for(const moment of factorizationFoundation(topic,classLevel)){
  events.push({stepId:moment.id,kind:moment.kind,label:moment.label,spoken:moment.spoken,question:moment.requiresLearnerResponse?moment.lines.slice(1).join(' '):undefined,expectation:moment.requiresLearnerResponse?'Explain the relationship in your own words before continuing.':undefined,lines:moment.lines,boardAction:moment.boardAction,pauseAfterMs:moment.pauseAfterMs});
 }
 // Source content is compiled into learner-facing teaching moments. Raw source rows, provenance and author instructions never reach the board or voice.
 for(const moment of composeLearnerSourceMoments(unit.structuredSteps)){
  events.push({stepId:moment.id,kind:moment.kind,label:moment.label,spoken:moment.spoken,question:moment.requiresLearnerResponse?moment.lines.slice(1).join(' '):undefined,modelAnswer:undefined,expectation:moment.requiresLearnerResponse?'Attempt it first. Show the reasoning or working that the question asks for.':undefined,lines:moment.lines,boardAction:moment.boardAction,pauseAfterMs:moment.pauseAfterMs});
 }
 const parts=splitSentences(unit.explain||'');
 parts.forEach((p:string,i:number)=>events.push({kind:'idea',label:i===0?'CORE IDEA — SLOWLY':'BUILD THE IDEA — ONE REASON AT A TIME',spoken:`${p} Now ask yourself what makes this statement true and how it connects to the definitions we just established.`,lines:[p,'What makes this true?','Which definition or rule supports it?']}));
 if(unit.why)events.push({kind:'idea',label:'REASONING BEHIND THE RULE',spoken:unit.why,lines:['Why this works',unit.why]});
 const bankRich=deepExamples(unit.title);
 const authored=Array.isArray(unit.workedExamples)?unit.workedExamples.slice(0,5).map((x:string,i:number)=>authoredExample(x,i)):[];
 const rich:StructuredExample[]=mathPack?.workedExamples?.length?mathPack.workedExamples:(bankRich.length?bankRich:authored);
 if(rich.length){
  rich.forEach((ex,ei)=>{
   events.push({kind:'example',label:`EXAMPLE ${ei+1} — UNDERSTAND THE SITUATION`,spoken:`Let us work this example slowly. ${ex.problem} Before doing anything, identify what is given, what is required and which concept this belongs to.`,lines:[ex.title,ex.problem,'GIVEN → REQUIRED → METHOD','Now watch the working change one line at a time.']});
   ex.steps.forEach((step,si)=>events.push({kind:'example',label:`EXAMPLE ${ei+1} · REASONING STEP ${si+1}`,spoken:`${step} ${exampleReasoningPrompt(step,si,subject)}`,lines:[`Step ${si+1}`,step,subject==='English Language'?'What language evidence makes this step valid?':'What rule allows this step? Why this operation?']}));
   events.push({kind:'idea',label:`EXAMPLE ${ei+1} — WHY THE METHOD WORKS`,spoken:ex.why,lines:['Why it works',ex.why]});
   if(ex.verification)events.push({kind:'idea',label:`EXAMPLE ${ei+1} — VERIFY, DO NOT JUST TRUST THE ANSWER`,spoken:ex.verification,lines:['Independent verification',ex.verification]});
   events.push({kind:'check',label:`EXAMPLE ${ei+1} — EXPLAIN IT BACK`,spoken:`Pause here and answer this in your own words or working: ${ex.check}`,question:ex.check,expectation:'Explain the key idea, rule or step. AVORA is checking understanding, not memorised wording.',lines:['Pause here','Explain the reasoning, not only the final answer.','The question appears once below so you can focus on it clearly.']});
  });
 }
 if(mathPack?.standardQuestions?.length){
  const standard=mathPack.standardQuestions.slice(0,8);
  events.push({kind:'idea',label:'CURRICULUM-STANDARD PRACTICE SET',spoken:`You have also got ${standard.length} reviewed questions aligned to this topic. These move from concept and misconception checks into application, reasoning and transfer. We will not mistake seeing an answer for mastery; you must solve them yourself after the demonstrations.`,lines:['Reviewed question set',...standard.map((q,i)=>`${i+1}. ${q.prompt}`)]});
 }
 else{
  const exampleText=String(unit.example||'');
  events.push({kind:'example',label:'WORKED EXAMPLE 1 — FIRST READ',spoken:`Here is our first worked example. ${exampleText} Do not copy the answer. First identify what is happening and which idea controls it.`,lines:['Worked example 1',exampleText,'What is happening here? Which idea controls it?']});
  const steps=exampleText.split('→').map((x:string)=>x.trim()).filter(Boolean);
  const breakdown=steps.length>1?steps:depth.exampleBreakdown.map((x:string)=>x.replace(/^\d+\.\s*/,''));
  breakdown.forEach((step:string,i:number)=>events.push({kind:'example',label:`WORKED EXAMPLE 1 · REASONING ${i+1}`,spoken:exampleReasoningPrompt(step,i,subject),lines:[`${subject==='English Language'?'Reasoning point':'Step'} ${i+1}`,step,subject==='English Language'?'Which word, structure or evidence controls this?':'What changed? Which rule allows it?']}));
  events.push({kind:'idea',label:'WORKED EXAMPLE 1 — EXPLAIN THE REASON',spoken:`A finished answer is not enough. Rebuild the example by naming the concept, explaining why it applies, and checking that the result answers the original task.`,lines:['Name the concept','Explain why it applies','Follow each step','Check the final result']});
  events.push({kind:'example',label:'EXAMPLE 2 — CONTRAST THE THINKING',spoken:`Now compare the correct reasoning with a tempting wrong approach. The purpose is to understand what must stay true when the wording, numbers or sentence changes.`,lines:['A second way to learn:',subject==='English Language'?'Compare the correct language evidence with a tempting but unsupported choice.':'Compare the correct method with a tempting operation or formula that does not fit.','Ask: exactly which rule would the wrong approach break?']});
  events.push({kind:'idea',label:'EXAMPLE 2 — WHAT MUST STAY TRUE',spoken:`Even when the surface details change, the underlying concept stays the same. ${depth.masteryChecklist.join('. ')}.`,lines:['What must stay true:',...depth.masteryChecklist.slice(0,4).map((x:string)=>`• ${x}`)]});
  events.push({kind:'idea',label:'FRESH APPLICATION — PREPARE',spoken:`Next you will meet a fresh situation. Before answering, identify the concept, say what the question expects, choose a reasoned method, and check your result.`,lines:['Fresh application next','1. Identify the concept','2. Explain what is expected','3. Use the rule with reasons','4. Check the result']});
 }
 depth.misconceptions.forEach((m:string,i:number)=>events.push({kind:'mistake',label:`COMMON MISTAKE ${i+1} — WHY IT FAILS`,spoken:`A learner may make this mistake: ${m}. We do not just say “wrong”; we ask which definition, relationship, grammar rule, evidence or mathematical property it breaks.`,lines:['Common mistake',m,'Why it fails → which idea was broken?']}));
 events.push({kind:'idea',label:'BEFORE AVORA TESTS YOU',spoken:`Use this checklist before you answer: ${depth.masteryChecklist.join('. ')}.`,lines:['Understanding checklist',...depth.masteryChecklist.map((x:string)=>`✓ ${x}`)]});
 events.push({kind:'check',label:'SECTION UNDERSTANDING CHECK',spoken:`Now answer one clear question about exactly what we have just taught: ${unit.check}`,question:unit.check,expectation:subject==='English Language'?'Answer directly, identify the word/structure/evidence that controls the answer, and explain why it fits.':'Answer directly, state the rule or relationship first, show the working, and check the result.',lines:['Now you do something','Use only the concept just taught.','Explain the reason, not only the final answer.']});
 return events.map((e,i)=>({...e,stepId:e.stepId||`runtime-${String(i+1).padStart(3,'0')}`})) as BoardEvent[];
}

export default function TutorClient(){
 const router=useRouter(),params=useSearchParams();
 async function readJson(r:Response,label:string){try{return await parseJson(r,label)}catch(e:any){if(e?.code==='SESSION_EXPIRED'){router.replace('/login');router.refresh()}throw e}}
 const requestedTopic=params.get('topic')||'';
 const requestedSubject=params.get('subject')||'';
 const [subject,setSubject]=useState(requestedSubject==='English Language'?'English Language':'Mathematics');
 const [topic,setTopic]=useState(requestedTopic);
 const [topics,setTopics]=useState<Topic[]>([]);
 const [plan,setPlan]=useState<TutorPlan|undefined>(undefined);
 const [exam,setExam]=useState('BECE');const [classLevel,setClassLevel]=useState('JSS3');
 const [questions,setQuestions]=useState<Q[]>([]);const [exerciseQuestions,setExerciseQuestions]=useState<Q[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [phase,setPhase]=useState<Phase>('probe');const [unitIndex,setUnitIndex]=useState(0);const [covered,setCovered]=useState<number[]>([]);
 const [answer,setAnswer]=useState('');const [feedback,setFeedback]=useState<Feedback|null>(null);const [checking,setChecking]=useState(false);
 const [eventIndex,setEventIndex]=useState(0);const [paused,setPaused]=useState(false);const [voiceOn,setVoiceOn]=useState(VOICE_TEACHING_ENABLED);const [rate,setRate]=useState(.9);const [speaking,setSpeaking]=useState(false);const [extraBoard,setExtraBoard]=useState<string[]>([]);
 const [voiceChoices,setVoiceChoices]=useState<VoiceChoice[]>([]);const [voiceURI,setVoiceURI]=useState('');const [speechAvailable,setSpeechAvailable]=useState(true);const [narrationSegment,setNarrationSegment]=useState(0);const [narrationChar,setNarrationChar]=useState(0);const [syncing,setSyncing]=useState(false);
 const timer=useRef<number|null>(null);const utterance=useRef<SpeechSynthesisUtterance|null>(null);const started=useRef(false);const pausedRef=useRef(false);const playToken=useRef(0);const skipPlaybackEffect=useRef(false);
 const [ask,setAsk]=useState('');const [asking,setAsking]=useState(false);const [chat,setChat]=useState<ChatTurn[]>([]);const [checkpoint,setCheckpoint]=useState('');const [checkpointReply,setCheckpointReply]=useState('');const [checkingPoint,setCheckingPoint]=useState(false);
 const [questionHelp,setQuestionHelp]=useState('');const [revealed,setRevealed]=useState<Feedback|null>(null);const [helping,setHelping]=useState(false);
 const [reguideStepId,setReguideStepId]=useState<string|null>(null);const [assistanceLevel,setAssistanceLevel]=useState<'HINT'|'RETEACH'|'ANSWER'|null>(null);const [freshEvidenceRequired,setFreshEvidenceRequired]=useState(false);
 const [online,setOnline]=useState(true);const [sessionReady,setSessionReady]=useState(false);const [restoredSession,setRestoredSession]=useState(false);const [lastSavedAt,setLastSavedAt]=useState<number|null>(null);const [screenAwake,setScreenAwake]=useState(false);const [autoPausedByVisibility,setAutoPausedByVisibility]=useState(false);const [cachedLesson,setCachedLesson]=useState(false);const [pendingSync,setPendingSync]=useState(0);
 const [showLessonMap,setShowLessonMap]=useState(false);
 const [exerciseIndex,setExerciseIndex]=useState(0);const [exerciseAnswer,setExerciseAnswer]=useState('');const [exerciseFeedback,setExerciseFeedback]=useState<Feedback|null>(null);const [exerciseChecking,setExerciseChecking]=useState(false);const [exerciseCorrect,setExerciseCorrect]=useState(0);const [exerciseFinished,setExerciseFinished]=useState(false);
 const wakeLockRef=useRef<any>(null);const activeSessionKeyRef=useRef('');


 const sourceChapters=useMemo(()=>subject==='Mathematics'?textbookChapters(classLevel,topic):[],[classLevel,subject,topic]);
 const officialTopic=useMemo(()=>officialNerdc2025Topic(classLevel,subject,topic),[classLevel,subject,topic]);
 const unit=plan?.units[unitIndex];
 const grounding=useMemo(()=>groundingFor(subject,unit?.title||topic,classLevel),[subject,unit?.title,topic,classLevel]);
 const events=useMemo(()=>buildEvents(unit,topic,subject,classLevel),[unit,topic,subject,classLevel]);const event=events[Math.min(eventIndex,Math.max(0,events.length-1))];
 const lessonSteps=useMemo(()=>events.map(e=>({id:e.stepId,label:e.label,kind:e.kind,summary:String(e.question||e.lines[0]||e.spoken).slice(0,500)})),[events]);
 const spokenSegments=useMemo(()=>event?narrationSegments(event.spoken):[],[event]);
 const activeSpokenSegment=spokenSegments[Math.min(narrationSegment,Math.max(0,spokenSegments.length-1))]||'';
 const narrationProgress=spokenSegments.length?Math.min(100,Math.round(((narrationSegment+(activeSpokenSegment?Math.min(1,narrationChar/Math.max(1,activeSpokenSegment.length)):0))/spokenSegments.length)*100)):0;
 const visibleBoardLineCount=!VOICE_TEACHING_ENABLED?(event?.lines?.length||0):syncing&&voiceOn&&event?.lines?.length>1?Math.max(1,Math.ceil(((narrationSegment+1)/Math.max(1,spokenSegments.length))*event.lines.length)):(event?.lines?.length||0);
 const visualSpec=useMemo(()=>subject==='Mathematics'&&event?visualFor(topic,event.label,event.lines):{kind:'none' as const,title:'',caption:''},[subject,topic,event]);
 const probeQ=questions[0];
 const exerciseQ=exerciseQuestions[exerciseIndex];
 const guidedQ=useMemo(()=>{if(!unit||!questions.length)return undefined;const ranked=[...questions].map(q=>({q,score:questionFit(q,unit)})).sort((a,b)=>b.score-a.score);const matched=ranked.filter(x=>x.score>=1);if(matched.length)return matched[unitIndex%matched.length].q;return questions[unitIndex%questions.length]},[questions,unit,unitIndex]);

 useEffect(()=>{setSubject(requestedSubject==='English Language'?'English Language':'Mathematics');},[requestedSubject]);
 // The lesson loader intentionally re-runs only when the selected topic/subject changes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void load(topic,subject)},[subject,topic]);
 // stopAll is the current mounted playback cleanup; do not restart this effect on each render.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>()=>stopAll(),[]);
 useEffect(()=>{
  if(!VOICE_TEACHING_ENABLED){setSpeechAvailable(false);setVoiceOn(false);return}
  if(typeof window==='undefined'||!('speechSynthesis'in window)){setSpeechAvailable(false);return}
  const synth=window.speechSynthesis;setSpeechAvailable(true);
  const refresh=()=>{const list=synth.getVoices();const english=list.filter(v=>/^en(-|_)/i.test(v.lang));const shown=(english.length?english:list).sort((a,b)=>voiceScore(b)-voiceScore(a)||a.name.localeCompare(b.name));setVoiceChoices(shown.map(v=>({uri:v.voiceURI,name:v.name,lang:v.lang,local:v.localService})));setVoiceURI(current=>{if(current&&shown.some(v=>v.voiceURI===current))return current;const saved=window.localStorage.getItem('avora:tutor-voice-uri');if(saved&&shown.some(v=>v.voiceURI===saved))return saved;return preferredVoice(shown)?.voiceURI||''})};
  refresh();synth.addEventListener?.('voiceschanged',refresh);return()=>synth.removeEventListener?.('voiceschanged',refresh)
 },[]);
 // Playback is driven by these state transitions; event/playCurrent are derived from the same render.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!VOICE_TEACHING_ENABLED||phase!=='teach'||!event||paused)return;if(skipPlaybackEffect.current){skipPlaybackEffect.current=false;return}playCurrent();return clearTimer},[phase,eventIndex,paused,voiceOn,rate,voiceURI,unitIndex]);

 useEffect(()=>{if(typeof window==='undefined')return;let previous=window.navigator.onLine;const update=()=>{const isOnline=window.navigator.onLine;setOnline(isOnline);if(isOnline){if(!previous)trackEvent('TUTOR_RECONNECTED',{subject,topic,offline:false});void flushQueuedActions().then(r=>setPendingSync(r.remaining)).catch(()=>{})}else{if(previous)trackEvent('TUTOR_OFFLINE_ENTERED',{subject,topic,offline:true});void countPendingSyncActions().then(setPendingSync).catch(()=>{})}previous=isOnline};update();window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update)}},[subject,topic]);
 useEffect(()=>{if(typeof document==='undefined')return;const onVisibility=()=>{if(document.visibilityState==='hidden'&&phase==='teach'&&!paused){pause();setAutoPausedByVisibility(true)}};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility)},[phase,paused]);
 useEffect(()=>{if(typeof navigator==='undefined')return;const nav:any=navigator;let cancelled=false;async function syncWakeLock(){try{if(phase==='teach'&&!paused&&document.visibilityState==='visible'&&nav.wakeLock?.request){if(!wakeLockRef.current){const lock=await nav.wakeLock.request('screen');if(cancelled){await lock.release?.();return}wakeLockRef.current=lock;setScreenAwake(true);lock.addEventListener?.('release',()=>{wakeLockRef.current=null;setScreenAwake(false)})}}else if(wakeLockRef.current){await wakeLockRef.current.release?.();wakeLockRef.current=null;setScreenAwake(false)}}catch{setScreenAwake(false)}}void syncWakeLock();return()=>{cancelled=true;if(wakeLockRef.current){void wakeLockRef.current.release?.();wakeLockRef.current=null;setScreenAwake(false)}}},[phase,paused]);
 useEffect(()=>{if(typeof window==='undefined'||!topic||!sessionReady||activeSessionKeyRef.current!==`${subject}:${topic}`)return;const snapshot={version:1,subject,topic,phase:phase==='success'?'probe':phase,unitIndex,eventIndex,covered,answer,checkpoint,chat:chat.slice(-8),rate,voiceOn,freshEvidenceRequired,reguideStepId,assistanceLevel,savedAt:Date.now()};try{window.localStorage.setItem(`avora:tutor-session:${subject}:${topic}`,JSON.stringify(snapshot));setLastSavedAt(snapshot.savedAt)}catch{}},[subject,topic,phase,unitIndex,eventIndex,covered,answer,checkpoint,chat,rate,voiceOn,freshEvidenceRequired,reguideStepId,assistanceLevel,sessionReady]);

 function clearTimer(){if(timer.current){window.clearTimeout(timer.current);timer.current=null}}
 function stopSpeech(){if(typeof window!=='undefined'&&'speechSynthesis'in window)window.speechSynthesis.cancel();setSpeaking(false);setSyncing(false);setNarrationSegment(0);setNarrationChar(0);utterance.current=null}
 function stopAll(){playToken.current++;clearTimer();stopSpeech()}
 async function load(chosen:string,subj:string){
  stopAll();activeSessionKeyRef.current='';pausedRef.current=false;setSessionReady(false);setRestoredSession(false);setAutoPausedByVisibility(false);setLoading(true);setError('');setFeedback(null);setAnswer('');setEventIndex(0);setPaused(false);setExtraBoard([]);setChat([]);setCheckpoint('');setCheckpointReply('');setQuestionHelp('');setRevealed(null);setReguideStepId(null);setAssistanceLevel(null);setFreshEvidenceRequired(false);setExerciseQuestions([]);setExerciseIndex(0);setExerciseAnswer('');setExerciseFeedback(null);setExerciseCorrect(0);setExerciseFinished(false);setPhase('probe');setUnitIndex(0);setPlan(undefined);
  try{const u=new URLSearchParams();if(chosen)u.set('topic',chosen);u.set('subject',subj);let d:any;let fromCache=false;try{d=await readJson(await fetch('/api/tutor?'+u.toString(),{cache:'no-store'}),'Tutor');setCachedLesson(false);void cacheTutorLesson(subj,chosen,d).catch(()=>{})}catch(networkError){const cached=await getCachedTutorLesson(subj,chosen).catch(()=>null);if(!cached)throw networkError;d=cached.payload;fromCache=true;setCachedLesson(true);trackEvent('TUTOR_CACHED_LESSON_USED',{subject:subj,topic:chosen,cached:true})}setExam(d.exam);setClassLevel(d.classLevel);setTopics(d.topics||[]);const loadedQuestions=d.questions||[];setQuestions(loadedQuestions);setExerciseQuestions(d.exerciseQuestions||[]);setPlan(d.plan||undefined);let serverUnit=0;let serverCovered:number[]=[];if(chosen&&!fromCache&&typeof navigator!=='undefined'&&navigator.onLine){try{const pu=new URLSearchParams({topic:chosen,subject:subj,exam:d.exam});const pd=await readJson(await fetch('/api/tutor/progress?'+pu.toString(),{cache:'no-store'}),'Tutor progress');if(pd.progress){serverCovered=Array.isArray(pd.progress.coveredUnits)?pd.progress.coveredUnits:[];serverUnit=Number.isInteger(pd.progress.currentUnit)&&pd.progress.currentUnit>=0?pd.progress.currentUnit:0;setCovered(serverCovered);setUnitIndex(serverUnit)}}catch{}}
   if(chosen&&typeof window!=='undefined'){try{const raw=window.localStorage.getItem(`avora:tutor-session:${subj}:${chosen}`);if(raw){const snap=JSON.parse(raw);const fresh=Number(snap?.savedAt)>Date.now()-7*24*60*60*1000;const units=Array.isArray(d.plan?.units)?d.plan.units.length:0;if(fresh&&snap?.subject===subj&&snap?.topic===chosen&&['probe','teach','guided','exercise'].includes(snap?.phase)){const savedUnit=Math.max(0,Math.min(units?units-1:0,Number(snap.unitIndex)||0));setUnitIndex(savedUnit);setEventIndex(Math.max(0,Number(snap.eventIndex)||0));setCovered(Array.isArray(snap.covered)?snap.covered.filter((x:any)=>Number.isInteger(x)&&x>=0&&(!units||x<units)):serverCovered);setAnswer(String(snap.answer||''));setCheckpoint(String(snap.checkpoint||''));setChat(Array.isArray(snap.chat)?snap.chat.slice(-8):[]);setRate(Number(snap.rate)>=.7&&Number(snap.rate)<=1.2?Number(snap.rate):.9);setVoiceOn(VOICE_TEACHING_ENABLED&&snap.voiceOn!==false);setFreshEvidenceRequired(Boolean(snap.freshEvidenceRequired));setReguideStepId(typeof snap.reguideStepId==='string'?snap.reguideStepId:null);setAssistanceLevel(['HINT','RETEACH','ANSWER'].includes(snap.assistanceLevel)?snap.assistanceLevel:null);setPhase(snap.phase);setRestoredSession(true);trackEvent('TUTOR_LESSON_RESTORED',{subject:subj,topic:chosen,restored:true});setLastSavedAt(Number(snap.savedAt)||null);if(snap.phase==='teach'){pausedRef.current=true;setPaused(true)}}}}catch{}}
   if(chosen&&!loadedQuestions.length&&d.plan?.units?.[0]?.check){
    setQuestions([{id:`probe:${subj}:${chosen}`,prompt:d.plan.units[0].check,type:'SHORT_ANSWER',options:[],hint:'Explain the idea and show the key step rather than guessing.',explanation:'AVORA will use this answer to choose the right starting point for your lesson.',difficulty:1,skill:d.plan.units[0].title,topic:chosen}])
   }
  }catch(e:any){setError(e.message||'Could not prepare Tutor.')}finally{activeSessionKeyRef.current=chosen?`${subj}:${chosen}`:'';if(chosen)trackEvent('TUTOR_LESSON_OPENED',{subject:subj,topic:chosen,exam});setSessionReady(true);setLoading(false)}
 }
 function selectTopic(t:string){setTopic(t);router.replace('/tutor?topic='+encodeURIComponent(t)+'&subject='+encodeURIComponent(subject));}
 function chooseSubject(s:string){setSubject(s);setTopic('');router.replace('/tutor?subject='+encodeURIComponent(s));}

 function scheduleAdvance(ms:number){clearTimer();if(event?.kind==='check')return;const token=playToken.current;timer.current=window.setTimeout(()=>{if(pausedRef.current||token!==playToken.current)return;if(eventIndex<events.length-1)setEventIndex(i=>i+1);else setPhase('guided')},ms)}
 function playCurrent(){
  clearTimer();stopSpeech();if(!event||pausedRef.current)return;const token=++playToken.current;
  const base=event.kind==='example'?9000:event.kind==='idea'?7000:6000;const wait=Math.max(base,Math.min(26000,4200+event.spoken.length*48));
  const segments=narrationSegments(event.spoken);setNarrationSegment(0);setNarrationChar(0);
  if(!VOICE_TEACHING_ENABLED||!voiceOn||typeof window==='undefined'||!('speechSynthesis'in window)){setSyncing(false);return}
  const synth=window.speechSynthesis;const selected=synth.getVoices().find(v=>v.voiceURI===voiceURI)||preferredVoice(synth.getVoices());setSyncing(true);
  const speakPart=(index:number)=>{if(pausedRef.current||token!==playToken.current)return;if(index>=segments.length){setSpeaking(false);setSyncing(false);scheduleAdvance(Math.max(900,event.pauseAfterMs??1400));return}setNarrationSegment(index);setNarrationChar(0);const u=new SpeechSynthesisUtterance(segments[index]);utterance.current=u;u.lang=selected?.lang||'en-NG';if(selected)u.voice=selected;u.rate=rate;u.pitch=1;u.volume=1;u.onstart=()=>{if(token===playToken.current)setSpeaking(true)};u.onboundary=(e)=>{if(token===playToken.current&&e.name==='word')setNarrationChar(e.charIndex||0)};u.onend=()=>{if(pausedRef.current||token!==playToken.current)return;window.setTimeout(()=>speakPart(index+1),90)};u.onerror=()=>{if(pausedRef.current||token!==playToken.current)return;window.setTimeout(()=>speakPart(index+1),80)};synth.speak(u)};
  speakPart(0)
 }
 function pause(){if(pausedRef.current)return;pausedRef.current=true;clearTimer();if(typeof window!=='undefined'&&'speechSynthesis'in window&&window.speechSynthesis.speaking){window.speechSynthesis.pause()}setPaused(true)}
 function resume(){if(!pausedRef.current)return;pausedRef.current=false;setAutoPausedByVisibility(false);if(typeof window!=='undefined'&&'speechSynthesis'in window&&window.speechSynthesis.paused&&utterance.current){skipPlaybackEffect.current=true;window.speechSynthesis.resume()}setPaused(false)}
 function replay(){stopAll();pausedRef.current=false;setPaused(false);window.setTimeout(playCurrent,80)}
 function nextEvent(){stopAll();pausedRef.current=false;setPaused(false);setCheckpoint('');setCheckpointReply('');setQuestionHelp('');setRevealed(null);if(eventIndex<events.length-1)setEventIndex(i=>i+1);else if(guidedQ)setPhase('guided');else continueAfterGuided()}
 function prevEvent(){stopAll();pausedRef.current=false;setPaused(false);setCheckpoint('');setCheckpointReply('');setEventIndex(i=>Math.max(0,i-1))}
 function toggleVoice(){stopSpeech();setVoiceOn(v=>!v)}
 function chooseVoice(uri:string){setVoiceURI(uri);if(typeof window!=='undefined')window.localStorage.setItem('avora:tutor-voice-uri',uri)}
 function applyGuidanceMeta(d:GuidanceMeta){setReguideStepId(d.reguideStepId||null);setAssistanceLevel(d.assistanceLevel||null);setFreshEvidenceRequired(Boolean(d.requiresFreshEvidence))}
 function jumpToGuidanceStep(){if(!reguideStepId)return;trackEvent('TUTOR_RETEACH_TRIGGERED',{subject,topic,exam,reason:assistanceLevel||'RETEACH'});const idx=events.findIndex(e=>e.stepId===reguideStepId);if(idx<0)return;stopAll();pausedRef.current=false;setEventIndex(idx);setPhase('teach');setPaused(false);setCheckpoint('');setCheckpointReply('');setQuestionHelp('')}

 async function check(kind:'probe'|'guided'){
  const q=kind==='probe'?probeQ:guidedQ;if(!q||!answer.trim()||checking)return;if(!online){setError('You are offline. Your answer is saved on this device; reconnect to let AVORA mark it.');return;}setChecking(true);setError('');setRevealed(null);
  try{
   const d=q.id.startsWith('probe:')?
    await readJson(await fetch('/api/tutor/probe',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify({subject,topic,classLevel,question:q.prompt,answer})}),'Answer check'):
    await readJson(await fetch('/api/tutor/check',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify({questionId:q.id,answer,reveal:false})}),'Answer check');
   setFeedback(d)
  }catch(e:any){setError(e.message||'Could not mark this answer.')}finally{setChecking(false)}
 }
 async function explainQuestion(q:Q|undefined){if(!q||helping)return;if(!online){setQuestionHelp('You are offline. Continue reviewing the board; reconnect when you want AVORA to diagnose your attempt.');return;}setHelping(true);setQuestionHelp('');try{const d=await readJson(await fetch('/api/tutor/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,topic,classLevel,exam,unitIndex,question:`I already attempted this practice question: ${q.prompt}. My attempt was: ${answer}. Diagnose the first meaningful gap or mistake, preserve anything I did correctly, and give me only the next useful hint or teaching step. Do not reveal the final answer yet.`,board:[q.prompt],recent:[],currentStepId:event?.stepId,lessonSteps})}),'AVORA');setQuestionHelp(String(d.reply||''));applyGuidanceMeta(d)}catch(e:any){setQuestionHelp(e.message||'AVORA could not explain that just now.')}finally{setHelping(false)}}
 async function revealAnswer(q:Q|undefined){if(!q||checking)return;if(!online){setError('You are offline. Reconnect before requesting the worked answer.');return;}setChecking(true);try{const d=await readJson(await fetch('/api/tutor/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:q.id,answer:answer||'',reveal:true})}),'Answer reveal');setRevealed(d);setAssistanceLevel('ANSWER');setFreshEvidenceRequired(true)}catch(e:any){setError(e.message||'Could not show the worked answer.')}finally{setChecking(false)}}

 async function saveProgress(next:number,cov:number[],complete:boolean){const payload={topic,subject,exam,currentUnit:next,coveredUnits:cov,coverageComplete:complete,lastUnitTitle:unit?.title};if(!online){try{await queueSyncAction('/api/tutor/progress',payload,{dedupeKey:`progress:${subject}:${topic}`});setPendingSync(await countPendingSyncActions())}catch{}return}try{const r=await fetch('/api/tutor/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('progress sync failed')}catch{try{await queueSyncAction('/api/tutor/progress',payload,{dedupeKey:`progress:${subject}:${topic}`});setPendingSync(await countPendingSyncActions())}catch{}}}
 async function logInteraction(kind:'CHECKPOINT'|'QUESTION'|'RETEACH'|'LESSON_COMPLETE',learnerText?:string,teacherText?:string,outcome?:string){const payload={topic,subject,exam,unitTitle:unit?.title,kind,learnerText,teacherText,outcome};if(!online){try{await queueSyncAction('/api/tutor/progress',payload);setPendingSync(await countPendingSyncActions())}catch{}return}try{const r=await fetch('/api/tutor/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('interaction sync failed')}catch{try{await queueSyncAction('/api/tutor/progress',payload);setPendingSync(await countPendingSyncActions())}catch{}}}
 function beginLesson(){trackEvent('TUTOR_LESSON_STARTED',{subject,topic,exam,classLevel});pausedRef.current=false;setFeedback(null);setAnswer('');setPhase('teach');setEventIndex(0);setPaused(false)}
 function continueAfterGuided(){
  const cov=[...new Set([...covered,unitIndex])].sort((a,b)=>a-b);setCovered(cov);setFeedback(null);setAnswer('');setExtraBoard([]);setChat([]);
  if(plan&&unitIndex<plan.units.length-1){const n=unitIndex+1;setUnitIndex(n);setEventIndex(0);setPhase('teach');pausedRef.current=false;setPaused(false);void saveProgress(n,cov,false)}else if(exerciseQuestions.length){setExerciseIndex(0);setExerciseAnswer('');setExerciseFeedback(null);setExerciseCorrect(0);setExerciseFinished(false);setPhase('exercise');void saveProgress(unitIndex,cov,true);trackEvent('TUTOR_TOPIC_EXERCISE_STARTED',{subject,topic,exam,classLevel,questions:exerciseQuestions.length})}else{setPhase('success');void saveProgress(unitIndex,cov,true);void logInteraction('LESSON_COMPLETE','','Topic teaching coverage completed.','COVERED');trackEvent('TUTOR_LESSON_COMPLETED',{subject,topic,exam,classLevel,outcome:'COVERED'})}
 }

 async function checkExercise(){
  if(!exerciseQ||!exerciseAnswer||exerciseChecking||exerciseFeedback)return;
  if(!online){setError('Reconnect to let AVORA mark this exercise.');return}
  setExerciseChecking(true);setError('');
  try{const d=await readJson(await fetch('/api/tutor/exercise-check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId:exerciseQ.id,answer:exerciseAnswer})}),'NERDC exercise');setExerciseFeedback(d);if(d.correct)setExerciseCorrect(v=>v+1)}catch(e:any){setError(e.message||'Could not mark this exercise.')}finally{setExerciseChecking(false)}
 }
 function nextExercise(){
  if(!exerciseFeedback)return;
  if(exerciseIndex<exerciseQuestions.length-1){setExerciseIndex(i=>i+1);setExerciseAnswer('');setExerciseFeedback(null);setError('');return}
  const finalCorrect=exerciseCorrect;setExerciseFinished(true);trackEvent('TUTOR_TOPIC_EXERCISE_COMPLETED',{subject,topic,exam,classLevel,score:finalCorrect,total:exerciseQuestions.length});
  if(finalCorrect>=Math.ceil(exerciseQuestions.length*.8)){setPhase('success');void logInteraction('LESSON_COMPLETE','','NERDC topic teaching and 15-question exercise completed.','MASTERED');trackEvent('TUTOR_LESSON_COMPLETED',{subject,topic,exam,classLevel,outcome:'MASTERED'})}
 }
 function reteachAfterExercise(){setExerciseIndex(0);setExerciseAnswer('');setExerciseFeedback(null);setExerciseCorrect(0);setExerciseFinished(false);setUnitIndex(0);setEventIndex(0);setCovered([]);setPhase('teach');setPaused(false);pausedRef.current=false;trackEvent('TUTOR_RETEACH_TRIGGERED',{subject,topic,exam,reason:'NERDC_EXERCISE_BELOW_80'})}
 async function explainCheckpoint(showModel=false){if(!event||helping)return;if(!online){setQuestionHelp('You are offline. Your checkpoint attempt is saved locally. Reconnect for targeted re-teaching.');return;}setHelping(true);setQuestionHelp('');const prompt=event.question||event.spoken;try{const d=await readJson(await fetch('/api/tutor/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,topic,classLevel,exam,unitIndex,question:showModel?`I attempted this checkpoint: ${prompt}. My attempt was: ${checkpoint}. Teach from exactly where my attempt stopped or went wrong. Preserve correct work, explain one legal/reasoned step at a time, and only reach the full worked solution after the reasoning has been taught. Do not restart from zero unless my foundation is missing.`:`I attempted this checkpoint: ${prompt}. My attempt was: ${checkpoint}. Explain the first gap in simple language without giving the final answer.`,board:[...(event.lines||[]),...extraBoard],recent:chat.slice(-4),currentStepId:event.stepId,lessonSteps})}),'AVORA');setQuestionHelp(String(d.reply||''));applyGuidanceMeta(d)}catch(e:any){setQuestionHelp(e.message||'AVORA could not explain that just now.')}finally{setHelping(false)}}

 async function respondToCheckpoint(){
  const response=checkpoint.trim();if(!response||checkingPoint||!event)return;if(!online){setCheckpointReply('Your attempt is saved on this device. Reconnect so AVORA can check and diagnose it.');return;}pause();setCheckingPoint(true);setCheckpointReply('');
  try{const d=await readJson(await fetch('/api/tutor/checkpoint',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(20000),body:JSON.stringify({subject,topic,classLevel,exam,unitIndex,question:event.question||event.spoken,answer:response,board:[...(event.lines||[]),...extraBoard]})}),'AVORA checkpoint');const reply=`${d.verdict|| (d.correct?'Correct':'Incorrect')}\n\n${d.feedback||''}\n\n${d.correction||''}\n\nAVORA's worked solution:\n${d.solution||'No worked solution was returned.'}`;setCheckpointReply(reply);applyGuidanceMeta({assistanceLevel:d.correct?'HINT':'RETEACH',requiresFreshEvidence:!d.correct});void logInteraction('CHECKPOINT',response,reply,d.correct?'CORRECT':'INCORRECT');if(Array.isArray(d.board)&&d.board.length)setExtraBoard(x=>[...x,...d.board].slice(-8))}catch(e:any){setCheckpointReply(e.message||'I could not check that just now. Try again.')}finally{setCheckingPoint(false)}
 }
 async function askTeacher(presetQuestion?:string){
  const question=(presetQuestion||ask).trim();if(!question||asking)return;if(!online){setChat((x:ChatTurn[])=>[...x,{role:'student' as const,text:question},{role:'teacher' as const,text:'You are offline. I saved your lesson position; reconnect and ask this again for a live answer.'}].slice(-8));setAsk('');return;}pause();setAsking(true);const recent=[...chat,{role:'student' as const,text:question}].slice(-8);setChat(recent);setAsk('');
  try{const d=await readJson(await fetch('/api/tutor/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,topic,classLevel,exam,unitIndex,question,board:[...(event?.lines||[]),...extraBoard],recent,currentStepId:event?.stepId,lessonSteps})}),'AVORA');applyGuidanceMeta(d);setChat((x:ChatTurn[])=>[...x,{role:'teacher' as const,text:String(d.reply||'')}].slice(-8));void logInteraction('QUESTION',question,String(d.reply||''),'ANSWERED');if(Array.isArray(d.board)&&d.board.length)setExtraBoard(x=>[...x,...d.board].slice(-6))}catch(e:any){setChat((x:ChatTurn[])=>[...x,{role:'teacher' as const,text:String(e.message||'I could not answer that just now. Ask me again.')}])}finally{setAsking(false)}
 }

 if(loading)return <section className="tutor-loading"><b>AVORA is preparing your lesson…</b><span>Loading the topic map, learner context and reviewed questions.</span></section>;
 if(error&&!topics.length)return <section className="tutor-error"><b>{error}</b><button onClick={()=>load(topic,subject)}>Retry</button></section>;
 if(!topic)return <section className="tutor-picker-v2"><div className="tutor-subjects"><button className={subject==='Mathematics'?'active':''} onClick={()=>chooseSubject('Mathematics')}><span>∑</span><b>Mathematics</b><small>Choose any topic and start learning directly.</small></button><button className={subject==='English Language'?'active':''} onClick={()=>chooseSubject('English Language')}><span>Aa</span><b>English Language</b><small>Grammar, comprehension, vocabulary and usage.</small></button></div><div className="tutor-topic-grid">{topics.map(t=><button key={t.name} onClick={()=>selectTopic(t.name)}><span>{t.questions?`${t.questions} reviewed questions`:'Full lesson map'}</span><b>{t.name}</b><small>Teach me this topic →</small></button>)}</div></section>;


 return <section className="tutor-engine-v1">
  <div className="tutor-breadcrumb"><Link href="/home">Home</Link><span>›</span><Link href={'/learn?subject='+encodeURIComponent(subject)}>{subject}</Link><span>›</span><b>{topic}</b></div>
  <header className="teacher-session-head"><div><span>{classLevel} · {exam} · {subject}</span><h2>{learnerTopicTitle(topic)}</h2><p>{plan?.goal||'AVORA will teach this topic, check your understanding and adapt to your questions.'}</p></div><button onClick={()=>{setTopic('');router.replace('/tutor?subject='+encodeURIComponent(subject))}}>Change topic</button></header>
  {officialTopic&&<section className="nerdc-objectives-v1491"><div className="nerdc-objectives-main"><span className="curriculum-trust-chip">NERDC NEW REVISED BEC · SEPTEMBER 2025</span><h3>By the end of this topic, you should be able to:</h3><ol>{officialTopic.objectives.map((objective,i)=><li key={i}><b>{i+1}</b><span>{objective}</span></li>)}</ol></div><details className="curriculum-details-v1491"><summary>View curriculum details</summary><div><p><b>Class:</b> {officialTopic.classLevel}</p><p><b>Subject:</b> {officialTopic.subject}</p><p><b>Theme:</b> {officialTopic.theme}</p><p><b>Official topic:</b> {officialTopic.topic}</p><p><b>NERDC content:</b> {officialTopic.content}</p><p><b>Evaluation guide:</b> {officialTopic.evaluation}</p><p><b>Source page{officialTopic.pages.length>1?'s':''}:</b> {officialTopic.pages.join(', ')}</p><small>AVORA splits this official topic into smaller teaching sections only to teach every objective explicitly. The official NERDC topic and objectives remain unchanged.</small></div></details></section>}
  {!VOICE_TEACHING_ENABLED&&<div className="text-first-source-banner"><b>Verified text-first lesson</b><span>The written NERDC-aligned lesson is the academic source of truth. AVORA voice teaching is preserved for later development but is not used for this learner-facing lesson.</span></div>}
  {!online&&<div className="tutor-resilience-v140 offline"><div><i></i><b>Offline learning mode</b><span>Loaded lesson content and the teaching board remain available. Attempts are kept on this device until you reconnect.</span></div><div className="resilience-badges"><span>{lastSavedAt?'✓ Lesson autosaved':'Saving lesson…'}</span><span>{cachedLesson?'✓ Loaded from offline lesson cache':'✓ Latest lesson cached'}</span>{pendingSync>0&&<span>{pendingSync} queued to sync</span>}<span>{screenAwake?'✓ Screen kept awake':'Screen follows device settings'}</span></div></div>}
  {restoredSession&&<div className="session-restored-v140"><div><b>Lesson restored from this device</b><span>{autoPausedByVisibility?'AVORA paused when you left the page so you would not miss teaching.':'Your last section, board step and unfinished answer were recovered. Voice stays paused until you choose Continue.'}</span></div><button type="button" onClick={()=>{setRestoredSession(false);if(paused)resume()}}>Continue from here →</button></div>}
  {plan&&<div className="lesson-map-v1"><div><b>Lesson sections</b><span>{covered.length}/{plan.units.length} completed</span></div><div>{plan.units.map((x,i)=><button key={x.title} className={`${i===unitIndex?'active ':''}${covered.includes(i)?'done':''}`} onClick={()=>{stopAll();setUnitIndex(i);setEventIndex(0);setPhase('teach');setFeedback(null);setPaused(false)}}><i>{covered.includes(i)?'✓':i+1}</i><span>{learnerTopicTitle(x.title)}</span></button>)}</div></div>}

  {phase==='probe'&&!probeQ&&<article className="teacher-turn-card"><span className="teacher-kicker">FULL LESSON AVAILABLE</span><h2>We can teach this topic even before its question bank is complete.</h2><p className="teacher-copy">AVORA will never leave a curriculum lesson blank merely because a reviewed diagnostic question is missing. We teach first, then attach reviewed assessment as it becomes available.</p><div className="teacher-actions"><button className="primary" onClick={beginLesson}>Start the complete lesson →</button></div></article>}
  {phase==='probe'&&probeQ&&<article className="teacher-turn-card"><span className="teacher-kicker">BEFORE I TEACH</span><h2>Show me what you already know.</h2><p className="teacher-copy">This only sets the pace. One answer will never make AVORA skip the rest of the required topic.</p><Question q={probeQ} answer={answer} setAnswer={x=>{setAnswer(x);setFeedback(null);setError('')}}/>{checking&&<p className="answer-status" role="status">AVORA is checking your answer…</p>}{error&&<p className="answer-status error" role="alert">{error}</p>}{feedback&&<div className={feedback.correct?'persistent-feedback good':'persistent-feedback'}><b>{feedback.correct?'Correct — I can build from that.':'Not yet — this shows me where to begin.'}</b><p>{feedback.correct?(feedback.explanation||'That answer is correct.'):(feedback.feedback||feedback.hint||'I will teach the missing idea before asking you again.')}</p></div>}<div className="teacher-actions">{!feedback?<button type="button" className="primary" disabled={!answer||checking} onClick={()=>check('probe')}>{checking?'Checking…':'Check my answer'}</button>:<button type="button" className="primary" onClick={beginLesson}>Start teaching me →</button>}</div></article>}

  {phase==='teach'&&unit&&event&&<article className="live-teacher-stage">
   <div className="teacher-stage-title"><div><button type="button" className="lesson-progress-button" onClick={()=>setShowLessonMap(value=>!value)} aria-expanded={showLessonMap}>SESSION {eventIndex+1} OF {events.length} · {showLessonMap?'Hide lesson map':'Open lesson map'}</button><h2>{learnerTopicTitle(unit.title)}</h2></div><div className="teacher-state"><i className={paused?'paused':speaking?'speaking':''}></i><span>{!VOICE_TEACHING_ENABLED?'Verified text lesson · move when you are ready':paused?'Paused — nothing is moving':speaking?'AVORA is teaching':'Ready for the next explanation'}</span></div></div>
   {showLessonMap&&<nav className="session-map-v1" aria-label="Lesson map">{events.map((item,i)=><button type="button" key={item.stepId} className={i===eventIndex?'active':''} onClick={()=>{stopAll();setEventIndex(i);setPaused(true);pausedRef.current=true}}><i>{i<eventIndex?'✓':i+1}</i><span>{learnerSessionTitle(item.label)}</span></button>)}</nav>}
   <section className="avora-teacher-dialogue-v1491"><div className="avora-tutor-mark">A</div><div className="avora-teacher-copy"><span>AVORA IS TEACHING</span><p>{event.spoken}</p><div className="teacher-interrupt-actions"><button type="button" disabled={asking} onClick={()=>void askTeacher('Why is this step or idea valid? Explain the exact reason using what is currently on the board.')}>Why?</button><button type="button" disabled={asking} onClick={()=>void askTeacher('Explain this exact idea more simply, from the foundation, without skipping the reason behind it.')}>Explain more simply</button><button type="button" disabled={asking} onClick={()=>void askTeacher('Give me one different example of this exact idea, work it carefully, then give me one short question to try.')}>Another example</button></div></div></section>
   <div className={`animated-board-v1 ${paused?'is-paused':''} board-action-${(event.boardAction||'WRITE').toLowerCase()}`} data-step-id={event.stepId} aria-live="polite"><div className="board-step-meta"><span>{learnerSessionTitle(event.label)}</span></div><div className="board-writing" key={`${unitIndex}-${eventIndex}`}>{event.lines.slice(0,visibleBoardLineCount).map((line,i)=><div key={i} className={`board-line line-${i}`}>{line}</div>)}{extraBoard.map((line,i)=><div key={'x'+i} className="board-line board-extra">{line}</div>)}</div><VisualBoard spec={visualSpec}/><div className="board-timeline">{events.map((_,i)=><i key={i} className={i<eventIndex?'done':i===eventIndex?'active':''}></i>)}</div></div>
   {event.kind==='check'&&<section className="lesson-checkpoint-v2"><span>YOUR TURN — THE LESSON WAITS FOR YOU</span><h3>{event.question||event.spoken}</h3><div className="task-expectation"><b>What AVORA wants you to do</b><p>{event.expectation||'Answer the question directly and show your reasoning.'}</p></div><p>There is no need to guess what the task means. If you are unsure, ask AVORA before answering.</p>{checkpointReply&&<div className="checkpoint-help-actions"><button type="button" disabled={helping} onClick={()=>void explainCheckpoint(false)}>{helping?'Explaining…':'Explain my first gap'}</button><button type="button" disabled={helping} onClick={()=>void explainCheckpoint(true)}>Teach this from my attempt</button></div>}{questionHelp&&<div className="question-help-box"><b>AVORA EXPLAINS</b><p>{questionHelp}</p></div>}{reguideStepId&&<div className="reguide-card"><div><b>Targeted re-teaching available</b><span>{assistanceLevel==='RETEACH'?'AVORA identified a lesson step to rebuild this idea.':'Return to the exact lesson step connected to this gap.'}</span></div><button type="button" onClick={jumpToGuidanceStep}>Re-teach from exact step →</button></div>}{freshEvidenceRequired&&<p className="fresh-evidence-note">This help is assisted learning. AVORA will require a fresh question before counting independent mastery.</p>}<textarea value={checkpoint} onChange={e=>{setCheckpoint(e.target.value);setCheckpointReply('')}} placeholder="Type your answer or working here…" rows={3}/><button className="primary" disabled={!checkpoint.trim()||checkingPoint} onClick={()=>void respondToCheckpoint()}>{checkingPoint?'AVORA is checking…':'Check whether I understood it'}</button>{checkpointReply&&<div className="checkpoint-teacher-reply"><b>AVORA'S CHECK</b><p>{checkpointReply}</p><button onClick={nextEvent}>Continue when I am ready →</button></div>}</section>}
   {VOICE_TEACHING_ENABLED&&<div className="voice-runtime-v139"><div className="voice-runtime-copy"><b>{speechAvailable?(speaking?'AVORA is speaking':paused?'Voice paused':'Voice ready'):'Voice unavailable in this browser'}</b><span>{voiceOn&&activeSpokenSegment?activeSpokenSegment:'Board-first teaching remains available with voice off.'}</span></div><div className="voice-runtime-progress" role="progressbar" aria-label="Narration progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={narrationProgress}><i style={{width:`${narrationProgress}%`}} /></div>{speechAvailable&&voiceChoices.length>0&&<label>Teacher voice<select value={voiceURI} onChange={e=>chooseVoice(e.target.value)}>{voiceChoices.map(v=><option key={v.uri} value={v.uri}>{v.name} · {v.lang}{v.local?'':' · online'}</option>)}</select></label>}</div>}
   <div className="teacher-controls-v1">{VOICE_TEACHING_ENABLED&&<><button onClick={paused?resume:pause}>{paused?'▶ Continue':'Ⅱ Pause'}</button><button onClick={replay}>↻ Replay</button><button onClick={()=>setRate(r=>r<=.72?.95:Math.max(.7,+(r-.1).toFixed(2)))}>{Math.round(rate*100)}% speed</button><button onClick={toggleVoice}>{voiceOn?'🔊 Voice on':'🔇 Voice off'}</button></>}<button onClick={prevEvent} disabled={eventIndex===0}>← Previous</button><button className="primary" onClick={nextEvent} disabled={event.kind==='check'&&!checkpointReply}>Next teaching step →</button></div>
   <section className="ask-teacher-v1"><div className="ask-heading"><b>Interrupt me anytime.</b><span>Ask about the exact thing on the board. AVORA pauses the lesson while you ask.</span></div>{chat.length>0&&<div className="mini-conversation">{chat.map((x,i)=><div key={i} className={x.role}><b>{x.role==='teacher'?'AVORA':'You'}</b><p>{x.text}</p></div>)}</div>}{reguideStepId&&paused&&<div className="reguide-card compact"><div><b>Reconnect to the lesson</b><span>AVORA can return to the exact step that supports this question.</span></div><button type="button" onClick={jumpToGuidanceStep}>Go to step →</button></div>}<div className="ask-compose"><input value={ask} onChange={e=>setAsk(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void askTeacher()}} placeholder="Why did you do that? Explain it another way. Give me an easier example…"/><button disabled={!ask.trim()||asking} onClick={()=>void askTeacher()}>{asking?'Thinking…':'Ask AVORA'}</button></div>{paused&&chat.length>0&&<button className="resume-lesson" onClick={resume}>Continue my lesson from here →</button>}</section>
  </article>}

  {phase==='guided'&&guidedQ&&<article className="teacher-turn-card"><span className="teacher-kicker">NOW YOU TRY THE SAME SKILL</span><h2>Practice what AVORA just taught.</h2><div className="task-expectation"><b>What you are expected to do</b><p>{questionInstruction(guidedQ)}</p></div><Question q={guidedQ} answer={answer} setAnswer={x=>{setAnswer(x);setFeedback(null);setRevealed(null);setReguideStepId(null);setAssistanceLevel(null);setFreshEvidenceRequired(false)}}/>{feedback&&<div className="question-help-row">{!feedback.correct&&<button type="button" onClick={()=>void explainQuestion(guidedQ)} disabled={helping}>{helping?'Diagnosing…':'Explain from my attempt'}</button>}{(!feedback.correct&&questionHelp)&&<button type="button" onClick={()=>void revealAnswer(guidedQ)} disabled={checking}>Show the full worked solution after the hint</button>}</div>}{questionHelp&&<div className="question-help-box"><b>WHAT THE QUESTION MEANS</b><p>{questionHelp}</p></div>}{reguideStepId&&<div className="reguide-card"><div><b>Re-teach the missing idea</b><span>AVORA linked this difficulty to a specific teaching step.</span></div><button type="button" onClick={jumpToGuidanceStep}>Open exact teaching step →</button></div>}{freshEvidenceRequired&&<p className="fresh-evidence-note">Because AVORA substantially helped with this item, use a fresh equivalent question for independent mastery evidence.</p>}{feedback&&<div className={feedback.correct?'persistent-feedback good':'persistent-feedback'}><b>{feedback.correct?'Correct ✓ — you got this one.':'Not yet — this answer is not correct.'}</b><p><strong>Your answer:</strong> {answer}</p><p>{feedback.correct?(feedback.explanation||'That is correct. Notice which rule or step made it work.'):(feedback.hint||'Use the clue and try again.')}</p></div>}{revealed&&<div className="answer-reveal-box"><b>AVORA'S ANSWER</b><strong>{revealed.correctAnswer||'See the explanation below.'}</strong><p>{revealed.explanation||revealed.hint||'Review the rule AVORA just taught, then try a similar question.'}</p><small>Seeing the answer helps you learn, but it does not count as independent mastery.</small></div>}{error&&<p className="flow-error">{error}</p>}<div className="teacher-actions"><button onClick={()=>{setPhase('teach');setEventIndex(0);setFeedback(null);setAnswer('');setQuestionHelp('');setRevealed(null)}}>Teach this again</button>{!feedback?.correct?<button className="primary" disabled={!answer||checking} onClick={()=>check('guided')}>{checking?'Marking…':'Check my answer'}</button>:<button className="primary" onClick={continueAfterGuided}>{plan&&unitIndex<plan.units.length-1?'Continue to next section →':'Finish topic teaching →'}</button>}{revealed&&!feedback?.correct&&<button onClick={continueAfterGuided}>{plan&&unitIndex<plan.units.length-1?'Continue after review →':'Finish this taught topic →'}</button>}</div></article>}

  {phase==='exercise'&&exerciseQ&&!exerciseFinished&&<article className="teacher-turn-card nerdc-topic-exercise"><span className="teacher-kicker">NERDC TOPIC EXERCISE · {exerciseIndex+1} OF {exerciseQuestions.length}</span><h2>Now prove what you understood.</h2><p className="teacher-copy">These 15 multiple-choice questions sample concepts, application, reasoning and common misconceptions from this official topic. Read each option carefully before choosing.</p><div className="exercise-score-strip"><span>Score so far</span><b>{exerciseCorrect} correct</b></div><Question q={exerciseQ} answer={exerciseAnswer} setAnswer={x=>{if(!exerciseFeedback)setExerciseAnswer(x)}}/>{exerciseFeedback&&<div className={exerciseFeedback.correct?'persistent-feedback good tutor-feedback-v1491':'persistent-feedback tutor-feedback-v1491'}><span className="feedback-tutor-label">AVORA TUTOR FEEDBACK</span><b>{exerciseFeedback.correct?'Correct ✓ — now understand why.':'Not yet — we will fix the idea, not just the answer.'}</b><p><strong>Your answer:</strong> {exerciseAnswer}</p><p><strong>Correct answer:</strong> {exerciseFeedback.correctAnswer}</p><p><strong>Why:</strong> {exerciseFeedback.explanation||exerciseFeedback.hint}</p>{!exerciseFeedback.correct&&<button type="button" onClick={()=>{setPhase('teach');setUnitIndex(0);setEventIndex(0);setPaused(true);pausedRef.current=true}}>Teach the topic again from the foundation →</button>}</div>}{error&&<p className="answer-status error" role="alert">{error}</p>}<div className="teacher-actions">{!exerciseFeedback?<button className="primary" disabled={!exerciseAnswer||exerciseChecking} onClick={()=>void checkExercise()}>{exerciseChecking?'Marking…':'Check answer'}</button>:<button className="primary" onClick={nextExercise}>{exerciseIndex<exerciseQuestions.length-1?'Next question →':'Finish exercise →'}</button>}</div></article>}
  {phase==='exercise'&&exerciseFinished&&<article className="teacher-turn-card"><span className="teacher-kicker">MASTERY CHECK</span><h2>{exerciseCorrect} / {exerciseQuestions.length}</h2><p className="teacher-copy">AVORA requires at least 80% independent evidence here before treating the topic as secure. A lower score does not erase your progress; it tells us to reteach the topic from the beginning and focus on the rules and misconceptions that still need work.</p><div className="teacher-actions"><button className="primary" onClick={reteachAfterExercise}>Re-teach this topic completely →</button><Link className="link-button" href={'/practice?topic='+encodeURIComponent(topic)}>Do more independent practice</Link></div></article>}

  {phase==='success'&&<article className="teacher-turn-card success"><span className="teacher-kicker">TOPIC COVERAGE COMPLETE</span><h2>You have been taught the required sections of {topic}.</h2><p>That is teaching coverage, not a fake mastery badge. Now prove the topic independently without Tutor help.</p><div className="teacher-actions"><Link className="primary link-button" href={'/practice?topic='+encodeURIComponent(topic)}>Start independent practice →</Link><Link className="link-button" href={'/learn?subject='+encodeURIComponent(subject)}>Choose another topic</Link></div></article>}
 </section>
}

function Question({q,answer,setAnswer}:{q:Q;answer:string;setAnswer:(x:string)=>void}){return <div className="teacher-question"><h3>{q.prompt}</h3>{q.type==='MULTIPLE_CHOICE'&&q.options?.length?<div className="teacher-options">{q.options.map((o,i)=><button type="button" key={`${o}-${i}`} className={answer===o?'chosen':''} onClick={()=>setAnswer(o)}><b>{String.fromCharCode(65+i)}</b><span>{o}</span></button>)}</div>:<div className="teacher-input"><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer here…"/></div>}</div>}
