'use client';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {getTutorPlan} from '@/lib/tutorCurriculum';

type Topic={name:string;questions:number};
type Q={id:string;prompt:string;type:string;options:string[];hint:string;explanation:string;difficulty:number;skill:string;topic:string};
type Phase='probe'|'teach'|'example'|'guided'|'success';

async function readApiJson(response:Response,label:string){
 const text=await response.text();
 if(!text.trim())throw new Error(`${label} returned no data. Your connection may have dropped. Please try again.`);
 let data:any;
 try{data=JSON.parse(text)}catch{throw new Error(`${label} returned an invalid response. Refresh or retry the request.`)}
 if(response.status===401){window.location.assign('/login');throw new Error('Your session has expired. Redirecting to sign in…')}
 if(!response.ok)throw new Error(data?.error||`${label} could not complete the request.`);
 return data;
}
type Lesson={idea:string;visual:string;example:string;steps:string[];simple:string};

const lessons:Record<string,Lesson>={
 'Number & Numeration':{idea:'Fractions, decimals and percentages are different ways to describe the same part of a whole.',simple:'A percentage means “out of 100”. Find the part, compare it with the whole, then convert only if the question asks you to.',visual:'25% = 25/100 = 1/4',example:'Example: 3/5 as a percentage. Multiply both parts by 20: 3/5 = 60/100 = 60%.',steps:['Identify the whole and the part.','Choose the fraction, decimal or percentage relationship.','Make one calculation.','Check whether the result is reasonable.']},
 'Algebra':{idea:'An equation is a balance. To find an unknown, undo operations while doing the same thing to both sides.',simple:'Keep both sides equal. Remove what is attached to x one operation at a time.',visual:'x + 6 = 14  →  x + 6 − 6 = 14 − 6  →  x = 8',example:'Example: 3x + 5 = 20. Subtract 5 from both sides: 3x = 15. Divide both sides by 3: x = 5.',steps:['Identify what is being done to the unknown.','Undo that operation on both sides.','Simplify.','Substitute your answer back to check.']},
 'Geometry & Mensuration':{idea:'First decide what is being measured. Around a shape is perimeter; the surface inside is area; space inside a solid is volume.',simple:'Picture the shape first. Decide whether the question asks for around, inside, or an angle before choosing a formula.',visual:'PERIMETER = around the edge   |   AREA = surface inside',example:'Example: a 5 cm by 3 cm rectangle has area 15 cm² and perimeter 16 cm.',steps:['Identify what must be measured.','Sketch or picture the shape.','Choose the matching relationship or formula.','Use the correct unit.']},
 'Commercial Arithmetic':{idea:'Money problems become clearer when you find the actual change before turning it into a percentage.',simple:'Find the money difference first. Only then compare it with the original amount.',visual:'COST → CHANGE → COMPARE WITH ORIGINAL → %',example:'Example: cost ₦500, selling price ₦600. Profit = ₦100. Profit percentage = 100/500 × 100 = 20%.',steps:['Identify the original amount.','Find the change.','Compare with the correct base amount.','Convert to percentage if required.']},
 'Statistics & Data':{idea:'Data questions ask for different things: mean is average, median is middle, mode is most frequent, range is spread.',simple:'Read what the question asks before calculating. Average, middle, most common and spread are not the same thing.',visual:'MEAN = total ÷ count   |   MEDIAN = middle   |   MODE = most frequent   |   RANGE = largest − smallest',example:'Example: 2, 4, 4, 7, 8. Median = 4, mode = 4 and range = 6.',steps:['Identify the requested measure.','Arrange or count the data if needed.','Use only the matching rule.','Check the result against the data.']},
 'Ratio & Proportion':{idea:'A ratio compares quantities. Before comparing measurements, the quantities must use compatible units. A metre is 100 centimetres, a kilogram is 1000 grams, and a litre is 1000 millilitres.',simple:'First make the units the same. Then simplify or scale both parts of the ratio by the same factor.',visual:'1 m = 100 cm   •   1 kg = 1000 g   •   2 kg = 2000 g',example:'Example: 50 cm : 2 m. Since 1 m = 100 cm, 2 m = 200 cm. Now compare 50 cm : 200 cm, which simplifies to 1 : 4.',steps:['Check whether the quantities use the same unit.','Convert to one common unit when needed.','Simplify or find the scale factor.','Check that the relationship is unchanged.']},
 'Measurement':{idea:'Unit conversion is about scale. Moving to a smaller unit produces more units; moving to a larger unit produces fewer.',simple:'Write the unit you have and the unit you need. Then use the exact conversion relationship between them.',visual:'1 m = 100 cm   |   1 kg = 1000 g   |   1 L = 1000 ml',example:'Example: 2.5 m = 2.5 × 100 = 250 cm.',steps:['Write the starting unit.','Write the required unit.','Recall the conversion relationship.','Multiply or divide and label the answer.']},
 'Probability':{idea:'Probability compares the outcomes you want with all equally possible outcomes.',simple:'Count the possible outcomes. Count the wanted outcomes. Put wanted over total.',visual:'Probability = favourable outcomes ÷ total possible outcomes',example:'Example: an even number on a fair die has 3 favourable outcomes out of 6, so probability = 3/6 = 1/2.',steps:['List or count all possible outcomes.','Count favourable outcomes.','Put favourable over total.','Simplify and check that the answer lies between 0 and 1.']},
 'Grammar & Structure':{idea:'Grammar questions test relationships between words: subject, verb, tense and sentence structure.',simple:'Find who or what the sentence is about, then check the verb and the time of the action.',visual:'SUBJECT → VERB → REST OF THE IDEA',example:'Example: “Each of the players has a jersey.” “Each” is singular, so the correct verb is “has”.',steps:['Find the subject.','Find the verb.','Check agreement and tense.','Read the complete sentence naturally.']},
 'Vocabulary & Lexis':{idea:'Vocabulary in context is solved by using clues around the word, not by guessing the word alone.',simple:'Read the whole sentence and replace the difficult word with each option. Keep the meaning that fits naturally.',visual:'WORD + CONTEXT CLUE → BEST MEANING',example:'Example: “The diligent student completed every task.” Diligent means hard-working.',steps:['Read the complete sentence.','Find the clue around the word.','Test the possible meanings.','Choose the meaning that preserves the sentence.']},
 'Comprehension':{idea:'Comprehension asks you to find evidence in a passage and answer only what the question asks.',simple:'Read the question, locate the matching line or idea, then answer from that evidence.',visual:'QUESTION → RELEVANT LINE → DIRECT ANSWER',example:'Example: “Although the rain was heavy, the match continued.” What happened despite the rain? The match continued.',steps:['Read the question carefully.','Locate the matching evidence.','Ignore unrelated details.','Answer only what is supported.']},
 'Sentence Meaning':{idea:'Sentence meaning tests whether you can preserve an idea when it is expressed in different words.',simple:'Say the sentence in simpler words without changing its meaning.',visual:'ORIGINAL SENTENCE → SIMPLE MEANING → BEST MATCH',example:'Example: “Bola is too tired to continue” means Bola is so tired that continuing is not possible.',steps:['Find the key expression.','Restate it simply.','Keep the original meaning.','Choose the closest option.']},
 'Punctuation':{idea:'Punctuation shows sentence boundaries, pauses, questions, quotations and possession.',simple:'Ask what job the mark needs to do before choosing it.',visual:'QUESTION ?   STATEMENT .   LIST ,   POSSESSION ’',example:'Example: “Where are you going?” asked Mother. The question mark belongs with the spoken question.',steps:['Identify what the sentence is doing.','Choose the mark for that job.','Place it at the correct boundary.','Read the sentence again.']},
 'Spelling & Usage':{idea:'Spelling and usage questions reward careful comparison of the complete word and its meaning in context.',simple:'Slow down and compare the part that changes between the options.',visual:'WHOLE WORD → TROUBLE PART → CHECK IN CONTEXT',example:'Example: “accept” means receive; “except” means leave out.',steps:['Read the complete word or sentence.','Notice the changing part.','Use meaning as well as spelling.','Choose the standard form.']},
 'Word Classes':{idea:'Word classes describe the job a word performs in a sentence.',simple:'Do not label a word from memory alone. Ask what job it is doing in this sentence.',visual:'NOUN = thing   |   VERB = action/state   |   ADJECTIVE = describes noun   |   ADVERB = describes action',example:'Example: in “They opened the heavy door”, “heavy” describes “door”, so it is an adjective.',steps:['Find the target word.','Ask what job it performs.','Match the job to a word class.','Check it in the sentence.']},
 'Concord':{idea:'Concord means the subject and verb agree in number.',simple:'Find the true subject first. Decide whether it is singular or plural, then choose the matching verb.',visual:'SINGULAR SUBJECT ↔ SINGULAR VERB   |   PLURAL SUBJECT ↔ PLURAL VERB',example:'Example: “The boys play football.” “Boys” is plural, so “play” is correct.',steps:['Find the true subject.','Decide singular or plural.','Choose the matching verb.','Read the sentence naturally.']}
};
const aliases:Record<string,string>={'Geometry & Measurement':'Geometry & Mensuration','Data & Statistics':'Statistics & Data'};
const fallback:Lesson={idea:'Start by identifying exactly what the question gives you and exactly what it asks you to find.',simple:'Know what you have, know what you need, then make one justified step.',visual:'WHAT I KNOW → WHAT I NEED → ONE VALID STEP',example:'Read the information, state the target, make one valid step, then check it.',steps:['State what you know.','State what you need.','Make one justified step.','Check the result.']};

type BoardStep={label:string;title:string;body:string;visual?:string;spoken?:string};

function verbalizeForSpeech(text:string){
 return String(text||'')
  .replace(/cm²/g,' square centimetres').replace(/cm³/g,' cubic centimetres')
  .replace(/m²/g,' square metres').replace(/m³/g,' cubic metres')
  .replace(/(\d+(?:\.\d+)?)\s*\/\s*(\d+)/g,'$1 over $2').replace(/kg\b/gi,' kilograms').replace(/\bcm\b/gi,' centimetres').replace(/\bmm\b/gi,' millimetres').replace(/\bkm\b/gi,' kilometres').replace(/\bmL\b/g,' millilitres')
  .replace(/÷/g,' divided by ').replace(/×/g,' times ').replace(/=/g,' equals ').replace(/→/g,'. Then ').replace(/≥/g,' greater than or equal to ').replace(/≤/g,' less than or equal to ')
  .replace(/\+/g,' plus ').replace(/−/g,' minus ').replace(/\s+/g,' ').trim();
}

function teacherNarration(step:BoardStep,unit:any){
 const clean=verbalizeForSpeech(step.body);
 if(step.spoken)return verbalizeForSpeech(step.spoken);
 if(step.label==='CORE IDEA')return `Let us begin with the main idea. ${clean} I want you to understand the reason before we worry about remembering a rule.`;
 if(step.label==='TERMS'){
  const parts=(unit?.terms||[]).map(([a,b]:[string,string])=>`${a} means ${b}`);
  return `Before I use these words, let us make them clear. ${verbalizeForSpeech(parts.join('. '))}. These meanings will help the rest of the lesson make sense.`;
 }
 if(step.label==='METHOD')return `Now let us think through the method. ${clean} Do not rush this step. The goal is to know why the method works, not just copy it.`;
 if(step.label==='WORKED EXAMPLE')return `Watch this example carefully. ${clean} Follow each decision and notice why the next step is allowed.`;
 if(step.label==='CHECK')return `Before we move on, I want to make sure this part is clear. ${clean} Take your time. If you miss it, we will explain the exact part again.`;
 return clean;
}

function buildBoardSteps(topic:string,lesson:Lesson,unit:any,simple:boolean):BoardStep[]{
 const normalized=aliases[topic]||topic;
 const terms=unit?.terms?.length?unit.terms.map(([a,b]:[string,string])=>`${a}: ${b}`).join(' • '):'';
 if(normalized==='Ratio & Proportion') return [
  {label:'FOUNDATION',title:'First, make the units speak the same language',body:'Before we compare measurements in a ratio, both quantities must use the same unit.',visual:'m = metre   •   cm = centimetre   •   kg = kilogram   •   g = gram',spoken:'Before we solve a ratio with measurements, let us make sure the units are clear. M means metre. C M means centimetre. K G means kilogram, and G means gram. We compare like with like, so different units must first be converted.'},
  {label:'CONVERSION',title:'Learn the conversion relationship',body:'One metre contains 100 centimetres. One kilogram contains 1000 grams.',visual:'1 m = 100 cm     |     1 kg = 1000 g',spoken:'One metre is equal to one hundred centimetres. One kilogram is equal to one thousand grams. These relationships let us rewrite both quantities using the same unit.'},
  {label:'WATCH',title:'Convert before you simplify',body:'For 50 cm : 2 m, convert 2 metres to centimetres first.',visual:'2 m = 2 × 100 cm = 200 cm',spoken:'Now watch carefully. We have fifty centimetres compared with two metres. The units are different. Since one metre equals one hundred centimetres, two metres equals two times one hundred centimetres. That gives us two hundred centimetres.'},
  {label:'WORKED EXAMPLE',title:'Now the ratio can be simplified',body:'Both quantities are now centimetres, so the common unit can be removed and the numbers simplified.',visual:'50 cm : 200 cm  →  50 : 200  →  1 : 4',spoken:'Now both quantities are in centimetres. Fifty centimetres to two hundred centimetres becomes fifty to two hundred. Divide both parts by fifty. Fifty divided by fifty equals one, and two hundred divided by fifty equals four. So the ratio is one to four.'},
  {label:'YOUR TURN',title:'Now you will use what I just taught',body:'I will pause the teaching and give you a fresh reviewed question. If you miss it, we will stay here, find the exact gap, and work through it together.',spoken:'That is the idea. Now it is your turn. I will give you a fresh question. Take your time. If you get stuck, I will explain the part causing the difficulty instead of simply moving on.'}
 ];
 const base:BoardStep[]=[
  {label:'CORE IDEA',title:unit?.title||'Understand the idea',body:unit?.why||unit?.explain||(simple?lesson.simple:lesson.idea)},
  ...(terms?[{label:'TERMS',title:'Words you must understand',body:terms}]:[]),
  {label:'METHOD',title:'How to think about it',body:unit?.explain||(simple?lesson.simple:lesson.idea),visual:unit?.example?undefined:lesson.visual},
  {label:'WORKED EXAMPLE',title:'Watch the method in action',body:unit?.example||lesson.example},
  {label:'CHECK',title:'Now check your understanding',body:unit?.check||'Explain the main idea in your own words, then try a fresh question.'}
 ];
 if(normalized==='Algebra'){
  base[2]={label:'METHOD',title:'Keep the equation balanced',body:'Whatever operation you perform on one side of an equation must also be performed on the other side.',visual:'x + 6 = 14  →  x + 6 − 6 = 14 − 6  →  x = 8',spoken:'We want x by itself. Six has been added to x, so we undo that by subtracting six. But an equation is a balance, so we subtract six from both sides. On the left, plus six and minus six cancel. On the right, fourteen minus six equals eight. That leaves x equal to eight.'};
 }
 return base.map(step=>({...step,spoken:teacherNarration(step,unit)}));
}

function TutorWhiteboard({topic,lesson,simple,unit,stepIndex,voiceEnabled,speaking,paused,rate,voiceSupported,onToggleVoice,onHear,onPauseResume,onRepeat,onSlower,onStop,onPrevious,onNext,onLessonComplete}:{topic:string;lesson:Lesson;simple:boolean;unit:any;stepIndex:number;voiceEnabled:boolean;speaking:boolean;paused:boolean;rate:number;voiceSupported:boolean;onToggleVoice:()=>void;onHear:()=>void;onPauseResume:()=>void;onRepeat:()=>void;onSlower:()=>void;onStop:()=>void;onPrevious:()=>void;onNext:()=>void;onLessonComplete:()=>void}){
 const steps=buildBoardSteps(topic,lesson,unit,simple);
 const safe=Math.max(0,Math.min(stepIndex,steps.length-1));
 const step=steps[safe];
 const algebra=(aliases[topic]||topic)==='Algebra'&&step.label==='METHOD';
 const percent=(aliases[topic]||topic)==='Number & Numeration'&&step.label==='METHOD';
 useEffect(()=>{if(paused)return;const start=setTimeout(()=>onHear(),450);const wait=Math.max(8500,Math.min(15000,5200+(step.spoken||step.body).length*22));const advance=setTimeout(()=>{if(safe<steps.length-1)onNext();else onLessonComplete()},wait);return()=>{clearTimeout(start);clearTimeout(advance)}},[safe,paused]);
 return <div className="live-whiteboard whiteboard-tutor" aria-label="AVORA whiteboard tutor">
  <div className="whiteboard-top whiteboard-tutor-head"><div><span>AVORA WHITEBOARD TUTOR</span><small>{voiceEnabled?(speaking?(paused?'Voice paused':'Explaining this board step…'):`Voice on · ${Math.round(rate*100)}% speed`):'Voice off · follow the board visually'}</small></div><button className={voiceEnabled?'voice-switch on':'voice-switch'} onClick={onToggleVoice} disabled={!voiceSupported} aria-pressed={voiceEnabled}>{voiceEnabled?'🔊 Voice on':'🔇 Voice off'}</button></div>
  <div className="board-progress" aria-label={`Whiteboard step ${safe+1} of ${steps.length}`}>{steps.map((_,i)=><i key={i} className={i<safe?'done':i===safe?'active':''}/>)}</div>
  <div className="board-step-copy"><span>{step.label} · STEP {safe+1} OF {steps.length}</span><h3>{step.title}</h3><p>{step.body}</p></div>
  {algebra?<div className="balance-board synchronized-board"><div className="board-equation">x + 6 = 14</div><div className="board-arrow">subtract 6 from both sides ↓</div><div className="board-equation muted">x + 6 − 6 = 14 − 6</div><div className="board-equation answer">x = 8</div></div>:
   percent?<div className="percent-board synchronized-board"><div className="percent-grid" aria-hidden="true">{Array.from({length:100},(_,i)=><i key={i} className={i<25?'filled':''}/>)}</div><div className="board-equation">25 shaded out of 100 = 25% = 1/4</div></div>:
   step.visual?<div className="board-general synchronized-board"><div className="board-equation">{step.visual}</div></div>:null}
  <div className="whiteboard-controls compact"><button onClick={onPauseResume}>{paused?'▶ Continue':'⏸ Pause'}</button><button onClick={onRepeat} disabled={!voiceSupported||!voiceEnabled}>↻ Replay</button><button onClick={onSlower} disabled={!voiceSupported}>{Math.round(rate*100)}% speed</button><button onClick={onToggleVoice} disabled={!voiceSupported}>{voiceEnabled?'🔊 Voice':'🔇 Voice'}</button><button className="ask-control" onClick={()=>document.getElementById('ask-avora-input')?.focus()}>💬 Ask AVORA</button></div>
  {!voiceSupported&&<p className="whiteboard-caption">Voice is unavailable in this browser, but every explanation remains visible and usable on the whiteboard.</p>}
 </div>
}

export default function TutorClient(){
 const params=useSearchParams(),router=useRouter();
 const requested=params.get('topic')||'';
 const recoveryTopics=(params.get('recovery')||'').split('|').map(x=>x.trim()).filter(Boolean);
 const recoveryIndex=Math.max(0,recoveryTopics.findIndex(x=>x.toLowerCase()===requested.toLowerCase()));
 const nextRecovery=recoveryTopics[recoveryIndex+1]||'';
 const [topics,setTopics]=useState<Topic[]>([]),[topic,setTopic]=useState(requested),[questions,setQuestions]=useState<Q[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [exam,setExam]=useState('BECE'),[subject,setSubject]=useState('Mathematics'),[classLevel,setClassLevel]=useState('JSS3'),[unitIndex,setUnitIndex]=useState(0),[coveredUnits,setCoveredUnits]=useState<number[]>([]);
 const [phase,setPhase]=useState<Phase>('probe'),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<any>(null),[checking,setChecking]=useState(false),[showVisual,setShowVisual]=useState(true),[simple,setSimple]=useState(false);
 const [speaking,setSpeaking]=useState(false),[paused,setPaused]=useState(false),[rate,setRate]=useState(0.92),[voiceSupported,setVoiceSupported]=useState(false),[voiceEnabled,setVoiceEnabled]=useState(true),[boardStep,setBoardStep]=useState(0),[listening,setListening]=useState(false),[studentQuestion,setStudentQuestion]=useState(''),[teacherReply,setTeacherReply]=useState('');
 const lastSpeech=useRef('');
 const lesson=useMemo(()=>lessons[aliases[topic]||topic]||fallback,[topic]);
 const plan=useMemo(()=>getTutorPlan(exam,subject,topic),[exam,subject,topic]);
 const unit=plan?.units[Math.min(unitIndex,Math.max(0,(plan?.units.length||1)-1))];
 const probeQ=questions[0]||null;
 const guidedQ=questions[1]||questions[0]||null;
 const sectionQ=questions[2]||questions[1]||questions[0]||null;
 const q=phase==='example'?sectionQ:phase==='guided'?guidedQ:probeQ;
 const coverageComplete=Boolean(plan?.units.length)&&coveredUnits.length>=plan!.units.length;
 useEffect(()=>{setVoiceSupported(typeof window!=='undefined'&&'speechSynthesis' in window);return()=>{if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel()}},[]);
 useEffect(()=>{load(topic)},[topic]);
 useEffect(()=>{setBoardStep(0);return()=>{if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel()}},[topic,phase,unitIndex]);
 async function load(t:string){setLoading(true);setError('');setQuestions([]);setAnswer('');setFeedback(null);setPhase('probe');setShowVisual(true);setSimple(false);setCoveredUnits([]);setUnitIndex(0);try{const r=await fetch('/api/tutor'+(t?'?topic='+encodeURIComponent(t):''),{cache:'no-store',headers:{'Accept':'application/json'}});const d=await readApiJson(r,'AVORA Tutor');setTopics(d.topics||[]);setExam(d.exam||'BECE');setSubject(d.subject||'Mathematics');setClassLevel(d.classLevel||(d.exam==='BECE'?'JSS3':'Primary 6'));if(d.questions?.length)setQuestions(d.questions);else if(d.question)setQuestions([d.question]);if(t){try{const pr=await fetch('/api/tutor/progress?topic='+encodeURIComponent(t),{cache:'no-store',headers:{'Accept':'application/json'}});const pd=await readApiJson(pr,'Tutor progress');if(pd.progress){setUnitIndex(Math.max(0,pd.progress.currentUnit||0));setCoveredUnits(Array.isArray(pd.progress.coveredUnits)?pd.progress.coveredUnits:[])}}catch(e:any){console.warn('Tutor progress recovery:',e?.message||e)}}}catch(e:any){setError(e.message||'Could not load tutor.')}finally{setLoading(false)}}
 function choose(name:string){setTopic(name);router.replace('/tutor?topic='+encodeURIComponent(name));}
 async function saveProgress(nextUnit:number,nextCovered:number[],done=false){if(!topic)return;try{await fetch('/api/tutor/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,currentUnit:nextUnit,coveredUnits:nextCovered,coverageComplete:done})})}catch{}}
 function markCovered(i=unitIndex){const next=Array.from(new Set([...coveredUnits,i])).sort((a,b)=>a-b);setCoveredUnits(next);void saveProgress(i,next,Boolean(plan&&next.length>=plan.units.length));return next}
 function goNextUnit(){if(!plan)return;const nextCovered=markCovered(unitIndex);if(unitIndex<plan.units.length-1){const next=unitIndex+1;setUnitIndex(next);setPhase('teach');setAnswer('');setFeedback(null);void saveProgress(next,nextCovered,false);setTimeout(()=>speak(`Next we are learning ${plan.units[next].title}. ${verbalizeForSpeech(plan.units[next].why||plan.units[next].explain)}`),80)}else{setPhase('success');void saveProgress(unitIndex,nextCovered,true);setTimeout(()=>speak('You have now covered every required section in this topic map. The next step is independent practice to prove mastery.'),80)}}
 function speechText(){if(phase==='probe')return q?`Before we begin, solve this standard ${exam} question. ${q.prompt}`:'';if(phase==='teach'){const steps=buildBoardSteps(topic,lesson,unit,simple);const step=steps[Math.max(0,Math.min(boardStep,steps.length-1))];return step?(step.spoken||`${step.title}. ${step.body}`):''}if(phase==='example')return unit?`Now it is your turn to prove this section. ${verbalizeForSpeech(unit.check)} Take your time and answer the question on screen.`:verbalizeForSpeech(lesson.example);if(phase==='guided')return q?`Now try a different reviewed question on this topic. ${verbalizeForSpeech(q.prompt)}`:'';return `You have covered the required teaching sections for ${topic}. Now prove the learning independently with fresh questions.`}
 function speak(text=speechText()){if(!voiceSupported||!voiceEnabled||!text)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=rate;u.pitch=1;u.lang='en-NG';u.onstart=()=>{setSpeaking(true);setPaused(false)};u.onend=()=>{setSpeaking(false);setPaused(false)};u.onerror=()=>{setSpeaking(false);setPaused(false)};lastSpeech.current=text;window.speechSynthesis.speak(u)}
 function pauseResume(){if(!voiceSupported||!voiceEnabled)return;if(paused){setPaused(false);setTimeout(()=>speak(lastSpeech.current||speechText()),30);return}if(speaking||window.speechSynthesis.speaking){window.speechSynthesis.cancel();setSpeaking(false);setPaused(true)}}
 function stopVoice(){if(!voiceSupported)return;window.speechSynthesis.cancel();setSpeaking(false);setPaused(false)}
 function boardSpeech(index:number){const steps=buildBoardSteps(topic,lesson,unit,simple);const step=steps[Math.max(0,Math.min(index,steps.length-1))];return step?(step.spoken||`${step.title}. ${step.body}`):''}
 function toggleVoice(){if(voiceEnabled){stopVoice();setVoiceEnabled(false)}else{setVoiceEnabled(true);setPaused(false);setTimeout(()=>{const text=boardSpeech(boardStep);if(text){lastSpeech.current=text;const u=new SpeechSynthesisUtterance(text);u.rate=rate;u.pitch=1;u.lang='en-NG';u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(u)}},60)}}
 function previousBoardStep(){stopVoice();const next=Math.max(0,boardStep-1);setBoardStep(next);if(voiceEnabled)setTimeout(()=>speak(boardSpeech(next)),60)}
 function nextBoardStep(){stopVoice();const max=buildBoardSteps(topic,lesson,unit,simple).length-1;setBoardStep(v=>Math.min(max,v+1))}
 function slower(){setRate(r=>Math.max(.65,Number((r-.1).toFixed(2))));stopVoice()}
 function repeat(){speak(lastSpeech.current||speechText())}
 function listenForAnswer(){const w=window as any;const SR=w.SpeechRecognition||w.webkitSpeechRecognition;if(!SR){setError('Voice answers are not supported by this browser yet. You can still type or tap your answer.');return}try{const rec=new SR();rec.lang='en-NG';rec.interimResults=false;rec.maxAlternatives=1;setListening(true);rec.onresult=(e:any)=>{const text=String(e.results?.[0]?.[0]?.transcript||'').trim();if(text)setAnswer(text)};rec.onerror=()=>setError('I could not hear that clearly. Try again or type your answer.');rec.onend=()=>setListening(false);rec.start()}catch{setListening(false);setError('Voice input could not start. You can still type or tap your answer.')}}
 function askAvora(){
  const raw=studentQuestion.trim();if(!raw)return;
  const lower=raw.toLowerCase();
  const matchedTerm=unit?.terms?.find(([term]:[string,string])=>lower.includes(String(term).toLowerCase()));
  let reply='';
  if(matchedTerm){reply=`${matchedTerm[0]} means ${matchedTerm[1]}. ${unit?.example?`Let me connect it to this lesson: ${unit.example}`:''}`}
  else if(/cm|centimet|metre|meter|kg|kilogram|gram|millilit|litre|liter|unit|convert/.test(lower))reply='Let us make the units clear first. One metre equals one hundred centimetres. One kilogram equals one thousand grams. One litre equals one thousand millilitres. We convert before comparing quantities because the numbers only make sense when they represent the same unit.';
  else if(/why/.test(lower))reply=`Here is why this matters. ${unit?.why||plan?.why||unit?.explain||lesson.idea}`;
  else if(/example|show me/.test(lower))reply=`Yes. Let us use an example. ${unit?.example||lesson.example} I want you to follow the reason for each step, not just the final answer.`;
  else if(/again|simpler|understand|confus|don't understand|dont understand/.test(lower))reply=`Let us slow it down and rebuild the idea. ${unit?.explain||lesson.simple} ${unit?.prerequisites?.length?`The knowledge we need first is ${unit.prerequisites.join(', ')}.`:''}`;
  else reply=`Let us answer that from the exact section we are studying. ${unit?.explain||lesson.simple} ${unit?.example||''}`;
  setTeacherReply(reply);setStudentQuestion('');stopVoice();setTimeout(()=>speak(reply),80)
 }
 async function check(kind:'probe'|'guided'|'section'){if(!q||!answer.trim())return;setChecking(true);setError('');try{const r=await fetch('/api/tutor/check',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({questionId:q.id,answer})});const d=await readApiJson(r,'Answer check');setFeedback(d);if(kind==='probe'){setPhase('teach');setAnswer('');setTimeout(()=>speak(d.correct?`Good start. You can solve this question, but we will still cover the full ${topic} map required for ${exam}, moving faster through what you already know.`:`This answer shows a gap we can fix. We will begin from the core idea, then cover the rest of ${topic} in order.`),100)}else if(d.correct&&kind==='guided'){setPhase('example');setAnswer('');setFeedback(null);setTimeout(()=>speak('Good. Now I want you to prove this section once more before we move on.'),100)}else if(d.correct&&kind==='section'){setFeedback(d);setTimeout(()=>{goNextUnit()},900)}}catch(e:any){setError(e.message||'Could not check that answer.')}finally{setChecking(false)}}
 if(loading)return <section className="tutor-loading"><b>AVORA is preparing your complete lesson…</b><span>Checking the topic map, reviewed questions and your saved position.</span></section>;
 if(error&&!topic)return <section className="tutor-error"><b>AVORA Tutor could not prepare your topics.</b><p>{error}</p><button onClick={()=>load('')}>Try again</button></section>;
 if(!topic)return <section className="tutor-picker"><div className="purpose-strip"><b>You choose the topic. AVORA covers what your class and exam expect you to know.</b><p>Every topic follows a complete map: concepts, terms, methods, worked examples, guided practice and independent proof.</p></div><div className="topic-pick-grid">{topics.map((t,i)=><button key={t.name} onClick={()=>choose(t.name)}><span>{String(i+1).padStart(2,'0')}</span><div><b>{t.name}</b><small>{t.questions>0?`${t.questions} reviewed questions available`:'Academic lesson ready · question bank expansion pending'}</small></div><i>Learn →</i></button>)}</div></section>;
 if(error&&!probeQ)return <section className="tutor-error"><b>We could not open this lesson.</b><p>{error}</p><button onClick={()=>load(topic)}>Retry this topic</button><button onClick={()=>setTopic('')}>Choose another topic</button></section>;
 if(!probeQ)return <section className="tutor-error"><b>No reviewed question is available for this lesson yet.</b><button onClick={()=>setTopic('')}>Choose another topic</button></section>;
 const canVoiceAnswer=typeof window!=='undefined'&&Boolean((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition);
 return <section className="tutor-experience">
  <div className="tutor-breadcrumb"><Link href="/home">Home</Link><span>›</span><button onClick={()=>{setTopic('');router.replace('/tutor')}}>Topics</button><span>›</span><b>{topic}</b></div>
  <div className="lesson-context"><div><span>COMPLETE PERSONAL LESSON</span><h2>{topic}</h2><p>{exam} · {classLevel} · {probeQ.skill}. AVORA preserves the full topic map while adapting the pace to your evidence.</p></div><button onClick={()=>{setTopic('');router.replace('/tutor')}}>Change topic</button></div>
  {recoveryTopics.length>0&&<div className="exam-recovery-strip"><div><span>EXAM RECOVERY PATH</span><b>{recoveryIndex+1} of {recoveryTopics.length}: {topic}</b><small>Finish this topic’s teaching and independent proof before AVORA guides you to the next weak area.</small></div><div>{recoveryTopics.map((t,i)=><i key={t} className={i<recoveryIndex?'done':i===recoveryIndex?'active':''}>{i+1}</i>)}</div></div>}
  {plan&&<section className="topic-complete-map"><div className="topic-map-head"><div><span>COMPLETE {exam} TOPIC MAP · {classLevel}</span><h3>Everything required is visible. Nothing important is silently skipped.</h3><p>{plan.goal} {plan.why}</p></div><b>{coveredUnits.length}/{plan.units.length} covered</b></div><div className="topic-unit-tabs">{plan.units.map((u,i)=><button key={u.title} className={`${i===unitIndex?'active ':''}${coveredUnits.includes(i)?'covered':''}`} onClick={()=>{setUnitIndex(i);setPhase('teach')}}><span>{coveredUnits.includes(i)?'✓':String(i+1).padStart(2,'0')}</span><b>{u.title}</b></button>)}</div><div className="topic-map-rule"><b>Academic rule</b><span>Meaning → terms → method/reasoning → worked example → section check → different reviewed question → independent fresh evidence. Correct early answers may increase pace, but never delete required coverage.</span></div></section>}

  <div className="natural-tutor"><aside className="tutor-lesson-rail"><span>LEARNING ROUTE</span><ol><li className={phase==='probe'?'active':'done'}>Standard skill check</li><li className={phase==='teach'?'active':''}>Teach core + terms</li><li className={phase==='guided'?'active':''}>Different guided question</li><li className={phase==='example'?'active':''}>Section understanding check</li><li className={phase==='success'?'active':''}>Independent proof</li></ol><p>Coverage and mastery are different. AVORA records teaching coverage, but only independent answers can prove mastery.</p></aside>
   <article className="natural-conversation"><div className="tutor-speaker"><span>A</span><div><b>AVORA Tutor</b><small>{q?.skill||probeQ.skill}</small></div></div>
    {phase==='probe'&&<div className="tutor-turn"><span>START WITH WHAT THE EXAM EXPECTS</span><h2>{probeQ.prompt}</h2><p>This is a standard reviewed question. It helps AVORA judge pace; it does not replace the rest of the topic.</p>{probeQ.type==='MULTIPLE_CHOICE'&&probeQ.options.length?<div className="probe-options">{probeQ.options.map((x,i)=><button key={`${x}-${i}`} className={answer===x?'chosen':''} onClick={()=>setAnswer(x)}><b>{String.fromCharCode(65+i)}</b><span>{x}</span></button>)}</div>:<input className="guided-input" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer"/>}<div className="probe-submit-row">{canVoiceAnswer&&<button className="voice-answer" onClick={listenForAnswer}>{listening?'Listening…':'🎙 Speak answer'}</button>}<button className="check-answer" disabled={!answer||checking} onClick={()=>check('probe')}>{checking?'Checking…':'Check and begin lesson'}</button></div>{feedback&&<div className="coach-feedback"><b>{feedback.correct?'Strong start.':'We found something to teach.'}</b><p>{feedback.correct?feedback.explanation:feedback.hint}</p></div>}</div>}
    {phase==='teach'&&<div className="tutor-turn"><span>REQUIRED SECTION {unitIndex+1}{plan?` OF ${plan.units.length}`:''}</span><h2>{unit?.title||(simple?lesson.simple:lesson.idea)}</h2>{unit&&<div className="lesson-purpose-card"><div><small>WHY YOU ARE LEARNING THIS</small><p>{unit.why||`This section builds a required part of ${topic} and prepares you for exam-style questions that depend on the same idea.`}</p></div>{unit.prerequisites?.length?<div><small>WHAT YOU NEED FIRST</small><p>{unit.prerequisites.join(' · ')}</p></div>:null}{unit.outcomes?.length?<div><small>BY THE END, YOU SHOULD BE ABLE TO</small><ul>{unit.outcomes.map((x:string)=><li key={x}>{x}</li>)}</ul></div>:null}</div>}<p className="teacher-mode-note">Watch and listen. AVORA will teach this section on the board at a natural pace, explain unfamiliar terms before using them, and pause only when your participation matters.</p>{showVisual&&<TutorWhiteboard topic={topic} lesson={lesson} simple={simple} unit={unit} stepIndex={boardStep} voiceEnabled={voiceEnabled} speaking={speaking} paused={paused} rate={rate} voiceSupported={voiceSupported} onToggleVoice={toggleVoice} onHear={()=>speak()} onPauseResume={pauseResume} onRepeat={repeat} onSlower={slower} onStop={stopVoice} onPrevious={previousBoardStep} onNext={nextBoardStep} onLessonComplete={()=>{setAnswer('');setFeedback(null);setPhase('guided')}}/>}</div>}
    {phase==='guided'&&guidedQ&&<div className="tutor-turn guided-problem"><span>GUIDED PRACTICE · FRESH QUESTION</span><h2>{guidedQ.prompt}</h2><p className="solve-note">This is deliberately different from the opening probe. Use the idea you just learned; AVORA gives help only if needed.</p>{guidedQ.type==='MULTIPLE_CHOICE'&&guidedQ.options.length?<div className="guided-options">{guidedQ.options.map((o,i)=><button className={answer===o?'selected':''} key={`${o}-${i}`} onClick={()=>{setAnswer(o);setFeedback(null)}}><b>{String.fromCharCode(65+i)}</b><span>{o}</span></button>)}</div>:<input className="guided-input" value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback(null)}} placeholder="Type your answer"/>}{feedback&&!feedback.correct&&<div className="tutor-clue"><b>Not yet — stay on this idea.</b><p>{feedback.hint}</p><small>Use the clue, change your answer and try again.</small></div>}{error&&<p className="flow-error">{error}</p>}<div className="guided-controls">{canVoiceAnswer&&<button onClick={listenForAnswer}>{listening?'Listening…':'🎙 Speak answer'}</button>}<button onClick={()=>setPhase('teach')}>Explain again</button><button className="check-answer" disabled={!answer||checking} onClick={()=>check('guided')}>{checking?'Checking…':'Check my answer'}</button></div></div>}
    {phase==='example'&&sectionQ&&<div className="tutor-turn section-proof"><span>YOUR TURN · SECTION CHECK</span><p className="section-check-prompt">{unit?.check||'Show me that this part now makes sense.'}</p><h2>{sectionQ.prompt}</h2><p>Take your time. AVORA will mark the answer and will not move on if this idea still needs teaching.</p>{sectionQ.type==='MULTIPLE_CHOICE'&&sectionQ.options.length?<div className="guided-options">{sectionQ.options.map((o,i)=><button className={answer===o?'selected':''} key={`${o}-${i}`} onClick={()=>{setAnswer(o);setFeedback(null)}}><b>{String.fromCharCode(65+i)}</b><span>{o}</span></button>)}</div>:<input className="guided-input" value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback(null)}} placeholder="Type your answer here…"/>}{feedback&&!feedback.correct&&<div className="tutor-clue"><b>We are staying on this idea.</b><p>{feedback.hint}</p><small>AVORA will explain it again before you retry.</small></div>}{feedback?.correct&&<div className="coach-feedback good"><b>Yes — that shows the section is understood.</b><p>{feedback.explanation}</p></div>}<div className="guided-controls"><button onClick={()=>{setPhase('teach');setBoardStep(0);setFeedback(null)}}>Explain this again</button><button className="check-answer" disabled={!answer||checking} onClick={()=>check('section')}>{checking?'Marking…':'Check my answer'}</button></div></div>}
    {phase==='success'&&<div className="tutor-turn"><span>TEACHING COVERAGE COMPLETE</span><h2>{topic} has been taught across the required {exam} map.</h2><div className="tutor-success"><b>{plan?`${coveredUnits.length} of ${plan.units.length} required sections covered.`:'Required teaching covered.'}</b><p>This is not yet a mastery claim. AVORA now needs fresh independent evidence without hints or Tutor assistance.</p></div><div className="proof-actions"><Link href={'/practice?topic='+encodeURIComponent(topic)}>Start independent proof</Link>{nextRecovery&&<button onClick={()=>router.push('/tutor?topic='+encodeURIComponent(nextRecovery)+'&recovery='+encodeURIComponent(recoveryTopics.join('|'))+'&from=exam')}>After proof: next weak topic is {nextRecovery}</button>}</div></div>}
   <section className="ask-avora-dock"><div><span>ASK YOUR TEACHER</span><b>Stop me anywhere you do not understand.</b></div>{teacherReply&&<div className="teacher-reply"><span>AVORA</span><p>{teacherReply}</p></div>}<div className="ask-row"><input id="ask-avora-input" value={studentQuestion} onChange={e=>setStudentQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')askAvora()}} placeholder="Ask: Why did you divide by 2? What does cm mean? Show another example…"/><button onClick={askAvora} disabled={!studentQuestion.trim()}>Ask</button></div></section>
   </article></div>
  <div className="trust-note"><b>Trust standard</b><p>AVORA shows the required topic map, explains core ideas and terminology, uses different questions for checking and guided practice, preserves teaching progress, and keeps assisted learning separate from independent mastery evidence.</p></div>
 </section>
}
