'use client'; import React from 'react';
const W=({q,children}:{q:string;children:React.ReactNode})=><div className="fraction-working"><div className="example-question"><span>WORKED EXAMPLE</span><strong>{q}</strong></div><div className="math-stack">{children}</div></div>; const L=({children,strong=false}:{children:React.ReactNode;strong?:boolean})=><div className={strong?'math-line math-result':'math-line'}>{children}</div>;
export default function UseOfSymbolsLesson({onExercise}:{onExercise:()=>void}){return <article className="wn-lesson fractions-premium-lesson"><header className="wn-hero"><span>JSS1 MATHEMATICS · ALGEBRAIC PROCESSES</span><h1>Use of Symbols</h1><p>Solve open sentences, connect inverse operations, and replace boxes or shapes with letters.</p></header>
<section className="wn-objectives"><h2>NERDC-Aligned Objectives</h2><ul><li>Solve open sentences.</li><li>Identify the relationship between addition and subtraction.</li><li>Identify the relationship between multiplication and division.</li><li>Use letters to represent boxes or shapes.</li><li>Solve open sentences with two operations.</li><li>Translate and solve word problems involving symbols.</li><li>Solve quantitative-aptitude problems.</li></ul></section>
<section className="wn-section"><h3>1. Open Sentences</h3><p>An open sentence contains an unknown value. The correct replacement makes the sentence true.</p><W q="Find the missing value: box − 5 = 8."><L>Undo subtraction by adding 5.</L><L>box = 8 + 5</L><L strong>box = 13</L><L>Check: 13 − 5 = 8.</L></W></section>
<section className="wn-section"><h3>2. Addition and Subtraction Are Inverses</h3><W q="Solve 7 + box = 11."><L>Undo +7 using −7.</L><L>box = 11 − 7</L><L strong>box = 4</L><L>Check: 7 + 4 = 11.</L></W><div className="lesson-rule"><span>7 + 4 = 11</span><span>11 − 7 = 4</span><span>11 − 4 = 7</span></div></section>
<section className="wn-section"><h3>3. Multiplication and Division Are Inverses</h3><W q="Solve shape × 3 = 12."><L>Undo ×3 using ÷3.</L><L>shape = 12 ÷ 3</L><L strong>shape = 4</L><L>Check: 4 × 3 = 12.</L></W><div className="lesson-rule"><span>4 × 3 = 12</span><span>12 ÷ 3 = 4</span><span>12 ÷ 4 = 3</span></div></section>
<section className="wn-section"><h3>4. Replace a Shape With a Letter</h3><div className="math-working"><L>2 + box = 11</L><L>Replace box by n: 2 + n = 11</L><L>n = 11 − 2</L><L strong>n = 9</L></div><p>The letter does not change the mathematics; it gives the unknown a convenient name.</p></section>
<section className="wn-section"><h3>5. Unknown in Different Positions</h3><W q="Solve 15 − x = 9."><L>What must be removed from 15 to leave 9?</L><L>x = 15 − 9</L><L strong>x = 6</L><L>Check: 15 − 6 = 9.</L></W><W q="Solve 24 ÷ y = 6."><L>24 divided by what gives 6?</L><L>y = 24 ÷ 6</L><L strong>y = 4</L></W></section>
<section className="wn-section"><h3>6. Two Operations</h3><W q="Solve 2x − 1 = 7."><L>Undo −1: 2x = 8.</L><L>Undo ×2: x = 8 ÷ 2.</L><L strong>x = 4</L><L>Check: 2(4) − 1 = 7.</L></W><W q="Solve x ÷ 2 + 3 = 8."><L>Undo +3: x ÷ 2 = 5.</L><L>Undo ÷2: x = 10.</L><L strong>x = 10</L><L>Check: 10 ÷ 2 + 3 = 8.</L></W></section>
<section className="wn-section"><h3>7. Word Problem</h3><W q="A number is doubled and 3 is added. The result is 17. Find the number."><L>Let the number be n.</L><L>2n + 3 = 17.</L><L>2n = 14.</L><L strong>n = 7</L><L>Check: 2(7) + 3 = 17.</L></W></section>
<section className="wn-section"><h3>8. Quantitative Aptitude</h3><W q="If the same shape appears twice and shape + shape + 4 = 18, find the shape."><L>Let the shape be n.</L><L>n + n + 4 = 18.</L><L>2n = 14.</L><L strong>n = 7</L></W></section>
<section className="wn-section"><h3>9. Common Mistakes</h3><div className="lesson-rule"><span>The same symbol in one problem has the same value.</span><span>Use inverse operations to undo operations.</span><span>With two operations, undo in reverse order.</span><span>Substitute the answer back to check.</span><span>Do not turn this topic into comparison signs; its focus is open sentences and placeholders.</span></div></section>
<div className="teacher-actions"><button className="primary" onClick={onExercise}>Go to Exercise →</button></div></article>}