'use client';import {useEffect,useRef,useState} from 'react';import {useRouter} from 'next/navigation';
type Q={id:string;number:number;subject:string;topic:string;prompt:string;type:string;options:string[]};
export default function WeeklyExamRunner({examId}:{examId:string}){const router=useRouter(),[paper,setPaper]=useState<any>(null),[i,setI]=useState(0),[answers,setAnswers]=useState<Record<string,string>>({}),[left,setLeft]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');const finishRef=useRef<()=>void>(()=>{});
 useEffect(()=>{(async()=>{setBusy(true);try{let r=await fetch('/api/weekly-exam/'+examId+'/start',{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not start weekly exam.');r=await fetch('/api/weekly-exam/session/'+d.sessionId,{cache:'no-store'});d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load weekly exam.');setPaper(d);setAnswers(d.answers||{});const elapsed=Math.floor((Date.now()-new Date(d.startedAt).getTime())/1000);setLeft(Math.max(0,Number(d.durationSeconds)-elapsed))}catch(e:any){setError(e.message)}finally{setBusy(false)}})()},[examId]);
 useEffect(()=>{finishRef.current=finish});useEffect(()=>{if(!paper)return;const t=setInterval(()=>setLeft(x=>{if(x<=1){clearInterval(t);finishRef.current();return 0}return x-1}),1000);return()=>clearInterval(t)},[paper]);
 async function save(q:Q,a:string){setAnswers(v=>({...v,[q.id]:a}));const r=await fetch('/api/weekly-exam/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:paper.sessionId,questionId:q.id,answer:a})});if(!r.ok){const d=await r.json();setError(d.error||'Answer did not sync.');return false}setError('');return true}
 async function move(n:number){const q=paper.questions[i],a=answers[q.id];if(a&&!await save(q,a))return;setI(n)}
 async function finish(){if(!paper||busy)return;setBusy(true);try{const q=paper.questions[i],a=answers[q.id];if(a&&!await save(q,a))throw new Error('Current answer did not sync.');const r=await fetch('/api/weekly-exam/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:paper.sessionId})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not submit.');router.replace('/weekly-exam/result/'+paper.sessionId)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(busy&&!paper)return <main className="shell"><p>Preparing your locked weekly paper…</p></main>;if(error&&!paper)return <main className="shell"><h1>Weekly exam</h1><p className="exam-error">{error}</p></main>;if(!paper)return null;const q:Q=paper.questions[i],mm=String(Math.floor(left/60)).padStart(2,'0'),ss=String(left%60).padStart(2,'0');
 return <main className="exam-session weekly-exam-session"><header className="exam-bar"><div><strong>{paper.title}</strong><span>Question {i+1} of {paper.questions.length}</span></div><time>{mm}:{ss}</time><button disabled={busy} onClick={finish}>Submit</button></header><div className="exam-work"><aside className="question-nav"><strong>Questions</strong><div>{paper.questions.map((x:Q,n:number)=><button key={x.id} className={(n===i?'active ':'')+(answers[x.id]?'answered':'')} onClick={()=>move(n)}>{n+1}</button>)}</div></aside><section className="exam-question"><div className="exam-topic">{q.subject} · {q.topic}</div><h1>{q.prompt}</h1>{q.type==='MULTIPLE_CHOICE'?<div className="exam-options">{q.options.map((o,j)=><button key={o} className={answers[q.id]===o?'chosen':''} onClick={()=>setAnswers(v=>({...v,[q.id]:o}))}><b>{String.fromCharCode(65+j)}</b><span>{o}</span></button>)}</div>:<div className="exam-input"><label>Your answer</label><textarea rows={8} value={answers[q.id]||''} onChange={e=>setAnswers(v=>({...v,[q.id]:e.target.value}))}/></div>}{error&&<p className="exam-error">{error}</p>}<footer><span>Answers sync as you move between questions.</span><div><button disabled={i===0||busy} onClick={()=>move(i-1)}>Previous</button>{i===paper.questions.length-1?<button className="next" disabled={busy} onClick={finish}>{busy?'Submitting…':'Submit weekly exam'}</button>:<button className="next" disabled={busy} onClick={()=>move(i+1)}>Next</button>}</div></footer></section></div></main>}