'use client';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
export default function WeeklyExamCreateForm({scope}:{scope:any[]}){
 const router=useRouter();const [classLevel,setClassLevel]=useState('JSS3'),[term,setTerm]=useState(1),[week,setWeek]=useState(1),[title,setTitle]=useState('AVORA Weekly Assessment'),[count,setCount]=useState(40),[duration,setDuration]=useState(60),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const available=useMemo(()=>scope.filter(x=>x.class_level===classLevel&&Number(x.term)===term&&Number(x.week_number)===week&&Number(x.approved_objectives)>0),[scope,classLevel,term,week]);
 function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/admin/weekly-exams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classLevel,term,week,title,questionCount:count,durationMinutes:duration,scheduleIds:selected})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create blueprint.');router.push('/admin/weekly-exams/'+d.id);router.refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="weekly-blueprint-form"><div className="school-work-fields"><label>Class<select value={classLevel} onChange={e=>{setClassLevel(e.target.value);setSelected([])}}><option>JSS1</option><option>JSS2</option><option>JSS3</option></select></label><label>Term<select value={term} onChange={e=>{setTerm(Number(e.target.value));setSelected([])}}><option value="1">Term 1</option><option value="2">Term 2</option><option value="3">Term 3</option></select></label><label>Week<input type="number" min="1" max="20" value={week} onChange={e=>{setWeek(Number(e.target.value));setSelected([])}}/></label><label>Exam title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Questions<input type="number" min="5" max="100" value={count} onChange={e=>setCount(Number(e.target.value))}/></label><label>Duration (minutes)<input type="number" min="10" max="240" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label></div><header><span className="section-kicker">VERIFIED WEEKLY SCOPE</span><h2>What did learners actually cover?</h2><p>Only schedules with reviewed/live daily objectives can be selected.</p></header>{available.length?<div className="weekly-scope-options">{available.map(x=><label key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/><span><b>{x.subject_name}</b><strong>{x.curriculum_topic_id}</strong><small>{x.approved_objectives} approved daily objectives</small></span></label>)}</div>:<div className="admin-empty"><b>No approved academic scope for this week.</b><p>Do not generate an exam yet. Complete and approve the week's objectives first.</p></div>}{error&&<p className="form-error">{error}</p>}<button className="premium-primary" disabled={busy||selected.length===0} onClick={save}>{busy?'Saving blueprint…':'Save academic blueprint →'}</button></section>;
}