import {getSession} from '@/lib/auth';
import {requireStudentLearningAccess} from '@/lib/learningAccess';
import {redirect} from 'next/navigation';
import {sql,withDbRetry} from '@/lib/db';
import {subjectSlug,subjectLabel} from '@/lib/subjects';
import Link from 'next/link';

function state(score:number,evidence:number,status?:string){if(status)return status.replaceAll('_',' ');if(!evidence)return 'Not assessed';if(evidence<3)return 'Early evidence';if(score>=.8&&evidence>=7)return 'Mastered';if(score>=.65)return 'Practising';if(score>=.4)return 'Developing';return 'Needs teaching'}
function confidence(evidence:number,label?:string){if(label)return label.toLowerCase().replace(/^./,c=>c.toUpperCase())+' evidence';if(evidence>=10)return 'Strong evidence';if(evidence>=6)return 'Good evidence';if(evidence>=3)return 'Building evidence';if(evidence>0)return 'Early evidence';return 'No evidence yet'}

export const dynamic='force-dynamic';
export default async function ProgressPage(){
 const s=await getSession();if(!s)redirect('/login');
 await requireStudentLearningAccess(s);
 const [p]=await withDbRetry(()=>sql`SELECT target_exam,preferred_subject,class_level FROM student_profiles WHERE user_id=${s.userId}`);
 const subSlug=subjectSlug(p?.preferred_subject),subject=subjectLabel(p?.preferred_subject),exam=p?.target_exam||'BECE';
 const [rows,tutorRows,plans,examRows,interactionRows]=await Promise.all([
  withDbRetry(()=>sql`SELECT sk.id,sk.name skill,t.name topic,COALESCE(m.score,0)::float score,COALESCE(m.evidence_count,0)::int evidence,m.last_practiced_at,lsi.status insight_status,lsi.confidence insight_confidence,lsi.misconception_note,lsi.prerequisite_gap,lsi.independent_accuracy::float,lsi.independent_evidence FROM skills sk JOIN topics t ON t.id=sk.topic_id JOIN subjects sub ON sub.id=t.subject_id LEFT JOIN mastery m ON m.skill_id=sk.id AND m.student_id=${s.userId} LEFT JOIN learner_skill_insights lsi ON lsi.skill_id=sk.id AND lsi.student_id=${s.userId} WHERE sub.slug=${subSlug} AND EXISTS(SELECT 1 FROM questions q WHERE q.skill_id=sk.id AND q.status='PUBLISHED' AND (q.exam_name=${exam} OR q.exam_name IS NULL)) ORDER BY CASE WHEN COALESCE(m.evidence_count,0)=0 THEN 1 ELSE 0 END,COALESCE(m.score,0),t.order_index`),
  withDbRetry(()=>sql`SELECT topic_name,current_unit,covered_units,coverage_complete,checkpoint_attempts,checkpoint_successes,last_unit_title,last_interaction_at FROM tutor_topic_progress WHERE student_id=${s.userId} AND exam_name=${exam} AND subject_slug=${subSlug} ORDER BY updated_at DESC`),
  withDbRetry(()=>sql`SELECT recommended_topic,recommended_skill,plan_reason,weak_topics,created_at FROM remediation_plans WHERE student_id=${s.userId} AND exam_name=${exam} AND subject_name=${subject} AND status='ACTIVE' ORDER BY created_at DESC LIMIT 1`),
  withDbRetry(()=>sql`SELECT score::float,assessment_type,submitted_at,topic_focus FROM exam_sessions WHERE student_id=${s.userId} AND exam_name=${exam} AND subject_name=${subject} AND status='COMPLETED' ORDER BY submitted_at DESC LIMIT 5`),
  withDbRetry(()=>sql`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE interaction_kind='CHECKPOINT')::int checkpoints,COUNT(*) FILTER(WHERE interaction_kind='QUESTION')::int questions FROM tutor_interactions WHERE student_id=${s.userId} AND exam_name=${exam} AND subject_slug=${subSlug}`)
 ]);
 const attempted=rows.filter((x:any)=>Number(x.evidence)>0),mastered=attempted.filter((x:any)=>state(Number(x.score),Number(x.evidence),x.insight_status)==='MASTERED'||state(Number(x.score),Number(x.evidence),x.insight_status)==='Mastered').length,needs=attempted.filter((x:any)=>String(x.insight_status||'').includes('NEEDS')||Number(x.score)<.4).length,avg=attempted.length?Math.round(attempted.reduce((a:number,x:any)=>a+Number(x.score),0)/attempted.length*100):null;
 const coverage=tutorRows.filter((x:any)=>x.coverage_complete).length,latestPlan:any=plans[0],interaction:any=interactionRows[0]||{};
 const observed=attempted.reduce((n:number,x:any)=>n+Number(x.evidence||0),0);
 return <main className="shell page progress-v9">
  <header className="evidence-hero-v9"><div><span className="eyebrow">AVORA LEARNING EVIDENCE · {p?.class_level||'JSS'} · {exam}</span><h1>What the learner understands — and what still needs teaching.</h1><p>This record separates lessons completed from independent proof. It is designed to be understandable to the learner, a parent and a teacher.</p></div><div className="evidence-hero-score"><strong>{avg===null?'—':`${avg}%`}</strong><span>demonstrated mastery</span><small>{observed} independent answers observed</small></div></header>

  <section className="evidence-summary-v9"><div><strong>{mastered}</strong><span>skills mastered</span><small>Requires repeated independent evidence</small></div><div><strong>{needs}</strong><span>need teaching</span><small>Not treated as failure — these are next priorities</small></div><div><strong>{coverage}</strong><span>topics fully taught</span><small>Tutor coverage, separate from mastery</small></div><div><strong>{Number(interaction.checkpoints||0)}</strong><span>Tutor checkpoints</span><small>Places AVORA stopped and waited for participation</small></div></section>

  {latestPlan&&<section className="remediation-card-v9"><div><span>NEXT TEACHING PLAN</span><h2>{latestPlan.recommended_topic}</h2><p>{latestPlan.plan_reason}</p></div><Link href={'/tutor?topic='+encodeURIComponent(latestPlan.recommended_topic)+'&subject='+encodeURIComponent(subject)+'&from=progress'}>Teach this weakness →</Link></section>}

  <section className="progress-explain"><b>AVORA's evidence rule</b><p>A lesson can be <strong>covered</strong> without being mastered. Guided Tutor work helps understanding, but <strong>Mastered</strong> requires repeated independent evidence from practice/exams. One wrong answer never labels a learner permanently.</p></section>

  <section className="skill-evidence-v9"><header><div><span>SKILL EVIDENCE</span><h2>{subject}</h2></div><p>Misconceptions appear only when AVORA has evidence that a particular error pattern may be affecting performance.</p></header><div className="skill-evidence-list-v9">{rows.map((x:any)=>{const ev=Number(x.evidence),sc=Number(x.score),st=state(sc,ev,x.insight_status);return <article key={x.id}><div className="skill-evidence-name"><small>{x.topic}</small><b>{x.skill}</b>{x.misconception_note&&<p><strong>AVORA noticed:</strong> {x.misconception_note}</p>}</div><div><span>Evidence</span><b>{ev?`${ev} answers`:'Not attempted'}</b><small>{confidence(ev,x.insight_confidence)}</small></div><div><span>Mastery</span><b>{ev?`${Math.round(sc*100)}%`:'—'}</b><small>{st}</small></div><div className="skill-action-v9"><Link href={'/tutor?topic='+encodeURIComponent(x.topic)+'&subject='+encodeURIComponent(subject)+'&from=progress'}>Teach / review →</Link></div></article>})}</div></section>

  <section className="evidence-grid-v9"><div className="evidence-panel-v9"><span>TEACHING RECORD</span><h3>What AVORA has actually taught</h3>{tutorRows.length?tutorRows.slice(0,8).map((x:any)=><div className="evidence-mini-row" key={x.topic_name}><div><b>{x.topic_name}</b><small>{x.last_unit_title||'Topic lesson'}</small></div><strong>{x.coverage_complete?'Covered':`${Array.isArray(x.covered_units)?x.covered_units.length:0} sections`}</strong></div>):<p>No Tutor teaching has been recorded yet.</p>}</div><div className="evidence-panel-v9"><span>RECENT ASSESSMENT</span><h3>Independent exam evidence</h3>{examRows.length?examRows.map((x:any,i:number)=><div className="evidence-mini-row" key={i}><div><b>{String(x.assessment_type||'Assessment').replaceAll('_',' ')}</b><small>{x.topic_focus||subject}</small></div><strong>{Math.round(Number(x.score||0)*100)}%</strong></div>):<p>No completed assessment yet.</p>}</div></section>

  <section className="trust-strip"><div><span>FOR PARENTS & TEACHERS</span><h3>No fake mastery. No punishment for learning slowly.</h3></div><p>Use this page to see what has been taught, what has been independently demonstrated, what AVORA thinks may be causing errors, and what it recommends next. It is evidence, not a label on the child.</p></section>
  <div className="progress-next"><div><span>NEXT ACTION</span><h3>{latestPlan?`Repair ${latestPlan.recommended_topic}`:'Continue building evidence.'}</h3><p>Use Tutor for teaching. Use Practice or Exam to prove the skill independently.</p></div><div><Link href={latestPlan?'/tutor?topic='+encodeURIComponent(latestPlan.recommended_topic)+'&subject='+encodeURIComponent(subject)+'&from=progress':'/tutor'}>Learn with Tutor</Link><Link href="/exam">Take an assessment</Link></div></div>
 </main>
}
