export type DeepExample={title:string;problem:string;steps:string[];why:string;check:string};

const banks:Record<string,DeepExample[]>={
 'simultaneous equations':[
  {title:'Example 1 — eliminate a variable immediately',problem:'Solve x + y = 9 and x - y = 3.',steps:['Write the equations one under the other: x + y = 9; x - y = 3.','Add the equations. +y and -y cancel, so 2x = 12.','Divide both sides by 2: x = 6.','Put x = 6 into x + y = 9: 6 + y = 9, so y = 3.','Check both originals: 6 + 3 = 9 and 6 - 3 = 3. Both are true.'],why:'We add because the y-coefficients are opposites. The aim of elimination is to make one unknown disappear without changing the solution.',check:'Why was addition better than subtraction in this example?'},
  {title:'Example 2 — matching coefficients',problem:'Solve 2x + y = 13 and x + y = 8.',steps:['The y-coefficients are both +1. Subtract the second equation from the first.','(2x + y) - (x + y) = 13 - 8, so x = 5.','Substitute x = 5 into x + y = 8: 5 + y = 8.','Therefore y = 3.','Check: 2(5) + 3 = 13 and 5 + 3 = 8.'],why:'Subtracting equal y-terms gives y - y = 0. We choose the operation because of the coefficients, not by guessing.',check:'If both y-terms had been -y, would addition or subtraction eliminate y?'},
  {title:'Example 3 — multiply before eliminating',problem:'Solve 2x + y = 11 and x + 2y = 13.',steps:['No variable cancels immediately, so first make one pair of coefficients equal.','Multiply the first equation by 2: 4x + 2y = 22.','Subtract x + 2y = 13: 3x = 9, so x = 3.','Substitute x = 3 into 2x + y = 11: 6 + y = 11, so y = 5.','Check in the second equation: 3 + 2(5) = 13.'],why:'Multiplying an entire equation by the same non-zero number creates an equivalent equation. That lets us deliberately create coefficients that cancel.',check:'Why must every term on the first equation be multiplied by 2?'},
  {title:'Example 4 — substitution method',problem:'Solve y = 2x + 1 and x + y = 10.',steps:['The first equation already tells us what y equals.','Replace y in the second equation with 2x + 1: x + (2x + 1) = 10.','Collect like terms: 3x + 1 = 10, so 3x = 9 and x = 3.','Use y = 2x + 1: y = 2(3) + 1 = 7.','Check: 3 + 7 = 10.'],why:'Substitution works because both occurrences of y represent the same unknown value.',check:'What made substitution especially convenient here?'},
  {title:'Example 5 — word problem',problem:'Two exercise books and one pen cost ₦1,100. One exercise book and two pens cost ₦1,000. Find each price.',steps:['Let b be the price of one book and p the price of one pen.','Translate the statements: 2b + p = 1100 and b + 2p = 1000.','Multiply the second equation by 2: 2b + 4p = 2000.','Subtract the first equation: 3p = 900, so p = ₦300.','Substitute into b + 2p = 1000: b + 600 = 1000, so b = ₦400.','Check the story: 2(400)+300=1100 and 400+2(300)=1000.'],why:'The hardest part of many exam questions is translating words into equations. Define the unknowns before calculating.',check:'What two equations would represent 3 books + 1 pen = ₦1,500 and 1 book + 1 pen = ₦700?'}
 ],
 'fractions, decimals and percentages':[
  {title:'Example 1 — connect the three forms',problem:'Write 3/5 as a decimal and a percentage.',steps:['A fraction is division, so calculate 3 ÷ 5 = 0.6.','A percentage means “out of 100”. Multiply the decimal by 100: 0.6 × 100 = 60.','Therefore 3/5 = 0.6 = 60%.'],why:'Fraction, decimal and percentage are different ways of naming the same value.',check:'What fraction and decimal are equal to 25%?'},
  {title:'Example 2 — percentage of a quantity',problem:'Find 15% of ₦4,000.',steps:['15% means 15/100.','Write the calculation: 15/100 × 4000.','Simplify 4000 ÷ 100 = 40.','Then 15 × 40 = 600.','So 15% of ₦4,000 is ₦600.'],why:'“Of” tells us to multiply. Converting the percentage to a fraction makes the meaning visible.',check:'Find 12% of ₦5,000 and explain each step.'}
 ],
 'linear equations':[
  {title:'Example 1 — preserve the balance',problem:'Solve 3x + 5 = 20.',steps:['Our goal is to leave x alone. The +5 is attached after 3x.','Undo +5 by subtracting 5 from both sides: 3x = 15.','Undo ×3 by dividing both sides by 3: x = 5.','Check in the original: 3(5)+5 = 20.'],why:'An equation is a balance. Whatever operation we apply to one side must also be applied to the other side.',check:'Solve 5x - 7 = 18 and check your answer.'}
 ],
 'concord':[
  {title:'Example 1 — singular subject',problem:'Choose: The boy (walk/walks) to school every day.',steps:['Find the subject: “The boy”.','Ask whether the subject is singular or plural. “Boy” is one person, so it is singular.','In the simple present tense, a third-person singular subject normally takes a verb ending in -s/-es.','Therefore: The boy walks to school every day.'],why:'Concord means agreement. The form of the verb must agree with the subject.',check:'Which is correct: “My sister cook” or “My sister cooks”? Why?'},
  {title:'Example 2 — do not be distracted by a nearby noun',problem:'Choose: The box of books (is/are) heavy.',steps:['Find the true subject before choosing the verb.','The subject is “box”, not “books”. “of books” only tells us what is inside the box.','“Box” is singular, so use “is”.','Correct sentence: The box of books is heavy.'],why:'A noun close to the verb can distract you. Agreement is with the grammatical subject, not simply the nearest noun.',check:'Choose and explain: “The list of names is/are on the table.”'}
 ],
 'basic subject–verb agreement':[
  {title:'Example 1 — singular noun, singular subject, singular verb',problem:'Choose the correct sentence: “The girl read every evening” or “The girl reads every evening.”',steps:['Find the subject: “The girl”.','Girl refers to one person, so the subject is singular.','The sentence is in the simple present tense. With a third-person singular subject, the main verb normally takes -s or -es.','Therefore the correct form is “The girl reads every evening.”','Check the meaning: one girl performs the action regularly.'],why:'In the simple present tense, the -s on the verb usually marks third-person singular agreement. This is different from nouns, where -s often marks plural.',check:'Why do we say “The student writes” but “The students write”? Explain what happens to both the noun and the verb.'},
  {title:'Example 2 — plural subject uses the base verb',problem:'Choose: “The players trains every morning” or “The players train every morning.”',steps:['The subject is “The players”.','Players refers to more than one person, so it is plural.','For a plural subject in the simple present, use the base verb: train, not trains.','Correct sentence: “The players train every morning.”'],why:'Do not copy the plural -s from the noun onto the verb. A plural noun may end in -s while its present-tense verb normally does not.',check:'Complete and explain: “My brothers ___ football on Saturdays.” Choose play or plays.'},
  {title:'Example 3 — special forms of be, have and do',problem:'Complete: “She ___ ready, she ___ a pen, and she ___ her homework every day.” Use is/are, has/have, does/do.',steps:['The subject “she” is third-person singular.','The verb be uses “is” with she in the present: She is ready.','Have changes to “has” with she: She has a pen.','Do changes to “does” with she: She does her homework.','The complete sentence uses is, has and does.'],why:'Some very common verbs do not follow only the ordinary -s pattern, so their agreement forms must be recognised directly.',check:'Complete with the correct forms: “They ___ ready, they ___ books, and they ___ their work.”'},
  {title:'Example 4 — find the true subject before the verb',problem:'Choose: “The basket of oranges is heavy” or “The basket of oranges are heavy.”',steps:['Ask what the sentence is mainly talking about: the basket.','“of oranges” gives more information about the basket; it does not become the subject.','Basket is singular.','Use the singular verb “is”.','Correct sentence: “The basket of oranges is heavy.”'],why:'Agreement follows the true grammatical subject, not the nearest noun. Prepositional phrases such as “of oranges” often contain distracting nouns.',check:'In “The colour of the walls ___ bright”, should the verb be is or are? Identify the true subject first.'},
  {title:'Example 5 — pronouns and person',problem:'Choose the correct forms: “I am”, “you are”, “he is”, “they are”.',steps:['Pronouns also control agreement.','I takes am in the present form of be.','You takes are whether it refers to one person or more than one.','He, she and it take is.','We and they take are.'],why:'Concord is not only singular versus plural; person also matters, especially with the verb be.',check:'Why is “You is ready” incorrect even when you means only one person?'},
 ],
 'indefinite pronouns and quantity expressions':[
  {title:'Example 1 — each/everyone are singular',problem:'Choose: “Each of the players has a jersey” or “Each of the players have a jersey.”',steps:['The controlling word is “Each”.','Each means every one considered separately, so it is singular.','“of the players” does not control the verb.','Use the singular form “has”.'],why:'Several common indefinite pronouns are grammatically singular even when their meaning involves many people.',check:'Choose and explain: “Everyone in the rooms is/are waiting.”'},
  {title:'Example 2 — some/all depend on what follows',problem:'Compare “Some of the water is gone” and “Some of the books are missing.”',steps:['Some can refer to an uncountable amount or to several countable items.','Water is treated as a singular mass, so use is.','Books is plural, so use are.','The meaning of the quantity phrase decides the agreement.'],why:'Not every indefinite quantity word has one fixed number. The noun it refers to can determine whether the phrase is singular or plural.',check:'Complete both: “All of the milk ___ fresh.” “All of the chairs ___ occupied.” Explain the difference.'}
 ],
 'compound subjects and either/neither structures':[
  {title:'Example 1 — subjects joined by and',problem:'Choose: “Ada and Musa is ready” or “Ada and Musa are ready.”',steps:['Ada is one subject and Musa is another.','The conjunction and joins two different people into a compound subject.','Two people form a plural subject.','Use the plural verb “are”.'],why:'Ordinary subjects joined by and normally represent more than one and therefore take plural agreement.',check:'Complete: “The teacher and the prefect ___ outside.” Explain your choice.'},
  {title:'Example 2 — either/or with different numbers',problem:'Choose: “Either the principal or the teachers is/are attending.”',steps:['The paired conjunction is either…or.','The two subject parts have different number: principal is singular; teachers is plural.','In the usual school rule, the verb agrees with the nearer subject.','Teachers is nearest to the verb, so use “are”.'],why:'The proximity rule prevents guessing from the first noun. The order of the subject parts matters when their numbers differ.',check:'Now reverse the order: “Either the teachers or the principal ___ attending.” Which verb fits, and why?'}
 ],
 'collective nouns, measurements and relative-clause agreement':[
  {title:'Example 1 — a group acting as one unit',problem:'Choose: “The committee has reached its decision” or “The committee have reached its decision.”',steps:['Committee is a collective noun: one word naming a group.','Here the group is presented as acting together and producing one decision.','Treat the committee as one unit.','Use the singular verb “has”.'],why:'Collective nouns depend partly on meaning. In standard school questions, a group presented as one unit commonly takes singular agreement.',check:'Why is singular agreement natural in “The team is ready for the match”?'},
  {title:'Example 2 — one measurement as one amount',problem:'Choose: “Ten kilometres is a long distance” or “Ten kilometres are a long distance.”',steps:['Kilometres looks plural, but the whole expression names one distance.','The sentence treats ten kilometres as a single amount.','Use the singular verb “is”.'],why:'Number words do not always make a subject grammatically plural when the entire phrase represents one amount, period or sum.',check:'Complete and explain: “Five thousand naira ___ enough for the books.”'},
  {title:'Example 3 — agreement inside a relative clause',problem:'Choose: “She is one of the pupils who work hard” or “She is one of the pupils who works hard.”',steps:['Focus on the relative clause “who ___ hard”.','Who refers back to “pupils”, not only to “she”.','Pupils is plural.','Use the plural verb “work”.'],why:'A relative-clause verb agrees with the noun represented by who, which or that. You must trace the relative word back to its antecedent.',check:'In “This is one of the books that belong to the library”, why is “belong” plural?'}
 ],
 'lines, angles and angle relationships':[
  {title:'Example 1 — classify before calculating',problem:'Classify 35°, 90°, 125°, 180° and 240°.',steps:['35° is greater than 0° but less than 90°, so it is acute.','90° is a right angle.','125° is between 90° and 180°, so it is obtuse.','180° is a straight angle.','240° is greater than 180° but less than 360°, so it is reflex.'],why:'Classification gives meaning to angle size before formulas or angle facts are used.',check:'Classify 72°, 150° and 300° and state the interval that justifies each answer.'},
  {title:'Example 2 — straight-line angles',problem:'Two adjacent angles form a straight line. One angle is 128°. Find the other.',steps:['State the relationship first: angles on a straight line add to 180°.','Let the unknown angle be x.','Write x + 128° = 180°.','Subtract 128° from 180°: x = 52°.','Check: 128° + 52° = 180°.'],why:'The subtraction comes from the straight-line fact. Naming the fact first prevents using 180° in the wrong situation.',check:'An angle on a straight line is 47°. Find the adjacent angle and state the fact before calculating.'},
  {title:'Example 3 — angles around a point',problem:'Angles around a point are 95°, 110°, 75° and x. Find x.',steps:['Angles around one point total 360°.','Add the known angles: 95 + 110 + 75 = 280°.','Write 280° + x = 360°.','So x = 80°.','Check that all four angles total 360°.'],why:'A complete turn is 360°, so every set of adjacent angles around the same point must total 360°.',check:'Three angles around a point are 120°, 85° and x. Find x and explain why 360° is the correct total.'},
  {title:'Example 4 — vertically opposite angles',problem:'Two straight lines cross. One angle is 64°. Find the angle directly opposite it.',steps:['Identify the pair: the angles are vertically opposite.','Vertically opposite angles are equal.','Therefore the opposite angle is also 64°.','No subtraction is needed for the opposite angle.'],why:'At an intersection, opposite angles are formed by the same two straight lines and have equal measure.',check:'If an angle at an intersection is 117°, what is the vertically opposite angle? What about either adjacent angle?'},
  {title:'Example 5 — parallel lines and a transversal',problem:'Two parallel lines are crossed by a transversal. One interior angle is 68°. Find its alternate interior angle.',steps:['Confirm the lines are parallel; the special parallel-line facts depend on this.','Identify the required relationship: alternate interior angles.','Alternate interior angles between parallel lines are equal.','Therefore the alternate interior angle is 68°.'],why:'Corresponding and alternate equalities come from the geometry of a transversal crossing parallel lines; they are not visual guesses.',check:'If a co-interior angle is 112°, what is the other co-interior angle, and which fact do you use?'}
 ],
 'speech sounds: vowels and consonants':[
  {title:'Example 1 — short and long vowel contrast',problem:'Compare “ship” and “sheep”.',steps:['Say ship slowly: /ʃɪp/. The middle vowel is /ɪ/.','Say sheep slowly: /ʃiːp/. The middle vowel is /iː/.','The first sound /ʃ/ and final sound /p/ are the same.','Only the vowel changes, and that change creates a different word and meaning.'],why:'Listening to contrasting pairs trains the ear to notice the exact sound that distinguishes words.',check:'Which vowel do you hear in “sit” and which in “seat”?'},
  {title:'Example 2 — another minimal pair',problem:'Compare “full” and “fool”.',steps:['full contains /ʊ/.','fool contains /uː/.','Keep the beginning /f/ and ending /l/ in mind; focus on the vowel.','Say the pair several times and listen for the shorter /ʊ/ versus longer /uː/.'],why:'Minimal pairs differ in one important sound, making them useful for pronunciation and listening practice.',check:'Can you give another pair in which changing only the vowel changes the word?'}
 ],
 'operations and order of operations':[
  {title:'Example 1 — multiplication before addition',problem:'Evaluate 5 + 3 × 4.',steps:['Identify the operations: addition and multiplication.','BODMAS tells us multiplication is done before addition when there are no brackets/orders.','Calculate 3 × 4 = 12.','Now add: 5 + 12 = 17.','Check by keeping the original order visible: 5 + (3 × 4) = 17.'],why:'The agreed order prevents the same expression from producing different answers.',check:'Evaluate 18 - 2 × 5 and explain why subtraction is not first.'},
  {title:'Example 2 — brackets change priority',problem:'Evaluate (5 + 3) × 4.',steps:['Brackets come first, so calculate 5 + 3 = 8.','Now multiply: 8 × 4 = 32.','Compare with 5 + 3 × 4 = 17: the brackets changed the structure.'],why:'Brackets group part of an expression and tell us to treat that group first.',check:'What is the difference between 6 + 2 × 5 and (6 + 2) × 5?'},
  {title:'Example 3 — division and multiplication share a level',problem:'Evaluate 24 ÷ 3 × 2.',steps:['Division and multiplication have equal priority.','When equal-priority operations occur, work from left to right.','24 ÷ 3 = 8.','8 × 2 = 16.'],why:'BODMAS does not mean multiplication always beats division; they are handled left to right.',check:'Evaluate 36 ÷ 6 × 3 and explain the order.'}
 ],
 'area of plane shapes':[
  {title:'Example 1 — rectangle from meaning',problem:'Find the area of a rectangle 8 cm long and 5 cm wide.',steps:['Area measures the surface inside the boundary, so the unit will be square units.','A rectangle can be seen as rows of unit squares: 8 in each row and 5 rows.','Multiply length × width: 8 × 5 = 40.','Therefore the area is 40 cm².'],why:'The formula A = l × w counts how many unit squares cover the rectangle.',check:'A rectangle has area 54 cm² and length 9 cm. What is its width, and why do you divide?'},
  {title:'Example 2 — triangle is half a matching parallelogram',problem:'Find the area of a triangle with base 10 cm and perpendicular height 6 cm.',steps:['Use the perpendicular height, not a sloping side.','A triangle with a matching copy forms a parallelogram of area base × height.','So one triangle is half: 1/2 × 10 × 6.','10 × 6 = 60; half is 30.','Area = 30 cm².'],why:'The 1/2 in the triangle formula comes from the triangle occupying half of a matching parallelogram.',check:'Why must the height be perpendicular to the base?'},
  {title:'Example 3 — composite shape',problem:'An L-shape can be split into rectangles of 6 cm × 4 cm and 3 cm × 2 cm. Find its total area if they do not overlap.',steps:['Break the unfamiliar shape into familiar non-overlapping shapes.','First rectangle: 6 × 4 = 24 cm².','Second rectangle: 3 × 2 = 6 cm².','Add because both pieces make the whole: 24 + 6 = 30 cm².'],why:'Composite-area problems become simpler when the whole is partitioned into shapes whose area formulas we understand.',check:'If one rectangle were a cut-out instead of an added piece, would you add or subtract its area? Why?'}
 ],
 'writing & composition':[
  {title:'Example 1 — build a paragraph, not a sentence pile',problem:'Write one paragraph explaining why punctuality matters at school.',steps:['Decide the paragraph’s single controlling idea: punctuality helps learning and responsibility.','Write a topic sentence that states that idea clearly.','Add a reason: arriving on time prevents missing instructions.','Add a concrete example: a pupil who misses the first ten minutes may not understand the task.','Close by linking the example back to the main idea.','Edit for tense, concord, punctuation and unnecessary repetition.'],why:'A strong paragraph develops one main idea with explanation and evidence rather than collecting unrelated sentences.',check:'Give me a topic sentence and one supporting example for a paragraph about keeping the environment clean.'},
  {title:'Example 2 — plan an informal letter',problem:'Plan a letter to a friend describing your first week in a new school.',steps:['Identify audience and purpose: a friend; to describe your experience.','Use the appropriate informal-letter layout.','Plan the body before drafting: arrival/first impression → people/classes → one memorable event → how you feel now.','Use paragraphs so each stage has a clear focus.','After drafting, edit names/capitals, tense consistency, punctuation and natural tone.'],why:'Planning reduces repetition and helps the reader follow the experience in a sensible order.',check:'What four body-paragraph ideas would you use for a letter describing a school excursion?'}
 ],
 'comprehension':[
  {title:'Example 1 — answer from evidence',problem:'A passage says: “Amina left home early because the bridge usually becomes crowded after seven.” Why did Amina leave early?',steps:['Read the question and identify the key phrase: “Why did Amina leave early?”','Return to the sentence that gives the reason.','The reason is introduced by “because”.','Answer in your own words without adding information: She left early to avoid the crowd on the bridge.'],why:'Comprehension answers must be supported by the passage. A reasonable guess that the passage does not support is still a weak answer.',check:'Which words in the sentence provide the evidence for the answer?'}
 ]
};

function keyFor(title:string){const t=title.toLowerCase();for(const k of Object.keys(banks))if(t.includes(k)||k.includes(t))return k;return ''}
export function deepExamples(title:string):DeepExample[]{const k=keyFor(title);return k?banks[k]:[]}
