export type Jss1ConversationQuestion={
 id:string;classLevel:'JSS1';subject:'English Language';topic:'Conversation on Various Issues';prompt:string;
 options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string;
};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1ConversationQuestion=>({
 id:`nerdc25-auth-jss1-eng-conversation-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Conversation on Various Issues',prompt,options,correctAnswer,explanation,difficulty,skill
});
export const jss1ConversationQuestions:Jss1ConversationQuestion[]=[
q(1,'What makes a conversation different from a speech?',['Conversation requires speakers to listen and respond to one another','Conversation must always be written first','A speech can never contain information','Conversation has only one speaker'],'Conversation requires speakers to listen and respond to one another','Conversation is interactive and two-way; each turn should connect with what another participant has said.',1,'meaning of conversation'),
q(2,'Which sequence best describes the broad structure of a conversation?',['opening → development → closing','closing → title → examination','argument → interruption → silence','question → unrelated speech → ending'],'opening → development → closing','A conversation can introduce the topic, develop it through connected turns, and end appropriately.',1,'conversation structure'),
q(3,'A says, “Many learners miss school when the road floods.” Which response best continues the conversation?',['Could improved drainage make the route safer during heavy rain?','My favourite food is rice.','I have a new football jersey.','English has many nouns.'],'Could improved drainage make the route safer during heavy rain?','A relevant response develops the point just made instead of changing to an unrelated subject.',1,'relevance'),
q(4,'What is turn-taking?',['Sharing speaking opportunities while listening and responding appropriately','Speaking until every other participant is silent','Changing the subject after every sentence','Repeating the same sentence many times'],'Sharing speaking opportunities while listening and responding appropriately','Turn-taking allows participants to contribute without unnecessary interruption or domination.',1,'turn-taking'),
q(5,'Which question is most open-ended?',['Why do you think some children remain out of school?','Did the meeting begin at ten?','Is the gate open?','Was the article published today?'],'Why do you think some children remain out of school?','Open questions invite explanation rather than a short yes/no or single-fact answer.',1,'questioning'),
q(6,'What is a follow-up question?',['A question that develops something the previous speaker has just said','A question that deliberately changes to an unrelated topic','A question asked before listening to any answer','A greeting used to end every conversation'],'A question that develops something the previous speaker has just said','Follow-up questions demonstrate listening because they grow from the preceding contribution.',1,'follow-up questions'),
q(7,'Which response shows respectful disagreement?',['I understand your point, but I think we should also consider the transport problem.','That is a foolish idea.','Be quiet; you know nothing about this.','You are wrong because I said so.'],'I understand your point, but I think we should also consider the transport problem.','Respectful disagreement addresses the idea, gives a reason or alternative, and avoids personal attack.',1,'respectful disagreement'),
q(8,'In language use, what does register mainly refer to?',['Language and vocabulary selected to suit the topic, audience and situation','The number of people in a classroom','A list containing only difficult words','Speaking as loudly as possible'],'Language and vocabulary selected to suit the topic, audience and situation','Register changes with subject matter, relationship, purpose and degree of formality.',1,'register'),
q(9,'Which sentence is most suitable for a formal school meeting?',['I suggest that we report the damaged gate because it may create a safety risk.','Guy, that gate don spoil well well.','Forget the gate jare.','Anybody can do anything they like.'],'I suggest that we report the damaged gate because it may create a safety risk.','The sentence uses clear, respectful language appropriate to a formal school discussion.',1,'formal register'),
q(10,'Which group contains vocabulary most closely associated with the economy?',['income, budget, prices, goods, employment','rhyme, stanza, metaphor, rhythm','goalkeeper, referee, penalty, striker','noun, pronoun, adjective, adverb'],'income, budget, prices, goods, employment','These terms help speakers discuss resources, spending, production, prices and work.',1,'economy register'),
q(11,'If food prices rise while a family’s income remains the same, what is a reasonable discussion point?',['The family may need to revise its budget and prioritise essential needs','The family automatically earns more money','Prices and budgets are unrelated','Every family must buy exactly the same goods'],'The family may need to revise its budget and prioritise essential needs','The response uses economic vocabulary to reason about a simple effect of higher prices under a fixed income.',2,'economy discussion'),
q(12,'Which vocabulary is most appropriate to a discussion of security?',['safety, prevention, emergency, report, protection','stanza, chorus, rhyme, imagery','profit, salary, budget, consumer','rainfall, emissions, drought, climate'],'safety, prevention, emergency, report, protection','These words belong naturally to discussions about safety and responsible prevention/reporting.',1,'security register'),
q(13,'A student receives an alarming but unverified safety message. What is the most responsible conversational response?',['Check whether the information is reliable and tell a trusted adult or appropriate authority if there is a genuine concern','Forward it immediately to everyone','Add frightening details so people pay attention','Assume it must be true because it sounds serious'],'Check whether the information is reliable and tell a trusted adult or appropriate authority if there is a genuine concern','Responsible discussion distinguishes verified information from rumours and uses safe reporting channels.',2,'information literacy and security'),
q(14,'Who are “out-of-school children” in the context of this lesson?',['Children of school age who are not attending school','Only children who have finished university','Every child absent for one lesson','Children playing outside after school hours'],'Children of school age who are not attending school','The term concerns school-age children who are outside formal schooling, though their individual reasons can differ.',1,'education register'),
q(15,'Which statement shows the best reasoning about out-of-school children?',['Different children may face different barriers, so solutions should address the particular causes involved','Every child is out of school for exactly the same reason','One punishment can solve every barrier to schooling','Distance, cost and displacement can never affect access to education'],'Different children may face different barriers, so solutions should address the particular causes involved','Good problem-solving avoids overgeneralisation and matches possible solutions to identified barriers.',2,'problem solving'),
q(16,'Which statement correctly distinguishes weather from climate?',['Weather describes shorter-term atmospheric conditions; climate concerns patterns over much longer periods','Weather and climate always mean exactly the same thing','One hot afternoon by itself describes a long-term climate pattern','Climate changes completely every hour'],'Weather describes shorter-term atmospheric conditions; climate concerns patterns over much longer periods','This distinction helps learners discuss climate change without using one isolated weather event as complete evidence.',2,'climate register'),
q(17,'Which set of words best fits a climate-change conversation?',['rainfall, temperature, flooding, drought, adaptation','salary, consumer, profit, budget, savings','dialogue, character, stage, costume, plot','syllable, vowel, consonant, stress, rhyme'],'rainfall, temperature, flooding, drought, adaptation','These terms are relevant to climate patterns, impacts and responses.',1,'climate vocabulary'),
q(18,'A speaker says, “According to the report, 120 pupils enrolled this term.” What good discussion habit does this demonstrate?',['Attributing a checkable claim to its source','Using slang to sound friendly','Changing a fact into an insult','Avoiding evidence'],'Attributing a checkable claim to its source','Current-issue discussion should identify sources for checkable claims rather than present unsupported information as fact.',2,'source use'),
q(19,'Which statement is clearly an opinion rather than a simple checkable fact?',['This is the best programme the school has ever introduced.','The meeting began at 10:00 a.m.','The report lists 120 pupils.','The notice gives Friday as the closing date.'],'This is the best programme the school has ever introduced.','“Best” expresses an evaluation and requires criteria and reasons; the other statements can be checked directly against records.',2,'fact and opinion'),
q(20,'Which framework best supports a problem-solving discussion of a current issue?',['issue → causes → effects → possible solutions','insult → interruption → rumour → conclusion','topic → unrelated story → louder voice → silence','solution → ignore cause → change topic → repeat'],'issue → causes → effects → possible solutions','This structure moves the conversation from identifying a problem to reasoning about why it happens, what it causes and what may help.',2,'problem-solving conversation')
];