export type Jss1SummaryQuestion={id:string;classLevel:'JSS1';subject:'English Language';topic:'Reading for Summary';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1SummaryQuestion=>({id:`nerdc25-auth-jss1-eng-summary-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Reading for Summary',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1SummaryQuestions:Jss1SummaryQuestion[]=[
q(1,'What is the main purpose of a summary?',['To give the essential meaning of a longer text more briefly and accurately','To copy every sentence from the original','To add the reader’s opinion to the passage','To make the passage longer'],'To give the essential meaning of a longer text more briefly and accurately','A summary reduces length while preserving the source’s important meaning.',1,'summary foundation'),
q(2,'Which principle best guides sentence reduction?',['Remove unnecessary wording without changing essential meaning','Delete as many words as possible even if meaning changes','Always remove words showing cause','Replace every word with a synonym'],'Remove unnecessary wording without changing essential meaning','Reduction is successful only when the important message and relationships remain accurate.',1,'sentence reduction'),
q(3,'Original: “The small young boy quickly ran at great speed towards the nearby school gate because he was already late.” Which is the best reduction?',['The boy ran to the school gate because he was late','The boy was small','The gate was nearby','The boy ran because school gates exist'],'The boy ran to the school gate because he was late','This keeps the central action and cause while removing redundant description.',1,'sentence reduction'),
q(4,'Why must “not” be treated carefully during reduction?',['Removing it can reverse the meaning of a sentence','It is always an example','It never affects meaning','It should always be replaced by “very”'],'Removing it can reverse the meaning of a sentence','Negation can be essential to the writer’s meaning and must not be deleted mechanically.',1,'meaning preservation'),
q(5,'What is a topic sentence?',['A sentence that expresses the controlling or central idea of a paragraph','The longest sentence in every paragraph','Any sentence containing an example','The title of a book'],'A sentence that expresses the controlling or central idea of a paragraph','A topic sentence commonly states the idea that the remaining sentences develop.',1,'topic sentences'),
q(6,'Where can a topic sentence occur?',['At the beginning, middle or end; sometimes the central idea is implied','Only as the first sentence','Only as the final sentence','Only in the title'],'At the beginning, middle or end; sometimes the central idea is implied','Its position is not fixed, so the reader must understand the paragraph rather than rely on location alone.',1,'topic sentences'),
q(7,'Which expression most clearly redirects attention toward an important contrast?',['however','for example','such as','also'],'however','“However” signals a contrast and may redirect attention from one idea to another.',1,'signal expressions'),
q(8,'Sentence: “Many pupils mentioned the heat. However, the major problem was the lack of clean drinking water.” What should a concise summary emphasise?',['The lack of clean drinking water was the main problem','Pupils mentioned many things','Heat is always dangerous','Every pupil wanted cold water'],'The lack of clean drinking water was the main problem','“However” and “the major problem” explicitly redirect attention to the more important point.',2,'attention redirection'),
q(9,'Why are examples often omitted from a short summary?',['Several examples can often be represented by the broader key idea they illustrate','Examples are always false','Examples never support ideas','A summary may contain no nouns'],'Several examples can often be represented by the broader key idea they illustrate','Summary writing compresses elaboration while preserving the essential general point.',1,'generalising examples'),
q(10,'“Residents cleared gutters, removed refuse from waterways and opened blocked drainage channels.” Which summary is strongest?',['Residents cleared obstructions from the drainage system','Residents touched several things','Gutters exist in the community','Only refuse was removed'],'Residents cleared obstructions from the drainage system','The answer combines the related examples into the broader action without losing their common meaning.',2,'combining ideas'),
q(11,'What does paraphrasing require?',['Restating the same meaning naturally in different wording/structure','Changing one word to a synonym and copying everything else','Adding a new explanation','Changing the writer’s claim'],'Restating the same meaning naturally in different wording/structure','True paraphrase demonstrates understanding while remaining faithful to the source.',1,'paraphrasing'),
q(12,'Original: “High transport fares compel many pupils to walk considerable distances to school.” Which is the best paraphrase?',['Expensive transport forces many pupils to walk long distances to school','Transport is wonderful for every pupil','Pupils always enjoy long walks','Schools charge high fares'],'Expensive transport forces many pupils to walk long distances to school','The wording and structure change while the essential meaning remains.',1,'paraphrasing'),
q(13,'A passage discusses causes, effects and solutions to lateness. The question asks for two causes. What should the summary contain?',['Only two causes supported by the passage','Every cause, effect and solution','The reader’s preferred solution','A history of the school'],'Only two causes supported by the passage','Summary answers must respect the exact scope and number of points requested.',2,'scope'),
q(14,'Which statement is an unsupported addition to a summary of “The council planted 200 trees along major roads”?',['The wonderful council wisely planted 200 beautiful trees','The council planted 200 trees','The trees were planted along major roads','The council planted trees along roads'],'The wonderful council wisely planted 200 beautiful trees','“Wonderful” and “wisely” add evaluative opinions that the source did not provide.',1,'faithfulness'),
q(15,'Original: “Better drainage may reduce flooding.” Which summary preserves the writer’s certainty?',['Improved drainage may reduce flooding','Improved drainage will eliminate flooding','Flooding can never occur with drainage','Drainage has already ended all flooding'],'Improved drainage may reduce flooding','The modal “may” expresses possibility; changing it to certainty distorts the source.',2,'certainty'),
q(16,'Which is the best combined summary of “The clinic lacked nurses. It lacked medicines. It had too few beds.”?',['The clinic lacked adequate staff, medicines and beds','The clinic had nurses','The clinic was perfect except for beds','Medicines were the only problem'],'The clinic lacked adequate staff, medicines and beds','The three related shortages are concisely combined without deleting a key category.',1,'combining key ideas'),
q(17,'Why should a writer read the whole passage before drafting the summary?',['Later information may develop, qualify or change the importance of earlier ideas','Only the final paragraph matters','The first sentence is never important','Reading the whole passage makes copying easier'],'Later information may develop, qualify or change the importance of earlier ideas','A complete view of the passage is necessary before deciding which ideas are essential.',2,'summary process'),
q(18,'Which sequence best represents AVORA’s summary process?',['READ → SCOPE → MARK → REDUCE → PARAPHRASE → COMBINE → CHECK','COPY → ADD → REPEAT → STOP','TITLE → GUESS → OPINION → COPY','DELETE → DELETE → DELETE → SUBMIT'],'READ → SCOPE → MARK → REDUCE → PARAPHRASE → COMBINE → CHECK','The process moves from understanding and selection to concise expression and verification.',1,'summary process'),
q(19,'Which final check is most complete?',['Is each point supported, important, accurate, concise, non-repetitive and within the requested scope?','Is my answer the shortest possible?','Did I replace every original word?','Did I add my opinion?'],'Is each point supported, important, accurate, concise, non-repetitive and within the requested scope?','A good audit checks faithfulness, importance, concision, repetition and task requirements together.',2,'summary audit'),
q(20,'Why is “Flooding. Bad drainage. Waste.” weaker than “Blocked drains and poor waste disposal contribute to flooding” when full sentences are required?',['The fragments are brief but do not clearly express the relationship among the ideas','A summary must always contain ten words','The second sentence contains no key ideas','Fragments are always longer'],'The fragments are brief but do not clearly express the relationship among the ideas','Concision should not destroy grammatical clarity or important logical relationships.',3,'coherent summary writing')
];