export type Jss1FluencyQuestion={id:string;classLevel:'JSS1';subject:'English Language';topic:'Reading Short passages with fluency';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1FluencyQuestion=>({id:`nerdc25-auth-jss1-eng-fluency-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Reading Short passages with fluency',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1FluencyQuestions:Jss1FluencyQuestion[]=[
q(1,'Which description best explains fluent reading?',['Reading accurately at an appropriate pace, with meaningful phrasing/expression and understanding','Reading every passage as fast as possible','Reading loudly even when the words are wrong','Memorising a passage without understanding it'],'Reading accurately at an appropriate pace, with meaningful phrasing/expression and understanding','Fluency combines accuracy, suitable rate, phrasing/prosody and comprehension; speed alone is insufficient.',1,'fluency foundation'),
q(2,'What does accuracy mean in reading?',['Reading the printed words correctly','Reading faster than everyone else','Making every sentence very loud','Skipping unfamiliar words'],'Reading the printed words correctly','Accuracy concerns faithful recognition and production of the words in the text.',1,'accuracy'),
q(3,'Why is excessive speed a problem?',['It can cause skipped or changed words and loss of meaning','It always improves comprehension','It automatically improves pronunciation','It removes the need for punctuation'],'It can cause skipped or changed words and loss of meaning','A useful reading rate preserves both accuracy and understanding.',1,'rate'),
q(4,'What is phrasing?',['Grouping words into meaningful sense units','Stopping after every word','Ignoring grammar and punctuation','Reading only the longest words'],'Grouping words into meaningful sense units','Phrase reading helps the reader carry connected ideas rather than process isolated words.',1,'phrasing'),
q(5,'Which grouping is most natural?',['After the rain, / the children returned to the field.','After / the / rain / the / children / returned / to / the / field.','After the / rain the children / returned to / the field.','After / the rain the / children returned to the / field.'],'After the rain, / the children returned to the field.','The first version follows meaningful grammatical and semantic groups.',1,'sense groups'),
q(6,'What does prosody include?',['Stress, rhythm, pausing and intonation that reflect meaning','Only spelling accuracy','Only reading speed','The number of paragraphs in a passage'],'Stress, rhythm, pausing and intonation that reflect meaning','Prosody is the expressive organisation of oral reading.',1,'prosody'),
q(7,'A learner reads a question exactly like a flat statement. What needs the most improvement?',['Intonation/prosody','Eyesight','Paragraph count','Handwriting'],'Intonation/prosody','A question mark and the intended meaning should influence oral delivery.',1,'intonation'),
q(8,'A learner reads “plants” where the text says “planted.” What is the best response?',['Check the print and meaning, correct the word, then reread the whole phrase','Ignore the error and continue','Start the entire book again','Guess another word quickly'],'Check the print and meaning, correct the word, then reread the whole phrase','Self-correction should restore both the correct word and the flow of the phrase.',2,'self-correction'),
q(9,'Why is comprehension included in fluency?',['Reading should carry connected meaning, not merely produce sounds','Comprehension is needed only in writing','Understanding always makes punctuation unnecessary','Fluent readers do not need to remember ideas'],'Reading should carry connected meaning, not merely produce sounds','If a learner cannot follow the passage, fast accurate-sounding word calling is not complete fluent reading.',1,'comprehension'),
q(10,'What should a learner do before reading a short unfamiliar passage?',['Preview the title/text, notice difficult words and punctuation, and know the reading purpose','Immediately race through it','Cover all punctuation','Memorise the last sentence first'],'Preview the title/text, notice difficult words and punctuation, and know the reading purpose','A brief preview prepares word recognition and gives reading a purpose.',1,'pre-reading'),
q(11,'In NERDC fluency guidance, what is vocalisation in silent reading?',['Saying every word aloud or moving the lips while reading silently','Reading a passage aloud for pronunciation practice','Answering a comprehension question','Looking at a title before reading'],'Saying every word aloud or moving the lips while reading silently','Oral reading has valid uses, but unnecessary vocalisation can restrict speed during a silent-reading task.',2,'efficient reading habits'),
q(12,'What is regressive reading when it becomes a bad habit?',['Repeatedly jumping backward over text without a genuine need','Rereading once because meaning was unclear','Reading a passage for the first time','Correcting one misread word'],'Repeatedly jumping backward over text without a genuine need','Strategic rereading can help comprehension; habitual unnecessary backtracking disrupts flow.',2,'regression'),
q(13,'What does increasing eye span aim to help a reader do?',['Take in useful groups of print rather than fixating on every tiny unit','See through a closed book','Ignore whole phrases','Read without understanding'],'Take in useful groups of print rather than fixating on every tiny unit','Wider useful visual grouping supports phrase reading and efficient movement through text.',2,'eye span'),
q(14,'Why can permanent word-by-word finger tracking limit a developing fluent reader?',['It may reinforce isolated word reading instead of meaningful phrase grouping','It always damages eyesight','It changes the spelling of words','It makes punctuation disappear'],'It may reinforce isolated word reading instead of meaningful phrase grouping','Tracking can be a temporary support, but fluent reading increasingly groups words into meaningful units.',2,'reading habits'),
q(15,'Which is the best use of repeated reading?',['Give each rereading a target such as accuracy, phrasing or expression','Race through the same passage repeatedly with no feedback','Memorise the passage and never read a new one','Repeat only the easiest sentence'],'Give each rereading a target such as accuracy, phrasing or expression','Purposeful repeated reading combines practice with guidance and a specific improvement goal.',1,'repeated reading'),
q(16,'A reader is accurate but sounds robotic, pausing at nearly every word. What should be practised next?',['Sense-group phrasing and expression','Faster guessing','Ignoring punctuation','Skipping short words'],'Sense-group phrasing and expression','The words are accurate, so the next fluency target is connecting them into meaningful phrases with suitable prosody.',2,'diagnosing fluency'),
q(17,'A reader finishes first but cannot state the passage’s main idea. Which conclusion is best?',['The fast rate did not produce complete fluent reading because comprehension was lost','The reader must be the most fluent','Main ideas are unrelated to reading','The passage should always be read even faster'],'The fast rate did not produce complete fluent reading because comprehension was lost','Fluency serves meaning; speed that destroys comprehension is not the target.',2,'rate and comprehension'),
q(18,'Which statement correctly distinguishes useful rereading from harmful regression?',['Useful rereading repairs lost meaning; harmful regression is habitual unnecessary backtracking','All rereading is harmful','All backward eye movement improves fluency','A fluent reader can never reread anything'],'Useful rereading repairs lost meaning; harmful regression is habitual unnecessary backtracking','The purpose matters: strategic rereading is a comprehension tool, while habitual regression can disrupt efficient reading.',2,'strategic rereading'),
q(19,'Why should fluency eventually be checked with an unfamiliar passage?',['To show that the learner can transfer the skill rather than merely perform a memorised text','Because practised passages are always useless','Because unfamiliar words should always be skipped','To prevent comprehension'],'To show that the learner can transfer the skill rather than merely perform a memorised text','Mastery means applying fluent reading behaviours to fresh age-appropriate text.',3,'transfer'),
q(20,'Which self-check is most complete after oral reading?',['Accuracy, phrasing, expression, meaning and self-correction','Speed only','Volume and page number only','Number of difficult words only'],'Accuracy, phrasing, expression, meaning and self-correction','A multidimensional check prevents the learner from mistaking one feature—especially speed—for complete fluency.',2,'self-assessment')
];