export const jss1IntroductionLiteratureDeepLessons=[{
 topicId:'revised2025-jss1-english-introduction-literature-deep',classLevel:'JSS1',subject:'English Language',topic:'Introduction to Literature',
 objectives:['Explain the meaning of literature','Identify prose, drama and poetry as major genres/forms of written literature','Distinguish oral literature from written literature','Recognise examples of oral and written literary expression','Explain with evidence how literature reflects different aspects of life and the moral values of society','Read/listen to short age-appropriate literary examples and identify their category'],
 prerequisites:['basic reading comprehension','listening comprehension','ability to distinguish spoken and written communication'],
 teaching:[
 'LITERATURE is the artistic use of language to express, represent and explore human experiences, ideas, feelings, imagination and society. At JSS1, the important question is not only “What is literature?” but also “What kind is this, and what part of life does it show us?”',
 'NERDC’s learning outcome is to READ AND APPRECIATE age-appropriate literary works. To appreciate literature means to understand and respond thoughtfully to what a work communicates and how it presents human experience.',
 'Literature can entertain, communicate ideas, preserve experiences and values, stimulate imagination, and help readers or listeners think about people and society. These are useful ways to understand why communities create and share literary works; the curriculum particularly emphasises how literature reflects life and moral values.',
 'NERDC requires learners to recognise the genres PROSE, DRAMA and POETRY. These are broad literary forms with different ways of organising language and presenting experience.',
 'PROSE is language arranged mainly in sentences and paragraphs rather than verse lines. Literary prose includes stories and other prose narratives. In this introductory lesson, identify the form; the detailed features and types of prose fiction belong to the later NERDC topic “Introduction to Prose Fiction.”',
 'DRAMA is literature written mainly to be performed. It presents action through characters, dialogue and performance. A written play may contain character names, spoken lines and stage directions.',
 'POETRY uses carefully selected and arranged language, often in lines and stanzas, to express experiences, feelings or ideas. Poetry may use rhythm, imagery, sound patterns and figurative language. Not every poem must rhyme.',
 'Do not identify a genre from one feature alone. Dialogue can occur inside prose, for example. Look at the work’s overall organisation and purpose: prose narration, performance-centred drama, or poetic arrangement.',
 'NERDC also requires two broad TYPES/CATEGORIES according to how literature is transmitted: ORAL LITERATURE and WRITTEN LITERATURE.',
 'ORAL LITERATURE is created, performed, preserved or passed on mainly through speech and performance. It may be heard in storytelling, songs, chants, riddles, proverbs and other verbal traditions. Because performance matters, voice, gesture, audience response and memory can be important.',
 'WRITTEN LITERATURE is preserved primarily in written form and read from texts such as books, scripts and written poems. NERDC specifically asks learners to explain written literature and its categories.',
 'ORAL and WRITTEN describe modes of transmission, while PROSE, DRAMA and POETRY describe literary forms/genres. Do not treat the two classifications as if they answer exactly the same question.',
 'A story can begin in oral tradition and later be written down. Once recorded on a page, the written version exists as a text, but its origin or oral-tradition features do not disappear. Categories can therefore interact.',
 'LITERATURE REFLECTS LIFE when it represents recognisable experiences, relationships, choices, beliefs, conflicts, hopes, fears, customs, occupations, environments or social issues.',
 'For example, a story about pupils deciding whether to report examination cheating can reflect school life, honesty, peer pressure, responsibility and consequences. The work does not need to reproduce a real event word-for-word to reflect real aspects of life.',
 'Literature can reflect FAMILY LIFE: relationships between parents, children, siblings or relatives; care, conflict, responsibility and belonging.',
 'It can reflect SCHOOL LIFE: friendship, discipline, learning, competition, bullying, leadership, success and failure.',
 'It can reflect COMMUNITY AND CULTURE: language, celebrations, occupations, customs, beliefs, expectations and ways people relate to one another.',
 'It can reflect MORAL VALUES. NERDC specifically asks learners to discuss how literature reflects the moral values of society. Values may include honesty, respect, courage, kindness, responsibility, fairness, unity and perseverance.',
 'A MORAL VALUE is not automatically the same as THEME. A work can explore a broad theme such as friendship while presenting values such as loyalty or honesty. At this introductory level, learners should support interpretations with evidence from what characters say, do and experience.',
 'Literature can also show undesirable behaviour—greed, dishonesty, cruelty or selfishness—and its consequences. Showing a behaviour does not necessarily mean the writer approves of it.',
 'Literature may reflect life directly or imaginatively. Talking animals or invented worlds can still represent human problems, values and relationships. “Reflects life” therefore does not mean every literary event must be literally possible.',
 'APPRECIATING a short work involves asking: What form/category is it? What happens or is expressed? What aspect of life appears? What value, idea or feeling is presented? What evidence in the work supports my answer?',
 'EVIDENCE matters. Instead of saying “This story teaches kindness” only because kindness sounds positive, point to an action, event, consequence, image or line that supports that interpretation.',
 'COMPARE THE GENRES: Prose usually develops language in sentences/paragraphs; drama centres on performed action and dialogue; poetry arranges language more compactly in lines/stanzas. All three can communicate similar human experiences in different ways.',
 'COMPARE THE CATEGORIES: Oral literature is mainly transmitted/performed by word of mouth; written literature is mainly preserved/read in written text. Both can entertain, communicate experience and reflect society.',
 'NERDC suggests audio/video tales, story sessions, drama and poetry readings as resources. This matters because learners should EXPERIENCE literature by listening, reading and observing performance—not merely memorise definitions.',
 'AVORA LITERATURE ROUTINE: EXPERIENCE THE WORK → IDENTIFY CATEGORY/GENRE → NOTICE PEOPLE/EVENTS/IDEAS → CONNECT TO AN ASPECT OF LIFE → IDENTIFY VALUE/MEANING → SUPPORT WITH EVIDENCE.'
 ],
 workedExamples:[
 'A printed short story written in paragraphs is an example of written literature and, by literary form, prose.',
 'A play script containing character names, dialogue and stage directions is written literature in the genre of drama.',
 'A poem printed in a book is written literature in the genre of poetry.',
 'A traditional tale performed aloud by an elder to an audience can be approached as oral literature because spoken performance is its main mode of transmission.',
 'A community riddle spoken from one generation to another is an example of oral literary expression.',
 'A story in which two siblings learn to share responsibilities reflects family life and may present cooperation or responsibility as values.',
 'A school story about a learner returning a lost wallet can reflect honesty and responsibility in everyday life.',
 'A drama about neighbours resolving a disagreement peacefully can reflect community relationships and values such as tolerance and dialogue.',
 'A poem describing a farmer waiting anxiously for rain may reflect work, environment, hope and uncertainty.',
 'A story can contain dialogue and still be prose. Dialogue alone does not automatically turn prose into drama.',
 'A poem does not stop being poetry because it does not rhyme. Overall poetic arrangement and use of language matter.',
 'A fictional talking tortoise can still reflect human qualities such as cleverness, greed or patience; imaginative content can represent real human behaviour.',
 'If a character cheats and later faces consequences, the text may invite reflection on dishonesty; the learner should cite those events as evidence.',
 '“This work reflects school life because its central conflict concerns pupils, rules and examination conduct” is stronger than “It reflects life because it is a story.”',
 'A spoken tale later printed in a collection demonstrates that oral and written traditions can interact; classification should consider the version and context being discussed.',
 'Genre question: “How is this literary work formed?” Category question: “Is it being transmitted mainly orally or in writing?” Keeping these questions separate prevents confusion.'
 ],
 misconceptions:['thinking literature means only printed novels','thinking oral literature is not literature because it is not written','using oral/written and prose/drama/poetry as identical classifications','thinking every text written in paragraphs is automatically literary prose','thinking any text with dialogue is drama','believing every poem must rhyme','thinking drama can exist only on a stage and not as a written script','thinking literature reflects life only when every event is factual','assuming a work approves of every behaviour it depicts','naming a moral value without evidence','confusing theme with moral value in every case','thinking literature is only for entertainment','treating imaginative characters as incapable of representing human life','prematurely importing detailed prose-fiction analysis into this introductory topic'],
 guidedPractice:[
 'CATEGORY SORT: classify short examples as oral or written literature and explain the evidence for each decision.',
 'GENRE SORT: examine brief original extracts representing prose, drama and poetry; identify the genre and the structural clue that supports the answer.',
 'TWO-AXIS CLASSIFICATION: for each example, answer separately (a) oral/written? and (b) prose/drama/poetry where applicable, explaining why the classifications are different.',
 'LIFE MIRROR: after a short story or performance, list the aspects of family, school, community or cultural life reflected in it.',
 'VALUE + EVIDENCE: identify one moral value or social concern in a short literary piece and quote/paraphrase the event or action that supports the interpretation.',
 'NERDC DISCUSSION: listen to/view an age-appropriate tale, drama scene or poetry reading, then discuss how it reflects moral values in society.',
 'FORM TRANSFER: take one simple situation—returning a lost item—and imagine how it could be presented as prose, drama or poetry without claiming the genres are identical.'
 ],
 independentPractice:[
 'Explain literature in your own words, then distinguish oral and written literature with two examples of each.',
 'Create a comparison table for prose, drama and poetry showing typical organisation and one original example of each.',
 'Read or listen to an age-appropriate literary work and write a short appreciation identifying its category/genre, one aspect of life it reflects, one value/idea, and evidence.',
 'Choose a familiar social experience such as friendship, honesty, family responsibility or school discipline. Explain how each of prose, drama and poetry could represent that same experience differently.'
 ],
 source:{authority:'NERDC Revised BEC 2025',url:'https://nerdc.gov.ng',verified:'OFFICIAL_SCOPE_PRESERVED_INTRODUCTION_ONLY'},
 mastery:{criterion:'Learner explains literature, distinguishes oral and written categories, identifies prose/drama/poetry, and explains with textual or performance evidence how literature reflects aspects and moral values of life at at least 80% mastery.',status:'DEEP_WHEN_PASSED'}
}];