export const jss1ProseFictionDeepLessons=[{
 topicId:'revised2025-jss1-english-prose-fiction-deep',classLevel:'JSS1',subject:'English Language',topic:'Introduction to Prose Fiction',
 objectives:['Explain the meaning of prose fiction','Explain age-appropriate functions of prose fiction','Identify narrative and descriptive prose as the two types specified by NERDC','Differentiate narrative from descriptive prose using textual evidence','Explain plot, characterisation, style, setting and theme','Read and appreciate class-appropriate prose texts','Create a simple plot/story map from a prose text','Produce an evidence-based character sketch including description, traits, motivations and role'],
 prerequisites:['Introduction to Literature','creative-writing story elements','theme and evidence','reading for meaning'],
 teaching:[
 'PROSE is language normally organised in sentences and paragraphs rather than verse lines. PROSE FICTION is imaginative prose that presents invented or imaginatively shaped characters, events and situations as a story or fictional world.',
 'Fiction does not mean “bad writing” or “a lie told to deceive.” In literature, fiction is an imaginative creation. A fictional story may still represent realistic people, places, problems, emotions and social experiences.',
 'NERDC asks learners to understand FUNCTIONS OF PROSE FICTION. Prose fiction can entertain, stimulate imagination, explore human experiences and choices, communicate ideas/themes, encourage empathy and reflection, and represent aspects of society. A particular text may perform several functions at once.',
 'NERDC specifies two TYPES for this JSS1 topic: NARRATIVE and DESCRIPTIVE. AVORA keeps those as the official scope rather than replacing them with a longer list of prose forms.',
 'NARRATIVE PROSE primarily tells a story or recounts connected events. It answers questions such as: What happened? To whom? In what order? What caused the next event? How did the situation change?',
 'DESCRIPTIVE PROSE primarily creates a vivid picture or impression of a person, place, object, scene or experience through carefully selected details. It answers: What is it like? What can the reader imagine seeing, hearing, smelling, tasting or feeling?',
 'Narrative and descriptive prose can MIX. A narrative story can pause to describe a market, storm or character. A descriptive passage can mention movement or small events. Classify by the passage’s dominant purpose, not by one isolated sentence.',
 'Example distinction: “Amina entered the compound, found the gate locked and ran to the neighbour for help” is mainly narrative because events progress. “The compound lay silent beneath dusty mango trees; cracked paint curled from the gate” is mainly descriptive because the focus is creating an impression.',
 'NERDC lists FEATURES/ELEMENTS: PLOT, CHARACTERISATION, STYLE, SETTING and THEME. These elements work together to create meaning.',
 'PLOT is the organised sequence of important events in a story and the relationships among them. A plot is stronger than a random list because actions and consequences connect.',
 'For JSS1 story mapping, identify the OPENING SITUATION, central PROBLEM/CONFLICT or challenge, DEVELOPMENT through important events, a decisive TURNING POINT/CLIMAX where appropriate, and the OUTCOME/RESOLUTION. Not every literary plot follows one rigid diagram, so use the actual text as evidence.',
 'CAUSE AND EFFECT strengthens plot analysis: What caused this event? What decision changed the situation? What consequence followed? This reveals why an event matters.',
 'A STORY MAP is a visual/structured summary of a story’s important parts. NERDC explicitly asks learners to create a plot diagram after reading a short story. A useful map records characters, setting, problem, major events, turning point and outcome.',
 'A CHARACTER is a person, animal or imagined being participating in a fictional work. CHARACTERISATION is the method by which the writer creates and reveals a character.',
 'DIRECT CHARACTERISATION tells a quality explicitly: “Sade was impatient.” INDIRECT CHARACTERISATION lets readers infer qualities through speech, actions, thoughts, appearance, choices or other characters’ responses: “Sade tapped her foot, checked the clock again and pushed past the queue.”',
 'NERDC’s character-analysis activity asks for a CHARACTER SKETCH including physical description, personality traits, motivations and the character’s role in the story. Each claim should be supported by evidence.',
 'PHYSICAL DESCRIPTION concerns relevant appearance. PERSONALITY TRAITS describe qualities such as courageous, selfish, patient or curious. MOTIVATION means what a character wants, needs, fears or hopes to achieve. ROLE means the character’s function/importance in the events.',
 'Do not confuse CHARACTER with CHARACTERISATION. “Musa” may be a character; “the writer shows Musa’s courage through his decision to return during the storm” discusses characterisation.',
 'SETTING is the time, place and relevant social/physical environment in which events occur. Setting can affect what characters can do and what problems arise.',
 'A setting is not just a location name. “Ilorin” gives place, but “an overcrowded Ilorin motor park at dawn during heavy rain” adds time and physical/social circumstances that can shape events.',
 'THEME is an important central idea explored through the text—for example honesty, responsibility, friendship, courage, greed or consequences of poor choices. State themes from patterns in events, conflicts and character decisions, not from guesswork.',
 'Theme is not the same as PLOT. “A boy loses money and later returns a wallet he finds” describes events; “honesty when facing temptation” expresses an idea those events may explore.',
 'STYLE is the writer’s manner of presenting the story through choices such as vocabulary/diction, sentence patterns, description, dialogue, imagery, tone, pace and narrative presentation. At JSS1, identify clear effects rather than memorising advanced labels.',
 'Example of style: short sentences—“The door slammed. Footsteps stopped. Silence.”—can create a fast, tense effect. A longer descriptive sentence can slow the pace and make readers observe a scene.',
 'APPRECIATION means reading with understanding and responding thoughtfully to how the prose works. NERDC expects learners to read class-appropriate prose, not merely recite definitions.',
 'Before reading, preview the title/context and predict carefully. During reading, track characters, setting, unfamiliar words, major events and questions. After reading, map the plot and discuss characterisation, style, setting and theme with evidence.',
 'PREDICTIVE QUESTIONS ask what may happen next and why, using clues. REFLECTIVE QUESTIONS ask learners to think about events, choices, meanings or their responses after reading. NERDC explicitly recommends both during prose reading.',
 'Evidence formula: CLAIM → TEXTUAL EVENT/DETAIL → EXPLANATION. Example: “Bisi is responsible because she returns to complete the assigned task even after her friends leave; her choice shows commitment to duty.”',
 'Do not confuse AUTHOR with NARRATOR/CHARACTER. The author creates the work; a narrator is the voice telling the story. This clarification supports accurate appreciation, although NERDC does not require advanced point-of-view taxonomy here.',
 'A good PLOT SUMMARY selects the major events in logical order and leaves out unnecessary description. A CHARACTER SKETCH focuses on who the character is and how the text reveals that person. A THEME RESPONSE focuses on an idea developed by the whole text.',
 'NARRATIVE vs DESCRIPTIVE CHECK: If removing the event sequence destroys the passage’s main purpose, it is strongly narrative. If removing sensory/qualifying detail destroys the main impression, it is strongly descriptive. Many prose texts contain both.',
 'AVORA PROSE ROUTINE: READ → IDENTIFY TYPE/DOMINANT PURPOSE → MAP PLOT → ANALYSE CHARACTER → LOCATE SETTING → INFER THEME → NOTICE STYLE → SUPPORT EVERY INTERPRETATION WITH EVIDENCE.'
 ],
 workedExamples:[
 'DEFINITION: A made-up school story written in ordinary sentences and paragraphs is prose fiction even if its school setting feels realistic.',
 'FUNCTION: A story about peer pressure may entertain through events while also helping readers reflect on friendship, courage and decision-making.',
 'NARRATIVE: “Kunle missed the bus, borrowed a bicycle and reached school before assembly ended.” Connected events dominate.',
 'DESCRIPTIVE: “The old classroom smelled of chalk; sunlight leaked through wooden shutters onto scarred desks.” Creating an impression dominates.',
 'MIXED PROSE: A story may narrate a journey and include a descriptive paragraph about the destination. The presence of description does not cancel the narrative form of the whole story.',
 'PLOT: Ada hides a broken trophy → another learner is blamed → Ada sees the unfair punishment → she confesses → the punishment is corrected. The events connect through choices and consequences.',
 'PLOT MAP: Opening—team prepares for match; Problem—captain is injured; Development—players disagree; Turning point—quiet substitute proposes a plan; Outcome—team cooperates successfully.',
 'CAUSE/EFFECT: Because Chidi ignores the weather warning, he becomes stranded; the decision causes the later problem.',
 'DIRECT CHARACTERISATION: “Mr Bello was patient.” The narrator states the trait.',
 'INDIRECT CHARACTERISATION: “Mr Bello explained the problem a third time without raising his voice.” The action suggests patience.',
 'CHARACTER SKETCH: Trait—determined. Evidence—Amara practises after repeated failures. Motivation—she wants to represent her school. Role—her persistence drives the central conflict toward resolution.',
 'WEAK CHARACTER CLAIM: “Tayo is kind because I like him.” This gives no textual evidence.',
 'SETTING: “A riverside village during the rainy season” supplies place/time/environment; flooded paths may then affect the plot.',
 'THEME: If several events show characters choosing truth despite personal cost, honesty/integrity may be a supported theme.',
 'PLOT vs THEME: “The sisters quarrel over inherited land and later reconcile” is plot summary; “family conflict and reconciliation” expresses thematic ideas.',
 'STYLE—PACE: “Run. Now.” can create urgency. The effect comes from brief sentence structure in context.',
 'STYLE—DESCRIPTION: Precise sensory detail can slow the pace and make the reader observe a setting closely.',
 'PREDICTION: “Because the character secretly packs a bag, I predict she may leave; the packed bag is my clue.” This is evidence-based rather than random guessing.',
 'REFLECTION: “The character could have asked for help before lying; the lie worsened the conflict” evaluates a choice using story events.',
 'APPRECIATION RESPONSE: “The writer uses the crowded market setting to intensify Kemi’s difficulty finding her brother; the setting actively affects the problem rather than serving as background only.”'
 ],
 misconceptions:['prose fiction means every statement in the text is factual','fiction means a writer is trying to deceive the reader','all prose is fiction','narrative prose contains no description','descriptive prose cannot contain any action','plot is merely every detail in the order printed','a plot diagram must force every story into exactly the same shape','character and characterisation mean the same thing','personality traits can be guessed without evidence','setting means place only','theme is the same as plot summary','theme is always a one-word moral','style means handwriting or font','dialogue automatically makes prose into drama','the narrator is always the author','appreciating prose means saying whether you liked it without evidence'],
 guidedPractice:[
 'TYPE TEST: compare four original passages and classify each as mainly narrative or descriptive, underlining the textual evidence that establishes the dominant purpose.',
 'NERDC STORY MAP: after reading a short original prose text, map setting, characters, problem, major events, turning point and outcome.',
 'CAUSE/EFFECT CHAIN: connect five major plot events with “because/therefore” statements to test whether the learner understands development rather than memorising sequence.',
 'CHARACTER SKETCH LAB: use a supplied character to record physical description, traits, motivations, role and one piece of evidence for every interpretive claim.',
 'SHOW OR TELL: identify direct and indirect characterisation in short extracts and explain what trait the evidence reveals.',
 'SETTING EFFECT: change one setting condition (time/weather/social environment) and discuss which plot events would logically change and why.',
 'THEME EVIDENCE LADDER: move from event → repeated pattern/conflict → possible theme → two supporting details.',
 'STYLE SPOTLIGHT: compare a fast action paragraph and a slow descriptive paragraph; identify sentence/detail choices and explain their effect.',
 'PREDICT/REFLECT: pause during a prose reading to make an evidence-based prediction; after reading, revisit the prediction and answer a reflective question using the outcome.'
 ],
 independentPractice:[
 'Read an age-appropriate short prose text and produce a complete story map showing characters, setting, central problem, major events, turning point and outcome.',
 'Write a 200–300 word character sketch of one character, covering relevant physical description, personality traits, motivation and role, with evidence from the text.',
 'Compare one narrative and one descriptive passage. Explain the dominant purpose of each and quote/paraphrase at least three details that support your classification.',
 'Write an appreciation paragraph explaining how one setting or stylistic choice affects the plot, character or reader’s experience. Use claim → evidence → explanation.',
 'After reading a complete class-appropriate prose text, identify and explain one theme using at least two separate events/character choices as evidence.'
 ],
 source:{authority:'NERDC Revised BEC 2025',url:'https://nerdc.gov.ng',verified:'OFFICIAL_PROSE_FICTION_SCOPE_PRESERVED_AND_NIGERIAN_FME_RESOURCE_CROSSCHECKED'},
 mastery:{criterion:'Learner explains prose fiction/functions, distinguishes narrative and descriptive prose, accurately analyses plot/characterisation/style/setting/theme with evidence, completes a story map and character sketch, and reads/appreciates an age-appropriate prose text at at least 80% mastery.',status:'DEEP_WHEN_PASSED'}
}];