export type Jss1LetterQ={id:string;classLevel:'JSS1';subject:'English Language';topic:'Writing Informal and Formal Letters';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1LetterQ=>({id:`nerdc25-auth-jss1-eng-letter-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Writing Informal and Formal Letters',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1LetterQuestions:Jss1LetterQ[]=[
q(1,'Which two letter types does NERDC require in this JSS1 topic?',['Formal and informal','Business and electronic only','Invitation and apology only','Narrative and descriptive'],'Formal and informal','The curriculum explicitly identifies formal and informal letters as the two types for this topic.',1,'types'),
q(2,'Which situation most clearly requires an informal letter?',['Writing to a close friend about your new school','Requesting permission from your principal','Writing officially to a government office','Applying formally to an organisation'],'Writing to a close friend about your new school','A close friend is a familiar personal audience, matching an informal letter.',1,'audience'),
q(3,'Which situation most clearly requires a formal letter?',['Writing to your principal to request permission','Telling your cousin about a holiday','Thanking a close friend for a birthday gift','Sharing family news with an aunt'],'Writing to your principal to request permission','Communication with a school authority for an official request requires formal conventions.',1,'audience'),
q(4,'How many addresses does NERDC prescribe for a formal letter?',['Two','One','Three','None'],'Two','The curriculum lists two addresses among the conventional features of a formal letter.',1,'formal format'),
q(5,'How many addresses does NERDC prescribe for an informal letter?',['One','Two','Three','None'],'One','The curriculum lists one address for an informal letter.',1,'informal format'),
q(6,'Which feature is specifically required for the formal letter but not listed as a core informal feature by NERDC?',['An adequate heading','A body','An opening salutation','A closing'],'An adequate heading','NERDC lists an adequate heading among the formal-letter features.',1,'heading'),
q(7,'What is the main purpose of a formal-letter heading?',['To state the subject/purpose clearly','To greet the recipient','To replace the body','To provide the writer’s address'],'To state the subject/purpose clearly','A specific heading lets the official reader understand the matter quickly.',1,'heading'),
q(8,'Which is the stronger formal heading?',['REQUEST FOR PERMISSION TO BE ABSENT FROM SCHOOL','LETTER','HELLO PRINCIPAL','MY STORY'],'REQUEST FOR PERMISSION TO BE ABSENT FROM SCHOOL','A formal heading should identify the specific subject rather than merely announce that the document is a letter.',1,'heading quality'),
q(9,'Which opening best suits a formal request to a principal?',['I am writing to request permission to be absent from school on Friday.','Hi! Guess what?','How are you enjoying yourself?','What’s up, Principal?'],'I am writing to request permission to be absent from school on Friday.','It states the purpose directly and respectfully in an appropriate formal register.',1,'formal tone'),
q(10,'Which opening best suits an informal letter to a close friend?',['How are you and everyone at home? I have been eager to tell you about my new school.','I hereby wish to bring the aforementioned matter to your attention.','REQUEST FOR OFFICIAL CONSIDERATION','To whom it may concern.'],'How are you and everyone at home? I have been eager to tell you about my new school.','The language is warm and personal while still being clear and grammatical.',1,'informal tone'),
q(11,'Which statement is correct?',['Informal writing can be conversational without being careless','Informal letters do not need grammar or punctuation','Formal letters should contain emojis to appear friendly','All letters should use exactly the same register'],'Informal writing can be conversational without being careless','Informality concerns relationship and register; accuracy and organisation still matter.',1,'register'),
q(12,'Which sequence best organises a simple formal-letter body?',['State purpose → give necessary details/reasons → courteous requested action/conclusion','Greetings for one page → unrelated story → purpose','Heading → signature → reason → salutation','Closing → address → body'],'State purpose → give necessary details/reasons → courteous requested action/conclusion','A formal reader should encounter the purpose early, followed by relevant support and a clear courteous ending.',2,'organisation'),
q(13,'Why are paragraphs important in either letter type?',['They organise related ideas and make the message easier to follow','They make the letter automatically formal','They replace punctuation','Every sentence must be a separate paragraph'],'They organise related ideas and make the message easier to follow','Paragraphs give different parts of the message clear functions and improve coherence.',1,'paragraphing'),
q(14,'Which is inappropriate in an ordinary formal letter to a school authority?',['Random slang and emojis','A clear purpose','Relevant facts','Respectful language'],'Random slang and emojis','Official communication normally requires restrained, respectful language rather than chat-style features.',1,'formal register'),
q(15,'A learner writes a beautifully formatted letter to the principal but never states why permission is needed. What is the main problem?',['The task content is incomplete even though the format looks correct','A formal letter never needs a reason','The second address should be removed','The letter should become informal'],'The task content is incomplete even though the format looks correct','Format and content are both required; layout cannot replace the information demanded by the task.',2,'task fulfilment'),
q(16,'Which planning sequence is strongest?',['Audience → purpose → type → required format → key points → paragraph order','Closing → signature → guess audience','Write everything first and read the task later','Count words → add greetings → choose purpose'],'Audience → purpose → type → required format → key points → paragraph order','Planning from audience and purpose ensures that format, tone and content all fit the task.',2,'planning'),
q(17,'A letter to a principal has one address, “Hi Principal!”, no heading and ends “Cheers”. What is the best diagnosis?',['It mixes informal conventions into a formal task','It is correct because the recipient is known','It needs only a longer body','It should remove all addresses'],'It mixes informal conventions into a formal task','The official audience requires the formal features prescribed by the curriculum and an appropriate register.',2,'editing'),
q(18,'Why should a learner not simply memorise one sample letter?',['A new task may change the audience, purpose and required content even when the format type is the same','Every letter has completely different grammar','Samples are never useful','Formal letters have no conventions'],'A new task may change the audience, purpose and required content even when the format type is the same','A model teaches conventions, but the actual prompt determines what information must be communicated.',2,'transfer'),
q(19,'Which item belongs to the final editing check for a formal letter?',['Correct addresses, salutation, heading, task content, tone, grammar, closing and signature','Only handwriting size','Only the number of paragraphs','Only whether the letter is long'],'Correct addresses, salutation, heading, task content, tone, grammar, closing and signature','Effective editing checks format, communication, register and language accuracy together.',2,'editing'),
q(20,'A task says: “Write to your friend explaining why you changed schools.” What is the best approach?',['Choose informal format, plan the reasons/details, use a natural personal tone, organise paragraphs, then edit','Use two addresses and an official heading because changing schools is serious','Write to the principal instead','Use formal vocabulary throughout because all school topics are formal'],'Choose informal format, plan the reasons/details, use a natural personal tone, organise paragraphs, then edit','Letter type depends primarily on the intended recipient and communicative situation; the friend makes this an informal task.',3,'integrated writing decision')
];