export type Jss1LitQ={id:string;classLevel:'JSS1';subject:'English Language';topic:'Introduction to Literature';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1LitQ=>({id:`nerdc25-auth-jss1-eng-litintro-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Introduction to Literature',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1IntroductionLiteratureQuestions:Jss1LitQ[]=[
q(1,'Which description best fits literature?',['Artistic use of language to express and explore human experiences, ideas, feelings or imagination','Only factual school notes','Any list of words','Only printed novels'],'Artistic use of language to express and explore human experiences, ideas, feelings or imagination','Literature uses language artistically to represent and explore experience and ideas.',1,'meaning'),
q(2,'Which three genres does NERDC explicitly name in this topic?',['Prose, drama and poetry','Biography, letter and report','News, advert and memo','Noun, verb and adjective'],'Prose, drama and poetry','The performance objective explicitly names prose, drama and poetry.',1,'genres'),
q(3,'Which two major categories does NERDC require learners to identify?',['Oral and written literature','Old and new literature','Long and short literature','Local and foreign only'],'Oral and written literature','NERDC lists oral and written as the two broad types/categories.',1,'categories'),
q(4,'Which is most characteristic of prose?',['Language mainly organised in sentences and paragraphs','Character labels and stage directions as the main structure','Verse lines are compulsory','It must always be spoken from memory'],'Language mainly organised in sentences and paragraphs','Literary prose is normally organised primarily through sentences and paragraphs.',1,'prose'),
q(5,'Which feature most strongly suggests drama?',['Action presented for performance through characters and dialogue','Paragraphs alone','A compulsory rhyme scheme','Two addresses'],'Action presented for performance through characters and dialogue','Drama is performance-centred and commonly uses dialogue and stage action.',1,'drama'),
q(6,'Which statement about poetry is correct?',['Poetry may use lines, stanzas, imagery and rhythm, but every poem need not rhyme','Every poem must rhyme','Poetry is always prose','Poetry cannot express real-life experiences'],'Poetry may use lines, stanzas, imagery and rhythm, but every poem need not rhyme','Rhyme is possible but is not a universal requirement of poetry.',1,'poetry'),
q(7,'A traditional story is performed aloud by an elder and passed from generation to generation. Which category best describes this mode?',['Oral literature','Written literature only','Formal letter','Report writing'],'Oral literature','Its primary transmission here is spoken performance.',1,'oral literature'),
q(8,'A play script printed in a book is best classified as what genre?',['Drama','Prose because it is printed','Poetry because characters speak','Oral literature only'],'Drama','Printing does not change the literary genre; the script is structured as drama.',1,'genre vs medium'),
q(9,'Why are “oral/written” and “prose/drama/poetry” not identical classifications?',['The first concerns mode of transmission while the second concerns literary form/genre','They mean exactly the same thing','Only oral literature has genres','Written literature cannot be drama'],'The first concerns mode of transmission while the second concerns literary form/genre','They answer different questions about a literary work.',2,'classification'),
q(10,'Which example best shows literature reflecting school life?',['A story about pupils facing choices concerning friendship, rules and examinations','A random multiplication table','A dictionary list with no literary context','A bus timetable'],'A story about pupils facing choices concerning friendship, rules and examinations','Those experiences can represent recognisable aspects of school life.',1,'literature and life'),
q(11,'A story shows a pupil returning a lost wallet even when nobody is watching. Which value is most directly reflected?',['Honesty','Greed','Carelessness','Jealousy'],'Honesty','The character chooses to return property that is not theirs, providing evidence of honesty.',1,'moral values'),
q(12,'Why should a learner give evidence when identifying a value in literature?',['The interpretation should be supported by actions, events or language in the work','Any positive word is automatically correct','Evidence is needed only in mathematics','The title always gives every value'],'The interpretation should be supported by actions, events or language in the work','Evidence connects an interpretation to what the work actually presents.',2,'evidence'),
q(13,'A story contains several lines of dialogue. Must it therefore be drama?',['No; prose stories can also contain dialogue','Yes, all dialogue is drama','Yes, if quotation marks are used','No, because drama has no dialogue'],'No; prose stories can also contain dialogue','Genre depends on the work’s overall form, not the presence of a single feature.',2,'genre distinction'),
q(14,'Which statement about literature reflecting life is strongest?',['Even imaginative events can represent real human behaviour, relationships and values','Every event in literature must have happened exactly in real life','Talking animals can never reflect human life','Literature cannot reflect society'],'Even imaginative events can represent real human behaviour, relationships and values','Imaginative representation can still explore recognisable human experiences.',2,'reflection of life'),
q(15,'If a story depicts a greedy character, what should a reader avoid assuming?',['That the work automatically approves of greed','That characters can make poor choices','That consequences may reveal values','That literature can explore behaviour'],'That the work automatically approves of greed','Depiction is not the same as approval; context and consequences matter.',2,'critical appreciation'),
q(16,'Which resource matches NERDC’s experiential approach to this topic?',['Story sessions, drama, poetry readings and audio/video tales','Only grammar substitution tables','Only mathematical charts','Only address templates'],'Story sessions, drama, poetry readings and audio/video tales','NERDC lists these resources so learners can encounter literature through reading, listening and performance.',1,'learning experience'),
q(17,'What does it mean to appreciate an age-appropriate literary work at introductory level?',['Understand and respond thoughtfully to its form, experience, ideas/values and supporting evidence','Memorise only its title','Count every word','Copy it without discussion'],'Understand and respond thoughtfully to its form, experience, ideas/values and supporting evidence','Appreciation involves meaningful engagement rather than definition memorisation alone.',2,'appreciation'),
q(18,'Which response gives better evidence?',['“It reflects responsibility because Ada accepts her duty and completes the task despite wanting to leave.”','“It reflects responsibility because responsibility is good.”','“It is literature because I said so.”','“It has a moral because all stories do.”'],'“It reflects responsibility because Ada accepts her duty and completes the task despite wanting to leave.”','The answer links the value directly to a character’s action.',2,'evidence'),
q(19,'A spoken traditional tale is later printed in a book. What is the most careful conclusion?',['Oral and written traditions can interact; consider the version and context being discussed','It was never oral literature','Printing makes it poetry','It can no longer have any oral-tradition features'],'Oral and written traditions can interact; consider the version and context being discussed','A work can move between transmission modes while retaining features or history from oral tradition.',3,'classification nuance'),
q(20,'Which sequence best supports literary appreciation?',['Experience the work → identify category/genre → notice experiences/ideas → connect to life/value → support with evidence','Guess a moral → ignore the work → memorise the title','Count paragraphs → choose any value','Identify one character → stop reading'],'Experience the work → identify category/genre → notice experiences/ideas → connect to life/value → support with evidence','This sequence moves from the actual work to a supported interpretation.',3,'integrated appreciation')
];