export type Jss1NVAQuestion={id:string;classLevel:'JSS1';subject:'English Language';topic:'Parts of speech: Nouns, Verbs and Adjectives';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1NVAQuestion=>({id:`nerdc25-auth-jss1-eng-nva-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Parts of speech: Nouns, Verbs and Adjectives',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1NVAQuestions:Jss1NVAQuestion[]=[
q(1,'Which statement about nouns is most accurate?',['Nouns can name people, places, objects, substances, events, qualities, states or ideas','Nouns are only objects we can touch','Every noun must begin with a capital letter','Every noun has a plural form'],'Nouns can name people, places, objects, substances, events, qualities, states or ideas','Nouns include concrete items and abstract concepts such as honesty, joy and education.',1,'noun foundation'),
q(2,'Which word is an abstract noun?',['patience','table','goat','bell'],'patience','Patience names a quality rather than a physical object perceived directly through the senses.',1,'noun types'),
q(3,'Which is a proper noun?',['Nigeria','country','city','river'],'Nigeria','Nigeria names a particular country and is conventionally capitalised as a proper noun.',1,'proper nouns'),
q(4,'Which expression uses the uncountable noun “information” naturally in standard English?',['some information','an information','three informations','many informations'],'some information','Information is normally treated as an uncountable noun; “some information” or “a piece of information” is appropriate.',1,'countability'),
q(5,'In “The pupils planted trees,” what is the function of “The pupils”?',['subject','object','adjective','verb'],'subject','The noun phrase “The pupils” is the subject performing the action expressed by “planted.”',1,'noun function'),
q(6,'In “We planted trees,” what is the function of “trees”?',['object','subject','linking verb','adjective'],'object','“Trees” is the noun receiving/completing the action of the transitive verb “planted.”',1,'noun function'),
q(7,'Which statement about verbs is most accurate?',['Verbs can express actions, events, processes or states','Every verb is a visible physical action','Forms of “be” are never verbs','Verbs cannot change form'],'Verbs can express actions, events, processes or states','Words such as run express action, while know, seem and be can express states or relationships.',1,'verb foundation'),
q(8,'Which sentence contains a helping/auxiliary verb plus a main verb?',['Mariam has completed the project','Mariam owns a bicycle','The project seems difficult','Pupils read books'],'Mariam has completed the project','“Has” helps form the perfect verb phrase while “completed” carries the main lexical meaning.',1,'auxiliary verbs'),
q(9,'In which sentence is “has” functioning as the main verb?',['Mariam has a bicycle','Mariam has completed the work','Mariam has been reading','Mariam has finished'],'Mariam has a bicycle','Here “has” means possesses and carries the main lexical meaning rather than helping another verb.',2,'verb function in context'),
q(10,'Which sentence contains an intransitive verb use?',['The baby slept','Ngozi opened the door','The pupil kicked the ball','The cook prepared rice'],'The baby slept','“Slept” has no object in this sentence, so it is intransitive in this use.',1,'transitivity'),
q(11,'Which sentence contains a linking verb followed by an adjective?',['The soup smells delicious','The cook smells the soup','The girl opened the pot','They carried food'],'The soup smells delicious','“Smells” links the subject “soup” to the adjective “delicious,” which describes the soup.',2,'linking verbs'),
q(12,'Which statement about adjectives is correct?',['An adjective can describe a noun before it or after a linking verb','An adjective must always stand immediately before a noun','Every adjective ends in -ful','Adjectives can describe only colours'],'An adjective can describe a noun before it or after a linking verb','Compare “a difficult question” and “The question is difficult.” Both uses are adjectival.',1,'adjective foundation'),
q(13,'In “The children are cheerful,” what part of speech is “cheerful”?',['adjective','noun','verb','preposition'],'adjective','“Cheerful” follows the linking verb “are” and describes the subject “children.”',1,'predicative adjective'),
q(14,'In “They clean the classroom every day,” what part of speech is “clean”?',['verb','adjective','noun','conjunction'],'verb','“Clean” expresses what the subject does and functions as the predicate verb.',1,'context-sensitive class'),
q(15,'In “They entered a clean classroom,” what part of speech is “clean”?',['adjective','verb','noun','pronoun'],'adjective','“Clean” modifies the noun “classroom,” so its function is adjectival.',1,'context-sensitive class'),
q(16,'In “Water the young plants,” which classification is correct?',['Water = verb; plants = noun; young = adjective','Water = noun; plants = verb; young = noun','Water = adjective; plants = noun; young = verb','All three words are nouns'],'Water = verb; plants = noun; young = adjective','The imperative “Water” expresses the action, “plants” names what receives it, and “young” describes the plants.',2,'integrated classification'),
q(17,'Which set correctly shows “light” in three different classes?',['the light (noun); a light bag (adjective); light the candle (verb)','a light bag (noun); light the candle (adjective); the light (verb)','all three are adjectives','all three are nouns'],'the light (noun); a light bag (adjective); light the candle (verb)','Word class depends on grammatical use in context, not spelling alone.',2,'word-class flexibility'),
q(18,'Why is a suffix such as -ness only a clue to word class rather than absolute proof?',['Words should still be classified by their actual grammatical function in context','Suffixes never occur in English','Every -ness word is a verb','Context cannot affect grammar'],'Words should still be classified by their actual grammatical function in context','Morphological endings are useful evidence, but sentence behaviour/function should confirm classification.',2,'grammar evidence'),
q(19,'Sentence: “A careful farmer inspected the young maize plants.” Which analysis is correct?',['farmer/maize/plants = nouns; inspected = verb; careful/young = adjectives','careful/young = nouns; farmer = verb','inspected = adjective; plants = verb','all words are nouns'],'farmer/maize/plants = nouns; inspected = verb; careful/young = adjectives','The nouns name entities, “inspected” forms the predicate, and “careful/young” modify nouns.',2,'passage analysis'),
q(20,'What is the strongest way to identify an unfamiliar word’s part of speech in a sentence?',['Examine its position, grammatical function, connected words and possible form changes','Use its spelling only','Assume its most familiar dictionary meaning','Choose noun whenever uncertain'],'Examine its position, grammatical function, connected words and possible form changes','Reliable classification combines contextual syntax, function and morphology instead of relying on one superficial clue.',3,'integrated grammar reasoning')
];