export const jss1MythsLegendsDeepLessons=[{
 topicId:'revised2025-jss1-english-myths-legends-deep',classLevel:'JSS1',subject:'English Language',topic:'Myths and Legends',
 objectives:['Explain myths and legends at an age-appropriate introductory level','Identify features of myths and legends using evidence','Recognise NERDC’s African and non-African scope','Explain themes in myths and legends','Recognise supernatural figures and superstitious beliefs as curriculum-listed features/themes where present','Distinguish myth from legend and relate both carefully to folktales','Retell myths and legends faithfully','Identify supported moral lessons','Narrate and dramatize myths and legends effectively','Document a myth or legend from a reliable identified source'],
 prerequisites:['Introduction to Literature','Folktales','theme versus moral lesson','oral retelling and narration'],
 teaching:[
 'MYTHS AND LEGENDS are traditional narratives, but the labels describe different kinds of traditional story. NERDC asks learners to identify their features, explain themes, retell them, identify moral lessons and narrate examples.',
 'A MYTH is a traditional narrative that may explain origins, natural phenomena, customs, sacred ideas or a people’s understanding of the world and may involve gods, supernatural beings or extraordinary events. When studying a myth, say “the story explains/presents/believes…” rather than treating its supernatural explanation as scientific proof.',
 'A LEGEND is a traditional narrative associated with a person, place or event remembered as connected in some way with the past. Legends may contain historical elements alongside exaggeration, supernatural material or details that cannot be independently verified.',
 'A useful distinction is: MYTH often centres on origins, sacred/traditional explanations or supernatural order; LEGEND often centres on a remembered hero, person, place or event linked to the past. This is a guide, not a claim that every traditional narrative fits perfectly into one box.',
 'FOLKTALE is the broader traditional-story form studied in the previous topic, often shared for entertainment and lessons. Myths, legends and folktales can overlap in oral tradition, themes and supernatural elements; classification should use the particular narrative’s focus and cultural function.',
 'NERDC includes AFRICAN AND NON-AFRICAN tales comprising myths and legends. Learners should compare actual narratives, not use one story to make claims about an entire continent or culture.',
 'FEATURES are recognisable characteristics supported by the narrative. NERDC specifically names SUPERNATURAL FIGURES and SUPERSTITIOUS BELIEFS among features/themes to be studied.',
 'SUPERNATURAL FIGURES are beings or agents presented as having powers beyond ordinary natural human experience—for example deities, spirits or extraordinary beings within a narrative tradition. Identify what the story presents; do not assert the being’s real-world existence as a classroom fact.',
 'A SUPERSTITIOUS BELIEF, in this curriculum context, is a traditional belief connecting actions, signs, objects or events with luck, misfortune or unseen causes without established scientific evidence. Describe it respectfully as a belief represented in the story rather than mocking believers or presenting it as verified science.',
 'Not every myth or legend must contain every listed feature. A learner should say “This narrative contains a supernatural figure because…” and cite evidence rather than memorising a checklist and forcing it onto every tale.',
 'MYTHS may explain an ORIGIN: why a feature of the world, a practice, a place or an aspect of life is understood to exist within the tradition. The explanation belongs to the narrative/cultural tradition and should be reported accurately as such.',
 'LEGENDS often connect extraordinary storytelling to a named or remembered person, place or past event. A legendary figure may be celebrated for courage, wisdom, strength, leadership or another quality, but the narrative details still need critical reading.',
 'THEME is a central idea explored through events—for example courage, pride, obedience, sacrifice, justice, loyalty, greed, destiny or responsibility.',
 'MORAL LESSON is a practical lesson a reader/listener may draw from the characters’ choices and consequences. “Pride” can be a theme; “Excessive pride can lead to a person’s downfall” can be a moral lesson.',
 'Supernatural content is not itself automatically the theme. A spirit may be a character/feature while the story’s theme is obedience, courage or greed.',
 'Likewise, a superstitious belief represented in a story is not automatically its moral lesson. Ask what choices, conflicts and consequences develop across the whole narrative.',
 'RETELLING requires fidelity to the source narrative: preserve central characters, setting/context, important events, sequence, outcome and essential meaning while expressing the story in your own words.',
 'When retelling a MYTH, preserve the traditional explanation or supernatural element as the narrative presents it, using attribution such as “According to the story…” where needed.',
 'When retelling a LEGEND, preserve the story’s claimed connection to the person/place/event but do not add invented historical certainty. “The legend says…” is different from “Historical records prove…”.',
 'NARRATION uses clear pronunciation, appropriate pace, pauses, tone, gesture and eye contact to help listeners follow the narrative. Voice should clarify the story rather than overwhelm it.',
 'DRAMATIZATION converts suitable scenes into spoken dialogue and action. It should preserve the key event, character motivation and meaning rather than rewrite the traditional narrative beyond recognition.',
 'DOCUMENTATION means recording a myth or legend carefully through writing, audio or another approved format. NERDC specifically asks learners to document myths and stories about legends.',
 'For community documentation, record the title/name if known, who narrated/provided it, relevant place/community information supplied by the source, date/context of collection where appropriate, the narrative itself, and the learner’s separate notes on features/theme/lesson.',
 'Do not invent missing cultural details. If the storyteller does not know an origin or date, write that it is unknown/not supplied rather than filling the gap.',
 'Respectful documentation distinguishes three layers: SOURCE SAYS → NARRATIVE PRESENTS → LEARNER INTERPRETS. Keeping these separate prevents accidental distortion.',
 'COMPARING MYTH AND LEGEND: ask what the narrative centres on, what kind of characters/forces appear, whether it explains origins/world order or attaches itself to a remembered person/place/event, and what themes/values the events develop.',
 'COMPARING WITH FOLKTALES: all can circulate traditionally and teach/entertain, but myth often carries explanatory/sacred significance, legend often claims a past connection, and folktale is commonly discussed as a traditional tale without requiring either focus.',
 'CRITICAL APPRECIATION does not mean disrespect. Learners can understand what a community narrative means, identify its values and appreciate its storytelling while distinguishing traditional/supernatural claims from independently verified facts.',
 'AVORA ROUTINE: EXPERIENCE THE NARRATIVE → CLASSIFY CAREFULLY → IDENTIFY FEATURE WITH EVIDENCE → MAP EVENTS → EXPLAIN THEME → DRAW SUPPORTED MORAL → RETELL/NARRATE → DOCUMENT SOURCE RESPONSIBLY.'
 ],
 workedExamples:[
 'MYTH-LIKE FOCUS: A traditional narrative explains why, according to that tradition, a natural feature came into existence through actions of supernatural beings. Its origin-explanation focus supports classification as myth.',
 'LEGEND-LIKE FOCUS: A traditional story centres on a remembered warrior associated with a particular town and describes extraordinary deeds attributed to him. Its person/place/past connection supports classification as legend.',
 'SUPERNATURAL FIGURE: A spirit speaks to a traveller and performs an impossible act within the narrative. The spirit is a supernatural figure; this observation describes the story rather than proving spirits scientifically.',
 'SUPERSTITIOUS BELIEF: Characters believe a particular sign predicts misfortune. A careful response says, “The characters regard the sign as an omen,” not “The sign definitely causes misfortune.”',
 'THEME vs FEATURE: A supernatural being may be a feature; COURAGE may be the theme if the narrative repeatedly develops how characters respond to danger.',
 'THEME vs MORAL: PRIDE is a theme; “A person who refuses every warning because of pride may face avoidable consequences” is a possible moral supported by events.',
 'MYTH RETELLING: “According to the tale, the river began when…” accurately attributes a traditional origin explanation.',
 'UNSAFE CLAIM: “This proves exactly how the river was scientifically formed” goes beyond what a myth as literary material establishes.',
 'LEGEND RETELLING: “The legend says the hunter crossed the forest alone…” preserves the narrative’s claim without turning it automatically into verified history.',
 'DOCUMENTATION: “Narrated by [identified consenting source], recorded in [place/context], [date if required]” separates provenance from the learner’s analysis.',
 'MISSING INFORMATION: If the source does not know when the tale originated, write “origin date not supplied” rather than inventing a century.',
 'SEQUENCE: beginning situation → warning/challenge → character decision → supernatural/extraordinary encounter → consequence → outcome is one possible event map, not a compulsory template.',
 'CHARACTER EVIDENCE: If a hero returns despite danger to rescue companions, the action supports courage/loyalty more strongly than simply calling the hero “good.”',
 'MORAL EVIDENCE: If a character repeatedly ignores wise warnings and suffers the predicted consequence, a lesson about listening to sound advice is supported.',
 'MULTIPLE INTERPRETATIONS: A narrative may explore courage and loyalty simultaneously if both are developed by events.',
 'DRAMATIZATION: A decisive meeting between a legendary hero and community elders can become a scene with dialogue while preserving the original conflict and outcome.',
 'AFRICAN/NON-AFRICAN COMPARISON: Two supplied narratives may both include supernatural intervention but differ in what that intervention explains or how characters respond.',
 'MYTH/FOLKTALE OVERLAP: A traditional animal narrative that primarily entertains/teaches may be discussed as folktale; an origin-focused sacred/traditional explanation may be discussed as myth. Use context, not one superficial feature.',
 'LEGEND/FOLKTALE OVERLAP: A traditional story about a named past hero may share folktale motifs while its claimed historical connection supports discussion as legend.',
 'APPRECIATION: “The narrative uses an extraordinary test to explore responsibility; the hero succeeds only after accepting responsibility for the community” links feature, event and theme.'
 ],
 misconceptions:['myths are simply lies and therefore have no literary/cultural value','every supernatural story is automatically a myth','every story about an old person is a legend','myth and legend mean exactly the same thing','folktale, myth and legend can always be separated by one feature','supernatural figure automatically equals theme','superstitious belief automatically equals moral lesson','traditional belief should be presented as scientifically verified fact','traditional belief should be mocked because it is not scientific evidence','all African myths are alike','all non-African myths are alike','a legend is automatically proven history','retelling permits adding invented cultural facts','documentation means claiming the learner wrote the traditional narrative','theme and moral lesson are identical','good narration means exaggerating or shouting throughout'],
 guidedPractice:[
 'CLASSIFICATION CLINIC: examine four short original narrative summaries and decide myth-like, legend-like or folktale-like focus, citing two pieces of evidence and allowing overlap where justified.',
 'FEATURE + EVIDENCE: identify supernatural figures or represented superstitious beliefs in supplied narratives and state exactly what the text says without converting the belief into factual proof.',
 'THEME/MORAL GRID: separate characters/features, themes and possible moral lessons, supporting each interpretive answer with an event.',
 'RETELLING CHAIN: learners retell a supplied myth/legend in sequence; peers check whether central characters, extraordinary elements, turning points and outcome remain faithful.',
 'ATTRIBUTION PRACTICE: rewrite overconfident statements (“This is how the mountain was created”) as accurate literary attribution (“According to the myth…”).',
 'DRAMATIZATION: adapt one important scene for performance while preserving the narrative’s central event and cultural framing.',
 'AFRICAN/NON-AFRICAN TEXT COMPARISON: compare two supplied age-appropriate narratives on feature, theme and moral evidence without generalising beyond the texts.',
 'NERDC DOCUMENTATION PROJECT: with permission, obtain a community myth/legend from an identified source; document provenance, narrative and learner analysis in separate sections.'
 ],
 independentPractice:[
 'Read/listen to an age-appropriate myth. Identify at least three features with evidence, explain one theme, state a supported moral lesson, and explain what the narrative traditionally accounts for or represents.',
 'Read/listen to an age-appropriate legend. Explain what person/place/event it is associated with, retell its major events, identify a theme and distinguish legendary claims from facts independently established in the supplied material.',
 'Orally narrate a myth or legend in 3–5 minutes using clear sequencing, pace, pauses and expression while preserving its central meaning.',
 'Document a myth or legend from a supplied book/recording or consenting community storyteller. Clearly identify the source and separate the narrative from your interpretation; do not invent missing provenance.',
 'Compare one African and one non-African myth/legend supplied for class, identifying one supported similarity and one difference in features/themes without making claims about whole cultures.'
 ],
 source:{authority:'NERDC Revised BEC 2025',url:'https://nerdc.gov.ng',verified:'OFFICIAL_MYTHS_LEGENDS_SCOPE_PRESERVED'},
 mastery:{criterion:'Learner identifies features/themes of myths and legends with evidence, recognises supernatural figures and represented superstitious beliefs appropriately, retells/narrates faithfully, draws supported moral lessons, and documents sources responsibly at at least 80% mastery.',status:'DEEP_WHEN_PASSED'}
}];