export type Jss1FolktaleQ={id:string;classLevel:'JSS1';subject:'English Language';topic:'Folktales';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1FolktaleQ=>({id:`nerdc25-auth-jss1-eng-folktale-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Folktales',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1FolktaleQuestions:Jss1FolktaleQ[]=[
q(1,'Which description best fits a folktale?',['A traditional story associated with a community/culture and passed on especially through storytelling','Any modern news report','Every story containing an animal','Only a story written by a known novelist'],'A traditional story associated with a community/culture and passed on especially through storytelling','Traditional sharing and storytelling are central to folktales, though tales can later be written or recorded.',1,'meaning'),
q(2,'Which range of folktales does NERDC explicitly include?',['African and non-African tales','African tales only','European tales only','Modern Nigerian novels only'],'African and non-African tales','The curriculum explicitly identifies African and non-African tales.',1,'scope'),
q(3,'Which is a purpose explicitly named by NERDC?',['Didactic lessons and entertainment','Only examination practice','Only advertising','Only historical dating'],'Didactic lessons and entertainment','NERDC names didactic lessons and entertainment among folktale purposes.',1,'purpose'),
q(4,'What does “didactic” mean in this context?',['Intended to teach or instruct','Impossible to retell','Written only for actors','Without any meaning'],'Intended to teach or instruct','A didactic story communicates instruction or a lesson.',1,'vocabulary'),
q(5,'Which statement about folktale features is safest?',['Not every folktale must contain every possible feature; use evidence from the tale','Every folktale must contain a talking tortoise','All folktales have exactly three characters','A repeated phrase alone proves a story is a folktale'],'Not every folktale must contain every possible feature; use evidence from the tale','Folktale traditions vary, so identification should use a combination of supported features and context.',2,'features'),
q(6,'Which can support oral storytelling and memory?',['Meaningful repetition or recurring phrases','Randomly changing the plot','Removing the ending','Mispronouncing names'],'Meaningful repetition or recurring phrases','Repetition can make a tale easier for tellers and listeners to follow and remember.',1,'oral features'),
q(7,'Which claim is incorrect?',['All folktales are animal stories','Some folktales contain human characters','Some may use imaginative beings','Folktales may later be written down'],'All folktales are animal stories','Animals are common in some traditions, but folktales are not limited to animal stories.',1,'misconception'),
q(8,'In literary discussion, what is a theme?',['A central idea explored through the story','The complete list of events','The storyteller’s name only','The number of paragraphs'],'A central idea explored through the story','Themes are important ideas such as greed, wisdom, courage or cooperation developed through events.',1,'theme'),
q(9,'Which pair correctly distinguishes theme and moral lesson?',['Theme: greed; Moral: greed can make a person lose what they already have','Theme: greed can cause loss; Moral: greed','They are always exactly the same phrase','Theme: three paragraphs; Moral: four paragraphs'],'Theme: greed; Moral: greed can make a person lose what they already have','A theme names an explored idea; a moral lesson states a practical lesson that may be drawn from the events.',2,'theme vs moral'),
q(10,'Why should a moral lesson be supported with story evidence?',['So the lesson grows from characters, events and consequences rather than being guessed','Because every tale has only one permitted sentence','Because morals depend on story length','Because evidence turns a folktale into drama'],'So the lesson grows from characters, events and consequences rather than being guessed','Interpretation should connect to what actually happens in the tale.',2,'evidence'),
q(11,'What is retelling?',['Recounting an existing tale in your own words while preserving its important events and meaning','Inventing a completely different ending and characters','Memorising every word exactly','Giving only the title'],'Recounting an existing tale in your own words while preserving its important events and meaning','A retelling may shorten details but should remain recognisably faithful to the source tale.',1,'retelling'),
q(12,'Which detail should normally be preserved in a retelling?',['The central problem and important events leading to the outcome','Every minor adjective','Every pause made by the original teller','The exact number of sentences'],'The central problem and important events leading to the outcome','Major events and meaning are essential; minor detail can often be compressed.',1,'retelling sequence'),
q(13,'Which sequence words can help make a retelling clear?',['At first, afterwards, eventually, finally','Blue, tall, sweet, quickly','Because only','Dear Sir, Yours faithfully'],'At first, afterwards, eventually, finally','Sequence expressions help listeners follow the order of events when used naturally.',1,'sequencing'),
q(14,'Which behaviour best demonstrates effective narration?',['Using clear speech, suitable pace, meaningful pauses and expressive tone','Shouting every sentence','Speaking so fast that no one follows','Changing the plot for excitement'],'Using clear speech, suitable pace, meaningful pauses and expressive tone','Oral performance should strengthen comprehension and engagement without distorting the tale.',1,'narration'),
q(15,'A learner says, “The tortoise is greedy because tortoises are always greedy in folktales.” What is wrong?',['The trait should be inferred from this character’s actions, not assumed from the animal species','Nothing; every tortoise character is identical','Greed cannot be a character trait','Animals cannot appear in folktales'],'The trait should be inferred from this character’s actions, not assumed from the animal species','Character analysis needs evidence from the particular tale.',2,'character evidence'),
q(16,'A tale makes listeners laugh at a trickster but later shows the trickster suffering for greed. What purposes may operate together?',['Entertainment and didactic teaching','Only grammar practice','Only factual reporting','Neither entertainment nor teaching'],'Entertainment and didactic teaching','A folktale can entertain while also presenting a lesson through consequences.',2,'purpose'),
q(17,'What is good practice when documenting a folktale heard from another person?',['Identify the storyteller/source and context appropriately rather than pretending you invented the traditional tale','Claim authorship yourself','Change the cultural source','Add invented facts and label them traditional'],'Identify the storyteller/source and context appropriately rather than pretending you invented the traditional tale','Careful documentation respects the source and distinguishes the learner’s commentary from the tale received.',2,'documentation'),
q(18,'Which comparison is responsible?',['These two supplied tales both use repeated tests, but their characters and outcomes differ','All African folktales are exactly the same','All non-African folktales teach one lesson','One tale proves what an entire culture believes'],'These two supplied tales both use repeated tests, but their characters and outcomes differ','Comparison should be based on the actual texts rather than cultural stereotypes.',2,'comparison'),
q(19,'If two learners state different moral lessons from the same folktale, can both be reasonable?',['Yes, if each interpretation is supported by events and evidence','No, every folktale has exactly one sentence that all readers must give','Yes, even without reading the tale','No folktale can have a moral lesson'],'Yes, if each interpretation is supported by events and evidence','Literary works can support more than one defensible interpretation when evidence supports each one.',3,'interpretation'),
q(20,'Which routine best demonstrates mastery of a folktale?',['Experience tale → identify features with evidence → map events → retell → explain theme → draw supported lesson → narrate/dramatize','Read title → guess moral → stop','Memorise definitions without hearing a tale','Change the story → call it a retelling'],'Experience tale → identify features with evidence → map events → retell → explain theme → draw supported lesson → narrate/dramatize','This integrates the knowledge and performance objectives NERDC expects.',3,'integrated mastery')
];