export type Jss1ThreeLevelQuestion={id:string;classLevel:'JSS1';subject:'English Language';topic:'Reading Passages to Answer Literal, Inferential and Critical Questions';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1ThreeLevelQuestion=>({id:`nerdc25-auth-jss1-eng-threelevel-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Reading Passages to Answer Literal, Inferential and Critical Questions',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1ThreeLevelQuestions:Jss1ThreeLevelQuestion[]=[
q(1,'Which description best matches a literal question?',['It asks for information directly stated in the passage','It always asks for the reader’s personal opinion','It requires a conclusion that has no textual clue','It asks the reader to rewrite the whole passage'],'It asks for information directly stated in the passage','Literal comprehension retrieves information that the text explicitly gives.',1,'literal comprehension'),
q(2,'Which sequence is useful for answering a literal question?',['question → key words → locate → check → answer','guess → copy everything → stop','opinion → title → answer','prediction → ignore text → answer'],'question → key words → locate → check → answer','The sequence focuses the reader on the exact information requested and verifies it in context.',1,'literal strategy'),
q(3,'Passage: “At 7:30 a.m., Aisha boarded the bus at Unity Road.” Where did Aisha board the bus?',['Unity Road','7:30 a.m.','Aisha','The passage does not say'],'Unity Road','“Where” asks for the directly stated place, Unity Road.',1,'literal precision'),
q(4,'Which formula best represents inference?',['textual clues + reasoning','personal preference + guessing','speed + pronunciation','title + copying'],'textual clues + reasoning','An inference connects evidence in the text to a reasonable unstated conclusion.',1,'inference foundation'),
q(5,'Kunle enters shaking water from his umbrella and his jacket is wet. What is the most reasonable inference?',['It was probably raining outside','Kunle won a football match','Kunle bought a new jacket','The building has no roof'],'It was probably raining outside','The wet umbrella and jacket are textual clues that reasonably support rain.',1,'supported inference'),
q(6,'Why is “Kunle won a football match” a weak inference from Question 5?',['The passage provides no clue about a football match','Football matches never happen in rain','Kunle cannot play football','All inferences must be literal facts'],'The passage provides no clue about a football match','Inference is not free guessing; it must be anchored in textual evidence.',1,'unsupported inference'),
q(7,'Which best describes critical comprehension?',['Evaluating an idea or decision using textual evidence and sound reasons','Finding only a name stated in the passage','Guessing what happens without clues','Reading every sentence aloud'],'Evaluating an idea or decision using textual evidence and sound reasons','Critical comprehension makes and justifies a judgement rather than merely retrieving or inferring information.',1,'critical comprehension'),
q(8,'A school cancels an outdoor event after an official severe-weather warning. Which is the strongest critical response?',['The cancellation was reasonable because the official warning identified a safety risk','I like cancellations','It was wrong because outdoor events are fun','The weather warning does not matter'],'The cancellation was reasonable because the official warning identified a safety risk','The answer states a judgement, cites evidence and gives the safety reason.',2,'critical evidence'),
q(9,'Does critical reading always mean disagreeing with the writer?',['No; a reader may agree, disagree or partly agree if the judgement is reasoned and evidence-based','Yes; criticism always means saying the writer is wrong','Yes; agreement is literal comprehension','No; critical questions need no evidence'],'No; a reader may agree, disagree or partly agree if the judgement is reasoned and evidence-based','Critical thinking concerns evaluation, not automatic opposition.',1,'critical thinking'),
q(10,'Passage directly says, “Tunde stayed indoors because he had a fever.” What level is “Why did Tunde stay indoors?”',['Literal','Inferential','Critical','Impossible to classify'],'Literal','Although the question begins with “why,” the reason is explicitly stated, so the task is literal retrieval.',2,'question classification'),
q(11,'What determines a comprehension level most reliably?',['What kind of thinking and evidence the text requires to answer','The first word of the question only','The length of the answer','Whether the passage has a title'],'What kind of thinking and evidence the text requires to answer','Question stems provide clues, but classification depends on whether the answer is stated, inferred or evaluated.',2,'classification'),
q(12,'What should happen to a pre-reading prediction when the passage contradicts it?',['Revise or reject the prediction to fit the evidence','Keep it because first guesses are always correct','Ignore the passage','Change the passage'],'Revise or reject the prediction to fit the evidence','Predictions prepare reading but remain provisional; textual evidence controls the final understanding.',1,'prediction'),
q(13,'Which is the best evidence habit for an inferential answer?',['Name the relevant clues and explain how they support the conclusion','State the conclusion repeatedly','Give a personal story instead of passage evidence','Copy the title only'],'Name the relevant clues and explain how they support the conclusion','A defensible inference exposes both its textual basis and its reasoning.',2,'inference evidence'),
q(14,'Which structure best supports a critical answer?',['judgement + evidence + reason/criterion','guess + emotion + repetition','title + first word + speed','quotation only'],'judgement + evidence + reason/criterion','Evaluation needs a conclusion, the text that supports it, and a defensible basis for the judgement.',2,'critical response structure'),
q(15,'Sentence: “The path was treacherous; loose stones made several walkers slip.” What does “treacherous” most likely mean here?',['dangerous or unsafe','colourful','very short','crowded with shops'],'dangerous or unsafe','The context clue “loose stones made several walkers slip” supports the meaning dangerous/unsafe.',2,'context inference'),
q(16,'Which answer is most likely unsupported?',['A conclusion that cannot be connected to any word, event or idea in the passage','A literal answer located in a sentence','An inference supported by two clues','A critical judgement supported by evidence and a safety reason'],'A conclusion that cannot be connected to any word, event or idea in the passage','Comprehension answers must remain accountable to the text.',1,'evidence'),
q(17,'A post recommends medicine to everyone only because “my neighbour says it works.” Which critical judgement is strongest?',['The support is weak because one neighbour’s claim is insufficient evidence for a general health recommendation','The claim must be correct because it is online','The neighbour’s opinion proves the medicine works for everyone','Evidence is unnecessary for health claims'],'The support is weak because one neighbour’s claim is insufficient evidence for a general health recommendation','The judgement evaluates the adequacy of the evidence using an appropriate reliability criterion.',3,'source evaluation'),
q(18,'Why is copying an entire paragraph often a poor literal answer?',['It may hide whether the learner identified the precise information requested','Long answers are always grammatically wrong','A passage can never be quoted','Literal questions require opinions'],'It may hide whether the learner identified the precise information requested','Good literal comprehension selects the relevant stated information rather than copying indiscriminately.',2,'answer precision'),
q(19,'Which option best describes “Find it → Work it out → Evaluate it with evidence”?',['Literal → Inferential → Critical','Critical → Literal → Inferential','Inferential → Critical → Literal','Fluency → Grammar → Writing'],'Literal → Inferential → Critical','The memory sequence matches direct retrieval, evidence-based inference and reasoned evaluation.',1,'three-level framework'),
q(20,'After answering three comprehension questions, which final check is strongest?',['Literal: locate the statement; Inferential: show clues plus reasoning; Critical: show judgement plus evidence plus reason','Check only whether every answer is long','Make every answer an opinion','Use the same sentence for all three levels'],'Literal: locate the statement; Inferential: show clues plus reasoning; Critical: show judgement plus evidence plus reason','The check verifies that each answer satisfies the distinctive evidence requirement of its comprehension level.',3,'integrated mastery')
];