export type Jss1SpeechQuestion={id:string;classLevel:'JSS1';subject:'English Language';topic:'Speech Sounds (Vowels and Consonants)';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1SpeechQuestion=>({id:`nerdc25-auth-jss1-eng-speech-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Speech Sounds (Vowels and Consonants)',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1SpeechQuestions:Jss1SpeechQuestion[]=[
q(1,'What is the main difference between a letter and a speech sound?',['A letter is written; a speech sound is produced and heard','A letter is heard but a sound is written','Every letter always represents exactly one sound','There is no difference'],'A letter is written; a speech sound is produced and heard','English spelling and pronunciation do not have a perfect one-to-one relationship, so sounds must be learned by listening and articulation as well as spelling.',1,'sound versus spelling'),
q(2,'Which description best fits a monophthong?',['A vowel whose quality remains relatively steady within the syllable','Two consonants written together','A vowel that always has two letters','A sound made only through the nose'],'A vowel whose quality remains relatively steady within the syllable','Monophthongs are pure vowels; the tongue/lip position does not make the clear two-part glide characteristic of a diphthong.',1,'monophthongs'),
q(3,'Which description best fits a diphthong?',['A vowel sound that glides from one vowel position toward another in one syllable','Any word containing two vowel letters','Two consonants pronounced at once','A vowel made with the lips completely closed'],'A vowel sound that glides from one vowel position toward another in one syllable','Diphthongs are classified by the movement of the vowel quality, not by the number of letters used in spelling.',1,'diphthongs'),
q(4,'Which word contains /iː/?',['sheep','ship','shop','cup'],'sheep','In a common British pronunciation model, sheep contains /iː/, while ship contains /ɪ/.',1,'vowel discrimination'),
q(5,'Which contrast helps distinguish /ɪ/ from /iː/?',['ship — sheep','fan — van','sip — zip','ten — den'],'ship — sheep','The two words contrast the short /ɪ/ vowel with long /iː/.',1,'minimal pairs'),
q(6,'Which word contains /ʊ/?',['book','food','bird','cat'],'book','Book commonly contains /ʊ/; food commonly contains /uː/.',1,'vowel identification'),
q(7,'Which pair contrasts /ʊ/ and /uː/?',['full — fool','pen — pain','thin — tin','light — right'],'full — fool','Full uses /ʊ/ and fool uses /uː/ in the target pronunciation model.',1,'vowel discrimination'),
q(8,'Which word begins with the diphthong /eɪ/?',['eight','eat','at','out'],'eight','Eight begins with /eɪ/, a glide toward /ɪ/.',1,'diphthong identification'),
q(9,'Which word contains /aɪ/?',['light','late','lot','let'],'light','Light contains the /aɪ/ diphthong.',1,'diphthong identification'),
q(10,'Which word contains /aʊ/?',['house','horse','hose','whose'],'house','House contains the /aʊ/ diphthong in the target pronunciation model.',1,'diphthong identification'),
q(11,'What happens in a stop consonant such as /p/ or /b/?',['Air is briefly blocked and then released','Air flows only through the nose throughout','The mouth remains completely open','The sound is always a vowel glide'],'Air is briefly blocked and then released','Stops/plosives involve a complete oral closure followed by release.',1,'consonant manner'),
q(12,'Which pair uses essentially the same lip position but differs mainly in voicing?',['fan — van','ship — sheep','book — boot','light — right'],'fan — van','/f/ is voiceless and /v/ is voiced; both use the lower lip against the upper teeth.',2,'voicing'),
q(13,'How can a learner physically check the difference between /s/ and /z/?',['Touch the throat gently and feel vibration for /z/ but not /s/','Close both ears and look at the spelling','Hold the nose for both sounds','Open the mouth as widely as possible'],'Touch the throat gently and feel vibration for /z/ but not /s/','/s/ is voiceless while /z/ normally has vocal-cord vibration.',2,'voicing discrimination'),
q(14,'Which sound is a nasal?',['/m/','/f/','/t/','/ʃ/'],'/m/','For /m/, the lips close while voiced air escapes through the nose.',1,'nasals'),
q(15,'Which word ends with /ŋ/?',['sing','sin','sit','sip'],'sing','Sing ends with the velar nasal /ŋ/; it should not automatically receive an extra /g/ sound.',1,'nasal identification'),
q(16,'Which pair best practises /θ/ against /t/?',['thin — tin','fan — van','sip — zip','coat — goat'],'thin — tin','/θ/ is a voiceless dental fricative, while /t/ is a voiceless stop made at the ridge behind the upper teeth.',2,'place and manner contrast'),
q(17,'Which statement about /ʃ/ and /ʒ/ is correct?',['They have similar friction positions, but /ʃ/ is voiceless and /ʒ/ is voiced','They are both vowels','/ʃ/ is nasal and /ʒ/ is a stop','They are identical sounds'],'They have similar friction positions, but /ʃ/ is voiceless and /ʒ/ is voiced','The pair is distinguished importantly by voicing, with friction produced in a similar post-alveolar region.',2,'fricatives'),
q(18,'Which sound is classified in the NERDC lesson category of semi-vowels?',['/w/','/m/','/k/','/f/'],'/w/','/w/ and /j/ are commonly taught as semi-vowels/glides because their articulation begins vowel-like and moves quickly into a following vowel.',2,'semi-vowels'),
q(19,'Why are contrast pairs such as fan/van useful?',['They train the learner to hear and produce a meaningful sound difference while most of the word stays similar','They prove spelling always predicts pronunciation','They remove the need to listen','They are used only to test vocabulary meanings'],'They train the learner to hear and produce a meaningful sound difference while most of the word stays similar','A controlled contrast focuses attention on the target phonemic distinction.',2,'pronunciation practice'),
q(20,'A learner sees two vowel letters together in a word. What is the safest conclusion?',['Listen to the actual pronunciation before deciding whether the word contains a diphthong','It must contain a diphthong','It must contain two syllables','Both letters must be pronounced separately'],'Listen to the actual pronunciation before deciding whether the word contains a diphthong','Sound classification is based on pronunciation, not simply the appearance of spelling.',3,'sound-spelling reasoning')
];