export const jss1CreativeWritingDeepLessons=[{
 topicId:'revised2025-jss1-english-creative-writing-deep',classLevel:'JSS1',subject:'English Language',topic:'Introduction to Creative writing',
 objectives:['Discuss the meaning and purpose of creative writing','Describe plot, characterisation, style, setting, theme and language as story elements','Explain stories, poems, plays/drama and biographies as creative forms','Explain and use dialogue, descriptive writing and figurative language','Use sensory description involving sight, smell, touch, taste and sound','Plan, draft, revise and produce an original age-appropriate creative work','Develop a short biography using personal information, education, passion, achievements, values and future aspiration'],
 prerequisites:['sentence construction','paragraphing','basic punctuation','reading short stories'],
 teaching:[
 'CREATIVE WRITING is writing in which a writer uses imagination, observation and purposeful language to shape ideas, experiences, people, places or events into an engaging form. NERDC expects learners not only to define it but to DO creative writing.',
 'Creative writing is not the same as writing anything that comes to mind. Effective creativity still needs meaning, organisation, appropriate language and revision.',
 'NERDC names six important STORY ELEMENTS: plot, characterisation, style, setting, theme and language. These elements work together rather than existing as isolated definitions.',
 'PLOT is the organised sequence of important events—what happens and how events connect. A simple JSS1 story can move from an opening situation to a problem, attempts/actions, an important turning point and a resolution. The exact shape can vary; a plot is more than a list of unrelated events.',
 'A useful plot question is CAUSE AND EFFECT: What happened? Why did it happen? What did it cause next? Events become a story when they meaningfully connect.',
 'CHARACTERS are the people, animals or imagined beings who participate in a story. CHARACTERISATION is how the writer reveals what they are like through actions, speech, thoughts, appearance, choices and what others say about them.',
 'Instead of only telling “Bola was generous,” a writer can show characterisation: “Bola divided her only loaf and handed half to the hungry child.” The action gives evidence of generosity.',
 'SETTING is where and when events occur and includes relevant social/environmental circumstances. “At dawn in a crowded Ilorin motor park during heavy rain” gives more usable setting than simply “outside.”',
 'Setting should contribute to the writing. Rain can delay a journey; darkness can create uncertainty; a noisy market can affect dialogue. Description should serve the scene rather than become a disconnected list.',
 'THEME is an important underlying idea explored by the work, such as honesty, courage, friendship, responsibility or consequences of greed. A theme is not simply one event and should normally emerge through the characters and events rather than a forced sermon.',
 'STYLE is the writer’s distinctive manner of expression—the choices of sentence pattern, description, dialogue, imagery, pace and tone that shape how the work feels.',
 'LANGUAGE means the actual words and expressions selected. Strong creative language is precise and suitable for the form, character, setting and audience. “The rusty gate groaned open” creates a clearer effect than “The gate was somehow bad.”',
 'NERDC lists four CREATIVE FORMS: stories, poems, plays/drama and biographies. Each form communicates creatively but has different conventions.',
 'A STORY normally develops events through characters, setting, plot and prose narration. It can use description and dialogue to make scenes vivid.',
 'A POEM arranges language for concentrated meaning and effect. Poems may use imagery, sound, rhythm, line arrangement and figurative expression. Not every poem must rhyme.',
 'A PLAY/DRAMA is written primarily for performance. Characters speak through dialogue and may act according to stage directions. A drama script should make clear who is speaking.',
 'A BIOGRAPHY presents the life of a real person. NERDC’s learner activity specifically asks for biographies focusing on personal information, education, passion, achievements, values and future aspiration. When a learner writes about his/her own life, that is more precisely autobiographical writing; AVORA preserves NERDC’s activity while explaining this distinction.',
 'DIALOGUE is the spoken exchange between characters. Good dialogue should sound appropriate to the speaker and situation and should help reveal character, develop events or communicate necessary information.',
 'Dialogue is not decoration. If ten lines of conversation neither reveal character nor move the situation forward, the writer should revise or reduce them.',
 'Basic dialogue punctuation matters. Example: “Wait for me,” Amina called. Begin direct speech with a capital letter and use quotation marks consistently where prose dialogue convention requires them.',
 'DESCRIPTIVE WRITING uses precise details to help a reader imagine a person, place, object, event or experience. NERDC specifically requires SENSORY DESCRIPTION using SIGHT, SMELL, TOUCH, TASTE and SOUND.',
 'Do not force all five senses into every scene. Select details a person could naturally notice. At a bakery: warm air on the skin (touch), sweet bread aroma (smell), trays of golden loaves (sight), metal pans clattering (sound), a buttery bite (taste).',
 'Specific sensory details are stronger than empty adjectives. “The room was nice” tells little; “Sunlight crossed the clean blue walls while the ceiling fan hummed softly” gives observable detail.',
 'FIGURATIVE LANGUAGE expresses an idea imaginatively rather than only literally. At this introductory level, useful examples include SIMILE, METAPHOR and PERSONIFICATION.',
 'A SIMILE compares using like or as: “The moon shone like a silver coin.” A METAPHOR makes a direct imaginative comparison: “The classroom was an oven.” PERSONIFICATION gives human qualities/actions to non-human things: “The wind whispered through the leaves.”',
 'Figurative language must make sense in context. More figures of speech do not automatically make writing better. One fresh, appropriate image is stronger than many confusing comparisons.',
 'SHOWING and TELLING can work together. Telling can move a story quickly (“Three weeks passed”). Showing slows down important moments using action, dialogue and sensory detail. Writers choose according to purpose.',
 'A strong creative-writing process is IDEA → PURPOSE/FORM → PLAN → DRAFT → DEVELOP → REVISE → EDIT → SHARE. Revision improves content and effect; editing checks grammar, spelling and punctuation.',
 'For a STORY PLAN, decide: character → desire/goal → setting → problem → key events → turning point → ending → possible theme. The ending should grow from what happened rather than appear from nowhere.',
 'For a BIOGRAPHY PLAN based on NERDC’s activity: identify the person → relevant personal background → education → passion/interests → achievements → values → future aspiration where appropriate. Arrange information clearly, often chronologically.',
 'For a POEM, begin with an image, feeling, observation or idea; select concrete words and line breaks deliberately. For DRAMA, identify characters, setting/situation, conflict or purpose, dialogue and useful stage directions.',
 'REVISION QUESTIONS: Is the form clear? Are events connected? Can I infer character traits from evidence? Is the setting concrete? Does dialogue have a job? Are sensory details relevant? Is figurative language meaningful? Does the ending fit?',
 'AVORA CREATIVE ROUTINE: IMAGINE/OBSERVE → CHOOSE FORM → BUILD ELEMENTS → USE TECHNIQUES → DRAFT → READ ALOUD → REVISE FOR EFFECT → EDIT FOR ACCURACY.'
 ],
 workedExamples:[
 'PLOT: Tunde misses the last bus because he returned a lost purse; the purse owner later gives him a safe ride home. The events connect through cause and effect.',
 'CHARACTERISATION by telling: “Zainab was brave.” By showing: “Although her hands shook, Zainab stepped forward and warned the younger pupils away from the broken wire.”',
 'SETTING: “At 6:15 a.m., mist covered the quiet school field and wet grass soaked Musa’s sandals.” Time, place and physical conditions are concrete.',
 'THEME: A story in which a learner lies repeatedly and loses friends may explore honesty and trust. Theme comes from the pattern of events, not just the word “honesty.”',
 'STYLE: Short sentences can speed an urgent moment: “The bell rang. Smoke rose. We ran.” Longer descriptive sentences can slow a reflective scene.',
 'LANGUAGE: Replace “The dog moved fast” with “The frightened dog dashed through the open gate” when the stronger verb and modifier fit the scene.',
 'STORY FORM: narrator + characters + connected events + setting can build a short prose story.',
 'POEM FORM: “Rain taps the roof / then races down the glass.” Line arrangement and imagery create a compact effect; rhyme is not compulsory.',
 'DRAMA FORM: ADA: Where is the key? / (Musa searches his pocket.) / MUSA: I had it a minute ago. Character labels, dialogue and stage direction signal performance.',
 'BIOGRAPHY: “Amina Yusuf grew up in… She attended… Her interest in… led her to… She values… and hopes to…” follows NERDC’s suggested areas without inventing achievements.',
 'DIALOGUE: “Don’t touch that wire,” Kemi shouted. This can reveal urgency and affect the next action.',
 'SIGHT: “Orange light spread across the wet road.” The detail appeals mainly to sight.',
 'SOUND: “The generator coughed twice and fell silent.” The wording creates an audible impression.',
 'SMELL: “The sharp smell of smoke drifted from the kitchen.”',
 'TOUCH: “The metal rail felt hot beneath his palm.”',
 'TASTE: “The unripe mango left a sharp sour taste on her tongue.”',
 'SIMILE: “The child clung to his bag like a lifebuoy.” The comparison uses like.',
 'METAPHOR: “The classroom was an oven by noon.” It directly compares the hot classroom to an oven.',
 'PERSONIFICATION: “The old door complained as we pushed it open.” A human action is imaginatively assigned to the door.',
 'REVISION: “It was a very scary night and I was scared” → “Each knock on the window made me grip the blanket tighter.” The revision replaces repetition with observable action and sound.'
 ],
 misconceptions:['thinking creative writing means writing without structure','confusing plot with theme','confusing a character with characterisation','treating setting as place only and ignoring time/context','stating a theme without evidence from events','believing every poem must rhyme','believing drama is ordinary prose with character names added later','confusing biography with a completely invented story','believing dialogue is useful merely because characters are talking','forcing all five senses into every description','using many adjectives instead of precise sensory details','confusing simile and metaphor','thinking figurative language should be used in every sentence','believing first drafts should never be changed','editing spelling while ignoring weak plot/content','copying a model instead of producing original work'],
 guidedPractice:[
 'ELEMENT HUNT: Read a short original AVORA story and label evidence of plot, characterisation, setting, theme, style and language.',
 'STORY CHAIN: Following NERDC group story-building, each learner adds an event only if it logically develops the previous event; the group then checks cause and effect.',
 'FIVE-SENSE STATION: Observe or imagine a familiar place and create a sensory bank under sight, smell, touch, taste and sound; select only details appropriate to the final paragraph.',
 'SHOW THE TRAIT: Convert statements such as “Ngozi was impatient” into actions, dialogue or thoughts that allow the reader to infer the trait.',
 'DIALOGUE WORKSHOP: Rewrite a flat exchange so that each line reveals character or advances the situation; punctuate it correctly.',
 'FIGURATIVE-LANGUAGE LAB: Create one meaningful simile, metaphor and personification from the same scene, then decide which best fits and why.',
 'FORM SWITCH: Express one idea briefly as a story opening, a poem, a drama exchange and a biographical statement to compare conventions.',
 'NERDC BIOGRAPHY BUILDER: Plan a short biography around personal information, education, passion, achievements, values and future aspiration, using only accurate information.'
 ],
 independentPractice:[
 'Write a 350–500 word age-appropriate short story with a clear setting, connected plot, at least one developed character, purposeful dialogue, sensory description and a theme that emerges from events.',
 'Write a vivid description of a familiar place or event using at least three naturally relevant senses and two appropriate figures of speech. Underline the sensory evidence and label the figures.',
 'Write a one-page drama scene involving two or three characters and a clear situation/problem. Use character labels, purposeful dialogue and brief useful stage directions.',
 'Develop a short factual biography of a real person you know or have reliably researched, covering relevant NERDC areas: personal information, education, passion, achievements, values and future aspiration where known. Do not invent missing facts.',
 'REVISION TASK: Take one first draft and produce a second version. List at least five substantive improvements to plot/organisation, characterisation, setting, language, dialogue or description before correcting surface errors.'
 ],
 source:{authority:'NERDC Revised BEC 2025',url:'https://nerdc.gov.ng',verified:'OFFICIAL_SCOPE_AND_ACTIVITIES_PRESERVED_WITH_WRITING_PEDAGOGY_CROSSCHECK'},
 mastery:{criterion:'Learner explains creative writing, accurately describes NERDC story elements and creative forms, identifies and applies dialogue/descriptive/figurative techniques, and independently produces and revises coherent creative work with at least 80% mastery.',status:'DEEP_WHEN_PASSED'}
}];