export type Jss1CWQ={id:string;classLevel:'JSS1';subject:'English Language';topic:'Introduction to Creative writing';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1CWQ=>({id:`nerdc25-auth-jss1-eng-cw-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Introduction to Creative writing',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1CreativeWritingQuestions:Jss1CWQ[]=[
q(1,'Which best describes creative writing at this level?',['Using imagination/observation and purposeful language to shape ideas or experiences into an engaging form','Writing anything at all without organisation','Copying a story exactly','Using difficult words in every sentence'],'Using imagination/observation and purposeful language to shape ideas or experiences into an engaging form','Creative writing allows imagination but still requires purposeful choices, organisation and revision.',1,'meaning'),
q(2,'Which list contains the story elements named by NERDC?',['Plot, characterisation, style, setting, theme and language','Address, salutation, heading and signature','Noun, verb, adjective and adverb','Prefix, suffix and compound only'],'Plot, characterisation, style, setting, theme and language','These six are explicitly listed in the JSS1 creative-writing curriculum.',1,'story elements'),
q(3,'What is plot?',['The organised sequence and connection of important events','The place only','The moral stated in one word','The list of characters'],'The organised sequence and connection of important events','Plot concerns what happens and how important events connect, often through cause and effect.',1,'plot'),
q(4,'Which sentence SHOWS that a character is generous rather than merely telling it?',['Bola divided her only loaf and gave half to the hungry child.','Bola was generous.','Generosity is good.','Bola was a character.'],'Bola divided her only loaf and gave half to the hungry child.','The action provides evidence from which the reader can infer generosity.',2,'characterisation'),
q(5,'What does setting mainly establish?',['Where and when events occur, with relevant circumstances','Only the names of characters','Only the ending','The writer’s handwriting'],'Where and when events occur, with relevant circumstances','Setting includes place, time and useful surrounding conditions.',1,'setting'),
q(6,'Which is the clearest setting?',['At dawn in a crowded motor park during heavy rain','Somewhere','A nice place','The character was kind'],'At dawn in a crowded motor park during heavy rain','It gives specific time, place and physical circumstances.',1,'setting detail'),
q(7,'What is theme?',['An important underlying idea explored through the work','The chronological list of events','Every adjective in a story','The title only'],'An important underlying idea explored through the work','Theme is an idea such as trust or courage that emerges through the work.',1,'theme'),
q(8,'Which set contains only creative forms listed by NERDC?',['Stories, poems, plays/drama and biographies','Letters, reports, minutes and notices','Arguments, debates, equations and tables','Nouns, verbs, prefixes and suffixes'],'Stories, poems, plays/drama and biographies','Those four forms are explicitly named in the curriculum.',1,'creative forms'),
q(9,'Which statement about poems is most accurate?',['A poem can use imagery, sound, rhythm and line arrangement; it does not always have to rhyme','Every poem must rhyme','A poem must contain stage directions','A poem must be a biography'],'A poem can use imagery, sound, rhythm and line arrangement; it does not always have to rhyme','Rhyme can be a poetic resource, but it is not a compulsory feature of every poem.',2,'poetry form'),
q(10,'Which feature most clearly signals a drama script?',['Character labels with spoken dialogue and possible stage directions','Two addresses','Only descriptive paragraphs','A list of suffixes'],'Character labels with spoken dialogue and possible stage directions','Drama is primarily designed for performance, so speakers and actions need to be clear.',1,'drama form'),
q(11,'NERDC asks learners to develop biographies focusing on which areas?',['Personal information, education, passion, achievements, values and future aspiration','Only height and favourite colour','Only imaginary adventures','Only dialogue and rhyme'],'Personal information, education, passion, achievements, values and future aspiration','These are the specific biography areas listed in the NERDC learner activity.',1,'biography'),
q(12,'Which dialogue is doing useful story work?',['“Don’t touch that wire,” Kemi shouted as Musa reached toward it.','“Hello.” “Hello.” “Okay.” “Okay.” with no effect on the scene','Ten greetings unrelated to the plot','Random speech copied from another story'],'“Don’t touch that wire,” Kemi shouted as Musa reached toward it.','The line communicates urgency and directly affects the developing action.',2,'dialogue'),
q(13,'Which senses does NERDC explicitly name for sensory description?',['Sight, smell, touch, taste and sound','Sight only','Hearing and sight only','Memory, thought and opinion'],'Sight, smell, touch, taste and sound','The curriculum explicitly directs learners to describe with words related to all five of these senses.',1,'sensory description'),
q(14,'Which sentence contains a simile?',['The moon shone like a silver coin.','The classroom was an oven.','The wind whispered.','The moon appeared.'],'The moon shone like a silver coin.','A simile makes a comparison using like or as.',1,'simile'),
q(15,'Which sentence contains a metaphor?',['The classroom was an oven by noon.','The classroom was as hot as an oven.','The classroom became warm.','The fan hummed.'],'The classroom was an oven by noon.','A metaphor makes a direct imaginative comparison without like/as.',1,'metaphor'),
q(16,'Which sentence contains personification?',['The old door complained as we pushed it open.','The old door was brown.','The door was like wood.','We opened the door.'],'The old door complained as we pushed it open.','Complaining is a human action imaginatively attributed to the door.',1,'personification'),
q(17,'Why is “The room was nice” weaker than a precise sensory description?',['It gives little concrete evidence for the reader to imagine','It contains too many senses','It is a poem','It has too much dialogue'],'It gives little concrete evidence for the reader to imagine','Specific sights, sounds, smells, textures or tastes create a clearer experience.',2,'description'),
q(18,'Which is the strongest creative-writing process?',['Choose/develop idea and form → plan → draft → revise content/effect → edit accuracy','Write once → never reread','Edit spelling before deciding what the story is about','Copy a model → change only the names'],'Choose/develop idea and form → plan → draft → revise content/effect → edit accuracy','Revision strengthens ideas and effect; editing then checks grammar, spelling and punctuation.',2,'writing process'),
q(19,'A learner fills every sentence with similes and metaphors until the story is confusing. What should the learner do?',['Keep only figurative language that is clear, fresh and useful in context','Add even more figures of speech','Remove the plot instead','Turn every sentence into dialogue'],'Keep only figurative language that is clear, fresh and useful in context','Figurative language is a technique, not a quantity target; it should strengthen meaning.',2,'revision'),
q(20,'Which plan best prepares a learner to write a coherent short story?',['Character/goal → setting → problem → connected events → turning point → ending → possible theme','List ten adjectives → choose a title → stop','Write the ending first and add unrelated events','Choose five figures of speech but no characters or events'],'Character/goal → setting → problem → connected events → turning point → ending → possible theme','This plan connects the major story elements and helps events develop meaningfully rather than randomly.',3,'integrated creative writing')
];