export type Jss1MLQ={id:string;classLevel:'JSS1';subject:'English Language';topic:'Myths and Legends';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1MLQ=>({id:`nerdc25-auth-jss1-eng-mythlegend-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Myths and Legends',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1MythsLegendsQuestions:Jss1MLQ[]=[
q(1,'Which description best fits a myth at this introductory level?',['A traditional narrative that may explain origins, natural phenomena, customs or sacred ideas and may involve supernatural beings','Any recent newspaper report','Every story about a named person','A formal letter'],'A traditional narrative that may explain origins, natural phenomena, customs or sacred ideas and may involve supernatural beings','Myths commonly carry traditional explanatory or sacred significance, though individual myths vary.',1,'myth meaning'),
q(2,'Which description best fits a legend?',['A traditional narrative associated with a person, place or event remembered as connected with the past','A scientific report proving a supernatural event','Every animal story','A poem that must rhyme'],'A traditional narrative associated with a person, place or event remembered as connected with the past','Legends often attach traditional storytelling to remembered people, places or events.',1,'legend meaning'),
q(3,'What geographical/cultural range does NERDC explicitly require?',['African and non-African myths and legends','African narratives only','European legends only','Nigerian myths only'],'African and non-African myths and legends','The curriculum explicitly includes African and non-African tales comprising myths and legends.',1,'scope'),
q(4,'Which features/themes are explicitly mentioned by NERDC?',['Supernatural figures and superstitious beliefs','Only rhyme and alliteration','Addresses and salutations','Subject-verb agreement'],'Supernatural figures and superstitious beliefs','These are specifically listed in the NERDC content for this topic.',1,'NERDC features'),
q(5,'What is a supernatural figure in literary analysis?',['A being/agent presented in a narrative as having powers beyond ordinary natural human experience','Any courageous human','Every narrator','A person who writes a book'],'A being/agent presented in a narrative as having powers beyond ordinary natural human experience','The label describes how the figure is presented within the narrative.',1,'supernatural feature'),
q(6,'How should a learner discuss a traditional supernatural explanation?',['Attribute it to the narrative/tradition rather than present it automatically as scientific proof','State that it has been scientifically proved','Mock the people connected to it','Remove it from every retelling'],'Attribute it to the narrative/tradition rather than present it automatically as scientific proof','Literary appreciation can represent a tradition accurately while distinguishing narrative claims from independent factual verification.',2,'critical attribution'),
q(7,'Which wording is most careful?',['“According to the myth, the river began when…”','“Science proves the river began exactly as this myth says.”','“Anyone who tells this story is wrong.”','“The story has no meaning because it is traditional.”'],'“According to the myth, the river began when…”','This wording faithfully reports the traditional narrative without converting it into an unsupported factual claim.',2,'attribution'),
q(8,'Which focus most strongly supports classification as a legend?',['A traditional story about extraordinary deeds attributed to a remembered person associated with a particular place','A list of grammar rules','A scientific experiment','An official memo'],'A traditional story about extraordinary deeds attributed to a remembered person associated with a particular place','Association with a remembered person/place/past event is characteristic of legends.',1,'legend identification'),
q(9,'Which statement about myth, legend and folktale is most accurate?',['They can overlap, so classification should consider the narrative’s focus and cultural function','They can always be separated by whether an animal appears','They mean exactly the same thing','Only myths belong to oral tradition'],'They can overlap, so classification should consider the narrative’s focus and cultural function','Traditional narrative categories can share features; one superficial clue is not enough.',2,'comparison'),
q(10,'Which is a theme rather than a supernatural feature?',['Courage','A spirit with extraordinary powers','An omen believed to predict misfortune','A magical object'],'Courage','Courage is an idea explored through choices/events; the others describe narrative elements or represented beliefs.',1,'theme'),
q(11,'Which pair correctly distinguishes theme from moral lesson?',['Theme: pride; Moral: excessive pride can lead to downfall','Theme: excessive pride can lead to downfall; Moral: a spirit','They are always identical','Theme: three characters; Moral: four scenes'],'Theme: pride; Moral: excessive pride can lead to downfall','Theme names a central idea; a moral states a practical lesson drawn from events.',2,'theme vs moral'),
q(12,'A spirit appears in a story. Does that automatically mean “supernatural power” is the story’s theme?',['No; the spirit can be a feature while the theme may be courage, greed, obedience or another developed idea','Yes, every character is the theme','Yes, supernatural content is always the moral too','No, spirits cannot appear in myths'],'No; the spirit can be a feature while the theme may be courage, greed, obedience or another developed idea','Features, themes and moral lessons answer different analytical questions.',2,'analysis'),
q(13,'What should a faithful retelling preserve?',['Central characters/context, major events, sequence, outcome and essential meaning','Only the title','Every word exactly','A newly invented ending'],'Central characters/context, major events, sequence, outcome and essential meaning','Retelling uses the learner’s own words while preserving the narrative’s core.',1,'retelling'),
q(14,'When retelling a legend, which statement should be avoided unless evidence independently supports it?',['“Historical records prove every event happened exactly this way.”','“The legend says…”','“In the narrative…”','“The storyteller presents…”'],'“Historical records prove every event happened exactly this way.”','A legend’s connection to the past does not automatically verify every narrative detail as historical fact.',2,'legend/history distinction'),
q(15,'Which is part of effective oral narration?',['Clear pronunciation, suitable pace, meaningful pauses and expressive tone','Shouting throughout','Changing important events whenever desired','Removing the ending'],'Clear pronunciation, suitable pace, meaningful pauses and expressive tone','Delivery should help listeners understand and appreciate the narrative.',1,'narration'),
q(16,'What does documentation require?',['Carefully recording the narrative and identifying its source/context where appropriate','Inventing a source if none is known','Claiming authorship of a traditional story','Replacing unfamiliar details with guesses'],'Carefully recording the narrative and identifying its source/context where appropriate','Responsible documentation preserves provenance and separates source material from learner commentary.',1,'documentation'),
q(17,'If a storyteller cannot supply the date when a legend originated, what should the learner do?',['Record that the origin date was not supplied/known rather than inventing one','Choose a century at random','Delete the whole narrative','Claim it is exactly 1,000 years old'],'Record that the origin date was not supplied/known rather than inventing one','Unknown provenance should remain unknown rather than being silently fabricated.',2,'source integrity'),
q(18,'Which comparison is responsible?',['These two supplied narratives both use supernatural intervention, but the events and meanings differ','All African myths have the same supernatural beings','One non-African legend proves what all non-African cultures believe','Every myth teaches exactly one lesson'],'These two supplied narratives both use supernatural intervention, but the events and meanings differ','Comparison should remain grounded in the particular narratives.',2,'comparison'),
q(19,'Why can dramatization help with myths and legends?',['It lets learners demonstrate understanding of characters, conflict and key events through performance while preserving meaning','It proves the narrative is historically factual','It removes the need to understand the story','It allows changing every event'],'It lets learners demonstrate understanding of characters, conflict and key events through performance while preserving meaning','NERDC includes dramatization as an active learning method for this topic.',2,'dramatization'),
q(20,'Which routine best demonstrates mastery?',['Experience → classify carefully → identify features with evidence → map events → explain theme → draw supported moral → retell/narrate → document source responsibly','Guess whether it is a myth → memorise one definition → stop','Find a supernatural figure → call it the theme → stop','Rewrite the tale completely → claim it is traditional'],'Experience → classify carefully → identify features with evidence → map events → explain theme → draw supported moral → retell/narrate → document source responsibly','This integrates the curriculum’s knowledge, interpretation, narration and documentation requirements.',3,'integrated mastery')
];