export type Jss1PFQ={id:string;classLevel:'JSS1';subject:'English Language';topic:'Introduction to Prose Fiction';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1PFQ=>({id:`nerdc25-auth-jss1-eng-prosefiction-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Introduction to Prose Fiction',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1ProseFictionQuestions:Jss1PFQ[]=[
q(1,'What is prose fiction?',['Imaginative prose presenting invented or imaginatively shaped characters/events in sentences and paragraphs','Every factual newspaper article','Only poetry without rhyme','A formal letter'],'Imaginative prose presenting invented or imaginatively shaped characters/events in sentences and paragraphs','Prose fiction uses prose form to create a fictional narrative/world.',1,'definition'),
q(2,'Which is a valid function of prose fiction?',['To entertain and explore human experiences, ideas and choices','Only to list grammar rules','Only to record scientific measurements','Only to give addresses'],'To entertain and explore human experiences, ideas and choices','A prose work may entertain while also encouraging reflection on people, society and ideas.',1,'functions'),
q(3,'Which two prose types does NERDC specify for this topic?',['Narrative and descriptive','Formal and informal','Oral and written','Comedy and tragedy'],'Narrative and descriptive','The revised curriculum explicitly lists Narrative and Descriptive as the two types.',1,'types'),
q(4,'Which passage is mainly narrative?',['Musa missed the bus, borrowed a bicycle and reached school just before assembly ended.','Dust lay thick on the silent desks beneath cracked windows.','The room was narrow, cool and dim.','The mango smelled sweet and felt soft.'],'Musa missed the bus, borrowed a bicycle and reached school just before assembly ended.','Connected events and change over time dominate this passage.',1,'narrative'),
q(5,'Which passage is mainly descriptive?',['The old classroom smelled of chalk; sunlight crossed scarred desks beneath dusty windows.','Tola woke, dressed and ran to school.','The bell rang, so everyone entered.','He fell, stood and continued walking.'],'The old classroom smelled of chalk; sunlight crossed scarred desks beneath dusty windows.','Sensory and qualifying details create an impression of the scene.',1,'descriptive'),
q(6,'Can narrative prose contain description?',['Yes; types can mix, so classify by the dominant purpose','No, never','Only if it becomes poetry','Only if no events occur'],'Yes; types can mix, so classify by the dominant purpose','Stories often use descriptive passages while remaining primarily narrative.',2,'type distinction'),
q(7,'What is plot?',['The organised sequence and relationship of important story events','The physical appearance of one character','The location only','The font used in a book'],'The organised sequence and relationship of important story events','Plot concerns how significant events develop and connect.',1,'plot'),
q(8,'Why is cause and effect useful in plot analysis?',['It shows how decisions/events lead to later developments and consequences','It counts adjectives','It identifies page size','It proves every story is factual'],'It shows how decisions/events lead to later developments and consequences','Cause/effect reveals why events matter within the story’s development.',2,'plot analysis'),
q(9,'What is characterisation?',['The methods a writer uses to create and reveal characters','The list of chapter titles','The time/place of a story','The central idea only'],'The methods a writer uses to create and reveal characters','Characterisation reveals characters through description, speech, action, thought and other evidence.',1,'characterisation'),
q(10,'Which is indirect characterisation?',['“Mr Bello explained the problem a third time without raising his voice.”','“Mr Bello was patient.”','“Patience is a theme.”','“The classroom was large.”'],'“Mr Bello explained the problem a third time without raising his voice.”','The action lets the reader infer patience rather than stating the trait directly.',2,'indirect characterisation'),
q(11,'NERDC’s character sketch activity includes which information?',['Physical description, personality traits, motivations and role in the story','Only the character’s name','Only height and age','Only whether the reader likes the character'],'Physical description, personality traits, motivations and role in the story','These are explicitly named in the curriculum’s character-analysis activity.',1,'character sketch'),
q(12,'What does setting include?',['Time, place and relevant social/physical environment','Place only','Theme and moral only','Plot ending only'],'Time, place and relevant social/physical environment','Setting establishes where/when events happen and the surrounding conditions that can affect them.',1,'setting'),
q(13,'Which statement is a theme rather than a plot summary?',['Honesty when facing temptation','A boy finds a wallet and returns it','The boy walks to school','The wallet belongs to a teacher'],'Honesty when facing temptation','Theme expresses a central idea; the other options state events/details.',1,'theme'),
q(14,'What is style in prose fiction?',['The writer’s manner of presentation through language, sentence choices, description, dialogue, pace and related choices','The reader’s handwriting','The book cover only','The number of characters'],'The writer’s manner of presentation through language, sentence choices, description, dialogue, pace and related choices','Style concerns how the writer shapes the prose and its effect.',1,'style'),
q(15,'“The door slammed. Footsteps stopped. Silence.” What can the short sentences create in context?',['A quick, tense or suspenseful effect','A postal address','A rhyme scheme automatically','A character’s physical description only'],'A quick, tense or suspenseful effect','Brief sentences can affect pace and tension when used purposefully.',2,'style effect'),
q(16,'What is a story/plot map useful for?',['Organising important characters, setting, problem, major events, turning point and outcome','Copying every sentence','Replacing the original text with guesses','Listing only adjectives'],'Organising important characters, setting, problem, major events, turning point and outcome','NERDC explicitly includes story mapping/plot diagram work after reading a short story.',1,'story mapping'),
q(17,'Which is the strongest character claim?',['“Bisi is responsible because she returns to finish her assigned task after her friends leave.”','“Bisi is responsible because I like her.”','“Bisi is responsible because all main characters are.”','“Bisi is responsible; no evidence is needed.”'],'“Bisi is responsible because she returns to finish her assigned task after her friends leave.”','A literary claim should be supported by a relevant action/detail from the text.',2,'textual evidence'),
q(18,'What is an evidence-based prediction?',['A reasonable idea about what may happen next supported by clues in the text','A random guess unrelated to the text','A summary of the ending after reading it','A definition copied from a dictionary'],'A reasonable idea about what may happen next supported by clues in the text','NERDC recommends predictive questions; predictions should grow from textual clues.',2,'prediction'),
q(19,'Why should the author not automatically be treated as the narrator?',['The author creates the work, while a narrator is the voice through which a story is told','Every narrator is fictional but every author is not','Authors never write prose','Narrators only appear in drama'],'The author creates the work, while a narrator is the voice through which a story is told','Separating creator from narrative voice prevents inaccurate interpretation.',2,'appreciation'),
q(20,'Which routine best demonstrates prose-fiction mastery?',['Read → identify type → map plot → analyse character → locate setting → infer theme → notice style → support with evidence','Read title → guess theme → stop','Count paragraphs → ignore events','Memorise definitions without reading prose'],'Read → identify type → map plot → analyse character → locate setting → infer theme → notice style → support with evidence','This integrates NERDC’s knowledge and active prose-appreciation requirements.',3,'integrated mastery')
];