export type Jss1SVAQuestion={id:string;classLevel:'JSS1';subject:'English Language';topic:'Subject-Verb Agreement';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1SVAQuestion=>({id:`nerdc25-auth-jss1-eng-sva-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Subject-Verb Agreement',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1SVAQuestions:Jss1SVAQuestion[]=[
q(1,'What is subject-verb agreement?',['The grammatical matching of a verb form with its subject in number/person where required','Making every verb end in -s','Making every subject plural','Putting the nearest noun beside the verb'],'The grammatical matching of a verb form with its subject in number/person where required','Agreement is a relationship between the grammatical subject and the finite verb form.',1,'agreement meaning'),
q(2,'Choose the correct sentence.',['The boy plays football','The boy play football','The boy playing football every day','The boy are play football'],'The boy plays football','A third-person singular subject normally takes the -s/-es form of an ordinary verb in the simple present.',1,'singular agreement'),
q(3,'Choose the correct sentence.',['The boys play football','The boys plays football','The boys is play football','The boys playing football every day'],'The boys play football','A plural subject normally takes the base present form of an ordinary lexical verb.',1,'plural agreement'),
q(4,'Why is “I play” correct although I refers to one person?',['The simple-present -s rule applies to third-person singular subjects, not every singular meaning','I is always plural','Play is a noun here','English has no agreement'],'The simple-present -s rule applies to third-person singular subjects, not every singular meaning','I and you use the base present form; he/she/it and equivalent singular noun phrases normally take -s/-es.',2,'person agreement'),
q(5,'Which sentence is correct?',['She studies every evening','She study every evening','She studys every evening','She studying every evening'],'She studies every evening','Study changes y to ies in the third-person singular present form.',1,'verb form'),
q(6,'Which set correctly shows present forms of “be”?',['I am; she is; they are','I is; she are; they am','I are; she am; they is','I be; she be; they be'],'I am; she is; they are','Be has irregular agreement forms that must be learned.',1,'be agreement'),
q(7,'Choose the correct pair.',['She has a pen; they have pens','She have a pen; they has pens','She has a pen; they has pens','She have a pen; they have pens'],'She has a pen; they have pens','Has agrees with third-person singular she; have agrees with plural they.',1,'have agreement'),
q(8,'Choose the correct pair.',['He does his work; they do their work','He do his work; they does their work','He does his work; they does their work','He do his work; they do their work'],'He does his work; they do their work','Does is the third-person singular form; do is used with plural they.',1,'do agreement'),
q(9,'Which question is correct?',['Does the boy play?','Does the boy plays?','Do the boy plays?','Does the boy playing?'],'Does the boy play?','Does carries the third-person singular agreement, so the lexical verb remains in the base form play.',2,'auxiliary agreement'),
q(10,'Choose the correct sentence.',['The basket of oranges is heavy','The basket of oranges are heavy','The basket of oranges be heavy','The basket of oranges have heavy'],'The basket of oranges is heavy','The subject head is singular basket; oranges is inside the prepositional phrase and does not control agreement.',2,'intervening phrase'),
q(11,'Choose the correct sentence.',['The students in the classroom are ready','The students in the classroom is ready','The students in the classroom am ready','The students in the classroom has ready'],'The students in the classroom are ready','The plural subject head students controls the verb, not the singular noun classroom.',2,'subject head'),
q(12,'Which sentence has normal agreement for two separate subjects joined by “and”?',['Musa and Ada are ready','Musa and Ada is ready','Musa and Ada has ready','Musa and Ada am ready'],'Musa and Ada are ready','Two separate subjects joined by and normally form a plural subject.',1,'compound subject'),
q(13,'Choose the standard form.',['Everyone is ready','Everyone are ready','Everyone were ready now','Everyone have ready'],'Everyone is ready','Everyone is grammatically singular in standard formal English.',2,'indefinite pronoun'),
q(14,'Which sentence is correct?',['Several are absent','Several is absent','Several has absent','Several am absent'],'Several are absent','Several has plural meaning and takes plural agreement.',1,'plural indefinite'),
q(15,'Choose the correct pair.',['Some water is left; some pupils are waiting','Some water are left; some pupils is waiting','Some water is left; some pupils is waiting','Some water are left; some pupils are waiting'],'Some water is left; some pupils are waiting','With some, agreement depends on the noun/quantity referred to: water is mass singular here, pupils plural.',2,'quantifier agreement'),
q(16,'Choose the correct pair.',['There is a book on the desk; there are three books on the desk','There are a book on the desk; there is three books on the desk','There is a book; there is three books','There are a book; there are three books'],'There is a book on the desk; there are three books on the desk','In careful standard usage the following noun phrase controls singular/plural agreement.',2,'there construction'),
q(17,'Which sentence is correct?',['Either the teacher or the pupils are coming','Either the teacher or the pupils is coming','Either the teacher or the pupils am coming','Either the teacher or the pupils has coming'],'Either the teacher or the pupils are coming','With unlike subjects joined by either...or, standard agreement commonly follows the nearer subject; pupils is plural.',3,'either or'),
q(18,'Which sentence is correct?',['Either the pupils or the teacher is coming','Either the pupils or the teacher are coming','Either the pupils or the teacher am coming','Either the pupils or the teacher have coming'],'Either the pupils or the teacher is coming','The nearer subject teacher is singular, so is agrees with it.',3,'either or'),
q(19,'Which sentence correctly handles a verb group?',['The players are training','The players is training','The players are trains','The players is trains'],'The players are training','The finite auxiliary are carries agreement with plural players; training does not change for number.',2,'verb group agreement'),
q(20,'How should you solve “The list of names ___ on the desk”?',['Identify list as the singular subject head, ignore the of-phrase for agreement, and choose is','Agree with names and choose are','Choose are because it is nearest the blank','Add -s to every word'],'Identify list as the singular subject head, ignore the of-phrase for agreement, and choose is','Agreement is controlled by the head of the subject noun phrase, list, not the plural noun inside “of names.”',3,'integrated agreement reasoning')
];