export const jss1FolktalesDeepLessons=[{
 topicId:'revised2025-jss1-english-folktales-deep',classLevel:'JSS1',subject:'English Language',topic:'Folktales',
 objectives:['Explain what a folktale is in the context of oral/traditional literature','Identify features of folktales from evidence in a tale','Recognise that NERDC includes African and non-African folktales','Explain themes of folktales','Distinguish a theme from a moral lesson','Explain purposes of folktales including didactic teaching and entertainment','Retell a folktale accurately in a logical sequence','Narrate a folktale engagingly using appropriate language and delivery','Present or document a folktale without inventing its cultural source'],
 prerequisites:['Introduction to Literature','oral and written literature','basic theme and moral-value awareness','listening and speaking skills'],
 teaching:[
 'A FOLKTALE is a traditional story associated with a community or culture and passed from people to people, especially through oral storytelling, though folktales may later be written, recorded or dramatized. Folktales belong strongly to oral tradition because telling, listening and retelling help preserve them.',
 'NERDC requires learners to work with both AFRICAN and NON-AFRICAN tales. The aim is not to assume every culture tells identical stories, but to recognise that communities in different places preserve stories that can entertain, teach, explain behaviour or transmit values.',
 'A folktale is not simply any old story. When identifying one, look for a combination of traditional transmission, culturally shared storytelling, recognisable folktale patterns/features and the tale’s function in its community.',
 'FEATURES are characteristics that help us recognise and discuss a folktale. Not every folktale contains every possible feature, so evidence from the particular tale matters.',
 'A common feature is TRADITIONAL/ORAL TRANSMISSION: the story is told and retold across people or generations. Because oral retelling can vary, different versions of the same tale may exist.',
 'Folktales often use SIMPLE, MEMORABLE STORY PATTERNS: a challenge, journey, contest, mistake, trick, test or consequence. Repetition may help listeners follow and remember events.',
 'Some folktales contain HUMAN characters; others contain ANIMALS or supernatural/imaginative beings that speak and act in human-like ways. Do not define all folktales as “animal stories”—that is too narrow.',
 'Characters can represent recognisable qualities such as cleverness, greed, patience, pride, kindness or foolishness. Judge the quality from what a character says, chooses and does.',
 'Folktales may use familiar or traditional openings/closings, repeated phrases, songs, chants, audience responses or formulaic expressions. These can strengthen participation and memory in oral performance, but their exact forms differ across traditions.',
 'SETTING in folktales may be broadly described—a village, forest, kingdom or distant past—rather than mapped with modern precision. The important question is how the setting supports the events and cultural world of that tale.',
 'THEME is a central idea explored through the story, such as greed, wisdom, obedience, courage, justice, cooperation or consequences of pride.',
 'A MORAL LESSON is a practical lesson about conduct that listeners may draw from events—for example, “Greed can cause a person to lose what he already has.” Theme and moral are related but not identical: GREED can be a theme; a warning about greed can be the moral lesson.',
 'Do not force one moral onto every tale. A learner should first understand the events, then infer a lesson supported by the characters’ actions and consequences.',
 'NERDC explicitly identifies PURPOSES such as DIDACTIC LESSONS and ENTERTAINMENT. DIDACTIC means intended to teach or instruct. A folktale can entertain listeners while also encouraging reflection about behaviour and values.',
 'Folktales can also help communities preserve and share cultural memories, values, storytelling practices and language. This is useful context, but learners should not make claims about a specific community unless the tale or a reliable source supports them.',
 'RETELLING means recounting an existing tale in your own words while preserving its important characters, major events, logical order and essential meaning. Retelling is not inventing an entirely different plot.',
 'A strong RETELLING answers: Who are the important characters? Where/under what situation does the tale begin? What starts the main problem? What important events follow? What is the turning point/outcome? How does it end? What theme or lesson emerges?',
 'Separate MAJOR events from minor details. If removing a detail does not damage the main sequence or meaning, it may be shortened in a retelling.',
 'SEQUENCE WORDS can clarify oral retelling: at first, soon, afterwards, meanwhile, eventually and finally. Use them naturally rather than placing one before every sentence.',
 'NARRATION is the skill of presenting the tale effectively to listeners. Good narration uses clear pronunciation, suitable pace, audible voice, meaningful pauses, expressive tone and eye contact/gesture where appropriate.',
 'Expression should support meaning. A warning may sound urgent; suspense may use a pause; a repeated chant may invite audience participation. Performance should not become noise that makes the story difficult to understand.',
 'When a folktale contains a repeated line or song, preserve it when it is important to the story’s identity or audience participation. If you do not know the authentic wording, do not invent and label it as traditional.',
 'DOCUMENTING a folktale means recording it carefully in writing, audio or another suitable form. If you obtained it from a parent, grandparent, storyteller, book or recording, identify that source when appropriate instead of pretending you created the traditional tale.',
 'CULTURAL RESPECT matters. Do not mock unfamiliar beliefs, names or customs. Ask what role an element plays in the story and distinguish what the tale says from assumptions about an entire people.',
 'COMPARE WITHOUT STEREOTYPING: African and non-African folktales may share patterns such as tricksters, tests, repeated events or moral consequences, but similarities must be demonstrated from the tales being compared.',
 'A SIMPLE ANALYSIS ROUTINE is CHARACTER → IMPORTANT EVENTS → FEATURE EVIDENCE → THEME → MORAL/PURPOSE. This keeps interpretation grounded in the tale.',
 'A SIMPLE RETELLING ROUTINE is LISTEN/READ → NOTE WHO/WHERE/PROBLEM → ORDER MAJOR EVENTS → RETELL IN OWN WORDS → PRESERVE IMPORTANT REPETITION → END CLEARLY → STATE A SUPPORTED LESSON IF ASKED.',
 'AVORA FOLKTALE ROUTINE: EXPERIENCE → IDENTIFY FEATURES → MAP EVENTS → RETELL → EXPLAIN THEME → DRAW SUPPORTED LESSON → NARRATE/DRAMATIZE.'
 ],
 workedExamples:[
 'IDENTIFICATION: A community story repeatedly told aloud about a clever animal facing consequences may be a folktale when its traditional transmission and storytelling context support that classification.',
 'NOT ENOUGH EVIDENCE: “It has an animal, therefore it is a folktale” is weak reasoning because modern authored stories can also have talking animals.',
 'FEATURE: A phrase repeated three times before the hero succeeds creates a memorable pattern that can support oral storytelling.',
 'FEATURE: A storyteller says a recurring line and listeners respond. This illustrates participatory oral performance.',
 'CHARACTER EVIDENCE: If a tortoise deceives three neighbours to collect food from each, the actions provide evidence of trickery/greed; the trait should not be guessed from the animal species.',
 'THEME: GREED may be a central idea if repeated choices and consequences revolve around wanting more than one needs.',
 'MORAL: “Greed can make a person lose what he already possesses” is a lesson drawn from a story in which greed leads to loss.',
 'THEME vs MORAL: COOPERATION is an idea/theme; “People can solve difficult problems more effectively when they cooperate” is a possible lesson.',
 'PURPOSE: A humorous trickster episode can entertain while its consequences also teach a didactic lesson.',
 'RETELLING: Original has ten descriptive details around a journey. A reteller may shorten minor scenery but must preserve the journey, problem, decisive actions and outcome.',
 'BAD RETELLING: Changing the central character, problem and ending creates a new story rather than faithfully retelling the tale.',
 'SEQUENCE: “At first the brothers refused to work together. Afterwards each failed alone. Finally they combined their efforts and moved the fallen tree.” The order makes cause and development clear.',
 'NARRATION: Slowing down before the moment a hidden character appears can create suspense without changing the story.',
 'NARRATION: Shouting every sentence is not expressive narration; changes in pace, volume and pause should follow meaning.',
 'DOCUMENTATION: “Retold from a story narrated by my grandmother during a family storytelling session” identifies a source honestly when that is truly how the learner obtained it.',
 'AFRICAN/NON-AFRICAN COMPARISON: Two tales from different traditions may both punish greed, but the learner should compare actual events and features rather than claim the cultures are the same.',
 'MORAL EVIDENCE: If a character ignores repeated warnings and suffers the predicted consequence, a lesson about listening to wise advice is supported by the plot.',
 'MULTIPLE LESSONS: A tale may reasonably support more than one interpretation when each is backed by events; learners should explain their evidence.',
 'DRAMATIZATION: Converting a key scene into dialogue and action can demonstrate understanding, provided the central event and meaning remain recognisable.',
 'SUMMARY CHECK: A strong folktale response can identify a feature, point to evidence, explain a theme and state a moral lesson without confusing those four tasks.'
 ],
 misconceptions:['every story from the past is automatically a folktale','all folktales are animal stories','all folktales have exactly the same features','African folktales are all alike','non-African folktales are all alike','theme and moral lesson mean exactly the same thing','a moral can be chosen without evidence from events','folktales exist only to teach and cannot entertain','retelling means memorising every original word','retelling permits changing the main plot completely','narration means speaking as loudly and dramatically as possible','a written folktale cannot have originated in oral tradition','every repeated phrase is proof by itself that a text is a folktale','talking animals prove a story is traditional','a learner may invent a cultural source for a tale','one folktale can represent every belief of an entire culture'],
 guidedPractice:[
 'FEATURE DETECTIVE: Read/listen to an original classroom folktale and create a two-column chart: feature claimed / exact evidence from the tale.',
 'EVENT ROPE: Put mixed event cards into the correct story order, then remove minor details while preserving the main plot for retelling.',
 'THEME OR MORAL?: Sort statements such as “greed”, “honesty”, “greed can lead to loss” and “telling the truth protects trust” into themes/ideas and moral lessons, explaining the distinction.',
 'NERDC RETELLING CIRCLE: In groups, learners retell the same tale in their own words; listeners check characters, sequence, major events and ending rather than exact wording.',
 'NARRATION LAB: Retell one short scene twice—first flatly, then with purposeful pace, pause and tone—and discuss which delivery improves comprehension.',
 'DRAMA TRANSFER: Dramatize one decisive scene from a folktale while preserving the original event and meaning.',
 'AFRICAN/NON-AFRICAN COMPARISON: Using two supplied age-appropriate tales, compare only features, themes and lessons supported by the texts; avoid cultural generalisations.',
 'DOCUMENTATION TASK: Interview a willing storyteller about a folktale, record source/context with permission, document the major events, and distinguish the storyteller’s version from the learner’s commentary.'
 ],
 independentPractice:[
 'Read or listen to an age-appropriate folktale. Identify at least four features with evidence, explain one theme, state one supported moral lesson and explain one purpose.',
 'Retell a folktale orally in 3–5 minutes, preserving the main characters, event sequence, problem, outcome and important repeated elements while using your own words.',
 'Write a faithful 300–450 word retelling of a folktale from a supplied or reliably identified source, then annotate where you shortened minor details without changing the central plot.',
 'Compare one African and one non-African folktale supplied for class. Identify one supported similarity and one difference in features, theme, character pattern or lesson without making claims about whole cultures.',
 'Prepare and perform/dramatize a key folktale scene, then explain how your voice, pauses, gesture or dialogue helped communicate the story.'
 ],
 source:{authority:'NERDC Revised BEC 2025',url:'https://nerdc.gov.ng',verified:'OFFICIAL_FOLKTALE_SCOPE_PRESERVED'},
 mastery:{criterion:'Learner identifies folktale features with evidence, explains themes and moral lessons without confusing them, recognises didactic/entertainment purposes, and faithfully retells/narrates an age-appropriate folktale at at least 80% mastery.',status:'DEEP_WHEN_PASSED'}
}];