export type Jss1OralComprehensionQuestion={
 id:string;classLevel:'JSS1';subject:'English Language';topic:'Oral Comprehension';prompt:string;
 options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string;
};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1OralComprehensionQuestion=>({
 id:`nerdc25-auth-jss1-eng-oral-comprehension-${String(n).padStart(2,'0')}`,
 classLevel:'JSS1',subject:'English Language',topic:'Oral Comprehension',prompt,options,correctAnswer,explanation,difficulty,skill
});
export const jss1OralComprehensionQuestions:Jss1OralComprehensionQuestion[]=[
q(1,'Which statement best describes oral comprehension?',['Listening to spoken information, understanding its meaning and responding appropriately','Hearing any sound without paying attention','Memorising every word a speaker says','Reading a passage silently as fast as possible'],'Listening to spoken information, understanding its meaning and responding appropriately','Oral comprehension requires purposeful listening and understanding, not merely receiving sound.',1,'meaning'),
q(2,'What is the clearest difference between hearing and listening?',['Hearing receives sound; listening pays attention to understand it','Listening happens automatically; hearing requires concentration','Hearing always produces understanding','There is no difference'],'Hearing receives sound; listening pays attention to understand it','Listening is deliberate and meaning-focused, while hearing can occur without focused attention.',1,'hearing versus listening'),
q(3,'Before listening to a passage about road safety, which action best prepares the learner?',['Think about the topic and predict likely ideas while remaining ready to confirm them','Write an answer before hearing the passage','Ignore the announced topic','Try to memorise unrelated road signs'],'Think about the topic and predict likely ideas while remaining ready to confirm them','Prediction activates relevant knowledge but must be checked against what is actually heard.',1,'before-listening strategy'),
q(4,'Which is the best strategy while listening?',['Identify the main idea and important supporting details','Try to write every word and stop listening whenever one word is missed','Focus only on the first sentence','Replace the speaker’s information with personal experience'],'Identify the main idea and important supporting details','Effective listeners track the central message and key evidence instead of attempting a complete transcript.',1,'during-listening strategy'),
q(5,'A question whose answer is directly stated in the oral text mainly tests',['literal comprehension','inferential comprehension','critical evaluation','imagination'],'literal comprehension','Literal comprehension retrieves information explicitly stated by the speaker.',1,'literal comprehension'),
q(6,'Tunde enters the classroom dripping with water and places a wet umbrella beside the door. What is the best inference?',['It was probably raining outside','Tunde’s favourite colour is blue','Tunde bought the umbrella that morning','The classroom roof is broken'],'It was probably raining outside','The wet clothing and umbrella are spoken clues supporting the conclusion that rain was likely.',1,'inference from clues'),
q(7,'Why is the answer in Question 6 an inference rather than a literal answer?',['The rain is not stated directly; the listener combines clues to reach the conclusion','The answer has no evidence','Every answer about weather is inferential','The listener is allowed to invent missing details'],'The rain is not stated directly; the listener combines clues to reach the conclusion','Inference uses evidence plus reasoning to understand something not stated word-for-word.',2,'literal versus inferential'),
q(8,'Which formula best represents a sound inference?',['evidence + reasoning','guess + imagination','opinion + confidence','memory + speed'],'evidence + reasoning','An inference must be supported by clues from the oral text and logical reasoning.',1,'inference'),
q(9,'Which question mainly requires critical comprehension?',['Was Kunle’s decision sensible? Give a reason from the situation.','What was Kunle’s name?','Where did Kunle go?','At what time did Kunle arrive?'],'Was Kunle’s decision sensible? Give a reason from the situation.','Critical comprehension asks the learner to evaluate or judge information and justify the response.',1,'critical comprehension'),
q(10,'A learner says, “I disagree,” when asked to judge a speaker’s proposal. What is missing?',['A reason supported by the oral text or sound reasoning','A louder voice','A second unrelated opinion','A memorised definition'],'A reason supported by the oral text or sound reasoning','Critical answers should explain the judgement rather than state an unsupported opinion.',2,'critical response'),
q(11,'Oral text: “Chika arrived at the market at eight o’clock and bought three oranges.” Which question is literal?',['How many oranges did Chika buy?','Why does Chika prefer oranges?','Was buying oranges a wise decision?','What might Chika cook later?'],'How many oranges did Chika buy?','The number three is stated directly in the oral text.',1,'literal detail'),
q(12,'Oral text: “When the final bell rang, Bisi packed her books, waved goodbye and hurried towards the school gate.” What is the best inference?',['Bisi was probably preparing to leave school','Bisi had lost her books','Bisi was beginning the school day','Bisi was going to the laboratory'],'Bisi was probably preparing to leave school','The final bell, packing, goodbye and movement to the gate combine to support this inference.',2,'multi-clue inference'),
q(13,'Which action is a common listening mistake?',['Trying to remember every word instead of tracking meaning and key details','Listening for names, times and reasons','Using context to understand an unfamiliar word','Checking whether evidence supports an inference'],'Trying to remember every word instead of tracking meaning and key details','Attempting word-for-word memory can overload attention and cause the learner to miss the message.',1,'misconceptions'),
q(14,'If you miss one unfamiliar word in an oral passage, what should you usually do?',['Continue listening and use surrounding context to work out the likely meaning','Stop listening completely','Invent any meaning that comes to mind','Assume the whole passage cannot be understood'],'Continue listening and use surrounding context to work out the likely meaning','Later words, causes, examples or contrasts may provide enough context to recover the meaning.',1,'context strategy'),
q(15,'Announcement: “The sports competition scheduled for Wednesday has been moved to Friday because of forecast heavy rainfall.” Why was the event moved?',['Heavy rainfall was forecast for Wednesday','The athletes requested a holiday','Friday was originally the scheduled day','The sports field was permanently closed'],'Heavy rainfall was forecast for Wednesday','The reason is directly stated after “because,” so this is literal comprehension.',1,'cause and detail'),
q(16,'Sade finds a wallet containing money, bank cards and an identity card. She takes it to a responsible school officer, who helps return it intact. What can reasonably be inferred about Sade?',['She values honesty','She wanted to keep the money','She dislikes school officers','She owns the wallet'],'She values honesty','Returning valuable lost property intact is evidence supporting the character inference.',2,'character inference'),
q(17,'In the wallet situation, why is taking the wallet to a responsible school officer a sensible action?',['It provides a safer, accountable way to identify and return the property','It allows the officer to keep the money','It proves every lost item belongs to the school','It removes the need to identify the owner'],'It provides a safer, accountable way to identify and return the property','This critical judgement evaluates the action against the goal of returning property responsibly.',2,'critical judgement'),
q(18,'A WET FLOOR sign is beside a freshly mopped corridor. Emeka sees it but keeps running and then slips. Which evidence best supports the inference that he ignored a warning?',['He saw the wet-floor sign but continued running','The school has a cleaner','His friend was nearby','The corridor is inside a school'],'He saw the wet-floor sign but continued running','This detail directly links awareness of the warning to the unsafe action.',2,'evidence selection'),
q(19,'Which is the best critical judgement of Emeka’s decision to keep running?',['It was unsafe because he ignored a visible warning about the wet floor','It was sensible because corridors are for running','His friend caused the accident','Wet floors cannot create risk'],'It was unsafe because he ignored a visible warning about the wet floor','A strong critical answer states a judgement and supports it with relevant evidence.',2,'critical judgement'),
q(20,'Which sequence best describes effective oral comprehension?',['prepare and predict → listen for main idea/details → recall, infer, evaluate and respond','guess the answers → ignore details → copy a friend','memorise every sound → stop at unfamiliar words → answer from general knowledge','speak continuously → hear a few words → give an unsupported opinion'],'prepare and predict → listen for main idea/details → recall, infer, evaluate and respond','Effective listening uses purposeful strategies before, during and after the oral text.',3,'integrated mastery')
];
