export type Jss1ACPIQuestion={id:string;classLevel:'JSS1';subject:'English Language';topic:'Parts of speech: Adverbs, Conjunctions, Prepositions and Interjections';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1ACPIQuestion=>({id:`nerdc25-auth-jss1-eng-acpi-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Parts of speech: Adverbs, Conjunctions, Prepositions and Interjections',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1ACPIQuestions:Jss1ACPIQuestion[]=[
q(1,'What can an adverb modify?',['A verb, adjective, another adverb or sometimes a whole clause','Only a noun','Only a preposition','Only an interjection'],'A verb, adjective, another adverb or sometimes a whole clause','Adverbs have several modifying functions; they are not limited to verbs.',1,'adverb meaning'),
q(2,'In “Ada answered politely,” what does “politely” do?',['It modifies the verb answered and expresses manner','It names a person','It joins two clauses','It introduces a noun phrase'],'It modifies the verb answered and expresses manner','Politely tells how Ada answered, so it is an adverb of manner.',1,'adverb manner'),
q(3,'Which word is an adverb of frequency in “She often reads after dinner”?',['often','reads','after','dinner'],'often','Often tells how frequently the reading occurs.',1,'adverb frequency'),
q(4,'In “The water is very cold,” what does “very” modify?',['the adjective cold','the noun water','the verb is only','a conjunction'],'the adjective cold','Very is an adverb of degree intensifying the adjective cold.',1,'adverb degree'),
q(5,'Which statement is correct?',['Not every adverb ends in -ly, and not every -ly word is an adverb','Every adverb ends in -ly','Every -ly word is an adverb','Fast can never be an adverb'],'Not every adverb ends in -ly, and not every -ly word is an adverb','Fast, hard and often can be adverbs, while friendly and lovely commonly function as adjectives.',1,'adverb features'),
q(6,'In “He drives fast,” what part of speech is “fast”?',['adverb','adjective','noun','conjunction'],'adverb','Fast modifies the verb drives by describing how he drives.',1,'context classification'),
q(7,'In “a fast car,” what part of speech is “fast”?',['adjective','adverb','preposition','interjection'],'adjective','Fast modifies the noun car, so it functions as an adjective.',1,'context classification'),
q(8,'What is the main job of a conjunction?',['To join grammatical units and show a relationship between them','To name a person','To express sudden pain only','To describe a noun'],'To join grammatical units and show a relationship between them','Conjunctions connect words, phrases or clauses while signalling relationships such as addition, contrast or reason.',1,'conjunction meaning'),
q(9,'Which conjunction best expresses contrast: “He was tired, ___ he continued working”?',['but','so','because','and'],'but','But signals the contrast between being tired and continuing.',1,'coordinating conjunction'),
q(10,'Which conjunction best expresses result: “He was tired, ___ he rested”?',['so','but','although','because'],'so','So introduces the result of the preceding situation.',1,'logical relationship'),
q(11,'In “We stayed indoors because it was raining,” what relationship does “because” express?',['reason/cause','place','sudden emotion','alternative'],'reason/cause','Because introduces the subordinate clause explaining why they stayed indoors.',1,'subordination'),
q(12,'Which is a correlative conjunction pair?',['either...or','under...table','very...slowly','ouch...oh'],'either...or','Either and or work together to connect alternatives.',1,'correlative conjunction'),
q(13,'What does a preposition normally do?',['Introduces a phrase expressing a relationship involving its object','Joins two independent clauses only','Expresses a sudden reaction','Changes every noun into a verb'],'Introduces a phrase expressing a relationship involving its object','Prepositions relate their complements to other sentence elements in place, time, direction and other ways.',1,'preposition meaning'),
q(14,'Which sentence expresses movement to the inside?',['The child ran into the room','The child is in the room','The child slept in the room','The room is quiet'],'The child ran into the room','Into expresses direction/movement toward the interior, unlike in, which commonly expresses location here.',1,'place and direction'),
q(15,'Which set follows common standard patterns for time prepositions?',['at 8:00; on Tuesday; in September','in 8:00; at Tuesday; on September','on 8:00; in Tuesday; at September','at 8:00; at Tuesday; at September'],'at 8:00; on Tuesday; in September','At commonly marks precise clock time, on a day/date, and in a month/year or longer period.',1,'time prepositions'),
q(16,'Why is “before” a preposition in “before lunch”?',['It introduces the noun lunch as its object','It expresses pain','It modifies an adjective','It joins two full clauses'],'It introduces the noun lunch as its object','Before heads the prepositional phrase “before lunch.”',2,'context-sensitive preposition'),
q(17,'Why is “before” functioning as a conjunction in “before we ate”?',['It introduces the clause “we ate”','It has the noun lunch as object','It expresses surprise','It modifies ate as an adverb of manner'],'It introduces the clause “we ate”','Here before connects the subordinate time clause to the rest of the sentence.',2,'context-sensitive conjunction'),
q(18,'What is an interjection?',['A word or short expression conveying a sudden reaction or feeling, often separate from the clause','A word that always modifies a verb','A word that always joins clauses','A noun naming a place'],'A word or short expression conveying a sudden reaction or feeling, often separate from the clause','Interjections such as Ouch!, Hurray! and Oh! convey reactions and are often grammatically detached.',1,'interjection meaning'),
q(19,'In “Oh, I understand now,” what does “Oh” most naturally express?',['realisation in this context','a physical location','a reason clause','a noun object'],'realisation in this context','The context shows a mild reaction of realisation; an interjection’s exact force depends on context and tone.',2,'interjection context'),
q(20,'Which analysis is correct for “Wow! The extremely careful driver stopped before the gate because a child crossed suddenly”?',['Wow = interjection; extremely/suddenly = adverbs; before = preposition; because = conjunction','Wow = noun; extremely = adjective; before = interjection; because = preposition','All target words are adverbs','Before and because are both nouns'],'Wow = interjection; extremely/suddenly = adverbs; before = preposition; because = conjunction','Each item is classified by its grammatical function: reaction, modification, noun-phrase relation and clause connection respectively.',3,'integrated analysis')
];