export const jss1LetterWritingDeepLessons=[{
 topicId:'revised2025-jss1-english-formal-informal-letters',classLevel:'JSS1',subject:'English Language',topic:'Writing Informal and Formal Letters',
 objectives:['Identify formal and informal letters from purpose and audience','Identify the NERDC-prescribed features of both types','Distinguish their format, tone and language','Plan, draft, edit and write a coherent informal letter','Plan, draft, edit and write a coherent formal letter','Choose a letter type appropriate to a given situation'],
 prerequisites:['sentence construction','paragraphing','capital letters and punctuation','addresses and dates'],
 teaching:[
 'A LETTER is a written message sent to a person or organisation for a particular purpose. Before writing, ask: WHO is receiving it? WHY am I writing? WHAT relationship do I have with the reader? These questions determine whether the letter should be informal or formal.',
 'NERDC requires two types at this level: FORMAL and INFORMAL letters. The difference is not merely layout; audience, purpose, tone, vocabulary and conventions also differ.',
 'An INFORMAL LETTER is a personal letter written to someone with whom the writer has a close or familiar relationship, such as a friend or relative. Its tone can be warm and conversational while remaining clear and grammatically correct.',
 'NERDC specifies these core informal-letter features: ONE address, an opening salutation, the body of the letter and a closing. A date is conventionally written with the writer’s address in school letter-writing practice.',
 'The writer’s address tells the recipient where the letter comes from. Keep the address complete and consistently arranged. The date tells when the letter was written.',
 'An informal salutation should suit the relationship, for example “Dear Amina,” or “Dear Uncle Tunde,”. Do not use an impersonal official greeting when writing naturally to a close friend.',
 'The BODY carries the message. A useful informal structure is: opening paragraph—greet/reconnect and introduce the reason; middle paragraphs—develop the news, explanation or story; final paragraph—round off naturally, perhaps with good wishes or a request for a reply.',
 'Informal does not mean careless. Avoid confusing abbreviations, random slang, poor punctuation and one giant paragraph. Natural personal language can still be accurate and organised.',
 'An informal closing should suit a personal relationship. Examples include “Yours affectionately,” or another course-approved personal close, followed by the writer’s first name/name as appropriate. Follow the convention taught by the school text.',
 'A FORMAL LETTER is written for official, institutional or serious communication—for example to a school principal or another authority. NERDC itself gives a formal letter to the school principal as a model situation.',
 'NERDC specifies these formal-letter features: TWO addresses, an opening salutation, an adequate heading, the body of the letter, a closing and a signature.',
 'The FIRST address is the writer/sender’s address. The SECOND is the recipient’s official address, including the recipient’s position where appropriate, such as “The Principal”. This two-address feature is a major visual difference from the informal letter.',
 'The formal SALUTATION must respect the recipient and the convention being used, for example “Dear Sir,” or “Dear Madam,” where appropriate. If a named-recipient convention is taught, the complimentary close should remain consistent with it.',
 'The HEADING/SUBJECT states the purpose clearly and specifically. “REQUEST FOR PERMISSION TO BE ABSENT FROM SCHOOL” is stronger than a vague heading such as “LETTER”. The heading helps the recipient understand the matter immediately.',
 'The formal BODY should be direct and logically paragraphed. Paragraph 1 states the purpose. Middle paragraph(s) provide necessary facts, reasons or details. The final paragraph states the requested action or courteous conclusion.',
 'FORMAL TONE means respectful, clear, restrained and purposeful. Prefer “I am writing to request permission…” to chat-like expressions. Avoid insults, unnecessary slang, emojis and over-familiar language.',
 'Politeness does not mean begging or filling the letter with grand words. A strong formal letter communicates the necessary facts accurately, courteously and concisely.',
 'The formal CLOSING and SIGNATURE complete the letter. In a common school convention, “Yours faithfully,” is used after “Dear Sir/Madam,” followed by the writer’s signature and name. Where a course teaches named-recipient conventions, follow that prescribed pairing consistently.',
 'FORMAT and CONTENT must work together. A perfectly arranged formal letter with no clear purpose is weak; a sensible message in the wrong format is also incomplete.',
 'COMPARE: Informal—one address, familiar recipient, personal/conversational tone, no NERDC-required formal heading. Formal—two addresses, official recipient, adequate heading, formal respectful tone, closing and signature.',
 'AUDIENCE TEST: writing to your friend about your new school → informal. Writing to your principal requesting permission → formal. The situation determines the type.',
 'PURPOSE TEST: identify exactly what the task asks—inform, invite, thank, narrate, request, complain or apply. Include only details that help achieve that purpose.',
 'PLAN BEFORE WRITING: AUDIENCE → PURPOSE → TYPE → REQUIRED FORMAT → 3–5 KEY POINTS → PARAGRAPH ORDER. Planning prevents a correct-looking letter with missing content.',
 'DRAFT: turn the plan into complete paragraphs. Give each paragraph a clear job and use linking expressions where needed.',
 'EDIT: check (1) correct type, (2) addresses, (3) salutation, (4) heading where formal, (5) all task points, (6) paragraphing, (7) tone/register, (8) grammar/spelling/punctuation, (9) suitable closing, and (10) signature where formal.',
 'Do not mix formats. A formal letter should not suddenly become a chat with a friend; an informal letter should not contain a second official recipient address simply because formal letters do.',
 'AVORA LETTER ROUTINE: READ TASK → IDENTIFY AUDIENCE/PURPOSE → CHOOSE TYPE → LAY OUT FEATURES → PLAN POINTS → DRAFT → EDIT → FINAL CHECK.'
 ],
 workedExamples:[
 'TASK: Write to your friend describing your new school. Audience = friend; purpose = share personal experience; type = informal.',
 'TASK: Write to your principal requesting permission to miss school for an important appointment. Audience = school authority; purpose = official request; type = formal.',
 'INFORMAL skeleton: writer’s address/date → Dear [name], → opening → developed body paragraphs → friendly final paragraph → suitable personal close → name.',
 'FORMAL skeleton: writer’s address/date → recipient’s official address → Dear Sir/Madam, → clear heading → purpose paragraph → details/reasons → courteous final paragraph → formal close → signature/name.',
 'Weak informal opening: “I am writing this letter to inform you that I am fine.” Better natural opening: “How are you and everyone at home? I have been eager to tell you about my new school.”',
 'Weak formal opening: “How are you? I hope you are enjoying yourself.” Better: “I am writing to request permission to be absent from school on Friday, 9 October 2026, for an important family appointment.”',
 'Weak heading: “A LETTER.” Better: “REQUEST FOR PERMISSION TO BE ABSENT FROM SCHOOL.”',
 'Weak formal tone: “You must fix this problem now.” Better respectful request: “I respectfully request that the matter be considered.”',
 'BODY ORGANISATION: purpose first; relevant explanation second; requested action/thanks last. Do not hide the purpose until the final paragraph.',
 'INFORMAL paragraphing: reconnect → main news/story → further detail/reaction → closing wishes. The exact number of paragraphs depends on the task.',
 'FORMAL CONTENT CHECK: if the task asks for permission and a reason, a beautiful format without the reason does not fully answer the question.',
 'INFORMAL CONTENT CHECK: if asked to describe a new school, include meaningful details—environment, people, activities or experiences—not only greetings.',
 'REGISTER CONTRAST: “Guess what happened!” can suit a friend in context; “I wish to bring the following matter to your attention” suits formal communication.',
 'ERROR REPAIR: A letter to a principal with one address, “Hi Principal!”, no heading and “Cheers” mixes informal conventions. Restore the second address, formal salutation, adequate heading, appropriate body and formal close/signature.',
 'ERROR REPAIR: A letter to a close friend written like an official application may be grammatically correct but mismatched to audience and purpose.',
 'FINAL AUDIT: cover the task prompt and ask whether a reader can identify the letter type from layout, tone and purpose before reading every sentence.'
 ],
 misconceptions:['thinking letter type depends only on topic rather than audience/purpose','giving a formal letter only one address','giving an informal letter two official addresses','omitting the heading from a formal letter','using a vague heading such as LETTER','believing informal means grammatically careless','using slang or emojis in formal letters','using an over-familiar opening to an authority','writing all body content as one paragraph','memorising a sample and ignoring the actual task','including irrelevant details just to make the letter long','mixing salutation and closing conventions','forgetting the formal signature','focusing on layout while failing to answer the purpose'],
 guidedPractice:[
 'LETTER SORT: classify twelve situations as formal or informal and justify each answer using audience, relationship and purpose.',
 'FEATURE LABEL: annotate model letters, identifying address(es), date, salutation, heading where required, body paragraphs, closing and signature.',
 'TONE SWITCH: rewrite six chat-like sentences for a formal recipient, then make six stiff official sentences natural for a close friend.',
 'PARAGRAPH PLAN: turn a prompt into audience, purpose, letter type, required features and four ordered content points before drafting.',
 'NERDC GROUP DRAFT: one group writes a formal letter to the principal while another writes an informal letter to a friend; exchange drafts and check tone and format.',
 'ERROR CLINIC: repair two deliberately mixed-up letters containing wrong address count, salutation, heading, paragraphing, register and closing.',
 'MODEL COMPARISON: compare two letters answering the same broad issue for different audiences and explain every change in format and language.'
 ],
 independentPractice:[
 'Write an informal letter to a friend telling him/her about your new school. Use the NERDC informal features and develop at least three meaningful content points.',
 'Write a formal letter to your school principal requesting permission to be absent for a genuine stated reason. Use all NERDC formal features and an adequate heading.',
 'Given one informal and one formal draft containing format, tone and content errors, edit both and explain at least eight corrections.',
 'Choose two situations from invitation, request, complaint, thanks or personal news. Decide the suitable letter type, plan each, then write one complete letter and justify the type chosen for the other.'
 ],
 source:{authority:'NERDC Revised BEC 2025',url:'https://nerdc.gov.ng',verified:'OFFICIAL_SCOPE_PRESERVED_WITH_NIGERIAN_JSS_REFERENCE_CROSSCHECK'},
 mastery:{criterion:'Learner identifies formal/informal letters and their NERDC-prescribed features, chooses the appropriate type for unfamiliar situations, and writes both with correct format, audience-appropriate tone, coherent paragraphs and complete task content at at least 80% mastery.',status:'DEEP_WHEN_PASSED'}
}];