export type Jss1MeaningQuestion={id:string;classLevel:'JSS1';subject:'English Language';topic:'Reading passages for meaning';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1MeaningQuestion=>({id:`nerdc25-auth-jss1-eng-meaning-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Reading passages for meaning',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1MeaningQuestions:Jss1MeaningQuestion[]=[
q(1,'What is the difference between a topic and a main idea?',['The topic names the general subject; the main idea states the most important point about it','The topic is always a sentence; the main idea is always one word','They always mean exactly the same thing','The main idea is only the title'],'The topic names the general subject; the main idea states the most important point about it','A topic such as “road safety” names the subject; a main idea explains what the writer is saying about road safety.',1,'topic versus main idea'),
q(2,'What is a supporting idea or detail?',['Information that explains, proves, illustrates or develops the main idea','The title of every passage','Any sentence the reader personally likes','A sentence that must always come first'],'Information that explains, proves, illustrates or develops the main idea','Supporting information may be a reason, example, fact, description, cause, effect or evidence.',1,'supporting details'),
q(3,'Paragraph: “Trees provide shade in the school compound. Their roots can help hold soil together. They can also make the environment more pleasant.” Which main idea best covers the details?',['Trees can benefit the school environment in several ways','Tree roots exist underground','Shade is the only useful part of a tree','Every school must become a forest'],'Trees can benefit the school environment in several ways','The answer works as an umbrella over all three important details rather than selecting only one.',1,'umbrella test'),
q(4,'Why is “Tree roots can hold soil” too narrow as the main idea for Question 3?',['It covers only one supporting detail and leaves the other important details out','It is grammatically incorrect','It is too long','It is a question'],'It covers only one supporting detail and leaves the other important details out','A main idea should account for most of the important supporting information.',1,'too narrow'),
q(5,'Which statement is most likely TOO BROAD for a paragraph about wearing seat belts, using pedestrian crossings and obeying traffic lights?',['Safety is important everywhere','Following road-safety rules can reduce avoidable danger','Road users can take practical steps to improve safety','Several road-safety behaviours reduce risk'],'Safety is important everywhere','It is related to safety but is so general that it does not accurately capture the paragraph’s particular focus on road use.',2,'too broad'),
q(6,'Where can a stated main idea appear?',['At the beginning, middle or end of a paragraph','Only in the first sentence','Only in the final sentence','Only in the title'],'At the beginning, middle or end of a paragraph','A topic sentence often carries the main idea, but its position is not fixed.',1,'stated main idea'),
q(7,'What should a reader do when no sentence states the main idea directly?',['Combine the important related details and infer the central message','Choose the first sentence automatically','Invent a personal opinion','Use only the title'],'Combine the important related details and infer the central message','An implied main idea is constructed from the pattern created by the paragraph’s important details.',2,'implied main idea'),
q(8,'Musa checks a message’s source, compares it with another reliable source and checks its publication date. What is the best implied main idea?',['Musa verifies information before accepting or sharing it','Musa dislikes reading dates','Every message online is false','Publication dates are the only thing that matters'],'Musa verifies information before accepting or sharing it','All three actions support the broader idea of careful verification.',2,'implied main idea'),
q(9,'Which expression often introduces an example or illustration?',['for example','however','therefore','although'],'for example','“For example” commonly signals that the next information illustrates a broader idea.',1,'signal words'),
q(10,'Which expression commonly signals a reason?',['because','finally','however','for example'],'because','“Because” commonly introduces a cause or reason supporting another statement.',1,'text relationships'),
q(11,'A paragraph says strong passwords, suspicious-link checks and privacy settings improve online safety. Which is the best main idea?',['Several responsible habits can improve online safety','Passwords contain letters','Links exist on the internet','Privacy settings are the only cyber-security measure'],'Several responsible habits can improve online safety','The best main idea unites the several related safety details.',1,'cyber-security passage'),
q(12,'Which detail does NOT support the main idea “The school reduced waste through organised action”?',['The principal enjoys watching football','Labelled bins were placed around the compound','Pupils learned to separate waste','A collection routine was introduced'],'The principal enjoys watching football','The football preference is unrelated to the school’s waste-reduction actions.',1,'relevance of details'),
q(13,'Why should a reader not choose an answer simply because it is true in real life?',['The correct main idea must be developed by the passage itself','Real-life knowledge is never useful','Every passage is fictional','Main ideas cannot contain facts'],'The correct main idea must be developed by the passage itself','Reading comprehension requires evidence from the text, not merely a generally true statement.',2,'text evidence'),
q(14,'Students from different backgrounds listen to one another, divide tasks fairly and resolve disagreements through discussion. Which idea best unites the details?',['Respectful cooperation helps people work peacefully together','All disagreements are harmful','Group work requires identical opinions','Only one student should make decisions'],'Respectful cooperation helps people work peacefully together','The details jointly develop peaceful coexistence through respectful cooperation.',2,'peaceful coexistence'),
q(15,'An AI paragraph explains that AI can recognise patterns and generate responses but can sometimes produce inaccurate information. Which main idea is strongest?',['AI can perform useful tasks, but important outputs should still be checked','AI is always correct','Pattern recognition is the only use of AI','People should accept every generated response'],'AI can perform useful tasks, but important outputs should still be checked','The answer captures both major sides developed in the paragraph.',2,'AI passage'),
q(16,'Why is the title of a passage not automatically its main idea?',['A title may name or suggest the subject, while the passage must be read to determine the writer’s complete central message','Titles are never related to passages','Main ideas must be questions','Titles contain no words'],'A title may name or suggest the subject, while the passage must be read to determine the writer’s complete central message','The title is a useful clue, but textual evidence must confirm the actual main idea.',2,'title versus main idea'),
q(17,'Paragraph 1 explains how a rumour spreads online. Paragraph 2 explains checking the source/date. Paragraph 3 explains comparing claims with reliable evidence. What is the strongest overall idea?',['Careful verification helps people avoid spreading unreliable online information','Dates are the only important part of a message','All online information is false','Rumours should be shared quickly'],'Careful verification helps people avoid spreading unreliable online information','The overall idea must connect the important ideas across all three paragraphs.',2,'whole-passage main idea'),
q(18,'Which response best JUSTIFIES a main-idea answer?',['The main idea is online verification because the paragraph discusses checking the source, date and supporting evidence','I chose it because I like it','It sounds important','It was the longest option'],'The main idea is online verification because the paragraph discusses checking the source, date and supporting evidence','A strong justification points to textual details that the proposed main idea unites.',2,'evidence justification'),
q(19,'What is the purpose of the one-sentence test?',['To express what the paragraph is mainly saying in one accurate, appropriately broad sentence','To copy the longest sentence','To remove all supporting details before reading','To turn every paragraph into one word'],'To express what the paragraph is mainly saying in one accurate, appropriately broad sentence','A one-sentence restatement helps reveal whether the reader has captured the central meaning rather than one minor detail.',2,'paraphrasing main idea'),
q(20,'Which sequence is most reliable for reading a paragraph for meaning?',['identify topic → determine central claim → test it against supporting details → state the main idea with evidence','choose first sentence → ignore other details → guess','read title only → use personal opinion → stop','count repeated words → select the longest sentence automatically'],'identify topic → determine central claim → test it against supporting details → state the main idea with evidence','This process integrates the paragraph instead of relying on a superficial clue such as sentence position or word repetition.',3,'integrated mastery')
];