export type Jss1WFQ={id:string;classLevel:'JSS1';subject:'English Language';topic:'Use of Prefixes, Suffixes and Compounds';prompt:string;options:string[];correctAnswer:string;explanation:string;difficulty:1|2|3;skill:string};
const q=(n:number,prompt:string,options:string[],correctAnswer:string,explanation:string,difficulty:1|2|3,skill:string):Jss1WFQ=>({id:`nerdc25-auth-jss1-eng-wf-${String(n).padStart(2,'0')}`,classLevel:'JSS1',subject:'English Language',topic:'Use of Prefixes, Suffixes and Compounds',prompt,options,correctAnswer,explanation,difficulty,skill});
export const jss1WordFormationQuestions:Jss1WFQ[]=[
q(1,'What is a prefix?',['An affix placed before a base','An affix placed after a base','Two complete sentences joined together','A punctuation mark'],'An affix placed before a base','A prefix occurs before the base, as un- does in unhappy.',1,'prefix meaning'),
q(2,'What is a suffix?',['An affix placed after a base','An affix placed before a base','A type of sentence','A capital letter'],'An affix placed after a base','A suffix follows the base, as -ful does in hopeful.',1,'suffix meaning'),
q(3,'What does “rewrite” most naturally mean?',['write again','not write','write without care','a person who writes'],'write again','The prefix re- commonly contributes the meaning again in rewrite.',1,'prefix re'),
q(4,'Which is the NERDC example formed with de-?',['decode','unhappy','rewrite','hopeful'],'decode','NERDC lists de- with decode among its common prefix examples.',1,'prefix de'),
q(5,'Which word contains the suffix -ful?',['hopeful','hopeless','happiness','unhappy'],'hopeful','Hopeful is formed from hope plus the suffix -ful.',1,'suffix ful'),
q(6,'Which word contains the suffix -less?',['helpless','helpful','happiness','rewrite'],'helpless','Helpless is formed from help plus -less, expressing lack/absence in context.',1,'suffix less'),
q(7,'What happens to the word class in happy→happiness?',['An adjective becomes a noun','A noun becomes a verb','A verb becomes an adjective','Nothing can be said about word class'],'An adjective becomes a noun','Happy is an adjective; -ness forms the abstract noun happiness.',2,'suffix and word class'),
q(8,'Which spelling is correct?',['hopeful','hopefull','hope-full-l','hopful'],'hopeful','The suffix is conventionally written -ful with one l.',1,'suffix spelling'),
q(9,'Which shows a spelling change when -ness is added?',['happy→happiness','kind→kindness','dark→darkness','weak→weakness'],'happy→happiness','Final y changes to i in happiness.',1,'spelling change'),
q(10,'Why should you not automatically split every word beginning with the letters “re”?',['The letters may not function as the prefix re- in that particular word','Every re word is a compound','Prefixes occur only at the end','Re- can never be a prefix'],'The letters may not function as the prefix re- in that particular word','Morphological analysis must identify a meaningful base and a real contribution from the affix.',2,'morphological analysis'),
q(11,'What is a compound word/expression?',['An established lexical unit formed from meaningful words/bases','Any two words beside each other','A word containing only a suffix','A sentence with two verbs'],'An established lexical unit formed from meaningful words/bases','Compounds combine meaningful elements into a recognised unit.',1,'compound meaning'),
q(12,'Which NERDC example is a closed compound?',['classroom','swimming pool','sister-in-law','return ticket'],'classroom','Classroom is written as one word and is a closed compound.',1,'closed compound'),
q(13,'Which NERDC example is an open compound?',['swimming pool','blackboard','teapot','sister-in-law'],'swimming pool','Swimming pool is written as separate words but functions as an established unit.',1,'open compound'),
q(14,'Which NERDC example is hyphenated?',['sister-in-law','classroom','market square','blackboard'],'sister-in-law','Sister-in-law is written with hyphens in the curriculum example.',1,'hyphenated compound'),
q(15,'Which pair contains two closed compounds from the NERDC list?',['blackboard and teapot','return ticket and market square','swimming pool and night flight','sister-in-law and dining room'],'blackboard and teapot','Both blackboard and teapot are written together.',1,'compound classification'),
q(16,'Which pair contains two open compounds from the NERDC list?',['dining room and market square','classroom and lifelong','blackboard and teapot','sister-in-law and classroom'],'dining room and market square','Both expressions are written as separate words while functioning as established units.',1,'compound classification'),
q(17,'Why is “red bag” not automatically a compound simply because the words are adjacent?',['Adjacency alone does not prove that the words form an established lexical unit','Every adjective+noun pair is a compound','Red can never modify a noun','All compounds must contain a hyphen'],'Adjacency alone does not prove that the words form an established lexical unit','Compound status depends on established lexical use and meaning, not mere proximity.',2,'compound reasoning'),
q(18,'Which analysis is correct for “unhappy”?',['un- is a prefix added before happy','-happy is a suffix added to un','unhappy is an open compound','un is a preposition'],'un- is a prefix added before happy','The base is happy and the prefix un- is attached before it.',1,'word analysis'),
q(19,'In “The unhappy pupil reread the notice beside the classroom,” which analysis is correct?',['unhappy and reread contain prefixes; classroom is a closed compound','all three are suffix words','classroom is an open compound','reread contains the suffix -read'],'unhappy and reread contain prefixes; classroom is a closed compound','Un- and re- occur before their bases; classroom combines class+room as a closed compound.',2,'text identification'),
q(20,'Which method best analyses a newly formed word?',['Identify the base and affix/compound parts, check accepted spelling, explain meaning and word class, then use it in context','Count its letters only','Assume every beginning is a prefix','Join any two words and call them a compound'],'Identify the base and affix/compound parts, check accepted spelling, explain meaning and word class, then use it in context','Complete word analysis connects structure, conventional spelling, meaning, grammar and actual use.',3,'integrated word formation')
];