export type DeepJss2MathLesson={
 topicId:string; classLevel:'JSS2'; subject:'Mathematics'; topic:string;
 source:{authority:'NERDC';url:string;page:number}; objectives:string[]; prerequisites:string[];
 teaching:string[]; workedExamples:string[]; misconceptions:string[]; guidedPractice:string[]; independentPractice:string[];
 mastery:{criterion:string;status:'DEEP_WHEN_PASSED'}; boardReady:true;
};

const sourceUrl='https://nerdc.gov.ng/content_manager/jss/jss1-3_maths.pdf';

/** AVORA-authored teaching. NERDC controls scope/objectives; explanations, examples and practice are original. */
export const jss2MathematicsDeepLessons:DeepJss2MathLesson[]=[
{
 topicId:'nerdc-jss2-math-numbers-and-numeration-whole-numbers-1',classLevel:'JSS2',subject:'Mathematics',topic:'Whole Numbers',source:{authority:'NERDC',url:sourceUrl,page:18},
 objectives:['Express whole numbers in standard form','Express decimal numbers in standard form','Find prime factors of numbers not greater than 200','Express numbers as products of prime factors','Find LCM and HCF','Identify perfect squares and find squares','Find square roots of perfect squares by factor method and estimate other square roots','Solve quantitative-reasoning problems using these ideas'],
 prerequisites:['JSS1 place value and large numbers','meaning of prime number, factor and multiple','basic multiplication and division facts','powers such as 10² and 10³'],
 teaching:[
  'STANDARD FORM — MEANING FIRST. Standard form writes a non-zero number as a×10^n where 1≤a<10. The first factor tells the significant digits while the power of ten records the place-value shift. A number such as 48,000 is not written as 48×10³ in standard form because 48 is not between 1 and 10.',
  'WHOLE NUMBERS IN STANDARD FORM. Move the decimal point left until exactly one non-zero digit remains before it. Count the number of places moved; that count becomes a positive power of ten. Example: 725,000→7.25×10⁵ because the decimal point moves five places left.',
  'DECIMALS IN STANDARD FORM. Move the decimal point right until the first factor lies between 1 and 10. A rightward move produces a negative exponent because the original number is smaller than 1. Example: 0.00084→8.4×10⁻⁴.',
  'CHECKING STANDARD FORM. Reverse the multiplication by 10^n. For 6.03×10⁶, move the decimal six places right to recover 6,030,000. For 9.05×10⁻³, move three places left to recover 0.00905.',
  'PRIME NUMBERS AND PRIME FACTORS. A prime number has exactly two positive factors: 1 and itself. Composite numbers have more than two. Prime factorization rewrites a number entirely as a product of prime numbers. A factor tree is complete only when every branch ends in primes.',
  'FACTOR-TREE METHOD. Begin with any convenient factor pair, then continue splitting every composite factor. Different trees may look different but must finish with the same prime factors, apart from order.',
  'REPEATED-DIVISION METHOD. Divide successively by the smallest prime that works exactly: usually 2, then 3, then 5, 7 and so on. Stop when the quotient becomes 1. The divisors written down are the prime factors.',
  'INDEX FORM. Repeated prime factors can be compressed with powers. For example, 2×2×2×3×3 becomes 2³×3². The exponent tells how many times that prime is used as a factor.',
  'LCM FROM PRIME FACTORS. The LCM must contain enough prime factors to be divisible by every given number. Therefore take every prime that appears and use its HIGHEST power among the numbers.',
  'HCF FROM PRIME FACTORS. The HCF must divide every given number, so only primes shared by all numbers can be used, and each shared prime can appear only to the LOWEST power present in all.',
  'PERFECT SQUARES. A perfect square is a whole number obtained by multiplying an integer by itself: 1,4,9,16,25,36,49,64,81,100,… In prime-factor form, every exponent in a perfect square is even because factors pair up.',
  'SQUARE ROOT OF A PERFECT SQUARE BY FACTOR METHOD. Prime-factorize the number, group equal primes into pairs, then take one factor from each pair. For 196=2²×7², √196=2×7=14.',
  'NON-PERFECT SQUARE ROOT BY ESTIMATION. First bracket the number between two consecutive perfect squares. If 64<70<81, then 8<√70<9. Test sensible decimals such as 8.3 or 8.4 and square them to decide which is closer.',
  'QUANTITATIVE REASONING. These ideas appear inside practical questions: scientific notation for large/small measurements, HCF for greatest equal group size, LCM for repeating schedules, and square roots for side lengths of squares. The learner must first identify which relationship the situation is describing before calculating.',
  'PERMANENT CHECKING RULE. Standard-form answers must reverse correctly; prime factorizations must multiply back to the original number; LCM must be divisible by each number; HCF must divide each number; square-root estimates should square back close to the original value.'
 ],
 workedExamples:[
  'STANDARD FORM — WHOLE NUMBER. Express 48,000 in standard form. Move the decimal 4 places left: 48,000→4.8. Therefore 48,000=4.8×10⁴. Check: 4.8×10,000=48,000.',
  'STANDARD FORM — LARGER NUMBER. Express 6,030,000 in standard form. Move the decimal 6 places left: 6,030,000=6.03×10⁶. Check by moving the decimal six places right.',
  'STANDARD FORM — SMALL DECIMAL. Express 0.0063 in standard form. Move the decimal 3 places right to get 6.3. Because the original is smaller than 1, the exponent is negative: 0.0063=6.3×10⁻³.',
  'STANDARD FORM — VERY SMALL DECIMAL. Express 0.00084 in standard form. Move the decimal 4 places right to get 8.4, so 0.00084=8.4×10⁻⁴.',
  'PRIME FACTORIZATION — FACTOR TREE. Factorize 84. One tree is 84=12×7, 12=3×4, 4=2×2. Therefore 84=2²×3×7. Check: 4×3×7=84.',
  'PRIME FACTORIZATION — REPEATED DIVISION. Factorize 180. Divide: 180÷2=90, 90÷2=45, 45÷3=15, 15÷3=5, 5÷5=1. Therefore 180=2²×3²×5.',
  'LCM — TWO NUMBERS. Find LCM of 72 and 90. 72=2³×3²; 90=2×3²×5. Highest powers are 2³,3²,5. LCM=2³×3²×5=8×9×5=360.',
  'HCF — TWO NUMBERS. Find HCF of 72 and 90. Shared primes are 2 and 3. Lowest powers are 2¹ and 3². HCF=2×9=18.',
  'LCM AND HCF — THREE NUMBERS. For 36=2²×3², 48=2⁴×3 and 60=2²×3×5: HCF=2²×3=12. LCM=2⁴×3²×5=720. Check: 720 is divisible by 36,48 and 60; 12 divides all three.',
  'PERFECT SQUARE RECOGNITION. Is 144 a perfect square? 144=12×12, so yes. Prime-factor check: 144=2⁴×3²; every exponent is even. Therefore √144=12.',
  'SQUARE ROOT BY PRIME FACTORS. Find √196. 196=2×98=2×2×49=2²×7². Pair the equal factors: (2×2)(7×7). Take one from each pair: √196=2×7=14.',
  'SQUARE ROOT — NOT PERFECT. Estimate √50 to 1 d.p. Since 7²=49 and 8²=64, √50 lies just above 7. Try 7.1: 7.1²=50.41. Therefore √50≈7.1 to 1 d.p.',
  'SQUARE ROOT — CLOSER COMPARISON. Estimate √70 to 1 d.p. Since 8²=64 and 9²=81, √70 is between 8 and 9. 8.3²=68.89 and 8.4²=70.56. 70 is closer to 70.56 than 68.89, so √70≈8.4 to 1 d.p.',
  'QUANTITATIVE REASONING — REPEATING EVENTS. A bus leaves every 18 minutes and another every 24 minutes. They leave together now. When next together? 18=2×3², 24=2³×3. LCM=2³×3²=72. They leave together again after 72 minutes.',
  'QUANTITATIVE REASONING — GREATEST EQUAL GROUPS. 84 red beads and 126 blue beads are to be packed into the greatest possible number of identical groups with no leftovers. 84=2²×3×7, 126=2×3²×7. HCF=2×3×7=42, so 42 identical groups can be made.'
 ],
 misconceptions:[
  'writing 48×10³ as standard form even though the first factor is not between 1 and 10',
  'using a positive exponent for a number smaller than 1',
  'counting decimal-point moves in the wrong direction',
  'leaving composite factors such as 6 or 9 in a prime factorization',
  'assuming a different factor tree gives a different prime factorization',
  'using highest powers for HCF or lowest powers for LCM',
  'including a prime in the HCF when it is not present in every number',
  'assuming every square root is a whole number',
  'pairing unlike prime factors when using the square-root factor method',
  'giving an estimated square root without bracketing it between perfect squares and checking by squaring'
 ],
 guidedPractice:[
  'Express 725,000 and 0.00084 in standard form and reverse each answer to verify it.',
  'Prime-factorize 168 using a factor tree and 180 using repeated division.',
  'Find HCF and LCM of 24 and 54 using prime factors; verify both results.',
  'Find HCF and LCM of 36,48 and 60.',
  'Decide whether 225 is a perfect square and justify using both multiplication and prime factors.',
  'Find √196 by prime factors.',
  'Estimate √82 to 1 d.p. by bracketing and testing.',
  'Two warning lights flash every 15 s and 20 s. Determine when they next flash together and explain why LCM is used.'
 ],
 independentPractice:[
  'Write 8,450,000 in standard form.',
  'Write 0.000072 in standard form.',
  'Convert 3.68×10⁵ to an ordinary number.',
  'Convert 7.02×10⁻⁴ to an ordinary decimal.',
  'Prime-factorize 96.',
  'Prime-factorize 150.',
  'Prime-factorize 192.',
  'Find HCF of 84 and 126.',
  'Find LCM of 24 and 90.',
  'Find HCF and LCM of 36,48,60.',
  'List the perfect squares between 50 and 150.',
  'Find 17² without a calculator and state whether 289 is a perfect square.',
  'Find √324 using prime factors.',
  'Estimate √65 to 1 d.p. and check by squaring.',
  'Estimate √115 to 1 d.p.',
  'Three bells ring every 12,18 and 30 minutes. If they ring together now, after how many minutes will they next ring together?',
  'A teacher has 72 pencils and 96 rulers and wants the greatest number of identical packs with nothing left over. How many packs can be made and what is in each pack?',
  'A square courtyard has area 625 m². Find the side length and explain why a square root is required.'
 ],
 mastery:{criterion:'At least 80% across standard form, prime factorization, LCM/HCF, perfect squares, square roots and quantitative reasoning, with every answer checked using an appropriate reverse or reasonableness method.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-numbers-and-numeration-fractions-1',classLevel:'JSS2',subject:'Mathematics',topic:'Fractions',source:{authority:'NERDC',url:sourceUrl,page:19},
 objectives:['Convert simple fractions to ratios, decimals and percentages and vice versa','Solve quantitative-reasoning problems involving fractions, ratios, decimals and percentages'],
 prerequisites:['JSS1 equivalent fractions and simplification','basic division','meaning of ratio','place value in decimals','percentage as parts per hundred'],
 teaching:[
  'FRACTION, RATIO, DECIMAL AND PERCENTAGE ARE RELATED BUT NOT IDENTICAL WORDS. A fraction such as 3/5 describes three equal parts out of five equal parts of a whole. A ratio such as 3:5 compares two quantities. A decimal such as 0.6 is a base-ten representation of the same numerical value as 3/5, while 60% means 60 out of every 100.',
  'FRACTION TO DECIMAL. Divide the numerator by the denominator. For 3/5, calculate 3÷5=0.6. The division is not a trick: a fraction bar itself means division.',
  'FRACTION TO PERCENTAGE. Either convert to decimal and multiply by 100%, or create an equivalent fraction with denominator 100 when convenient. For 3/5, 0.6×100%=60%. Also, 3/5=60/100=60%.',
  'DECIMAL TO FRACTION. Use place value. 0.45 means 45 hundredths, so 0.45=45/100. Then simplify by the HCF: HCF(45,100)=5, so 45/100=9/20.',
  'PERCENTAGE TO FRACTION. The symbol % means “per hundred”. Therefore 35%=35/100=7/20 after dividing numerator and denominator by 5.',
  'PERCENTAGE TO DECIMAL. Divide by 100, which is the same as moving the decimal point two places left. Thus 62.5%=0.625. To check, 0.625×100%=62.5%.',
  'DECIMAL TO PERCENTAGE. Multiply by 100%. For 0.375, 0.375×100%=37.5%. This preserves the value because percent is simply a different scale of representation.',
  'RATIO — IDENTIFY WHAT IS BEING COMPARED. If a class has 12 boys and 20 girls, boys:girls=12:20=3:5. But boys:total=12:32=3:8. The same data produce different ratios because the quantities being compared are different.',
  'RATIO MUST USE COMMON UNITS. Before forming a ratio, convert quantities to the same unit. For 2.5 m:50 cm, convert 2.5 m to 250 cm; ratio=250:50=5:1.',
  'PART-TO-PART AND PART-TO-WHOLE. If red:blue=2:3, red is 2 out of 5 total parts, so red fraction of the whole is 2/5 and red percentage is 40%. The ratio 2:3 must not be mistaken for fraction 2/3 of the total.',
  'SHARING IN A RATIO. Add the ratio parts first. To share ₦4,200 in the ratio 2:5, total parts=7. One part=₦4,200÷7=₦600. Shares are 2×₦600=₦1,200 and 5×₦600=₦3,000.',
  'FINDING A PERCENTAGE OF A QUANTITY. Convert the percentage to a fraction or decimal and multiply by the quantity. 15% of ₦2,400=15/100×2,400=₦360.',
  'PERCENTAGE INCREASE. First find the increase, then add it to the original amount. Increasing ₦800 by 12.5% gives increase=0.125×800=₦100, so new amount=₦900.',
  'PERCENTAGE DECREASE. First find the decrease, then subtract it. Decreasing ₦6,000 by 18% gives decrease=0.18×6,000=₦1,080, so new amount=₦4,920.',
  'FINDING THE WHOLE FROM A PART. If 30% of a number is 72, write 0.30×whole=72. Whole=72÷0.30=240. This is different from finding 30% of a known whole.',
  'QUANTITATIVE REASONING — READ THE RELATIONSHIP BEFORE CALCULATING. Ask whether the unknown is a fraction, decimal, percentage, ratio share, part or whole. The representation may change, but the actual quantity must remain equivalent.',
  'PERMANENT CHECKING RULE. Convert back whenever possible. If 3/8 becomes 37.5%, convert 37.5% back to 0.375 and then to 3/8. Ratio shares must add to the original total. Percentage increases/decreases must move the amount in the expected direction.'
 ],
 workedExamples:[
  'FRACTION TO DECIMAL AND PERCENTAGE. Convert 7/8. Decimal: 7÷8=0.875. Percentage: 0.875×100%=87.5%. Therefore 7/8=0.875=87.5%.',
  'FRACTION WITH EASY DENOMINATOR 100. Convert 3/20 to a percentage. Multiply numerator and denominator by 5: 3/20=15/100=15%. Decimal=0.15.',
  'DECIMAL TO FRACTION. Convert 0.45. 0.45=45/100. HCF(45,100)=5. Divide both by 5: 45/100=9/20.',
  'DECIMAL TO FRACTION — THREE DECIMAL PLACES. 0.375=375/1000. HCF=125. Divide: 375÷125=3 and 1000÷125=8. Therefore 0.375=3/8.',
  'PERCENTAGE TO FRACTION. 62.5%=62.5/100=0.625=625/1000=5/8. Check: 5÷8=0.625=62.5%.',
  'RATIO PART-TO-PART. A class has 12 boys and 20 girls. Boys:girls=12:20=3:5 after dividing both terms by 4.',
  'RATIO PART-TO-WHOLE. The same class has total 32. Boys:total=12:32=3:8. Therefore boys are 3/8 of the class, which is 37.5%.',
  'RATIO WITH UNIT CONVERSION. Simplify 2.5m:50cm. Convert 2.5m=250cm. Ratio=250:50=5:1.',
  'SHARING IN A RATIO. Share ₦4,200 in 2:5. Total parts=7. One part=4200÷7=600. First share=2×600=₦1,200. Second share=5×600=₦3,000. Check: 1,200+3,000=4,200.',
  'THREE-PART RATIO. Share 72kg in the ratio 1:2:3. Total parts=6. One part=72÷6=12kg. Shares: 12kg,24kg,36kg. Check total=72kg.',
  'PERCENTAGE OF QUANTITY. Find 15% of ₦8,000. 15/100×8,000=0.15×8,000=₦1,200.',
  'PERCENTAGE INCREASE. Increase 360 by 20%. Increase=0.20×360=72. New value=360+72=432.',
  'PERCENTAGE DECREASE. Reduce ₦2,400 by 15%. Reduction=0.15×2,400=₦360. New value=₂,400−₦360=₦2,040.',
  'FIND THE ORIGINAL WHOLE. 25% of a quantity is 45. Let whole=x. 0.25x=45, so x=45÷0.25=180.',
  'MIXED CONTEXT. In a survey, 18 of 30 learners prefer football. Fraction=18/30=3/5. Decimal=0.6. Percentage=60%. Prefer football : do not prefer=18:12=3:2. Notice that part-to-whole ratio 18:30 differs from part-to-part ratio 18:12.'
 ],
 misconceptions:[
  'treating a fraction a/b as automatically the same as part-to-part ratio a:b without checking context',
  'adding or subtracting numerator and denominator when converting forms',
  'multiplying by 100 twice when converting a decimal to a percentage',
  'forgetting to simplify a fraction or ratio',
  'forming a ratio before converting quantities to the same unit',
  'simplifying only one term of a ratio',
  'using the number of ratio parts as though it were the original quantity',
  'confusing percentage increase with the final amount',
  'subtracting a percentage number directly from a money amount instead of finding the percentage of the base quantity',
  'using the new amount rather than the original amount as the base unless the problem explicitly requires it'
 ],
 guidedPractice:[
  'Convert 5/8 to decimal and percentage and verify by converting back.',
  'Convert 0.72 to a fraction in lowest terms and to a percentage.',
  'Convert 37.5% to a decimal and fraction.',
  'Simplify 18:30 and state the HCF used.',
  'Write 3m:75cm as a simplified ratio.',
  'A class has boys:girls=5:3 and 48 learners. Find boys, girls and the percentage who are girls.',
  'Share ₦9,600 in the ratio 3:5.',
  'Find 7.5% of ₦24,000.',
  'Increase 640 by 12.5%.',
  'Decrease ₦15,000 by 18%.',
  'If 40% of a number is 96, find the number.',
  'In a club, 21 of 35 members attended. Express attendance as fraction, decimal, percentage and attended:absent ratio.'
 ],
 independentPractice:[
  'Convert 11/20 to decimal and percentage.',
  'Convert 7/16 to decimal and percentage.',
  'Convert 0.35 to a fraction in lowest terms and a percentage.',
  'Convert 0.625 to a fraction and percentage.',
  'Convert 72% to a simplified fraction and decimal.',
  'Convert 12.5% to a fraction and decimal.',
  'Simplify 42:63.',
  'Simplify 2.4m:80cm.',
  'A bag contains 18 red and 27 blue counters. Find red:blue, red:total and red as a percentage of total.',
  'Share ₦18,000 in the ratio 2:3.',
  'Share 84kg in the ratio 2:3:7.',
  'Find 18% of ₦35,000.',
  'Increase 1,250 by 16%.',
  'Decrease 4,800 by 22.5%.',
  'A price rises from ₦5,000 by 12%. Find the increase and new price.',
  'After a 20% decrease, a quantity becomes 320. Find the original quantity.',
  '45 learners represent 75% of a class. Find the full class size.',
  'A school recorded attendance of 270 out of 300 learners. Express attendance as a simplified fraction, decimal and percentage.',
  'A recipe uses flour:sugar=5:2. If 750g flour is used, find the sugar required.',
  'Write one real-life situation where the ratios part-to-part and part-to-whole would give different answers and calculate both.'
 ],
 mastery:{criterion:'Learner converts accurately among fractions, ratios, decimals and percentages, distinguishes ratio contexts, solves ratio sharing and percentage change/whole problems, and reaches at least 80% with reverse checks and correct base quantities.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-basic-operations-derived-operations-1',classLevel:'JSS2',subject:'Mathematics',topic:'Transactions in the homes and offices',source:{authority:'NERDC',url:sourceUrl,page:20},
 objectives:['Solve household and office arithmetic problems','Solve simple commercial arithmetic involving profit, interest, discount and commission'],
 prerequisites:['percentages and decimals','addition/subtraction of money','multiplication/division','reading bills, tables and money notation'],
 teaching:[
  'START WITH THE FINANCIAL WORDS. Cost price (CP) is what an item costs the seller. Selling price (SP) is what the customer pays. Marked price (MP) is the price written before any discount. Profit occurs when SP>CP; loss occurs when SP<CP. Principal (P) is the original sum invested or borrowed. Rate (R) is the percentage per stated time, and time (T) must match that rate.',
  'HOUSEHOLD BUDGET. A budget plans how income will be used. Total expenditure is the sum of all planned expenses. Balance=income−expenditure. A positive balance is a surplus; a negative balance is a deficit and means spending exceeds income.',
  'READING BILLS AND RECORDS. Before calculating, identify the unit, quantity used, rate per unit, fixed charge, tax/levy if present, previous balance and total due. Do not multiply a rate by the wrong quantity or ignore fixed charges.',
  'PROFIT. Profit=SP−CP. Profit percentage is normally based on COST PRICE: profit%=profit/CP×100. State the formula before substituting so the denominator is not guessed.',
  'FINDING SELLING PRICE FROM PROFIT. If profit or profit% is given, first calculate the profit from CP, then SP=CP+profit. For a 20% profit on ₦8,000, profit=0.20×8,000=₦1,600; SP=₦9,600.',
  'LOSS. Loss=CP−SP. Loss%=loss/CP×100. Because the seller originally spent CP, the percentage loss is compared with that original cost unless a question states otherwise.',
  'FINDING SELLING PRICE FROM LOSS. If loss%=15% on CP ₦24,000, loss=0.15×24,000=₦3,600; SP=24,000−3,600=₦20,400.',
  'SIMPLE INTEREST — MEANING FIRST. Simple interest is calculated on the original principal only throughout the stated time. Interest does not become part of the principal for the next period.',
  'SIMPLE INTEREST FORMULA. I=PRT/100 when R is a percentage per annum and T is measured in years. Amount A=P+I. Every symbol must be identified before substitution.',
  'TIME CONVERSION IN INTEREST. If the rate is per annum but time is in months, convert months to years. Eighteen months=18/12=1.5 years. Do not use T=18 with an annual rate.',
  'FINDING AN UNKNOWN IN SIMPLE INTEREST. The same formula can be rearranged. If P, I and T are known, R=100I/(PT). If P, I and R are known, T=100I/(PR). Substitute with units and check that the result is sensible.',
  'DISCOUNT. Discount is the amount removed from the marked price. Discount=discount rate×MP. Selling price after discount=MP−discount. A discount must reduce the amount, never increase it.',
  'FINDING MARKED PRICE FROM A DISCOUNTED PRICE. If an item is sold at 80% of its marked price because of a 20% discount, SP=0.80MP. Therefore MP=SP/0.80.',
  'COMMISSION. Commission is payment calculated from a stated base such as sales. Commission=commission rate×sales. If an employee also receives a fixed salary, total earnings=fixed salary+commission.',
  'FINDING SALES FROM COMMISSION. If 5% commission equals ₦12,500, then 0.05×sales=12,500, so sales=₦250,000.',
  'COMBINED TRANSACTIONS. Real questions may combine discount and profit. Keep the stages separate: marked price→discounted selling price, then compare selling price with cost price to determine profit/loss.',
  'PERMANENT FINANCIAL CHECK. Write the base before every percentage. Profit/loss percentage uses CP by default; discount uses MP; commission uses stated sales/base; interest uses P. Then ask whether the final amount moved in the expected direction.'
 ],
 workedExamples:[
  'BUDGET — SURPLUS. Monthly income=₦180,000. Expenses: rent ₦45,000, food ₦62,500, transport ₦18,000, utilities ₦12,500, school needs ₦22,000. Total expenditure=45,000+62,500+18,000+12,500+22,000=₦160,000. Balance=180,000−160,000=₦20,000 surplus.',
  'BUDGET — DEFICIT. Income=₦95,000; planned expenses total ₦103,500. Balance=95,000−103,500=−₦8,500. The negative sign means the plan exceeds income by ₦8,500.',
  'PROFIT AND PROFIT %. CP=₦8,000, SP=₦9,600. Profit=9,600−8,000=₦1,600. Profit%=1,600/8,000×100=20%. Check: 20% of 8,000=1,600.',
  'FIND SP FROM PROFIT %. CP=₦12,500, profit=16%. Profit=0.16×12,500=₦2,000. SP=12,500+2,000=₦14,500.',
  'LOSS AND LOSS %. CP=₦10,000, SP=₦8,500. Loss=10,000−8,500=₦1,500. Loss%=1,500/10,000×100=15%.',
  'FIND SP FROM LOSS %. CP=₦24,000, loss=15%. Loss=0.15×24,000=₦3,600. SP=24,000−3,600=₦20,400.',
  'SIMPLE INTEREST — YEARS. P=₦50,000,R=8% p.a.,T=2 years. I=50,000×8×2/100=₦8,000. Amount=50,000+8,000=₦58,000.',
  'SIMPLE INTEREST — MONTHS. P=₦120,000,R=7.5% p.a.,T=18 months=1.5 years. I=120,000×7.5×1.5/100=₦13,500. Amount=₦133,500.',
  'FIND THE RATE. P=₦80,000,I=₦12,000,T=2 years. R=100I/(PT)=100×12,000/(80,000×2)=7.5% p.a.',
  'DISCOUNT. MP=₦25,000, discount=12%. Discount amount=0.12×25,000=₦3,000. SP=25,000−3,000=₦22,000.',
  'FIND DISCOUNT RATE. MP=₦30,000 and discount amount=₦3,600. Rate=3,600/30,000×100=12%.',
  'FIND MARKED PRICE. An item sells for ₦16,000 after 20% discount. Customer pays 80% of MP, so 0.80MP=16,000. MP=16,000/0.80=₦20,000.',
  'COMMISSION. Sales=₦240,000, rate=10%. Commission=0.10×240,000=₦24,000.',
  'SALARY PLUS COMMISSION. Fixed salary=₦55,000, commission=4% of ₦300,000 sales. Commission=₦12,000. Total earnings=55,000+12,000=₦67,000.',
  'FIND SALES FROM COMMISSION. Commission=₦12,500 at 5%. Sales=12,500/0.05=₦250,000.',
  'BILL WITH FIXED CHARGE. Electricity usage=185 units at ₦72 per unit plus fixed charge ₦1,500. Usage charge=185×72=₦13,320. Total=13,320+1,500=₦14,820.',
  'COMBINED DISCOUNT AND PROFIT. MP=₦15,000, discount=10%, CP=₦11,000. Discount=₦1,500; SP=₦13,500. Profit=13,500−11,000=₦2,500. Profit%=2,500/11,000×100≈22.7%. The discount base was MP, but the profit percentage base was CP.',
  'REALISTIC OFFICE PURCHASE. An office buys 8 printer cartridges at ₦7,500 each and pays delivery of ₦4,000. Item cost=8×7,500=₦60,000. Total cost=60,000+4,000=₦64,000. The delivery charge must not be omitted when the question asks total expenditure.'
 ],
 misconceptions:[
  'confusing cost price, selling price and marked price',
  'calculating profit percentage using selling price by default',
  'using marked price as the base for profit percentage',
  'adding a loss to cost price instead of subtracting it',
  'adding discount to marked price instead of subtracting it',
  'calculating discount from selling price when the rate is stated on marked price',
  'using months directly as years in simple-interest formula',
  'using compound-interest reasoning in a simple-interest question',
  'forgetting amount=P+I after calculating interest',
  'calculating commission on the wrong base amount',
  'ignoring fixed charges, previous balance or units in bills',
  'treating a negative budget balance as money left over',
  'mixing the bases in a combined discount-and-profit question'
 ],
 guidedPractice:[
  'Prepare a budget from ₦150,000 income and expenses of ₦40,000, ₦52,500, ₦18,000, ₦12,500 and ₦15,000. State surplus/deficit.',
  'An item costs ₦6,500 and sells for ₦7,800. Find profit and profit percentage.',
  'An article costing ₦18,000 is sold at a 12% loss. Find the loss and selling price.',
  'Find simple interest and amount on ₦75,000 at 6% p.a. for 3 years.',
  'Find simple interest on ₦96,000 at 10% p.a. for 9 months.',
  'An investment of ₦50,000 earns ₦7,500 simple interest in 3 years. Find the annual rate.',
  'Find the selling price after 15% discount on ₦32,000 marked price.',
  'An item sells for ₦27,000 after a 10% discount. Find its marked price.',
  'Find 4.5% commission on sales of ₦480,000.',
  'An agent earns ₦18,000 commission at 6%. Find the sales value.',
  'A bill charges 240 units at ₦65 each plus ₦1,800 fixed charge. Find total due.',
  'An item marked ₦20,000 gets 10% discount. Its cost price is ₦15,000. Find the actual selling price, profit and profit percentage.'
 ],
 independentPractice:[
  'A family earns ₦220,000 monthly and plans expenses totalling ₦197,500. Find the balance and interpret it.',
  'A household earns ₦125,000 but plans ₦132,800 expenditure. Find and interpret the balance.',
  'CP=₦14,400 and SP=₦17,280. Find profit and profit percentage.',
  'CP=₦25,000 and SP=₦21,250. Find loss and loss percentage.',
  'Find the SP of an item costing ₦48,000 if a 25% profit is required.',
  'Find the SP of an item costing ₦36,000 if sold at 12.5% loss.',
  'Find simple interest and amount on ₦90,000 at 7% p.a. for 4 years.',
  'Find simple interest on ₦160,000 at 9% p.a. for 15 months.',
  'A principal of ₦120,000 earns ₦27,000 in 2.5 years simple interest. Find the rate.',
  'At 8% p.a., how long will ₦50,000 take to earn ₦12,000 simple interest?',
  'Find the discount and selling price when MP=₦45,000 and discount rate=18%.',
  'An item sells for ₦34,000 after 15% discount. Find MP.',
  'A salesperson earns 7% commission on ₦650,000 sales. Find commission.',
  'A salesperson receives ₦60,000 basic salary plus 3.5% of ₦800,000 sales. Find total earnings.',
  'Commission is ₦24,000 at 4%. Find sales.',
  'A water bill charges 32m³ at ₦480 per m³ plus service fee ₦2,250. Find total bill.',
  'An invoice contains 12 notebooks at ₦1,250 each, 5 files at ₦800 each and delivery ₦2,000. Find total invoice amount.',
  'An item marked ₦50,000 is discounted by 20%. If CP=₦32,000, find SP, profit and profit percentage.',
  'A trader buys an item for ₦25,000, marks it 40% above cost, then gives a 10% discount on marked price. Find MP, final SP and actual profit percentage.',
  'Explain why a 20% discount and a 20% profit cannot automatically be cancelled when they are calculated on different base amounts.'
 ],
 mastery:{criterion:'At least 80% across household budgets, bills, profit/loss, simple interest, discount and commission, with every percentage base identified explicitly and final money answers interpreted correctly.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-basic-operations-derived-operations-2',classLevel:'JSS2',subject:'Mathematics',topic:'Approximation',source:{authority:'NERDC',url:sourceUrl,page:20},
 objectives:['Approximate numbers to a stated degree of accuracy','Solve quantitative-reasoning problems involving approximation'],
 prerequisites:['place value','decimal notation','whole-number rounding','multiplication and division'],
 teaching:[
  'APPROXIMATION replaces a number with a nearby value that is easier to use while keeping the size sensible. The answer must state the required accuracy, because 47.386 can reasonably become 47, 47.4 or 47.39 depending on the instruction.',
  'ROUNDING TO A PLACE VALUE. Identify the digit in the required place, then look only at the digit immediately to its right. If that next digit is 0–4, keep the target digit; if it is 5–9, increase the target digit by 1. All following digits are then removed or replaced by zeros where place value requires.',
  'DECIMAL PLACES count digits to the right of the decimal point. For 6.7845 to 2 d.p., keep 7 and 8, inspect the next digit 4, and obtain 6.78. For 6.786 to 2 d.p., the next digit is 6, so 6.79.',
  'SIGNIFICANT FIGURES begin at the first non-zero digit. Leading zeros only locate the decimal point and are not significant. Thus 0.004786 to 2 s.f. keeps 4 and 7; the next digit 8 rounds 7 upward, giving 0.0048.',
  'ZEROS CAN BE SIGNIFICANT OR PLACEHOLDERS. In 5.040, the zero between 5 and 4 is significant, and a final zero written to show measured precision can also be significant. In 0.00504, the zeros before 5 are not significant.',
  'ROUNDING WHOLE NUMBERS. 48,763 to the nearest hundred: the hundreds digit is 7 and the tens digit is 6, so round up to 48,800. To the nearest thousand, inspect the hundreds digit 7 and obtain 49,000.',
  'ROUNDING DECIMALS TO A NAMED UNIT. Nearest tenth means one decimal place; nearest hundredth means two decimal places. Do not confuse a named place with significant figures.',
  'ESTIMATION OF SUMS AND DIFFERENCES. Round numbers to convenient but sensible values before calculating. The goal is not exact equality but a quick expected size. Example 398+602≈400+600=1,000.',
  'ESTIMATION OF PRODUCTS. Round factors to convenient nearby numbers: 49×21≈50×20=1,000. This gives a benchmark for the exact result 1,029.',
  'ESTIMATION OF QUOTIENTS. Choose compatible rounded values: 1,986÷51≈2,000÷50=40. An exact answer near 39 is therefore plausible.',
  'APPROXIMATION AS A CALCULATOR CHECK. Estimate before entering the exact expression. If 19.8×5.03 is estimated as 20×5≈100, a calculator result 99.594 is sensible; 995.94 should be rejected and re-entered.',
  'ROUNDING IN MULTI-STEP PROBLEMS. Unless told otherwise, keep enough accuracy during intermediate steps and round at the end. Rounding every step can accumulate error.',
  'BOUNDS IDEA. A rounded value represents a range. If a length is 8.4 cm correct to the nearest 0.1 cm, the actual value is at least 8.35 cm but less than 8.45 cm. This explains why rounded values are approximate, not exact.',
  'QUANTITATIVE REASONING. In money, measurement, population and geometry contexts, decide whether the problem wants an exact answer or a sensible estimate. Always attach the correct unit.',
  'PERMANENT CHECK. State the requested accuracy, preserve place value, estimate the expected magnitude, and ask whether the rounded answer is consistent with the original number.'
 ],
 workedExamples:[
  'NEAREST TEN. Round 4,367 to the nearest 10. Tens digit=6; next digit=7, so round up: 4,370.',
  'NEAREST HUNDRED. Round 58,649 to the nearest 100. Hundreds digit=6; tens digit=4, so keep 6: 58,600.',
  'NEAREST THOUSAND. Round 2,549,800 to the nearest 1,000. Thousands digit=9; hundreds digit=8, so 9 rounds up and carries: 2,550,000.',
  'ONE DECIMAL PLACE. 6.784 to 1 d.p. Keep 7; next digit 8 means round up: 6.8.',
  'TWO DECIMAL PLACES. 47.386 to 2 d.p. Keep 3 and 8; next digit 6 rounds 8 to 9: 47.39.',
  'ROUNDING WITH CARRY. 9.996 to 2 d.p. Keep 9.99; next digit 6 rounds the hundredths upward, producing 10.00.',
  'TWO SIGNIFICANT FIGURES. 0.004786: first significant digit 4, second 7, next digit 8, so answer=0.0048.',
  'THREE SIGNIFICANT FIGURES. 48,650 to 3 s.f. Keep 4,8,6; next digit 5 means round 6 up: 48,700.',
  'SIGNIFICANT ZERO. 0.05046 to 3 s.f. Significant digits are 5,0,4; next digit 6 rounds 4 up: 0.0505.',
  'ESTIMATE A SUM. 398+602≈400+600=1,000. Exact sum=1,000, confirming the estimate perfectly.',
  'ESTIMATE A PRODUCT. 49.8×20.2≈50×20=1,000. The exact result should be close to 1,000.',
  'ESTIMATE A QUOTIENT. 598÷29.7≈600÷30=20. An exact result around 20 is reasonable.',
  'MIXED EXPRESSION. 19.6+80.3−9.8≈20+80−10=90. Exact value 90.1 agrees closely.',
  'MONEY CONTEXT. Three items cost ₦4,980, ₦2,075 and ₦3,040. Estimate total to nearest thousand: ₦5,000+₦2,000+₦3,000≈₦10,000. Exact total ₦10,095 is reasonable.',
  'MEASUREMENT CONTEXT. A rectangle measures 19.8 cm by 5.1 cm. Estimated area≈20×5=100 cm². Exact area=100.98 cm², very close.',
  'ROUND AT THE END. 13.47×2.86=38.5242. To 3 s.f., answer=38.5. Rounding 13.47→13 and 2.86→3 first would give 39 and lose unnecessary accuracy.'
 ],
 misconceptions:[
  'confusing decimal places with significant figures',
  'counting leading zeros as significant',
  'looking at several following digits instead of the single next digit for the rounding decision',
  'dropping placeholder zeros so the place value changes',
  'rounding 9.996 to 9.99 instead of allowing a carry to 10.00',
  'rounding every intermediate step in a multi-step problem',
  'using an estimate as though it were the exact answer',
  'estimating with values that are not convenient or not close enough to be useful',
  'accepting a calculator answer without an order-of-magnitude check',
  'forgetting the requested unit or degree of accuracy'
 ],
 guidedPractice:[
  'Round 7,846 to nearest 10, nearest 100 and nearest 1,000.',
  'Round 6.7845 to 3 d.p.',
  'Round 0.009746 to 2 s.f.',
  'Round 528,941 to 3 s.f.',
  'Round 12.995 to 2 d.p. and explain the carrying.',
  'State the significant figures in 0.05040.',
  'Estimate 39.7×2.98 using convenient numbers.',
  'Estimate 2,040÷49.',
  'Estimate 198+403−51.',
  'A calculator gives 7,920 for 79.2×9.8. Estimate first and decide whether it is plausible.',
  'Find the exact total of ₦4,975, ₦8,120 and ₦2,890, then compare it with an estimate.',
  'Explain why rounding only at the final stage is usually safer in a multi-step calculation.'
 ],
 independentPractice:[
  'Round 84,376 to nearest 10.',
  'Round 84,376 to nearest 100.',
  'Round 84,376 to nearest 1,000.',
  'Round 3.7468 to 1 d.p.',
  'Round 3.7468 to 2 d.p.',
  'Round 0.006784 to 2 s.f.',
  'Round 0.006784 to 3 s.f.',
  'Round 96,549 to 3 s.f.',
  'Round 999.6 to nearest whole number.',
  'Round 9.9994 to 3 d.p.',
  'Estimate 501+298+197.',
  'Estimate 81×39.',
  'Estimate 1,503÷29.',
  'Estimate 49.8×9.97.',
  'Estimate 602−198+95.',
  'A bill has amounts ₦18,750, ₦7,980 and ₦12,230. Estimate the total to nearest thousand, then find the exact total.',
  'A field is 48.7m by 19.8m. Estimate its area before calculating exactly.',
  'A bus travels 298km using 31 litres of fuel. Estimate km per litre.',
  'A calculator shows 0.048 for 480÷10. Decide whether the answer is reasonable and explain.',
  'Explain the difference between 2 d.p. and 2 s.f. using the number 0.04726.'
 ],
 mastery:{criterion:'Learner distinguishes place-value rounding, decimal places and significant figures, estimates all four operations sensibly, checks calculator outputs and achieves at least 85% with the requested accuracy stated correctly.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-basic-operations-derived-operations-3',classLevel:'JSS2',subject:'Mathematics',topic:'Multiplication and division of directed numbers',source:{authority:'NERDC',url:sourceUrl,page:20},
 objectives:['Obtain squares and square roots from supplied square/square-root tables','Interpret information from tables, charts, records and schedules','Multiply directed numbers','Divide directed numbers'],
 prerequisites:['JSS1 addition/subtraction of directed numbers','multiplication tables','meaning of positive and negative values'],
 teaching:[
  'DIRECTED NUMBERS combine magnitude with direction relative to zero. A positive sign can represent gain, rise, forward or above; a negative sign can represent loss, fall, backward or below, depending on context.',
  'MULTIPLICATION — SAME SIGNS. Positive×positive is positive. Negative×negative is also positive. The second result can be understood through arithmetic patterns: as 3×(−2)=−6,2×(−2)=−4,1×(−2)=−2,0×(−2)=0, the next consistent result is (−1)×(−2)=+2.',
  'MULTIPLICATION — DIFFERENT SIGNS. Exactly one negative factor gives a negative product. Determine the sign first, then multiply the magnitudes. Example (−7)×4 has different signs, so negative; 7×4=28, hence −28.',
  'SEVERAL FACTORS. Count negative factors. An even number of negative factors produces a positive result; an odd number produces a negative result. Then multiply absolute values.',
  'DIVISION REVERSES MULTIPLICATION. If (−4)×3=−12, then −12÷3=−4 and −12÷(−4)=3. This gives the same sign rules for division.',
  'DO NOT MIX SIGN RULES WITH ADDITION RULES. For addition, signs interact through magnitude and direction; for multiplication/division, the sign depends on whether the two signs are the same or different.',
  'CONTEXT — TEMPERATURE. A repeated drop of 3°C each hour for 4 hours is 4×(−3)=−12°C total change.',
  'CONTEXT — FINANCE. A repeated loss of ₦2,500 over 3 identical transactions is 3×(−2,500)=−₦7,500.',
  'CONTEXT — VERTICAL MOVEMENT. Descending 6m per minute for 5 minutes gives 5×(−6)=−30m relative change.',
  'SQUARES OF DIRECTED NUMBERS. Squaring means multiplying a number by itself. (−5)²=(−5)(−5)=25. But −5² without brackets is interpreted as −(5²)=−25 because the exponent applies to 5 only.',
  'SQUARE-ROOT TABLES. Read the table title, row/column headings and stated precision before extracting a value. A square-root value must be positive at this level unless the question explicitly asks for solutions of an equation such as x²=25.',
  'REASONABLENESS CHECK FOR ROOTS. If 49<50<64, then 7<√50<8. A table value outside this range is impossible.',
  'READING CHARTS, TABLES AND SCHEDULES. Identify headings, units and categories before combining values. The arithmetic may be easy, but the real skill is extracting the correct data.',
  'PERMANENT CHECK. Decide sign separately from magnitude, verify division by multiplication, and test any table value against a rough estimate or surrounding known values.'
 ],
 workedExamples:[
  'SAME POSITIVE SIGNS. 6×4=24.',
  'TWO NEGATIVES. (−5)(−3)=+15 because the signs are the same and 5×3=15.',
  'DIFFERENT SIGNS. (−7)×4=−28.',
  'DIFFERENT SIGNS REVERSED. 9×(−6)=−54.',
  'THREE FACTORS — TWO NEGATIVES. (−2)(−3)(4): two negatives give positive; 2×3×4=24.',
  'THREE FACTORS — TWO NEGATIVES. (−5)(2)(−3): two negatives give positive; 5×2×3=30.',
  'THREE FACTORS — THREE NEGATIVES. (−2)(−3)(−4): three negatives give negative; magnitude 24, answer −24.',
  'DIVISION DIFFERENT SIGNS. −63÷9=−7.',
  'DIVISION SAME NEGATIVE SIGNS. −48÷−6=+8.',
  'CHAINED DIVISION. −72÷(−3)÷2 =24÷2=12.',
  'TEMPERATURE CONTEXT. Temperature changes −3°C each hour for 4 hours. Total change=4×(−3)=−12°C.',
  'FINANCE CONTEXT. Three equal losses of ₦2,500 give 3×(−2,500)=−₦7,500.',
  'SQUARE OF A NEGATIVE. (−6)²=(−6)(−6)=36.',
  'BRACKETS MATTER. −6²=−(6²)=−36, but (−6)²=36.',
  'SQUARE-ROOT TABLE CHECK. If a table gives √2.25=1.50, verify 1.50²=2.25.',
  'NON-PERFECT ROOT CHECK. Since 49<50<64, √50 must lie between 7 and 8. A table value 7.07 is plausible.',
  'TABLE INTERPRETATION. A schedule lists buses at 8:15,8:45,9:15. The interval is 30 minutes. Do not calculate before identifying that the entries are times, not ordinary decimals.',
  'CHART INTERPRETATION. If a bar chart shows 18 boys and 24 girls, total=42 and difference=6; units are learners, not percentages unless the axis says so.'
 ],
 misconceptions:[
  'making every product negative when any negative number appears',
  'using addition sign rules for multiplication',
  'forgetting that two negative factors give a positive product',
  'losing a negative sign during division',
  'counting negative factors incorrectly in a long product',
  'treating −5² and (−5)² as identical',
  'reading a numerical table without checking headings or precision',
  'accepting an impossible square-root value without bracketing',
  'ignoring units in charts and schedules',
  'treating time entries or categories as ordinary numbers without context'
 ],
 guidedPractice:[
  'Evaluate (−9)(4) and explain the sign.',
  'Evaluate (−6)(−7) and explain the sign.',
  'Evaluate (−2)(5)(−3).',
  'Evaluate (−2)(−3)(−4).',
  'Evaluate 72÷(−8).',
  'Evaluate −81÷(−9).',
  'Explain why (−7)² is positive.',
  'Compare −7² and (−7)².',
  'Use a supplied square-root table to estimate √70 and verify by squaring approximately.',
  'A lift descends 4 floors per movement for 3 movements. Represent the total change with directed numbers.',
  'A chart shows values 12,18,25 and15 units. Find total and range after confirming the axis unit.',
  'A timetable shows departures every 25 minutes starting at 9:10. Write the next four departure times.'
 ],
 independentPractice:[
  'Evaluate (−8)(5).','Evaluate (−9)(−4).','Evaluate 7(−12).','Evaluate (−3)(−5)(2).','Evaluate (−2)(−3)(−4)(−1).',
  'Evaluate −84÷7.','Evaluate −96÷−12.','Evaluate 144÷−16.','Evaluate −120÷(−5)÷3.',
  'Evaluate (−11)².','Evaluate −11² and explain the difference from the previous question.',
  'A temperature falls 4°C per hour for 6 hours. Find total change.',
  'A diver descends 7m per minute for 5 minutes. Find the signed change.',
  'Four identical transactions each produce a loss of ₦1,250. Represent total change.',
  'Use a square-root table or calculator to obtain √38 to the stated table precision, then bracket it between consecutive integers.',
  'A table gives √90≈9.487. Check whether this is reasonable using 9² and 10².',
  'Interpret a small class timetable and calculate the interval between three specified periods.',
  'Interpret a supplied chart, state its unit, find total, largest value and difference between two categories.'
 ],
 mastery:{criterion:'Learner multiplies/divides directed numbers with at least 85% accuracy, explains sign rules from patterns/inverse operations, distinguishes bracketed squares, and reads tables/charts with units and reasonableness checks.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-algebraic-processes-algebraic-operations-1',classLevel:'JSS2',subject:'Mathematics',topic:'Algebraic expressions',source:{authority:'NERDC',url:sourceUrl,page:21},
 objectives:['Expand algebraic expressions','Factorize simple algebraic expressions','Expand and factorize quadratic expressions','Solve quantitative-reasoning problems','Simplify algebraic fractions'],
 prerequisites:['JSS1 variables, coefficients and like terms','distributive law','integer sign rules','basic fractions'],
 teaching:[
  'AN ALGEBRAIC EXPRESSION combines numbers, variables and operations without an equals sign. A term is a part separated by + or −; a coefficient is the numerical factor multiplying a variable.',
  'LIKE TERMS have exactly the same variable part with the same powers. 3x and 5x are like; 3x and 3x² are not. Only like terms can be collected by adding or subtracting coefficients.',
  'EXPANSION uses the distributive law. In 3(x+4), the 3 multiplies both x and 4, giving 3x+12. The outside factor must reach every term.',
  'NEGATIVE FACTORS. In −2(3y−5), multiply −2 by both terms: −6y+10. A negative times a negative is positive.',
  'EXPAND THEN COLLECT. For 2(x+3)+3x, first get 2x+6+3x, then combine 2x and3x to obtain 5x+6.',
  'FACTORISATION reverses expansion. Search first for the greatest common factor shared by every term. 6x+9=3(2x+3). Verify by expanding.',
  'VARIABLE COMMON FACTORS. 12a²−8a has common factor 4a, so 12a²−8a=4a(3a−2). Take the highest variable power common to all terms.',
  'QUADRATIC EXPRESSIONS. A quadratic contains a highest variable power of 2. For x²+5x+6, seek two numbers whose product is +6 and sum is +5: 2 and3, so (x+2)(x+3).',
  'SIGNS IN QUADRATIC FACTORISATION. If c is positive and b is negative, both factors are often negative; if c is negative, the two factor signs differ. Always check by expansion.',
  'QUADRATIC WITH LEADING COEFFICIENT NOT 1. At this level, use splitting/grouping where appropriate: for 2x²+7x+3, product ac=6; numbers 6 and1 sum to7. Split 7x into6x+x and group.',
  'ALGEBRAIC FRACTIONS behave like numerical fractions. You may cancel common FACTORS, not terms across addition. 6x/9 simplifies to 2x/3 by dividing numerator and denominator by3.',
  'LIKE DENOMINATORS. x/5+2x/5=3x/5 because the denominator stays 5 and numerators combine.',
  'UNLIKE DENOMINATORS. x/2+x/3 requires LCM 6: 3x/6+2x/6=5x/6.',
  'RESTRICTIONS. A denominator cannot be zero. If a denominator contains a variable, exclude any value that would make it zero.',
  'PERMANENT CHECK. Expansion should be checked by multiplying back; factorisation should reproduce the original expression when expanded; algebraic fractions should be simplified by factors only.'
 ],
 workedExamples:[
  'COLLECT LIKE TERMS. 3x+5x−2=8x−2.',
  'TWO VARIABLES. 5x+2y−3x+y =2x+3y.',
  'SINGLE BRACKET. 3(x+4)=3x+12.',
  'NEGATIVE BRACKET. −2(3y−5)=−6y+10.',
  'EXPAND AND COLLECT. 2(x+3)+3x=2x+6+3x=5x+6.',
  'TWO BRACKETS. 4(2y−1)−3(y+2)=8y−4−3y−6=5y−10.',
  'COMMON FACTOR. 6x+9=3(2x+3). Check: 3×2x+3×3=6x+9.',
  'VARIABLE COMMON FACTOR. 12a²−8a=4a(3a−2).',
  'TWO-VARIABLE COMMON FACTOR. 15xy+20x=5x(3y+4).',
  'QUADRATIC a=1. x²+5x+6: product6,sum5→2 and3. Therefore (x+2)(x+3).',
  'QUADRATIC WITH NEGATIVE MIDDLE. x²−7x+12: product12,sum−7→−3 and−4. Therefore (x−3)(x−4).',
  'QUADRATIC MIXED SIGNS. x²+x−6: product−6,sum1→3 and−2. Therefore (x+3)(x−2).',
  'QUADRATIC a≠1. 2x²+7x+3. ac=6; split middle:2x²+6x+x+3=2x(x+3)+1(x+3)=(2x+1)(x+3).',
  'ALGEBRAIC FRACTION SIMPLIFY. 6x/9=2x/3.',
  'LIKE DENOMINATORS. x/5+2x/5=3x/5.',
  'UNLIKE DENOMINATORS. x/2+x/3=3x/6+2x/6=5x/6.',
  'FRACTION WITH TERMS. (x+1)/4+(x−1)/4=(2x)/4=x/2.',
  'VERIFY FACTORISATION. (x+2)(x+3)=x²+3x+2x+6=x²+5x+6, so the factorisation is correct.'
 ],
 misconceptions:[
  'combining unlike terms such as x and x²',
  'multiplying an outside factor by only the first term in a bracket',
  'losing a sign when a negative factor is distributed',
  'factoring out a number that is not common to every term',
  'forgetting a common variable factor',
  'guessing quadratic factors without checking product and sum',
  'not verifying factorisation by expansion',
  'cancelling terms across addition in an algebraic fraction',
  'adding denominators when adding algebraic fractions',
  'ignoring denominator restrictions'
 ],
 guidedPractice:[
  'Simplify 7x+3x−4.','Simplify 4a+3b−2a+b.','Expand 5(x−3).','Expand −3(2y+4).',
  'Simplify 3(x+2)+2x.','Factorize 8x+12.','Factorize 15a²−20a.',
  'Factorize x²+7x+12.','Factorize x²−5x+6.','Factorize 2x²+7x+3.',
  'Simplify 12a/18b.','Simplify x/4+x/6.'
 ],
 independentPractice:[
  'Simplify 9x−4x+7.','Simplify 6a+2b−3a+5b.','Expand 4(x+7).','Expand −5(2m−3).',
  'Simplify 2(3x−1)+4x.','Simplify 3(a+4)−2(a−1).','Factorize 10x+15.','Factorize 18xy+24x².',
  'Factorize x²+9x+20.','Factorize x²−9x+20.','Factorize x²−x−12.','Factorize 3x²+10x+8.',
  'Simplify 8xy/12x.','Simplify 3a/7−a/7.','Simplify 2x/5+3x/10.',
  'Explain why (x+2)/(x+2) can simplify to1 only when x≠−2.',
  'Expand your factorised answer for x²−x−12 to verify it.',
  'Create one quadratic expression from a pair of binomial factors and expand it.'
 ],
 mastery:{criterion:'Learner expands and factorizes linear/quadratic expressions, simplifies algebraic fractions and verifies results by reverse operations with at least 85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-algebraic-processes-algebraic-operations-2',classLevel:'JSS2',subject:'Mathematics',topic:'Simple equations',source:{authority:'NERDC',url:sourceUrl,page:21},
 objectives:['Solve simple linear equations','Form and solve equations from practical problems','Check solutions by substitution'],
 prerequisites:['inverse operations','algebraic expressions','integer arithmetic','fractions'],
 teaching:[
  'AN EQUATION says two expressions have equal value. The equals sign is a balance, not a signal to “write the answer”. Solving means finding the value that makes the equality true.',
  'BALANCE PRINCIPLE. Any operation performed on one side must also be performed on the other side. This preserves equality.',
  'ONE-STEP ADDITION. x+7=15. Subtract7 from both sides: x=8. We subtract because addition by7 is undone by subtraction7.',
  'ONE-STEP SUBTRACTION. x−9=4. Add9 to both sides: x=13.',
  'ONE-STEP MULTIPLICATION. 5x=35. Divide both sides by5: x=7.',
  'ONE-STEP DIVISION. x/4=6. Multiply both sides by4: x=24.',
  'TWO-STEP EQUATIONS. Undo operations in reverse structural order. In 3x+5=17, first subtract5 to get 3x=12, then divide by3 to get x=4.',
  'BRACKETS. In 2(x+3)=14, either divide both sides by2 first to get x+3=7, or expand to 2x+6=14. Both are valid when done correctly.',
  'UNKNOWN ON BOTH SIDES. In 5x+2=3x+14, subtract3x from both sides to collect variables:2x+2=14, then subtract2 and divide by2.',
  'FRACTION EQUATIONS. Clear a numerical denominator by multiplying both sides by the denominator or by the LCM when several fractions occur.',
  'NEGATIVE COEFFICIENTS. In 7−2x=1, subtract7 from both sides to get −2x=−6, then divide by−2 to get x=3.',
  'FORMING EQUATIONS FROM WORDS. Define the unknown first. “Three times a number minus4 is20” becomes 3x−4=20.',
  'PERIMETER AND NUMBER PROBLEMS. Translate relationships carefully before solving. If a rectangle has length x+3, width x and perimeter26, then 2(x+3)+2x=26.',
  'CHECK BY SUBSTITUTION. A solution is not complete until it satisfies the original equation. Substitute the value into both sides and compare.',
  'TRANSPOSITION IS A SHORTCUT, NOT MAGIC. What looks like “moving +5 across as −5” is shorthand for subtracting5 from both sides. AVORA should teach the balance meaning before the shortcut.',
  'PERMANENT CHECK. Keep an equals sign on every line, perform one justified operation at a time, and verify in the original equation.'
 ],
 workedExamples:[
  'ONE STEP. x+7=15. Subtract7 both sides: x=8. Check:8+7=15.',
  'ONE STEP. x−9=4. Add9 both sides: x=13. Check:13−9=4.',
  'MULTIPLICATION. 5x=35. Divide both sides by5: x=7.',
  'DIVISION. x/3=8. Multiply both sides by3: x=24.',
  'TWO STEP. 3x+5=17. 3x=12, so x=4. Check:3(4)+5=17.',
  'TWO STEP WITH SUBTRACTION. 4x−7=21. 4x=28, so x=7.',
  'BRACKET — DIVIDE FIRST. 2(x+3)=14. Divide by2: x+3=7. Subtract3: x=4.',
  'BRACKET — EXPAND. 3(2x−1)=15. 6x−3=15; 6x=18; x=3.',
  'NEGATIVE BRACKET. 5−2(x−4)=11. Expand:5−2x+8=11→13−2x=11→−2x=−2→x=1.',
  'UNKNOWN BOTH SIDES. 5x+2=3x+14. 2x+2=14→2x=12→x=6.',
  'UNKNOWN BOTH SIDES WITH NEGATIVE. 7−2x=x+1. Subtract1:6−2x=x. Add2x:6=3x, so x=2.',
  'FRACTION. x/3+2=8. Subtract2: x/3=6. Multiply by3: x=18.',
  'FRACTION TWO TERMS. x/2+x/3=10. Multiply every term by LCM6:3x+2x=60→5x=60→x=12.',
  'WORD PROBLEM. “A number plus8 is21.” Let x be the number. x+8=21→x=13.',
  'WORD PROBLEM. “Three times a number minus4 is20.” 3x−4=20→3x=24→x=8.',
  'PERIMETER. Rectangle length=x+3,width=x, perimeter26. 2(x+3)+2x=26→2x+6+2x=26→4x=20→x=5. Dimensions:8 and5.',
  'CHECKING. For 4x−7=21 with x=7: left=28−7=21, right=21. Equal, so solution is correct.'
 ],
 misconceptions:[
  'treating the equals sign as “the answer comes next”',
  'performing an operation on only one side',
  'changing a sign without understanding the inverse operation',
  'undoing two-step equations in the wrong order',
  'expanding a bracket incorrectly',
  'collecting unlike terms across an equals sign',
  'forgetting to multiply every term when clearing fractions',
  'losing a negative sign when dividing by a negative coefficient',
  'forming an equation before defining the unknown',
  'failing to substitute into the original equation to check'
 ],
 guidedPractice:[
  'Solve x+12=30.','Solve x−7=15.','Solve 6x=54.','Solve x/5=9.',
  'Solve 4x+3=27.','Solve 7x−5=30.','Solve 2(x+4)=18.','Solve 3(2x−1)=21.',
  'Solve 5x+4=3x+18.','Solve 9−2x=x.','Solve x/4+3=8.','Solve x/2+x/6=16.',
  'Form and solve: twice a number plus5 is19.','A rectangle has width x and length x+4; perimeter is32. Find x and the dimensions.'
 ],
 independentPractice:[
  'Solve x+18=45.','Solve x−14=9.','Solve 8x=72.','Solve x/7=6.',
  'Solve 3x+8=29.','Solve 5x−11=24.','Solve 4(x+2)=28.','Solve 2(3x−5)=14.',
  'Solve 6x+1=4x+15.','Solve 10−3x=x−2.','Solve x/3+5=11.','Solve x/2+x/4=18.',
  'Solve (x+3)/5=4.','Solve (2x−1)/3=5.',
  'Form and solve: a number decreased by9 gives17.',
  'Form and solve: four times a number plus3 equals35.',
  'The sum of two consecutive integers is41. Form an equation and find them.',
  'A rectangle has length x+5 and width x−1; perimeter36. Find x and dimensions.',
  'A learner buys 3 identical notebooks and a ₦500 pen for ₦2,600. Form an equation and find the notebook price.',
  'Verify two of your answers by substitution and explain the balance operation used.'
 ],
 mastery:{criterion:'Learner solves one-step, two-step, bracket, both-side and simple fractional equations, forms equations from contexts, and verifies solutions with at least 85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-algebraic-processes-algebraic-operations-3',classLevel:'JSS2',subject:'Mathematics',topic:'Linear inequalities',source:{authority:'NERDC',url:sourceUrl,page:22},
 objectives:['Identify a linear inequality in one variable','Solve linear inequalities in one variable','Represent solution sets on a number line','Solve word problems involving linear inequalities'],
 prerequisites:['simple equations','directed numbers','number-line representation'],
 teaching:[
  'AN INEQUALITY compares quantities that may have many possible values rather than one exact equality. The symbols <,>,≤,≥ mean less than, greater than, less than or equal to, and greater than or equal to.',
  'A SOLUTION SET is a whole range. If x<4, every value below4 works. Therefore an inequality answer should not normally be written as one isolated number.',
  'THE BALANCE IDEA STILL APPLIES. Adding or subtracting the same quantity on both sides preserves the order relationship.',
  'MULTIPLYING OR DIVIDING BY A POSITIVE NUMBER preserves the sign direction because positive scaling keeps order.',
  'MULTIPLYING OR DIVIDING BY A NEGATIVE NUMBER reverses order. Since 2<5, multiplying both sides by−1 gives−2>−5. This explains the reversal rule rather than treating it as magic.',
  'ONE-STEP INEQUALITIES are solved like equations while preserving order: x+4<9 gives x<5.',
  'TWO-STEP INEQUALITIES undo operations in reverse structural order. For 3x+2≤14, subtract2 then divide by3 to obtain x≤4.',
  'NEGATIVE COEFFICIENT. For −2x<8, divide by−2 and reverse the sign: x>−4.',
  'UNKNOWN ON BOTH SIDES. Collect variable terms on one side and constants on the other before the final division.',
  'NUMBER-LINE ENDPOINTS. < or > excludes the endpoint, so use an open circle. ≤ or ≥ includes the endpoint, so use a filled circle.',
  'NUMBER-LINE DIRECTION. Values less than an endpoint extend left; values greater extend right.',
  'COMPOUND INEQUALITY. −2<x≤4 means x is greater than−2 and at most4. Show an open circle at−2, filled circle at4, shade between.',
  'LANGUAGE TRANSLATION. at least→≥, at most→≤, more than→>, fewer/less than→<, no more than→≤, not less than→≥.',
  'WORD PROBLEMS. Define the variable, identify the limit, form the inequality, solve, then interpret in context.',
  'DISCRETE CONTEXTS. If x counts people/books, a result x>3.2 means x must be at least4 whole units. State both algebraic range and practical interpretation.',
  'CHECKING. Test one value inside the solution set, one boundary value where useful, and one value outside it in the original inequality.'
 ],
 workedExamples:[
  'x+7<12→x<5. Check4 works:11<12; boundary5 fails:12<12 is false.',
  'y−3≥8→y≥11.',
  '4p≤20→p≤5.',
  '−3q>12. Divide by−3 and reverse: q<−4.',
  '5x−7≤18→5x≤25→x≤5.',
  '7−2x≤9→−2x≤2→x≥−1 after division by−2.',
  '6x+5>2x+17→4x>12→x>3.',
  '2(x+3)<14→2x+6<14→x<4.',
  '3−5x≥18→−5x≥15→x≤−3.',
  'NUMBER LINE x>2: open circle at2, shade right.',
  'NUMBER LINE x≤−1: filled circle at−1, shade left.',
  'COMPOUND RANGE −3<x≤2: open at−3, filled at2, shade between.',
  'LANGUAGE “score at least50” gives s≥50.',
  'CAPACITY “no more than45 passengers” gives p≤45.',
  'BUDGET: ₦5,000 available, keep at least ₦800. 5000−x≥800→x≤4200.',
  'AGE: a competition requires age under18. a<18; a17-year-old qualifies, an18-year-old does not.',
  'INTEGER INTERPRETATION: x>31.5 litres and litres sold whole→minimum32 litres.',
  'CHECK −4x+3≥19→x≤−4. Test−5:23≥19 true; test0:3≥19 false.'
 ],
 misconceptions:['giving one value instead of a range','reversing the sign after addition/subtraction','forgetting reversal after multiplying/dividing by a negative','reversing when dividing by a positive','using filled endpoints for strict inequalities','using open endpoints for inclusive inequalities','shading the wrong direction','confusing at least with at most','ignoring whole-number restrictions','failing to test a boundary or representative value'],
 guidedPractice:['Solve and graph x+5<13.','Solve and graph y−8≥−2.','Solve 6p≤42.','Solve −4q<20 and explain reversal.','Solve 3x+7>19.','Solve 10−2x≤4.','Solve 5x+2≤2x+14.','Solve 3(x−2)>9.','Graph −1≤x<5.','Translate “a person must be at least18 years old”.','A bag holds at most12kg. Write an inequality for mass m.','A student has ₦2,500 and wants at least ₦400 left. Form and solve an inequality for spending.','A hall holds fewer than350 people. Represent the condition and explain the endpoint.','A test pass mark is not less than40. Write and graph the inequality.'],
 independentPractice:['Solve x+9≤20.','Solve x−12>−4.','Solve 7x<35.','Solve −5x≥25.','Solve 4x−3≤17.','Solve 8−3x>2.','Solve 7x+4≥3x+20.','Solve 2(x+5)≤18.','Solve −3(x−2)>12.','Solve 5−2x≥x−7.','Graph x<−2.','Graph y≥4.','Graph −3<p≤5.','Translate “no more than60 minutes”.','Translate “more than ₦2,500”.','A bus has capacity52. If p passengers are aboard, write the inequality.','A student needs at least70 marks overall and has38 already. If x is remaining marks, form and solve.','A phone plan allows at most5GB extra data. Form an inequality for extra use d.','A package must weigh less than2.5kg. Discuss acceptable recorded values.','Explain with a numerical example why dividing by a negative reverses the sign.'],
 mastery:{criterion:'Learner solves one-step, two-step, bracket and both-side inequalities, explains negative sign reversal, graphs solution sets correctly, translates real contexts and achieves at least85%.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-algebraic-processes-algebraic-operations-4',classLevel:'JSS2',subject:'Mathematics',topic:'Graphs',source:{authority:'NERDC',url:sourceUrl,page:23},
 objectives:['Identify x-axis and y-axis','Plot points on the Cartesian plane','Prepare tables of values','Plot graphs of linear equations in two variables','Interpret plotted graphs','Plot linear graphs from real-life situations','Solve quantitative-reasoning problems using graphs'],
 prerequisites:['directed numbers','substitution','tables and scales'],
 teaching:[
  'THE CARTESIAN PLANE has horizontal x-axis and vertical y-axis meeting at origin(0,0). Right/up are positive; left/down are negative.',
  'ORDERED PAIR (x,y): x comes first and controls horizontal movement; y comes second and controls vertical movement.',
  'QUADRANTS: I(+,+), II(−,+), III(−,−), IV(+,−). Points on axes are not inside quadrants.',
  'SCALE. Equal physical intervals on one axis must represent equal numerical changes. Different axes may use different scales if clearly stated.',
  'PLOTTING. Begin at origin, move x horizontally, then y vertically. Mark accurately and label.',
  'TABLE OF VALUES. For y=2x+1 choose x-values, substitute each, calculate y, then form ordered pairs.',
  'LINEAR GRAPH. A linear equation produces points on one straight line. Plot at least three accurate points and use a ruler.',
  'Y-INTERCEPT is where x=0. In y=mx+c, c is the y-intercept.',
  'GRADIENT m=change in y/change in x. It is a rate of change, not just a visual steepness label.',
  'POSITIVE gradient rises left-to-right; negative falls; zero gradient is horizontal.',
  'REAL-LIFE AXES need labels and units. Without units a slope cannot be interpreted meaningfully.',
  'DISTANCE-TIME GRAPH. Gradient represents speed; steeper means faster; horizontal means stationary.',
  'COST-QUANTITY GRAPH. Gradient may represent unit price; a non-zero intercept can represent fixed charge.',
  'DISCRETE VS CONTINUOUS. Counts may not permit values between points; measurements often do. Join points only when intermediate values make sense.',
  'READING A GRAPH. Trace carefully to axes and respect marked scale rather than estimating by eye.',
  'INTERSECTION. Where two lines cross, both relationships have the same x and y values.',
  'PERMANENT CHECK. Substitute plotted points back into equation and check interpretations against axis units.'
 ],
 workedExamples:['(3,2) is Quadrant I.','(−3,2) is Quadrant II.','(−2,−4) is Quadrant III.','(4,−3) is Quadrant IV.','y=2x+1 for x=−1,0,1,2 gives y=−1,1,3,5.','Check (3,7) on y=2x+1:2(3)+1=7.','For y=3x−2, x=0→y=−2, intercept(0,−2).','Gradient through(1,3),(4,9)=6/3=2.','Gradient through(0,5),(2,1)=−4/2=−2.','y=−x+3 gives(0,3),(1,2),(2,1),(3,0), gradient−1.','Distance-time 120km in2h→60km/h.','Horizontal distance-time segment20min→stationary20min.','Cost line(0,500),(4,2500)→gradient₦500/item, intercept₦500 fixed charge.','Temperature point(3pm,32°C)→32°C at3pm.','Savings ₦2,000→₦5,000 in6 weeks→₦500/week.','y=2x+1 and y=x+4 intersect at(3,7).','Pupil counts are discrete, so2.5 pupils has no meaning.','If each large grid interval=5 units, halfway=2.5 units.'],
 misconceptions:['reversing x/y','ignoring negative directions','inconsistent scale','forgetting units','placing axis points in quadrants','table arithmetic errors','crooked line for linear relation','assuming graph passes origin','misreading gradient units','joining discrete points automatically','visual guessing instead of scale','gradient formula reversed'],
 guidedPractice:['Plot(2,4),(−3,1),(−2,−5),(4,−1).','Build table y=x+2 for x=−2 to2.','Graph y=3x−2.','Check whether(2,4) lies on y=2x.','Find y-intercept y=−2x+5.','Find gradient through(−1,2),(3,10).','Interpret distance-time from(1h,40km) to(3h,140km).','Interpret cost graph fixed₦1,000 plus₦250/item.','Decide whether pupil-count points should be joined.','Read five values from a supplied graph using scale.','Graph y=x+1 and y=−x+5, estimate intersection.','Create graph for savings starting₦2,000 increasing₦500 weekly.'],
 independentPractice:['State quadrant(5,−2).','State quadrant(−4,7).','Plot(0,5),(−3,0),(2,−4).','Table y=2x−3 for x=−2…2.','Graph y=x−2.','Graph y=−2x+4.','Gradient through(2,1),(6,9).','Gradient through(−2,5),(2,−3).','Intercept y=4x+7.','Does(4,11) lie on y=3x−1?','Read a supplied graph at x=3.5.','Journey120km in2.5h: average speed.','Interpret horizontal35min segment.','Taxi intercept₦800, gradient₦300/km: interpret.','Two pricing lines intersect(10,4500): explain.','Plot discrete books-borrowed data.','Explain continuous temperature vs discrete pupil count.','Create and interpret y=5x+2.'],
 mastery:{criterion:'Learner plots coordinates/linear graphs accurately, selects and reads scales, calculates gradient/intercept, interprets real-life graphs with units and intersections, achieving at least85%.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-mensuration-and-geometry-shapes-1',classLevel:'JSS2',subject:'Mathematics',topic:'Plane figures/Shapes',source:{authority:'NERDC',url:sourceUrl,page:24},
 objectives:['State properties of parallelogram, rhombus and kite','Identify these shapes in the environment','Draw plane objects to scale','Convert actual lengths to scale lengths and vice versa','Apply scale drawing to measurement problems','Solve quantitative-reasoning problems involving shapes and scale drawing'],
 prerequisites:['JSS1 plane shapes','measurement/unit conversion','ratio'],
 teaching:['PLANE FIGURES are two-dimensional. Classify from defining properties, not orientation or appearance.','PARALLELOGRAM: opposite sides parallel/equal; opposite angles equal; adjacent angles180°; diagonals bisect.','RECTANGLE is a parallelogram with four right angles; diagonals equal and bisect.','RHOMBUS has four equal sides; diagonals perpendicular and bisect opposite angles.','SQUARE is both rectangle and rhombus.','KITE has two pairs adjacent equal sides; diagonals perpendicular; one bisects the other.','HIERARCHY: every square is rectangle/rhombus; every rhombus is parallelogram; converses need not hold.','PROPERTY REASONING requires enough evidence for a name.','SYMMETRY: square4 lines, rectangle2, rhombus2, common kite1.','SCALE1:n means1 paper unit represents n same real units.','CONVERT UNITS FIRST.','REAL→DRAWING divide by scale factor.','DRAWING→REAL multiply by scale factor.','STATEMENT SCALE may be used directly or converted.','CHOOSE a scale that fits page and remains measurable.','AREA WARNING: length scale1:n implies area scale1:n².','PERMANENT CHECK: justify shape names and scale conversions with units.'],
 workedExamples:['Parallelogram angle68°→opposite68°, adjacent112°.','Rectangle with all sides equal is square.','Rhombus does not require right angles.','Kite AB=AD and CB=CD has adjacent equal pairs.','Square belongs to rectangle/rhombus families.','Parallelogram diagonals bisect but need not be equal/perpendicular.','1:200, real8m=800cm→4cm.','1:500,25m=2500cm→5cm.','1:250,7.2cm→18m.','1cm:4km,6.5cm→26km.','35m at1cm:5m→7cm.','1:50,000,3cm→1.5km.','Room6m×4m at1:100→6cm×4cm.','20m corridor fitting10cm→1:200.','Drawing8cm×5cm at1:100→8m×5m, perimeter26m.','Length scale1:100 gives area scale1:10,000.','Square symmetry4, rectangle2, rhombus2, kite1.','Opposite sides parallel/equal and diagonals bisect, without right-angle data→parallelogram.'],
 misconceptions:['classifying by appearance','every kite is rhombus','every rhombus has right angles','forgetting hierarchy','claiming all parallelogram diagonals equal','mixing units','wrong multiply/divide in scale','forgetting units','impractical scale','using length scale directly for area','ignoring symmetry evidence'],
 guidedPractice:['List parallelogram properties.','Compare rectangle/rhombus.','Explain why square is parallelogram.','Classify from properties.','Find adjacent angle if parallelogram angle74°.','Convert12m at1:300 to drawing length.','Convert5.6cm at1:250 to real length.','Convert4.5cm at1:50,000 to km.','Draw7m×5m room at1:100.','Choose scale for30m×20m compound.','State symmetry lines.','Explain area scale difference.'],
 independentPractice:['State five parallelogram properties.','State four rhombus properties.','State three kite properties.','Classify four equal sides+four right angles.','Find parallelogram angles if one=105°.','1:400 convert16m to drawing cm.','1:250 convert9cm to real metres.','1:100,000 convert6.4cm to km.','1cm:2km find drawing for15km.','12.5cm at1:200→actual metres.','Draw8m×6m rectangle at1:100.','Find scale for24m wall fitting12cm.','7cm×4cm at1:300→actual dimensions/perimeter.','Explain rhombus vs parallelogram hierarchy.','Compare diagonals rectangle/rhombus/kite.','State symmetry lines.','If length scale1:50, state area scale.','Give real-world shape examples justified by properties.'],
 mastery:{criterion:'Learner classifies parallelogram-family and kite shapes from defining properties/symmetry and solves representative/statement scale problems with correct unit conversion at least85%.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-mensuration-and-geometry-shapes-2',classLevel:'JSS2',subject:'Mathematics',topic:'Angles',source:{authority:'NERDC',url:sourceUrl,page:25},
 objectives:['Find the sum of angles in triangles','Find the sum of angles in quadrilaterals','Find the sum of interior angles of polygons','Distinguish angles of elevation and depression','Use elevation/depression with scale drawing to calculate heights/distances','Relate angles of elevation and depression','Solve quantitative-reasoning problems involving angles'],
 prerequisites:['JSS1 angle types','straight-line/point angles','parallel lines','scale drawing'],
 teaching:['ANGLES on a straight line sum180°; around a point360°; vertically opposite angles are equal.','TRIANGLE interior sum180°.','ISOSCELES triangle has equal base angles; equilateral has three60° angles.','TRIANGLE exterior angle equals sum of two opposite interior angles.','QUADRILATERAL sum360°.','POLYGON sum=(n−2)×180° because it splits into n−2 triangles.','REGULAR polygon each interior=[(n−2)180]/n.','EXTERIOR angles of any convex polygon sum360°; regular exterior=360/n.','NUMBER OF SIDES n=360/exterior angle for regular polygon.','PARALLEL LINES: corresponding/alternate equal; co-interior sum180°.','ELEVATION measured upward from horizontal; depression downward from horizontal.','With parallel horizontals suitable depression/elevation angles are equal by alternate angles.','SCALE DRAWING: baseline, construct angle, use scale, measure unknown, convert back.','Never measure elevation/depression from vertical.','PERMANENT CHECK: name the angle fact before calculation.'],
 workedExamples:['55°+65°+x=180°→x60°.','90°+37°+x=180°→x53°.','Isosceles vertex40°→base70°,70°.','Exterior125° and opposite55°→other70°.','Quadrilateral90°,85°,110°,x→75°.','Pentagon sum540°.','Octagon sum1080°.','Regular hexagon interior120°.','Regular nonagon interior140°.','Exterior30°→12 sides.','Corresponding72°→72°.','Co-interior115°→65°.','Elevation35° is upward from horizontal.','Depression28° corresponds to ground elevation28°.','Scale1cm:10m, measured4.6cm→46m.','Baseline50m at1cm:10m→5cm; construct40° and measured height3.2cm→32m.'],
 misconceptions:['using n×180','assuming polygon regular','measuring elevation from vertical','confusing depression/elevation','wrong exterior total','forgetting divide by n','mixing angle relationships','poor scale drawing','forgetting scale conversion'],
 guidedPractice:['Triangle48°,67°,x.','Isosceles vertex36°.','Quadrilateral95°,80°,110°,x.','Interior sums7-gon,10-gon.','Regular octagon interior.','Sides if exterior24°.','Parallel-line mixed examples.','Sketch elevation42°.','Sketch depression25°.','Explain equality of depression/elevation.','Scale1cm:5m model40m with30° elevation.','Check claimed regular pentagon interior120°.'],
 independentPractice:['Triangle72°,41°,x.','Isosceles vertex54°.','Exterior with opposite48°,76°.','Quadrilateral89°,96°,102°,x.','Hexagon sum.','12-gon sum.','Regular pentagon interior.','Regular decagon exterior.','Sides for exterior45°.','Sides for exterior20°.','Corresponding-angle problem.','Alternate-angle problem.','Co-interior problem.','Draw elevation/depression diagram.','Scale1cm:20m measured5.4cm→actual.','Scale drawing point60m from tower with elevation35°.','Explain impossible triangle100°,50°,40°.','Derive polygon sum formula.'],
 mastery:{criterion:'Learner uses triangle/quadrilateral/polygon/parallel-line facts, regular polygon formulas and elevation/depression scale drawings with explicit justification and at least85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-mensuration-and-geometry-shapes-3',classLevel:'JSS2',subject:'Mathematics',topic:'Bearing',source:{authority:'NERDC',url:sourceUrl,page:26},
 objectives:['Identify cardinal points','Locate objects using compass and three-digit bearings','Find distances between objects using scale drawing'],
 prerequisites:['angles measured clockwise','protractor use','scale drawing'],
 teaching:[
  'CARDINAL DIRECTIONS are North, East, South and West, with NE, SE, SW and NW between them.',
  'A THREE-DIGIT BEARING is measured clockwise from North and written with three digits, for example 035°,090°,180° and270°.',
  'THE STARTING POINT MATTERS. Bearing of B from A means stand at A, draw North at A, then measure clockwise from that North line to AB.',
  'CARDINAL BEARINGS: N=000° or360°, E=090°, S=180°, W=270°.',
  'INTERMEDIATE DIRECTIONS: exact NE=045°, SE=135°, SW=225°, NW=315°.',
  'DRAWING A BEARING: draw North, place protractor centre at the point, align zero with North, measure clockwise, then draw the ray.',
  'READING A BEARING: begin at North, turn clockwise to the target line, and record the angle with three digits.',
  'REVERSE BEARING changes viewpoint by180°. If the original is below180°, add180°; if180° or more, subtract180°.',
  'COMPASS NOTATION and bearings are related but different. N30°E means30° east of North, which is bearing030°; S20°E means20° east of South, bearing160°.',
  'SCALE DRAWING combines direction and distance. Determine the bearing first, then mark the scaled distance along that ray.',
  'MULTI-LEG JOURNEYS require a fresh North line at each new point. Do not measure the next bearing from the previous route line.',
  'DISTANCE BETWEEN TWO ENDPOINTS can be found by measuring the final connecting line on the completed scale drawing and converting back.',
  'POSITION CHECK: if a bearing lies between090° and180°, the point should be in the south-east quadrant. Use this to catch protractor errors.',
  'REVERSE-BEARING CHECK: the two bearings must differ by exactly180°.',
  'PERMANENT METHOD: starting point→North line→clockwise angle→three-digit notation→scaled distance→fresh North at next point→final check.'
 ],
 workedExamples:[
  'Due East is090° because it is a quarter-turn clockwise from North.',
  'Due South is180°; due West is270°.',
  'NE is045° and NW is315°.',
  'Bearing of B from A=065°. Reverse bearing of A from B=065+180=245°.',
  'Bearing220° reversed gives040° because220−180=40, written040°.',
  'Bearing005° must be written005°, not5°.',
  'N35°E converts to035° because turn35° clockwise from North.',
  'S30°E converts to150° because South is180° and move30° back toward East:180−30=150°.',
  'S25°W converts to205° because180+25=205°.',
  'N40°W converts to320° because360−40=320°.',
  'At scale1cm:5km,20km is drawn as4cm.',
  'A to B bearing060°,15km at1cm:5km: draw060° ray and mark3cm.',
  'From B to C bearing140°,10km at same scale: draw new North at B, measure140°, mark2cm.',
  'If completed drawing gives AC=4.6cm at1cm:5km, actual AC=23km.',
  'A ship travels20km on045° then15km on135°. At1cm:5km draw4cm then3cm; measure displacement from start.',
  'Position check: bearing135° should point SE. A line pointing NW means the angle was measured incorrectly.',
  'Reverse pair125° and305° is correct because difference=180°.',
  'Reverse pair075° and245° is wrong; correct reverse of075° is255°.'
 ],
 misconceptions:[
  'measuring anticlockwise',
  'starting from East instead of North',
  'omitting leading zeros',
  'confusing bearing of A from B with B from A',
  'using one North line for all legs',
  'adding180° without reducing angles above360°',
  'converting quadrant notation carelessly',
  'drawing distance before direction',
  'forgetting scale conversion',
  'ignoring whether the ray lands in the correct quadrant'
 ],
 guidedPractice:[
  'Write bearings of E,S,W,NE,SE,SW,NW.',
  'Find reverse bearings of035°,125°,240°,315°.',
  'Draw070° from point A.',
  'Draw205° from point P.',
  'Convert N25°E,N40°W,S35°E,S20°W to three-digit bearings.',
  'Convert bearings045°,120°,225°,310° into compass/quadrant descriptions.',
  'At1cm:4km convert28km to drawing length.',
  'At1cm:6km convert5.5cm drawing to actual distance.',
  'Draw A→B055°,12km at1cm:4km.',
  'From B draw B→C130°,8km and measure AC.',
  'Explain why every reverse bearing differs by180°.',
  'Check whether a plotted130° ray is in the correct quadrant.'
 ],
 independentPractice:[
  'Write bearing of due North.','Write bearing of SE.','Write bearing of NW.',
  'Find reverse of080°.','Find reverse of190°.','Find reverse of275°.',
  'Convert N15°E to bearing.','Convert N50°W to bearing.','Convert S35°E to bearing.','Convert S42°W to bearing.',
  'Convert bearing110° to compass description.','Convert bearing300° to compass description.',
  'At1cm:2km convert18km to drawing length.','At1cm:6km convert5.5cm to actual distance.',
  'Plot B15km from A on060° at1cm:5km.','From B plot C10km on150° and measure AC.',
  'A ship travels20km on045°, then15km on135°; make a scale drawing and find displacement.',
  'A hiker travels12km on300°, then8km on060°; estimate final displacement by scale drawing.',
  'Explain why measuring from East produces a wrong bearing.',
  'Check and correct claimed reverse pair075° and245°.'
 ],
 mastery:{criterion:'Learner writes, converts, draws and reverses bearings accurately, handles multi-leg scale drawings and distance conversions, and achieves at least85% with correct three-digit notation.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-mensuration-and-geometry-shapes-4',classLevel:'JSS2',subject:'Mathematics',topic:'Construction',source:{authority:'NERDC',url:sourceUrl,page:26},
 objectives:['Construct triangles from two sides and included angle','Construct triangles from two angles and included side','Construct triangles from three sides','Bisect a given angle'],
 prerequisites:['ruler and compass use','protractor where permitted','triangle vocabulary','accurate measurement'],
 teaching:[
  'GEOMETRIC CONSTRUCTION creates exact relationships from given measurements. Keep arcs visible because they show how the figure was obtained.',
  'PERPENDICULAR BISECTOR of a line segment passes through its midpoint at90°. Draw equal-radius arcs from both endpoints using radius more than half the segment.',
  'ANGLE BISECTOR divides one angle into two equal parts. Use one arc from vertex to cut both arms, then equal arcs from those cut points.',
  '60° can be constructed from an equilateral triangle because all three sides and angles are equal.',
  '30° is obtained by bisecting60°; 90° by constructing a perpendicular; 45° by bisecting90°.',
  'SAS TRIANGLE: draw one given side, construct the included angle at the correct endpoint, mark the second given side length along the ray, then join the third side.',
  'ASA TRIANGLE: draw the included side, construct the two given angles at its endpoints, extend the rays until they meet.',
  'AAS can be completed by first finding the missing triangle angle from180° when necessary.',
  'SSS TRIANGLE: draw one side; from its endpoints draw arcs with radii equal to the other two sides; their intersection is the third vertex.',
  'TRIANGLE INEQUALITY must hold for SSS: sum of any two sides must be greater than the third. If not, the arcs will not meet.',
  'PERPENDICULAR THROUGH A POINT ON A LINE: mark equal distances on both sides of the point, draw equal arcs, and join their intersection to the point.',
  'PERPENDICULAR FROM AN EXTERNAL POINT: arc from the external point cuts the line twice; equal arcs from those cuts locate a point on the perpendicular.',
  'LOCUS INTERPRETATION. Any point on a perpendicular bisector is equidistant from the segment endpoints; any point on an angle bisector is equidistant from the two arms.',
  'ACCURACY STANDARD: sharp pencil, firm compass radius, labelled points, exact centres, visible arcs and correct units.',
  'VERIFY AFTER CONSTRUCTION. Measuring afterward is a check, not a substitute for the construction method.'
 ],
 workedExamples:[
  'Bisect AB=8cm: arcs from A and B using same radius greater than4cm meet above/below; joining intersections crosses AB at midpoint4cm from each end.',
  'Bisect70°: one arc from vertex cuts arms at X,Y; equal arcs from X,Y meet at P; join vertex to P to obtain35° and35°.',
  'Construct60° on AB: compass radius AB; arcs from A and B meet at C; triangle ABC is equilateral.',
  'Construct30° by bisecting the60° angle.',
  'Construct90° at O on a line using equal points left/right of O and intersecting arcs.',
  'Construct45° by bisecting the90° angle.',
  'SAS: AB=6cm,AC=5cm,∠BAC=70°. Draw AB6; construct70° at A; mark AC5; join C to B.',
  'SAS: PQ=7cm,PR=4cm,∠QPR=55°. Draw PQ7; construct55° at P; mark PR4; join RQ.',
  'ASA: AB=6cm,∠A=50°,∠B=60°. Draw AB; construct both rays; intersection gives C.',
  'AAS: AB=5cm,∠A=40°,∠C=75°. First B=180−115=65°, then use AB with angles40° and65°.',
  'SSS: sides5,6,7cm. Draw base7; arc radius5 from one end, radius6 from other; intersection gives third vertex.',
  'SSS isosceles:6,6,8cm. Use base8 and equal6cm arcs; apex lies on perpendicular bisector.',
  'Impossible SSS:2,3,6cm because2+3≤6; arcs cannot intersect.',
  'External perpendicular: point P above line l; arc centred P cuts l at A,B; equal arcs from A,B meet Q; PQ is perpendicular to l.',
  'Locus: a school equally distant from villages A and B must lie on perpendicular bisector of AB.',
  'Angle-bisector locus: a point equally distant from two intersecting roads lies on one of their angle bisectors.',
  'Construct120° from60° geometry and verify with protractor after completing arcs.',
  'Construct135° as90°+45°, with45° obtained by bisection.'
 ],
 misconceptions:[
  'using protractor where compass construction is required',
  'changing compass radius during paired arcs',
  'using wrong included angle in SAS',
  'mixing SSS radii',
  'drawing ASA angles from wrong endpoints',
  'ignoring triangle inequality',
  'using radius too small for perpendicular-bisector arcs to meet',
  'erasing construction evidence',
  'measuring midpoint by ruler instead of constructing it',
  'treating verification measurement as the construction itself'
 ],
 guidedPractice:[
  'Bisect a7cm segment.',
  'Construct perpendicular through midpoint of9cm segment.',
  'Bisect an80° angle.',
  'Construct60° and then30°.',
  'Construct90° and then45°.',
  'Construct120°.',
  'Construct SAS triangle5cm,6cm,included65°.',
  'Construct SAS triangle7cm,4cm,included50°.',
  'Construct SSS triangle5,7,8cm.',
  'Construct ASA triangle base6cm,angles55°,70°.',
  'Test whether3,4,8cm can form a triangle.',
  'Construct perpendicular from a point outside a line.'
 ],
 independentPractice:[
  'Bisect10cm segment.','Construct perpendicular at a point on a line.','Construct perpendicular from external point.',
  'Bisect110° angle.','Construct30°.','Construct45°.','Construct60°.','Construct90°.','Construct120°.','Construct135°.',
  'Construct SAS triangle7cm,5cm,included50°.','Construct SAS triangle6cm,8cm,included40°.',
  'Construct SSS triangle6,6,8cm.','Construct SSS triangle5,7,9cm.',
  'Construct ASA triangle base7cm,angles40°,75°.','Construct AAS triangle base5cm with angles35°,65°.',
  'Decide if2,5,8cm can form triangle and explain.','Decide if4,5,7cm can form triangle.',
  'Use perpendicular bisector to locate a point equidistant from A,B.',
  'Write a complete angle-bisector construction without using a protractor.'
 ],
 mastery:{criterion:'Learner performs accurate line/angle bisectors, standard-angle and SAS/ASA/AAS/SSS constructions, preserves arcs, checks triangle feasibility and explains why each construction works.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-everyday-statistics-data-collection-and-presentation-1',classLevel:'JSS2',subject:'Mathematics',topic:'Data presentation',source:{authority:'NERDC',url:sourceUrl,page:27},
 objectives:['Present data in ordered form','Construct frequency tables from familiar data','Read information from pie charts','Calculate and interpret interquartile range','Use box plots to organise, compare and interpret distributions'],
 prerequisites:['JSS1 data presentation','fractions/percentages','median','angles'],
 teaching:[
  'RAW DATA are individual observations before organisation. Ordering reveals centre and spread more clearly.',
  'A FREQUENCY TABLE lists each value/category and how often it appears. Total frequency must equal total observations.',
  'TALLY MARKS help count systematically in groups of five before final frequency.',
  'PIE CHART sector angle=(frequency/total)×360°. Every sector must represent its share of the whole.',
  'PERCENT TO ANGLE: percentage×360/100. ANGLE TO FREQUENCY: angle/360×total.',
  'CHECK PIE CHART: angles total360° and percentages total100% apart from rounding.',
  'ORDER DATA BEFORE QUARTILES. Quartiles are meaningless if the dataset is not sorted.',
  'Q2 is the median. For odd n under AVORA school convention, exclude the overall median before finding Q1 and Q3; for even n split equally.',
  'IQR=Q3−Q1 measures spread of the middle50%, reducing influence of extreme values compared with full range.',
  'FIVE-NUMBER SUMMARY is minimum,Q1,median,Q3,maximum.',
  'BOX PLOT: draw uniform number scale, box Q1→Q3, median line atQ2, whiskers to min/max.',
  'COMPARING BOX PLOTS: compare median (centre), IQR (middle spread), total range, and visible asymmetry.',
  'A HIGHER MEDIAN means higher central value, not automatically “better” unless context defines better.',
  'A LARGER IQR means more variability in the middle half.',
  'OUTLIERS may stretch total range without changing IQR much; describe only what the data show.',
  'BAR CHART vs PIE CHART: bars compare category sizes directly; pie charts emphasise proportions of one whole.',
  'LINE GRAPH is appropriate for change over ordered time or continuous sequence, not every categorical dataset.',
  'PERMANENT CHECK: labels, units, total frequency, scale and source must be read before interpreting.'
 ],
 workedExamples:[
  'Data2,3,2,5,3,2→ordered2,2,2,3,3,5; frequencies2→3,3→2,5→1.',
  'Tallies for scores1,2,2,3,2,1,4 give1:2,2:3,3:1,4:1.',
  '10 of40 learners choose football→sector10/40×360=90°.',
  '25% category→sector0.25×360=90°.',
  '72° sector in total150→72/360×150=30 people.',
  'Pie sectors90°,120°,60°,90° sum360°, so total is consistent.',
  'Even data2,4,5,7,8,10,13,15: Q2=7.5,Q1=4.5,Q3=11.5,IQR=7.',
  'Odd data1,3,4,6,8,9,12: Q2=6; lower1,3,4→Q1=3; upper8,9,12→Q3=9; IQR=6.',
  'Five-number summary2,4.5,7.5,11.5,15 gives box from4.5 to11.5, median7.5, whiskers2 and15.',
  'Class A median52,IQR8; Class B median55,IQR18. B centre is higher, but middle50% is more spread.',
  'Dataset A range30 but IQR5 may have extreme values far from central cluster.',
  'Category frequencies12,18,30 out of60 convert to72°,108°,180°.',
  'Pie chart angle144° with total80 represents32 because144/360×80=32.',
  'Bar chart is better than pie chart when comparing exact counts across many categories.',
  'Line graph is suitable for monthly rainfall over a year because order/time matters.',
  'Box plots with same median but IQR6 vs14 have equal centre but different central spread.',
  'If median lies near Q1 and upper whisker is long, distribution appears more stretched on upper side; describe shape cautiously.',
  'Frequency check: if table frequencies sum48 but source says50 observations, two observations are missing or miscounted.'
 ],
 misconceptions:[
  'using frequency directly as angle',
  'forgetting total angle360°',
  'finding quartiles before ordering',
  'confusing range with IQR',
  'including odd overall median in both halves under stated convention',
  'drawing non-uniform box-plot scale',
  'claiming causation from chart',
  'assuming higher median always better',
  'comparing IQRs with mismatched units',
  'forgetting total frequency check'
 ],
 guidedPractice:[
  'Create frequency table from3,5,5,6,8,5,9,6,6,11.',
  'Convert frequencies8,12,20 out of40 to pie angles.',
  'Find frequency represented by54° in total120.',
  'Order3,5,5,6,8,9,11,13 and find Q1,Q2,Q3,IQR.',
  'Find quartiles for1,2,4,5,7,9,10.',
  'Build five-number summary and sketch box plot.',
  'Compare two box plots with medians45/50 and IQRs6/14.',
  'Explain effect of one very large value on range versus IQR.',
  'Choose bar/pie/line for three data contexts and justify.',
  'Check a faulty pie chart whose sectors total350°.',
  'Check a frequency table against stated sample size.',
  'Write two evidence-based sentences comparing centre and spread.'
 ],
 independentPractice:[
  'Construct frequency table for twenty supplied scores.',
  'Turn frequencies5,10,15,20 into pie angles.',
  'Find percentage for108° sector.',
  'Find frequency for90° sector if total200.',
  'Find quartiles/IQR for2,4,6,8,10,12,14,16.',
  'Find quartiles/IQR for1,3,4,7,9,11,15.',
  'Construct box plot from min2,Q1=5,median8,Q3=12,max20.',
  'Compare box plots A:3,6,9,12,18 and B:2,8,10,16,22.',
  'State which dataset has larger IQR and range.',
  'Explain why one outlier may affect range more than IQR.',
  'Choose graph type for market-share categories.',
  'Choose graph type for daily temperature over14 days.',
  'Interpret a pie chart of school transport modes.',
  'Interpret a frequency table and identify modal value.',
  'Detect an impossible pie chart with sectors totalling more than360°.',
  'Write a full comparison of two distributions using median,IQR,range.',
  'Explain why a chart cannot prove the cause of a pattern.',
  'Design a small survey and state suitable presentation form.'
 ],
 mastery:{criterion:'Learner constructs/checks frequency and pie representations, computes quartiles/IQR accurately, builds and compares box plots, and selects/interprets displays with at least85% evidence-based accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-everyday-statistics-data-collection-and-presentation-2',classLevel:'JSS2',subject:'Mathematics',topic:'Probability',source:{authority:'NERDC',url:sourceUrl,page:27},
 objectives:['Discuss chance events in everyday life','Determine probabilities of simple events','Apply probability/chance to everyday situations'],
 prerequisites:['fractions/ratios','counting outcomes','data interpretation'],
 teaching:[
  'PROBABILITY measures likelihood from0 to1. 0 means impossible;1 means certain.',
  'EXPERIMENT is the action, OUTCOME is one possible result, EVENT is one or more outcomes of interest.',
  'SAMPLE SPACE lists all possible outcomes. Build it before counting favourable outcomes.',
  'For EQUALLY LIKELY outcomes, P(event)=favourable outcomes/total outcomes.',
  'A fair coin has sample space{H,T}; a fair die has{1,2,3,4,5,6}.',
  'PROBABILITY can be written as fraction, decimal or percentage, but must stay between0 and1.',
  'COMPLEMENT means not the event. P(not A)=1−P(A).',
  'CERTAIN/IMPOSSIBLE checks help catch mistakes: probability cannot be negative or exceed1.',
  'COMPOUND DESCRIPTION within one trial may use counting: on a die, “even or greater than4” requires listing union outcomes, not adding blindly.',
  'WITHOUT REPLACEMENT changes probabilities because the total contents change after an item is removed.',
  'WITH REPLACEMENT restores original composition before the next draw.',
  'EXPERIMENTAL PROBABILITY=observed frequency/number of trials.',
  'THEORETICAL and experimental probabilities may differ in small samples; repeated trials often bring relative frequency closer to theoretical expectation.',
  'EXPECTED FREQUENCY can be estimated as probability×number of trials, but it is not a guarantee.',
  'EVERYDAY RISK: a70% chance means event is likely, not certain. Probability informs decisions under uncertainty.',
  'INDEPENDENT EVENTS: one fair coin toss does not “owe” a head after several tails. Previous independent outcomes do not force the next result.',
  'PERMANENT METHOD: define experiment→list sample space→identify event→count carefully→simplify probability→interpret.'
 ],
 workedExamples:[
  'Fair coin: S={H,T};P(H)=1/2.',
  'Fair die: P(6)=1/6.',
  'Fair die: even outcomes{2,4,6};P(even)=3/6=1/2.',
  'Fair die: number>4 gives{5,6};P=2/6=1/3.',
  'Fair die: prime outcomes{2,3,5};P=3/6=1/2.',
  'Bag3 red,2 blue,5 green,total10:P(blue)=2/10=1/5.',
  'Same bag:P(not blue)=8/10=4/5, also1−1/5=4/5.',
  'Spinner with8 equal sectors,3 yellow:P(yellow)=3/8.',
  'Letters in word SCHOOL chosen equally by position:S,C,H,O,O,L;P(O)=2/6=1/3.',
  'Die event even OR >4: union{2,4,6,5}={2,4,5,6};P=4/6=2/3.',
  'Without replacement: bag2 red,1 blue. First red P=2/3; if red removed, second red P=1/2.',
  'With replacement after red draw from2R1B, composition returns; next red remains2/3.',
  'Experiment: heads18 times in40 tosses→experimental P(H)=18/40=0.45.',
  'Rain on18 of60 comparable days→experimental probability0.3.',
  'Expected sixes in120 fair-die rolls≈1/6×120=20, not guaranteed exactly20.',
  'If P(rain)=0.7, P(no rain)=0.3.',
  'Impossible event die shows7:P=0. Certain event die shows1–6:P=1.',
  'After five tails on a fair coin, next toss P(head)=1/2 because tosses are independent.'
 ],
 misconceptions:[
  'putting total over favourable',
  'not listing sample space',
  'double-counting overlap in OR event',
  'probabilities below0 or above1',
  'assuming experimental equals theoretical exactly',
  'believing past independent outcomes force next',
  'confusing with/without replacement',
  'treating expected frequency as guarantee',
  'forgetting complement sums to1',
  'assuming outcomes are equally likely without checking'
 ],
 guidedPractice:[
  'Find P(odd),P(prime),P(not prime) on fair die.',
  'Find P(vowel) from letters in MATHS.',
  'Bag4 red,3 blue,1 green: find each colour probability and complements.',
  'Spinner12 equal sectors with5 shaded: find shaded/not shaded.',
  'Find P(even or >4) on die by listing outcomes.',
  'A coin gives27 heads in50 tosses: experimental probability.',
  'Compare experimental0.54 with theoretical0.5.',
  'Estimate expected heads in200 fair tosses.',
  'Bag2R1B: compare second-draw red probability with and without replacement after first red.',
  'Explain why six consecutive tails do not make head certain next.',
  'Convert3/8 probability to decimal and percentage.',
  'Decide whether1.2 can be a probability and justify.'
 ],
 independentPractice:[
  'Find P(head) fair coin.','Find P(number<3) fair die.','Find P(multiple of3) fair die.','Find P(not even) fair die.',
  'Bag5 red,4 blue,1 white: P(red).','Same bag:P(not white).','Same bag:P(blue or white).',
  'Spinner10 equal sectors,4 green:P(green),P(not green).',
  'Choose a letter from BANANA by position:P(A),P(N),P(B).',
  'A die rolled60 times shows6 eight times: experimental P(6).',
  'A coin tossed100 times gives56 heads: experimental P(H).',
  'Compare theoretical and experimental coin probabilities.',
  'Estimate expected threes in180 fair-die rolls.',
  'If P(bus late)=0.25, find P(not late).',
  'Bag3R2B without replacement: find first red probability and second red after a red is removed.',
  'Explain how replacement changes the second probability.',
  'Explain gambler’s fallacy using coin tosses.',
  'Give one everyday statement where probability informs a decision but does not guarantee outcome.',
  'Create a six-outcome sample space and one event of probability1/3.',
  'Check whether listed probabilities0,0.4,1,1.3,−0.2 are valid.'
 ],
 mastery:{criterion:'Learner builds sample spaces, computes simple/complement/union and basic replacement probabilities, distinguishes theoretical from experimental probability, and interprets chance without certainty at at least85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
}

];

export function getJss2MathDeepLesson(topicId:string){return jss2MathematicsDeepLessons.find(x=>x.topicId===topicId)}
