export type DeepJss2MathLesson={
 topicId:string; classLevel:'JSS2'; subject:'Mathematics'; topic:string;
 source:{authority:'NERDC';url:string;page:number}; objectives:string[]; prerequisites:string[];
 teaching:string[]; workedExamples:string[]; misconceptions:string[]; guidedPractice:string[]; independentPractice:string[];
 mastery:{criterion:string;status:'DEEP_WHEN_PASSED'}; boardReady:true;
};

const sourceUrl='https://nerdc.gov.ng/content_manager/jss/jss1-3_maths.pdf';

/** AVORA-authored teaching. NERDC controls scope/objectives; explanations, examples and practice are original. */
export const jss2MathematicsDeepLessons:DeepJss2MathLesson[]=[
{
 topicId:'nerdc-jss2-math-numbers-and-numeration-whole-numbers-1',classLevel:'JSS2',subject:'Mathematics',topic:'Whole Numbers',source:{authority:'NERDC',url:sourceUrl,page:18},
 objectives:['Express whole numbers in standard form','Express decimal numbers in standard form','Find prime factors of numbers not greater than 200','Express numbers as products of prime factors','Find LCM and HCF','Identify perfect squares and find squares','Find square roots of perfect squares by factor method and estimate other square roots','Solve quantitative-reasoning problems using these ideas'],
 prerequisites:['JSS1 place value and large numbers','meaning of prime number, factor and multiple','basic multiplication and division facts','powers such as 10² and 10³'],
 teaching:[
  'STANDARD FORM — MEANING FIRST. Standard form writes a non-zero number as a×10^n where 1≤a<10. The first factor tells the significant digits while the power of ten records the place-value shift. A number such as 48,000 is not written as 48×10³ in standard form because 48 is not between 1 and 10.',
  'WHOLE NUMBERS IN STANDARD FORM. Move the decimal point left until exactly one non-zero digit remains before it. Count the number of places moved; that count becomes a positive power of ten. Example: 725,000→7.25×10⁵ because the decimal point moves five places left.',
  'DECIMALS IN STANDARD FORM. Move the decimal point right until the first factor lies between 1 and 10. A rightward move produces a negative exponent because the original number is smaller than 1. Example: 0.00084→8.4×10⁻⁴.',
  'CHECKING STANDARD FORM. Reverse the multiplication by 10^n. For 6.03×10⁶, move the decimal six places right to recover 6,030,000. For 9.05×10⁻³, move three places left to recover 0.00905.',
  'PRIME NUMBERS AND PRIME FACTORS. A prime number has exactly two positive factors: 1 and itself. Composite numbers have more than two. Prime factorization rewrites a number entirely as a product of prime numbers. A factor tree is complete only when every branch ends in primes.',
  'FACTOR-TREE METHOD. Begin with any convenient factor pair, then continue splitting every composite factor. Different trees may look different but must finish with the same prime factors, apart from order.',
  'REPEATED-DIVISION METHOD. Divide successively by the smallest prime that works exactly: usually 2, then 3, then 5, 7 and so on. Stop when the quotient becomes 1. The divisors written down are the prime factors.',
  'INDEX FORM. Repeated prime factors can be compressed with powers. For example, 2×2×2×3×3 becomes 2³×3². The exponent tells how many times that prime is used as a factor.',
  'LCM FROM PRIME FACTORS. The LCM must contain enough prime factors to be divisible by every given number. Therefore take every prime that appears and use its HIGHEST power among the numbers.',
  'HCF FROM PRIME FACTORS. The HCF must divide every given number, so only primes shared by all numbers can be used, and each shared prime can appear only to the LOWEST power present in all.',
  'PERFECT SQUARES. A perfect square is a whole number obtained by multiplying an integer by itself: 1,4,9,16,25,36,49,64,81,100,… In prime-factor form, every exponent in a perfect square is even because factors pair up.',
  'SQUARE ROOT OF A PERFECT SQUARE BY FACTOR METHOD. Prime-factorize the number, group equal primes into pairs, then take one factor from each pair. For 196=2²×7², √196=2×7=14.',
  'NON-PERFECT SQUARE ROOT BY ESTIMATION. First bracket the number between two consecutive perfect squares. If 64<70<81, then 8<√70<9. Test sensible decimals such as 8.3 or 8.4 and square them to decide which is closer.',
  'QUANTITATIVE REASONING. These ideas appear inside practical questions: scientific notation for large/small measurements, HCF for greatest equal group size, LCM for repeating schedules, and square roots for side lengths of squares. The learner must first identify which relationship the situation is describing before calculating.',
  'PERMANENT CHECKING RULE. Standard-form answers must reverse correctly; prime factorizations must multiply back to the original number; LCM must be divisible by each number; HCF must divide each number; square-root estimates should square back close to the original value.'
 ],
 workedExamples:[
  'STANDARD FORM — WHOLE NUMBER. Express 48,000 in standard form. Move the decimal 4 places left: 48,000→4.8. Therefore 48,000=4.8×10⁴. Check: 4.8×10,000=48,000.',
  'STANDARD FORM — LARGER NUMBER. Express 6,030,000 in standard form. Move the decimal 6 places left: 6,030,000=6.03×10⁶. Check by moving the decimal six places right.',
  'STANDARD FORM — SMALL DECIMAL. Express 0.0063 in standard form. Move the decimal 3 places right to get 6.3. Because the original is smaller than 1, the exponent is negative: 0.0063=6.3×10⁻³.',
  'STANDARD FORM — VERY SMALL DECIMAL. Express 0.00084 in standard form. Move the decimal 4 places right to get 8.4, so 0.00084=8.4×10⁻⁴.',
  'PRIME FACTORIZATION — FACTOR TREE. Factorize 84. One tree is 84=12×7, 12=3×4, 4=2×2. Therefore 84=2²×3×7. Check: 4×3×7=84.',
  'PRIME FACTORIZATION — REPEATED DIVISION. Factorize 180. Divide: 180÷2=90, 90÷2=45, 45÷3=15, 15÷3=5, 5÷5=1. Therefore 180=2²×3²×5.',
  'LCM — TWO NUMBERS. Find LCM of 72 and 90. 72=2³×3²; 90=2×3²×5. Highest powers are 2³,3²,5. LCM=2³×3²×5=8×9×5=360.',
  'HCF — TWO NUMBERS. Find HCF of 72 and 90. Shared primes are 2 and 3. Lowest powers are 2¹ and 3². HCF=2×9=18.',
  'LCM AND HCF — THREE NUMBERS. For 36=2²×3², 48=2⁴×3 and 60=2²×3×5: HCF=2²×3=12. LCM=2⁴×3²×5=720. Check: 720 is divisible by 36,48 and 60; 12 divides all three.',
  'PERFECT SQUARE RECOGNITION. Is 144 a perfect square? 144=12×12, so yes. Prime-factor check: 144=2⁴×3²; every exponent is even. Therefore √144=12.',
  'SQUARE ROOT BY PRIME FACTORS. Find √196. 196=2×98=2×2×49=2²×7². Pair the equal factors: (2×2)(7×7). Take one from each pair: √196=2×7=14.',
  'SQUARE ROOT — NOT PERFECT. Estimate √50 to 1 d.p. Since 7²=49 and 8²=64, √50 lies just above 7. Try 7.1: 7.1²=50.41. Therefore √50≈7.1 to 1 d.p.',
  'SQUARE ROOT — CLOSER COMPARISON. Estimate √70 to 1 d.p. Since 8²=64 and 9²=81, √70 is between 8 and 9. 8.3²=68.89 and 8.4²=70.56. 70 is closer to 70.56 than 68.89, so √70≈8.4 to 1 d.p.',
  'QUANTITATIVE REASONING — REPEATING EVENTS. A bus leaves every 18 minutes and another every 24 minutes. They leave together now. When next together? 18=2×3², 24=2³×3. LCM=2³×3²=72. They leave together again after 72 minutes.',
  'QUANTITATIVE REASONING — GREATEST EQUAL GROUPS. 84 red beads and 126 blue beads are to be packed into the greatest possible number of identical groups with no leftovers. 84=2²×3×7, 126=2×3²×7. HCF=2×3×7=42, so 42 identical groups can be made.'
 ],
 misconceptions:[
  'writing 48×10³ as standard form even though the first factor is not between 1 and 10',
  'using a positive exponent for a number smaller than 1',
  'counting decimal-point moves in the wrong direction',
  'leaving composite factors such as 6 or 9 in a prime factorization',
  'assuming a different factor tree gives a different prime factorization',
  'using highest powers for HCF or lowest powers for LCM',
  'including a prime in the HCF when it is not present in every number',
  'assuming every square root is a whole number',
  'pairing unlike prime factors when using the square-root factor method',
  'giving an estimated square root without bracketing it between perfect squares and checking by squaring'
 ],
 guidedPractice:[
  'Express 725,000 and 0.00084 in standard form and reverse each answer to verify it.',
  'Prime-factorize 168 using a factor tree and 180 using repeated division.',
  'Find HCF and LCM of 24 and 54 using prime factors; verify both results.',
  'Find HCF and LCM of 36,48 and 60.',
  'Decide whether 225 is a perfect square and justify using both multiplication and prime factors.',
  'Find √196 by prime factors.',
  'Estimate √82 to 1 d.p. by bracketing and testing.',
  'Two warning lights flash every 15 s and 20 s. Determine when they next flash together and explain why LCM is used.'
 ],
 independentPractice:[
  'Write 8,450,000 in standard form.',
  'Write 0.000072 in standard form.',
  'Convert 3.68×10⁵ to an ordinary number.',
  'Convert 7.02×10⁻⁴ to an ordinary decimal.',
  'Prime-factorize 96.',
  'Prime-factorize 150.',
  'Prime-factorize 192.',
  'Find HCF of 84 and 126.',
  'Find LCM of 24 and 90.',
  'Find HCF and LCM of 36,48,60.',
  'List the perfect squares between 50 and 150.',
  'Find 17² without a calculator and state whether 289 is a perfect square.',
  'Find √324 using prime factors.',
  'Estimate √65 to 1 d.p. and check by squaring.',
  'Estimate √115 to 1 d.p.',
  'Three bells ring every 12,18 and 30 minutes. If they ring together now, after how many minutes will they next ring together?',
  'A teacher has 72 pencils and 96 rulers and wants the greatest number of identical packs with nothing left over. How many packs can be made and what is in each pack?',
  'A square courtyard has area 625 m². Find the side length and explain why a square root is required.'
 ],
 mastery:{criterion:'At least 80% across standard form, prime factorization, LCM/HCF, perfect squares, square roots and quantitative reasoning, with every answer checked using an appropriate reverse or reasonableness method.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-numbers-and-numeration-fractions-1',classLevel:'JSS2',subject:'Mathematics',topic:'Fractions',source:{authority:'NERDC',url:sourceUrl,page:19},
 objectives:['Convert simple fractions to ratios, decimals and percentages and vice versa','Solve quantitative-reasoning problems involving fractions, ratios, decimals and percentages'],
 prerequisites:['JSS1 equivalent fractions and simplification','basic division','meaning of ratio','place value in decimals','percentage as parts per hundred'],
 teaching:[
  'FRACTION, RATIO, DECIMAL AND PERCENTAGE ARE RELATED BUT NOT IDENTICAL WORDS. A fraction such as 3/5 describes three equal parts out of five equal parts of a whole. A ratio such as 3:5 compares two quantities. A decimal such as 0.6 is a base-ten representation of the same numerical value as 3/5, while 60% means 60 out of every 100.',
  'FRACTION TO DECIMAL. Divide the numerator by the denominator. For 3/5, calculate 3÷5=0.6. The division is not a trick: a fraction bar itself means division.',
  'FRACTION TO PERCENTAGE. Either convert to decimal and multiply by 100%, or create an equivalent fraction with denominator 100 when convenient. For 3/5, 0.6×100%=60%. Also, 3/5=60/100=60%.',
  'DECIMAL TO FRACTION. Use place value. 0.45 means 45 hundredths, so 0.45=45/100. Then simplify by the HCF: HCF(45,100)=5, so 45/100=9/20.',
  'PERCENTAGE TO FRACTION. The symbol % means “per hundred”. Therefore 35%=35/100=7/20 after dividing numerator and denominator by 5.',
  'PERCENTAGE TO DECIMAL. Divide by 100, which is the same as moving the decimal point two places left. Thus 62.5%=0.625. To check, 0.625×100%=62.5%.',
  'DECIMAL TO PERCENTAGE. Multiply by 100%. For 0.375, 0.375×100%=37.5%. This preserves the value because percent is simply a different scale of representation.',
  'RATIO — IDENTIFY WHAT IS BEING COMPARED. If a class has 12 boys and 20 girls, boys:girls=12:20=3:5. But boys:total=12:32=3:8. The same data produce different ratios because the quantities being compared are different.',
  'RATIO MUST USE COMMON UNITS. Before forming a ratio, convert quantities to the same unit. For 2.5 m:50 cm, convert 2.5 m to 250 cm; ratio=250:50=5:1.',
  'PART-TO-PART AND PART-TO-WHOLE. If red:blue=2:3, red is 2 out of 5 total parts, so red fraction of the whole is 2/5 and red percentage is 40%. The ratio 2:3 must not be mistaken for fraction 2/3 of the total.',
  'SHARING IN A RATIO. Add the ratio parts first. To share ₦4,200 in the ratio 2:5, total parts=7. One part=₦4,200÷7=₦600. Shares are 2×₦600=₦1,200 and 5×₦600=₦3,000.',
  'FINDING A PERCENTAGE OF A QUANTITY. Convert the percentage to a fraction or decimal and multiply by the quantity. 15% of ₦2,400=15/100×2,400=₦360.',
  'PERCENTAGE INCREASE. First find the increase, then add it to the original amount. Increasing ₦800 by 12.5% gives increase=0.125×800=₦100, so new amount=₦900.',
  'PERCENTAGE DECREASE. First find the decrease, then subtract it. Decreasing ₦6,000 by 18% gives decrease=0.18×6,000=₦1,080, so new amount=₦4,920.',
  'FINDING THE WHOLE FROM A PART. If 30% of a number is 72, write 0.30×whole=72. Whole=72÷0.30=240. This is different from finding 30% of a known whole.',
  'QUANTITATIVE REASONING — READ THE RELATIONSHIP BEFORE CALCULATING. Ask whether the unknown is a fraction, decimal, percentage, ratio share, part or whole. The representation may change, but the actual quantity must remain equivalent.',
  'PERMANENT CHECKING RULE. Convert back whenever possible. If 3/8 becomes 37.5%, convert 37.5% back to 0.375 and then to 3/8. Ratio shares must add to the original total. Percentage increases/decreases must move the amount in the expected direction.'
 ],
 workedExamples:[
  'FRACTION TO DECIMAL AND PERCENTAGE. Convert 7/8. Decimal: 7÷8=0.875. Percentage: 0.875×100%=87.5%. Therefore 7/8=0.875=87.5%.',
  'FRACTION WITH EASY DENOMINATOR 100. Convert 3/20 to a percentage. Multiply numerator and denominator by 5: 3/20=15/100=15%. Decimal=0.15.',
  'DECIMAL TO FRACTION. Convert 0.45. 0.45=45/100. HCF(45,100)=5. Divide both by 5: 45/100=9/20.',
  'DECIMAL TO FRACTION — THREE DECIMAL PLACES. 0.375=375/1000. HCF=125. Divide: 375÷125=3 and 1000÷125=8. Therefore 0.375=3/8.',
  'PERCENTAGE TO FRACTION. 62.5%=62.5/100=0.625=625/1000=5/8. Check: 5÷8=0.625=62.5%.',
  'RATIO PART-TO-PART. A class has 12 boys and 20 girls. Boys:girls=12:20=3:5 after dividing both terms by 4.',
  'RATIO PART-TO-WHOLE. The same class has total 32. Boys:total=12:32=3:8. Therefore boys are 3/8 of the class, which is 37.5%.',
  'RATIO WITH UNIT CONVERSION. Simplify 2.5m:50cm. Convert 2.5m=250cm. Ratio=250:50=5:1.',
  'SHARING IN A RATIO. Share ₦4,200 in 2:5. Total parts=7. One part=4200÷7=600. First share=2×600=₦1,200. Second share=5×600=₦3,000. Check: 1,200+3,000=4,200.',
  'THREE-PART RATIO. Share 72kg in the ratio 1:2:3. Total parts=6. One part=72÷6=12kg. Shares: 12kg,24kg,36kg. Check total=72kg.',
  'PERCENTAGE OF QUANTITY. Find 15% of ₦8,000. 15/100×8,000=0.15×8,000=₦1,200.',
  'PERCENTAGE INCREASE. Increase 360 by 20%. Increase=0.20×360=72. New value=360+72=432.',
  'PERCENTAGE DECREASE. Reduce ₦2,400 by 15%. Reduction=0.15×2,400=₦360. New value=₂,400−₦360=₦2,040.',
  'FIND THE ORIGINAL WHOLE. 25% of a quantity is 45. Let whole=x. 0.25x=45, so x=45÷0.25=180.',
  'MIXED CONTEXT. In a survey, 18 of 30 learners prefer football. Fraction=18/30=3/5. Decimal=0.6. Percentage=60%. Prefer football : do not prefer=18:12=3:2. Notice that part-to-whole ratio 18:30 differs from part-to-part ratio 18:12.'
 ],
 misconceptions:[
  'treating a fraction a/b as automatically the same as part-to-part ratio a:b without checking context',
  'adding or subtracting numerator and denominator when converting forms',
  'multiplying by 100 twice when converting a decimal to a percentage',
  'forgetting to simplify a fraction or ratio',
  'forming a ratio before converting quantities to the same unit',
  'simplifying only one term of a ratio',
  'using the number of ratio parts as though it were the original quantity',
  'confusing percentage increase with the final amount',
  'subtracting a percentage number directly from a money amount instead of finding the percentage of the base quantity',
  'using the new amount rather than the original amount as the base unless the problem explicitly requires it'
 ],
 guidedPractice:[
  'Convert 5/8 to decimal and percentage and verify by converting back.',
  'Convert 0.72 to a fraction in lowest terms and to a percentage.',
  'Convert 37.5% to a decimal and fraction.',
  'Simplify 18:30 and state the HCF used.',
  'Write 3m:75cm as a simplified ratio.',
  'A class has boys:girls=5:3 and 48 learners. Find boys, girls and the percentage who are girls.',
  'Share ₦9,600 in the ratio 3:5.',
  'Find 7.5% of ₦24,000.',
  'Increase 640 by 12.5%.',
  'Decrease ₦15,000 by 18%.',
  'If 40% of a number is 96, find the number.',
  'In a club, 21 of 35 members attended. Express attendance as fraction, decimal, percentage and attended:absent ratio.'
 ],
 independentPractice:[
  'Convert 11/20 to decimal and percentage.',
  'Convert 7/16 to decimal and percentage.',
  'Convert 0.35 to a fraction in lowest terms and a percentage.',
  'Convert 0.625 to a fraction and percentage.',
  'Convert 72% to a simplified fraction and decimal.',
  'Convert 12.5% to a fraction and decimal.',
  'Simplify 42:63.',
  'Simplify 2.4m:80cm.',
  'A bag contains 18 red and 27 blue counters. Find red:blue, red:total and red as a percentage of total.',
  'Share ₦18,000 in the ratio 2:3.',
  'Share 84kg in the ratio 2:3:7.',
  'Find 18% of ₦35,000.',
  'Increase 1,250 by 16%.',
  'Decrease 4,800 by 22.5%.',
  'A price rises from ₦5,000 by 12%. Find the increase and new price.',
  'After a 20% decrease, a quantity becomes 320. Find the original quantity.',
  '45 learners represent 75% of a class. Find the full class size.',
  'A school recorded attendance of 270 out of 300 learners. Express attendance as a simplified fraction, decimal and percentage.',
  'A recipe uses flour:sugar=5:2. If 750g flour is used, find the sugar required.',
  'Write one real-life situation where the ratios part-to-part and part-to-whole would give different answers and calculate both.'
 ],
 mastery:{criterion:'Learner converts accurately among fractions, ratios, decimals and percentages, distinguishes ratio contexts, solves ratio sharing and percentage change/whole problems, and reaches at least 80% with reverse checks and correct base quantities.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-basic-operations-derived-operations-1',classLevel:'JSS2',subject:'Mathematics',topic:'Transactions in the homes and offices',source:{authority:'NERDC',url:sourceUrl,page:20},
 objectives:['Solve household and office arithmetic problems','Solve simple commercial arithmetic involving profit, interest, discount and commission'],
 prerequisites:['percentages and decimals','addition/subtraction of money','multiplication/division','reading bills, tables and money notation'],
 teaching:[
  'START WITH THE FINANCIAL WORDS. Cost price (CP) is what an item costs the seller. Selling price (SP) is what the customer pays. Marked price (MP) is the price written before any discount. Profit occurs when SP>CP; loss occurs when SP<CP. Principal (P) is the original sum invested or borrowed. Rate (R) is the percentage per stated time, and time (T) must match that rate.',
  'HOUSEHOLD BUDGET. A budget plans how income will be used. Total expenditure is the sum of all planned expenses. Balance=income−expenditure. A positive balance is a surplus; a negative balance is a deficit and means spending exceeds income.',
  'READING BILLS AND RECORDS. Before calculating, identify the unit, quantity used, rate per unit, fixed charge, tax/levy if present, previous balance and total due. Do not multiply a rate by the wrong quantity or ignore fixed charges.',
  'PROFIT. Profit=SP−CP. Profit percentage is normally based on COST PRICE: profit%=profit/CP×100. State the formula before substituting so the denominator is not guessed.',
  'FINDING SELLING PRICE FROM PROFIT. If profit or profit% is given, first calculate the profit from CP, then SP=CP+profit. For a 20% profit on ₦8,000, profit=0.20×8,000=₦1,600; SP=₦9,600.',
  'LOSS. Loss=CP−SP. Loss%=loss/CP×100. Because the seller originally spent CP, the percentage loss is compared with that original cost unless a question states otherwise.',
  'FINDING SELLING PRICE FROM LOSS. If loss%=15% on CP ₦24,000, loss=0.15×24,000=₦3,600; SP=24,000−3,600=₦20,400.',
  'SIMPLE INTEREST — MEANING FIRST. Simple interest is calculated on the original principal only throughout the stated time. Interest does not become part of the principal for the next period.',
  'SIMPLE INTEREST FORMULA. I=PRT/100 when R is a percentage per annum and T is measured in years. Amount A=P+I. Every symbol must be identified before substitution.',
  'TIME CONVERSION IN INTEREST. If the rate is per annum but time is in months, convert months to years. Eighteen months=18/12=1.5 years. Do not use T=18 with an annual rate.',
  'FINDING AN UNKNOWN IN SIMPLE INTEREST. The same formula can be rearranged. If P, I and T are known, R=100I/(PT). If P, I and R are known, T=100I/(PR). Substitute with units and check that the result is sensible.',
  'DISCOUNT. Discount is the amount removed from the marked price. Discount=discount rate×MP. Selling price after discount=MP−discount. A discount must reduce the amount, never increase it.',
  'FINDING MARKED PRICE FROM A DISCOUNTED PRICE. If an item is sold at 80% of its marked price because of a 20% discount, SP=0.80MP. Therefore MP=SP/0.80.',
  'COMMISSION. Commission is payment calculated from a stated base such as sales. Commission=commission rate×sales. If an employee also receives a fixed salary, total earnings=fixed salary+commission.',
  'FINDING SALES FROM COMMISSION. If 5% commission equals ₦12,500, then 0.05×sales=12,500, so sales=₦250,000.',
  'COMBINED TRANSACTIONS. Real questions may combine discount and profit. Keep the stages separate: marked price→discounted selling price, then compare selling price with cost price to determine profit/loss.',
  'PERMANENT FINANCIAL CHECK. Write the base before every percentage. Profit/loss percentage uses CP by default; discount uses MP; commission uses stated sales/base; interest uses P. Then ask whether the final amount moved in the expected direction.'
 ],
 workedExamples:[
  'BUDGET — SURPLUS. Monthly income=₦180,000. Expenses: rent ₦45,000, food ₦62,500, transport ₦18,000, utilities ₦12,500, school needs ₦22,000. Total expenditure=45,000+62,500+18,000+12,500+22,000=₦160,000. Balance=180,000−160,000=₦20,000 surplus.',
  'BUDGET — DEFICIT. Income=₦95,000; planned expenses total ₦103,500. Balance=95,000−103,500=−₦8,500. The negative sign means the plan exceeds income by ₦8,500.',
  'PROFIT AND PROFIT %. CP=₦8,000, SP=₦9,600. Profit=9,600−8,000=₦1,600. Profit%=1,600/8,000×100=20%. Check: 20% of 8,000=1,600.',
  'FIND SP FROM PROFIT %. CP=₦12,500, profit=16%. Profit=0.16×12,500=₦2,000. SP=12,500+2,000=₦14,500.',
  'LOSS AND LOSS %. CP=₦10,000, SP=₦8,500. Loss=10,000−8,500=₦1,500. Loss%=1,500/10,000×100=15%.',
  'FIND SP FROM LOSS %. CP=₦24,000, loss=15%. Loss=0.15×24,000=₦3,600. SP=24,000−3,600=₦20,400.',
  'SIMPLE INTEREST — YEARS. P=₦50,000,R=8% p.a.,T=2 years. I=50,000×8×2/100=₦8,000. Amount=50,000+8,000=₦58,000.',
  'SIMPLE INTEREST — MONTHS. P=₦120,000,R=7.5% p.a.,T=18 months=1.5 years. I=120,000×7.5×1.5/100=₦13,500. Amount=₦133,500.',
  'FIND THE RATE. P=₦80,000,I=₦12,000,T=2 years. R=100I/(PT)=100×12,000/(80,000×2)=7.5% p.a.',
  'DISCOUNT. MP=₦25,000, discount=12%. Discount amount=0.12×25,000=₦3,000. SP=25,000−3,000=₦22,000.',
  'FIND DISCOUNT RATE. MP=₦30,000 and discount amount=₦3,600. Rate=3,600/30,000×100=12%.',
  'FIND MARKED PRICE. An item sells for ₦16,000 after 20% discount. Customer pays 80% of MP, so 0.80MP=16,000. MP=16,000/0.80=₦20,000.',
  'COMMISSION. Sales=₦240,000, rate=10%. Commission=0.10×240,000=₦24,000.',
  'SALARY PLUS COMMISSION. Fixed salary=₦55,000, commission=4% of ₦300,000 sales. Commission=₦12,000. Total earnings=55,000+12,000=₦67,000.',
  'FIND SALES FROM COMMISSION. Commission=₦12,500 at 5%. Sales=12,500/0.05=₦250,000.',
  'BILL WITH FIXED CHARGE. Electricity usage=185 units at ₦72 per unit plus fixed charge ₦1,500. Usage charge=185×72=₦13,320. Total=13,320+1,500=₦14,820.',
  'COMBINED DISCOUNT AND PROFIT. MP=₦15,000, discount=10%, CP=₦11,000. Discount=₦1,500; SP=₦13,500. Profit=13,500−11,000=₦2,500. Profit%=2,500/11,000×100≈22.7%. The discount base was MP, but the profit percentage base was CP.',
  'REALISTIC OFFICE PURCHASE. An office buys 8 printer cartridges at ₦7,500 each and pays delivery of ₦4,000. Item cost=8×7,500=₦60,000. Total cost=60,000+4,000=₦64,000. The delivery charge must not be omitted when the question asks total expenditure.'
 ],
 misconceptions:[
  'confusing cost price, selling price and marked price',
  'calculating profit percentage using selling price by default',
  'using marked price as the base for profit percentage',
  'adding a loss to cost price instead of subtracting it',
  'adding discount to marked price instead of subtracting it',
  'calculating discount from selling price when the rate is stated on marked price',
  'using months directly as years in simple-interest formula',
  'using compound-interest reasoning in a simple-interest question',
  'forgetting amount=P+I after calculating interest',
  'calculating commission on the wrong base amount',
  'ignoring fixed charges, previous balance or units in bills',
  'treating a negative budget balance as money left over',
  'mixing the bases in a combined discount-and-profit question'
 ],
 guidedPractice:[
  'Prepare a budget from ₦150,000 income and expenses of ₦40,000, ₦52,500, ₦18,000, ₦12,500 and ₦15,000. State surplus/deficit.',
  'An item costs ₦6,500 and sells for ₦7,800. Find profit and profit percentage.',
  'An article costing ₦18,000 is sold at a 12% loss. Find the loss and selling price.',
  'Find simple interest and amount on ₦75,000 at 6% p.a. for 3 years.',
  'Find simple interest on ₦96,000 at 10% p.a. for 9 months.',
  'An investment of ₦50,000 earns ₦7,500 simple interest in 3 years. Find the annual rate.',
  'Find the selling price after 15% discount on ₦32,000 marked price.',
  'An item sells for ₦27,000 after a 10% discount. Find its marked price.',
  'Find 4.5% commission on sales of ₦480,000.',
  'An agent earns ₦18,000 commission at 6%. Find the sales value.',
  'A bill charges 240 units at ₦65 each plus ₦1,800 fixed charge. Find total due.',
  'An item marked ₦20,000 gets 10% discount. Its cost price is ₦15,000. Find the actual selling price, profit and profit percentage.'
 ],
 independentPractice:[
  'A family earns ₦220,000 monthly and plans expenses totalling ₦197,500. Find the balance and interpret it.',
  'A household earns ₦125,000 but plans ₦132,800 expenditure. Find and interpret the balance.',
  'CP=₦14,400 and SP=₦17,280. Find profit and profit percentage.',
  'CP=₦25,000 and SP=₦21,250. Find loss and loss percentage.',
  'Find the SP of an item costing ₦48,000 if a 25% profit is required.',
  'Find the SP of an item costing ₦36,000 if sold at 12.5% loss.',
  'Find simple interest and amount on ₦90,000 at 7% p.a. for 4 years.',
  'Find simple interest on ₦160,000 at 9% p.a. for 15 months.',
  'A principal of ₦120,000 earns ₦27,000 in 2.5 years simple interest. Find the rate.',
  'At 8% p.a., how long will ₦50,000 take to earn ₦12,000 simple interest?',
  'Find the discount and selling price when MP=₦45,000 and discount rate=18%.',
  'An item sells for ₦34,000 after 15% discount. Find MP.',
  'A salesperson earns 7% commission on ₦650,000 sales. Find commission.',
  'A salesperson receives ₦60,000 basic salary plus 3.5% of ₦800,000 sales. Find total earnings.',
  'Commission is ₦24,000 at 4%. Find sales.',
  'A water bill charges 32m³ at ₦480 per m³ plus service fee ₦2,250. Find total bill.',
  'An invoice contains 12 notebooks at ₦1,250 each, 5 files at ₦800 each and delivery ₦2,000. Find total invoice amount.',
  'An item marked ₦50,000 is discounted by 20%. If CP=₦32,000, find SP, profit and profit percentage.',
  'A trader buys an item for ₦25,000, marks it 40% above cost, then gives a 10% discount on marked price. Find MP, final SP and actual profit percentage.',
  'Explain why a 20% discount and a 20% profit cannot automatically be cancelled when they are calculated on different base amounts.'
 ],
 mastery:{criterion:'At least 80% across household budgets, bills, profit/loss, simple interest, discount and commission, with every percentage base identified explicitly and final money answers interpreted correctly.',status:'DEEP_WHEN_PASSED'},boardReady:true
}
{
 topicId:'nerdc-jss2-math-basic-operations-derived-operations-2',classLevel:'JSS2',subject:'Mathematics',topic:'Approximation',source:{authority:'NERDC',url:sourceUrl,page:20},
 objectives:['Approximate numbers to a stated degree of accuracy','Solve quantitative-reasoning problems involving approximation'],
 prerequisites:['place value','JSS1 estimation and approximation','decimal notation'],
 teaching:['Decimal places count digits to the right of the decimal point. Look at the next digit: 0–4 leaves the retained digit unchanged; 5–9 increases it by one.','Significant figures begin at the first non-zero digit. Zeros between non-zero digits are significant; leading zeros are not.','For a requested accuracy, state the rounded value clearly and preserve placeholder zeros when they communicate place value.','Use approximation to judge whether an exact answer is reasonable. In applied problems, round only at the requested stage to reduce accumulated error.'],
 workedExamples:['47.386 to 2 d.p.=47.39.','0.005786 to 2 s.f.=0.0058.','83,649 to 2 s.f.=84,000.','19.8×5.03≈20×5=100, so an exact calculator result near 100 is plausible.'],
 misconceptions:['counting leading zeros as significant figures','rounding every intermediate step unnecessarily','confusing 2 d.p. with 2 s.f.','dropping place-holding zeros so 84,000 becomes 84'],
 guidedPractice:['Round 6.7845 to 3 d.p.; 0.009746 to 2 s.f.; 528,941 to 3 s.f.; estimate 39.7×2.98.'],
 independentPractice:['Ten mixed rounding questions plus three quantitative-reasoning problems requiring an estimate and an explanation of reasonableness.'],
 mastery:{criterion:'Learner distinguishes decimal places from significant figures and gets at least 8 of 10 rounding/estimation items correct.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-basic-operations-derived-operations-3',classLevel:'JSS2',subject:'Mathematics',topic:'Multiplication and division of directed numbers',source:{authority:'NERDC',url:sourceUrl,page:20},
 objectives:['Obtain squares and square roots from supplied square/square-root tables','Interpret information from tables, charts, records and schedules','Multiply directed numbers','Divide directed numbers'],
 prerequisites:['JSS1 addition/subtraction of directed numbers','multiplication tables','meaning of positive and negative values'],
 teaching:['For multiplication and division, equal signs give a positive result and unlike signs give a negative result. Determine the sign separately from the magnitude.','The sign rule follows repeated patterns: for example 3×(-2)=-6, 2×(-2)=-4, 1×(-2)=-2, 0×(-2)=0, so (-1)×(-2)=+2 to preserve the constant difference.','Division reverses multiplication: if (-4)×3=-12, then -12÷3=-4 and -12÷(-4)=3.','A square/square-root table is a lookup tool, not a substitute for understanding. Read the table title and headings first, locate the given number or required entry using the row/column convention printed on that table, record the value with the stated precision, then verify that a claimed square root is reasonable by squaring or by bracketing it between nearby perfect squares.','In tables, charts and schedules, identify the row/column headings and units before extracting or combining values.'],
 workedExamples:['If a supplied square-root table gives √2.25=1.50, check: 1.50²=2.25. For a non-perfect value, first bracket it; for example 49<50<64 means 7<√50<8, so any table value must lie between 7 and 8.','(-7)×6=-42.','(-8)×(-5)=40.','54÷(-9)=-6.','A temperature changes by -3°C each hour for 4 hours: total change=4×(-3)=-12°C.'],
 misconceptions:['reading a numerical table without checking its headings or precision','accepting an impossible square-root table value without a reasonableness check','always making a product negative when a negative number appears','using addition sign rules for multiplication','losing the sign when dividing','reading chart entries without checking units'],
 guidedPractice:['Use the square/square-root table supplied in class to obtain two values and verify each by estimation or squaring; then evaluate (-9)(4), (-6)(-7), 72÷(-8), -81÷(-9) and explain each sign.'],
 independentPractice:['Twelve directed-number products/quotients plus three context/table problems.'],
 mastery:{criterion:'At least 85% accuracy and learner can verbally justify the sign of every product/quotient.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-algebraic-processes-algebraic-operations-1',classLevel:'JSS2',subject:'Mathematics',topic:'Algebraic expressions',source:{authority:'NERDC',url:sourceUrl,page:21},
 objectives:['Expand algebraic expressions','Factorize simple algebraic expressions','Expand and factorize quadratic expressions','Solve quantitative-reasoning problems','Simplify algebraic fractions with monomial denominators','Interpret and solve word problems leading to simple algebraic fractions'],
 prerequisites:['JSS1 algebraic symbols','collecting like terms','distributive law','common factors and fractions'],
 teaching:['Expansion removes brackets by multiplying every term inside by the factor outside. Factorization reverses expansion by extracting a common factor or finding factors that reproduce the expression.','For quadratics, first identify the standard form ax²+bx+c. Define a as the coefficient of x², b as the coefficient of x, and c as the constant. If bx is split as mx+nx, then m+n=b because the split terms must still combine to bx; for grouping to rebuild the quadratic, mn=ac. So compare factor pairs until BOTH sum b and product ac are satisfied. When a=1, ac=c. Check the final factors by expanding.','The NERDC quadratic box/grid method makes the same distributive structure visible. For expansion, place one factor along the top and the other down the side of a 2×2 box, multiply to fill all cells, then collect like terms. For factorisation, place ax² and c in opposite cells, find the two middle terms whose sum is bx and product is acx², fill the remaining cells, then take common factors from rows and columns. The box is a representation of the distributive law, not a different rule.','Algebraic fractions obey ordinary fraction rules. Factor numerator/denominator where useful and cancel only common factors, never separate terms joined by addition.','Translate words before calculating: “three more than x” is x+3; “half of y” is y/2; “the sum divided by p” requires brackets around the sum.'],
 workedExamples:['3(x+4)-2(x-1)=3x+12-2x+2=x+14.','6x+9=3(2x+3).','x²+5x+6=(x+2)(x+3). In a 2×2 box, x² and 6 occupy opposite cells; split 5x as 2x+3x, then the row/column common factors reveal (x+2)(x+3).','(6x²+9x)/(3x)=2x+3 for x≠0.'],
 misconceptions:['multiplying the outside factor by only the first term','canceling x from (x+3)/x','factorizing x²+5x+6 with numbers whose product/sum do not match','treating the quadratic box as a memorised picture without checking that its four cells expand back to the original expression','omitting brackets when translating grouped word phrases'],
 guidedPractice:['Expand 4(2x-3)+5; factorize 8y+12; factorize x²+7x+12; simplify (10a²-5a)/(5a).'],
 independentPractice:['Six expansion/factorization tasks, four algebraic-fraction tasks and two word-to-algebra problems, each followed by a verification step.'],
 mastery:{criterion:'Learner scores at least 80% and verifies factorization by expansion and fraction simplification by identifying valid common factors.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-algebraic-processes-algebraic-operations-2',classLevel:'JSS2',subject:'Mathematics',topic:'Simple equations',source:{authority:'NERDC',url:sourceUrl,page:22},
 objectives:['Solve problems involving simple equations'],
 prerequisites:['JSS1 simple equations','inverse operations','expansion and collecting like terms'],
 teaching:['An equation states that two expressions are equal. Preserve equality by performing the same valid operation on both sides.','Simplify each side first, remove brackets where needed, collect variable terms on one side and constants on the other, then divide by the coefficient.','Fractions can often be cleared by multiplying every term on both sides by the LCM of denominators.','Always substitute the proposed answer into the original equation; equality must be restored.'],
 workedExamples:['3n-4=2n+1 ⇒ n=5; check:11=11.','5(x-2)=3x+8 ⇒5x-10=3x+8⇒2x=18⇒x=9.','x/3+2=7 ⇒x/3=5⇒x=15.'],
 misconceptions:['moving a term across the equals sign without understanding the inverse operation','changing only one side of an equation','dividing one term but not the entire side','checking in a rearranged line rather than the original equation'],
 guidedPractice:['Solve 4y+7=2y+19 and 3(2p-1)=15; verify both.'],
 independentPractice:['Ten equations of increasing difficulty including brackets and simple fractions, plus two short word problems.'],
 mastery:{criterion:'At least 8 of 10 equations correct, with valid transformations and successful substitution checks.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-algebraic-processes-algebraic-operations-3',classLevel:'JSS2',subject:'Mathematics',topic:'Linear inequalities',source:{authority:'NERDC',url:sourceUrl,page:22},
 objectives:['Identify a linear inequality in one variable','Solve linear inequalities in one variable','Represent solution sets on a number line','Solve word problems involving linear inequalities'],
 prerequisites:['simple equations','directed numbers','number-line representation'],
 teaching:['An inequality compares quantities using <, >, ≤ or ≥. Its solution is usually a set of values rather than one value.','Solve similarly to an equation, but multiplying or dividing both sides by a negative number reverses the inequality sign.','On a number line, an open circle means the endpoint is excluded (< or >); a filled circle means included (≤ or ≥). Shade in the direction containing the solutions.','Translate language carefully: “at least” means ≥, “at most” means ≤, “more than” means > and “less than” means <.'],
 workedExamples:['3x+2<14 ⇒3x<12⇒x<4.','-2y≥8 ⇒ y≤-4 because division by -2 reverses the sign.','A bus carries at most 45 people: if x is passengers, x≤45.'],
 misconceptions:['forgetting to reverse the sign after multiplying/dividing by a negative','using a filled circle for a strict inequality','treating the answer as a single value','misreading “at least” as ≤'],
 guidedPractice:['Solve 5x-7≤18 and -3p<12; draw both solution sets on number lines.'],
 independentPractice:['Eight symbolic inequalities and four word problems requiring translation, solution and number-line representation.'],
 mastery:{criterion:'Learner solves and graphs at least 80% correctly and explains when and why the inequality sign reverses.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-algebraic-processes-algebraic-operations-4',classLevel:'JSS2',subject:'Mathematics',topic:'Graphs',source:{authority:'NERDC',url:sourceUrl,page:23},
 objectives:['Identify x-axis and y-axis','Plot points on the Cartesian plane','Prepare tables of values','Plot graphs of linear equations in two variables','Interpret plotted graphs','Plot linear graphs from real-life situations','Solve quantitative-reasoning problems using graphs'],
 prerequisites:['directed numbers','substitution in algebra','reading tables and scales'],
 teaching:['The Cartesian plane has a horizontal x-axis and vertical y-axis meeting at the origin (0,0). Coordinates are written (x,y): move in x first, then y.','To graph y=mx+c, choose convenient x-values, calculate y, make a table, plot the ordered pairs and draw the straight line through them.','A graph scale must be uniform on each axis, though x- and y-axes may use different scales. Label axes, units and title when context is involved.','Interpret a graph by connecting coordinates to meaning: slope shows rate of change, intercepts show values where an axis quantity is zero, and a horizontal segment may show no change.'],
 workedExamples:['For y=2x+1 and x=-1,0,1,2, y=-1,1,3,5; plot (-1,-1),(0,1),(1,3),(2,5).','Point (-3,2) lies 3 units left and 2 units up from the origin.','If a distance-time graph goes from (0 h,0 km) to (2 h,120 km), average speed over that interval is 60 km/h.'],
 misconceptions:['reversing x and y coordinates','using unequal, unmarked scale intervals','joining unrelated discrete points when a continuous line is not justified','reading slope without considering axis units'],
 guidedPractice:['Make a table and graph y=3x-2 for x=-1,0,1,2; identify the y-intercept and interpret the slope.'],
 independentPractice:['Plot two linear equations, interpret six features from a supplied distance-time/item-price dataset, and answer two quantitative-reasoning graph questions.'],
 mastery:{criterion:'Accurate axes/scales/points and at least 80% correct interpretation across algebraic and real-life graphs.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-mensuration-and-geometry-shapes-1',classLevel:'JSS2',subject:'Mathematics',topic:'Plane figures/Shapes',source:{authority:'NERDC',url:sourceUrl,page:24},
 objectives:['State properties of parallelogram, rhombus and kite','Identify these shapes in the environment','Draw plane objects to scale','Convert actual lengths to scale lengths and vice versa','Apply scale drawing to measurement problems','Solve quantitative-reasoning problems involving shapes and scale drawing'],
 prerequisites:['JSS1 plane shapes','measurement and unit conversion','ratio'],
 teaching:['A parallelogram has both pairs of opposite sides parallel and equal; opposite angles are equal and diagonals bisect each other.','A rhombus is a parallelogram with all four sides equal; its diagonals are perpendicular and bisect opposite angles. A kite has two pairs of adjacent equal sides, with one pair of opposite angles equal.','A scale such as 1:100 means 1 unit on the drawing represents 100 of the same units in reality. Convert units before applying the scale.','For “1 cm represents 5 m”, keep the stated correspondence visible throughout the calculation to avoid unit errors.'],
 workedExamples:['At scale 1:200, a real 8 m wall=800 cm/200=4 cm on the drawing.','A 6.5 cm map distance at 1 cm:4 km represents 26 km.','A quadrilateral with all sides equal and both pairs of opposite sides parallel is a rhombus.'],
 misconceptions:['assuming every kite is a rhombus','mixing metres and centimetres inside a ratio','multiplying when the scale requires division or vice versa','describing a rhombus as needing right angles'],
 guidedPractice:['Classify three quadrilaterals from properties; convert 12 m to drawing length at 1:300; recover real length from 7 cm at 1 cm:2.5 m.'],
 independentPractice:['A property table for parallelogram/rhombus/kite plus six scale-drawing problems and one room-layout application.'],
 mastery:{criterion:'Learner identifies properties without overgeneralising and solves at least 5 of 6 scale problems with correct units.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-mensuration-and-geometry-shapes-2',classLevel:'JSS2',subject:'Mathematics',topic:'Angles',source:{authority:'NERDC',url:sourceUrl,page:25},
 objectives:['Find the sum of angles in triangles','Find the sum of angles in quadrilaterals','Find the sum of interior angles of polygons','Distinguish angles of elevation and depression','Use elevation/depression with scale drawing to calculate heights/distances','Relate angles of elevation and depression','Solve quantitative-reasoning problems involving angles'],
 prerequisites:['JSS1 angle types and measurement','parallel-line angle facts','basic scale drawing'],
 teaching:['The interior angles of a triangle total 180° and of a quadrilateral total 360°. Splitting an n-sided polygon into n−2 triangles gives interior-angle sum (n−2)×180°.','An angle of elevation is measured upward from a horizontal line of sight; an angle of depression is measured downward from a horizontal line of sight.','When the observer and target horizontals are parallel, an angle of depression can equal the corresponding angle of elevation through alternate-angle relationships.','At JSS2, scale drawings can model height/distance: draw the horizontal, construct the stated angle accurately, use the selected scale and measure the missing length.'],
 workedExamples:['Pentagon angle sum=(5−2)×180°=540°.','A regular hexagon has each interior angle 720°/6=120°.','If a scale drawing uses 1 cm:10 m and the measured height is 4.6 cm, actual height=46 m.'],
 misconceptions:['using n×180° for polygon angle sum','measuring elevation from the vertical','assuming every polygon is regular','forgetting to convert measured drawing length back through the scale'],
 guidedPractice:['Find unknown angles in a triangle and quadrilateral; compute sums for 7- and 10-sided polygons; sketch and label elevation/depression.'],
 independentPractice:['Eight polygon/angle problems plus two scale-drawing elevation/depression problems with measured results and units.'],
 mastery:{criterion:'At least 80% and learner can justify the polygon formula and correctly distinguish elevation from depression.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-mensuration-and-geometry-shapes-3',classLevel:'JSS2',subject:'Mathematics',topic:'Bearing',source:{authority:'NERDC',url:sourceUrl,page:26},
 objectives:['Identify cardinal points','Locate objects using compass and three-digit bearings','Find distances between objects using scale drawing'],
 prerequisites:['angles measured clockwise','protractor use','scale drawing'],
 teaching:['The four major cardinal points are N,E,S,W; minor points include NE,SE,SW,NW. Compass directions describe sectors, while three-digit bearings give precise clockwise angles from North.','A three-digit bearing always has three figures: east is 090°, south 180°, west 270°. To locate an object, draw North at the starting point, measure clockwise, then draw the ray.','Reverse bearings differ by 180°: add 180° if the original is below 180°, otherwise subtract 180°.','When scale drawing is involved, determine direction first, measure/draw the scaled distance second, and convert back to the real distance only at the end.'],
 workedExamples:['A point due southeast has compass direction SE; an exact direction might be 135°.','Bearing of B from A is 065°; bearing of A from B=245°.','At scale 1 cm:5 km, a plotted separation of 7.4 cm represents 37 km.'],
 misconceptions:['measuring bearings anticlockwise','starting a bearing from East instead of North','writing 65° instead of 065°','assuming the reverse bearing is obtained by changing N to S without checking the exact angle'],
 guidedPractice:['Draw bearings 040°,125°,270° from a point; find their reverse bearings; solve one scale-distance problem.'],
 independentPractice:['Six compass/three-digit bearing conversions, four reverse-bearing questions and two scale-drawing navigation problems.'],
 mastery:{criterion:'Learner measures/writes bearings correctly to three digits and solves at least 80% of direction-distance tasks.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-mensuration-and-geometry-shapes-4',classLevel:'JSS2',subject:'Mathematics',topic:'Construction',source:{authority:'NERDC',url:sourceUrl,page:26},
 objectives:['Construct triangles from two sides and included angle','Construct triangles from two angles and the included side','Construct triangles from three sides','Bisect a given angle'],
 prerequisites:['ruler, compass and protractor use','triangle vocabulary','accurate measurement'],
 teaching:['A mathematical construction follows enough given measurements to determine a unique figure. Draw a clear base first and keep construction arcs visible.','For SAS, draw one given side, construct the included angle at the correct endpoint, mark the second side length, then join the remaining vertices.','For ASA, draw the included side, construct each given angle at its endpoint and extend the rays until they meet. For SSS, draw one side, use compass arcs of the other two side lengths; their intersection locates the third vertex.','To bisect an angle using a compass, draw an arc from the vertex cutting both arms; from those cut points draw equal-radius arcs that intersect; join the vertex to the intersection.'],
 workedExamples:['Construct ΔABC with AB=6 cm, AC=5 cm and ∠BAC=70° (SAS).','Construct ΔPQR with PQ=7 cm, ∠P=50°, ∠Q=65° (ASA).','Construct a triangle of sides 5 cm,6 cm,8 cm using SSS; check each side afterward.'],
 misconceptions:['using the wrong angle in an SAS construction','changing compass radius while creating the angle bisector intersection','erasing all construction evidence','attempting impossible SSS data where two smaller sides do not exceed the largest'],
 guidedPractice:['Complete one SAS triangle and bisect a 76° angle; verify the two halves with a protractor.'],
 independentPractice:['Construct one SAS, one ASA and one SSS triangle and two angle bisectors; label all given dimensions and verification measurements.'],
 mastery:{criterion:'All required constructions are geometrically valid, labelled, accurate within normal drawing tolerance and supported by visible construction steps.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-everyday-statistics-data-collection-and-presentation-1',classLevel:'JSS2',subject:'Mathematics',topic:'Data presentation',source:{authority:'NERDC',url:sourceUrl,page:27},
 objectives:['Present data in ordered form','Construct frequency tables from familiar data','Read information from pie charts','Calculate and interpret the interquartile range (IQR)','Use box plots to organise, compare and interpret data distributions'],
 prerequisites:['JSS1 data collection/presentation','fractions, ratios and percentages','median and ordered data','angles and protractor use'],
 teaching:['Raw data become easier to interpret when ordered and summarised. A frequency table records each value or category and how often it occurs; total frequency must equal the number of observations.','For a pie chart, sector angle=(category frequency/total frequency)×360°. The sector angles should total 360°; percentages should total 100% apart from rounding. To read a pie chart, reverse the relationship: frequency=(sector angle/360°)×total when the total is known.','Quartiles divide an ORDERED data set into four parts. AVORA uses this school convention consistently: find the median Q2; for an odd number of observations exclude that overall median before finding the median of the lower half (Q1) and upper half (Q3); for an even number split the ordered data equally into lower and upper halves.','The interquartile range is IQR=Q3−Q1. It measures the spread of the middle 50% of the data. A larger IQR means the central half is more spread out; a smaller IQR means it is more tightly grouped. Compare IQRs only after checking that the datasets and units are meaningfully comparable.','A box plot is built from the five-number summary: minimum, Q1, median (Q2), Q3 and maximum. Draw a number-line scale; make a box from Q1 to Q3; draw a line at the median; extend whiskers to the minimum and maximum. The box length represents the IQR.','To compare two box plots, discuss centre (medians), spread of the middle half (IQRs), overall range and visible skew/unequal whiskers. Do not invent causes that the plot does not establish.','Statistical interpretation should state what the data support. Always read labels, units, time period and source before drawing conclusions; computer-generated box plots still require the learner to understand what the five-number summary means.'],
 workedExamples:['Data 2,3,2,5,3,2 ordered gives 2,2,2,3,3,5; frequencies are 2→3, 3→2, 5→1.','In a survey of 40 learners, 10 choose football: sector angle=10/40×360°=90°. A 72° sector in a pie chart of 150 people represents 72/360×150=30 people.','For 2,4,5,7,8,10,13,15: Q2=(7+8)/2=7.5. Lower half 2,4,5,7 gives Q1=(4+5)/2=4.5. Upper half 8,10,13,15 gives Q3=(10+13)/2=11.5. IQR=11.5−4.5=7.','The same data have five-number summary 2,4.5,7.5,11.5,15. A box plot places whiskers at 2 and 15, a box from 4.5 to 11.5 and a median line at 7.5.','Class A has median 52 and IQR 8; Class B has median 55 and IQR 18. B has the higher central value but its middle 50% is more spread out. That description is supported; saying why B varies more would need extra evidence.'],
 misconceptions:['using frequency directly as degrees','forgetting that pie sectors must sum to 360°','finding quartiles before ordering the data','using range (maximum−minimum) when the question asks for IQR (Q3−Q1)','including the single overall median in both halves under the stated odd-data convention','drawing a box plot without a uniform numerical scale','claiming causation from a descriptive chart or box plot'],
 guidedPractice:['Order 3,5,5,6,8,9,11,13; find Q1, median, Q3 and IQR; then sketch its box plot on a labelled scale.','Given two five-number summaries, compare their medians, IQRs and overall ranges using complete sentences.'],
 independentPractice:['Create a frequency table and read a supplied pie chart; calculate quartiles and IQR for three datasets; construct two box plots on a common scale and write a justified comparison of centre and spread.'],
 mastery:{criterion:'Learner orders data correctly, constructs consistent frequency/pie representations, computes Q1/Q2/Q3 and IQR accurately, builds a valid box plot and makes evidence-based comparisons at 80%+.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss2-math-everyday-statistics-data-collection-and-presentation-2',classLevel:'JSS2',subject:'Mathematics',topic:'Probability',source:{authority:'NERDC',url:sourceUrl,page:27},
 objectives:['Discuss chance events in everyday life','Determine probabilities of simple events','Apply probability/chance to everyday situations'],
 prerequisites:['fractions and ratios','data interpretation','counting equally likely outcomes'],
 teaching:['Probability measures how likely an event is, from 0 (impossible) to 1 (certain). For equally likely outcomes, P(event)=favourable outcomes/total possible outcomes.','An experiment is the action, an outcome is a possible result, and an event is one or more outcomes of interest. List the sample space before counting.','The complement of an event is “not the event”; P(not A)=1−P(A). Experimental probability uses observed relative frequency and may differ from theoretical probability in a small number of trials.','Probability supports decisions under uncertainty, but it does not guarantee what happens in one trial. A 70% chance does not mean an event must happen.'],
 workedExamples:['Fair coin: sample space {H,T}; P(H)=1/2.','Fair die: P(number greater than 4)=2/6=1/3.','Bag with 3 red,2 blue,5 green counters: P(blue)=2/10=1/5; P(not blue)=4/5.','If rain occurred on 18 of 60 comparable recorded days, experimental probability=18/60=0.3.'],
 misconceptions:['putting total outcomes over favourable outcomes','assuming past independent outcomes force the next result','treating experimental and theoretical probability as always identical','giving probabilities below 0 or above 1'],
 guidedPractice:['Find probabilities of even, prime and not-prime outcomes on a fair die; compare with a 30-roll experiment.'],
 independentPractice:['Ten coin/die/counter probability questions plus three everyday applications requiring interpretation rather than prediction certainty.'],
 mastery:{criterion:'At least 80% accuracy, valid sample spaces, probabilities in [0,1], and clear distinction between likelihood and certainty.',status:'DEEP_WHEN_PASSED'},boardReady:true
}
];

export function getJss2MathDeepLesson(topicId:string){return jss2MathematicsDeepLessons.find(x=>x.topicId===topicId)}
