import type {TopicTeachingMap} from './deepTeachingArchitecture';
const t=(name:string,description:string,examples:string[])=>({name,description,examples});
const common=(governingIdea:string,types:ReturnType<typeof t>[],checks:string[]):TopicTeachingMap=>({standard:'JSS2 Mathematics deep-teaching map: activate prerequisites, define vocabulary, teach every listed form explicitly, model at least three varied examples per mapped type, explain every mathematical reason, then move through guided practice, independent practice, checking and mastery.',governingIdea,types,minimumRepresentativeExamples:3,noJumpChecks:checks});
export const jss2MathematicsTeachingMaps:Record<string,TopicTeachingMap>={
'Whole Numbers and Decimals in Standard Form':common('Standard form writes a non-zero number as A×10^n where 1≤A<10; the exponent records how place value has shifted.',[
 t('Large whole numbers','Move the decimal point left until the leading factor is between 1 and 10.',['45,000=4.5×10^4','7,230,000=7.23×10^6','602,000,000=6.02×10^8']),
 t('Small decimals','Move the decimal point right and use a negative exponent.',['0.0045=4.5×10^-3','0.000072=7.2×10^-5','0.305=3.05×10^-1']),
 t('Standard form to ordinary notation','Use exponent sign and size to restore place value.',['3.4×10^5','6.08×10^-4','9.001×10^2'])],['define power/exponent and powers of ten','explain exponent sign rather than teach decimal-point movement as magic','verify by expanding place values']),
'Prime Factors and Applications':common('Every whole number greater than 1 can be decomposed into prime factors; the decomposition exposes divisibility structure.',[
 t('Factor trees','Split a composite number repeatedly until every leaf is prime.',['60','84','180']),t('Repeated division','Divide successively by primes and write index form.',['72','150','360']),t('Applications','Use prime structure to reason about divisibility, grouping or perfect powers.',['is 540 divisible by 18?','least multiplier making 72 a square','greatest square factor of 180'])],['define prime, composite and factor','explain why decomposition stops only at primes','show that different valid trees give the same prime product']),
'LCM, HCF, Squares and Square Roots':common('Prime powers reveal both shared factors and required multiples; a square has paired prime factors and its square root reverses squaring.',[
 t('LCM by prime factors','Take every needed prime at its greatest occurring power.',['12,18','24,30','8,12,18']),t('HCF by prime factors','Take only common primes at their smallest powers.',['36,48','72,108','60,90,150']),t('Perfect squares and roots','Recognise paired prime factors or known square patterns.',['√144','√225','√576']),t('Estimating non-perfect roots','Locate a number between consecutive perfect squares.',['√50','√90','√130'])],['contrast LCM and HCF purposes','explain greatest vs smallest prime powers','define square root as inverse of squaring','bound estimates using neighbouring squares']),
'Fractions, Ratios, Decimals and Percentages in Transactions':common('Fractions, ratios, decimals and percentages are related representations of comparison; transactions apply those comparisons to money and quantities.',[
 t('Conversions','Convert without changing the represented value.',['3/5↔0.6↔60%','0.375↔3/8↔37.5%','ratio 2:5 as fraction/percentage of total']),t('Percentage of quantity','Interpret percent as per hundred and scale to the quantity.',['15% of ₦8,000','7.5% of 24,000','increase 360 by 20%']),t('Profit/loss/discount','Identify the correct base amount before calculating percentage.',['CP ₦4,000 SP ₦4,600','20% discount on ₦15,000','loss from ₦12,500 to ₦11,000']),t('Ratio sharing/household transaction','Translate proportional shares into fractional parts of a total.',['share ₦18,000 in 2:3','budget food:transport=5:2','recipe cost ratio'])],['define ratio and percentage base','distinguish cost price, selling price, profit, loss and discount','never assume every percentage is taken from the same base']),
'Approximation':common('Approximation reports a nearby value to a stated accuracy; the retained place determines which following digit controls rounding.',[
 t('Place-value rounding','Round whole/decimal numbers to named places.',['48,763 nearest 100','6.784 nearest 0.1','0.0964 nearest 0.01']),t('Decimal places','Count places after the decimal point.',['12.476 to 2 d.p.','0.00876 to 3 d.p.','105.995 to 1 d.p.']),t('Significant figures','Count from the first non-zero significant digit.',['0.004786 to 2 s.f.','48,650 to 3 s.f.','9.996 to 3 s.f.']),t('Estimation/checking','Approximate operands to judge answer size.',['49.8×20.2','598÷29.7','19.6+80.3−9.8'])],['distinguish decimal places from significant figures','explain the next-digit rule','state accuracy with every rounded answer','use estimates to detect unreasonable exact answers']),
'Directed and Non-Directed Numbers':common('Directed numbers combine magnitude with direction relative to a chosen zero; non-directed quantities describe magnitude only.',[
 t('Number line','Locate/order positive, zero and negative values.',['−5,−1,0,3','compare −7 and −2','distance from −4 to 3']),t('Context interpretation','Attach signs to opposite directions or changes.',['temperature −3°C','₦2,000 debt vs credit','5m below sea level']),t('Directed vs non-directed quantities','Decide whether direction/sign is meaningful.',['temperature vs mass','elevation vs length','profit/loss vs capacity'])],['define origin/zero and opposite directions','explain why −7<−2 using number-line position','distinguish magnitude from signed value']),
'Multiplication and Division of Directed Numbers':common('Sign rules arise from consistency with arithmetic patterns and inverse operations, not arbitrary memorisation.',[
 t('Same signs','Positive×positive and negative×negative give positive.',['6×4','(−5)(−3)','−48÷−6']),t('Different signs','Exactly one negative factor gives a negative result.',['−7×4','9×−6','−63÷9']),t('Multiple factors','Track magnitude and parity of negative factors.',['(−2)(−3)(4)','(−5)(2)(−3)','−72÷(−3)÷2']),t('Context','Interpret repeated signed changes.',['temperature change','financial gain/loss cycles','vertical movement'])],['establish multiplication as repeated signed change/pattern','separate sign determination from magnitude calculation','use inverse division to justify division signs']),
'Algebraic Expressions: Expansion and Factorisation':common('Expansion distributes multiplication across a sum; factorisation reverses that process and must reproduce the original expression when expanded.',[
 t('Single-bracket expansion','Multiply the outside factor by every term.',['3(x+4)','−2(3y−5)','5a(2a+3)']),t('Collecting after expansion','Expand then combine only like terms.',['2(x+3)+3x','4(2y−1)−3(y+2)','3a(a+2)+2a']),t('Common-factor factorisation','Extract the greatest shared numerical/variable factor.',['6x+9','12a²−8a','15xy+20x']),t('Simple quadratic structure','For suitable x²+bx+c forms, choose factors satisfying sum/product conditions.',['x²+5x+6','x²−7x+12','x²+x−6'])],['define expression, term, coefficient, like term, factor and product','explain distributive law','factorisation must be verified by expansion','do not merge unlike terms']),
'Algebraic Fractions':common('An algebraic fraction behaves like a numerical fraction; denominators determine permissible operations and values.',[
 t('Meaning/simplification','Identify numerator/denominator and cancel only common factors.',['6x/9','12a/18b','8xy/12x']),t('Like numerical denominators','Combine algebraic numerators over the common denominator.',['x/5+2x/5','3a/7−a/7','(x+1)/4+(x−1)/4']),t('Unlike numerical denominators','Use LCM to create equivalent fractions.',['x/2+x/3','a/4−a/6','2x/5+3x/10'])],['define numerator, denominator and restriction','explain cancellation applies to factors, not terms across addition','explain why common denominators are required']),
'Simple Equations':common('An equation states equality; solving preserves that equality while isolating the unknown through inverse operations.',[
 t('One-step equations','Undo one operation equally on both sides.',['x+7=15','x−9=4','5x=35']),t('Two-step equations','Undo operations in reverse structural order.',['3x+5=17','4x−7=21','x/3+2=8']),t('Brackets','Expand correctly before isolating, or divide a common multiplier where valid.',['2(x+3)=14','3(2x−1)=15','5−2(x−4)=11']),t('Unknown on both sides','Collect variable terms while preserving equality.',['5x+2=3x+14','7−2x=x+1','4(x−1)=2x+10']),t('Forming equations','Translate a relationship into an equation then interpret the solution.',['number plus 8 is 21','three times a number minus 4 is 20','perimeter word problem'])],['distinguish equation from expression','teach balance/inverse operation before transposition shortcut','apply an operation to both sides','substitute into original equation to verify']),
'Linear Inequalities':common('An inequality describes a range of values; equivalent transformations preserve order except multiplication/division by a negative reverses the inequality direction.',[
 t('Reading/writing inequalities','Translate words and symbols.',['x<5','y≥−2','at most 12']),t('Addition/subtraction','Apply same addition/subtraction to both sides.',['x+4<9','y−7≥3','5>x−2']),t('Positive multiplication/division','Scale both sides without reversing sign.',['3x≤12','x/4>2','2y+1<9']),t('Negative multiplication/division','Reverse the sign and explain order reversal.',['−2x<8','−x≥5','3−2x≤9']),t('Number-line representation','Use open/closed points and rays.',['x<3','x≥−1','−2<x≤4'])],['define inequality symbols and solution set','explain open vs closed endpoint','demonstrate why multiplying by negative reverses order using numbers','check sample values']),
'Graphs and Cartesian Plane':common('Coordinates locate positions by ordered horizontal and vertical displacement; a graph represents a relationship between quantities.',[
 t('Axes and coordinates','Read/plot ordered pairs in all relevant quadrants.',['(3,2)','(−2,4)','(4,−3)']),t('Tables to linear graphs','Generate ordered pairs from a rule.',['y=x+2','y=2x−1','y=−x+3']),t('Reading/interpreting graphs','Extract values, intercepts and trends.',['distance-time table graph','cost vs quantity','temperature over time']),t('Real-life linear relationship','Choose scales, label axes/units and interpret meaning.',['taxi fare','water filling','savings over weeks'])],['define origin, x-axis, y-axis and ordered pair','explain x-coordinate before y-coordinate','teach scale before plotting','connect each point to a pair of related values']),
'Plane Figures and Their Properties':common('Plane figures are classified by defining side, angle, parallelism, perpendicularity and symmetry properties, not appearance alone.',[
 t('Triangles','Classify by sides and by angles.',['equilateral','isosceles right triangle','scalene obtuse triangle']),t('Quadrilaterals','Use hierarchy of side/angle/parallel properties.',['square vs rectangle','rhombus vs parallelogram','trapezium']),t('Regular polygons','Connect equal sides/angles to regularity.',['regular pentagon','regular hexagon','non-regular octagon']),t('Symmetry','Identify line and rotational symmetry where expected.',['square','rectangle','equilateral triangle'])],['define polygon, parallel, perpendicular and symmetry','classify from properties rather than orientation','explain overlapping classifications where applicable']),
'Scale Drawing of Lengths and Distances':common('A scale is a constant ratio between drawing length and actual length, expressed in compatible units.',[
 t('Statement scale','Interpret forms such as 1 cm represents 5 m.',['1cm:5m for 20m','1cm:2km for 7km','2cm:10m for 35m']),t('Representative fraction','Use unitless 1:n scales after unit conversion.',['1:100','1:50,000','1:250,000']),t('Drawing from real length','Convert actual distance to drawing distance.',['30m at 1:500','6km at 1:100,000','12.5m at 1:250']),t('Recovering actual length','Measure/read drawing and scale back.',['7cm at 1:200','4.5cm at 1:50,000','12cm where 1cm=3m'])],['convert units before applying ratio','explain scale as multiplicative relationship','label units on recovered lengths','check whether drawing size is physically sensible']),
'Quantitative Aptitude with Shapes and Scale':common('Quantitative aptitude requires identifying a defensible numerical/spatial rule and testing it against all given evidence before predicting.',[
 t('Shape-number relationships','Infer operations connecting labels/regions.',['triangle corner sums','box input-output','circle sector number rule']),t('Scale reasoning','Compare proportional dimensions/areas without guessing.',['map distance puzzle','enlarged rectangle dimensions','model-to-real ratio']),t('Spatial sequences','Track rotation, count, position or symmetry changes.',['rotating arrow sequence','growing matchstick pattern','alternating polygon pattern'])],['state the proposed rule explicitly','test rule on more than one given case','distinguish numerical evidence from visual guess','explain why rejected patterns fail']),
'Angles and Polygons':common('Angle relationships follow from straight lines, points, parallel lines, triangles and polygon decomposition.',[
 t('Basic angle relations','Use complementary, supplementary, vertically opposite and around-a-point facts.',['35° complement','linear pair with 128°','vertical opposite to 67°']),t('Parallel-line angles','Use corresponding, alternate and co-interior relationships.',['corresponding 72°','alternate angle','co-interior with 115°']),t('Triangle angles','Use interior sum 180° and exterior relationship.',['55°,65°,x','isosceles triangle','exterior angle problem']),t('Polygon interior sums','Decompose n-gon into n−2 triangles.',['quadrilateral','pentagon','octagon']),t('Regular polygon angles','Use equal interior/exterior angles.',['regular hexagon','regular nonagon','find sides from exterior angle 30°'])],['define each angle relation','derive (n−2)×180° rather than state it unexplained','mark equal/parallel evidence','distinguish interior and exterior angles']),
'Angles of Elevation and Depression':common('Elevation/depression are measured from a horizontal line of sight; parallel horizontals create equal alternate angles in many diagrams.',[
 t('Identify elevation/depression','Read observer-target position correctly.',['top of tree from ground','boat from cliff','aircraft from observer']),t('Scale/diagram height-distance problems','Represent a right-triangle situation using given angle and scale/measurement methods appropriate to level.',['tower diagram','flagpole shadow/line of sight','cliff and boat']),t('Linked elevation/depression','Relate horizontal lines and interpret reciprocal sight lines.',['observer on building to car','ship and lighthouse','two observation levels'])],['draw horizontal reference line','state where the angle is measured','do not measure from vertical','distinguish diagram/scale reasoning from later trigonometric methods']),
'Bearings and Distances':common('A three-digit bearing is a clockwise angle measured from north; distance and direction together locate a position.',[
 t('Cardinal/intercardinal direction','Connect compass directions to angular turns.',['NE','SW','due east']),t('Three-digit bearings','Measure/write clockwise from north using three digits.',['045°','120°','275°']),t('Reverse bearings','Find opposite direction by adding/subtracting 180°.',['060°↔240°','135°↔315°','300°↔120°']),t('Scale bearing-distance problems','Construct/read routes using protractor, ruler and scale.',['5km on 060°','two-leg journey','locate B from A then C from B'])],['define bearing and north reference','measure clockwise only','use three digits','explain reverse-bearing 180° relationship','apply scale with consistent units']),
'Triangle Construction and Angle Bisectors':common('Geometric construction uses exact locus/intersection properties; compass arcs are evidence of why the construction works.',[
 t('SSS construction','Three side lengths determine vertices by intersecting distance arcs when triangle inequality permits.',['5,6,7cm','4,4,6cm','6,7,8cm']),t('SAS construction','Two sides and included angle determine the triangle.',['5cm,60°,7cm','4cm,90°,6cm','6cm,45°,5cm']),t('ASA construction','One side and two endpoint angles locate the third vertex.',['6cm,50°,70°','5cm,45°,90°','7cm,60°,40°']),t('Angle bisector','Equal-radius arcs locate points equidistant from angle arms.',['bisect 60°','bisect 90°','bisect an arbitrary drawn angle'])],['define SSS/SAS/ASA and included angle','retain construction arcs','check triangle inequality for SSS','explain why equal arcs produce equal half-angles']),
'Statistics: Ordered Data and Frequency Tables':common('Statistics organises observations so distribution, frequency and patterns can be seen without losing what the data represent.',[
 t('Raw to ordered data','Sort values and preserve repetitions.',['scores 7,4,9,4,6','heights list','daily sales list']),t('Tally/frequency table','Count each observation exactly once.',['shoe sizes','number of siblings','test scores']),t('Grouped/simple class intervals','Organise broader numerical ranges where appropriate.',['ages 10–19 etc','marks intervals','travel times']),t('Interpretation','Answer total, most/least frequent and comparison questions.',['modal category','frequency difference','total observations'])],['define datum/data, tally and frequency','verify frequencies sum to number of observations','choose non-overlapping classes','distinguish value from frequency']),
'Statistics: Pie Charts and Graphical Representation':common('A pie chart maps each category fraction of the total onto the same fraction of 360°; other graphs must preserve scale and category meaning.',[
 t('Frequency to sector angle','Use frequency/total×360°.',['10 of 40','15 of 60','18 of 72']),t('Construct pie chart','Calculate all sectors and check total 360°.',['sports preferences','household budget','transport modes']),t('Recover data from pie chart','Use angle/360×total.',['90° of 80 pupils','144° of ₦50,000','45° of 200 votes']),t('Other graphical representation','Choose/read bar/line representations with correct scales.',['bar chart categories','line graph over time','compare two category bars'])],['explain why full circle is 360°','check sector angles total 360°','label category and scale','distinguish categorical bars from continuous/time lines']),
'Probability':common('Probability measures chance from 0 to 1; theoretical probability uses equally likely outcomes while experimental probability uses observed relative frequency.',[
 t('Probability language/scale','Classify impossible, unlikely, even chance, likely and certain.',['sun rises tomorrow','roll 7 on standard die','coin head']),t('Simple theoretical probability','Count favourable outcomes over total equally likely outcomes.',['coin','die','bag with coloured counters']),t('Complement','Use P(not A)=1−P(A) for simple events.',['not rolling 6','not red counter','not head']),t('Experimental probability','Use observed frequency/number of trials and compare with theory.',['coin 30 tosses','spinner 50 spins','die 60 rolls'])],['define outcome, event and equally likely','probability must lie between 0 and 1','do not treat probability as certainty','distinguish theoretical from experimental evidence'])
};
