export type DeepJss3MathLesson={
 topicId:string; classLevel:'JSS3'; subject:'Mathematics'; topic:string;
 source:{authority:'NERDC';url:string;page:number}; objectives:string[]; prerequisites:string[];
 teaching:string[]; workedExamples:string[]; misconceptions:string[]; guidedPractice:string[]; independentPractice:string[];
 mastery:{criterion:string;status:'DEEP_WHEN_PASSED'}; boardReady:true;
};

const sourceUrl='https://nerdc.gov.ng/content_manager/jss/jss1-3_maths.pdf';

/**
 * AVORA-authored JSS3 Mathematics teaching layer.
 * NERDC is used for curriculum scope and performance objectives. Explanations,
 * examples, practice and mastery tasks below are original AVORA teaching content.
 */
export const jss3MathematicsDeepLessons:DeepJss3MathLesson[]=[
{
 topicId:'nerdc-jss3-math-numbers-and-numeration-whole-numbers-1',classLevel:'JSS3',subject:'Mathematics',topic:'Whole Numbers',source:{authority:'NERDC',url:sourceUrl,page:28},
 objectives:['Revise basic operations in the binary number system','Convert binary numbers to other bases and convert numbers from other bases to binary','Solve quantitative-reasoning problems involving binary numbers','Use a computer or calculator appropriately for simple mathematical calculations','Translate verbal statements and word problems into numerical expressions','Simplify expressions involving brackets and fractions','Solve direct- and inverse-proportion problems and apply them to practical situations','Solve compound-interest problems and connect compound interest to everyday financial situations'],
 prerequisites:['JSS1/JSS2 binary notation and place value','fraction operations and BODMAS','ratio, rate and percentage','simple interest and repeated percentage change'],
 teaching:[
  'BINARY REVISION — PLACE VALUE BEFORE PROCEDURE. Binary is a base-two place-value system. From right to left, the places are 2⁰=1,2¹=2,2²=4,2³=8,2⁴=16 and so on. Only the digits 0 and 1 are valid. Every binary operation must preserve these place values.',
  'BINARY ADDITION. The basic facts are 0+0=0, 0+1=1, 1+1=10₂ and 1+1+1=11₂. Regroup whenever a column reaches two because two units of one binary place make one unit of the next place.',
  'BINARY SUBTRACTION. When 0−1 occurs, borrow one unit from the next binary place. That borrowed unit is worth 10₂ in the current place. Record every regrouping, especially when borrowing passes across zeros.',
  'BINARY MULTIPLICATION. Multiplying by 1 reproduces the multiplicand and multiplying by 0 gives zero. In long multiplication, each move one place left represents multiplication by 2, so partial products must be shifted correctly.',
  'BINARY DIVISION. Use the same compare→write quotient digit→multiply→subtract→bring down cycle as ordinary long division, but quotient digits are only 0 or 1. Verify with divisor×quotient+remainder=dividend.',
  'BINARY TO BASE TEN. Multiply each binary digit by its power-of-two place value and add. Never read 101101₂ as “one hundred and one thousand…” because its digits do not represent decimal place values.',
  'BASE TEN TO BINARY. Repeatedly divide by 2, record each remainder, and read the remainders from bottom to top. The bottom-to-top order works because the first remainder gives the 2⁰ place, the next gives 2¹, and so on.',
  'OTHER BASES AND BINARY. A safe general route is source base→base ten→binary or binary→base ten→target base. Check that every digit used is legal for its base before calculating.',
  'QUANTITATIVE REASONING WITH BASES. Questions may hide the base-system idea inside counting, coding or place-value patterns. Write the place values explicitly before operating rather than treating the numeral as a decimal number.',
  'USING A CALCULATOR OR COMPUTER WELL. Technology can perform arithmetic quickly, but the learner must estimate first, enter the expression correctly, read the display with units, and decide whether the answer is reasonable. A calculator cannot repair a wrongly translated expression.',
  'TRANSLATING WORDS INTO MATHEMATICS. Identify the quantities, then the relationship. Sum means addition, difference means subtraction, product means multiplication and quotient means division. Phrases such as “5 less than x” reverse the spoken order: x−5, not 5−x.',
  'BRACKETS PRESERVE GROUPING. “Three times the sum of x and 4” is 3(x+4), not 3x+4. “The difference between 7 and the sum of half of 8 and 3” is 7−(8/2+3). Translate before simplifying.',
  'EXPRESSIONS WITH BRACKETS. Use distributive multiplication: a(b+c)=ab+ac. Multiply every term inside the bracket, then collect only like terms. A minus sign before a bracket changes every sign inside when the bracket is removed.',
  'EXPRESSIONS WITH FRACTIONS. Fractions follow ordinary arithmetic rules. For addition/subtraction, use a common denominator; for multiplication, multiply numerators and denominators; for division, multiply by the reciprocal. Apply BODMAS to mixed expressions.',
  'DIRECT PROPORTION. If y is directly proportional to x, then y=kx and y/x=k is constant. If x doubles, y doubles. Find k from one known pair, then use the same k for another pair.',
  'INVERSE PROPORTION. If y is inversely proportional to x, then y=k/x and xy=k is constant. When one quantity increases, the other decreases so their product stays constant. This often appears in fixed-work problems involving workers and time.',
  'HOW TO CHOOSE DIRECT OR INVERSE. Ask what should happen if one quantity doubles. If the other should also double, the relation is direct. If the other should halve for the same total task or quantity, it is inverse. Do not choose by keywords alone.',
  'COMPOUND INTEREST — MEANING FIRST. Compound interest adds each period’s interest to the balance. The next period earns interest on the new balance, so the interest amount can grow from one year to the next.',
  'COMPOUND INTEREST YEAR-BY-YEAR. If ₦50,000 earns 8% annually, year 1 interest is 0.08×50,000=₦4,000, giving ₦54,000. Year 2 interest is 0.08×54,000=₦4,320, giving ₦58,320. Compound interest after two years is ₦8,320.',
  'COMPOUND-INTEREST FORMULA. Repeated multiplication by the same growth factor gives A=P(1+r/100)^n. This formula is a compressed version of the year-by-year method, not a separate rule. Compound interest=amount−principal.',
  'SIMPLE VS COMPOUND INTEREST. Simple interest is calculated repeatedly on the original principal; compound interest is calculated on the growing balance. Over more than one period at a positive rate, compound interest is normally larger.',
  'PERMANENT CHECKING STANDARD. Reconvert number-base answers, substitute translated expressions into the original wording, test proportion answers using the constant, compare compound-interest formula with year-by-year growth, and estimate calculator results before trusting them.'
 ],
 workedExamples:[
  'BINARY ADDITION. Calculate 1011₂+0110₂.\n      1 0 1 1\n    + 0 1 1 0\n    ---------\n    1 0 0 0 1₂\nFrom the right: 1+0=1; 1+1=10₂, write 0 carry 1; 0+1+1=10₂, write 0 carry 1; 1+0+1=10₂, write 0 carry 1; bring down the final carry. Check: 11+6=17 and 10001₂=17₁₀.',
  'BINARY SUBTRACTION. Calculate 1010₂−0011₂. Since 0−1 requires borrowing, regroup in base two. The result is 0111₂. Check in base ten: 10−3=7, and 111₂=7.',
  'BINARY MULTIPLICATION. 101₂×11₂. First partial product: 101₂×1=101₂. Second partial product is shifted left: 101₂×10₂=1010₂. Add 0101₂+1010₂=1111₂. Check: 5×3=15.',
  'BINARY DIVISION. 111₂÷11₂. In base ten this is 7÷3, but work in binary: quotient 10₂, remainder 1₂. Verify: 11₂×10₂+1₂=110₂+1₂=111₂.',
  'BINARY TO DECIMAL. Convert 101101₂. Place values are 32,16,8,4,2,1. So 1×32+0×16+1×8+1×4+0×2+1×1=32+8+4+1=45. Therefore 101101₂=45₁₀.',
  'DECIMAL TO BINARY. Convert 45₁₀ by repeated division. 45÷2=22 r1; 22÷2=11 r0; 11÷2=5 r1; 5÷2=2 r1; 2÷2=1 r0; 1÷2=0 r1. Read remainders bottom to top: 101101₂.',
  'OTHER BASE TO BINARY. Convert 132₄ to binary through base ten. 132₄=1×4²+3×4+2=16+12+2=30₁₀. Convert 30 to binary: 11110₂. Therefore 132₄=11110₂.',
  'TRANSLATION — ORDER MATTERS. Translate “five less than x”. The quantity x is reduced by 5, so the expression is x−5. It is not 5−x.',
  'TRANSLATION — GROUPING. Translate “three times the sum of n and 4”. The sum must be formed first: n+4. Three times that whole sum is 3(n+4).',
  'TRANSLATION AND SIMPLIFICATION. “The difference between 7 and the sum of half of 8 and 3” becomes 7−(8/2+3)=7−(4+3)=7−7=0.',
  'BRACKETS. Simplify 3(2x−5)+4(x+1). Expand every term: 6x−15+4x+4. Collect like terms: 10x−11.',
  'MINUS BEFORE BRACKET. Simplify 5a−2(a−3). Distribute −2: 5a−2a+6=3a+6. The +6 appears because −2×−3=+6.',
  'FRACTION EXPRESSION. Simplify 3/4+5/6. LCM(4,6)=12. 3/4=9/12 and 5/6=10/12. Sum=19/12=1 7/12.',
  'DIRECT PROPORTION. Six notebooks cost ₦2,700 at constant price. Cost per notebook k=2700/6=₦450. Ten notebooks cost 10×450=₦4,500. Since quantity increased by factor 10/6, cost increases by the same factor.',
  'DIRECT PROPORTION WITH EQUATION. If y∝x and y=18 when x=6, then y=kx gives 18=6k, so k=3. When x=11, y=3×11=33.',
  'INVERSE PROPORTION. Eight workers finish a fixed job in 15 days. Worker-days are constant: 8×15=120. For 12 workers, days=120/12=10. More workers lead to fewer days for the same fixed job.',
  'INVERSE PROPORTION WITH EQUATION. If y∝1/x and y=20 when x=3, then xy=k=60. When x=5, y=60/5=12.',
  'COMPOUND INTEREST — YEAR BY YEAR. ₦20,000 at 10% annually for 2 years. Year 1 interest=₦2,000, balance=₦22,000. Year 2 interest=₦2,200, balance=₦24,200. Compound interest=₦4,200.',
  'COMPOUND INTEREST — FORMULA. ₦50,000 at 8% annually for 2 years: A=50,000(1.08)²=50,000×1.1664=₦58,320. CI=58,320−50,000=₦8,320.',
  'SIMPLE VS COMPOUND. ₦100,000 at 10% for 2 years. Simple interest=100,000×10×2/100=₦20,000, amount=₦120,000. Compound amount=100,000(1.1)²=₦121,000, so compound interest=₦21,000. The extra ₦1,000 is interest earned on the first year’s interest.',
  'CALCULATOR REASONABLENESS. Evaluate 19.8×5.03. Estimate first: 20×5≈100. A calculator result of about 99.594 is reasonable; a display of 995.94 would signal a likely entry or decimal-place error.'
 ],
 misconceptions:[
  'reading a binary numeral as an ordinary decimal number',
  'using an invalid digit such as 2 in base two',
  'forgetting binary carries or borrows are based on groups of two rather than ten',
  'reading repeated-division remainders top-to-bottom when converting decimal to binary',
  'using a digit that is illegal in the stated base',
  'translating “5 less than x” as 5−x instead of x−5',
  'dropping brackets from phrases such as “three times the sum”',
  'multiplying an outside factor by only the first term inside a bracket',
  'adding fraction numerators and denominators directly',
  'treating every two-quantity question as direct proportion',
  'using inverse proportion when the total task is not fixed',
  'calculating compound interest each year only on the original principal',
  'using the compound-interest formula without converting the rate correctly to a decimal growth factor',
  'accepting a calculator display without checking order of magnitude, unit or meaning'
 ],
 guidedPractice:[
  'Add 111₂+101₂ and verify in base ten.',
  'Subtract 1000₂−0110₂ and verify by binary addition.',
  'Multiply 110₂×101₂ using shifted partial products.',
  'Divide 1011₂ by 10₂ and state quotient and remainder.',
  'Convert 110011₂ to base ten, then convert 51₁₀ back to binary.',
  'Convert 213₄ to base ten and then to binary.',
  'Translate: “seven more than twice x”, “four less than the product of 3 and n”, and “half the difference between p and 6”.',
  'Simplify 2(3x+4)−5(x−1).',
  'Simplify 5/8+3/4−1/2.',
  'If 8 pens cost ₦3,600, find the cost of 15 at the same rate and justify direct proportion.',
  'If 10 workers need 18 days for a fixed task, estimate and then calculate the time for 15 workers.',
  'Find amount and compound interest on ₦30,000 at 5% annually for 3 years using the year-by-year method, then verify with the formula.'
 ],
 independentPractice:[
  'Evaluate 10101₂+1110₂.',
  'Evaluate 11000₂−1011₂.',
  'Evaluate 101₂×110₂.',
  'Evaluate 1101₂÷11₂ and verify.',
  'Convert 100111₂ to base ten.',
  'Convert 73₁₀ to binary.',
  'Convert 231₄ to binary through base ten.',
  'Translate “nine less than three times a number x”.',
  'Translate “twice the sum of p and 7”.',
  'Simplify 4(2a−3)+3(a+5).',
  'Simplify 7−2(3−x).',
  'Evaluate 2/3+5/8.',
  'Twelve exercise books cost ₦5,400. Find the cost of 20 at the same rate.',
  'A car uses 18 litres of fuel for 216 km at a constant consumption rate. How many litres are required for 300 km?',
  'Six machines make a fixed order in 15 hours. How long would 10 identical machines take?',
  'If y∝x and y=28 when x=4, find y when x=9.',
  'If y∝1/x and y=24 when x=5, find y when x=8.',
  'Find the amount and compound interest on ₦40,000 at 10% per annum for 2 years.',
  'Find the amount on ₦75,000 at 6% compounded annually for 3 years.',
  'Compare simple and compound interest on ₦60,000 at 5% for 2 years.',
  'A calculator gives 4,965 for 49.8×9.97. Estimate first and decide whether the display is plausible.',
  'Create one real-life example each of direct and inverse proportion and explain why each model fits.'
 ],
 mastery:{criterion:'At least 80% across binary operations/conversion, verbal translation, bracket/fraction expressions, direct and inverse proportion, compound interest and calculator reasonableness, with method shown and every proportional model justified from the relationship.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-numbers-and-numeration-whole-numbers-2',classLevel:'JSS3',subject:'Mathematics',topic:'Rational and non-rational numbers',source:{authority:'NERDC',url:sourceUrl,page:29},
 objectives:['Identify rational numbers and non-rational (irrational) numbers','Determine experimentally an approximate value of pi using circular objects'],
 prerequisites:['fractions and equivalent fractions','terminating and recurring decimals','square roots and perfect squares','measurement of circumference and diameter'],
 teaching:[
  'START WITH THE SET IDEA. A rational number is any number that can be written exactly as p/q, where p and q are integers and q≠0. The word rational is connected to ratio. The fraction may not be obvious at first, so classification requires reasoning rather than appearance.',
  'EVERY INTEGER IS RATIONAL. Any integer n can be written as n/1. Therefore −7=−7/1, 0=0/1 and 12=12/1 are all rational.',
  'TERMINATING DECIMALS ARE RATIONAL. A terminating decimal has a finite number of decimal places and can be written over a power of 10. For example, 0.125=125/1000=1/8.',
  'RECURRING DECIMALS ARE RATIONAL. A decimal such as 0.333… repeats a fixed pattern forever and equals 1/3. A repeating block such as 0.121212… is also rational because the repetition can be converted exactly to a fraction.',
  'IRRATIONAL NUMBERS cannot be written exactly as p/q. Their decimal expansions continue without terminating and without settling into a repeating block. Common examples at this level include √2, √3, √5 and π.',
  'A SQUARE-ROOT SYMBOL DOES NOT AUTOMATICALLY MEAN IRRATIONAL. Simplify first. √49=7, so it is rational. √72=√(36×2)=6√2, so it is irrational because √2 is irrational.',
  'PERFECT-SQUARE TEST. For a positive integer under a square root, check whether it is a perfect square after simplification. If the simplified root is an integer, the value is rational. If an irrational root remains, the number is irrational.',
  'RATIONAL PLUS OR MINUS RATIONAL remains rational. Rational×rational and rational÷non-zero rational are rational. At this level, mixed expressions containing an irrational term must be handled carefully; an irrational-looking expression may simplify to a rational value in special cases.',
  'EXACT FORM VS APPROXIMATION. √2 and π are exact symbols. Writing √2≈1.414 or π≈3.142 gives approximations. Do not replace an exact irrational number with a rounded decimal too early if the question does not ask for an approximation.',
  'COMPARING IRRATIONAL NUMBERS. Estimate them using nearby perfect squares or known decimal approximations. Since 4<5<9, 2<√5<3. Testing 2.2²=4.84 and 2.3²=5.29 shows √5 lies between 2.2 and 2.3.',
  'ORDERING MIXED NUMBERS. Convert or approximate only enough to compare. For −√4,−1.5,0,√3: −√4=−2 and √3≈1.732, so order is −2<−1.5<0<√3.',
  'PI IS A RATIO ARISING FROM CIRCLES. For any circle, circumference divided by diameter is approximately the same constant, π. The exact value of π is irrational; 22/7 and 3.142 are useful approximations, not definitions.',
  'EXPERIMENTAL PI. Measure the circumference C and diameter d of several circular objects. For each object calculate C/d. Good measurements should produce values close to 3.14. Differences arise from ruler/tape precision, thickness of the object, difficulty locating the exact diameter and ordinary measurement error.',
  'WHY MULTIPLE OBJECTS HELP. One inaccurate measurement can give a poor estimate. Repeating the experiment with several circles allows the learner to see the stable pattern and, if required, calculate a mean estimate.',
  'PERMANENT CLASSIFICATION RULE. Before calling a number rational or irrational, ask: Can it be written exactly as p/q? Does a decimal terminate or recur? Can a square root simplify to an integer? Is the number exact or merely an approximation?'
 ],
 workedExamples:[
  'INTEGER. Classify −7. Since −7=−7/1 and both −7 and 1 are integers with non-zero denominator, −7 is rational.',
  'TERMINATING DECIMAL. Classify 0.125. 0.125=125/1000=1/8. Therefore it is rational.',
  'RECURRING DECIMAL. Classify 0.333…. This equals 1/3, so it is rational.',
  'RECURRING BLOCK. Let x=0.121212…. Then 100x=12.121212…. Subtract: 100x−x=12, so 99x=12 and x=12/99=4/33. Therefore the recurring decimal is rational.',
  'PERFECT-SQUARE ROOT. √81=9=9/1, so √81 is rational.',
  'NON-PERFECT ROOT. √20=√(4×5)=2√5. Since √5 is irrational, √20 is irrational.',
  'ROOT THAT LOOKS IRRATIONAL BUT IS NOT. √0.49=0.7=7/10. Therefore it is rational.',
  'SIMPLIFY BEFORE CLASSIFYING. √72=√(36×2)=6√2, so it is irrational. By contrast, √144=12, rational.',
  'MIXED CLASSIFICATION. Numbers: −4,2/7,0.75,0.121212…,√36,√7,π. Rational: −4,2/7,0.75,0.121212…,√36=6. Irrational: √7 and π.',
  'COMPARE √5 AND 2.3. Since 2.2²=4.84 and 2.3²=5.29, √5 is between 2.2 and 2.3; therefore √5<2.3.',
  'ORDER MIXED VALUES. Order −√4,−1.5,0,√3. Since −√4=−2 and √3≈1.732, the order is −2<−1.5<0<√3.',
  'APPROXIMATE EXPRESSION. Estimate 2+√3. Since √3≈1.732, 2+√3≈3.732. Exact form remains 2+√3.',
  'PI EXPERIMENT — ONE OBJECT. A lid has C=62.9cm and d=20.0cm. C/d=62.9/20.0=3.145. This is close to π.',
  'PI EXPERIMENT — SECOND OBJECT. A circular plate has C=78.5cm and d=25.0cm. C/d=78.5/25=3.14.',
  'PI EXPERIMENT — COMPARING MEASUREMENTS. Three objects give C/d values 3.12,3.15 and3.14. Mean=(3.12+3.15+3.14)/3≈3.137. The small spread suggests measurement error around a stable value near π.',
  '22/7 IS AN APPROXIMATION. 22/7≈3.142857…. π≈3.141592…. They are close but not equal. Therefore 22/7 is rational while π is irrational.'
 ],
 misconceptions:[
  'thinking every decimal is irrational',
  'thinking every non-terminating decimal is irrational even when it recurs',
  'thinking every square root is irrational',
  'classifying √49 as irrational without simplifying',
  'assuming a decimal displayed on a calculator is exact when it may be rounded',
  'using 22/7 as the exact definition of π',
  'calling 3.142 irrational because it approximates π; 3.142 is terminating and therefore rational',
  'classifying a number by appearance rather than by whether it can be expressed as p/q',
  'rounding an irrational number too early and then treating the rounded value as exact',
  'measuring a circle only once and treating measurement error as a change in π'
 ],
 guidedPractice:[
  'Classify −12,0,5/9,0.625,0.454545…,√64,√10 and π with a reason for each.',
  'Convert 0.272727… to a fraction using an algebraic recurring-decimal method.',
  'Simplify and classify √45,√121 and √0.81.',
  'Place √6 between two consecutive integers, then between two consecutive tenths.',
  'Order −2.2,−√5,0,√2,1.5 from least to greatest.',
  'State whether each is exact or approximate: π,3.14,√2,1.414.',
  'Measure circumference and diameter of two circular objects, calculate C/d and comment on the results.',
  'Given C/d measurements 3.13,3.16,3.14,3.15, calculate the mean estimate and explain why the values are not identical.'
 ],
 independentPractice:[
  'Classify 14 and justify.',
  'Classify −3/11 and justify.',
  'Classify 0.0375 and convert it to a fraction.',
  'Classify 0.6666… and state an exact fraction.',
  'Classify 0.101001000100001… and explain why the pattern does or does not recur.',
  'Simplify and classify √225.',
  'Simplify and classify √32.',
  'Simplify and classify √98.',
  'Classify π,22/7,3.14159 and explain the difference among them.',
  'Estimate √7 to 2 decimal places using nearby squares or a calculator check.',
  'Compare √10 and 3.2.',
  'Order −√9,−2.8,−√5,0,√2,1.6.',
  'Estimate 5−√6 to 2 decimal places while keeping 5−√6 as the exact form.',
  'A circular tin has circumference 94.3cm and diameter 30cm. Calculate C/d and compare with 3.14.',
  'Measure three circular household objects and prepare a table of object,C,d,C/d.',
  'Calculate the mean of your three C/d values.',
  'Give three reasons experimental C/d values may differ slightly.',
  'Explain in your own words why 3.142 is rational but π is irrational even though 3.142 is often used for π.'
 ],
 mastery:{criterion:'At least 85% correct classification across integers, fractions, terminating/recurring decimals and simplified roots, plus accurate exact-versus-approximate reasoning and a multi-object experimental estimate of π with measurement-error explanation.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-basic-operations-basic-operations-1',classLevel:'JSS3',subject:'Mathematics',topic:'Addition of numbers in base 2 numerals',source:{authority:'NERDC',url:sourceUrl,page:30},
 objectives:['Add two or three 3-digit binary numbers accurately'],
 prerequisites:['binary place value','base-ten addition and carrying'],
 teaching:['Binary addition follows place value exactly like ordinary addition, but regrouping occurs at 2 rather than 10. The basic facts are 0+0=0, 0+1=1, 1+1=10₂ and 1+1+1=11₂.','Work from right to left. When a column totals 2, write 0 and carry 1; when it totals 3, write 1 and carry 1. Align digits by place value before adding.','Check by converting the addends and answer to base ten. The base-ten sum should agree, but the working should still demonstrate binary addition.'],
 workedExamples:['101₂+011₂=1000₂ because 5+3=8.','111₂+101₂+010₂=1110₂ because 7+5+2=14.'],
 misconceptions:['using decimal carrying rules','writing 2 as a binary digit','misaligning place-value columns','forgetting a carried 1 when adding three numerals'],
 guidedPractice:['Add 101₂+110₂, then 011₂+101₂+111₂; verify both in base ten.'],
 independentPractice:['Ten binary additions, including two- and three-addend examples; convert three answers to base ten as checks.'],
 mastery:{criterion:'At least 9 of 10 additions correct, with valid binary digits and correct carrying shown.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-basic-operations-basic-operations-2',classLevel:'JSS3',subject:'Mathematics',topic:'Subtraction of numbers in base 2 numerals',source:{authority:'NERDC',url:sourceUrl,page:30},
 objectives:['Subtract 3-digit binary numbers accurately'],
 prerequisites:['binary place value','binary addition','borrowing in base ten'],
 teaching:['Binary subtraction uses 0−0=0, 1−0=1 and 1−1=0. When 0−1 occurs, borrow 1 from the next binary place; that borrowed 1 is worth 10₂, so 10₂−1₂=1₂.','If the next place is also zero, borrowing may pass across several places. Record each regrouping so the place-value change is visible.','Check by converting both numerals to base ten or by adding the difference back to the subtrahend.'],
 workedExamples:['110₂−011₂=011₂ because 6−3=3.','1000₂−0011₂=0101₂ because 8−3=5.'],
 misconceptions:['treating borrowed 1 as decimal ten','dropping leading place-value positions too early','subtracting the smaller digit from the larger regardless of order'],
 guidedPractice:['Subtract 101₂−011₂ and 1000₂−0110₂; check each by addition.'],
 independentPractice:['Ten subtraction problems with increasing borrowing complexity, plus three missing-number checks.'],
 mastery:{criterion:'At least 9 of 10 correct with borrowing shown and one independent verification method used.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-basic-operations-basic-operations-3',classLevel:'JSS3',subject:'Mathematics',topic:'Multiplication of numbers in base 2 numerals',source:{authority:'NERDC',url:sourceUrl,page:30},
 objectives:['Multiply two 2-digit binary numbers accurately'],
 prerequisites:['binary place value','binary addition','ordinary long multiplication'],
 teaching:['Binary multiplication has only four digit facts: 0×0=0, 0×1=0, 1×0=0 and 1×1=1. The place-value shifts in long multiplication are the important part.','Multiply by each digit of the multiplier from right to left. A row produced by a 1 copies the multiplicand; a row produced by a 0 is zero. Shift each new row one binary place to the left.','Add the partial products using binary addition and check in base ten when learning the method.'],
 workedExamples:['11₂×10₂=110₂ because 3×2=6.','11₂×11₂: partial products 11₂ and 110₂ sum to 1001₂, and 3×3=9.'],
 misconceptions:['forgetting the place-value shift','writing decimal multiplication facts into binary columns','using a digit 2 in a partial product'],
 guidedPractice:['Multiply 10₂×11₂ and 11₂×11₂, showing partial products.'],
 independentPractice:['Eight 2-digit-by-2-digit binary products and two contextual repeated-grouping problems.'],
 mastery:{criterion:'At least 8 of 10 correct with properly shifted partial products and valid binary addition.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-basic-operations-basic-operations-4',classLevel:'JSS3',subject:'Mathematics',topic:'Division of numbers in base 2 numerals',source:{authority:'NERDC',url:sourceUrl,page:30},
 objectives:['Divide two- to three-digit binary numbers by simple binary divisors'],
 prerequisites:['binary subtraction','binary multiplication','long division'],
 teaching:['Binary long division follows the same cycle as decimal long division: compare, place a quotient digit, multiply, subtract, and bring down. Quotient digits are only 0 or 1.','At each step ask whether the divisor fits into the current binary part. If yes, write 1; if no, write 0 and bring down the next digit.','A remainder must be smaller than the divisor. Verify by divisor×quotient+remainder=dividend.'],
 workedExamples:['110₂÷10₂=11₂ because 6÷2=3.','111₂÷11₂=10₂ remainder 1₂ because 7=3×2+1.'],
 misconceptions:['omitting a zero in the quotient when the divisor does not fit','using decimal division facts without binary place value','accepting a remainder equal to or larger than the divisor'],
 guidedPractice:['Divide 100₂ by 10₂ and 101₂ by 10₂; verify each.'],
 independentPractice:['Eight exact and remainder binary divisions; verify three using multiplication and addition.'],
 mastery:{criterion:'At least 8 of 10 division problems correct, including valid quotient-place zeros and remainder checks.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-algebraic-processes-algebraic-operations-1',classLevel:'JSS3',subject:'Mathematics',topic:'Factorization',source:{authority:'NERDC',url:sourceUrl,page:31},
 objectives:['Factorize simple algebraic expressions','Factorize quadratic expressions using appropriate methods','Use factorization in word and quantitative-reasoning problems'],
 prerequisites:['expansion of brackets','common factors','algebraic terms and coefficients','integer multiplication'],
 teaching:[
  'FACTORISATION is the reverse of expansion. Expansion multiplies factors to produce terms; factorisation rewrites an expression as a product of simpler factors.',
  'ALWAYS CHECK FOR A GREATEST COMMON FACTOR FIRST. If every term has a common numerical or variable factor, remove it before trying another method.',
  'COMMON NUMERICAL FACTOR. 12x+18 has common factor6, so12x+18=6(2x+3). The factor6 must divide every term exactly.',
  'COMMON VARIABLE FACTOR. 15x²y−10xy² has common factor5xy, giving5xy(3x−2y). Use the greatest common variable power shared by every term.',
  'GROUPING works well with four terms. Group terms so each pair has a factor and leaves the SAME bracket. Example ax+ay+bx+by=a(x+y)+b(x+y)=(a+b)(x+y).',
  'DIFFERENCE OF TWO SQUARES uses a²−b²=(a−b)(a+b). Both terms must be perfect squares and the sign between them must be minus.',
  'PERFECT-SQUARE TRINOMIALS follow a²±2ab+b²=(a±b)². Verify the middle term before applying the identity.',
  'QUADRATIC x²+bx+c. Find two numbers whose product is c and sum is b. Those numbers form the two binomial factors.',
  'WHEN c IS POSITIVE, the two numbers have the same sign. Their common sign matches b. WHEN c IS NEGATIVE, the signs are opposite.',
  'GENERAL QUADRATIC ax²+bx+c. Use the ac method: find two numbers whose product is ac and sum is b, split the middle term, then factor by grouping.',
  'DO NOT SPLIT THE MIDDLE TERM UNTIL BOTH CONDITIONS ARE MET: product=ac and sum=b.',
  'REARRANGEMENT may help grouping, but only terms are reordered; no sign or coefficient may change.',
  'FACTORISATION CAN SOLVE EQUATIONS after one side is zero: if (x−3)(x+5)=0, then x=3 or x=−5 because a product is zero only when at least one factor is zero.',
  'WORD PROBLEMS may generate an algebraic expression that can be factorised. Define quantities first so symbols still have meaning.',
  'PERMANENT CHECK: multiply the factors back out. If the expansion does not reproduce the original expression exactly, the factorisation is wrong.'
 ],
 workedExamples:[
  'COMMON FACTOR: 8x+12=4(2x+3). Check:4×2x+4×3=8x+12.',
  'COMMON VARIABLE FACTOR: 12a²−18a=6a(2a−3).',
  'TWO VARIABLES: 15xy+20x²=5x(3y+4x).',
  'GROUPING: ax+ay+bx+by=a(x+y)+b(x+y)=(a+b)(x+y).',
  'GROUPING: 3m+3p+mq+pq=3(m+p)+q(m+p)=(m+p)(3+q).',
  'DIFFERENCE OF SQUARES: x²−25=(x−5)(x+5).',
  'DIFFERENCE OF SQUARES: 9a²−16b²=(3a−4b)(3a+4b).',
  'PERFECT SQUARE: x²+6x+9=(x+3)² because2×x×3=6x.',
  'PERFECT SQUARE: 4y²−12y+9=(2y−3)².',
  'QUADRATIC a=1: x²+7x+12. Product12,sum7→3 and4. Answer=(x+3)(x+4).',
  'QUADRATIC NEGATIVE MIDDLE: x²−9x+20. Product20,sum−9→−4,−5. Answer=(x−4)(x−5).',
  'QUADRATIC MIXED SIGNS: x²+x−12. Product−12,sum1→4,−3. Answer=(x+4)(x−3).',
  'GENERAL QUADRATIC: 2x²+7x+3. ac=6; numbers6,1. Split:2x²+6x+x+3=2x(x+3)+1(x+3)=(2x+1)(x+3).',
  'GENERAL QUADRATIC: 3x²−x−2. ac=−6; numbers2,−3. 3x²+2x−3x−2=x(3x+2)−1(3x+2)=(x−1)(3x+2).',
  'GENERAL QUADRATIC: 6x²+11x+3. ac=18; numbers9,2. 6x²+9x+2x+3=3x(2x+3)+1(2x+3)=(3x+1)(2x+3).',
  'EQUATION FROM FACTORS: x²−2x−15=0→(x−5)(x+3)=0→x=5 or−3.',
  'VERIFY: (2x+1)(x+3)=2x²+6x+x+3=2x²+7x+3.',
  'CONTEXT: rectangle area x²+7x+12 can be written (x+3)(x+4), suggesting side expressions x+3 and x+4.'
 ],
 misconceptions:[
  'factoring only some terms',
  'using a factor that does not divide every term',
  'confusing collection of like terms with factorisation',
  'using difference-of-squares rule for a sum of squares',
  'calling every three-term quadratic a perfect square',
  'choosing pair with correct product but wrong sum',
  'forgetting ac when leading coefficient is not1',
  'splitting middle term with changed total',
  'losing a negative sign during grouping',
  'failing to expand to verify'
 ],
 guidedPractice:[
  'Factorize10x+15.',
  'Factorize18a²b−24ab².',
  'Factorize2x+2y+3x+3y by grouping.',
  'Factorize y²−64.',
  'Factorize4a²−25.',
  'Factorize x²+10x+25.',
  'Factorize x²+11x+24.',
  'Factorize x²−2x−35.',
  'Factorize2x²+9x+4.',
  'Factorize3x²+8x+4.',
  'Solve x²−7x+12=0 by factorisation.',
  'Expand three of your answers to verify.'
 ],
 independentPractice:[
  'Factorize14x+21.',
  'Factorize20a²b+30ab².',
  'Factorize3x+3y+5x+5y.',
  'Factorize x²−81.',
  'Factorize16p²−9q².',
  'Factorize x²+8x+16.',
  'Factorize x²−12x+36.',
  'Factorize x²+13x+40.',
  'Factorize x²−11x+24.',
  'Factorize x²+2x−35.',
  'Factorize2x²+5x+2.',
  'Factorize3x²+11x+6.',
  'Factorize4x²−4x−3.',
  'Factorize6x²+7x−3.',
  'Solve x²−9x+20=0.',
  'Solve2x²+7x+3=0.',
  'A rectangle has area x²+9x+20. Express possible side lengths algebraically.',
  'Create one quadratic from two binomial factors and factorize it back.',
  'Explain why x²+9 cannot use difference-of-squares over real integers.',
  'Verify at least five factorisations by full expansion.'
 ],
 mastery:{criterion:'Learner chooses the correct factorisation method, handles common factors/grouping/identities/quadratics including a≠1, and verifies by expansion with at least85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-algebraic-processes-algebraic-operations-2',classLevel:'JSS3',subject:'Mathematics',topic:'Simple equations involving fractions',source:{authority:'NERDC',url:sourceUrl,page:31},
 objectives:['Solve simple equations involving fractions','Translate word problems into simple fractional equations and solve them'],
 prerequisites:['equivalent fractions','LCM of denominators','inverse operations','JSS2 simple linear equations'],
 teaching:[
  'A FRACTIONAL EQUATION contains one or more fractions with an unknown. The equality must be preserved throughout the solution.',
  'THE SAFEST FIRST STEP is usually to multiply EVERY TERM on BOTH SIDES by the LCM of the denominators. This clears fractions without changing the solution.',
  'WHY LCM WORKS: each denominator divides the LCM, so the fractional coefficients become whole-number coefficients.',
  'ONE FRACTION TERM. x/4=7. Multiply both sides by4 to get x=28.',
  'FRACTION PLUS CONSTANT. x/3+5=11. Multiply every term by3 or first isolate x/3. Both methods are valid if balance is preserved.',
  'MULTIPLE DENOMINATORS. x/4+x/6=5 uses LCM12. Multiply all terms:3x+2x=60.',
  'NEGATIVE FRACTION TERMS require careful signs. In x/2−x/5=9, LCM10 gives5x−2x=90, not5x+2x.',
  'FRACTION ON BOTH SIDES. x/3+2=x/6+7 can be cleared by LCM6 across the entire equation.',
  'BRACKETS IN NUMERATORS. (x+3)/5=4 means the entire numerator x+3 is divided by5.',
  'TWO FRACTIONAL EXPRESSIONS. (2x−1)/3=(x+5)/2 can be solved by multiplying all terms by6; cross multiplication is only a shortcut because each side is a single fraction.',
  'VARIABLE DENOMINATOR RESTRICTION. If a denominator contains x, values making denominator zero are forbidden. State restrictions before algebra.',
  'DO NOT CROSS-MULTIPLY A SUM such as x/3+2=5. Cross multiplication applies only to one fraction equal to one fraction.',
  'WORD PROBLEMS: define unknown, translate fractional relationships, clear denominators, solve, then interpret with units.',
  'AGE/PART problems often use phrases such as one-half, one-third, three-quarters of a number.',
  'CHECK BY SUBSTITUTION into the ORIGINAL fractional equation, not only the cleared equation.',
  'PERMANENT METHOD: identify denominators→LCM→multiply every term→simplify→solve→substitute back.'
 ],
 workedExamples:[
  'x/4=7→multiply by4→x=28.',
  'x/3+2=7→multiply by3: x+6=21→x=15.',
  'x/5−3=9→x−15=45→x=60.',
  'x/4+x/6=5→LCM12:3x+2x=60→5x=60→x=12.',
  'x/2−x/5=9→LCM10:5x−2x=90→3x=90→x=30.',
  'x/3+2=x/6+7→LCM6:2x+12=x+42→x=30.',
  '(x+3)/5=4→x+3=20→x=17.',
  '(2x−1)/3=5→2x−1=15→x=8.',
  '(2x−1)/3=(x+5)/2→multiply by6:2(2x−1)=3(x+5)→4x−2=3x+15→x=17.',
  'x/2+(x−3)/4=6→LCM4:2x+x−3=24→3x=27→x=9.',
  '(x+1)/3−(x−2)/6=4→LCM6:2x+2−x+2=24→x+4=24→x=20.',
  '3x/4−x/8=10→LCM8:6x−x=80→x=16.',
  'WORD: one third of a number plus5 is13. x/3+5=13→x/3=8→x=24.',
  'WORD: half a number reduced by7 is18. x/2−7=18→x/2=25→x=50.',
  'WORD: three quarters of a number is27. 3x/4=27→3x=108→x=36.',
  'CHECK x=12 in x/4+x/6=5:3+2=5, correct.',
  'RESTRICTION EXAMPLE: 4/(x−2)=2 requires x≠2 before solving.',
  'For 4/(x−2)=2: multiply by x−2→4=2x−4→x=4; restriction satisfied.'
 ],
 misconceptions:[
  'multiplying only fractional terms by LCM',
  'forgetting right side when clearing denominators',
  'cross-multiplying a sum',
  'losing negative signs',
  'treating numerator brackets as separate fractions',
  'using wrong LCM',
  'ignoring denominator restrictions',
  'stopping before interpreting a word problem',
  'checking only the transformed equation',
  'cancelling across addition illegally'
 ],
 guidedPractice:[
  'Solve x/6=8.',
  'Solve x/4+3=10.',
  'Solve x/3−x/9=8.',
  'Solve x/2+x/5=14.',
  'Solve x/4+3=x/8+8.',
  'Solve (x−5)/3=7.',
  'Solve (3x+1)/4=10.',
  'Solve (x+2)/3=(x+8)/5.',
  'Solve x/3+(x−2)/6=5.',
  'Translate and solve: one quarter of a number plus9 is16.',
  'Translate and solve: two thirds of a number is30.',
  'Verify four answers by substitution.'
 ],
 independentPractice:[
  'Solve x/7=9.',
  'Solve x/5+4=12.',
  'Solve x/3−5=7.',
  'Solve x/4+x/8=9.',
  'Solve x/2−x/6=12.',
  'Solve x/3+4=x/6+9.',
  'Solve (x+7)/4=6.',
  'Solve (2x−3)/5=7.',
  'Solve (x−1)/2=(x+5)/4.',
  'Solve (3x+2)/4=(x+6)/2.',
  'Solve x/5+(x+2)/10=8.',
  'Solve (x+3)/6−(x−1)/3=2.',
  'One fifth of a number plus12 is20. Find the number.',
  'Three quarters of a number minus5 is25. Find the number.',
  'Half a number plus one third of the same number is35. Find it.',
  'A learner spends one quarter of money on transport and has ₦9,000 left from ₦12,000. Verify the fractional relationship.',
  'State restrictions and solve 6/(x−1)=3.',
  'State restrictions and solve 10/(x+2)=5.',
  'Verify at least five solutions in the original equations.',
  'Explain why cross multiplication is invalid for x/3+2=5.'
 ],
 mastery:{criterion:'Learner clears denominators legally, solves single/multiple-fraction equations including brackets and simple variable denominators, models word problems and verifies original equations with at least85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-algebraic-processes-algebraic-operations-3',classLevel:'JSS3',subject:'Mathematics',topic:'Simultaneous linear equations',source:{authority:'NERDC',url:sourceUrl,page:32},
 objectives:['Compile tables of values for two linear functions','Solve simultaneous linear equations graphically','Solve by elimination','Apply elimination to real-life problems','Solve by substitution','Apply substitution to real-life problems'],
 prerequisites:['linear equations','Cartesian graphs','substitution','signed-number arithmetic'],
 teaching:[
  'SIMULTANEOUS EQUATIONS describe two conditions that must both be true. The solution is one ordered pair (x,y) satisfying both equations.',
  'GRAPHICAL METHOD: rewrite if necessary, create value tables, plot both lines on same axes, then read their point of intersection.',
  'A GRAPHICAL ANSWER can be approximate because drawing and scale introduce measurement error.',
  'TABLES OF VALUES should use enough x-values to establish each straight line accurately; two points define a line, but three or more help catch arithmetic mistakes.',
  'ELIMINATION works by adding or subtracting equations so one variable disappears.',
  'IF COEFFICIENTS ALREADY MATCH, add/subtract directly. If not, multiply one or both entire equations by suitable constants first.',
  'WHEN SCALING AN EQUATION, every term including the constant must be multiplied.',
  'SUBSTITUTION isolates one variable in one equation and replaces it in the other. It is efficient when a variable has coefficient1 or is easy to isolate.',
  'AFTER FINDING ONE VARIABLE, substitute back into either ORIGINAL equation to obtain the second.',
  'CHECK THE ORDERED PAIR in both original equations.',
  'PARALLEL DISTINCT LINES have no simultaneous solution because they never intersect.',
  'IDENTICAL LINES represent infinitely many solutions because every point on one lies on the other.',
  'WORD PROBLEMS require two genuinely independent relationships. Define both unknowns with units first.',
  'NUMBER PROBLEMS may use sum/difference relationships; price problems use count and total cost; age and geometry problems use their own relationships.',
  'CHOOSE METHOD INTELLIGENTLY: graph for visual meaning, elimination for convenient coefficients, substitution for easy isolation.',
  'PERMANENT METHOD: define equations→choose method→solve carefully→recover second variable→check both equations→interpret context.'
 ],
 workedExamples:[
  'ELIMINATION EASY: x+y=7, x−y=1. Add→2x=8→x=4; then y=3.',
  'ELIMINATION SUBTRACT:2x+y=11,2x−y=5. Subtract second from first→2y=6→y=3; x=4.',
  'ELIMINATION SCALE ONE:2x+3y=12, x+y=5. Multiply second by2:2x+2y=10. Subtract→y=2, then x=3.',
  'ELIMINATION SCALE BOTH:2x+3y=13,3x−2y=4. Multiply first by2→4x+6y=26; second by3→9x−6y=12; add→13x=38→x=38/13; then substitute.',
  'SUBSTITUTION: y=x+2 and2x+y=11→2x+x+2=11→x=3,y=5.',
  'SUBSTITUTION: x=2y−1 and x+y=8→2y−1+y=8→3y=9→y=3,x=5.',
  'SUBSTITUTION REARRANGE: x+y=10 and3x−y=6. y=10−x; substitute3x−(10−x)=6→4x=16→x=4,y=6.',
  'GRAPH TABLE: y=x+1 for x=0,1,2 gives1,2,3. y=−x+5 gives5,4,3. Intersection at(2,3).',
  'GRAPH CHECK: point(2,3) satisfies y=x+1 and y=−x+5.',
  'NO SOLUTION: y=2x+1 and y=2x−3 have same gradient but different intercepts, so parallel.',
  'INFINITE SOLUTIONS:2x+2y=10 and x+y=5 are same line after dividing first by2.',
  'TICKETS: adults ₦500, students ₦300,20 tickets total ₦7,600. a+s=20;500a+300s=7600→a=8,s=12.',
  'NUMBERS: sum15,difference3. x+y=15,x−y=3→2x=18→x=9,y=6.',
  'PRICES:2 notebooks+1 pen=₦1,900;1 notebook+2 pens=₦2,000. Solve2n+p=1900,n+2p=2000→n=600,p=700.',
  'AGES: mother+daughter=50; mother is22 years older. m+d=50,m−d=22→m=36,d=14.',
  'GEOMETRY: rectangle perimeter30 gives l+w=15; l−w=3→l=9,w=6.',
  'CHECK example x=3,y=5 in2x+y=11→11 and y=x+2→5.',
  'METHOD COMPARISON: y=3x−1 with x+y=11 is fastest by substitution because y is already isolated.'
 ],
 misconceptions:[
  'solving only one equation',
  'finding point on one graph only',
  'using different scales carelessly on graph',
  'scaling only part of an equation',
  'adding/subtracting signs incorrectly',
  'forgetting to recover second variable',
  'not checking both equations',
  'using two dependent equations in a word problem',
  'assuming every pair has one solution',
  'misreading graph intersection because of poor scale'
 ],
 guidedPractice:[
  'Solve x+y=9,x−y=3 by elimination.',
  'Solve2x+y=8,x−y=1.',
  'Solve3x+2y=16,x+y=6.',
  'Solve2x+3y=13,4x−y=5.',
  'Solve y=2x+1,x+y=10 by substitution.',
  'Solve x=3y−2,2x+y=16.',
  'Make tables and graph y=x+2,y=−x+6.',
  'Check graph intersection algebraically.',
  'Identify whether y=2x+3,y=2x−1 has one/no/infinite solutions.',
  'Model and solve a ticket-price problem.',
  'Model and solve sum/difference of two numbers.',
  'Verify four ordered pairs in both originals.'
 ],
 independentPractice:[
  'Solve x+y=12,x−y=4.',
  'Solve2x+y=9,2x−y=3.',
  'Solve3x+y=14,x+y=8.',
  'Solve2x+5y=19,3x−y=5.',
  'Solve4x+3y=18,2x−y=4.',
  'Solve y=x+4,2x+y=13.',
  'Solve x=2y+1,x+y=13.',
  'Solve y=10−x,3x−2y=5.',
  'Graph y=2x+1 and y=−x+7.',
  'Graph y=x−2 and y=3x−6.',
  'Determine solution type for y=4x+2 and y=4x−5.',
  'Determine solution type for2x+2y=8 and x+y=4.',
  'Two numbers sum28 and differ6. Find them.',
  'A cinema sells adult tickets₦1,200 and child tickets₦800;30 tickets total₦30,400. Find each count.',
  'Three notebooks and two pens cost₦3,100; two notebooks and one pen cost₦1,900. Find prices.',
  'A rectangle has perimeter44cm and length4cm more than width. Find dimensions.',
  'A mother and son total54 years; mother is30 years older. Find ages.',
  'Choose the most efficient method for three supplied systems and justify.',
  'Check at least five solutions in both original equations.',
  'Explain graphically why parallel lines give no simultaneous solution.'
 ],
 mastery:{criterion:'Learner solves systems graphically, by elimination and substitution, recognises no/infinite-solution cases, models real contexts and verifies both equations with at least85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-mensuration-and-geometry-shapes-1',classLevel:'JSS3',subject:'Mathematics',topic:'Similar Shapes',source:{authority:'NERDC',url:sourceUrl,page:33},
 objectives:['Identify similar triangles, rectangles, squares, cubes and cuboids','Recognize similar shapes in the environment','Enlarge figures using scale factors','Calculate corresponding lengths, areas and volumes','Solve quantitative-reasoning problems involving similarity'],
 prerequisites:['ratio and proportion','scale drawing','area and volume','properties of common shapes'],
 teaching:[
  'SIMILAR SHAPES have the same shape but may differ in size. Corresponding angles are equal and corresponding lengths are in a constant ratio.',
  'CONGRUENT shapes are same shape AND same size; similarity allows a non-unit scale factor.',
  'CORRESPONDENCE must be established before ratios. Match vertices by equal angles and corresponding side positions.',
  'LINEAR SCALE FACTOR k=image length/original corresponding length.',
  'IF k>1, enlargement; if0<k<1, reduction; if k=1, congruent size.',
  'LENGTHS change by k.',
  'AREAS change by k² because two perpendicular dimensions each scale by k.',
  'VOLUMES change by k³ because three dimensions each scale by k.',
  'AREA RATIO can recover linear factor by square root: if area ratio=25:9, linear ratio=5:3.',
  'VOLUME RATIO can recover linear factor by cube root: if volume ratio=64:27, linear ratio=4:3.',
  'SIMILAR TRIANGLES may be established by equal corresponding angles and proportional sides.',
  'ALL SQUARES are similar because all angles are90° and side ratios match. Not all rectangles are similar because length:width ratios may differ.',
  'CUBES are all similar; cuboids are similar only when corresponding length:width:height ratios match.',
  'COORDINATE ENLARGEMENT about origin by factor k sends(x,y)→(kx,ky).',
  'REAL-LIFE MODELS include maps, photographs, models and scale drawings; always identify direction of scale factor.',
  'PERMANENT CHECK: label correspondence, write ratio direction, then use k/k²/k³ according to dimension.'
 ],
 workedExamples:[
  'Triangles sides3,4,5 and6,8,10 have scale factor2 and are similar.',
  'Triangles sides4,6,8 and6,9,12 have common ratio1.5 and are similar.',
  'Rectangles2×5 and4×10 are similar because side ratios both double.',
  'Rectangles3×5 and6×8 are not similar because ratios do not match.',
  'Small side7cm corresponds to large side21cm→k=3.',
  'If k=2.5 and original side8cm, image side20cm.',
  'Reduction k=0.4 of15cm gives6cm.',
  'Area original12cm²,k=3→image area12×9=108cm².',
  'Area ratio49:16→linear ratio7:4.',
  'Cube side ratio2:5→volume ratio8:125.',
  'Volume original27cm³,k=2→216cm³.',
  'Volume ratio64:27→linear ratio4:3.',
  'Coordinate(2,−3) enlarged factor2 about origin→(4,−6).',
  'Triangle vertices(1,1),(3,1),(1,4), factor3→(3,3),(9,3),(3,12).',
  'All squares of sides2cm and7cm are similar with k=3.5.',
  'Cuboids2×3×4 and4×6×8 are similar with k=2.',
  'Cuboids2×3×4 and4×6×10 are not similar because third ratio differs.',
  'Map scale1:50,000: a5cm map distance represents250,000cm=2.5km; this is a linear similarity scale.'
 ],
 misconceptions:[
  'assuming same shape visually without checking ratio',
  'matching wrong corresponding sides',
  'reversing scale factor direction',
  'using k for area',
  'using k² for volume',
  'taking square root of volume ratio',
  'assuming all rectangles are similar',
  'assuming all cuboids are similar',
  'forgetting centre/origin in coordinate enlargement',
  'mixing units before forming ratios'
 ],
 guidedPractice:[
  'Test similarity for triangles5,7,9 and10,14,18.',
  'Test rectangles4×6 and10×15.',
  'Find missing side when k=3.',
  'Find k from corresponding sides8 and14.',
  'Find image area when k=2.5 and original area16.',
  'Find linear ratio from area ratio81:25.',
  'Find volume ratio for linear ratio3:4.',
  'Find linear ratio from volume ratio125:8.',
  'Enlarge three coordinate points by factor2 about origin.',
  'Reduce coordinates by factor1/2.',
  'Compare two cuboids for similarity.',
  'Explain why area uses k² and volume k³.'
 ],
 independentPractice:[
  'Determine whether sides3,5,7 and6,10,14 are similar sets.',
  'Determine whether rectangles6×8 and9×12 are similar.',
  'Determine whether rectangles6×8 and9×11 are similar.',
  'Find missing corresponding side if4cm maps to10cm and another side is7cm.',
  'A photo enlarged k=1.5 from12cm width: find new width.',
  'A shape reduced k=0.6 from25cm side: find image side.',
  'Area32cm² enlarged k=4: find image area.',
  'Area ratio36:49: find linear ratio.',
  'Cube volume125cm³ enlarged k=2: find image volume.',
  'Volume ratio216:27: find linear ratio.',
  'Enlarge(−2,3),(1,4),(5,−1) by factor3.',
  'Reduce(8,6),(−4,10) by factor1/2.',
  'Show all squares are similar.',
  'Give counterexample proving not all rectangles similar.',
  'Test cuboids3×4×5 and6×8×10.',
  'Test cuboids3×4×5 and6×8×12.',
  'A model car scale1:20 has length22cm. Find real length.',
  'A map at1:100,000 shows7.5cm. Find real distance in km.',
  'Explain difference between congruent and similar.',
  'Create a similarity problem involving k,k² andk³ and solve it.'
 ],
 mastery:{criterion:'Learner establishes correspondence, uses scale factors for length/area/volume, recovers linear ratios, handles coordinate and real-life scaling, and achieves at least85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-mensuration-and-geometry-shapes-2',classLevel:'JSS3',subject:'Mathematics',topic:'Trigonometry',source:{authority:'NERDC',url:sourceUrl,page:33},
 objectives:['Identify sine, cosine and tangent of an acute angle in a right-angled triangle','Use trigonometric ratios to find unknown distances and lengths','Apply trigonometric ratios to practical and word problems'],
 prerequisites:['right-angled triangles','Pythagoras theorem','ratio','angles and calculator use'],
 teaching:[
  'TRIGONOMETRY here studies ratios of sides in a RIGHT-ANGLED triangle relative to a chosen acute angle θ.',
  'NAME THE SIDES RELATIVE TO θ. HYPOTENUSE is always opposite the90° angle. OPPOSITE is across from θ. ADJACENT touches θ but is not the hypotenuse.',
  'THE SAME SIDE can be opposite for one acute angle and adjacent for the other. The hypotenuse never changes.',
  'SOH: sinθ=opposite/hypotenuse.',
  'CAH: cosθ=adjacent/hypotenuse.',
  'TOA: tanθ=opposite/adjacent.',
  'CHOOSE THE RATIO that contains the known side(s) and the unknown side. Do not choose by memory alone.',
  'FINDING A SIDE. Write ratio equation first, substitute numbers, then rearrange algebraically before using calculator.',
  'FINDING AN ANGLE uses inverse trigonometric functions: θ=sin⁻¹(...), cos⁻¹(...), or tan⁻¹(...).',
  'CALCULATOR MUST BE IN DEGREE MODE for angles given/required in degrees.',
  'ANGLE OF ELEVATION is measured upward from horizontal; angle of depression downward from horizontal.',
  'DRAW A DIAGRAM for word problems: ground line, vertical object, line of sight, right angle and given angle.',
  'EYE HEIGHT may need adding or subtracting if observer’s eye is above ground.',
  'LADDER PROBLEMS: ladder is usually hypotenuse; vertical height opposite angle at ground; ground distance adjacent.',
  'SHADOW PROBLEMS often use tanθ=height/shadow length when angle of elevation is known.',
  'PYTHAGORAS vs TRIG: if two sides are known and a third side is required, Pythagoras may be simpler. Trig is essential when an acute angle is involved.',
  'ROUND ONLY AT THE END unless instructed, to avoid accumulated error.',
  'REASONABLENESS: hypotenuse must be longest; sin/cos values for acute angles lie between0 and1; lengths must be positive.',
  'PERMANENT METHOD: sketch→mark90° and θ→label O/A/H→choose ratio→form equation→solve→units→reasonableness check.'
 ],
 workedExamples:[
  'If O=6,H=10, sinθ=6/10=0.6.',
  'If A=8,H=10, cosθ=0.8.',
  'If O=9,A=12, tanθ=9/12=0.75.',
  'Find O when H=12,θ=30°: O=12sin30°=6.',
  'Find A when H=15,θ=40°: A=15cos40°≈11.49.',
  'Find O when A=20,θ=35°: O=20tan35°≈14.00.',
  'Find H when O=8,θ=25°: sin25°=8/H→H=8/sin25°≈18.93.',
  'Find H when A=9,θ=50°: cos50°=9/H→H≈14.00.',
  'Find A when O=7,θ=32°: tan32°=7/A→A=7/tan32°≈11.20.',
  'Find angle if O=6,H=10: θ=sin⁻¹(0.6)≈36.9°.',
  'Find angle if A=12,H=15: θ=cos⁻¹(12/15)≈36.9°.',
  'Find angle if O=8,A=10: θ=tan⁻¹(0.8)≈38.7°.',
  'Ladder5m at60° to ground: height=5sin60°≈4.33m.',
  'Pole20m away, elevation35°: height=20tan35°≈14.0m ignoring eye height.',
  'Observer eye1.6m high, 25m from building, elevation40°: height above eye=25tan40°≈20.98m; total≈22.58m.',
  'Shadow12m, elevation50°: height=12tan50°≈14.30m.',
  'If a right triangle has legs9,12, hypotenuse15, angle opposite9 has sin=9/15=0.6, cos=12/15=0.8, tan=9/12=0.75.',
  'Reasonableness: calculated hypotenuse6m when one leg8m is impossible; recheck equation/calculator.'
 ],
 misconceptions:[
  'naming opposite/adjacent without chosen angle',
  'calling longest-looking drawn side hypotenuse without checking90°',
  'using wrong ratio',
  'using radian mode',
  'forgetting inverse function for unknown angle',
  'adding eye height when it should be subtracted or vice versa',
  'rounding too early',
  'forgetting units',
  'accepting hypotenuse shorter than a leg',
  'using trig in a non-right triangle at this level without justification'
 ],
 guidedPractice:[
  'Label O/A/H for three triangles relative to marked angles.',
  'Find opposite whenH=14,θ=28°.',
  'Find adjacent whenH=18,θ=62°.',
  'Find opposite whenA=16,θ=37°.',
  'Find hypotenuse whenO=9,θ=35°.',
  'Find adjacent whenO=5,θ=22°.',
  'Find θ whenO=7,H=13.',
  'Find θ whenA=9,H=12.',
  'Find θ whenO=11,A=15.',
  'Solve a ladder problem.',
  'Solve a pole-angle-of-elevation problem.',
  'Solve a building problem including1.5m eye height.'
 ],
 independentPractice:[
  'Find sinθ for O=8,H=17.',
  'Find cosθ for A=15,H=17.',
  'Find tanθ for O=12,A=5.',
  'Find O ifH=20,θ=42°.',
  'Find A ifH=25,θ=33°.',
  'Find O ifA=18,θ=27°.',
  'Find H ifO=11,θ=48°.',
  'Find H ifA=16,θ=55°.',
  'Find A ifO=13,θ=38°.',
  'Find θ ifO=9,H=15.',
  'Find θ ifA=7,H=10.',
  'Find θ ifO=14,A=20.',
  'A6m ladder makes65° with ground. Find height reached.',
  'A point30m from tower sees top at32°. Find tower height ignoring eye height.',
  'Observer eye1.7m,20m from building, elevation45°. Find total height.',
  'A tree casts18m shadow when elevation is40°. Find height.',
  'Choose between Pythagoras and trig for three supplied right-triangle problems and justify.',
  'Explain why hypotenuse identification must come before SOHCAHTOA.',
  'Check one side answer using Pythagoras where enough information is available.',
  'State calculator mode and rounding used for five answers.'
 ],
 mastery:{criterion:'Learner identifies O/A/H relative to angle, chooses correct SOHCAHTOA ratio, finds sides and angles, solves elevation/ladder/shadow problems including eye height and checks plausibility with at least85% accuracy.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-mensuration-and-geometry-shapes-3',classLevel:'JSS3',subject:'Mathematics',topic:'Area of plane figures',source:{authority:'NERDC',url:sourceUrl,page:34},
 objectives:['Find areas of triangles','Find areas of parallelograms','Find areas of trapezia','Find areas of circles and sectors','Solve word problems involving area','Solve quantitative-reasoning problems involving areas'],
 prerequisites:['length measurement','perimeter versus area','fractions and decimals','circle vocabulary and π'],
 teaching:['Area measures surface in square units. The triangle formula A=1/2 bh can be derived as half a matching parallelogram; the perpendicular height must correspond to the chosen base.','A parallelogram has area bh because it can be rearranged into a rectangle with the same base and perpendicular height. A trapezium has area 1/2(a+b)h where a and b are the parallel sides.','A circle has area πr². A sector is a fraction of a circle, so sector area=(θ/360°)πr² for central angle θ.','Composite area problems should be decomposed into familiar shapes. Mark dimensions and units, compute each component, then add or subtract as the diagram requires.','Deriving and explaining formulas helps learners distinguish height, slant length, radius, diameter and parallel sides rather than simply substituting numbers.'],
 workedExamples:['Triangle b=12 cm,h=7 cm: A=42 cm².','Trapezium parallel sides 8 cm and 14 cm, height 5 cm: A=1/2(22)(5)=55 cm².','Circle r=7 cm: A=49π≈154 cm² using 22/7 where appropriate.','90° sector of radius 8 cm: A=90/360×π×64=16π≈50.3 cm².'],
 misconceptions:['using a sloping side as perpendicular height','forgetting to square the radius','using diameter in place of radius','using θ/180 instead of θ/360 for sector area','reporting area in linear units'],
 guidedPractice:['Derive triangle area from a rectangle sketch; calculate one triangle, parallelogram, trapezium, circle and sector.'],
 independentPractice:['Fifteen area problems including composite shapes and word contexts; require diagrams and square-unit answers.'],
 mastery:{criterion:'At least 80% across all listed figures, correct identification of perpendicular heights/radii and correct square units.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-mensuration-and-geometry-shapes-4',classLevel:'JSS3',subject:'Mathematics',topic:'Construction',source:{authority:'NERDC',url:sourceUrl,page:35},
 objectives:['Construct a 45° angle','Construct a 30° angle','Copy a given angle using ruler and compasses','Construct simple plane shapes accurately'],
 prerequisites:['basic ruler-and-compass construction','60° and 90° constructions','angle bisectors','triangle construction'],
 teaching:['Geometric construction uses an unmarked straightedge and compasses to create exact relationships. Keep arcs visible because they are evidence of the construction logic.','Construct 45° by first constructing a 90° angle and bisecting it. Construct 30° by constructing 60° and bisecting it.','To copy an angle, draw an arc across both arms of the original, reproduce the same arc radius at the new vertex, transfer the chord distance between the two intersections, then draw the second arm.','Simple plane shapes can be built from known sides, perpendiculars, parallel relationships, equal radii and constructed angles. Always verify dimensions after construction.'],
 workedExamples:['At point A on a line, construct a perpendicular to obtain 90°, then bisect to obtain 45°.','Construct an equilateral-triangle 60° at a point, then bisect to obtain 30°.','Copy a 73° given angle without setting a protractor by transferring its arc and chord.'],
 misconceptions:['measuring 45° or 30° directly with a protractor when a construction is required','changing compass width during a transfer step','erasing arcs before verification','assuming a sketch is a construction without geometric evidence'],
 guidedPractice:['Construct 45° and 30° from a common baseline; copy a supplied angle and verify with a protractor only after construction.'],
 independentPractice:['Complete six constructions: two target angles, two copied angles and two simple plane shapes with labelled dimensions and visible arcs.'],
 mastery:{criterion:'All required constructions are valid, within normal drawing tolerance, labelled and supported by visible compass/straightedge evidence.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-everyday-statistics-data-collection-and-presentation-1',classLevel:'JSS3',subject:'Mathematics',topic:'Measure of central tendency',source:{authority:'NERDC',url:sourceUrl,page:36},
 objectives:['Review mean, median and mode','Calculate the median of a data set','Find the mode of a data set','Calculate the mean of a data set','Find the range of a data set','Apply measures of central tendency and range to analyse information'],
 prerequisites:['JSS1/JSS2 data collection and tables','addition and division','ordering numbers'],
 teaching:['Mean, median and mode describe different aspects of a data set. Mean uses every value, median is the middle after ordering, and mode is the most frequent value. None is automatically “best” for every situation.','For an odd number of ordered values, the median is the middle value. For an even number, it is the mean of the two middle values. Data must be ordered first.','The mode may be one value, more than one value, or absent if no value repeats more than others. Range=max−min describes spread, not centre.','Outliers can pull the mean strongly while leaving the median relatively stable. Interpretation should therefore compare the measures and connect them to the context rather than merely calculate them.'],
 workedExamples:['Data 2,4,4,5,10: mean=5, median=4, mode=4, range=8.','Data 3,5,7,9: median=(5+7)/2=6.','Salaries 40,42,43,45,200 (thousands) have mean 74 but median 43; the median better represents a typical worker because of the outlier.'],
 misconceptions:['finding median before ordering','dividing mean by the wrong number of observations','calling the largest value the mode','confusing range with a central measure','assuming there must be exactly one mode'],
 guidedPractice:['For two small data sets calculate mean, median, mode and range, then decide which measure best represents a “typical” value.'],
 independentPractice:['Ten data sets plus four interpretation questions involving outliers, multiple modes and comparison of groups.'],
 mastery:{criterion:'At least 85% computational accuracy plus correct interpretation of when mean/median/mode is informative.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-everyday-statistics-data-collection-and-presentation-2',classLevel:'JSS3',subject:'Mathematics',topic:'Data presentation',source:{authority:'NERDC',url:sourceUrl,page:36},
 objectives:['Represent information accurately on pie charts','Interpret information presented on pie charts'],
 prerequisites:['frequency tables','fractions, percentages and ratios','angles and 360°','protractor use'],
 teaching:['A pie chart represents a whole as 360°. Convert each category to a sector angle using frequency/total×360°. The angles must total 360° apart from small rounding effects.','When percentages are given, sector angle=percentage/100×360°. When a sector angle and total are known, category frequency=angle/360×total.','Construction quality matters: label categories, use a sensible key where needed, draw angles from the centre and avoid visual exaggeration.','Interpretation should compare proportions, recover counts where possible and state only conclusions supported by the chart. A pie chart is poor for showing change over time, so choose presentation methods with purpose.'],
 workedExamples:['In a class of 40, 12 choose football: angle=12/40×360°=108°.','A 72° sector represents 20% of the whole because 72/360=0.2. In a survey of 250 people that equals 50 people.','Sector angles 90°,126°,54° and 90° sum to 360°, corresponding to 25%,35%,15%,25%.'],
 misconceptions:['using frequency as the angle','forgetting total frequency in the denominator','drawing sectors from the circumference instead of the centre','claiming the largest sector proves a cause','accepting angles that do not total 360°'],
 guidedPractice:['Convert a five-category frequency table to angles, check the sum, sketch the pie chart and answer five interpretation questions.'],
 independentPractice:['Construct two complete pie charts from raw/frequency data and solve ten reverse-reading questions involving angle, percentage and frequency.'],
 mastery:{criterion:'At least 85% accuracy in angle/frequency conversion, internally consistent 360° charts and evidence-based interpretation.',status:'DEEP_WHEN_PASSED'},boardReady:true
}
];

export function getJss3MathDeepLesson(topicId:string){return jss3MathematicsDeepLessons.find(x=>x.topicId===topicId)}
