import type { TutorPlan, TutorUnit } from './tutorCurriculum';

export type Jss3EnglishQuestion = {
  id: string; prompt: string; options: string[]; correctAnswer: string; explanation: string;
};
export type Jss3EnglishLesson = {
  topic: string; strand: 'Reading'|'Writing'|'Listening and Speaking'|'Grammatical Accuracy'|'Literature';
  authority: string; objectives: string[]; plan: TutorPlan; questions: Jss3EnglishQuestion[];
  performanceTasks?: string[];
};
const U=(title:string,body:string):TutorUnit=>({title,body});
const Q=(id:string,prompt:string,options:string[],correctAnswer:string,explanation:string):Jss3EnglishQuestion=>({id,prompt,options,correctAnswer,explanation});

export const jss3CriticalEvaluation: Jss3EnglishLesson = {
 topic:'Reading for Critical Evaluation', strand:'Reading',
 authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:[
  'Read critically and explain what critical reading requires.',
  'Distinguish verifiable facts from opinions and mixed claims.',
  'Make deductions that are supported by information presented.',
  'Recognise words and statements that indicate bias or balance.',
  'Explain the meaning and purpose of road danger signs and interpret their warnings.',
  'Apply critical evaluation to passages on road safety, drug use, consumer rights and other relevant issues.'
 ],
 plan:{topic:'Reading for Critical Evaluation',objective:'Understand, question and evaluate what a writer says; separate fact from opinion; detect bias or balance; and make evidence-based deductions.',units:[
 U('Start with the meaning','Critical reading means understanding a text and then examining its claims instead of accepting every sentence automatically. Ask: What is the writer saying? What evidence supports it? Is it a fact, an opinion or a mixture? Is the language fair? What conclusion can I safely draw? Example: “Our school introduced a reading hour in January, and it is the best programme ever.” The date of introduction can be checked; “best programme ever” is a judgement. A critical reader separates the two claims.'),
 U('Why critical reading matters','Critical reading protects you from exaggeration, weak reasoning and one-sided persuasion. If an advert says, “Five thousand students bought this drink, so it certainly makes students intelligent,” the sales figure—even if true—does not prove the intelligence claim. Popularity is not proof of the advertised effect. Critical readers ask whether the evidence actually supports the conclusion.'),
 U('Fact: what it really means','A fact is a claim whose truth or falsity can be checked using evidence. “The meeting began at 9:00 a.m.” is factual because records or witnesses can settle it. A factual claim can still be wrong: “Nigeria became independent in 1970” is false, but it is still a factual claim because objective evidence can test it. Do not confuse “fact” with “a statement I agree with.”'),
 U('Opinion and judgement','An opinion expresses belief, preference, evaluation or judgement: “English is the easiest subject.” Words such as best, worst, beautiful, boring, excellent, probably and I believe often signal judgement, but context matters. “The doctor said the patient should rest” reports a checkable event even though it contains “should”. Always judge the whole claim.'),
 U('Mixed statements','One sentence can contain fact and opinion. “The library contains 5,000 books and is the most beautiful building in town.” The number of books can be counted; beauty is subjective. In examinations, split a long sentence into its individual claims before classifying it.'),
 U('Evidence and support','Evidence is information offered to support a claim. “Attendance improved after free buses were introduced” is a claim. “Records show attendance rose from 78% to 91%” supplies evidence of improvement. But the figures alone do not prove the buses were the only cause. Other changes may have occurred. Never stretch evidence beyond what it establishes.'),
 U('Deduction: conclusion from clues','A deduction is a conclusion logically supported by information given. “Tunde entered with a wet umbrella; water dripped from his shoes; other pupils wore raincoats.” A reasonable deduction is that rain was falling or had recently fallen. “Tunde’s mother bought the umbrella yesterday” is a guess because the passage gives no supporting clue. Use the rule: evidence + reasoning = deduction; evidence + imagination = guess.'),
 U('Explicit and implied meaning','Explicit information is stated directly: “Ada arrived at 8:30.” Implied information must be inferred: “Ada entered while the teacher was explaining the second exercise.” It is reasonable to infer that teaching had already started. A good inference stays close to the clues and does not invent details.'),
 U('Bias','Bias is an unfair or one-sided presentation. Compare: “Musa presented three proposals, while careless Tobi wasted everyone’s time with another ridiculous speech.” The labels “careless”, “wasted” and “ridiculous” reveal hostility toward Tobi. Bias can appear through loaded words, selective evidence, unfair labels or presenting only one side. A biased passage can still contain facts; evaluate each claim separately.'),
 U('Balance','A balanced presentation represents relevant viewpoints or evidence fairly. “Some parents support smartphones because learners can access dictionaries quickly; others worry that unrestricted use distracts learners.” This does not force both sides to have exactly the same number of words; it avoids unfairly misrepresenting a relevant side.'),
 U('Loaded language and absolute claims','Words can push emotions before evidence is considered. “The council imposed another ridiculous rule on helpless motorists” is more loaded than “The council introduced a traffic rule.” Also question absolute words such as all, always, never, everyone, completely, certainly and only. “Every teenager with a smartphone performs poorly” requires far stronger evidence than “Excessive use can reduce study time for some learners.”'),
 U('Purpose and viewpoint','Ask why the text exists. A writer may inform, explain, warn, instruct, persuade or entertain. “Reduce speed when approaching the school crossing” warns/instructs. “Our product is unquestionably the smartest choice” persuades. Purpose does not automatically make a text false; it tells you what kinds of claims and language deserve close examination.'),
 U('Road danger signs','NERDC places road danger signs inside this topic because signs require interpretation and sensible deduction. A warning sign tells a road user that a hazard or condition lies ahead: a bend, junction, pedestrian/school crossing, road works, narrowing road, animals or another danger. If a sign warns of a sharp bend, you may infer that the driver should reduce speed and maintain control. You may NOT infer that an accident has definitely happened there.'),
 U('Worked passage: road safety','Residents complained about fast vehicles near a school. The authority installed warning signs and repainted a pedestrian crossing. A residents’ group then called the road “completely safe”, while school officials continued asking drivers to slow down. Facts: signs were installed and the crossing repainted. Opinion/overclaim: “completely safe”. Reasonable deduction: measures were taken to improve safety. Unsupported deduction: “No accident can ever occur there again.”'),
 U('Worked passage: drug use','A health centre reported treating 38 teenagers for problems linked to misuse of medicines and began school visits. A worker called education “one of the most important” protections; students asked that talks also explain how to seek help privately. The treatment figure is a checkable report; “most important” is evaluation. We may infer the centre considers the problem serious enough for outreach. We cannot infer that exactly 38 teenagers in the whole community misused medicine.'),
 U('Worked passage: consumer rights','A lamp is advertised to last twelve hours. Chika charges her lamp according to instructions and tests it three times; it lasts four to five hours each time. She may conclude that her tested lamp did not meet the advertised duration in those tests. She cannot conclude that every lamp produced by the company is defective. One tested unit does not establish a universal claim.'),
 U('Worked passage: technology at school','A school introduces twenty tablets. Teachers report easier diagram display, while two teachers report delays from charging and poor connectivity. A student calls tablets “the greatest improvement ever”. The quantity and reported incidents can be checked; “greatest” is opinion. The presence of advantages and disadvantages indicates balance. If the school keeps tablets but also keeps printed books, infer that it sees value in both—not that tablets have been proved to improve examination scores.'),
 U('A reliable critical-reading routine','1 Understand the literal meaning. 2 Identify the main issue and important claims. 3 Separate facts, opinions and mixed claims. 4 Ask what evidence supports each important claim. 5 Notice loaded words and absolute language. 6 Check for bias or balance. 7 Infer only what the clues support. 8 Test the limit of each conclusion: what can I NOT safely say? This last step prevents over-inference.'),
 U('Common traps','Trap 1: “Opinion means false.” No—an opinion may be sensible but remains a judgement. Trap 2: “Statistics prove the conclusion.” Numbers can be irrelevant or incomplete. Trap 3: “After means because of.” If scores rose after a revision class, the class may have helped, but timing alone does not prove it caused every improvement. Trap 4: “Bias makes every sentence false.” No—check individual claims. Trap 5: “Any possible story is a deduction.” Only evidence-supported conclusions qualify.'),
 U('Guided practice','A council surveys 120 Basic 9 learners; 84 say they visited the library last month. The president says, “This proves our library is the most useful facility in school.” The survey figures are factual claims. “Most useful” is an opinion. The evidence does not compare the library with laboratories, classrooms or sports facilities, so the conclusion is stronger than the evidence.'),
 U('BECE-style reasoning practice','Passage: After a pedestrian bridge opened, officials observed more people crossing above the road. A columnist wrote, “The bridge has solved every traffic problem here forever.” Traders still complained about illegal parking and congestion. Identify: (a) observed fact—more pedestrians used the bridge; (b) loaded/absolute claim—“every…forever”; (c) counter-evidence—parking and congestion remain; (d) safe deduction—the bridge addressed pedestrian crossing risk but the passage does not establish that all traffic problems ended.'),
 U('Mastery checkpoint','You are ready when you can explain critical reading without memorising a definition; classify facts/opinions in mixed sentences; point to exact words showing bias; explain why a passage is balanced; distinguish evidence from conclusion; make an inference and cite the clues supporting it; reject an over-inference; and interpret a road warning without inventing information.')
 ]},
 questions:[
 Q('j3e-crit-01','Critical reading mainly requires a reader to…',['memorise every sentence','examine meaning, evidence and conclusions','reject every opinion','read aloud quickly'],'examine meaning, evidence and conclusions','Critical reading combines understanding with evaluation.'),
 Q('j3e-crit-02','Which is an opinion?',['Nigeria is in West Africa','A week has seven days','English is the easiest subject','The meeting began at noon'],'English is the easiest subject','“Easiest” depends on judgement.'),
 Q('j3e-crit-03','A deduction is…',['a copied sentence','a conclusion supported by clues','an unsupported guess','the title of a text'],'a conclusion supported by clues','A deduction must follow logically from evidence.'),
 Q('j3e-crit-04','Which claim is factual in form?',['The hall is wonderful','The hall has 300 seats','The hall is the finest','The hall looks boring'],'The hall has 300 seats','The number of seats can be checked.'),
 Q('j3e-crit-05','“Careless Tobi gave another ridiculous speech.” The wording mainly shows…',['balance','bias','a road warning','a statistic'],'bias','Loaded negative labels reveal a one-sided attitude.'),
 Q('j3e-crit-06','A balanced passage…',['must agree with everybody','fairly represents relevant evidence or viewpoints','contains no opinions','has equal sentence counts for both sides'],'fairly represents relevant evidence or viewpoints','Balance concerns fair representation, not mechanical equality.'),
 Q('j3e-crit-07','Kunle arrives with a dripping umbrella and wet shoes. Best deduction?',['It probably rained','He bought shoes today','Tomorrow will be sunny','His mother owns a shop'],'It probably rained','Wet rain gear supports that inference.'),
 Q('j3e-crit-08','Which turns an inference into a guess?',['using clues','using logical reasoning','adding unsupported details','checking the passage'],'adding unsupported details','Unsupported invention is guessing.'),
 Q('j3e-crit-09','A writer says 5,000 people bought a product, therefore it is the highest-quality product. What is missing?',['a longer sentence','evidence connecting sales to quality','a title','an exclamation mark'],'evidence connecting sales to quality','Popularity alone does not establish quality.'),
 Q('j3e-crit-10','Which word creates the strongest absolute claim?',['sometimes','often','perhaps','always'],'always','“Always” allows no exception and therefore needs strong evidence.'),
 Q('j3e-crit-11','A sign warning of a sharp bend justifies which conclusion?',['An accident has happened','Drivers should approach cautiously','The road ends there','No vehicle may continue'],'Drivers should approach cautiously','The sign warns of a road condition, not a confirmed accident.'),
 Q('j3e-crit-12','A clinic treated 20 malaria patients. Which conclusion is NOT justified?',['The clinic treated malaria','Twenty such patients were treated','Exactly twenty people in the town had malaria','The clinic had malaria cases'],'Exactly twenty people in the town had malaria','The clinic data cannot establish the whole-town total.'),
 Q('j3e-crit-13','“The library has 5,000 books and is the most beautiful building.” This contains…',['two opinions','two facts','a fact and an opinion','neither'],'a fact and an opinion','The count is checkable; beauty is judgement.'),
 Q('j3e-crit-14','Evidence is…',['information used to support a claim','any emotional word','a paragraph title','always an opinion'],'information used to support a claim','Evidence provides support that can be evaluated.'),
 Q('j3e-crit-15','If scores rise after a revision class, we can safely say…',['the class caused every improvement','scores rose after the class began','every attendee studied hard','no other factor mattered'],'scores rose after the class began','Sequence is supported; sole causation is not.'),
 Q('j3e-crit-16','Which question best tests a strong claim?',['How long is the paragraph?','What evidence supports it?','Is the font attractive?','Can I memorise it?'],'What evidence supports it?','Critical evaluation asks whether evidence supports the claim.'),
 Q('j3e-crit-17','An implied idea is…',['stated word-for-word','understood logically from clues','unrelated to the passage','always false'],'understood logically from clues','Implication is inferred rather than directly stated.'),
 Q('j3e-crit-18','A biased passage…',['cannot contain any facts','may contain facts but present the issue unfairly','must be completely ignored','is always fiction'],'may contain facts but present the issue unfairly','Bias affects presentation; individual factual claims still require checking.'),
 Q('j3e-crit-19','Which phrase should trigger special caution because it overstates certainty?',['may help some learners','according to the record','solves every problem forever','the report states'],'solves every problem forever','“Every” and “forever” make sweeping claims.'),
 Q('j3e-crit-20','The first duty of a critical reader is to…',['understand what the text says','attack the writer','reject statistics','find spelling errors'],'understand what the text says','Evaluation must begin with accurate comprehension.'),
 Q('j3e-crit-21','If a school keeps tablets but also keeps printed books, the safest inference is…',['tablets guarantee high scores','books are useless','the school sees continuing value in both','all parents oppose tablets'],'the school sees continuing value in both','The decision itself supports this limited conclusion.'),
 Q('j3e-crit-22','Which best signals persuasive purpose?',['Our product is unquestionably the smartest choice','The meeting started at nine','Water filled the tank','The register contains 40 names'],'Our product is unquestionably the smartest choice','Evaluative promotional language aims to persuade.'),
 Q('j3e-crit-23','“Opinion” means…',['a statement that must be false','a judgement or belief rather than an objectively settled claim','a spelling error','a road sign'],'a judgement or belief rather than an objectively settled claim','Opinions may be reasonable but are evaluative.'),
 Q('j3e-crit-24','Why should a reader check counter-evidence?',['to make the text longer','to test whether a conclusion is too strong or one-sided','to avoid understanding the writer','to turn facts into opinions'],'to test whether a conclusion is too strong or one-sided','Counter-evidence can expose overstatement or bias.'),
 Q('j3e-crit-25','The strongest critical reader…',['believes everything printed','disagrees with every writer','understands, checks evidence and draws supported conclusions','reads only statistics'],'understands, checks evidence and draws supported conclusions','Critical reading is reasoned evaluation, not automatic belief or disbelief.')
 ],
 performanceTasks:[
  'Read a short road-safety passage and mark each important claim F (factual), O (opinion) or M (mixed), explaining each choice.',
  'Underline loaded words in a persuasive paragraph and rewrite it in more balanced language.',
  'Given five clues from a passage, state one supported deduction and one tempting but unsupported conclusion, explaining the difference.',
  'Interpret three road danger signs and state only the safe conclusions each sign supports.'
 ]
};

export const jss3EnglishLessons: Jss3EnglishLesson[]=[jss3CriticalEvaluation];
