import type { TutorPlan, TutorUnit } from './tutorCurriculum';

export type Jss3EnglishQuestion = {
  id: string; prompt: string; options: string[]; correctAnswer: string; explanation: string;
};
export type Jss3EnglishLesson = {
  topic: string; strand: 'Reading'|'Writing'|'Listening and Speaking'|'Grammatical Accuracy'|'Literature';
  authority: string; objectives: string[]; plan: TutorPlan; questions: Jss3EnglishQuestion[];
  performanceTasks?: string[];
};
const U=(title:string,body:string):TutorUnit=>({title,body});
const Q=(id:string,prompt:string,options:string[],correctAnswer:string,explanation:string):Jss3EnglishQuestion=>({id,prompt,options,correctAnswer,explanation});

export const jss3CriticalEvaluation: Jss3EnglishLesson = {
 topic:'Reading for Critical Evaluation', strand:'Reading',
 authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:[
  'Read critically and explain what critical reading requires.',
  'Distinguish verifiable facts from opinions and mixed claims.',
  'Make deductions that are supported by information presented.',
  'Recognise words and statements that indicate bias or balance.',
  'Explain the meaning and purpose of road danger signs and interpret their warnings.',
  'Apply critical evaluation to passages on road safety, drug use, consumer rights and other relevant issues.'
 ],
 plan:{topic:'Reading for Critical Evaluation',objective:'Understand, question and evaluate what a writer says; separate fact from opinion; detect bias or balance; and make evidence-based deductions.',units:[
 U('Start with the meaning','Critical reading means understanding a text and then examining its claims instead of accepting every sentence automatically. Ask: What is the writer saying? What evidence supports it? Is it a fact, an opinion or a mixture? Is the language fair? What conclusion can I safely draw? Example: “Our school introduced a reading hour in January, and it is the best programme ever.” The date of introduction can be checked; “best programme ever” is a judgement. A critical reader separates the two claims.'),
 U('Why critical reading matters','Critical reading protects you from exaggeration, weak reasoning and one-sided persuasion. If an advert says, “Five thousand students bought this drink, so it certainly makes students intelligent,” the sales figure—even if true—does not prove the intelligence claim. Popularity is not proof of the advertised effect. Critical readers ask whether the evidence actually supports the conclusion.'),
 U('Fact: what it really means','A fact is a claim whose truth or falsity can be checked using evidence. “The meeting began at 9:00 a.m.” is factual because records or witnesses can settle it. A factual claim can still be wrong: “Nigeria became independent in 1970” is false, but it is still a factual claim because objective evidence can test it. Do not confuse “fact” with “a statement I agree with.”'),
 U('Opinion and judgement','An opinion expresses belief, preference, evaluation or judgement: “English is the easiest subject.” Words such as best, worst, beautiful, boring, excellent, probably and I believe often signal judgement, but context matters. “The doctor said the patient should rest” reports a checkable event even though it contains “should”. Always judge the whole claim.'),
 U('Mixed statements','One sentence can contain fact and opinion. “The library contains 5,000 books and is the most beautiful building in town.” The number of books can be counted; beauty is subjective. In examinations, split a long sentence into its individual claims before classifying it.'),
 U('Evidence and support','Evidence is information offered to support a claim. “Attendance improved after free buses were introduced” is a claim. “Records show attendance rose from 78% to 91%” supplies evidence of improvement. But the figures alone do not prove the buses were the only cause. Other changes may have occurred. Never stretch evidence beyond what it establishes.'),
 U('Deduction: conclusion from clues','A deduction is a conclusion logically supported by information given. “Tunde entered with a wet umbrella; water dripped from his shoes; other pupils wore raincoats.” A reasonable deduction is that rain was falling or had recently fallen. “Tunde’s mother bought the umbrella yesterday” is a guess because the passage gives no supporting clue. Use the rule: evidence + reasoning = deduction; evidence + imagination = guess.'),
 U('Explicit and implied meaning','Explicit information is stated directly: “Ada arrived at 8:30.” Implied information must be inferred: “Ada entered while the teacher was explaining the second exercise.” It is reasonable to infer that teaching had already started. A good inference stays close to the clues and does not invent details.'),
 U('Bias','Bias is an unfair or one-sided presentation. Compare: “Musa presented three proposals, while careless Tobi wasted everyone’s time with another ridiculous speech.” The labels “careless”, “wasted” and “ridiculous” reveal hostility toward Tobi. Bias can appear through loaded words, selective evidence, unfair labels or presenting only one side. A biased passage can still contain facts; evaluate each claim separately.'),
 U('Balance','A balanced presentation represents relevant viewpoints or evidence fairly. “Some parents support smartphones because learners can access dictionaries quickly; others worry that unrestricted use distracts learners.” This does not force both sides to have exactly the same number of words; it avoids unfairly misrepresenting a relevant side.'),
 U('Loaded language and absolute claims','Words can push emotions before evidence is considered. “The council imposed another ridiculous rule on helpless motorists” is more loaded than “The council introduced a traffic rule.” Also question absolute words such as all, always, never, everyone, completely, certainly and only. “Every teenager with a smartphone performs poorly” requires far stronger evidence than “Excessive use can reduce study time for some learners.”'),
 U('Purpose and viewpoint','Ask why the text exists. A writer may inform, explain, warn, instruct, persuade or entertain. “Reduce speed when approaching the school crossing” warns/instructs. “Our product is unquestionably the smartest choice” persuades. Purpose does not automatically make a text false; it tells you what kinds of claims and language deserve close examination.'),
 U('Road danger signs','NERDC places road danger signs inside this topic because signs require interpretation and sensible deduction. A warning sign tells a road user that a hazard or condition lies ahead: a bend, junction, pedestrian/school crossing, road works, narrowing road, animals or another danger. If a sign warns of a sharp bend, you may infer that the driver should reduce speed and maintain control. You may NOT infer that an accident has definitely happened there.'),
 U('Worked passage: road safety','Residents complained about fast vehicles near a school. The authority installed warning signs and repainted a pedestrian crossing. A residents’ group then called the road “completely safe”, while school officials continued asking drivers to slow down. Facts: signs were installed and the crossing repainted. Opinion/overclaim: “completely safe”. Reasonable deduction: measures were taken to improve safety. Unsupported deduction: “No accident can ever occur there again.”'),
 U('Worked passage: drug use','A health centre reported treating 38 teenagers for problems linked to misuse of medicines and began school visits. A worker called education “one of the most important” protections; students asked that talks also explain how to seek help privately. The treatment figure is a checkable report; “most important” is evaluation. We may infer the centre considers the problem serious enough for outreach. We cannot infer that exactly 38 teenagers in the whole community misused medicine.'),
 U('Worked passage: consumer rights','A lamp is advertised to last twelve hours. Chika charges her lamp according to instructions and tests it three times; it lasts four to five hours each time. She may conclude that her tested lamp did not meet the advertised duration in those tests. She cannot conclude that every lamp produced by the company is defective. One tested unit does not establish a universal claim.'),
 U('Worked passage: technology at school','A school introduces twenty tablets. Teachers report easier diagram display, while two teachers report delays from charging and poor connectivity. A student calls tablets “the greatest improvement ever”. The quantity and reported incidents can be checked; “greatest” is opinion. The presence of advantages and disadvantages indicates balance. If the school keeps tablets but also keeps printed books, infer that it sees value in both—not that tablets have been proved to improve examination scores.'),
 U('A reliable critical-reading routine','1 Understand the literal meaning. 2 Identify the main issue and important claims. 3 Separate facts, opinions and mixed claims. 4 Ask what evidence supports each important claim. 5 Notice loaded words and absolute language. 6 Check for bias or balance. 7 Infer only what the clues support. 8 Test the limit of each conclusion: what can I NOT safely say? This last step prevents over-inference.'),
 U('Common traps','Trap 1: “Opinion means false.” No—an opinion may be sensible but remains a judgement. Trap 2: “Statistics prove the conclusion.” Numbers can be irrelevant or incomplete. Trap 3: “After means because of.” If scores rose after a revision class, the class may have helped, but timing alone does not prove it caused every improvement. Trap 4: “Bias makes every sentence false.” No—check individual claims. Trap 5: “Any possible story is a deduction.” Only evidence-supported conclusions qualify.'),
 U('Guided practice','A council surveys 120 Basic 9 learners; 84 say they visited the library last month. The president says, “This proves our library is the most useful facility in school.” The survey figures are factual claims. “Most useful” is an opinion. The evidence does not compare the library with laboratories, classrooms or sports facilities, so the conclusion is stronger than the evidence.'),
 U('BECE-style reasoning practice','Passage: After a pedestrian bridge opened, officials observed more people crossing above the road. A columnist wrote, “The bridge has solved every traffic problem here forever.” Traders still complained about illegal parking and congestion. Identify: (a) observed fact—more pedestrians used the bridge; (b) loaded/absolute claim—“every…forever”; (c) counter-evidence—parking and congestion remain; (d) safe deduction—the bridge addressed pedestrian crossing risk but the passage does not establish that all traffic problems ended.'),
 U('Mastery checkpoint','You are ready when you can explain critical reading without memorising a definition; classify facts/opinions in mixed sentences; point to exact words showing bias; explain why a passage is balanced; distinguish evidence from conclusion; make an inference and cite the clues supporting it; reject an over-inference; and interpret a road warning without inventing information.')
 ]},
 questions:[
 Q('j3e-crit-01','Critical reading mainly requires a reader to…',['memorise every sentence','examine meaning, evidence and conclusions','reject every opinion','read aloud quickly'],'examine meaning, evidence and conclusions','Critical reading combines understanding with evaluation.'),
 Q('j3e-crit-02','Which is an opinion?',['Nigeria is in West Africa','A week has seven days','English is the easiest subject','The meeting began at noon'],'English is the easiest subject','“Easiest” depends on judgement.'),
 Q('j3e-crit-03','A deduction is…',['a copied sentence','a conclusion supported by clues','an unsupported guess','the title of a text'],'a conclusion supported by clues','A deduction must follow logically from evidence.'),
 Q('j3e-crit-04','Which claim is factual in form?',['The hall is wonderful','The hall has 300 seats','The hall is the finest','The hall looks boring'],'The hall has 300 seats','The number of seats can be checked.'),
 Q('j3e-crit-05','“Careless Tobi gave another ridiculous speech.” The wording mainly shows…',['balance','bias','a road warning','a statistic'],'bias','Loaded negative labels reveal a one-sided attitude.'),
 Q('j3e-crit-06','A balanced passage…',['must agree with everybody','fairly represents relevant evidence or viewpoints','contains no opinions','has equal sentence counts for both sides'],'fairly represents relevant evidence or viewpoints','Balance concerns fair representation, not mechanical equality.'),
 Q('j3e-crit-07','Kunle arrives with a dripping umbrella and wet shoes. Best deduction?',['It probably rained','He bought shoes today','Tomorrow will be sunny','His mother owns a shop'],'It probably rained','Wet rain gear supports that inference.'),
 Q('j3e-crit-08','Which turns an inference into a guess?',['using clues','using logical reasoning','adding unsupported details','checking the passage'],'adding unsupported details','Unsupported invention is guessing.'),
 Q('j3e-crit-09','A writer says 5,000 people bought a product, therefore it is the highest-quality product. What is missing?',['a longer sentence','evidence connecting sales to quality','a title','an exclamation mark'],'evidence connecting sales to quality','Popularity alone does not establish quality.'),
 Q('j3e-crit-10','Which word creates the strongest absolute claim?',['sometimes','often','perhaps','always'],'always','“Always” allows no exception and therefore needs strong evidence.'),
 Q('j3e-crit-11','A sign warning of a sharp bend justifies which conclusion?',['An accident has happened','Drivers should approach cautiously','The road ends there','No vehicle may continue'],'Drivers should approach cautiously','The sign warns of a road condition, not a confirmed accident.'),
 Q('j3e-crit-12','A clinic treated 20 malaria patients. Which conclusion is NOT justified?',['The clinic treated malaria','Twenty such patients were treated','Exactly twenty people in the town had malaria','The clinic had malaria cases'],'Exactly twenty people in the town had malaria','The clinic data cannot establish the whole-town total.'),
 Q('j3e-crit-13','“The library has 5,000 books and is the most beautiful building.” This contains…',['two opinions','two facts','a fact and an opinion','neither'],'a fact and an opinion','The count is checkable; beauty is judgement.'),
 Q('j3e-crit-14','Evidence is…',['information used to support a claim','any emotional word','a paragraph title','always an opinion'],'information used to support a claim','Evidence provides support that can be evaluated.'),
 Q('j3e-crit-15','If scores rise after a revision class, we can safely say…',['the class caused every improvement','scores rose after the class began','every attendee studied hard','no other factor mattered'],'scores rose after the class began','Sequence is supported; sole causation is not.'),
 Q('j3e-crit-16','Which question best tests a strong claim?',['How long is the paragraph?','What evidence supports it?','Is the font attractive?','Can I memorise it?'],'What evidence supports it?','Critical evaluation asks whether evidence supports the claim.'),
 Q('j3e-crit-17','An implied idea is…',['stated word-for-word','understood logically from clues','unrelated to the passage','always false'],'understood logically from clues','Implication is inferred rather than directly stated.'),
 Q('j3e-crit-18','A biased passage…',['cannot contain any facts','may contain facts but present the issue unfairly','must be completely ignored','is always fiction'],'may contain facts but present the issue unfairly','Bias affects presentation; individual factual claims still require checking.'),
 Q('j3e-crit-19','Which phrase should trigger special caution because it overstates certainty?',['may help some learners','according to the record','solves every problem forever','the report states'],'solves every problem forever','“Every” and “forever” make sweeping claims.'),
 Q('j3e-crit-20','The first duty of a critical reader is to…',['understand what the text says','attack the writer','reject statistics','find spelling errors'],'understand what the text says','Evaluation must begin with accurate comprehension.'),
 Q('j3e-crit-21','If a school keeps tablets but also keeps printed books, the safest inference is…',['tablets guarantee high scores','books are useless','the school sees continuing value in both','all parents oppose tablets'],'the school sees continuing value in both','The decision itself supports this limited conclusion.'),
 Q('j3e-crit-22','Which best signals persuasive purpose?',['Our product is unquestionably the smartest choice','The meeting started at nine','Water filled the tank','The register contains 40 names'],'Our product is unquestionably the smartest choice','Evaluative promotional language aims to persuade.'),
 Q('j3e-crit-23','“Opinion” means…',['a statement that must be false','a judgement or belief rather than an objectively settled claim','a spelling error','a road sign'],'a judgement or belief rather than an objectively settled claim','Opinions may be reasonable but are evaluative.'),
 Q('j3e-crit-24','Why should a reader check counter-evidence?',['to make the text longer','to test whether a conclusion is too strong or one-sided','to avoid understanding the writer','to turn facts into opinions'],'to test whether a conclusion is too strong or one-sided','Counter-evidence can expose overstatement or bias.'),
 Q('j3e-crit-25','The strongest critical reader…',['believes everything printed','disagrees with every writer','understands, checks evidence and draws supported conclusions','reads only statistics'],'understands, checks evidence and draws supported conclusions','Critical reading is reasoned evaluation, not automatic belief or disbelief.')
 ],
 performanceTasks:[
  'Read a short road-safety passage and mark each important claim F (factual), O (opinion) or M (mixed), explaining each choice.',
  'Underline loaded words in a persuasive paragraph and rewrite it in more balanced language.',
  'Given five clues from a passage, state one supported deduction and one tempting but unsupported conclusion, explaining the difference.',
  'Interpret three road danger signs and state only the safe conclusions each sign supports.'
 ]
};

export const jss3ReadingSpeed: Jss3EnglishLesson = {
 topic:'Reading for Speed',strand:'Reading',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Read rapidly while retaining meaning.','Use surveying, skimming and scanning appropriately.','Adjust reading rate to purpose and material.','Use rapid reading for reference and non-text materials.','Answer comprehension questions after speed reading.'],
 plan:{topic:'Reading for Speed',objective:'Choose and use the right rapid-reading technique without sacrificing comprehension.',units:[
 U('Speed is not rushing','Reading for speed means getting the required meaning efficiently. A learner who races through 600 words but cannot answer basic questions has not read effectively. Speed and comprehension work together. Your purpose determines how quickly and how deeply you read.'),
 U('Flexible reading rate','Do not read a dictionary entry, a story, an examination instruction and a difficult science explanation at one fixed speed. Slow down for dense reasoning, unfamiliar vocabulary and exact instructions; speed up when previewing familiar material or locating a known detail. Skilled readers change gears.'),
 U('Surveying','Surveying is a quick first look at the whole material before detailed reading. Examine the title, headings, subheadings, pictures, captions, opening/closing paragraphs, bold words, tables or layout. Example: before reading a chapter called “Road Safety”, surveying may reveal sections on pedestrians, signs, speed and emergency response. You now have a mental map.'),
 U('Skimming','Skimming is rapid reading to grasp the general idea or main points. Let your eyes move over headings, topic sentences and key words rather than stopping at every detail. If asked “What is this article mainly about?”, skim. Example: in four paragraphs about causes, effects and prevention of flooding, skimming should reveal the overall subject and major divisions.'),
 U('Scanning','Scanning is rapid searching for a specific item: a name, date, price, definition, score, telephone number or key word. If a timetable question asks when Mathematics begins, do not read every row as prose; scan for “Mathematics”, then read across to the time.'),
 U('Do not swap the techniques','A common textbook distinction is purpose: skim for general meaning; scan for a particular detail; survey to preview structure. If you need one date, skimming the entire passage wastes time. If you need the main argument, scanning for one number is insufficient.'),
 U('Eye movement and word groups','Slow readers often pronounce every word internally and repeatedly move backwards. Practise taking meaningful groups: “after the morning assembly / the Basic 9 learners / entered the laboratory.” Grouping helps the eyes process phrases, not isolated words. Never sacrifice meaning merely to avoid rereading; reread when the text truly requires it.'),
 U('Using context instead of stopping','In speed reading, an unfamiliar word does not always require an immediate dictionary stop. Read the surrounding sentence first. “The road was inundated after hours of rain; water entered nearby shops.” Even if “inundated” is unfamiliar, the context suggests flooding. Later, verify the word if precision matters.'),
 U('Speed with non-text materials','NERDC expects rapid reading to help with non-text materials. Timetables, charts, indexes, contents pages, notices and tables are not read like stories. Decide the target, identify labels/headings, then move directly to the relevant row, column or entry.'),
 U('Reference skill','Suppose a textbook index lists: Climate 44–49; Erosion 72–76; Flooding 77–81. To find causes of flooding, scan alphabetically for “Flooding”, note pages 77–81, then turn there. This is efficient referencing—not careless reading.'),
 U('Worked drill: survey','Material has title “Healthy Study Habits”, headings “Plan Your Time”, “Remove Distractions”, “Sleep Well”, and a final checklist. Before reading details you can predict that it explains habits that improve studying. That prediction came from surveying the structure.'),
 U('Worked drill: skim','Paragraphs discuss blocked drains, building on waterways, heavy rain and community clean-up. A good skim yields: “The passage explains causes of urban flooding and ways communities can reduce it.” You do not need every statistic to state the main idea.'),
 U('Worked drill: scan','Notice: Debate Finals — Friday 16 October; Venue: School Hall; Time: 1:30 p.m.; Teams: Blue vs Gold. Question: “Where will the debate hold?” Scan for the label Venue → School Hall. Reading every word several times is unnecessary.'),
 U('Timed comprehension strategy','Before a timed passage: read the question or task when appropriate; identify whether it asks main idea or detail; skim for structure; scan for names/numbers; read the relevant sentence carefully; verify the answer in context. Speed comes from purpose, not panic.'),
 U('Common mistakes','Mistake: “Skimming means reading the first sentence only.” No. It samples strategically across the text. Mistake: “Scanning means understanding nothing.” No. You read selectively around the target. Mistake: “Fast readers never slow down.” Skilled readers slow down when complexity demands it. Mistake: “Speed is words per minute only.” Comprehension is essential.'),
 U('Guided practice','You need (a) the price of a bus ticket in a long notice, (b) the overall argument of a newspaper article, (c) a first look at a new chapter. Choose: (a) scanning, (b) skimming, (c) surveying. Then read the exact target sentence normally to avoid taking a detail out of context.'),
 U('Mastery checkpoint','You have mastered this topic when you can explain surveying/skimming/scanning in your own words, choose the correct technique for a task, rapidly locate a detail in a table, state the main idea after skimming, preview a chapter through surveying, and still answer comprehension questions accurately.')
 ]},
 questions:[
 Q('j3e-speed-01','Reading for speed is successful when a learner…',['moves fastest even without meaning','reads efficiently and understands what the task requires','pronounces every word aloud','never rereads'],'reads efficiently and understands what the task requires','Comprehension remains essential.'),
 Q('j3e-speed-02','A quick first look at headings and layout is…',['surveying','dictation','proofreading','recitation'],'surveying','Surveying previews the structure.'),
 Q('j3e-speed-03','To get the general idea of a long article, use…',['scanning','skimming','spelling','copying'],'skimming','Skimming targets overall meaning/main points.'),
 Q('j3e-speed-04','To find one date in a notice, use…',['scanning','dramatisation','summary writing','slow oral reading'],'scanning','Scanning searches for a specific detail.'),
 Q('j3e-speed-05','Which is the best example of surveying?',['reading every word twice','checking title, headings and captions before reading','searching only for 1999','copying the conclusion'],'checking title, headings and captions before reading','Surveying maps the material.'),
 Q('j3e-speed-06','A skilled reader should…',['use one speed for everything','adjust speed to purpose and difficulty','always skip unfamiliar words','avoid comprehension questions'],'adjust speed to purpose and difficulty','Flexible rate is central to efficient reading.'),
 Q('j3e-speed-07','You need the Mathematics time in a timetable. Best technique?',['scan the subject column','read every row as a story','skim only the title','memorise all times first'],'scan the subject column','The target is a specific detail.'),
 Q('j3e-speed-08','Skimming differs from scanning mainly because skimming seeks…',['general meaning','one exact detail','correct spelling only','page numbers only'],'general meaning','Scanning targets specific information.'),
 Q('j3e-speed-09','Which material especially rewards scanning?',['a timetable','a poem whose imagery you must analyse','a complex proof','a drama performance'],'a timetable','Structured labels allow rapid location of a target.'),
 Q('j3e-speed-10','Why survey a chapter first?',['to avoid reading it','to build a mental map of its structure','to replace comprehension','to count letters'],'to build a mental map of its structure','Previewing makes later reading purposeful.'),
 Q('j3e-speed-11','Taking words in meaningful groups can…',['support fluent rapid reading','make meaning impossible','replace vocabulary knowledge','remove punctuation'],'support fluent rapid reading','Phrase grouping reduces word-by-word processing.'),
 Q('j3e-speed-12','When a passage becomes conceptually difficult, a skilled reader should…',['speed up blindly','slow down as needed','stop permanently','skip every example'],'slow down as needed','Reading rate should respond to difficulty.'),
 Q('j3e-speed-13','Which task needs skimming?',['Find the phone number','State what the article is mainly about','Locate page 81 in an index','Find the examination date'],'State what the article is mainly about','The task asks for overall meaning.'),
 Q('j3e-speed-14','Which task needs scanning?',['Explain the writer’s full argument','Find the venue in an announcement','Analyse a metaphor','Evaluate bias throughout a passage'],'Find the venue in an announcement','The venue is a specific target.'),
 Q('j3e-speed-15','A contents page is best treated as…',['non-text reference material','a narrative story','a poem','dialogue'],'non-text reference material','Its structure is designed for locating information.'),
 Q('j3e-speed-16','If you skim but cannot state the main idea, you should…',['claim success because you were fast','reread strategically for meaning','ignore the task','guess'],'reread strategically for meaning','Speed without required comprehension is not success.'),
 Q('j3e-speed-17','Which is NOT a sound speed-reading principle?',['read with a purpose','change rate when necessary','never slow down under any condition','use headings strategically'],'never slow down under any condition','Flexible reading is better than forced speed.'),
 Q('j3e-speed-18','Referencing skill helps a learner…',['locate needed information efficiently','avoid books','replace comprehension with guessing','read only fiction'],'locate needed information efficiently','Indexes and contents pages guide rapid retrieval.'),
 Q('j3e-speed-19','Survey → skim → focused reading is useful because it moves from…',['overview to main ideas to needed detail','detail to guessing','memorisation to copying','speech to spelling'],'overview to main ideas to needed detail','The sequence progressively narrows attention.'),
 Q('j3e-speed-20','NERDC mastery of reading for speed still requires…',['comprehension of selected material','speed alone','no questions afterward','oral memorisation only'],'comprehension of selected material','The evaluation guide explicitly includes comprehension.')
 ]},
 performanceTasks:['Survey a textbook chapter in 45 seconds and report its structure without reading every paragraph.','Skim a 400-word passage and state its main idea plus three major points.','Scan a timetable/notice for five specified details against a timer, then verify each in context.']
};

export const jss3ReadingSummary: Jss3EnglishLesson = {
 topic:'Reading for Summary',strand:'Reading',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Identify topic sentences.','Identify key ideas across paragraphs.','Recognise words and expressions that redirect attention to main points.','Reduce material to accurate phrases/sentences without losing essential meaning.'],
 plan:{topic:'Reading for Summary',objective:'Find the central meaning of paragraphs and compress it accurately in your own words.',units:[
 U('What summary reading means','Reading for summary means reading to separate essential ideas from examples, repetition and decoration. You are not trying to remember every sentence. You are asking: What must remain if this paragraph is shortened without changing its central meaning?'),
 U('Topic and topic sentence','The topic is what a paragraph is about; the topic sentence states its controlling idea. Paragraph: “Regular exercise strengthens the heart. It can also improve stamina and help control body weight.” Topic: exercise. Topic sentence: “Regular exercise strengthens the heart” if that sentence controls the supporting details.'),
 U('Topic sentence can move','Do not assume the first sentence is always the topic sentence. A paragraph may give examples first and conclude: “For these reasons, keeping drainage channels clear is a shared community responsibility.” Here the final sentence may carry the main point.'),
 U('Main idea versus supporting detail','Main idea: the central claim. Supporting details explain, prove or illustrate it. “Public libraries support learning” is main. “They provide dictionaries, textbooks, newspapers and quiet reading spaces” supplies support. A summary keeps the main point and only essential support.'),
 U('Key ideas across paragraphs','A multi-paragraph passage may develop several main points. Label each paragraph in a few words before combining them. Example: P1 cause of flooding; P2 effects; P3 prevention. Your final summary should preserve all three if the task asks for the whole passage.'),
 U('Signpost expressions','Words can redirect attention: however signals contrast; therefore/so signals result; most importantly highlights priority; in conclusion signals synthesis; although introduces concession; for example introduces illustration. These signals help locate the writer’s important movement, but the word itself is not the main idea.'),
 U('Delete repetition','If a paragraph says the same idea three ways, do not copy all three. “The road was unsafe. It posed serious danger. Travelling there was risky.” These largely repeat one idea: the road was dangerous.'),
 U('Examples are not automatically main ideas','“Many fruits contain useful nutrients. Oranges supply vitamin C; bananas provide potassium; avocados contain healthy fats.” Unless the question demands examples, a concise summary may be: “Different fruits provide useful nutrients.”'),
 U('Use your own words carefully','Paraphrase without changing meaning. Original: “The heavy rainfall forced residents to leave low-lying homes.” Safe: “Residents evacuated low areas because of severe rain.” Do not introduce a new cause such as “because the dam broke” if the passage never says so.'),
 U('Keep tense and logic','A summary must preserve relationships. If the original says “Because the bridge was damaged, buses used another route,” do not write “Buses damaged the bridge.” Compression must not reverse cause and effect.'),
 U('Worked paragraph','“Motorists should check tyres regularly. Worn tyres reduce grip, especially on wet roads. Drivers should also maintain correct tyre pressure.” Topic: tyre safety. Main idea: regular tyre maintenance improves road safety. Key supports: tread condition and pressure. Summary: “Motorists should maintain tyre condition and pressure to improve road safety.”'),
 U('Worked multi-paragraph passage','P1 describes traffic officers using cameras to observe roads. P2 explains speed-monitoring devices. P3 explains communication devices used to report incidents. Paragraph labels: observation, speed monitoring, communication. A whole-passage summary should combine those functions instead of listing every brand or example.'),
 U('From paragraph to one sentence','Method: read once for meaning; underline repeated key nouns/verbs; identify the topic sentence or formulate the controlling idea; cross out examples/repetition; restate the essential idea in one accurate sentence; compare with original to ensure nothing vital was distorted.'),
 U('Common summary errors','Copying whole sentences without selection; including personal opinion; adding information not in the passage; writing examples while omitting the general point; changing cause/effect; using vague pronouns whose referent is lost; reducing so much that the central meaning disappears.'),
 U('Guided practice','“Trees cool neighbourhoods by providing shade. Their roots can reduce soil erosion. Trees also absorb carbon dioxide.” Main idea: trees provide environmental benefits. Details: shade, erosion reduction, carbon dioxide absorption. A suitable summary: “Trees benefit the environment by cooling areas, protecting soil and absorbing carbon dioxide.”'),
 U('Mastery checkpoint','You are ready when you can identify topic sentences in different positions, distinguish main ideas from examples, use signposts to follow argument, label each paragraph’s key idea, paraphrase without distortion, and produce a shorter statement that still contains the essential meaning.')
 ]},
 questions:[
 Q('j3e-rsum-01','The main purpose of reading for summary is to…',['copy every sentence','identify and compress essential ideas','memorise punctuation','find only difficult words'],'identify and compress essential ideas','A summary preserves essentials while reducing detail.'),
 Q('j3e-rsum-02','A topic sentence usually expresses…',['the controlling idea of a paragraph','every example','the page number','the writer’s name'],'the controlling idea of a paragraph','It guides the supporting details.'),
 Q('j3e-rsum-03','A topic sentence…',['must always be first','may occur in different positions','must be a question','cannot be implied'],'may occur in different positions','Writers may place it first, later or make it implicit.'),
 Q('j3e-rsum-04','Which is normally supporting detail?',['a specific example illustrating a general claim','the controlling idea itself','the title only','the central conclusion always'],'a specific example illustrating a general claim','Examples commonly support broader ideas.'),
 Q('j3e-rsum-05','“However” often signals…',['contrast','a list of names','a date','pronunciation'],'contrast','It redirects attention to an opposing or qualifying point.'),
 Q('j3e-rsum-06','“Therefore” often signals…',['result/conclusion','example only','location','quotation'],'result/conclusion','It marks a consequence or inference.'),
 Q('j3e-rsum-07','A good summary should NOT…',['preserve main ideas','use concise wording','add the summariser’s unsupported opinion','retain logical relationships'],'add the summariser’s unsupported opinion','A summary represents the source.'),
 Q('j3e-rsum-08','Three sentences all say a road is dangerous. A summary should…',['repeat all three','combine the repeated idea','omit danger completely','invent an accident'],'combine the repeated idea','Repetition can be compressed.'),
 Q('j3e-rsum-09','Paraphrasing means…',['restating meaning in different words','changing the facts','adding examples','copying exactly'],'restating meaning in different words','Meaning should remain faithful.'),
 Q('j3e-rsum-10','Which error changes logic?',['shortening an example','reversing cause and effect','removing repetition','combining similar points'],'reversing cause and effect','A summary must preserve relationships.'),
 Q('j3e-rsum-11','Before summarising a long passage, it helps to…',['label each paragraph’s key idea','count all letters','ignore paragraph divisions','read only the last line'],'label each paragraph’s key idea','Paragraph labels reveal the structure.'),
 Q('j3e-rsum-12','“For example” usually introduces…',['illustration/support','the only main idea','a conclusion always','a title'],'illustration/support','Examples develop a broader point.'),
 Q('j3e-rsum-13','A summary is too short if it…',['removes repetition','loses an essential idea','uses own words','combines examples'],'loses an essential idea','Compression must retain the core meaning.'),
 Q('j3e-rsum-14','Which belongs in a summary?',['essential cause stated in the passage','your personal complaint','an invented statistic','an unrelated story'],'essential cause stated in the passage','Essential source information should remain.'),
 Q('j3e-rsum-15','The topic of a paragraph is…',['what it is generally about','always its first word','its punctuation','only its examples'],'what it is generally about','The topic names the subject area.'),
 Q('j3e-rsum-16','The main idea is more specific than the topic because it…',['states what the writer says about the topic','is only one noun','must be a date','cannot be a sentence'],'states what the writer says about the topic','It expresses the controlling message.'),
 Q('j3e-rsum-17','A safe summary of several fruit examples is…',['different fruits provide useful nutrients','oranges are the only useful fruit','all fruit cures disease','fruit is boring'],'different fruits provide useful nutrients','It captures the general point without overclaiming.'),
 Q('j3e-rsum-18','After writing a summary, compare it with the passage mainly to…',['check fidelity and missing essentials','make it longer automatically','add opinions','copy phrases'],'check fidelity and missing essentials','Verification catches distortion and omission.'),
 Q('j3e-rsum-19','Which is a useful final-summary test?',['Does every word copy the original?','Is it shorter, accurate and complete in essentials?','Did I add my view?','Did I include every example?'],'Is it shorter, accurate and complete in essentials?','Those are core summary qualities.'),
 Q('j3e-rsum-20','NERDC expects learners to identify…',['topic sentences and key ideas','only spelling errors','only character names','only dates'],'topic sentences and key ideas','These are explicit performance objectives.')
 ]},
 performanceTasks:['Label the topic sentence, main idea and supporting details in five varied paragraphs.','Reduce a 250-word passage to 70–90 words without adding information.','Summarise three paragraphs first separately and then as one coherent whole.']
};

const makeQs=(p:string,items:Array<[string,string[],string,string]>)=>items.map((x,i)=>Q(p+'-'+String(i+1).padStart(2,'0'),x[0],x[1],x[2],x[3]));

export const jss3Composition: Jss3EnglishLesson={
 topic:'Revision of Composition Writing — Narrative, Descriptive, Expository and Argumentative',strand:'Writing',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Identify major composition types.','Explain and use introduction, body and conclusion.','Arrange ideas in logical sequence.','Write narrative, descriptive, expository and argumentative compositions appropriate to purpose and audience.','Apply the process to practical themes including care of a motor vehicle.'],
 plan:{topic:'Composition Writing',objective:'Plan and write coherent JSS3/BECE-level compositions in four major forms.',units:[
 U('Composition is organised communication','A composition develops one central purpose through connected paragraphs. Strong writing is not a pile of correct sentences. It has relevant content, logical order, suitable vocabulary, paragraph unity, correct grammar and a clear beginning-development-ending structure.'),
 U('The writing process','Read the exact task; underline command words; identify type, audience and purpose; brainstorm; select relevant points; arrange them; draft; revise content and organisation; edit grammar, spelling and punctuation. Planning prevents a good writer from answering the wrong question.'),
 U('Introduction, body, conclusion','The introduction opens the subject and creates direction. The body develops one main point per paragraph with explanation/examples. The conclusion completes the purpose without suddenly introducing a major new argument. Each part must serve the same controlling idea.'),
 U('Narrative writing','Narrative tells events in meaningful sequence. Build setting, characters, conflict/problem, development, climax and resolution. Use time markers naturally and vary pace. Example prompt: “A mistake I will never repeat.” Do not spend three paragraphs on morning routine if the important mistake happens at the end.'),
 U('Narrative worked plan','Prompt: “The day honesty saved me.” Opening: examination script is mistakenly marked 92 instead of 72. Development: excitement, discovery, internal conflict, decision to report. Climax: learner approaches teacher. Resolution: correction plus unexpected recognition for honesty. Lesson emerges from events rather than a sermon pasted on at the end.'),
 U('Descriptive writing','Description helps the reader experience a person, place, object or scene. Select significant sensory details—sight, sound, smell, touch, movement—and organise them spatially or by dominant impression. “The market was busy” is weak; “traders called over one another while wheelbarrows squeezed through the narrow aisle” shows the scene.'),
 U('Description without listing','Avoid a catalogue: “There was a shop. There was a bus. There were people.” Connect details around an impression. For “Our school during inter-house sports”, move from the decorated field to competitors, spectators, sound and final atmosphere. Precise verbs and nouns are often stronger than too many adjectives.'),
 U('Expository writing','Exposition explains, informs or clarifies. It may define, classify, compare, show cause/effect or explain a process. Prompt: “Explain how students can prepare effectively for BECE.” Use clear points: study plan, active practice, correction of weak areas, rest and exam technique. Explain how/why each works.'),
 U('Argumentative writing','Argumentative writing takes a position and supports it with reasons/evidence while recognising relevant opposing views. Prompt: “Students should not bring phones to school.” State your position clearly, develop distinct reasons, address a counterargument fairly, then conclude from the case made. Insults are not arguments.'),
 U('Claim, reason, evidence, explanation','A useful argumentative paragraph: Claim—controlled educational phone use can aid learning. Reason—learners can access reference tools. Evidence/example—dictionary and approved research tasks. Explanation—quick access can support independent work when rules prevent distraction. Each paragraph should advance the case.'),
 U('Logical sequence and transitions','Use sequence that matches the form. Narrative: chronology/cause. Description: spatial movement or dominant impression. Exposition: general-to-specific, process, cause/effect. Argument: strongest logical progression. Transitions such as first, however, consequently, in contrast and finally should express real relationships, not decorate every sentence.'),
 U('Paragraph unity','One paragraph should develop one controlling point. If a paragraph about tyre maintenance suddenly discusses school uniforms, unity breaks. Topic sentence → explanation → evidence/example → link is a dependable structure, though good writing need not sound mechanical.'),
 U('NERDC application: care of a motor vehicle','A suitable expository composition can cover regular checks of water/coolant, engine oil, brake fluid, tyres, brakes and servicing. Organise by safety and maintenance rather than merely listing materials. Explain the purpose of each action and end by linking regular care to safety, reliability and reduced breakdowns.'),
 U('Language and register','Match language to task. Narrative may use dialogue and vivid verbs; exposition values clarity and precision; argument uses reasoned persuasive language; description uses concrete sensory detail. Avoid texting abbreviations, uncontrolled slang and memorised “big words” that do not fit meaning.'),
 U('Editing checklist','Content: did I answer every part? Organisation: clear paragraphs and order? Expression: precise vocabulary and varied sentences? Mechanics: spelling, punctuation, capitals? Consistency: tense and person? Relevance: remove attractive sentences that do not serve the topic.'),
 U('Mastery checkpoint','Given an unfamiliar prompt, you should identify the composition type, generate relevant points, make an outline, write a purposeful introduction, develop coherent body paragraphs, conclude appropriately, and revise for content, organisation and language.')
 ]},
 questions:makeQs('j3e-comp',[
 ['A narrative composition mainly develops…',['events in sequence','a list of definitions','only statistics','a formal address'],'events in sequence','Narrative centres on events and their development.'],
 ['A descriptive composition aims mainly to…',['create a vivid impression','prove an algebra theorem','list dates only','write a salutation'],'create a vivid impression','Description selects details that help the reader experience the subject.'],
 ['An expository composition mainly…',['explains or informs','must tell a fictional story','must insult an opponent','uses dialogue only'],'explains or informs','Exposition clarifies a subject.'],
 ['Argumentative writing requires…',['a supported position','no reasons','only emotional language','no conclusion'],'a supported position','Claims need reasons/evidence.'],
 ['The three basic composition elements in NERDC are…',['introduction, body, conclusion','title, comma, full stop','sender, receiver, stamp','actor, stage, costume'],'introduction, body, conclusion','These organise the complete composition.'],
 ['Before drafting, a writer should first understand…',['the exact task and purpose','how many big words to use','the examiner’s name','the page colour'],'the exact task and purpose','A well-written wrong answer still fails the task.'],
 ['Paragraph unity means…',['one controlling point is developed coherently','every paragraph has one sentence','all paragraphs are equal length','no transitions are used'],'one controlling point is developed coherently','Relevant sentences should support the paragraph focus.'],
 ['Which best strengthens an argument?',['relevant evidence and explanation','insults','repetition alone','capital letters'],'relevant evidence and explanation','Reasoned support makes a claim persuasive.'],
 ['A counterargument is…',['a relevant opposing view considered fairly','a spelling error','the title','a greeting'],'a relevant opposing view considered fairly','Good argument can acknowledge and answer opposition.'],
 ['Sensory detail is especially useful in…',['description','formal addressing','multiple choice marking','indexing'],'description','It creates vivid experience.'],
 ['A climax belongs most naturally to…',['narrative','an address block','a timetable','a dictionary entry'],'narrative','It is the high point of event development.'],
 ['“First, however, consequently” are useful when they…',['show genuine relationships','are inserted randomly','replace ideas','end every sentence'],'show genuine relationships','Transitions should express logic.'],
 ['Which is a poor conclusion?',['one that introduces an entirely new major argument','one that completes the purpose','one that synthesises key reasoning','one that resolves a narrative'],'one that introduces an entirely new major argument','Major development belongs in the body.'],
 ['Care of a motor vehicle is best explained by…',['organised maintenance actions and their purposes','unrelated road stories','only naming car colours','a poem only'],'organised maintenance actions and their purposes','NERDC’s application expects practical composition.'],
 ['Editing should check…',['content, organisation, expression and mechanics','only handwriting size','only title length','only first paragraph'],'content, organisation, expression and mechanics','Revision is multi-level.'],
 ['A narrative becomes weak when…',['irrelevant routine delays the main event','events have cause and effect','characters make choices','the ending resolves conflict'],'irrelevant routine delays the main event','Relevance and pacing matter.'],
 ['A descriptive paragraph is stronger when it uses…',['precise concrete details','only vague adjectives','a list without connection','unrelated facts'],'precise concrete details','Specific details create a controlled impression.'],
 ['Expository writing about BECE preparation should…',['explain how and why strategies work','tell an unrelated folktale','attack weak students','avoid organisation'],'explain how and why strategies work','Exposition develops clear information.'],
 ['The body of a composition should…',['develop the main ideas in logical paragraphs','contain only the title','repeat the introduction word-for-word','ignore the purpose'],'develop the main ideas in logical paragraphs','The body carries the development.'],
 ['A strong composition is best described as…',['relevant, organised and appropriately expressed','long regardless of relevance','full of difficult words','one unbroken paragraph'],'relevant, organised and appropriately expressed','Quality depends on purpose, coherence and control.']
 ])};

export const jss3LetterWriting:Jss3EnglishLesson={
 topic:'Revision of Informal and Formal Letter Writing',strand:'Writing',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Identify informal and formal letters and their purposes.','Use the correct format for each type.','Write letters suited to different situations.','Use language/register appropriate to relationship and purpose.'],
 plan:{topic:'Letter Writing',objective:'Choose the correct letter type, format and register, then communicate all required content clearly.',units:[
 U('Purpose decides the type','An informal letter is written to someone with whom you have a personal relationship—friend, sibling, parent or familiar relative. A formal letter is written in an official capacity to an institution, principal, company, editor or public officer. Do not decide by topic alone; decide by relationship and purpose.'),
 U('Informal format','Use the writer’s address and date, an appropriate personal salutation, coherent paragraphs, a friendly closing and writer’s first name/name as appropriate. The tone may be warm and conversational but grammar and clarity still matter.'),
 U('Formal format','NERDC emphasises the conventional formal form: writer’s address/date, receiver’s address, formal salutation, clear heading/title, organised body, formal complimentary close and signature/name. Follow the school/examination convention consistently.'),
 U('Formal heading','The heading states the subject precisely: “REQUEST FOR REPAIR OF THE SCHOOL PEDESTRIAN CROSSING” is clearer than “A Letter”. It lets the recipient know the issue immediately.'),
 U('Register','Informal: “I was delighted to hear…” may suit a friend. Formal: “I write to request…” suits an official. Avoid “Hey bro” in a formal complaint and avoid making a friendly letter sound like a government circular.'),
 U('Content fulfilment','If the question asks you to describe three problems and suggest two solutions, all five content demands must appear. Format cannot rescue missing content. Underline the task’s content points before planning.'),
 U('Worked informal plan','Task: Write to a cousin describing your new school. Opening: personal connection. Body 1: school environment; Body 2: teachers/learning; Body 3: activities/friends; closing: invite response. Specific experiences make the letter natural.'),
 U('Worked formal plan','Task: Write to the council about unsafe traffic near your school. Heading states request. Paragraph 1 identifies school/location and purpose. Paragraph 2 describes evidence of speeding/risk. Paragraph 3 proposes signs, crossing control or enforcement. Final paragraph respectfully requests action.'),
 U('Tone in complaints','Formal does not mean rude or weak. “Your officers are useless” is inappropriate. “Despite previous reports, vehicles continue to obstruct the crossing; I respectfully request enforcement during closing hours” is firm, specific and professional.'),
 U('Common format errors','Mixing two-address formal format with a friendly salutation; forgetting the heading; using “Dear friend” to a ministry; using slang; writing addresses inside the body; signing with an informal nickname in an official complaint; memorising a format but failing the content task.'),
 U('Editing letters','Check type, addresses/date, salutation, heading where required, paragraphing, all content points, register, closing, signature/name, spelling and punctuation. Read once as the recipient: is the requested action or message unmistakable?'),
 U('Mastery checkpoint','You can identify the correct letter type from relationship/purpose, reproduce its format without mixing conventions, adapt tone, fulfil every content instruction and write a coherent complete letter.')
 ]},
 questions:makeQs('j3e-let',[
 ['A letter to a close friend is normally…',['informal','formal','a report','a poem'],'informal','The relationship is personal.'],
 ['A letter to a local council requesting road repair is…',['formal','informal','a folktale','a diary only'],'formal','It is official communication.'],
 ['A formal letter normally includes…',['receiver’s address','only a nickname','no purpose','slang greeting'],'receiver’s address','The conventional formal format uses two addresses.'],
 ['The heading of a formal letter should…',['state the subject clearly','be “A Letter” always','contain jokes','replace the body'],'state the subject clearly','A precise heading announces purpose.'],
 ['Register means…',['language appropriate to situation and relationship','handwriting colour','paper size','number of stamps'],'language appropriate to situation and relationship','Tone and vocabulary should suit audience/purpose.'],
 ['Which is suitable formally?',['I write to request the repair of…','Hey bro, fix this thing','What’s up sir?','You people are useless'],'I write to request the repair of…','It is respectful and purpose-focused.'],
 ['If a task asks for three problems and two solutions, a complete letter should…',['address all five demands','choose one problem only','ignore solutions','discuss another topic'],'address all five demands','Content fulfilment is essential.'],
 ['An informal letter may be…',['warm and conversational','carelessly ungrammatical','written without paragraphs','addressed to an institution only'],'warm and conversational','Informality affects tone, not correctness.'],
 ['A complaint is strongest when it is…',['specific, factual and respectfully firm','insulting','vague','unrelated'],'specific, factual and respectfully firm','Clear evidence and requested action improve effectiveness.'],
 ['Which should NOT be mixed?',['formal format with slang friendship register','paragraphs with punctuation','purpose with evidence','heading with formal tone'],'formal format with slang friendship register','Format and register must match.'],
 ['The recipient should understand…',['the purpose/action requested','only the writer’s vocabulary level','nothing until the last line','an unrelated story'],'the purpose/action requested','Communication should be clear.'],
 ['The closing of a letter should…',['match the type/register','always be identical for every audience','be omitted','contain a new essay'],'match the type/register','Conventions differ by letter type.'],
 ['Before writing, underline…',['content demands in the question','only the word “letter”','every preposition','the examiner’s name'],'content demands in the question','This prevents omission.'],
 ['Which is a content error?',['failing to suggest solutions when required','using paragraphs','including a date','using a heading formally'],'failing to suggest solutions when required','Missing task requirements loses substance.'],
 ['A letter to your principal about an official school matter is usually…',['formal','informal because you know the principal','poetry','narrative only'],'formal','The communication is in an official relationship.'],
 ['Why use paragraphs?',['to organise distinct ideas clearly','to make the letter longer','to avoid punctuation','to hide the purpose'],'to organise distinct ideas clearly','Paragraphing improves coherence.'],
 ['A formal heading such as “REQUEST FOR…” is useful because it…',['states the subject immediately','replaces the salutation','serves as the address','is a signature'],'states the subject immediately','It clarifies the official purpose.'],
 ['Which is inappropriate in a formal letter?',['texting abbreviations and uncontrolled slang','clear evidence','respectful request','specific heading'],'texting abbreviations and uncontrolled slang','Formal register requires conventional language.'],
 ['Final editing should check…',['format, content, register and mechanics','only address length','only handwriting','only greeting'],'format, content, register and mechanics','All dimensions matter.'],
 ['The best way to choose formal vs informal is by…',['relationship and communicative purpose','topic length','number of paragraphs','day of the week'],'relationship and communicative purpose','Audience/purpose determines the form.']
 ])};

export const jss3SummaryWriting:Jss3EnglishLesson={
 topic:'Summary Writing',strand:'Writing',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Identify topic sentences.','Identify key ideas from different paragraphs.','Write concise phrases/sentences that summarise passages.','Apply summary skills to informational passages including monitoring devices and their uses.'],
 plan:{topic:'Summary Writing',objective:'Turn identified main ideas into concise, accurate, grammatical summary sentences.',units:[
 U('Reading for summary versus writing summary','Reading for summary finds the essentials; summary writing expresses those essentials concisely. The writing stage demands grammatical sentences, accurate meaning and obedience to the requested number/form of points.'),
 U('Answer the exact summary question','A passage may discuss causes, effects and solutions, while the question asks only for causes. Summarising the whole passage wastes effort. Circle the required focus before extracting points.'),
 U('Extract before rewriting','For each relevant paragraph, first write a tiny note: “camera—observes traffic”; “speed detector—measures vehicle speed”; “radio—reports incidents”. Then convert only required notes into polished sentences. Extraction separates thinking from wording.'),
 U('Topic sentence and hidden main idea','Some paragraphs state the main point directly; others imply it through details. If every sentence describes ways cameras help officers see distant road activity, the main idea may be “Cameras enable remote traffic observation” even if that exact sentence never appears.'),
 U('Compression techniques','Remove examples when not required; replace lists with a category; combine repeated points; use a shorter synonym/phrase; remove decorative modifiers. Original: “large, extremely costly and very expensive equipment” → “expensive equipment” if size is irrelevant to the question.'),
 U('Do not merge distinct points','Compression must not collapse two separately required ideas. “Cameras observe traffic” and “radar measures speed” are different functions. If the question requests two uses, preserve both.'),
 U('Write complete sense','Notes such as “for monitoring roads” may be useful during extraction but the final answer may require a full sentence: “Cameras enable officers to monitor road conditions remotely.” Follow the examination instruction about phrases/sentences.'),
 U('No imported knowledge','If you know additional facts about CCTV, do not add them unless the passage states them and the question requires them. Summary assesses the source, not how much outside information you know.'),
 U('Monitoring devices application','NERDC’s JSS3 content uses monitoring devices as an application. Typical categories in a passage may include observation cameras, speed-monitoring devices and communication/tracking equipment. Learn the summary skill: identify each device named by the source and state only the use the passage assigns to it.'),
 U('Worked compression','Original: “Because officers cannot stand at every junction throughout the day, cameras positioned at selected points allow the control room to observe traffic continuously.” Summary: “Cameras allow continuous remote observation of traffic.” Cause/context is removed because the required point is the device’s use.'),
 U('Common errors','Copying an entire paragraph; writing telegraphic fragments when sentences are requested; repeating one idea in two forms; including examples as separate main points; changing meaning; adding personal advice; exceeding the requested number of points.'),
 U('Final check','Count required points; verify each answers the exact question; compare each with the source; remove duplication; check grammar; ensure pronouns have clear referents; keep wording concise.'),
 U('Mastery checkpoint','You can extract requested points from several paragraphs, distinguish a device from its use, paraphrase accurately, produce concise grammatical sentences and avoid adding outside knowledge.')
 ]},
 questions:makeQs('j3e-swrite',[
 ['Summary writing begins by…',['identifying the exact required focus','copying the first paragraph','adding personal views','counting adjectives'],'identifying the exact required focus','The question determines which ideas matter.'],
 ['A good summary sentence is…',['concise and faithful','longer than the source','full of new examples','unrelated'],'concise and faithful','Compression must preserve meaning.'],
 ['If the question asks only for causes, include…',['causes stated in the passage','all effects too','your solutions','the title only'],'causes stated in the passage','Answer the requested aspect.'],
 ['Extraction notes are useful because they…',['separate key-point identification from final wording','replace the final answer always','add outside knowledge','make every point longer'],'separate key-point identification from final wording','They help organise thinking.'],
 ['Which may be removed when not required?',['illustrative examples','an essential cause','a required main idea','the requested use of a device'],'illustrative examples','Examples often support rather than constitute the required point.'],
 ['Two distinct required ideas should…',['remain distinct','always be merged into one vague point','be replaced by opinion','be omitted'],'remain distinct','Do not lose separately creditable points.'],
 ['A summary should normally avoid…',['outside information not in the source','paraphrase','grammar','main ideas'],'outside information not in the source','The source controls the answer.'],
 ['“Cameras allow continuous remote observation of traffic” is…',['a concise statement of use','an address','a salutation','a narrative climax'],'a concise statement of use','It compresses the function clearly.'],
 ['Repeating one idea twice is…',['duplication','balance','scanning','intonation'],'duplication','Each summary point should contribute distinct information.'],
 ['If sentences are requested, notes like “for traffic” are…',['too fragmentary','always perfect','a formal heading','a topic sentence automatically'],'too fragmentary','Final form must follow instructions.'],
 ['A hidden main idea may be…',['inferred from consistent supporting details','invented freely','unrelated to the paragraph','taken from another book'],'inferred from consistent supporting details','It must be supported by the paragraph.'],
 ['Which best compresses “very costly and extremely expensive”?',['expensive','cheap','large and cheap','free'],'expensive','It removes repetition without changing the cost meaning.'],
 ['A summary should preserve…',['important logical relationships','every adjective','every example','the writer’s exact sentence length'],'important logical relationships','Cause, contrast and result may be essential.'],
 ['Monitoring-device passages test whether learners can…',['identify key ideas and state uses concisely','repair electronics','invent devices','draw circuits only'],'identify key ideas and state uses concisely','The English skill is comprehension and summary.'],
 ['After drafting, count points to…',['match the number requested','increase length','avoid grammar','change the topic'],'match the number requested','Instruction compliance matters.'],
 ['Which is an error?',['adding a fact you know but the passage never states','paraphrasing accurately','removing repetition','checking grammar'],'adding a fact you know but the passage never states','Summary must remain source-bound.'],
 ['A topic sentence helps because it often…',['states a paragraph’s controlling idea','contains every example','gives the page number','is always a quotation'],'states a paragraph’s controlling idea','It can reveal the key point.'],
 ['Paraphrase should…',['change wording without changing meaning','reverse cause and effect','add judgement','remove every key idea'],'change wording without changing meaning','Fidelity is essential.'],
 ['A final summary check should remove…',['duplication','required points','grammar','meaning'],'duplication','Repeated points waste space and credit.'],
 ['NERDC expects learners to summarise…',['passages/paragraphs through key ideas','only poems','only letters','only dialogue'],'passages/paragraphs through key ideas','This is explicit in the evaluation guide.']
 ])};


export const jss3Phonemes:Jss3EnglishLesson={
 topic:'Speech / Phonemes',strand:'Listening and Speaking',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Identify and produce contrasting long and short vowels.','Identify and produce consonant sounds.','Identify and produce consonant clusters in context.','Recognise and use diphthongs in words and sentences.','Apply sound discrimination in connected speech.'],
 plan:{topic:'Speech / Phonemes',objective:'Hear and produce important English sound contrasts clearly in words, sentences and connected speech.',units:[
 U('Sound, not spelling','A phoneme is a sound unit that can distinguish meaning. English spelling is not a perfect sound guide: “machine” begins with letters ma but its later sound pattern differs from what spelling alone predicts. Train the ear and mouth, not only the eye.'),
 U('Minimal pairs','A minimal pair differs in one sound and shows that the contrast matters: ship/sheep, bit/beat, full/fool. Say each slowly, then normally. Ask: which sound changed and did the word change?'),
 U('Short /ɪ/ and long /iː/','Compare bit/beat, sit/seat, live/leave, fill/feel, ship/sheep. /iː/ is generally longer and tenser; /ɪ/ is shorter. Do not merely stretch any “i” spelling—listen to the word’s actual pronunciation. Sentence drill: “The sheep will sit near the seat.”'),
 U('Other vowel contrasts','Practise pairs such as full/fool (/ʊ/–/uː/) and cot/caught where the target accent distinguishes them. The learning goal is consistent intelligible contrast, not mocking a learner’s home accent. Use model audio/teacher pronunciation and repeated discrimination.'),
 U('Consonants','Consonant sounds involve some obstruction of airflow. Contrast sounds that learners may confuse: /f/ and /v/ in fan/van, fine/vine; /s/ and /z/ in sip/zip; /t/ and /d/ in ten/den. Feel voicing: place fingers lightly on the throat—/v/ vibrates more than /f/.'),
 U('/θ/ and /ð/','For the sounds in thin and this, the tongue tip is near/between the teeth and air passes through. Contrast thin/tin, thank/tank; then this/dis, though/do as appropriate discrimination practice. Aim for intelligibility through careful modelling rather than spelling guesses.'),
 U('Consonant clusters','A cluster contains two or more consonant sounds together without an intervening vowel: /st/ in stop, /pl/ in play, /str/ in street, final /nd/ in hand. Do not insert an extra vowel (“sətop”) or delete a sound (“sreet”). Build slowly: s + top → stop; s + t + reet → street.'),
 U('Initial and final clusters','Initial: play, school, spring, street. Final: helped, asked, next, hands. Final clusters can be harder because several consonants meet. Practise the base then add the ending: help → helped; ask → asked.'),
 U('Diphthongs','A diphthong glides from one vowel quality toward another within one syllable. Examples include /eɪ/ day, /aɪ/ my, /ɔɪ/ boy, /aʊ/ now, /əʊ/ go in common teaching models. Hear the movement rather than pronouncing two separate syllables.'),
 U('Diphthongs in sentences','“The boy found a coin.” Focus /ɔɪ/ in boy/coin. “They may go home today.” Focus /eɪ/ in may/today and /əʊ/ in go/home. Mark the target words, listen, repeat, then say the full sentence naturally.'),
 U('From word to connected speech','Correct isolation is only the first step. Practise target sounds in phrases and sentences at natural pace. Record, compare with a reliable model, identify one contrast to improve, repeat. Do not try to correct every sound at once.'),
 U('Listening discrimination','Teacher/audio says one word from a pair: ship/sheep, fan/van, sip/zip. Learner identifies it before seeing spelling. This proves the ear can distinguish the phonemes. Then reverse: learner produces, partner identifies.'),
 U('Common errors','Judging sound only from spelling; inserting vowels into clusters; dropping final consonants; treating diphthongs as two syllables; knowing IPA symbols but being unable to hear/produce the sound. Oral mastery requires listening and production.'),
 U('Mastery checkpoint','You can discriminate long/short vowel contrasts, produce key consonant contrasts, pronounce initial/final clusters without insertion/deletion, identify common diphthongs and use all targets intelligibly in connected sentences.')
 ]},
 questions:makeQs('j3e-phon',[
 ['A phoneme is best understood as…',['a sound unit that can distinguish meaning','a paragraph','a punctuation mark','a letter name only'],'a sound unit that can distinguish meaning','Phonemes function in the sound system.'],
 ['Which pair contrasts /ɪ/ and /iː/?',['ship/sheep','fan/van','sip/zip','ten/den'],'ship/sheep','The vowel contrast changes the word.'],
 ['Which word commonly contains /iː/?',['seat','sit','bit','ship'],'seat','Seat uses the long vowel /iː/.'],
 ['Which pair contrasts /f/ and /v/?',['fan/van','bit/beat','sip/zip','thin/tin'],'fan/van','Only the target consonant changes.'],
 ['Voicing can be felt by…',['lightly touching the throat','closing the book','counting letters','writing capitals'],'lightly touching the throat','Voiced sounds create vocal-fold vibration.'],
 ['A consonant cluster occurs in…',['street','ago','idea','open'],'street','/str/ is an initial consonant cluster.'],
 ['An error in “sətop” for “stop” is…',['vowel insertion into a cluster','diphthong production','correct clustering','stress marking'],'vowel insertion into a cluster','The cluster should not be split by an added vowel.'],
 ['Which has a final cluster?',['asked','away','open','idea'],'asked','The ending contains multiple consonant sounds.'],
 ['A diphthong involves…',['a glide between vowel qualities in one syllable','two paragraphs','only consonants','a silent letter only'],'a glide between vowel qualities in one syllable','It is a moving vowel quality.'],
 ['/aɪ/ is heard in…',['my','day','boy','go'],'my','“my” contains /aɪ/.'],
 ['/ɔɪ/ is heard in…',['boy','now','day','see'],'boy','“boy” contains /ɔɪ/.'],
 ['Why practise minimal pairs?',['to hear how one sound changes meaning','to memorise addresses','to learn paragraphs','to avoid listening'],'to hear how one sound changes meaning','They isolate a contrast.'],
 ['Which is an initial cluster?',['/pl/ in play','the vowel in see','the vowel in my','the full stop'],'/pl/ in play','Two consonants occur together initially.'],
 ['Oral mastery requires…',['identification and production','symbol memorisation only','spelling only','silent reading only'],'identification and production','NERDC requires learners to produce sounds.'],
 ['The safest way to learn pronunciation is to…',['use reliable models plus listening and practice','guess from spelling alone','add vowels to clusters','ignore context'],'use reliable models plus listening and practice','Sound learning needs auditory models.'],
 ['Which pair contrasts /s/ and /z/?',['sip/zip','fan/van','bit/beat','full/fool'],'sip/zip','The initial consonant changes.'],
 ['A learner who recognises /str/ but says “sreet” is…',['deleting a cluster sound','adding a diphthong','using correct cluster','changing tense'],'deleting a cluster sound','/t/ has been omitted.'],
 ['Connected-speech practice means…',['using target sounds in natural phrases/sentences','writing IPA only','reading letters separately','avoiding sentences'],'using target sounds in natural phrases/sentences','Production must transfer beyond isolated words.'],
 ['Which is NOT enough for phoneme mastery?',['knowing symbols without hearing/producing sounds','discrimination practice','sentence production','minimal-pair listening'],'knowing symbols without hearing/producing sounds','The topic is listening and speaking.'],
 ['A good self-correction routine is…',['record, compare, target one contrast, repeat','speak faster without listening','change every sound at once','avoid models'],'record, compare, target one contrast, repeat','Focused feedback supports improvement.']
 ])},
 performanceTasks:['Listen to 12 minimal-pair items and identify the word heard before seeing spelling.','Record five sentences containing long/short vowels, /f/-/v/ contrasts and clusters; compare with a model.','Build and pronounce ten consonant clusters from slow segmentation to natural speech.']
};

export const jss3Prosody:Jss3EnglishLesson={
 topic:'Intonation, Stress and Rhythm',strand:'Listening and Speaking',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Identify appropriate intonation patterns for statements, questions and commands.','Produce statements, questions and commands with appropriate intonation.','Identify and use stress meaningfully.','Recognise rhythm and recite poems with appropriate rhythm.'],
 plan:{topic:'Intonation, Stress and Rhythm',objective:'Use pitch movement, prominence and timing to make spoken English clear and meaningful.',units:[
 U('Speech has melody','Intonation is the movement of voice pitch across an utterance. The same words can sound complete, questioning, surprised or doubtful depending on pitch movement. Do not confuse intonation with simply speaking loudly.'),
 U('Falling intonation','A fall is common in complete statements, many WH-questions and firm commands: “The bus has arrived ↘.” “Where are you going ↘?” “Close the door ↘.” Context can change patterns, so learn the normal functions before exceptions.'),
 U('Rising intonation','A rise is common in yes/no questions and can signal incompleteness or checking: “Are you ready ↗?” “Did she call ↗?” A rise can also make a statement sound like a check rather than a firm assertion.'),
 U('Fall-rise','Fall-rise often suggests reservation, contrast, politeness or “there is more”. “I like it ↘↗” may imply “but…”. NERDC asks for three intonation patterns; learners should hear and practise fall, rise and fall-rise rather than memorise arrows only.'),
 U('Stress','Stress gives a syllable or word greater prominence through a combination of loudness, length and pitch. Word stress: PREsent (noun) vs preSENT (verb) in many standard models. Sentence stress highlights important information.'),
 U('Meaning through sentence stress','“SHE borrowed my book” corrects who. “She borrowed MY book” corrects whose. “She BORROWED my book” contrasts borrowing with another action. Stress can redirect meaning even when the words stay the same.'),
 U('Content and function words','In neutral English rhythm, nouns, main verbs, adjectives and adverbs often carry stronger stress; articles, auxiliaries and prepositions are often weaker. This is a tendency, not an unbreakable rule—any word can receive contrastive stress.'),
 U('Rhythm','Rhythm is the patterned movement of stressed and unstressed syllables in speech. In poetry, rhythm may be especially noticeable through repeated beats, syllable patterns, pauses and sound effects. Do not turn rhythm into mechanical shouting.'),
 U('Chunking and pauses','Meaningful thought groups improve delivery: “After the rain stopped / the players returned to the field.” Pausing at sense boundaries helps listeners follow ideas. Random pauses can distort meaning.'),
 U('Poetry performance','First understand the poem; mark sense groups; underline prominent words; note punctuation; identify repeated beat/sound; practise slowly; then recite naturally. Appropriate rhythm supports meaning and mood, not merely speed.'),
 U('Commands and questions','Compare “Sit down ↘” (firm command), “Sit down ↗?” (checking/surprised in a special context), “Can you sit down ↗?” (yes/no request). Grammar and intonation work together.'),
 U('Common errors','Using a flat pitch for every sentence; assuming every question rises; stressing every word equally; confusing loudness with stress; racing through poetry without sense pauses; memorising arrows without producing the sound.'),
 U('Mastery checkpoint','You can identify and produce fall, rise and fall-rise in suitable contexts; shift sentence stress to change focus; mark sense groups; and recite a short poem with meaningful rhythm and pauses.')
 ]},
 questions:makeQs('j3e-pros',[
 ['Intonation is…',['pitch movement across an utterance','spelling pattern','paragraph length','handwriting'],'pitch movement across an utterance','It is the melody of speech.'],
 ['A normal complete statement often takes…',['falling intonation','rising only','no pitch at all','spelling stress'],'falling intonation','A fall commonly signals completion.'],
 ['A yes/no question commonly takes…',['rising intonation','fall only in every context','no intonation','a comma'],'rising intonation','Rise commonly marks yes/no questioning.'],
 ['A WH-question commonly has…',['a fall in neutral use','always a rise','no stress','only fall-rise'],'a fall in neutral use','Many WH-questions normally fall.'],
 ['Fall-rise can suggest…',['reservation or contrast','a spelling error','plural only','past tense only'],'reservation or contrast','It often signals qualified meaning.'],
 ['Stress makes a syllable/word…',['more prominent','silent','a paragraph','ungrammatical'],'more prominent','Prominence combines several acoustic cues.'],
 ['“SHE borrowed my book” focuses on…',['who borrowed it','whose book','when','where'],'who borrowed it','Stress on SHE corrects/contrasts the person.'],
 ['“She borrowed MY book” focuses on…',['ownership','time','place','question type'],'ownership','MY receives contrastive prominence.'],
 ['Rhythm involves…',['patterned stressed and unstressed movement','only loudness','only spelling','addresses'],'patterned stressed and unstressed movement','Speech and poetry have timing patterns.'],
 ['A good poetry recitation should…',['reflect meaning, pauses and rhythm','be shouted at one volume','ignore punctuation','be as fast as possible'],'reflect meaning, pauses and rhythm','Performance should serve meaning.'],
 ['Random pauses may…',['distort meaning','always improve speech','create correct stress automatically','replace grammar'],'distort meaning','Thought groups should guide pauses.'],
 ['Which is NOT one of the three patterns taught here?',['fall','rise','fall-rise','capitalisation'],'capitalisation','Capitalisation is writing, not intonation.'],
 ['Every question rises. This statement is…',['false','always true','a definition of stress','a rhythm rule'],'false','WH-questions often fall; context also matters.'],
 ['Sentence stress can…',['change information focus','change spelling automatically','remove grammar','replace words'],'change information focus','Prominence tells listeners what is contrasted/new.'],
 ['Content words are often…',['more prominent in neutral speech','always silent','never stressed','punctuation'],'more prominent in neutral speech','They commonly carry lexical information.'],
 ['Function words…',['can receive contrastive stress when needed','can never be stressed','are not English','must be shouted'],'can receive contrastive stress when needed','Stress responds to meaning.'],
 ['A firm command often ends with…',['a fall','a mandatory rise','no pitch','a question mark'],'a fall','Falling intonation commonly signals firmness/completion.'],
 ['Before reciting a poem, first…',['understand its meaning','memorise arrows only','ignore punctuation','increase speed'],'understand its meaning','Prosody should express content.'],
 ['NERDC expects learners to…',['identify and produce appropriate patterns','identify only on paper','avoid speaking','study spelling only'],'identify and produce appropriate patterns','Listening and speaking require performance.'],
 ['Prosodic mastery is shown by…',['meaningful spoken use, not symbol memorisation','drawing arrows only','writing definitions only','reading silently'],'meaningful spoken use, not symbol memorisation','Production demonstrates control.']
 ])},
 performanceTasks:['Record the same short sentence with falling, rising and fall-rise contours and explain the meaning difference.','Move contrastive stress across a five-word sentence and explain each focus change.','Mark and recite a short poem with sense groups, stress and rhythm, then self-evaluate.']
};

export const jss3EnglishLessons: Jss3EnglishLesson[]=[jss3CriticalEvaluation,jss3ReadingSpeed,jss3ReadingSummary,jss3Composition,jss3LetterWriting,jss3SummaryWriting,jss3Phonemes,jss3Prosody];
