export type DeepJss3MathLesson={
 topicId:string; classLevel:'JSS3'; subject:'Mathematics'; topic:string;
 source:{authority:'NERDC';url:string;page:number}; objectives:string[]; prerequisites:string[];
 teaching:string[]; workedExamples:string[]; misconceptions:string[]; guidedPractice:string[]; independentPractice:string[];
 mastery:{criterion:string;status:'DEEP_WHEN_PASSED'}; boardReady:true;
};

const sourceUrl='https://nerdc.gov.ng/content_manager/jss/jss1-3_maths.pdf';

/**
 * AVORA-authored JSS3 Mathematics teaching layer.
 * NERDC is used for curriculum scope and performance objectives. Explanations,
 * examples, practice and mastery tasks below are original AVORA teaching content.
 */
export const jss3MathematicsDeepLessons:DeepJss3MathLesson[]=[
{
 topicId:'nerdc-jss3-math-numbers-and-numeration-whole-numbers-1',classLevel:'JSS3',subject:'Mathematics',topic:'Whole Numbers',source:{authority:'NERDC',url:sourceUrl,page:28},
 objectives:['Revise basic operations in the binary number system','Convert binary numbers to other bases and convert numbers from other bases to binary','Solve quantitative-reasoning problems involving binary numbers','Use a computer or calculator appropriately for simple mathematical calculations','Translate verbal statements and word problems into numerical expressions','Simplify expressions involving brackets and fractions','Solve direct- and inverse-proportion problems and apply them to practical situations','Solve compound-interest problems and connect compound interest to everyday financial situations'],
 prerequisites:['JSS1/JSS2 binary notation and place value','fraction operations and BODMAS','ratio, rate and percentage','simple interest and repeated percentage change'],
 teaching:[
  'BINARY REVISION — PLACE VALUE BEFORE PROCEDURE. Binary is a base-two place-value system. From right to left, the places are 2⁰=1,2¹=2,2²=4,2³=8,2⁴=16 and so on. Only the digits 0 and 1 are valid. Every binary operation must preserve these place values.',
  'BINARY ADDITION. The basic facts are 0+0=0, 0+1=1, 1+1=10₂ and 1+1+1=11₂. Regroup whenever a column reaches two because two units of one binary place make one unit of the next place.',
  'BINARY SUBTRACTION. When 0−1 occurs, borrow one unit from the next binary place. That borrowed unit is worth 10₂ in the current place. Record every regrouping, especially when borrowing passes across zeros.',
  'BINARY MULTIPLICATION. Multiplying by 1 reproduces the multiplicand and multiplying by 0 gives zero. In long multiplication, each move one place left represents multiplication by 2, so partial products must be shifted correctly.',
  'BINARY DIVISION. Use the same compare→write quotient digit→multiply→subtract→bring down cycle as ordinary long division, but quotient digits are only 0 or 1. Verify with divisor×quotient+remainder=dividend.',
  'BINARY TO BASE TEN. Multiply each binary digit by its power-of-two place value and add. Never read 101101₂ as “one hundred and one thousand…” because its digits do not represent decimal place values.',
  'BASE TEN TO BINARY. Repeatedly divide by 2, record each remainder, and read the remainders from bottom to top. The bottom-to-top order works because the first remainder gives the 2⁰ place, the next gives 2¹, and so on.',
  'OTHER BASES AND BINARY. A safe general route is source base→base ten→binary or binary→base ten→target base. Check that every digit used is legal for its base before calculating.',
  'QUANTITATIVE REASONING WITH BASES. Questions may hide the base-system idea inside counting, coding or place-value patterns. Write the place values explicitly before operating rather than treating the numeral as a decimal number.',
  'USING A CALCULATOR OR COMPUTER WELL. Technology can perform arithmetic quickly, but the learner must estimate first, enter the expression correctly, read the display with units, and decide whether the answer is reasonable. A calculator cannot repair a wrongly translated expression.',
  'TRANSLATING WORDS INTO MATHEMATICS. Identify the quantities, then the relationship. Sum means addition, difference means subtraction, product means multiplication and quotient means division. Phrases such as “5 less than x” reverse the spoken order: x−5, not 5−x.',
  'BRACKETS PRESERVE GROUPING. “Three times the sum of x and 4” is 3(x+4), not 3x+4. “The difference between 7 and the sum of half of 8 and 3” is 7−(8/2+3). Translate before simplifying.',
  'EXPRESSIONS WITH BRACKETS. Use distributive multiplication: a(b+c)=ab+ac. Multiply every term inside the bracket, then collect only like terms. A minus sign before a bracket changes every sign inside when the bracket is removed.',
  'EXPRESSIONS WITH FRACTIONS. Fractions follow ordinary arithmetic rules. For addition/subtraction, use a common denominator; for multiplication, multiply numerators and denominators; for division, multiply by the reciprocal. Apply BODMAS to mixed expressions.',
  'DIRECT PROPORTION. If y is directly proportional to x, then y=kx and y/x=k is constant. If x doubles, y doubles. Find k from one known pair, then use the same k for another pair.',
  'INVERSE PROPORTION. If y is inversely proportional to x, then y=k/x and xy=k is constant. When one quantity increases, the other decreases so their product stays constant. This often appears in fixed-work problems involving workers and time.',
  'HOW TO CHOOSE DIRECT OR INVERSE. Ask what should happen if one quantity doubles. If the other should also double, the relation is direct. If the other should halve for the same total task or quantity, it is inverse. Do not choose by keywords alone.',
  'COMPOUND INTEREST — MEANING FIRST. Compound interest adds each period’s interest to the balance. The next period earns interest on the new balance, so the interest amount can grow from one year to the next.',
  'COMPOUND INTEREST YEAR-BY-YEAR. If ₦50,000 earns 8% annually, year 1 interest is 0.08×50,000=₦4,000, giving ₦54,000. Year 2 interest is 0.08×54,000=₦4,320, giving ₦58,320. Compound interest after two years is ₦8,320.',
  'COMPOUND-INTEREST FORMULA. Repeated multiplication by the same growth factor gives A=P(1+r/100)^n. This formula is a compressed version of the year-by-year method, not a separate rule. Compound interest=amount−principal.',
  'SIMPLE VS COMPOUND INTEREST. Simple interest is calculated repeatedly on the original principal; compound interest is calculated on the growing balance. Over more than one period at a positive rate, compound interest is normally larger.',
  'PERMANENT CHECKING STANDARD. Reconvert number-base answers, substitute translated expressions into the original wording, test proportion answers using the constant, compare compound-interest formula with year-by-year growth, and estimate calculator results before trusting them.'
 ],
 workedExamples:[
  'BINARY ADDITION. Calculate 1011₂+0110₂.\n      1 0 1 1\n    + 0 1 1 0\n    ---------\n    1 0 0 0 1₂\nFrom the right: 1+0=1; 1+1=10₂, write 0 carry 1; 0+1+1=10₂, write 0 carry 1; 1+0+1=10₂, write 0 carry 1; bring down the final carry. Check: 11+6=17 and 10001₂=17₁₀.',
  'BINARY SUBTRACTION. Calculate 1010₂−0011₂. Since 0−1 requires borrowing, regroup in base two. The result is 0111₂. Check in base ten: 10−3=7, and 111₂=7.',
  'BINARY MULTIPLICATION. 101₂×11₂. First partial product: 101₂×1=101₂. Second partial product is shifted left: 101₂×10₂=1010₂. Add 0101₂+1010₂=1111₂. Check: 5×3=15.',
  'BINARY DIVISION. 111₂÷11₂. In base ten this is 7÷3, but work in binary: quotient 10₂, remainder 1₂. Verify: 11₂×10₂+1₂=110₂+1₂=111₂.',
  'BINARY TO DECIMAL. Convert 101101₂. Place values are 32,16,8,4,2,1. So 1×32+0×16+1×8+1×4+0×2+1×1=32+8+4+1=45. Therefore 101101₂=45₁₀.',
  'DECIMAL TO BINARY. Convert 45₁₀ by repeated division. 45÷2=22 r1; 22÷2=11 r0; 11÷2=5 r1; 5÷2=2 r1; 2÷2=1 r0; 1÷2=0 r1. Read remainders bottom to top: 101101₂.',
  'OTHER BASE TO BINARY. Convert 132₄ to binary through base ten. 132₄=1×4²+3×4+2=16+12+2=30₁₀. Convert 30 to binary: 11110₂. Therefore 132₄=11110₂.',
  'TRANSLATION — ORDER MATTERS. Translate “five less than x”. The quantity x is reduced by 5, so the expression is x−5. It is not 5−x.',
  'TRANSLATION — GROUPING. Translate “three times the sum of n and 4”. The sum must be formed first: n+4. Three times that whole sum is 3(n+4).',
  'TRANSLATION AND SIMPLIFICATION. “The difference between 7 and the sum of half of 8 and 3” becomes 7−(8/2+3)=7−(4+3)=7−7=0.',
  'BRACKETS. Simplify 3(2x−5)+4(x+1). Expand every term: 6x−15+4x+4. Collect like terms: 10x−11.',
  'MINUS BEFORE BRACKET. Simplify 5a−2(a−3). Distribute −2: 5a−2a+6=3a+6. The +6 appears because −2×−3=+6.',
  'FRACTION EXPRESSION. Simplify 3/4+5/6. LCM(4,6)=12. 3/4=9/12 and 5/6=10/12. Sum=19/12=1 7/12.',
  'DIRECT PROPORTION. Six notebooks cost ₦2,700 at constant price. Cost per notebook k=2700/6=₦450. Ten notebooks cost 10×450=₦4,500. Since quantity increased by factor 10/6, cost increases by the same factor.',
  'DIRECT PROPORTION WITH EQUATION. If y∝x and y=18 when x=6, then y=kx gives 18=6k, so k=3. When x=11, y=3×11=33.',
  'INVERSE PROPORTION. Eight workers finish a fixed job in 15 days. Worker-days are constant: 8×15=120. For 12 workers, days=120/12=10. More workers lead to fewer days for the same fixed job.',
  'INVERSE PROPORTION WITH EQUATION. If y∝1/x and y=20 when x=3, then xy=k=60. When x=5, y=60/5=12.',
  'COMPOUND INTEREST — YEAR BY YEAR. ₦20,000 at 10% annually for 2 years. Year 1 interest=₦2,000, balance=₦22,000. Year 2 interest=₦2,200, balance=₦24,200. Compound interest=₦4,200.',
  'COMPOUND INTEREST — FORMULA. ₦50,000 at 8% annually for 2 years: A=50,000(1.08)²=50,000×1.1664=₦58,320. CI=58,320−50,000=₦8,320.',
  'SIMPLE VS COMPOUND. ₦100,000 at 10% for 2 years. Simple interest=100,000×10×2/100=₦20,000, amount=₦120,000. Compound amount=100,000(1.1)²=₦121,000, so compound interest=₦21,000. The extra ₦1,000 is interest earned on the first year’s interest.',
  'CALCULATOR REASONABLENESS. Evaluate 19.8×5.03. Estimate first: 20×5≈100. A calculator result of about 99.594 is reasonable; a display of 995.94 would signal a likely entry or decimal-place error.'
 ],
 misconceptions:[
  'reading a binary numeral as an ordinary decimal number',
  'using an invalid digit such as 2 in base two',
  'forgetting binary carries or borrows are based on groups of two rather than ten',
  'reading repeated-division remainders top-to-bottom when converting decimal to binary',
  'using a digit that is illegal in the stated base',
  'translating “5 less than x” as 5−x instead of x−5',
  'dropping brackets from phrases such as “three times the sum”',
  'multiplying an outside factor by only the first term inside a bracket',
  'adding fraction numerators and denominators directly',
  'treating every two-quantity question as direct proportion',
  'using inverse proportion when the total task is not fixed',
  'calculating compound interest each year only on the original principal',
  'using the compound-interest formula without converting the rate correctly to a decimal growth factor',
  'accepting a calculator display without checking order of magnitude, unit or meaning'
 ],
 guidedPractice:[
  'Add 111₂+101₂ and verify in base ten.',
  'Subtract 1000₂−0110₂ and verify by binary addition.',
  'Multiply 110₂×101₂ using shifted partial products.',
  'Divide 1011₂ by 10₂ and state quotient and remainder.',
  'Convert 110011₂ to base ten, then convert 51₁₀ back to binary.',
  'Convert 213₄ to base ten and then to binary.',
  'Translate: “seven more than twice x”, “four less than the product of 3 and n”, and “half the difference between p and 6”.',
  'Simplify 2(3x+4)−5(x−1).',
  'Simplify 5/8+3/4−1/2.',
  'If 8 pens cost ₦3,600, find the cost of 15 at the same rate and justify direct proportion.',
  'If 10 workers need 18 days for a fixed task, estimate and then calculate the time for 15 workers.',
  'Find amount and compound interest on ₦30,000 at 5% annually for 3 years using the year-by-year method, then verify with the formula.'
 ],
 independentPractice:[
  'Evaluate 10101₂+1110₂.',
  'Evaluate 11000₂−1011₂.',
  'Evaluate 101₂×110₂.',
  'Evaluate 1101₂÷11₂ and verify.',
  'Convert 100111₂ to base ten.',
  'Convert 73₁₀ to binary.',
  'Convert 231₄ to binary through base ten.',
  'Translate “nine less than three times a number x”.',
  'Translate “twice the sum of p and 7”.',
  'Simplify 4(2a−3)+3(a+5).',
  'Simplify 7−2(3−x).',
  'Evaluate 2/3+5/8.',
  'Twelve exercise books cost ₦5,400. Find the cost of 20 at the same rate.',
  'A car uses 18 litres of fuel for 216 km at a constant consumption rate. How many litres are required for 300 km?',
  'Six machines make a fixed order in 15 hours. How long would 10 identical machines take?',
  'If y∝x and y=28 when x=4, find y when x=9.',
  'If y∝1/x and y=24 when x=5, find y when x=8.',
  'Find the amount and compound interest on ₦40,000 at 10% per annum for 2 years.',
  'Find the amount on ₦75,000 at 6% compounded annually for 3 years.',
  'Compare simple and compound interest on ₦60,000 at 5% for 2 years.',
  'A calculator gives 4,965 for 49.8×9.97. Estimate first and decide whether the display is plausible.',
  'Create one real-life example each of direct and inverse proportion and explain why each model fits.'
 ],
 mastery:{criterion:'At least 80% across binary operations/conversion, verbal translation, bracket/fraction expressions, direct and inverse proportion, compound interest and calculator reasonableness, with method shown and every proportional model justified from the relationship.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-numbers-and-numeration-whole-numbers-2',classLevel:'JSS3',subject:'Mathematics',topic:'Rational and non-rational numbers',source:{authority:'NERDC',url:sourceUrl,page:29},
 objectives:['Identify rational numbers and non-rational (irrational) numbers','Determine experimentally an approximate value of pi using circular objects'],
 prerequisites:['fractions and equivalent fractions','terminating and recurring decimals','square roots and perfect squares','measurement of circumference and diameter'],
 teaching:[
  'START WITH THE SET IDEA. A rational number is any number that can be written exactly as p/q, where p and q are integers and q≠0. The word rational is connected to ratio. The fraction may not be obvious at first, so classification requires reasoning rather than appearance.',
  'EVERY INTEGER IS RATIONAL. Any integer n can be written as n/1. Therefore −7=−7/1, 0=0/1 and 12=12/1 are all rational.',
  'TERMINATING DECIMALS ARE RATIONAL. A terminating decimal has a finite number of decimal places and can be written over a power of 10. For example, 0.125=125/1000=1/8.',
  'RECURRING DECIMALS ARE RATIONAL. A decimal such as 0.333… repeats a fixed pattern forever and equals 1/3. A repeating block such as 0.121212… is also rational because the repetition can be converted exactly to a fraction.',
  'IRRATIONAL NUMBERS cannot be written exactly as p/q. Their decimal expansions continue without terminating and without settling into a repeating block. Common examples at this level include √2, √3, √5 and π.',
  'A SQUARE-ROOT SYMBOL DOES NOT AUTOMATICALLY MEAN IRRATIONAL. Simplify first. √49=7, so it is rational. √72=√(36×2)=6√2, so it is irrational because √2 is irrational.',
  'PERFECT-SQUARE TEST. For a positive integer under a square root, check whether it is a perfect square after simplification. If the simplified root is an integer, the value is rational. If an irrational root remains, the number is irrational.',
  'RATIONAL PLUS OR MINUS RATIONAL remains rational. Rational×rational and rational÷non-zero rational are rational. At this level, mixed expressions containing an irrational term must be handled carefully; an irrational-looking expression may simplify to a rational value in special cases.',
  'EXACT FORM VS APPROXIMATION. √2 and π are exact symbols. Writing √2≈1.414 or π≈3.142 gives approximations. Do not replace an exact irrational number with a rounded decimal too early if the question does not ask for an approximation.',
  'COMPARING IRRATIONAL NUMBERS. Estimate them using nearby perfect squares or known decimal approximations. Since 4<5<9, 2<√5<3. Testing 2.2²=4.84 and 2.3²=5.29 shows √5 lies between 2.2 and 2.3.',
  'ORDERING MIXED NUMBERS. Convert or approximate only enough to compare. For −√4,−1.5,0,√3: −√4=−2 and √3≈1.732, so order is −2<−1.5<0<√3.',
  'PI IS A RATIO ARISING FROM CIRCLES. For any circle, circumference divided by diameter is approximately the same constant, π. The exact value of π is irrational; 22/7 and 3.142 are useful approximations, not definitions.',
  'EXPERIMENTAL PI. Measure the circumference C and diameter d of several circular objects. For each object calculate C/d. Good measurements should produce values close to 3.14. Differences arise from ruler/tape precision, thickness of the object, difficulty locating the exact diameter and ordinary measurement error.',
  'WHY MULTIPLE OBJECTS HELP. One inaccurate measurement can give a poor estimate. Repeating the experiment with several circles allows the learner to see the stable pattern and, if required, calculate a mean estimate.',
  'PERMANENT CLASSIFICATION RULE. Before calling a number rational or irrational, ask: Can it be written exactly as p/q? Does a decimal terminate or recur? Can a square root simplify to an integer? Is the number exact or merely an approximation?'
 ],
 workedExamples:[
  'INTEGER. Classify −7. Since −7=−7/1 and both −7 and 1 are integers with non-zero denominator, −7 is rational.',
  'TERMINATING DECIMAL. Classify 0.125. 0.125=125/1000=1/8. Therefore it is rational.',
  'RECURRING DECIMAL. Classify 0.333…. This equals 1/3, so it is rational.',
  'RECURRING BLOCK. Let x=0.121212…. Then 100x=12.121212…. Subtract: 100x−x=12, so 99x=12 and x=12/99=4/33. Therefore the recurring decimal is rational.',
  'PERFECT-SQUARE ROOT. √81=9=9/1, so √81 is rational.',
  'NON-PERFECT ROOT. √20=√(4×5)=2√5. Since √5 is irrational, √20 is irrational.',
  'ROOT THAT LOOKS IRRATIONAL BUT IS NOT. √0.49=0.7=7/10. Therefore it is rational.',
  'SIMPLIFY BEFORE CLASSIFYING. √72=√(36×2)=6√2, so it is irrational. By contrast, √144=12, rational.',
  'MIXED CLASSIFICATION. Numbers: −4,2/7,0.75,0.121212…,√36,√7,π. Rational: −4,2/7,0.75,0.121212…,√36=6. Irrational: √7 and π.',
  'COMPARE √5 AND 2.3. Since 2.2²=4.84 and 2.3²=5.29, √5 is between 2.2 and 2.3; therefore √5<2.3.',
  'ORDER MIXED VALUES. Order −√4,−1.5,0,√3. Since −√4=−2 and √3≈1.732, the order is −2<−1.5<0<√3.',
  'APPROXIMATE EXPRESSION. Estimate 2+√3. Since √3≈1.732, 2+√3≈3.732. Exact form remains 2+√3.',
  'PI EXPERIMENT — ONE OBJECT. A lid has C=62.9cm and d=20.0cm. C/d=62.9/20.0=3.145. This is close to π.',
  'PI EXPERIMENT — SECOND OBJECT. A circular plate has C=78.5cm and d=25.0cm. C/d=78.5/25=3.14.',
  'PI EXPERIMENT — COMPARING MEASUREMENTS. Three objects give C/d values 3.12,3.15 and3.14. Mean=(3.12+3.15+3.14)/3≈3.137. The small spread suggests measurement error around a stable value near π.',
  '22/7 IS AN APPROXIMATION. 22/7≈3.142857…. π≈3.141592…. They are close but not equal. Therefore 22/7 is rational while π is irrational.'
 ],
 misconceptions:[
  'thinking every decimal is irrational',
  'thinking every non-terminating decimal is irrational even when it recurs',
  'thinking every square root is irrational',
  'classifying √49 as irrational without simplifying',
  'assuming a decimal displayed on a calculator is exact when it may be rounded',
  'using 22/7 as the exact definition of π',
  'calling 3.142 irrational because it approximates π; 3.142 is terminating and therefore rational',
  'classifying a number by appearance rather than by whether it can be expressed as p/q',
  'rounding an irrational number too early and then treating the rounded value as exact',
  'measuring a circle only once and treating measurement error as a change in π'
 ],
 guidedPractice:[
  'Classify −12,0,5/9,0.625,0.454545…,√64,√10 and π with a reason for each.',
  'Convert 0.272727… to a fraction using an algebraic recurring-decimal method.',
  'Simplify and classify √45,√121 and √0.81.',
  'Place √6 between two consecutive integers, then between two consecutive tenths.',
  'Order −2.2,−√5,0,√2,1.5 from least to greatest.',
  'State whether each is exact or approximate: π,3.14,√2,1.414.',
  'Measure circumference and diameter of two circular objects, calculate C/d and comment on the results.',
  'Given C/d measurements 3.13,3.16,3.14,3.15, calculate the mean estimate and explain why the values are not identical.'
 ],
 independentPractice:[
  'Classify 14 and justify.',
  'Classify −3/11 and justify.',
  'Classify 0.0375 and convert it to a fraction.',
  'Classify 0.6666… and state an exact fraction.',
  'Classify 0.101001000100001… and explain why the pattern does or does not recur.',
  'Simplify and classify √225.',
  'Simplify and classify √32.',
  'Simplify and classify √98.',
  'Classify π,22/7,3.14159 and explain the difference among them.',
  'Estimate √7 to 2 decimal places using nearby squares or a calculator check.',
  'Compare √10 and 3.2.',
  'Order −√9,−2.8,−√5,0,√2,1.6.',
  'Estimate 5−√6 to 2 decimal places while keeping 5−√6 as the exact form.',
  'A circular tin has circumference 94.3cm and diameter 30cm. Calculate C/d and compare with 3.14.',
  'Measure three circular household objects and prepare a table of object,C,d,C/d.',
  'Calculate the mean of your three C/d values.',
  'Give three reasons experimental C/d values may differ slightly.',
  'Explain in your own words why 3.142 is rational but π is irrational even though 3.142 is often used for π.'
 ],
 mastery:{criterion:'At least 85% correct classification across integers, fractions, terminating/recurring decimals and simplified roots, plus accurate exact-versus-approximate reasoning and a multi-object experimental estimate of π with measurement-error explanation.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-basic-operations-basic-operations-1',classLevel:'JSS3',subject:'Mathematics',topic:'Addition of numbers in base 2 numerals',source:{authority:'NERDC',url:sourceUrl,page:30},
 objectives:['Add two or three 3-digit binary numbers accurately'],
 prerequisites:['binary place value','base-ten addition and carrying'],
 teaching:['Binary addition follows place value exactly like ordinary addition, but regrouping occurs at 2 rather than 10. The basic facts are 0+0=0, 0+1=1, 1+1=10₂ and 1+1+1=11₂.','Work from right to left. When a column totals 2, write 0 and carry 1; when it totals 3, write 1 and carry 1. Align digits by place value before adding.','Check by converting the addends and answer to base ten. The base-ten sum should agree, but the working should still demonstrate binary addition.'],
 workedExamples:['101₂+011₂=1000₂ because 5+3=8.','111₂+101₂+010₂=1110₂ because 7+5+2=14.'],
 misconceptions:['using decimal carrying rules','writing 2 as a binary digit','misaligning place-value columns','forgetting a carried 1 when adding three numerals'],
 guidedPractice:['Add 101₂+110₂, then 011₂+101₂+111₂; verify both in base ten.'],
 independentPractice:['Ten binary additions, including two- and three-addend examples; convert three answers to base ten as checks.'],
 mastery:{criterion:'At least 9 of 10 additions correct, with valid binary digits and correct carrying shown.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-basic-operations-basic-operations-2',classLevel:'JSS3',subject:'Mathematics',topic:'Subtraction of numbers in base 2 numerals',source:{authority:'NERDC',url:sourceUrl,page:30},
 objectives:['Subtract 3-digit binary numbers accurately'],
 prerequisites:['binary place value','binary addition','borrowing in base ten'],
 teaching:['Binary subtraction uses 0−0=0, 1−0=1 and 1−1=0. When 0−1 occurs, borrow 1 from the next binary place; that borrowed 1 is worth 10₂, so 10₂−1₂=1₂.','If the next place is also zero, borrowing may pass across several places. Record each regrouping so the place-value change is visible.','Check by converting both numerals to base ten or by adding the difference back to the subtrahend.'],
 workedExamples:['110₂−011₂=011₂ because 6−3=3.','1000₂−0011₂=0101₂ because 8−3=5.'],
 misconceptions:['treating borrowed 1 as decimal ten','dropping leading place-value positions too early','subtracting the smaller digit from the larger regardless of order'],
 guidedPractice:['Subtract 101₂−011₂ and 1000₂−0110₂; check each by addition.'],
 independentPractice:['Ten subtraction problems with increasing borrowing complexity, plus three missing-number checks.'],
 mastery:{criterion:'At least 9 of 10 correct with borrowing shown and one independent verification method used.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-basic-operations-basic-operations-3',classLevel:'JSS3',subject:'Mathematics',topic:'Multiplication of numbers in base 2 numerals',source:{authority:'NERDC',url:sourceUrl,page:30},
 objectives:['Multiply two 2-digit binary numbers accurately'],
 prerequisites:['binary place value','binary addition','ordinary long multiplication'],
 teaching:['Binary multiplication has only four digit facts: 0×0=0, 0×1=0, 1×0=0 and 1×1=1. The place-value shifts in long multiplication are the important part.','Multiply by each digit of the multiplier from right to left. A row produced by a 1 copies the multiplicand; a row produced by a 0 is zero. Shift each new row one binary place to the left.','Add the partial products using binary addition and check in base ten when learning the method.'],
 workedExamples:['11₂×10₂=110₂ because 3×2=6.','11₂×11₂: partial products 11₂ and 110₂ sum to 1001₂, and 3×3=9.'],
 misconceptions:['forgetting the place-value shift','writing decimal multiplication facts into binary columns','using a digit 2 in a partial product'],
 guidedPractice:['Multiply 10₂×11₂ and 11₂×11₂, showing partial products.'],
 independentPractice:['Eight 2-digit-by-2-digit binary products and two contextual repeated-grouping problems.'],
 mastery:{criterion:'At least 8 of 10 correct with properly shifted partial products and valid binary addition.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-basic-operations-basic-operations-4',classLevel:'JSS3',subject:'Mathematics',topic:'Division of numbers in base 2 numerals',source:{authority:'NERDC',url:sourceUrl,page:30},
 objectives:['Divide two- to three-digit binary numbers by simple binary divisors'],
 prerequisites:['binary subtraction','binary multiplication','long division'],
 teaching:['Binary long division follows the same cycle as decimal long division: compare, place a quotient digit, multiply, subtract, and bring down. Quotient digits are only 0 or 1.','At each step ask whether the divisor fits into the current binary part. If yes, write 1; if no, write 0 and bring down the next digit.','A remainder must be smaller than the divisor. Verify by divisor×quotient+remainder=dividend.'],
 workedExamples:['110₂÷10₂=11₂ because 6÷2=3.','111₂÷11₂=10₂ remainder 1₂ because 7=3×2+1.'],
 misconceptions:['omitting a zero in the quotient when the divisor does not fit','using decimal division facts without binary place value','accepting a remainder equal to or larger than the divisor'],
 guidedPractice:['Divide 100₂ by 10₂ and 101₂ by 10₂; verify each.'],
 independentPractice:['Eight exact and remainder binary divisions; verify three using multiplication and addition.'],
 mastery:{criterion:'At least 8 of 10 division problems correct, including valid quotient-place zeros and remainder checks.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-algebraic-processes-algebraic-operations-1',classLevel:'JSS3',subject:'Mathematics',topic:'Factorization',source:{authority:'NERDC',url:sourceUrl,page:31},
 objectives:['Factorize simple algebraic expressions','Factorize quadratic-type expressions using suitable methods including the curriculum equation-box approach','Translate word problems into algebraic expressions and factorize where appropriate'],
 prerequisites:['expansion of brackets','common factors','algebraic terms and coefficients','integer multiplication'],
 teaching:['Factorization reverses expansion. First look for a greatest common factor because removing it simplifies every later step. For ax+ay, the common factor is a, giving a(x+y).','Grouping is useful when four terms share factors in pairs. Rearrange only when mathematically valid, factor each pair, then factor the common bracket.','Recognise standard identities: a²−b²=(a−b)(a+b) and a²−2ab+b²=(a−b)². Expand the answer to verify.','For a quadratic ax²+bx+c, first identify a, b and c. To split the middle term, write bx as mx+nx. Because mx+nx must still equal bx, m+n=b. For grouping to reproduce the original first and constant terms, mn=ac. Therefore find two numbers whose sum is b and whose product is ac; compare candidate factor pairs explicitly, split the middle term only after both conditions are satisfied, factor by grouping, and verify by expansion. When a=1 this reduces to product c because ac=c.','In word problems, define quantities, form the expression, then factorize only if factorization serves the question; algebra is a model, not a ritual.'],
 workedExamples:['6x+9=3(2x+3).','3m+pq+3p+mq=(m+p)(3+q) after grouping 3(m+p)+q(m+p).','x²−25=(x−5)(x+5).','2x²+7x+3: a=2,b=7,c=3, so sum=7 and product=ac=6. Compare 1 and 6 (sum 7, product 6) with 2 and 3 (sum 5, product 6). Use 1 and 6, split 7x as x+6x, then factor 2x²+x+6x+3=x(2x+1)+3(2x+1)=(2x+1)(x+3); expand to verify.'],
 misconceptions:['dividing only some terms by the common factor','confusing factorization with collecting like terms','using (a−b)² for a²−b²','choosing factor pairs with the correct product but wrong sum'],
 guidedPractice:['Factorize 8x+12, 2a+2b+ac+bc, y²−49 and x²+9x+20; expand each answer to check.'],
 independentPractice:['Fifteen mixed factorization items, including common factor, grouping, difference of squares, perfect-square trinomials, simple quadratics and two word-model tasks.'],
 mastery:{criterion:'At least 80% across all required factorization patterns and successful expansion checks on selected answers.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-algebraic-processes-algebraic-operations-2',classLevel:'JSS3',subject:'Mathematics',topic:'Simple equations involving fractions',source:{authority:'NERDC',url:sourceUrl,page:31},
 objectives:['Solve simple equations involving fractions','Translate word problems into simple fractional equations and solve them'],
 prerequisites:['equivalent fractions','LCM of denominators','inverse operations','JSS2 simple linear equations'],
 teaching:['A fractional equation contains one or more algebraic fractions. The safest first move is usually to multiply every term by the LCM of all denominators, which clears the fractions without changing equality.','After clearing denominators, solve the resulting linear equation using balanced inverse operations. Whatever is done to one side must be done to the other.','If a denominator contains a variable, state any value that would make it zero before solving. At this level many examples use numerical denominators, but the zero-denominator rule remains fundamental.','For word problems, define the unknown, translate relationships carefully, solve, then interpret the solution in the original context and check it.'],
 workedExamples:['x/3+2=7 → multiply by 3: x+6=21 → x=15.','x/4+x/6=5 → LCM 12: 3x+2x=60 → x=12.','“One third of a number plus 5 is 13” gives x/3+5=13, so x=24.'],
 misconceptions:['multiplying only the fractional term by the LCM','cross-multiplying when the equation is not a single fraction equals a single fraction','losing a negative sign while clearing denominators','stopping after finding x without checking the context'],
 guidedPractice:['Solve x/5+3=9, x/3−x/6=4 and a word problem involving one quarter of a number.'],
 independentPractice:['Twelve fractional equations with different denominators and four word problems; verify at least four by substitution.'],
 mastery:{criterion:'At least 80% correct with denominators cleared legitimately, balanced working shown and correct interpretation of word problems.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-algebraic-processes-algebraic-operations-3',classLevel:'JSS3',subject:'Mathematics',topic:'Simultaneous linear equations',source:{authority:'NERDC',url:sourceUrl,page:32},
 objectives:['Compile tables of values for two linear functions','Solve simultaneous linear equations in two variables graphically','Solve simultaneous equations by elimination','Apply elimination to real-life problems','Solve simultaneous equations by substitution','Apply substitution to real-life problems'],
 prerequisites:['linear equations','Cartesian graphs and tables of values','substitution into expressions','signed-number arithmetic'],
 teaching:['Two simultaneous linear equations describe two conditions that must hold at the same time. A solution is an ordered pair (x,y) satisfying both equations.','Graphically, create a table for each line, plot both on the same axes and read their intersection. Graphical answers may be approximate because of drawing scale.','Elimination combines equations so one variable cancels. If coefficients do not already match, multiply one or both equations by suitable constants first.','Substitution rearranges one equation for one variable and replaces that variable in the other equation. It is efficient when a variable already has coefficient 1 or is easily isolated.','For real-life problems, define both unknowns with units, form two independent equations, solve, and check that the answer makes sense in both original statements.'],
 workedExamples:['x+y=7 and x−y=1. Adding gives 2x=8, x=4, then y=3.','2x+y=11 and y=x+2. Substitute: 2x+x+2=11 → x=3, y=5.','Tickets cost ₦500 for adults and ₦300 for students. 20 tickets total ₦7,600: a+s=20, 500a+300s=7600 → a=8, s=12.'],
 misconceptions:['finding a point on only one line and calling it the solution','adding equations without arranging like variables','changing one equation but not every term when scaling','forgetting to substitute back for the second variable','using two equations that express the same information in a word problem'],
 guidedPractice:['Solve x+y=9, x−y=3 by graph and elimination; solve y=2x+1 with x+y=10 by substitution.'],
 independentPractice:['Nine systems: three graphical, three elimination and three substitution, plus three real-life modelling problems. Compare methods on one system.'],
 mastery:{criterion:'At least 80% overall and at least two correct solutions by each method; every solution must satisfy both original equations.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-mensuration-and-geometry-shapes-1',classLevel:'JSS3',subject:'Mathematics',topic:'Similar Shapes',source:{authority:'NERDC',url:sourceUrl,page:33},
 objectives:['Identify similar triangles, rectangles, squares, cubes and cuboids','Recognize similar shapes in the environment','Enlarge figures using scale factors','Calculate corresponding lengths, areas and volumes of similar figures','Solve quantitative-reasoning problems involving similarity'],
 prerequisites:['ratio and proportion','scale drawing','area and volume','properties of common shapes'],
 teaching:['Similar figures have the same shape: corresponding angles are equal and corresponding lengths are in a constant ratio called the scale factor. Equal-looking alone is not enough; correspondence must be established.','If the linear scale factor from shape A to B is k, corresponding lengths multiply by k, areas by k² and volumes by k³. These different powers are essential.','An enlargement with k>1 increases size; 0<k<1 gives a reduction. A scale factor acts from a specified original to an image, so direction matters.','Use labelled corresponding sides before writing a proportion. For 3-D solids, match like dimensions before applying k³ to volumes.'],
 workedExamples:['Triangles with corresponding sides 3,4,5 and 6,8,10 are similar with scale factor 2.','If similar rectangles have linear scale factor 3 and the smaller area is 12 cm², larger area=12×3²=108 cm².','If similar cubes have side ratio 2:5, their volume ratio is 2³:5³=8:125.'],
 misconceptions:['using k for area instead of k²','using k² for volume instead of k³','matching non-corresponding sides','assuming all rectangles or all triangles are similar'],
 guidedPractice:['Find missing sides in two similar triangles; enlarge a simple coordinate shape by scale factor 2; calculate an area and volume under a stated scale factor.'],
 independentPractice:['Twelve similarity problems mixing lengths, scale factors, areas, volumes, diagrams and environmental applications.'],
 mastery:{criterion:'At least 80% with correct correspondence and explicit use of k, k² and k³ where appropriate.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-mensuration-and-geometry-shapes-2',classLevel:'JSS3',subject:'Mathematics',topic:'Trigonometry',source:{authority:'NERDC',url:sourceUrl,page:33},
 objectives:['Identify sine, cosine and tangent of an acute angle in a right-angled triangle','Use trigonometric ratios to find unknown distances and lengths','Apply trigonometric ratios to practical and word problems'],
 prerequisites:['right-angled triangles','Pythagoras theorem','ratio','angles and calculator use'],
 teaching:['For an acute angle θ in a right-angled triangle, name sides relative to θ: opposite is across from θ, adjacent touches θ but is not the hypotenuse, and hypotenuse is opposite the right angle.','The three ratios are sinθ=opposite/hypotenuse, cosθ=adjacent/hypotenuse and tanθ=opposite/adjacent. Choose the ratio containing the known and required sides.','Draw and label a right triangle from the situation before calculating. Distances, heights, ladders, shadows and angles of elevation are models only after the geometry has been identified.','Keep units consistent and check whether the answer is physically plausible. For calculator work, use degree mode for degree angles.'],
 workedExamples:['In a right triangle with opposite=6 and hypotenuse=10, sinθ=0.6.','A ladder 5 m long makes 60° with the ground. Height reached=5sin60°≈4.33 m.','From a point 20 m from a vertical pole, angle of elevation to the top is 35°. Height≈20tan35°≈14.0 m, ignoring eye height.'],
 misconceptions:['naming opposite/adjacent without reference to the chosen angle','using sine/cosine/tangent interchangeably','using radian mode accidentally','forgetting that the hypotenuse is always opposite 90°'],
 guidedPractice:['For three labelled right triangles identify O/A/H relative to a marked angle; solve one unknown-side problem with each trig ratio.'],
 independentPractice:['Twelve problems involving trig ratios, heights/distances and angles of elevation, with diagrams required for all word problems.'],
 mastery:{criterion:'At least 80% with correct side identification, ratio selection, degree-mode use and units.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-mensuration-and-geometry-shapes-3',classLevel:'JSS3',subject:'Mathematics',topic:'Area of plane figures',source:{authority:'NERDC',url:sourceUrl,page:34},
 objectives:['Find areas of triangles','Find areas of parallelograms','Find areas of trapezia','Find areas of circles and sectors','Solve word problems involving area','Solve quantitative-reasoning problems involving areas'],
 prerequisites:['length measurement','perimeter versus area','fractions and decimals','circle vocabulary and π'],
 teaching:['Area measures surface in square units. The triangle formula A=1/2 bh can be derived as half a matching parallelogram; the perpendicular height must correspond to the chosen base.','A parallelogram has area bh because it can be rearranged into a rectangle with the same base and perpendicular height. A trapezium has area 1/2(a+b)h where a and b are the parallel sides.','A circle has area πr². A sector is a fraction of a circle, so sector area=(θ/360°)πr² for central angle θ.','Composite area problems should be decomposed into familiar shapes. Mark dimensions and units, compute each component, then add or subtract as the diagram requires.','Deriving and explaining formulas helps learners distinguish height, slant length, radius, diameter and parallel sides rather than simply substituting numbers.'],
 workedExamples:['Triangle b=12 cm,h=7 cm: A=42 cm².','Trapezium parallel sides 8 cm and 14 cm, height 5 cm: A=1/2(22)(5)=55 cm².','Circle r=7 cm: A=49π≈154 cm² using 22/7 where appropriate.','90° sector of radius 8 cm: A=90/360×π×64=16π≈50.3 cm².'],
 misconceptions:['using a sloping side as perpendicular height','forgetting to square the radius','using diameter in place of radius','using θ/180 instead of θ/360 for sector area','reporting area in linear units'],
 guidedPractice:['Derive triangle area from a rectangle sketch; calculate one triangle, parallelogram, trapezium, circle and sector.'],
 independentPractice:['Fifteen area problems including composite shapes and word contexts; require diagrams and square-unit answers.'],
 mastery:{criterion:'At least 80% across all listed figures, correct identification of perpendicular heights/radii and correct square units.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-mensuration-and-geometry-shapes-4',classLevel:'JSS3',subject:'Mathematics',topic:'Construction',source:{authority:'NERDC',url:sourceUrl,page:35},
 objectives:['Construct a 45° angle','Construct a 30° angle','Copy a given angle using ruler and compasses','Construct simple plane shapes accurately'],
 prerequisites:['basic ruler-and-compass construction','60° and 90° constructions','angle bisectors','triangle construction'],
 teaching:['Geometric construction uses an unmarked straightedge and compasses to create exact relationships. Keep arcs visible because they are evidence of the construction logic.','Construct 45° by first constructing a 90° angle and bisecting it. Construct 30° by constructing 60° and bisecting it.','To copy an angle, draw an arc across both arms of the original, reproduce the same arc radius at the new vertex, transfer the chord distance between the two intersections, then draw the second arm.','Simple plane shapes can be built from known sides, perpendiculars, parallel relationships, equal radii and constructed angles. Always verify dimensions after construction.'],
 workedExamples:['At point A on a line, construct a perpendicular to obtain 90°, then bisect to obtain 45°.','Construct an equilateral-triangle 60° at a point, then bisect to obtain 30°.','Copy a 73° given angle without setting a protractor by transferring its arc and chord.'],
 misconceptions:['measuring 45° or 30° directly with a protractor when a construction is required','changing compass width during a transfer step','erasing arcs before verification','assuming a sketch is a construction without geometric evidence'],
 guidedPractice:['Construct 45° and 30° from a common baseline; copy a supplied angle and verify with a protractor only after construction.'],
 independentPractice:['Complete six constructions: two target angles, two copied angles and two simple plane shapes with labelled dimensions and visible arcs.'],
 mastery:{criterion:'All required constructions are valid, within normal drawing tolerance, labelled and supported by visible compass/straightedge evidence.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-everyday-statistics-data-collection-and-presentation-1',classLevel:'JSS3',subject:'Mathematics',topic:'Measure of central tendency',source:{authority:'NERDC',url:sourceUrl,page:36},
 objectives:['Review mean, median and mode','Calculate the median of a data set','Find the mode of a data set','Calculate the mean of a data set','Find the range of a data set','Apply measures of central tendency and range to analyse information'],
 prerequisites:['JSS1/JSS2 data collection and tables','addition and division','ordering numbers'],
 teaching:['Mean, median and mode describe different aspects of a data set. Mean uses every value, median is the middle after ordering, and mode is the most frequent value. None is automatically “best” for every situation.','For an odd number of ordered values, the median is the middle value. For an even number, it is the mean of the two middle values. Data must be ordered first.','The mode may be one value, more than one value, or absent if no value repeats more than others. Range=max−min describes spread, not centre.','Outliers can pull the mean strongly while leaving the median relatively stable. Interpretation should therefore compare the measures and connect them to the context rather than merely calculate them.'],
 workedExamples:['Data 2,4,4,5,10: mean=5, median=4, mode=4, range=8.','Data 3,5,7,9: median=(5+7)/2=6.','Salaries 40,42,43,45,200 (thousands) have mean 74 but median 43; the median better represents a typical worker because of the outlier.'],
 misconceptions:['finding median before ordering','dividing mean by the wrong number of observations','calling the largest value the mode','confusing range with a central measure','assuming there must be exactly one mode'],
 guidedPractice:['For two small data sets calculate mean, median, mode and range, then decide which measure best represents a “typical” value.'],
 independentPractice:['Ten data sets plus four interpretation questions involving outliers, multiple modes and comparison of groups.'],
 mastery:{criterion:'At least 85% computational accuracy plus correct interpretation of when mean/median/mode is informative.',status:'DEEP_WHEN_PASSED'},boardReady:true
},
{
 topicId:'nerdc-jss3-math-everyday-statistics-data-collection-and-presentation-2',classLevel:'JSS3',subject:'Mathematics',topic:'Data presentation',source:{authority:'NERDC',url:sourceUrl,page:36},
 objectives:['Represent information accurately on pie charts','Interpret information presented on pie charts'],
 prerequisites:['frequency tables','fractions, percentages and ratios','angles and 360°','protractor use'],
 teaching:['A pie chart represents a whole as 360°. Convert each category to a sector angle using frequency/total×360°. The angles must total 360° apart from small rounding effects.','When percentages are given, sector angle=percentage/100×360°. When a sector angle and total are known, category frequency=angle/360×total.','Construction quality matters: label categories, use a sensible key where needed, draw angles from the centre and avoid visual exaggeration.','Interpretation should compare proportions, recover counts where possible and state only conclusions supported by the chart. A pie chart is poor for showing change over time, so choose presentation methods with purpose.'],
 workedExamples:['In a class of 40, 12 choose football: angle=12/40×360°=108°.','A 72° sector represents 20% of the whole because 72/360=0.2. In a survey of 250 people that equals 50 people.','Sector angles 90°,126°,54° and 90° sum to 360°, corresponding to 25%,35%,15%,25%.'],
 misconceptions:['using frequency as the angle','forgetting total frequency in the denominator','drawing sectors from the circumference instead of the centre','claiming the largest sector proves a cause','accepting angles that do not total 360°'],
 guidedPractice:['Convert a five-category frequency table to angles, check the sum, sketch the pie chart and answer five interpretation questions.'],
 independentPractice:['Construct two complete pie charts from raw/frequency data and solve ten reverse-reading questions involving angle, percentage and frequency.'],
 mastery:{criterion:'At least 85% accuracy in angle/frequency conversion, internally consistent 360° charts and evidence-based interpretation.',status:'DEEP_WHEN_PASSED'},boardReady:true
}
];

export function getJss3MathDeepLesson(topicId:string){return jss3MathematicsDeepLessons.find(x=>x.topicId===topicId)}
