import type { TutorPlan, TutorUnit } from './tutorCurriculum';

export type Jss3EnglishQuestion = {
  id: string; prompt: string; options: string[]; correctAnswer: string; explanation: string;
};
export type Jss3EnglishLesson = {
  topic: string; strand: 'Reading'|'Writing'|'Listening and Speaking'|'Grammatical Accuracy'|'Literature';
  authority: string; objectives: string[]; plan: TutorPlan; questions: Jss3EnglishQuestion[];
  performanceTasks?: string[];
};
const U=(title:string,body:string):TutorUnit=>({title,body});
const Q=(id:string,prompt:string,options:string[],correctAnswer:string,explanation:string):Jss3EnglishQuestion=>({id,prompt,options,correctAnswer,explanation});

export const jss3CriticalEvaluation: Jss3EnglishLesson = {
 topic:'Reading for Critical Evaluation', strand:'Reading',
 authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:[
  'Read critically and explain what critical reading requires.',
  'Distinguish verifiable facts from opinions and mixed claims.',
  'Make deductions that are supported by information presented.',
  'Recognise words and statements that indicate bias or balance.',
  'Explain the meaning and purpose of road danger signs and interpret their warnings.',
  'Apply critical evaluation to passages on road safety, drug use, consumer rights and other relevant issues.'
 ],
 plan:{topic:'Reading for Critical Evaluation',objective:'Understand, question and evaluate what a writer says; separate fact from opinion; detect bias or balance; and make evidence-based deductions.',units:[
 U('Start with the meaning','Critical reading means understanding a text and then examining its claims instead of accepting every sentence automatically. Ask: What is the writer saying? What evidence supports it? Is it a fact, an opinion or a mixture? Is the language fair? What conclusion can I safely draw? Example: “Our school introduced a reading hour in January, and it is the best programme ever.” The date of introduction can be checked; “best programme ever” is a judgement. A critical reader separates the two claims.'),
 U('Why critical reading matters','Critical reading protects you from exaggeration, weak reasoning and one-sided persuasion. If an advert says, “Five thousand students bought this drink, so it certainly makes students intelligent,” the sales figure—even if true—does not prove the intelligence claim. Popularity is not proof of the advertised effect. Critical readers ask whether the evidence actually supports the conclusion.'),
 U('Fact: what it really means','A fact is a claim whose truth or falsity can be checked using evidence. “The meeting began at 9:00 a.m.” is factual because records or witnesses can settle it. A factual claim can still be wrong: “Nigeria became independent in 1970” is false, but it is still a factual claim because objective evidence can test it. Do not confuse “fact” with “a statement I agree with.”'),
 U('Opinion and judgement','An opinion expresses belief, preference, evaluation or judgement: “English is the easiest subject.” Words such as best, worst, beautiful, boring, excellent, probably and I believe often signal judgement, but context matters. “The doctor said the patient should rest” reports a checkable event even though it contains “should”. Always judge the whole claim.'),
 U('Mixed statements','One sentence can contain fact and opinion. “The library contains 5,000 books and is the most beautiful building in town.” The number of books can be counted; beauty is subjective. In examinations, split a long sentence into its individual claims before classifying it.'),
 U('Evidence and support','Evidence is information offered to support a claim. “Attendance improved after free buses were introduced” is a claim. “Records show attendance rose from 78% to 91%” supplies evidence of improvement. But the figures alone do not prove the buses were the only cause. Other changes may have occurred. Never stretch evidence beyond what it establishes.'),
 U('Deduction: conclusion from clues','A deduction is a conclusion logically supported by information given. “Tunde entered with a wet umbrella; water dripped from his shoes; other pupils wore raincoats.” A reasonable deduction is that rain was falling or had recently fallen. “Tunde’s mother bought the umbrella yesterday” is a guess because the passage gives no supporting clue. Use the rule: evidence + reasoning = deduction; evidence + imagination = guess.'),
 U('Explicit and implied meaning','Explicit information is stated directly: “Ada arrived at 8:30.” Implied information must be inferred: “Ada entered while the teacher was explaining the second exercise.” It is reasonable to infer that teaching had already started. A good inference stays close to the clues and does not invent details.'),
 U('Bias','Bias is an unfair or one-sided presentation. Compare: “Musa presented three proposals, while careless Tobi wasted everyone’s time with another ridiculous speech.” The labels “careless”, “wasted” and “ridiculous” reveal hostility toward Tobi. Bias can appear through loaded words, selective evidence, unfair labels or presenting only one side. A biased passage can still contain facts; evaluate each claim separately.'),
 U('Balance','A balanced presentation represents relevant viewpoints or evidence fairly. “Some parents support smartphones because learners can access dictionaries quickly; others worry that unrestricted use distracts learners.” This does not force both sides to have exactly the same number of words; it avoids unfairly misrepresenting a relevant side.'),
 U('Loaded language and absolute claims','Words can push emotions before evidence is considered. “The council imposed another ridiculous rule on helpless motorists” is more loaded than “The council introduced a traffic rule.” Also question absolute words such as all, always, never, everyone, completely, certainly and only. “Every teenager with a smartphone performs poorly” requires far stronger evidence than “Excessive use can reduce study time for some learners.”'),
 U('Purpose and viewpoint','Ask why the text exists. A writer may inform, explain, warn, instruct, persuade or entertain. “Reduce speed when approaching the school crossing” warns/instructs. “Our product is unquestionably the smartest choice” persuades. Purpose does not automatically make a text false; it tells you what kinds of claims and language deserve close examination.'),
 U('Road danger signs','NERDC places road danger signs inside this topic because signs require interpretation and sensible deduction. A warning sign tells a road user that a hazard or condition lies ahead: a bend, junction, pedestrian/school crossing, road works, narrowing road, animals or another danger. If a sign warns of a sharp bend, you may infer that the driver should reduce speed and maintain control. You may NOT infer that an accident has definitely happened there.'),
 U('Worked passage: road safety','Residents complained about fast vehicles near a school. The authority installed warning signs and repainted a pedestrian crossing. A residents’ group then called the road “completely safe”, while school officials continued asking drivers to slow down. Facts: signs were installed and the crossing repainted. Opinion/overclaim: “completely safe”. Reasonable deduction: measures were taken to improve safety. Unsupported deduction: “No accident can ever occur there again.”'),
 U('Worked passage: drug use','A health centre reported treating 38 teenagers for problems linked to misuse of medicines and began school visits. A worker called education “one of the most important” protections; students asked that talks also explain how to seek help privately. The treatment figure is a checkable report; “most important” is evaluation. We may infer the centre considers the problem serious enough for outreach. We cannot infer that exactly 38 teenagers in the whole community misused medicine.'),
 U('Worked passage: consumer rights','A lamp is advertised to last twelve hours. Chika charges her lamp according to instructions and tests it three times; it lasts four to five hours each time. She may conclude that her tested lamp did not meet the advertised duration in those tests. She cannot conclude that every lamp produced by the company is defective. One tested unit does not establish a universal claim.'),
 U('Worked passage: technology at school','A school introduces twenty tablets. Teachers report easier diagram display, while two teachers report delays from charging and poor connectivity. A student calls tablets “the greatest improvement ever”. The quantity and reported incidents can be checked; “greatest” is opinion. The presence of advantages and disadvantages indicates balance. If the school keeps tablets but also keeps printed books, infer that it sees value in both—not that tablets have been proved to improve examination scores.'),
 U('A reliable critical-reading routine','1 Understand the literal meaning. 2 Identify the main issue and important claims. 3 Separate facts, opinions and mixed claims. 4 Ask what evidence supports each important claim. 5 Notice loaded words and absolute language. 6 Check for bias or balance. 7 Infer only what the clues support. 8 Test the limit of each conclusion: what can I NOT safely say? This last step prevents over-inference.'),
 U('Common traps','Trap 1: “Opinion means false.” No—an opinion may be sensible but remains a judgement. Trap 2: “Statistics prove the conclusion.” Numbers can be irrelevant or incomplete. Trap 3: “After means because of.” If scores rose after a revision class, the class may have helped, but timing alone does not prove it caused every improvement. Trap 4: “Bias makes every sentence false.” No—check individual claims. Trap 5: “Any possible story is a deduction.” Only evidence-supported conclusions qualify.'),
 U('Guided practice','A council surveys 120 Basic 9 learners; 84 say they visited the library last month. The president says, “This proves our library is the most useful facility in school.” The survey figures are factual claims. “Most useful” is an opinion. The evidence does not compare the library with laboratories, classrooms or sports facilities, so the conclusion is stronger than the evidence.'),
 U('BECE-style reasoning practice','Passage: After a pedestrian bridge opened, officials observed more people crossing above the road. A columnist wrote, “The bridge has solved every traffic problem here forever.” Traders still complained about illegal parking and congestion. Identify: (a) observed fact—more pedestrians used the bridge; (b) loaded/absolute claim—“every…forever”; (c) counter-evidence—parking and congestion remain; (d) safe deduction—the bridge addressed pedestrian crossing risk but the passage does not establish that all traffic problems ended.'),
 U('Mastery checkpoint','You are ready when you can explain critical reading without memorising a definition; classify facts/opinions in mixed sentences; point to exact words showing bias; explain why a passage is balanced; distinguish evidence from conclusion; make an inference and cite the clues supporting it; reject an over-inference; and interpret a road warning without inventing information.')
 ]},
 questions:[
 Q('j3e-crit-01','Critical reading mainly requires a reader to…',['memorise every sentence','examine meaning, evidence and conclusions','reject every opinion','read aloud quickly'],'examine meaning, evidence and conclusions','Critical reading combines understanding with evaluation.'),
 Q('j3e-crit-02','Which is an opinion?',['Nigeria is in West Africa','A week has seven days','English is the easiest subject','The meeting began at noon'],'English is the easiest subject','“Easiest” depends on judgement.'),
 Q('j3e-crit-03','A deduction is…',['a copied sentence','a conclusion supported by clues','an unsupported guess','the title of a text'],'a conclusion supported by clues','A deduction must follow logically from evidence.'),
 Q('j3e-crit-04','Which claim is factual in form?',['The hall is wonderful','The hall has 300 seats','The hall is the finest','The hall looks boring'],'The hall has 300 seats','The number of seats can be checked.'),
 Q('j3e-crit-05','“Careless Tobi gave another ridiculous speech.” The wording mainly shows…',['balance','bias','a road warning','a statistic'],'bias','Loaded negative labels reveal a one-sided attitude.'),
 Q('j3e-crit-06','A balanced passage…',['must agree with everybody','fairly represents relevant evidence or viewpoints','contains no opinions','has equal sentence counts for both sides'],'fairly represents relevant evidence or viewpoints','Balance concerns fair representation, not mechanical equality.'),
 Q('j3e-crit-07','Kunle arrives with a dripping umbrella and wet shoes. Best deduction?',['It probably rained','He bought shoes today','Tomorrow will be sunny','His mother owns a shop'],'It probably rained','Wet rain gear supports that inference.'),
 Q('j3e-crit-08','Which turns an inference into a guess?',['using clues','using logical reasoning','adding unsupported details','checking the passage'],'adding unsupported details','Unsupported invention is guessing.'),
 Q('j3e-crit-09','A writer says 5,000 people bought a product, therefore it is the highest-quality product. What is missing?',['a longer sentence','evidence connecting sales to quality','a title','an exclamation mark'],'evidence connecting sales to quality','Popularity alone does not establish quality.'),
 Q('j3e-crit-10','Which word creates the strongest absolute claim?',['sometimes','often','perhaps','always'],'always','“Always” allows no exception and therefore needs strong evidence.'),
 Q('j3e-crit-11','A sign warning of a sharp bend justifies which conclusion?',['An accident has happened','Drivers should approach cautiously','The road ends there','No vehicle may continue'],'Drivers should approach cautiously','The sign warns of a road condition, not a confirmed accident.'),
 Q('j3e-crit-12','A clinic treated 20 malaria patients. Which conclusion is NOT justified?',['The clinic treated malaria','Twenty such patients were treated','Exactly twenty people in the town had malaria','The clinic had malaria cases'],'Exactly twenty people in the town had malaria','The clinic data cannot establish the whole-town total.'),
 Q('j3e-crit-13','“The library has 5,000 books and is the most beautiful building.” This contains…',['two opinions','two facts','a fact and an opinion','neither'],'a fact and an opinion','The count is checkable; beauty is judgement.'),
 Q('j3e-crit-14','Evidence is…',['information used to support a claim','any emotional word','a paragraph title','always an opinion'],'information used to support a claim','Evidence provides support that can be evaluated.'),
 Q('j3e-crit-15','If scores rise after a revision class, we can safely say…',['the class caused every improvement','scores rose after the class began','every attendee studied hard','no other factor mattered'],'scores rose after the class began','Sequence is supported; sole causation is not.'),
 Q('j3e-crit-16','Which question best tests a strong claim?',['How long is the paragraph?','What evidence supports it?','Is the font attractive?','Can I memorise it?'],'What evidence supports it?','Critical evaluation asks whether evidence supports the claim.'),
 Q('j3e-crit-17','An implied idea is…',['stated word-for-word','understood logically from clues','unrelated to the passage','always false'],'understood logically from clues','Implication is inferred rather than directly stated.'),
 Q('j3e-crit-18','A biased passage…',['cannot contain any facts','may contain facts but present the issue unfairly','must be completely ignored','is always fiction'],'may contain facts but present the issue unfairly','Bias affects presentation; individual factual claims still require checking.'),
 Q('j3e-crit-19','Which phrase should trigger special caution because it overstates certainty?',['may help some learners','according to the record','solves every problem forever','the report states'],'solves every problem forever','“Every” and “forever” make sweeping claims.'),
 Q('j3e-crit-20','The first duty of a critical reader is to…',['understand what the text says','attack the writer','reject statistics','find spelling errors'],'understand what the text says','Evaluation must begin with accurate comprehension.'),
 Q('j3e-crit-21','If a school keeps tablets but also keeps printed books, the safest inference is…',['tablets guarantee high scores','books are useless','the school sees continuing value in both','all parents oppose tablets'],'the school sees continuing value in both','The decision itself supports this limited conclusion.'),
 Q('j3e-crit-22','Which best signals persuasive purpose?',['Our product is unquestionably the smartest choice','The meeting started at nine','Water filled the tank','The register contains 40 names'],'Our product is unquestionably the smartest choice','Evaluative promotional language aims to persuade.'),
 Q('j3e-crit-23','“Opinion” means…',['a statement that must be false','a judgement or belief rather than an objectively settled claim','a spelling error','a road sign'],'a judgement or belief rather than an objectively settled claim','Opinions may be reasonable but are evaluative.'),
 Q('j3e-crit-24','Why should a reader check counter-evidence?',['to make the text longer','to test whether a conclusion is too strong or one-sided','to avoid understanding the writer','to turn facts into opinions'],'to test whether a conclusion is too strong or one-sided','Counter-evidence can expose overstatement or bias.'),
 Q('j3e-crit-25','The strongest critical reader…',['believes everything printed','disagrees with every writer','understands, checks evidence and draws supported conclusions','reads only statistics'],'understands, checks evidence and draws supported conclusions','Critical reading is reasoned evaluation, not automatic belief or disbelief.')
 ],
 performanceTasks:[
  'Read a short road-safety passage and mark each important claim F (factual), O (opinion) or M (mixed), explaining each choice.',
  'Underline loaded words in a persuasive paragraph and rewrite it in more balanced language.',
  'Given five clues from a passage, state one supported deduction and one tempting but unsupported conclusion, explaining the difference.',
  'Interpret three road danger signs and state only the safe conclusions each sign supports.'
 ]
};

export const jss3ReadingSpeed: Jss3EnglishLesson = {
 topic:'Reading for Speed',strand:'Reading',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Read rapidly while retaining meaning.','Use surveying, skimming and scanning appropriately.','Adjust reading rate to purpose and material.','Use rapid reading for reference and non-text materials.','Answer comprehension questions after speed reading.'],
 plan:{topic:'Reading for Speed',objective:'Choose and use the right rapid-reading technique without sacrificing comprehension.',units:[
 U('Speed is not rushing','Reading for speed means getting the required meaning efficiently. A learner who races through 600 words but cannot answer basic questions has not read effectively. Speed and comprehension work together. Your purpose determines how quickly and how deeply you read.'),
 U('Flexible reading rate','Do not read a dictionary entry, a story, an examination instruction and a difficult science explanation at one fixed speed. Slow down for dense reasoning, unfamiliar vocabulary and exact instructions; speed up when previewing familiar material or locating a known detail. Skilled readers change gears.'),
 U('Surveying','Surveying is a quick first look at the whole material before detailed reading. Examine the title, headings, subheadings, pictures, captions, opening/closing paragraphs, bold words, tables or layout. Example: before reading a chapter called “Road Safety”, surveying may reveal sections on pedestrians, signs, speed and emergency response. You now have a mental map.'),
 U('Skimming','Skimming is rapid reading to grasp the general idea or main points. Let your eyes move over headings, topic sentences and key words rather than stopping at every detail. If asked “What is this article mainly about?”, skim. Example: in four paragraphs about causes, effects and prevention of flooding, skimming should reveal the overall subject and major divisions.'),
 U('Scanning','Scanning is rapid searching for a specific item: a name, date, price, definition, score, telephone number or key word. If a timetable question asks when Mathematics begins, do not read every row as prose; scan for “Mathematics”, then read across to the time.'),
 U('Do not swap the techniques','A common textbook distinction is purpose: skim for general meaning; scan for a particular detail; survey to preview structure. If you need one date, skimming the entire passage wastes time. If you need the main argument, scanning for one number is insufficient.'),
 U('Eye movement and word groups','Slow readers often pronounce every word internally and repeatedly move backwards. Practise taking meaningful groups: “after the morning assembly / the Basic 9 learners / entered the laboratory.” Grouping helps the eyes process phrases, not isolated words. Never sacrifice meaning merely to avoid rereading; reread when the text truly requires it.'),
 U('Using context instead of stopping','In speed reading, an unfamiliar word does not always require an immediate dictionary stop. Read the surrounding sentence first. “The road was inundated after hours of rain; water entered nearby shops.” Even if “inundated” is unfamiliar, the context suggests flooding. Later, verify the word if precision matters.'),
 U('Speed with non-text materials','NERDC expects rapid reading to help with non-text materials. Timetables, charts, indexes, contents pages, notices and tables are not read like stories. Decide the target, identify labels/headings, then move directly to the relevant row, column or entry.'),
 U('Reference skill','Suppose a textbook index lists: Climate 44–49; Erosion 72–76; Flooding 77–81. To find causes of flooding, scan alphabetically for “Flooding”, note pages 77–81, then turn there. This is efficient referencing—not careless reading.'),
 U('Worked drill: survey','Material has title “Healthy Study Habits”, headings “Plan Your Time”, “Remove Distractions”, “Sleep Well”, and a final checklist. Before reading details you can predict that it explains habits that improve studying. That prediction came from surveying the structure.'),
 U('Worked drill: skim','Paragraphs discuss blocked drains, building on waterways, heavy rain and community clean-up. A good skim yields: “The passage explains causes of urban flooding and ways communities can reduce it.” You do not need every statistic to state the main idea.'),
 U('Worked drill: scan','Notice: Debate Finals — Friday 16 October; Venue: School Hall; Time: 1:30 p.m.; Teams: Blue vs Gold. Question: “Where will the debate hold?” Scan for the label Venue → School Hall. Reading every word several times is unnecessary.'),
 U('Timed comprehension strategy','Before a timed passage: read the question or task when appropriate; identify whether it asks main idea or detail; skim for structure; scan for names/numbers; read the relevant sentence carefully; verify the answer in context. Speed comes from purpose, not panic.'),
 U('Common mistakes','Mistake: “Skimming means reading the first sentence only.” No. It samples strategically across the text. Mistake: “Scanning means understanding nothing.” No. You read selectively around the target. Mistake: “Fast readers never slow down.” Skilled readers slow down when complexity demands it. Mistake: “Speed is words per minute only.” Comprehension is essential.'),
 U('Guided practice','You need (a) the price of a bus ticket in a long notice, (b) the overall argument of a newspaper article, (c) a first look at a new chapter. Choose: (a) scanning, (b) skimming, (c) surveying. Then read the exact target sentence normally to avoid taking a detail out of context.'),
 U('Mastery checkpoint','You have mastered this topic when you can explain surveying/skimming/scanning in your own words, choose the correct technique for a task, rapidly locate a detail in a table, state the main idea after skimming, preview a chapter through surveying, and still answer comprehension questions accurately.')
 ]},
 questions:[
 Q('j3e-speed-01','Reading for speed is successful when a learner…',['moves fastest even without meaning','reads efficiently and understands what the task requires','pronounces every word aloud','never rereads'],'reads efficiently and understands what the task requires','Comprehension remains essential.'),
 Q('j3e-speed-02','A quick first look at headings and layout is…',['surveying','dictation','proofreading','recitation'],'surveying','Surveying previews the structure.'),
 Q('j3e-speed-03','To get the general idea of a long article, use…',['scanning','skimming','spelling','copying'],'skimming','Skimming targets overall meaning/main points.'),
 Q('j3e-speed-04','To find one date in a notice, use…',['scanning','dramatisation','summary writing','slow oral reading'],'scanning','Scanning searches for a specific detail.'),
 Q('j3e-speed-05','Which is the best example of surveying?',['reading every word twice','checking title, headings and captions before reading','searching only for 1999','copying the conclusion'],'checking title, headings and captions before reading','Surveying maps the material.'),
 Q('j3e-speed-06','A skilled reader should…',['use one speed for everything','adjust speed to purpose and difficulty','always skip unfamiliar words','avoid comprehension questions'],'adjust speed to purpose and difficulty','Flexible rate is central to efficient reading.'),
 Q('j3e-speed-07','You need the Mathematics time in a timetable. Best technique?',['scan the subject column','read every row as a story','skim only the title','memorise all times first'],'scan the subject column','The target is a specific detail.'),
 Q('j3e-speed-08','Skimming differs from scanning mainly because skimming seeks…',['general meaning','one exact detail','correct spelling only','page numbers only'],'general meaning','Scanning targets specific information.'),
 Q('j3e-speed-09','Which material especially rewards scanning?',['a timetable','a poem whose imagery you must analyse','a complex proof','a drama performance'],'a timetable','Structured labels allow rapid location of a target.'),
 Q('j3e-speed-10','Why survey a chapter first?',['to avoid reading it','to build a mental map of its structure','to replace comprehension','to count letters'],'to build a mental map of its structure','Previewing makes later reading purposeful.'),
 Q('j3e-speed-11','Taking words in meaningful groups can…',['support fluent rapid reading','make meaning impossible','replace vocabulary knowledge','remove punctuation'],'support fluent rapid reading','Phrase grouping reduces word-by-word processing.'),
 Q('j3e-speed-12','When a passage becomes conceptually difficult, a skilled reader should…',['speed up blindly','slow down as needed','stop permanently','skip every example'],'slow down as needed','Reading rate should respond to difficulty.'),
 Q('j3e-speed-13','Which task needs skimming?',['Find the phone number','State what the article is mainly about','Locate page 81 in an index','Find the examination date'],'State what the article is mainly about','The task asks for overall meaning.'),
 Q('j3e-speed-14','Which task needs scanning?',['Explain the writer’s full argument','Find the venue in an announcement','Analyse a metaphor','Evaluate bias throughout a passage'],'Find the venue in an announcement','The venue is a specific target.'),
 Q('j3e-speed-15','A contents page is best treated as…',['non-text reference material','a narrative story','a poem','dialogue'],'non-text reference material','Its structure is designed for locating information.'),
 Q('j3e-speed-16','If you skim but cannot state the main idea, you should…',['claim success because you were fast','reread strategically for meaning','ignore the task','guess'],'reread strategically for meaning','Speed without required comprehension is not success.'),
 Q('j3e-speed-17','Which is NOT a sound speed-reading principle?',['read with a purpose','change rate when necessary','never slow down under any condition','use headings strategically'],'never slow down under any condition','Flexible reading is better than forced speed.'),
 Q('j3e-speed-18','Referencing skill helps a learner…',['locate needed information efficiently','avoid books','replace comprehension with guessing','read only fiction'],'locate needed information efficiently','Indexes and contents pages guide rapid retrieval.'),
 Q('j3e-speed-19','Survey → skim → focused reading is useful because it moves from…',['overview to main ideas to needed detail','detail to guessing','memorisation to copying','speech to spelling'],'overview to main ideas to needed detail','The sequence progressively narrows attention.'),
 Q('j3e-speed-20','NERDC mastery of reading for speed still requires…',['comprehension of selected material','speed alone','no questions afterward','oral memorisation only'],'comprehension of selected material','The evaluation guide explicitly includes comprehension.')
 ]},
 performanceTasks:['Survey a textbook chapter in 45 seconds and report its structure without reading every paragraph.','Skim a 400-word passage and state its main idea plus three major points.','Scan a timetable/notice for five specified details against a timer, then verify each in context.']
};

export const jss3ReadingSummary: Jss3EnglishLesson = {
 topic:'Reading for Summary',strand:'Reading',authority:'Official NERDC JSS1–JSS3 English Studies curriculum — JSS3 prior-cycle authority',
 objectives:['Identify topic sentences.','Identify key ideas across paragraphs.','Recognise words and expressions that redirect attention to main points.','Reduce material to accurate phrases/sentences without losing essential meaning.'],
 plan:{topic:'Reading for Summary',objective:'Find the central meaning of paragraphs and compress it accurately in your own words.',units:[
 U('What summary reading means','Reading for summary means reading to separate essential ideas from examples, repetition and decoration. You are not trying to remember every sentence. You are asking: What must remain if this paragraph is shortened without changing its central meaning?'),
 U('Topic and topic sentence','The topic is what a paragraph is about; the topic sentence states its controlling idea. Paragraph: “Regular exercise strengthens the heart. It can also improve stamina and help control body weight.” Topic: exercise. Topic sentence: “Regular exercise strengthens the heart” if that sentence controls the supporting details.'),
 U('Topic sentence can move','Do not assume the first sentence is always the topic sentence. A paragraph may give examples first and conclude: “For these reasons, keeping drainage channels clear is a shared community responsibility.” Here the final sentence may carry the main point.'),
 U('Main idea versus supporting detail','Main idea: the central claim. Supporting details explain, prove or illustrate it. “Public libraries support learning” is main. “They provide dictionaries, textbooks, newspapers and quiet reading spaces” supplies support. A summary keeps the main point and only essential support.'),
 U('Key ideas across paragraphs','A multi-paragraph passage may develop several main points. Label each paragraph in a few words before combining them. Example: P1 cause of flooding; P2 effects; P3 prevention. Your final summary should preserve all three if the task asks for the whole passage.'),
 U('Signpost expressions','Words can redirect attention: however signals contrast; therefore/so signals result; most importantly highlights priority; in conclusion signals synthesis; although introduces concession; for example introduces illustration. These signals help locate the writer’s important movement, but the word itself is not the main idea.'),
 U('Delete repetition','If a paragraph says the same idea three ways, do not copy all three. “The road was unsafe. It posed serious danger. Travelling there was risky.” These largely repeat one idea: the road was dangerous.'),
 U('Examples are not automatically main ideas','“Many fruits contain useful nutrients. Oranges supply vitamin C; bananas provide potassium; avocados contain healthy fats.” Unless the question demands examples, a concise summary may be: “Different fruits provide useful nutrients.”'),
 U('Use your own words carefully','Paraphrase without changing meaning. Original: “The heavy rainfall forced residents to leave low-lying homes.” Safe: “Residents evacuated low areas because of severe rain.” Do not introduce a new cause such as “because the dam broke” if the passage never says so.'),
 U('Keep tense and logic','A summary must preserve relationships. If the original says “Because the bridge was damaged, buses used another route,” do not write “Buses damaged the bridge.” Compression must not reverse cause and effect.'),
 U('Worked paragraph','“Motorists should check tyres regularly. Worn tyres reduce grip, especially on wet roads. Drivers should also maintain correct tyre pressure.” Topic: tyre safety. Main idea: regular tyre maintenance improves road safety. Key supports: tread condition and pressure. Summary: “Motorists should maintain tyre condition and pressure to improve road safety.”'),
 U('Worked multi-paragraph passage','P1 describes traffic officers using cameras to observe roads. P2 explains speed-monitoring devices. P3 explains communication devices used to report incidents. Paragraph labels: observation, speed monitoring, communication. A whole-passage summary should combine those functions instead of listing every brand or example.'),
 U('From paragraph to one sentence','Method: read once for meaning; underline repeated key nouns/verbs; identify the topic sentence or formulate the controlling idea; cross out examples/repetition; restate the essential idea in one accurate sentence; compare with original to ensure nothing vital was distorted.'),
 U('Common summary errors','Copying whole sentences without selection; including personal opinion; adding information not in the passage; writing examples while omitting the general point; changing cause/effect; using vague pronouns whose referent is lost; reducing so much that the central meaning disappears.'),
 U('Guided practice','“Trees cool neighbourhoods by providing shade. Their roots can reduce soil erosion. Trees also absorb carbon dioxide.” Main idea: trees provide environmental benefits. Details: shade, erosion reduction, carbon dioxide absorption. A suitable summary: “Trees benefit the environment by cooling areas, protecting soil and absorbing carbon dioxide.”'),
 U('Mastery checkpoint','You are ready when you can identify topic sentences in different positions, distinguish main ideas from examples, use signposts to follow argument, label each paragraph’s key idea, paraphrase without distortion, and produce a shorter statement that still contains the essential meaning.')
 ]},
 questions:[
 Q('j3e-rsum-01','The main purpose of reading for summary is to…',['copy every sentence','identify and compress essential ideas','memorise punctuation','find only difficult words'],'identify and compress essential ideas','A summary preserves essentials while reducing detail.'),
 Q('j3e-rsum-02','A topic sentence usually expresses…',['the controlling idea of a paragraph','every example','the page number','the writer’s name'],'the controlling idea of a paragraph','It guides the supporting details.'),
 Q('j3e-rsum-03','A topic sentence…',['must always be first','may occur in different positions','must be a question','cannot be implied'],'may occur in different positions','Writers may place it first, later or make it implicit.'),
 Q('j3e-rsum-04','Which is normally supporting detail?',['a specific example illustrating a general claim','the controlling idea itself','the title only','the central conclusion always'],'a specific example illustrating a general claim','Examples commonly support broader ideas.'),
 Q('j3e-rsum-05','“However” often signals…',['contrast','a list of names','a date','pronunciation'],'contrast','It redirects attention to an opposing or qualifying point.'),
 Q('j3e-rsum-06','“Therefore” often signals…',['result/conclusion','example only','location','quotation'],'result/conclusion','It marks a consequence or inference.'),
 Q('j3e-rsum-07','A good summary should NOT…',['preserve main ideas','use concise wording','add the summariser’s unsupported opinion','retain logical relationships'],'add the summariser’s unsupported opinion','A summary represents the source.'),
 Q('j3e-rsum-08','Three sentences all say a road is dangerous. A summary should…',['repeat all three','combine the repeated idea','omit danger completely','invent an accident'],'combine the repeated idea','Repetition can be compressed.'),
 Q('j3e-rsum-09','Paraphrasing means…',['restating meaning in different words','changing the facts','adding examples','copying exactly'],'restating meaning in different words','Meaning should remain faithful.'),
 Q('j3e-rsum-10','Which error changes logic?',['shortening an example','reversing cause and effect','removing repetition','combining similar points'],'reversing cause and effect','A summary must preserve relationships.'),
 Q('j3e-rsum-11','Before summarising a long passage, it helps to…',['label each paragraph’s key idea','count all letters','ignore paragraph divisions','read only the last line'],'label each paragraph’s key idea','Paragraph labels reveal the structure.'),
 Q('j3e-rsum-12','“For example” usually introduces…',['illustration/support','the only main idea','a conclusion always','a title'],'illustration/support','Examples develop a broader point.'),
 Q('j3e-rsum-13','A summary is too short if it…',['removes repetition','loses an essential idea','uses own words','combines examples'],'loses an essential idea','Compression must retain the core meaning.'),
 Q('j3e-rsum-14','Which belongs in a summary?',['essential cause stated in the passage','your personal complaint','an invented statistic','an unrelated story'],'essential cause stated in the passage','Essential source information should remain.'),
 Q('j3e-rsum-15','The topic of a paragraph is…',['what it is generally about','always its first word','its punctuation','only its examples'],'what it is generally about','The topic names the subject area.'),
 Q('j3e-rsum-16','The main idea is more specific than the topic because it…',['states what the writer says about the topic','is only one noun','must be a date','cannot be a sentence'],'states what the writer says about the topic','It expresses the controlling message.'),
 Q('j3e-rsum-17','A safe summary of several fruit examples is…',['different fruits provide useful nutrients','oranges are the only useful fruit','all fruit cures disease','fruit is boring'],'different fruits provide useful nutrients','It captures the general point without overclaiming.'),
 Q('j3e-rsum-18','After writing a summary, compare it with the passage mainly to…',['check fidelity and missing essentials','make it longer automatically','add opinions','copy phrases'],'check fidelity and missing essentials','Verification catches distortion and omission.'),
 Q('j3e-rsum-19','Which is a useful final-summary test?',['Does every word copy the original?','Is it shorter, accurate and complete in essentials?','Did I add my view?','Did I include every example?'],'Is it shorter, accurate and complete in essentials?','Those are core summary qualities.'),
 Q('j3e-rsum-20','NERDC expects learners to identify…',['topic sentences and key ideas','only spelling errors','only character names','only dates'],'topic sentences and key ideas','These are explicit performance objectives.')
 ]},
 performanceTasks:['Label the topic sentence, main idea and supporting details in five varied paragraphs.','Reduce a 250-word passage to 70–90 words without adding information.','Summarise three paragraphs first separately and then as one coherent whole.']
};

export const jss3EnglishLessons: Jss3EnglishLesson[]=[jss3CriticalEvaluation,jss3ReadingSpeed,jss3ReadingSummary];
