import type {TopicTeachingMap} from './deepTeachingArchitecture';

type TypeSpec=[string,string,string[]];
const m=(idea:string,types:TypeSpec[],checks:string[]=[]):TopicTeachingMap=>({
 standard:'Teach the language concept explicitly before expecting performance. Define unfamiliar terminology, model it in meaningful context, contrast correct and incorrect/non-example forms, explain why the choice works, then move from guided recognition to guided production and independent use.',
 governingIdea:idea,
 types:types.map(([name,description,examples])=>({name,description,examples})),
 minimumRepresentativeExamples:3,
 noJumpChecks:['define unfamiliar language terminology before relying on it','model the skill before asking the learner to produce it','use contrast or non-examples so the learner sees the boundary of the rule','require evidence or a reason rather than accepting a guess','teach form, meaning and use together where applicable','require independent production for productive language skills',...checks]
});

/** AVORA JSS3 English type-aware deep-teaching maps. Each entry maps the internal forms/cases the learner must meet; examples are AVORA-original prompts, not textbook copies. */
export const jss3EnglishTeachingMaps:Record<string,TopicTeachingMap>={
'Reading for critical evaluation':m('Critical evaluation first establishes meaning, then tests claims, evidence, assumptions, tone and reasoning before reaching a balanced evidence-based judgement.',[['Fact/opinion/assumption','Classify what kind of claim is being made.',['news paragraph','editorial','advert']],['Claim and evidence','Test relevance and sufficiency.',['single anecdote','named statistic','irrelevant example']],['Bias/tone/loaded language','Explain how wording shapes response.',['emotive adjective','one-sided selection','unsupported certainty']],['Comparative evaluation','Judge which of two texts is better supported and why.',['two editorials','two reports','claim vs counterclaim']]],['require evidence for every evaluative judgement']),
'Reading for speed':m('Mature reading speed is adaptive: the reader selects skimming, scanning, phrase reading or close reading according to purpose and checks comprehension.',[['Skimming','Get gist/structure rapidly.',['article','essay','chapter']],['Scanning','Locate exact target information.',['date','name','figure']],['Phrase reading','Process meaningful chunks rather than word-by-word fixation.',['noun phrase','clause','sentence']],['Adaptive speed','Slow down for dense inference and speed up for familiar material.',['argument','narrative','reference text']]],['never trade required comprehension for raw words-per-minute']),
'Reading for summary':m('Advanced summary selects only requested points, paraphrases accurately, combines related ideas and obeys constraints without commentary.',[['Point selection','Extract requested causes/effects/reasons.',['six causes','five benefits','three recommendations']],['Paraphrase','Preserve meaning with new wording/structure.',['complex sentence','technical phrase','two related claims']],['Compression','Combine repetition and remove illustration.',['example-heavy paragraph','repeated point','long explanation']],['Exam constraint','Meet sentence/word/point instructions exactly.',['specified points','one paragraph','limited words']]],['verify each point against source and task wording']),
'Revision: various types of composition writing – Narrative, Descriptive, Expository, Argumentative':m('Composition type is determined by communicative purpose; planning, organisation, register, evidence and revision must match that purpose.',[['Narrative','Develop coherent plot, conflict, viewpoint and resolution.',['unexpected visitor','difficult choice','journey']],['Descriptive','Create dominant impression through selective sensory/spatial detail.',['market','person','storm']],['Expository','Explain/classify/analyse accurately and logically.',['process','cause-effect','classification']],['Argumentative','Defend a claim with reasons/evidence and address counterargument.',['school policy','technology','community issue']]],['require planning, paragraph logic and revision for every type']),
'Revision: Letter writing: informal and formal':m('Letter writing integrates purpose, audience, register, organisation and convention; layout alone cannot earn mastery.',[['Informal','Personal but coherent communication.',['advice','invitation','experience']],['Formal request/application','Precise respectful official purpose.',['permission','application','inquiry']],['Formal complaint/proposal','State issue/evidence/remedy or recommendation.',['service complaint','school proposal','community request']],['Register transformation','Rewrite same message for different audiences.',['friend/principal','relative/company','peer/official']]],['check purpose and register before layout details']),
'Summary writing':m('Productive summary writing requires source-faithful selection, paraphrase, compression and grammatical sentence construction under explicit constraints.',[['Extraction','Identify only task-relevant points.',['reasons','effects','solutions']],['Paraphrase','Avoid lifting while preserving exact idea.',['sentence transformation','synonym + restructure','combine clauses']],['Compression','Remove repetition/examples.',['illustration','restatement','wordiness']],['Final editing','Check grammar, count and fidelity.',['six sentences','specified words','single paragraph']]],['do not reward copied chunks as paraphrase']),
'Speeches: phonemes':m('Phonemic accuracy depends on hearing/articulating meaningful sound contrasts in connected speech, including vowels, diphthongs and consonants.',[['Vowel contrasts','Distinguish pure vowels.',['ship/sheep','full/fool','bed/bird']],['Diphthongs','Produce vowel glides accurately.',['late/let','boy/buy','coat/cot']],['Consonant contrasts','Use voicing/place/manner cues.',['fan/van','thin/sin','rice/lice']],['Minimal pairs in context','Show sound contrast changes word meaning.',['pin/bin sentence','coat/goat phrase','sip/zip dialogue']]],['use phonetic description only to support audible/articulatory understanding']),
'Speeches: Intonation, stress and Rhythm':m('Prosody organises connected speech and signals focus, attitude and sentence meaning; performance must be linked to communicative effect.',[['Word stress','Place primary stress accurately.',['REcord/reCORD','PREsent/preSENT','PHOtograph/phoTOGraphy']],['Sentence/contrastive stress','Shift focus through prominence.',['I wanted BLUE','SHE called','three BOOKS']],['Rhythm','Group stressed/unstressed material naturally.',['speech line','dialogue','announcement']],['Intonation','Use contour for statement/question/attitude.',['falling statement','rising uncertainty','fall-rise reservation']]],['explain meaning change when stress/intonation changes']),
'Adverbials and Tenses':m('Accurate tense/aspect and adverbials jointly locate and shape events in time, place, manner, frequency, reason and degree.',[['Adverbial functions','Identify time/place/manner/frequency/reason/degree.',['yesterday','at home','because of rain']],['Tense/aspect contrast','Choose simple/continuous/perfect/perfect-continuous where required.',['worked/was working','has worked','has been working']],['Sequence of tenses','Maintain coherent time relationships across clauses.',['before/after','while/when','reported context']],['Error correction','Diagnose tense/adverbial mismatch.',['since + wrong form','yesterday + present perfect','misplaced adverb']]],['base tense choice on intended time/aspect meaning']),
'Adverbs, Conjunctions and Prepositions':m('These classes express modification and logical/spatial relationships; accurate use depends on function and intended relation, not memorised lists.',[['Adverbs','Classify/use manner, time, place, frequency, degree.',['carefully','often','outside']],['Coordinating/subordinating conjunctions','Join units with correct logical relation.',['and/but','because/although','if/when']],['Prepositions','Express place/time/movement/abstract relations.',['in/on/at','through/across','depend on']],['Ambiguous/error cases','Correct misplaced modifiers and wrong connectors/prepositions.',['only placement','although/but double marking','interested on/in']]],['identify grammatical function in context']),
'Active and Passive verbs':m('Voice controls grammatical focus while preserving tense and event roles; passive formation requires BE + past participle and purposeful agent handling.',[['Simple tense transformations','Preserve tense across active/passive.',['writes/is written','wrote/was written','will write/will be written']],['Continuous/perfect forms','Maintain auxiliary structure accurately.',['is writing/is being written','has written/has been written','was writing/was being written']],['Agent omission/inclusion','Choose by communicative relevance.',['unknown agent','obvious agent','important agent']],['Use/editing','Choose clearer voice for context and repair errors.',['report','instruction','news sentence']]],['identify subject, object, tense and participle before transforming']),
'Modal forms':m('Modals express meanings such as ability, permission, possibility, obligation, advice and deduction; interpretation depends on context and strength.',[['Ability/permission','Distinguish can/could/may uses.',['can swim','could swim','may leave']],['Obligation/advice','Compare must/have to/should.',['must submit','have to attend','should revise']],['Possibility/probability','Use may/might/could appropriately.',['may rain','might arrive','could be true']],['Deduction/conditional nuance','Interpret modal strength in context.',['must be home','can\'t be true','would help']]],['teach modal meaning and social force, not substitution tables']),
'Non-African folktales':m('Cross-cultural folktale study identifies universal narrative conventions while interpreting culture-specific values from evidence rather than stereotype.',[['Folktale conventions','Identify oral-pattern features, stock roles, repetition and motifs.',['trickster','quest','transformation']],['Plot/moral','Relate consequence to supported lesson.',['greed','kindness','wisdom']],['Cultural comparison','Compare values/motifs with African folktales carefully.',['hospitality','cleverness','community']],['Adaptation/performance','Retell while preserving central structure/theme.',['new setting','dramatic retelling','oral narration']]],['avoid unsupported claims about whole cultures']),
'Lessons from myths/legends':m('Myths and legends invite interpretation of cultural ideas, human choices and consequences; lessons must arise from textual events and genre features.',[['Myth lesson','Infer idea from origin/supernatural narrative.',['pride','obedience','responsibility']],['Legend lesson','Infer values from hero/place/event tradition.',['courage','loyalty','leadership']],['Evidence chain','Connect action → consequence → lesson.',['decision','result','theme']],['Comparison/application','Compare lessons without forcing modern moral onto text.',['two heroes','two consequences','past/present relevance']]],['distinguish supported lesson from generic moral slogan']),
'Prose Revision':m('BECE-level prose revision integrates plot, characterisation, setting, point of view, theme, style and evidence into coherent literary analysis.',[['Plot/conflict','Explain causal structure and turning points.',['conflict','climax','resolution']],['Characterisation','Infer traits/development from multiple evidence types.',['action','dialogue','contrast']],['Setting/viewpoint/style','Explain effect on reader/meaning.',['first person','setting pressure','diction']],['Theme/evidence response','Develop a claim with precise textual support.',['responsibility','betrayal','growth']]],['do not substitute plot retelling for analysis']),
'Poetry: Revision':m('Poetry revision integrates speaker, subject, structure, sound, imagery, figurative language, mood and theme; devices matter because of their effect.',[['Speaker/theme','Distinguish speaker from poet and infer central idea.',['social poem','nature poem','personal reflection']],['Structure/sound','Analyse stanza, line, rhyme, rhythm, repetition, alliteration/assonance.',['refrain','enjambment','sound pattern']],['Imagery/figures','Interpret image/figure in context.',['metaphor','personification','hyperbole']],['Effect/evidence','Explain how selected language creates mood/meaning.',['harsh diction','soft sounds','repeated image']]],['name a device only when learner can explain its contextual effect']),
'Drama: Revision':m('Drama revision integrates printed text and performance: dialogue, stage direction, conflict, character, theme, dramatic structure and performance choices.',[['Dramatic structure/conflict','Trace scene development and turning points.',['opening conflict','climax','resolution']],['Character through dialogue/action','Infer motive/relationship from performance evidence.',['aside','argument','decision']],['Stagecraft','Interpret stage directions, entrances, gesture, space and props.',['pause','movement','prop']],['Theme/performance response','Support interpretation and propose justified performance choices.',['tone of line','blocking','audience effect']]],['distinguish narrator-based prose analysis from dramatic performance evidence']),
};
