import type {NceeDomain,PrimaryPrepClass} from './nceePrep';
export type NceeBankQuestion={id:string;classLevel:PrimaryPrepClass;domain:NceeDomain;topic:string;prompt:string;options:string[];answer:string;explanation:string;difficulty:1|2|3;remediationTopic:string};
const Q=(id:string,classLevel:PrimaryPrepClass,domain:NceeDomain,topic:string,prompt:string,options:string[],answer:string,explanation:string,difficulty:1|2|3=2):NceeBankQuestion=>({id,classLevel,domain,topic,prompt,options,answer,explanation,difficulty,remediationTopic:topic});
const p6:NceeBankQuestion[]=[
Q('m01','Primary 6','Mathematics','Number relationships and estimation','What is the value of the digit 7 in 3,742,615?',['7','700','7,000','700,000'],'700,000','The 7 is in the hundred-thousands place, so its value is 700,000.'),
Q('m02','Primary 6','Mathematics','Number relationships and estimation','Which is the best estimate of 4,982 + 3,107?',['7,000','8,000','9,000','10,000'],'8,000','4,982 is about 5,000 and 3,107 is about 3,000; 5,000 + 3,000 = 8,000.'),
Q('m03','Primary 6','Mathematics','Multi-step operations','A school bought 24 cartons with 36 books in each carton. It gave out 175 books. How many remained?',['689','691','864','1,039'],'689','24 × 36 = 864 books. Then 864 − 175 = 689.'),
Q('m04','Primary 6','Mathematics','Multi-step operations','Evaluate 720 ÷ 8 + 35 × 2.',['125','160','180','250'],'160','Do division and multiplication first: 720÷8=90 and 35×2=70; then 90+70=160.'),
Q('m05','Primary 6','Mathematics','Fractions, decimals and percentages','What is 3/4 of 240?',['60','120','180','320'],'180','One quarter of 240 is 60; three quarters is 3×60=180.'),
Q('m06','Primary 6','Mathematics','Fractions, decimals and percentages','0.35 is equal to what percentage?',['3.5%','35%','350%','0.35%'],'35%','Multiply a decimal by 100 to express it as a percentage: 0.35×100=35%.'),
Q('m07','Primary 6','Mathematics','Ratio, proportion and sharing','Share ₦3,600 in the ratio 2:3. What is the larger share?',['₦1,200','₦1,440','₦2,160','₦2,400'],'₦2,160','There are 5 equal ratio parts. ₦3,600÷5=₦720; larger share=3×₦720=₦2,160.'),
Q('m08','Primary 6','Mathematics','Commercial arithmetic','A bag costs ₦8,000. A 10% discount is given. What is the new price?',['₦7,200','₦7,800','₦8,800','₦800'],'₦7,200','10% of ₦8,000 is ₦800. Subtract the discount: ₦8,000−₦800=₦7,200.'),
Q('m09','Primary 6','Mathematics','Measurement and mensuration','A rectangle is 12 cm long and 7 cm wide. What is its area?',['19 cm²','38 cm²','84 cm²','168 cm²'],'84 cm²','Area of a rectangle = length × width = 12×7=84 cm².'),
Q('m10','Primary 6','Mathematics','Angles, shapes and symmetry','Two angles of a triangle are 55° and 65°. Find the third angle.',['50°','60°','70°','120°'],'60°','Angles in a triangle total 180°. 180−55−65=60°.'),
Q('m11','Primary 6','Mathematics','Time, distance and everyday rate','A bus travels 180 km in 3 hours at a steady rate. What is its average speed?',['30 km/h','60 km/h','90 km/h','540 km/h'],'60 km/h','Speed = distance ÷ time = 180÷3=60 km/h.'),
Q('m12','Primary 6','Mathematics','Tables, charts and averages','The scores are 6, 8, 10, 12 and 14. What is the mean?',['8','9','10','12'],'10','Add the scores: 50. Divide by 5 scores: 50÷5=10.'),
Q('s01','Primary 6','Basic Science & Technology','Body systems and healthy living','Which organ pumps blood around the body?',['Brain','Heart','Kidney','Lung'],'Heart','The heart contracts repeatedly to pump blood through blood vessels.'),
Q('s02','Primary 6','Basic Science & Technology','Body systems and healthy living','Which habit best helps prevent the spread of many communicable diseases?',['Sharing cups','Regular handwashing','Skipping sleep','Eating only sweets'],'Regular handwashing','Washing hands with soap removes many germs before they enter the body or spread to others.'),
Q('s03','Primary 6','Basic Science & Technology','Ecology and environmental care','Which action best reduces soil erosion on a bare slope?',['Removing all plants','Planting grass','Burning the soil','Pouring oil on it'],'Planting grass','Plant roots hold soil together and plant cover reduces the force of moving water.'),
Q('s04','Primary 6','Basic Science & Technology','Materials and changes','Which change is reversible?',['Burning paper','Rusting iron','Melting ice','Cooking an egg'],'Melting ice','Melted ice can freeze back into solid ice; the other changes form new materials or cannot easily be reversed.'),
Q('s05','Primary 6','Basic Science & Technology','Forces, machines and energy','A wheelbarrow mainly helps a worker by doing what?',['Making the load heavier','Reducing effort needed to move a load','Creating electricity','Stopping gravity'],'Reducing effort needed to move a load','A wheelbarrow is a simple machine that gives mechanical advantage and makes moving loads easier.'),
Q('s06','Primary 6','Basic Science & Technology','Electricity and simple circuits','For a bulb to light in a simple battery circuit, the circuit must be _____.',['open','broken','complete','wet'],'complete','Electric current needs a complete closed path from one battery terminal through the bulb and back.'),
Q('s07','Primary 6','Basic Science & Technology','Light, sound and heat','Which material is a good conductor of heat?',['Wood','Plastic','Metal spoon','Rubber'],'Metal spoon','Metals generally transfer heat more readily than wood, plastic or rubber.'),
Q('s08','Primary 6','Basic Science & Technology','Earth, space, weather and resources','Which instrument is used to measure rainfall?',['Thermometer','Rain gauge','Wind vane','Barometer'],'Rain gauge','A rain gauge collects and measures the amount of rain that falls.'),
Q('s09','Primary 6','Basic Science & Technology','Technology, ICT awareness and safety','Which is the safest response to a suspicious online message asking for your password?',['Send the password','Ignore safety rules','Tell a trusted adult and do not share the password','Forward it to friends'],'Tell a trusted adult and do not share the password','Passwords should be kept private; suspicious requests should be reported to a trusted adult.'),
Q('s10','Primary 6','Basic Science & Technology','Forces, machines and energy','What form of energy is stored in food?',['Chemical energy','Sound energy','Light energy','Electrical energy'],'Chemical energy','Food stores chemical energy which the body releases during respiration.'),
Q('e01','Primary 6','English Studies','Comprehension and inference','Ada carried an umbrella although the sky was bright when she left home. Later, dark clouds gathered. What can we infer?',['Ada expected possible rain','Ada disliked umbrellas','It was already raining heavily','The umbrella was broken'],'Ada expected possible rain','Taking an umbrella before rain suggests Ada thought rain might come later.'),
Q('e02','Primary 6','English Studies','Vocabulary and word meaning','Choose the word closest in meaning to “rapid”.',['slow','quick','weak','quiet'],'quick','Rapid means happening or moving very quickly.'),
Q('e03','Primary 6','English Studies','Grammar and word classes','In “The careful driver stopped”, which word is an adjective?',['The','careful','driver','stopped'],'careful','“Careful” describes the noun “driver”, so it is an adjective.'),
Q('e04','Primary 6','English Studies','Tenses and subject–verb agreement','Choose the correct sentence.',['The boys plays football.','The boys play football.','The boys playing football.','The boys is play football.'],'The boys play football.','The plural subject “boys” agrees with the base-form verb “play” in the simple present.'),
Q('e05','Primary 6','English Studies','Tenses and subject–verb agreement','Yesterday, Musa _____ to the market.',['go','goes','went','going'],'went','“Yesterday” signals past time; the past tense of “go” is “went”.'),
Q('e06','Primary 6','English Studies','Spelling, punctuation and usage','Which sentence is punctuated correctly?',['where are you going?','Where are you going?','Where are you going.','where are you going.'],'Where are you going?','A sentence begins with a capital letter and a direct question ends with a question mark.'),
Q('e07','Primary 6','English Studies','Idioms and contextual meaning','If someone says “Keep an eye on my bag,” the person means _____.',['draw an eye on it','watch it carefully','hide it','open it'],'watch it carefully','“Keep an eye on” is an idiom meaning to watch or guard something carefully.'),
Q('e08','Primary 6','English Studies','Ordering ideas and cohesion','Which word best completes: “Tola studied hard; _____, she passed the examination.”',['however','therefore','although','unless'],'therefore','“Therefore” shows that passing was a result of studying hard.'),
Q('e09','Primary 6','English Studies','Editing and error recognition','Choose the correct form: “She _____ two pencils.”',['have','has','having','are having'],'has','With the third-person singular subject “she”, the simple-present form is “has”.'),
Q('e10','Primary 6','English Studies','Vocabulary and word meaning','Choose the opposite of “scarce”.',['rare','plentiful','little','empty'],'plentiful','Scarce means not enough or hard to find; plentiful means available in large amounts.'),
Q('n01','Primary 6','National Values Education','Citizenship and national identity','Which action best shows responsible citizenship?',['Destroying public property','Obeying lawful rules and protecting public property','Refusing every community duty','Spreading false rumours'],'Obeying lawful rules and protecting public property','Responsible citizens respect lawful rules and resources that belong to everyone.'),
Q('n02','Primary 6','National Values Education','Rights, duties and responsible behaviour','A right is best described as _____.',['something every person is entitled to under rules or law','permission to harm others','a reward for cheating','freedom from every responsibility'],'something every person is entitled to under rules or law','Rights are legitimate freedoms or protections, and they exist alongside responsibilities.'),
Q('n03','Primary 6','National Values Education','Leadership, democracy and cooperation','In a fair class election, the best practice is to _____.',['count only a friend’s votes','allow eligible pupils to vote and count votes honestly','threaten voters','change results secretly'],'allow eligible pupils to vote and count votes honestly','Fair participation and honest counting are basic democratic practices.'),
Q('n04','Primary 6','National Values Education','Integrity and consequences of choices','You find money that belongs to a classmate. What action best shows integrity?',['Keep it secretly','Return it or report it to a responsible adult','Spend half and return half','Tell nobody'],'Return it or report it to a responsible adult','Integrity means doing what is honest and right even when no one is forcing you.'),
Q('n05','Primary 6','National Values Education','Peace, security and conflict resolution','Two pupils disagree over a book. What is the best first step?',['Fight','Listen to each other and seek a fair solution','Destroy the book','Call more pupils to quarrel'],'Listen to each other and seek a fair solution','Peaceful conflict resolution begins with calm communication and a fair solution.'),
Q('n06','Primary 6','National Values Education','National symbols, institutions and unity','Which is a national symbol of Nigeria?',['The national flag','A private shop sign','A school timetable','A family photograph'],'The national flag','The national flag represents the country and is one of Nigeria’s national symbols.'),
Q('n07','Primary 6','National Values Education','Community service and public property','Which item is public property?',['A pupil’s private pencil','A government library','A family’s dining table','A personal shoe'],'A government library','A government library is provided for public use and should be protected by citizens.'),
Q('n08','Primary 6','National Values Education','Values in real-life situations','A friend asks you to lie so that he avoids punishment. What should you do?',['Lie immediately','Refuse to lie and encourage him to tell the truth','Blame another pupil','Hide the facts'],'Refuse to lie and encourage him to tell the truth','Honesty and responsibility require telling the truth rather than helping someone deceive others.'),
Q('q01','Primary 6','Quantitative & Vocational Aptitude','Advanced number sequences','What comes next: 3, 6, 12, 24, ____?',['27','36','42','48'],'48','Each number is doubled: 3→6→12→24→48.'),
Q('q02','Primary 6','Quantitative & Vocational Aptitude','Advanced number sequences','Find the missing number: 5, 9, 13, __, 21.',['15','16','17','18'],'17','The sequence increases by 4 each time.'),
Q('q03','Primary 6','Quantitative & Vocational Aptitude','Quantitative analogies','4 is to 16 as 5 is to _____.',['10','20','25','30'],'25','The second number is the square of the first: 4²=16, so 5²=25.'),
Q('q04','Primary 6','Quantitative & Vocational Aptitude','Missing values and coded operations','If ★ means “multiply by 2 then add 1”, what is 7★?',['9','14','15','16'],'15','Multiply 7 by 2 to get 14, then add 1 to get 15.'),
Q('q05','Primary 6','Quantitative & Vocational Aptitude','Tables, charts and comparison','A shop sold 12 pens Monday, 18 Tuesday and 15 Wednesday. How many more were sold Tuesday than Monday?',['3','6','15','30'],'6','Compare Tuesday with Monday: 18−12=6.'),
Q('q06','Primary 6','Quantitative & Vocational Aptitude','Rate, money and measurement aptitude','Three notebooks cost ₦750 equally. What is the cost of one?',['₦150','₦200','₦250','₦300'],'₦250','Equal cost means divide ₦750 by 3: ₦250.'),
Q('q07','Primary 6','Quantitative & Vocational Aptitude','Vocational tools, roles and safety','Which tool is most closely associated with a carpenter?',['Stethoscope','Saw','Thermometer','Syringe'],'Saw','A carpenter commonly uses a saw to cut wood.'),
Q('q08','Primary 6','Quantitative & Vocational Aptitude','Vocational tools, roles and safety','Which worker is most likely to use a trowel?',['Mason','Pilot','Nurse','Tailor'],'Mason','A mason uses a trowel when spreading mortar and laying blocks.'),
Q('q09','Primary 6','Quantitative & Vocational Aptitude','Diagram and spatial reasoning','A square is turned through a quarter-turn. How many degrees is the turn?',['45°','90°','180°','360°'],'90°','A full turn is 360°. One quarter of 360° is 90°.'),
Q('q10','Primary 6','Quantitative & Vocational Aptitude','Mixed timed quantitative reasoning','Which number does not belong: 8, 16, 24, 31, 40?',['16','24','31','40'],'31','All the others are multiples of 8; 31 is not.'),
Q('v01','Primary 6','Verbal Aptitude','Verbal analogies','Bird is to nest as bee is to _____.',['web','hive','den','stable'],'hive','A nest is a bird’s home; a hive is a bee’s home.'),
Q('v02','Primary 6','Verbal Aptitude','Word classification','Which word does not belong?',['mango','orange','banana','carrot'],'carrot','Mango, orange and banana are fruits; carrot is a root vegetable.'),
Q('v03','Primary 6','Verbal Aptitude','Opposites and closest meanings','Choose the word opposite in meaning to “ancient”.',['old','modern','broken','large'],'modern','Ancient means very old; modern is its contrast in time.'),
Q('v04','Primary 6','Verbal Aptitude','Letter and word codes','If CAT is coded as DBU by moving each letter one step forward, how is DOG coded?',['EPH','EOH','CPH','FQI'],'EPH','D→E, O→P and G→H, so DOG becomes EPH.'),
Q('v05','Primary 6','Verbal Aptitude','Sentence completion','The road was flooded, _____ we took another route.',['so','but','unless','because'],'so','“So” shows the result: because the road was flooded, another route was taken.'),
Q('v06','Primary 6','Verbal Aptitude','Logical word relationships','Puppy is to dog as kitten is to _____.',['goat','cat','lion','hen'],'cat','A puppy is a young dog; a kitten is a young cat.'),
Q('v07','Primary 6','Verbal Aptitude','Ordering and sequencing words','Which comes first in dictionary order?',['banana','ball','bank','bag'],'bag','Compare letters: all begin “ba”; the third letters are n, l, n, g. “g” comes first.'),
Q('v08','Primary 6','Verbal Aptitude','Mixed timed verbal reasoning','Complete the pattern: Monday, Wednesday, Friday, _____.',['Saturday','Sunday','Tuesday','Thursday'],'Sunday','The pattern skips one day each time: Monday, Wednesday, Friday, Sunday.'),
Q('v09','Primary 6','Verbal Aptitude','Word classification','Doctor, nurse and pharmacist are related because they all _____.',['work in health care','build houses','grow crops','drive buses'],'work in health care','All three occupations are part of health care.'),
Q('v10','Primary 6','Verbal Aptitude','Verbal analogies','Hot is to cold as tall is to _____.',['high','short','long','wide'],'short','Hot/cold are opposites; tall/short are also opposites.'),
];
// Primary 5 receives the same six-domain standard at gentler difficulty through its weekly bank.
// These questions are intentionally separate learner evidence, not a claim that Primary 5 sits NCEE.
const p5=p6.map((q,i)=>({...q,id:`p5-${q.id}`,classLevel:'Primary 5' as const,difficulty:1 as const,prompt:q.prompt,explanation:`Primary 5 foundation: ${q.explanation}`}));
import {NCEE_EDITORIAL_QUESTION_BANK} from './nceeEditorialBank';
// V10.12: the expanded editorial bank is the primary source for mocks and weekly practice.
// The original V10.11 starter items remain in-source as regression fixtures, but are not
// mixed into live mocks so the eight-form no-reuse guarantee stays deterministic.
export const NCEE_REVIEWED_QUESTION_BANK=NCEE_EDITORIAL_QUESTION_BANK;
export function nceeBankFor(classLevel:PrimaryPrepClass,domain?:NceeDomain){return NCEE_REVIEWED_QUESTION_BANK.filter(q=>q.classLevel===classLevel&&(!domain||q.domain===domain));}
