export type TutorUnit={title:string;terms:Array<[string,string]>;explain:string;example:string;check:string;why?:string;prerequisites?:string[];outcomes?:string[];commonMistakes?:string[]};
export type TutorPlan={goal:string;why:string;units:TutorUnit[];examFocus?:string[];outcomes?:string[]};

export const topicAliases:Record<string,string>={
  'Geometry & Measurement':'Geometry & Mensuration',
  'Data & Statistics':'Statistics & Data'
};

const M=(goal:string,why:string,units:TutorUnit[]):TutorPlan=>({goal,why,units});

export const beceTutorPlans:Record<string,TutorPlan>={
 'Number & Numeration':M(
  'Use numbers confidently across fractions, decimals, percentages, approximation, standard form and directed numbers.',
  'These ideas appear inside almost every other part of BECE Mathematics, so weak number sense makes later topics harder than they need to be.',[
   {title:'Fractions, decimals and percentages',terms:[['fraction','a number that describes parts of a whole'],['decimal','a base-ten way of writing a fraction'],['percentage','a comparison out of 100'],['equivalent','different forms with the same value']],explain:'Learn to move accurately between fractions, decimals and percentages, compare their sizes, simplify fractions and find a fraction or percentage of a quantity.',example:'3/5 = 0.6 = 60%. Therefore 3/5 of 250 = 150.',check:'Can you convert 7/20 to a decimal and percentage, then find 35% of 240?'},
   {title:'Operations and order of operations',terms:[['operation','a calculation such as addition, subtraction, multiplication or division'],['BODMAS','the agreed order for brackets, orders, division/multiplication, addition/subtraction']],explain:'Use the four operations with whole numbers, fractions and decimals. Apply BODMAS so a multi-step expression has one standard answer.',example:'18 - 2 × 5 = 18 - 10 = 8, not 80.',check:'Can you evaluate 24 ÷ 3 + 2 × 5 without changing the order?'},
   {title:'Approximation, estimation and significant figures',terms:[['estimate','a sensible approximate value'],['decimal place','a position after the decimal point'],['significant figure','a digit that contributes to the precision of a number']],explain:'Round numbers to required decimal places or significant figures and use estimation to check whether a calculated answer is reasonable.',example:'47.836 to 2 decimal places is 47.84; to 2 significant figures it is 48.',check:'Can you round 0.006784 to 2 significant figures and explain why the zeros are not counted?'},
   {title:'Standard form and powers',terms:[['index/power','how many times a base is used as a factor'],['standard form','a × 10^n where 1 ≤ a < 10']],explain:'Write very large or small numbers compactly and use simple laws of indices where required.',example:'530,000 = 5.3 × 10^5 and 0.0042 = 4.2 × 10^-3.',check:'Can you write 7,250,000 and 0.00081 in standard form?'},
   {title:'Directed numbers and number line reasoning',terms:[['directed number','a positive or negative number showing direction from zero'],['integer','a whole positive number, whole negative number, or zero']],explain:'Interpret positive and negative values, order them and calculate with them, especially in temperature, debt, elevation and number-line questions.',example:'-3 + 8 = 5; moving 8 steps right from -3 lands at 5.',check:'Can you explain why -2 is greater than -7 and calculate -6 - (-4)?'}
 ]),
 'Algebra':M(
  'Translate patterns and statements into algebra, simplify expressions, solve equations and use formulas confidently.',
  'Algebra is the language used to represent unknown quantities and relationships. BECE candidates need more than one equation trick.',[
   {title:'Algebraic language and expressions',terms:[['variable','a letter representing a number that can change or be unknown'],['constant','a fixed number'],['coefficient','the number multiplying a variable'],['term','a single part of an expression separated by + or −'],['expression','a mathematical phrase without an equals sign']],explain:'Read algebra correctly, identify terms and coefficients, translate simple verbal statements into expressions, and distinguish an expression from an equation.',example:'“Five more than three times x” is 3x + 5.',check:'Can you identify the coefficient and constant in 7y - 4 and write “twice n decreased by 3”?'},
   {title:'Collecting like terms and substitution',terms:[['like terms','terms with the same variable part'],['substitution','replacing a variable with a known value']],explain:'Combine only like terms and evaluate expressions by substituting given values carefully, including negative values.',example:'3x + 5x - 2 = 8x - 2. If x = 4, the value is 30.',check:'Can you simplify 4a + 3 - a + 8 and evaluate it when a = 2?'},
   {title:'Linear equations',terms:[['equation','a statement that two expressions are equal'],['solution','a value that makes an equation true'],['inverse operation','an operation that undoes another operation']],explain:'Treat an equation as a balance. Undo operations in a sensible order and perform the same operation on both sides.',example:'3x + 5 = 20 → 3x = 15 → x = 5.',check:'Can you solve 5x - 7 = 18 and verify the answer by substitution?'},
   {title:'Equations with brackets and variables on both sides',terms:[['expand','remove brackets by multiplying'],['transpose','a shorthand description for applying inverse operations; the equality must still be preserved']],explain:'Expand brackets first when needed, collect variable terms and constants, then isolate the unknown without breaking the equality.',example:'2(x + 3) = 14 → 2x + 6 = 14 → 2x = 8 → x = 4.',check:'Can you solve 4(x - 2) = 2x + 6?'},
   {title:'Simultaneous equations',terms:[['simultaneous equations','two equations solved together because the same unknowns must satisfy both'],['elimination','removing one variable by adding or subtracting equations'],['substitution method','expressing one variable in terms of another and replacing it']],explain:'Recognize when two unknowns are linked by two equations. Use elimination or substitution, then check both original equations.',example:'x + y = 9 and x - y = 3. Add: 2x = 12, so x = 6 and y = 3.',check:'Can you solve 2x + y = 11 and x - y = 1 and check both equations?'},
   {title:'Formulae, variation and word problems',terms:[['formula','a rule written using symbols'],['subject of a formula','the variable isolated on one side'],['direct proportion','two quantities changing in the same ratio']],explain:'Substitute into formulas, rearrange simple formulas, and convert real situations into equations before solving.',example:'If P = 2l + 2w, l = 7 and w = 3, then P = 20.',check:'Can you make w the subject of P = 2l + 2w, then use it when P = 30 and l = 6?'}
 ]),
 'Geometry & Mensuration':M(
  'Reason with angles and shapes, then calculate lengths, perimeter, area, surface area and volume using correct units.',
  'Geometry is not a formula-list. Students must first understand the object, relationships and what is actually being measured.',[
   {title:'Lines, angles and angle relationships',terms:[['acute angle','less than 90°'],['right angle','exactly 90°'],['obtuse angle','between 90° and 180°'],['straight angle','180°'],['vertically opposite angles','opposite angles formed by intersecting lines and equal in size']],explain:'Identify angle types and use angle facts on straight lines, around a point, vertically opposite angles and parallel lines.',example:'Angles on a straight line add to 180°. If one is 128°, the other is 52°.',check:'Can you state the angle facts before calculating an unknown angle?'},
   {title:'Triangles, quadrilaterals and polygons',terms:[['polygon','a closed plane shape with straight sides'],['regular polygon','a polygon with equal sides and equal angles'],['interior angle','an angle inside a polygon']],explain:'Know properties of common triangles and quadrilaterals and use angle sums to solve problems.',example:'The interior angles of a triangle total 180°; a quadrilateral totals 360°.',check:'Can you find the third angle of a triangle with angles 48° and 67°?'},
   {title:'Perimeter and circumference',terms:[['perimeter','total distance around a plane shape'],['circumference','distance around a circle'],['radius','distance from centre to circle'],['diameter','distance across a circle through its centre']],explain:'Add boundary lengths for polygons and use the circle relationship C = 2πr or πd when appropriate.',example:'A rectangle 8 cm by 5 cm has perimeter 26 cm.',check:'Can you explain why perimeter uses linear units such as cm, not cm²?'},
   {title:'Area of plane shapes',terms:[['area','amount of surface inside a plane shape'],['base','a chosen side used for measurement'],['perpendicular height','the shortest 90° distance from base to opposite point/side']],explain:'Use and understand area formulas for rectangles, triangles, parallelograms, trapezia and circles, including composite shapes.',example:'Triangle area = 1/2 × base × perpendicular height.',check:'Can you find a missing dimension when area is given rather than simply applying a formula?'},
   {title:'Surface area and volume of solids',terms:[['surface area','total area of the outer faces of a solid'],['volume','space occupied by a solid'],['cross-section','shape seen when a solid is cut across']],explain:'Distinguish surface area from volume and calculate common prisms/cuboids/cylinders at the required level.',example:'A cuboid 4 cm × 3 cm × 2 cm has volume 24 cm³.',check:'Can you explain why volume uses cubic units?'},
   {title:'Scale drawing, bearings and geometric construction',terms:[['scale','relationship between drawing length and real length'],['bearing','clockwise angle measured from north, written with three digits'],['construction','accurate drawing using geometric instruments']],explain:'Interpret scales, basic bearings and constructions where required, drawing carefully rather than estimating by eye.',example:'A bearing of 065° means turn 65° clockwise from north.',check:'Can you distinguish a bearing of 065° from 65° measured from east?'}
 ]),
 'Commercial Arithmetic':M(
  'Handle everyday money mathematics: profit/loss, discount, percentage change, interest, commission, tax and simple financial decisions.',
  'BECE questions often place percentage ideas inside realistic buying, selling and saving situations.',[
   {title:'Cost price, selling price, profit and loss',terms:[['cost price','amount paid to obtain an item'],['selling price','amount received when it is sold'],['profit','selling price minus cost price'],['loss','cost price minus selling price']],explain:'Identify the correct base quantities before calculating profit or loss and their percentages.',example:'CP ₦800, SP ₦920 → profit ₦120 → profit% = 120/800 × 100 = 15%.',check:'Can you explain why profit percentage is normally compared with cost price?'},
   {title:'Discount, markup and percentage change',terms:[['discount','reduction from marked/original price'],['markup','increase added to cost'],['percentage change','change divided by original amount × 100']],explain:'Separate the amount of change from the final price and always identify the original/base amount.',example:'20% discount on ₦5,000 is ₦1,000, so sale price is ₦4,000.',check:'Can you find the original price if a 10% discount gives a sale price of ₦4,500?'},
   {title:'Simple interest',terms:[['principal','original amount invested or borrowed'],['rate','percentage charged or earned per period'],['time','number of periods'],['simple interest','interest calculated only on the original principal']],explain:'Use I = PRT/100 with consistent time units, then distinguish interest from total amount.',example:'₦20,000 at 5% per year for 2 years gives ₦2,000 interest and ₦22,000 total.',check:'Can you find the rate if principal, time and interest are given?'},
   {title:'Commission, tax and bills',terms:[['commission','payment based on a percentage of sales/work'],['tax','compulsory charge calculated from a stated base'],['bill','statement of amount owed']],explain:'Read what percentage applies to what amount. Multi-part bills may require subtotals before tax or service charges.',example:'5% commission on ₦80,000 sales is ₦4,000.',check:'Can you calculate a bill with a subtotal and 7.5% tax without applying tax to the wrong base?'}
 ]),
 'Statistics & Data':M(
  'Collect, represent, read and summarize data using tables, charts and measures of central tendency and spread.',
  'The aim is not just calculating averages; it is interpreting what data says and choosing the right measure.',[
   {title:'Data, frequency and tables',terms:[['data','collected facts or values'],['frequency','how often a value/category occurs'],['frequency table','organized display of values and their counts']],explain:'Organize raw data, count accurately and read totals/frequencies from tables.',example:'For 2,2,3,4,4,4: frequency of 4 is 3.',check:'Can you build a frequency table without losing repeated values?'},
   {title:'Mean, median, mode and range',terms:[['mean','total divided by number of values'],['median','middle value after ordering'],['mode','most frequent value'],['range','largest minus smallest']],explain:'Choose the requested measure and understand what each describes.',example:'2,4,4,7,8 → mean 5, median 4, mode 4, range 6.',check:'Can you explain why the median requires ordering first?'},
   {title:'Bar charts, pie charts and line graphs',terms:[['bar chart','separate bars representing categories'],['pie chart','circle divided into sectors representing proportions'],['line graph','points joined to show change, often over time']],explain:'Read scales carefully, compare categories, calculate sector angles where needed and avoid confusing chart types.',example:'A category representing 25% of a pie chart has angle 90°.',check:'Can you calculate the fraction represented by a 72° sector?'},
   {title:'Interpretation and comparison',terms:[['trend','general direction in data'],['outlier','value noticeably different from others']],explain:'Use data to make justified statements, compare groups and recognize when one summary measure may be misleading.',example:'A very high outlier can raise the mean while leaving the median much less affected.',check:'Can you choose whether mean or median better represents a set with one extreme value?'}
 ]),
 'Ratio & Proportion':M(
  'Compare quantities, simplify and share in ratios, scale values and solve direct-proportion problems.',
  'Ratio reasoning appears in recipes, maps, rates, mixtures, scale drawings and many algebraic problems.',[
   {title:'Meaning and simplification of ratio',terms:[['ratio','comparison of quantities in the same relationship'],['equivalent ratio','ratio obtained by multiplying or dividing all parts by the same factor']],explain:'Put quantities in compatible units first, then simplify by a common factor.',example:'50 cm : 2 m = 50 : 200 = 1 : 4.',check:'Can you explain why 2 kg : 500 g must be converted before simplifying?'},
   {title:'Sharing in a given ratio',terms:[['part','one share-unit in a ratio'],['total parts','sum of the ratio numbers']],explain:'Find total ratio parts, find the value of one part, then multiply for each share.',example:'Share ₦900 in 2:3 → 5 parts, ₦180 each part → ₦360 and ₦540.',check:'Can you work backwards from one person’s share to the total?'},
   {title:'Direct proportion and unitary method',terms:[['proportion','equality of two ratios'],['unitary method','find the value for one unit, then scale']],explain:'Decide whether quantities scale together and use equivalent ratios or the value of one unit.',example:'3 books cost ₦900 → 1 costs ₦300 → 7 cost ₦2,100.',check:'Can you recognize when doubling one quantity should double the other?'},
   {title:'Rates and scale',terms:[['rate','comparison of quantities with different units'],['scale','fixed ratio between drawing/model and actual object']],explain:'Work with speed, price per unit and map/drawing scales while retaining units.',example:'150 km in 3 h gives average speed 50 km/h.',check:'Can you convert a map measurement into real distance using a stated scale?'}
 ]),
 'Measurement':M(
  'Measure and convert length, mass, capacity, time and related units accurately.',
  'Correct conversion and units are foundational to mensuration, science and everyday quantitative reasoning.',[
   {title:'Metric length',terms:[['millimetre','1/1000 of a metre'],['centimetre','1/100 of a metre'],['kilometre','1000 metres']],explain:'Convert within metric length and choose sensible units for objects and distances.',example:'2.75 m = 275 cm.',check:'Can you explain whether conversion to a smaller unit multiplies or divides?'},
   {title:'Mass and capacity',terms:[['gram','metric mass unit'],['kilogram','1000 grams'],['millilitre','1/1000 litre'],['litre','standard unit of capacity']],explain:'Convert mass/capacity and solve realistic totals and differences.',example:'3.4 kg = 3400 g; 2.5 L = 2500 ml.',check:'Can you combine 750 ml and 1.8 L in one unit?'},
   {title:'Time and timetables',terms:[['duration','amount of elapsed time'],['24-hour time','time notation from 00:00 to 23:59']],explain:'Calculate elapsed time, interpret timetables and convert common time units.',example:'From 13:45 to 15:10 is 1 hour 25 minutes.',check:'Can you handle a duration that crosses an hour boundary?'},
   {title:'Accuracy and units in context',terms:[['precision','level of detail in a measurement'],['unit','agreed quantity used for measurement']],explain:'Attach correct units, choose sensible precision and check whether an answer’s size makes sense.',example:'A classroom length of 8 m is sensible; 8 mm is not.',check:'Can you spot an answer that is numerically calculated but uses an impossible unit?'}
 ]),
 'Probability':M(
  'Describe chance, calculate simple probabilities and use sample spaces for equally likely events.',
  'Probability combines fractions with logical counting and careful interpretation of possible outcomes.',[
   {title:'Chance and probability scale',terms:[['impossible','probability 0'],['certain','probability 1'],['equally likely','outcomes having the same chance']],explain:'Place events from impossible to certain and express probability as fraction, decimal or percentage when required.',example:'A fair coin landing heads has probability 1/2 = 0.5 = 50%.',check:'Can you explain why probability cannot be greater than 1?'},
   {title:'Favourable and total outcomes',terms:[['outcome','a possible result'],['favourable outcome','a result satisfying the event']],explain:'For equally likely outcomes, probability = favourable outcomes / total possible outcomes.',example:'Even number on a fair die: {2,4,6}, so 3/6 = 1/2.',check:'Can you list outcomes before counting rather than guessing?'},
   {title:'Sample spaces and combined events',terms:[['sample space','complete set of possible outcomes'],['event','one or more outcomes of interest']],explain:'Use lists, tables or diagrams to organize outcomes for simple two-stage experiments.',example:'Two coin tosses: HH, HT, TH, TT. Exactly one head occurs in 2 of 4 outcomes.',check:'Can you build a complete sample space without missing or duplicating outcomes?'}
 ])
};

export const beceEnglishPlans:Record<string,TutorPlan>={
 'Grammar & Structure':M('Use standard English grammar accurately in sentences and exam contexts.','Grammar supports comprehension, writing and every language-use question.',[
  {title:'Sentence parts and clause structure',terms:[['subject','who or what the sentence is about'],['predicate','what is said about the subject'],['clause','a group of words containing a subject and verb'],['phrase','a group of words without a complete subject-verb structure']],explain:'Identify how sentences are built before deciding whether a form is correct.',example:'In “The diligent girl finished early”, “The diligent girl” is the subject and “finished early” is the predicate.',check:'Can you distinguish a phrase from a clause?'},
  {title:'Tense and aspect',terms:[['tense','form showing time'],['present perfect','have/has + past participle linking past action to present'],['continuous','be + -ing form showing ongoing action']],explain:'Choose verb forms from time clues and meaning, not merely what sounds familiar.',example:'“She has completed the work” differs from “She completed the work yesterday.”',check:'Can you explain why “yesterday” normally points to simple past?'},
  {title:'Agreement, pronouns and determiners',terms:[['agreement','matching grammatical forms'],['pronoun','word replacing a noun'],['determiner','word introducing or limiting a noun, such as a, the, some, each']],explain:'Match subjects and verbs, pronouns and antecedents, and use determiners correctly.',example:'“Each pupil has a book” because “each” is singular.',check:'Can you find the true subject in a sentence with an intervening phrase?'},
  {title:'Prepositions, conjunctions and modifiers',terms:[['preposition','word showing relationship, often place/time/direction'],['conjunction','word joining words, phrases or clauses'],['modifier','word/group adding description']],explain:'Use relationship words according to meaning and avoid misplaced modifiers.',example:'“Although it rained, we continued” uses a conjunction to show contrast.',check:'Can you choose between in, on and at from context rather than memorization alone?'}
 ]),
 'Vocabulary & Lexis':M('Understand word meaning, relationships and appropriate usage in context.','BECE vocabulary rewards context awareness, not isolated memorization.',[
  {title:'Meaning from context',terms:[['context','words and ideas surrounding a target word'],['synonym','word with similar meaning'],['antonym','word with opposite meaning']],explain:'Use sentence clues to infer meaning, then test options inside the sentence.',example:'“The diligent pupil revised nightly.” Diligent means hard-working.',check:'Can you identify which surrounding words prove your choice?'},
  {title:'Word relationships and semantic fields',terms:[['semantic field','group of words related by subject or meaning'],['collocation','words that commonly occur together']],explain:'Recognize natural word partnerships and groups of meaning.',example:'We normally say “make a decision”, not “do a decision”.',check:'Can you choose the word that fits both meaning and natural usage?'},
  {title:'Idioms and figurative meaning',terms:[['idiom','fixed expression whose meaning is not fully literal'],['figurative','non-literal use creating an image or special meaning']],explain:'Interpret the whole expression in context instead of translating each word literally.',example:'“He kicked the bucket” is an idiomatic expression meaning he died.',check:'Can you tell when a phrase is literal and when context makes it figurative?'},
  {title:'Register and appropriate word choice',terms:[['register','language style suited to situation or profession'],['formal','careful language used in official contexts'],['informal','relaxed language used in familiar contexts']],explain:'Choose vocabulary that suits audience, purpose and context.',example:'A formal letter uses “I wish to request…” rather than casual chat language.',check:'Can you identify vocabulary suited to school, hospital or legal contexts?'}
 ]),
 'Comprehension':M('Read passages actively, retrieve evidence, infer meaning and answer precisely.','Comprehension tests reading decisions: locating, interpreting and expressing evidence.',[
  {title:'Main idea and supporting details',terms:[['main idea','central message of a passage/paragraph'],['supporting detail','information that develops or proves the main idea']],explain:'Separate the central point from examples and minor details.',example:'If every sentence explains causes of flooding, “causes of flooding” is likely the main idea.',check:'Can you state the main idea in one sentence without copying the whole passage?'},
  {title:'Literal retrieval and reference',terms:[['literal','directly stated'],['reference word','word such as he, it, this or they pointing to something else']],explain:'Return to the exact part of the passage and track pronoun/reference links.',example:'In “Ada found the book and returned it”, “it” refers to the book.',check:'Can you quote the evidence location before answering?'},
  {title:'Inference and implied meaning',terms:[['inference','conclusion supported by clues but not directly stated'],['implied','suggested rather than plainly said']],explain:'Combine clues with reasonable logic without inventing facts beyond the passage.',example:'If streets are wet and people carry umbrellas, rain is a supported inference.',check:'Can you name the clue that supports your inference?'},
  {title:'Vocabulary in passage and writer purpose',terms:[['tone','writer’s attitude'],['purpose','reason the text was written']],explain:'Use local context to interpret words and identify whether the writer informs, persuades, describes or entertains.',example:'Repeated warnings and commands may indicate a persuasive/cautionary purpose.',check:'Can you distinguish what the writer says from how the writer feels about it?'},
  {title:'Answer construction',terms:[['relevant','directly connected to the question'],['concise','clear without unnecessary words']],explain:'Answer the exact command, use evidence and avoid copying unrelated sentences.',example:'For “Why did Musa leave?”, give the cause, not a summary of the paragraph.',check:'Can you turn evidence into a direct one- or two-sentence answer?'}
 ]),
 'Sentence Meaning':M('Recognize equivalent meanings, implications and relationships between sentence forms.','This tests whether a learner understands the idea beneath the wording.',[
  {title:'Paraphrase without changing meaning',terms:[['paraphrase','express the same meaning in different words'],['equivalent','having the same meaning/value']],explain:'Identify the core proposition, then reject options that add or remove meaning.',example:'“Bola is too tired to continue” means Bola is so tired that continuing is not possible.',check:'Can you explain why a near-synonym may still change the full sentence meaning?'},
  {title:'Negation and logical meaning',terms:[['negation','making a statement negative'],['double negative','two negative forms that may create nonstandard or changed meaning']],explain:'Track words such as not, never, hardly, unless and except carefully.',example:'“Hardly ever” means very rarely, not frequently.',check:'Can you restate “Unless you hurry, you will miss the bus” using “if…not”?'},
  {title:'Comparison, condition and implication',terms:[['condition','requirement on which something depends'],['implication','meaning suggested by a statement']],explain:'Recognize relationships expressed by if, unless, as…as, more…than, too…to and enough…to.',example:'“If it rains, we will stay” makes staying dependent on rain.',check:'Can you preserve both condition and result when paraphrasing?'}
 ]),
 'Punctuation':M('Use punctuation to make sentence structure and meaning clear.','Punctuation is grammar made visible; it can change how a sentence is read and understood.',[
  {title:'Sentence endings and commas',terms:[['full stop','ends a statement'],['question mark','ends a direct question'],['comma','marks certain boundaries, items or pauses']],explain:'Use sentence-ending marks correctly and commas for lists, introductions and selected clause boundaries.',example:'“After the rain stopped, we left.” uses a comma after an introductory clause.',check:'Can you tell why not every pause in speech deserves a comma?'},
  {title:'Apostrophes and possession',terms:[['apostrophe','mark used for possession and contractions'],['contraction','shortened form such as do not → don’t']],explain:'Distinguish plural -s from possessive ’s and place apostrophes correctly for singular/plural possessors.',example:'“the girl’s bag” = one girl; “the girls’ bags” = more than one girl.',check:'Can you punctuate “the teachers room” if one teacher owns it and if several do?'},
  {title:'Quotation and direct speech',terms:[['quotation marks','marks around direct words spoken/written'],['direct speech','speaker’s exact words']],explain:'Place quotation marks and related punctuation consistently.',example:'Mother asked, “Where are you going?”',check:'Can you separate the spoken words from the reporting clause?'},
  {title:'Colon, semicolon and other marks',terms:[['colon','introduces explanation/list after a complete lead-in'],['semicolon','links closely related independent clauses or separates complex list items']],explain:'Use advanced punctuation only when sentence structure supports it.',example:'“Bring three things: a pen, ruler and notebook.”',check:'Can you explain why a colon should not split a verb from its object?' }
 ]),
 'Spelling & Usage':M('Recognize standard spellings and choose words/forms that fit meaning and grammar.','Accurate spelling and usage improve both exam performance and written communication.',[
  {title:'Common spelling patterns',terms:[['syllable','beat/unit of sound in a word'],['prefix','element added before a base word'],['suffix','element added after a base word']],explain:'Use word families, syllables and affixes to reason about spelling instead of visual guessing only.',example:'happy → happiness changes y to i before -ness.',check:'Can you identify the base word before adding a suffix?'},
  {title:'Frequently confused words',terms:[['homophone','word sounding like another but differing in meaning/spelling'],['confusable','word easily mixed with another']],explain:'Use sentence meaning to distinguish pairs such as accept/except, affect/effect and their/there/they’re.',example:'“Please accept the gift” versus “Everyone came except Tola.”',check:'Can you explain the meaning of each option before choosing?'},
  {title:'Standard usage',terms:[['standard English','widely accepted grammatical/lexical form for formal contexts'],['usage','customary way a word/form is used']],explain:'Choose forms that are grammatically and contextually standard.',example:'“She is good at Mathematics,” not “good in Mathematics” in standard exam usage.',check:'Can you test an expression inside a complete sentence before deciding?' }
 ]),
 'Word Classes':M('Identify and use parts of speech according to the job they perform in a sentence.','A word’s class matters because it controls sentence structure and meaning.',[
  {title:'Nouns and pronouns',terms:[['noun','word naming a person, place, thing or idea'],['pronoun','word standing in for a noun/noun phrase'],['antecedent','noun a pronoun refers to']],explain:'Identify noun types and pronoun reference in actual sentences.',example:'In “Kemi said she was ready”, “she” is a pronoun referring to Kemi.',check:'Can you distinguish possessive pronouns from possessive determiners?'},
  {title:'Verbs and auxiliaries',terms:[['verb','word expressing action, event or state'],['auxiliary','helping verb used with a main verb'],['finite verb','verb marked for tense/agreement']],explain:'Locate the verb phrase and recognize main versus helping verbs.',example:'In “They have finished”, “have” is auxiliary and “finished” is the main verb.',check:'Can you identify the finite verb in a longer sentence?'},
  {title:'Adjectives and adverbs',terms:[['adjective','word describing/modifying a noun'],['adverb','word modifying a verb, adjective, adverb or whole clause']],explain:'Classify from function, not just endings such as -ly.',example:'“fast” is an adjective in “a fast car” but an adverb in “drive fast”.',check:'Can you explain why the same spelling can serve different word classes?'},
  {title:'Prepositions and conjunctions',terms:[['preposition','shows relationship between a noun phrase and another element'],['conjunction','joins words, phrases or clauses']],explain:'Differentiate relation words from joining words by their grammatical job.',example:'“under the table” uses a preposition; “because it rained” begins a subordinate clause.',check:'Can you classify “before” differently depending on how it is used?' }
 ]),
 'Concord':M('Make subjects, verbs and related forms agree correctly, including difficult constructions.','Concord errors are common because the true subject can be hidden by nearby words.',[
  {title:'Basic subject–verb agreement',terms:[['subject','noun phrase controlling the verb'],['agreement/concord','matching grammatical number/person']],explain:'Singular subjects generally take singular verb forms; plural subjects take plural forms, with special behavior of be/have.',example:'“The boy plays”; “The boys play.”',check:'Can you ignore a nearby noun that is not the true subject?'},
  {title:'Indefinite pronouns and quantity expressions',terms:[['indefinite pronoun','non-specific pronoun such as each, everyone, neither'],['quantity expression','phrase indicating amount/number']],explain:'Words such as each, everyone and one are singular even when followed by plural nouns.',example:'“Each of the players has a jersey.”',check:'Can you explain why “players” does not control the verb here?'},
  {title:'Compound subjects and either/neither structures',terms:[['compound subject','two or more subjects joined together'],['proximity rule','in some paired structures the nearer subject affects agreement']],explain:'Handle subjects joined by and, or, either…or and neither…nor according to standard rules.',example:'“My brother and sister are home.”',check:'Can you choose the verb in “Neither the teacher nor the pupils ___ ready” and explain why?'},
  {title:'Collective nouns and tricky agreement',terms:[['collective noun','singular-form noun naming a group'],['relative clause','clause introduced by who/which/that modifying a noun']],explain:'Use meaning and structure to handle group nouns, titles, measurements and relative-clause agreement.',example:'“Ten kilometres is a long distance” treats the measurement as one amount.',check:'Can you identify which noun controls a verb inside a relative clause?' }
 ])
};



// V7.20.7 academic depth layer. These additions keep the V7.20.6 Live Teaching Board,
// but make the teaching map closer to what an experienced tutor would deliberately cover.
function addUnits(plan:TutorPlan|undefined, units:TutorUnit[]){ if(plan) plan.units.push(...units); }

addUnits(beceTutorPlans['Number & Numeration'],[
 {title:'Rational, irrational numbers and pi',terms:[['rational number','a number that can be written as a fraction of integers'],['irrational number','a number that cannot be written as an exact fraction of integers'],['pi','the constant ratio of a circle’s circumference to its diameter']],why:'BECE/JSS3 work expects learners to distinguish number types and use π sensibly in mensuration.',prerequisites:['fractions','square roots at a basic level'],outcomes:['classify common rational and irrational numbers','use an appropriate value of π'],explain:'Rational numbers include integers, terminating decimals and recurring decimals because each can be written as a fraction. Irrational numbers such as √2 and π do not terminate or repeat in a fixed pattern. π is approximately 3.142 or 22/7 depending on the question.',example:'0.75 = 3/4 is rational. √2 is irrational. In circle work, use the value of π stated by the question.',check:'Can you explain why 0.333… is rational but √3 is not? '},
 {title:'Binary numbers and base-two operations',terms:[['binary','a number system using only 0 and 1'],['place value','the value a digit gets from its position'],['base','the number of digits used by a number system']],why:'Binary number work appears in the JSS3 mathematics curriculum and can be examined directly.',prerequisites:['place value','addition and subtraction'],outcomes:['convert simple base-2 and base-10 numbers','add and subtract short binary numbers'],explain:'In base two the place values are powers of 2: 1, 2, 4, 8, 16 and so on. Read a binary number by adding the place values where a 1 appears. Operations follow the same ideas as base ten, but carrying occurs whenever a column totals 2.',example:'1011₂ = 8 + 0 + 2 + 1 = 11₁₀. Also, 1 + 1 in binary is written 10₂.',check:'What base-ten number is 1101₂, and why?'}
]);

addUnits(beceTutorPlans['Algebra'],[
 {title:'Factorisation',terms:[['factorise','rewrite an expression as a product of factors'],['common factor','a factor shared by every term'],['difference of two squares','an expression a² − b² that factors as (a−b)(a+b)']],why:'JSS3 learners are expected to factorise simple and selected quadratic expressions before later algebra builds on the skill.',prerequisites:['multiplication','like terms','expanding brackets'],outcomes:['take out a common factor','factorise simple grouped expressions','recognise difference of two squares'],explain:'Factorising reverses expansion. First look for a common factor shared by every term. After that, check whether a known pattern such as a² − b² applies. Always multiply the factors back to verify.',example:'6x + 9 = 3(2x + 3). Also x² − 25 = (x − 5)(x + 5).',check:'Can you factorise 8a + 12 and verify by expanding your answer?'},
 {title:'Equations involving fractions',terms:[['denominator','the bottom part of a fraction'],['lowest common multiple','the smallest number divisible by all given denominators']],why:'Fractional equations become easy only when the learner understands why denominators are cleared.',prerequisites:['fractions','LCM','simple equations'],outcomes:['clear denominators safely','solve one-variable fractional equations','translate word problems into fractional equations'],explain:'Find a common multiple of the denominators and multiply every term on both sides by it. This removes the fractions without changing the equality. Then solve the simpler equation and check the result.',example:'x/3 + 2 = 6. Subtract 2 to get x/3 = 4; multiply both sides by 3 to get x = 12.',check:'Can you solve x/4 + 3 = 8 and explain why multiplying both sides by 4 is valid?'},
 {title:'Tables, graphs and simultaneous equations',terms:[['coordinate','an ordered pair locating a point'],['linear graph','a straight-line graph representing a linear relationship'],['intersection','point where two graphs meet']],why:'A graphical solution shows what simultaneous equations actually mean: one point satisfies both relationships.',prerequisites:['substitution','coordinates','simple linear equations'],outcomes:['make a table of values','plot a linear graph','read the intersection as the simultaneous solution'],explain:'Choose values for one variable, calculate the other, plot the points and draw each line accurately. The point where both lines cross gives the values that satisfy both equations.',example:'For x + y = 5, points such as (0,5), (2,3) and (5,0) lie on the same line.',check:'Why does the intersection of two linear graphs solve both equations at once?'}
]);

addUnits(beceTutorPlans['Commercial Arithmetic'],[
 {title:'Simple and compound interest',terms:[['principal','the original amount invested or borrowed'],['interest','money paid or earned for using money'],['compound interest','interest calculated on the growing balance, not only the original principal']],why:'The JSS3 curriculum includes compound interest and its everyday applications.',prerequisites:['percentages','money calculations'],outcomes:['distinguish simple from compound interest','calculate short compound-growth cases','interpret loans and savings contexts'],explain:'Simple interest repeatedly uses the original principal. Compound interest adds each period’s interest to the balance before the next period is calculated. For short exam problems, work year by year unless a formula is explicitly appropriate.',example:'₦10,000 at 10% compound interest becomes ₦11,000 after year 1 and ₦12,100 after year 2.',check:'Why is the second year’s interest larger than the first in compound interest?'}
]);

addUnits(beceTutorPlans['Geometry & Mensuration'],[
 {title:'Similar shapes and scale factor',terms:[['similar shapes','shapes with the same form but possibly different sizes'],['scale factor','multiplier relating corresponding lengths'],['corresponding','matching positions in two similar figures']],why:'Similarity is used to connect lengths, areas and volumes and is part of JSS3 geometry work.',prerequisites:['ratio','area','volume'],outcomes:['identify similar figures','find scale factors','connect length, area and volume scale factors'],explain:'For similar shapes, corresponding angles are equal and corresponding lengths have one common scale factor. If lengths scale by k, areas scale by k² and volumes by k³.',example:'If every length doubles, area becomes 4 times as large and volume becomes 8 times as large.',check:'If the length scale factor is 3, what are the area and volume scale factors?'},
 {title:'Introductory trigonometry',terms:[['right-angled triangle','a triangle containing one 90° angle'],['opposite','side across from the chosen angle'],['adjacent','non-hypotenuse side beside the chosen angle'],['hypotenuse','longest side opposite the right angle']],why:'JSS3 curriculum introduces sine, cosine and tangent for acute angles in right-angled triangles.',prerequisites:['ratio','right-angled triangles'],outcomes:['label opposite/adjacent/hypotenuse correctly','choose sine, cosine or tangent','solve simple right-triangle problems'],explain:'The side names depend on the angle you are considering. Sine compares opposite to hypotenuse, cosine compares adjacent to hypotenuse, and tangent compares opposite to adjacent. Label the triangle before choosing a ratio.',example:'For angle θ, if opposite = 3 and adjacent = 4, tan θ = 3/4.',check:'Why must you identify the chosen angle before naming the opposite and adjacent sides?'},
 {title:'Geometric construction',terms:[['construction','accurate drawing made with geometric instruments'],['bisect','divide into two equal parts'],['perpendicular','meeting at 90°']],why:'Construction assesses practical geometric reasoning, not only calculation.',prerequisites:['angle types','use of ruler and compass'],outcomes:['construct selected angles','copy/bisect angles','construct perpendiculars and simple shapes'],explain:'Construction is a sequence of justified compass arcs and straight lines. Accuracy matters, so the learner should understand what each arc guarantees rather than copying a picture blindly.',example:'To bisect an angle, draw equal-radius arcs from points on both arms, join their intersection to the vertex, and the angle is split equally.',check:'What does “bisect” guarantee about the two resulting angles?'}
]);

addUnits(beceTutorPlans['Statistics & Data'],[
 {title:'Data collection and presentation',terms:[['frequency','how often a value occurs'],['frequency table','table showing values/categories and their counts'],['bar chart','separate bars representing categories or discrete values'],['histogram','touching bars representing continuous grouped data']],why:'Students must not only calculate statistics; they must organise and interpret data correctly.',prerequisites:['counting','scales'],outcomes:['construct frequency tables','choose suitable displays','read scales accurately','interpret trends without inventing claims'],explain:'Begin by deciding what the data represents and whether values are categories, discrete counts or continuous measurements. Tally carefully, choose a sensible scale and label axes. A graph is useful only when its labels and scale make the data truthful.',example:'If scores 2, 2, 3, 4, 4, 4 occur, the frequencies are 2→2, 3→1 and 4→3.',check:'Why would a misleading vertical scale change how a bar chart appears even if the data values are unchanged?'}
]);

addUnits(beceEnglishPlans['Grammar & Structure'],[
 {title:'Tenses and aspect in real sentences',terms:[['tense','grammatical marking of time, especially present and past'],['aspect','how an action is viewed as complete, ongoing or related to another time'],['time marker','word or phrase such as yesterday, already, since or by then']],why:'English exam questions frequently depend on matching verb form to time and meaning, not memorising labels.',prerequisites:['verb','subject'],outcomes:['use time clues','distinguish simple/progressive/perfect forms','keep tense consistent when context requires'],explain:'First locate the time of the action, then decide whether it is habitual, ongoing, completed, or completed before another event. The verb form must express both the time and the relationship between events.',example:'“By the time she arrived, the bus had left.” The leaving happened before another past action, so past perfect is appropriate.',check:'Why is “had left” more precise than “left” in the example?'},
 {title:'Active, passive and modal forms',terms:[['active voice','the subject performs the action'],['passive voice','the subject receives the action'],['modal','helping verb such as can, may, must, should or might']],why:'These structures are part of grammatical accuracy and change emphasis, certainty, permission and obligation.',prerequisites:['subject','object','verb phrase'],outcomes:['change suitable active sentences to passive','choose modal forms by meaning','preserve tense during transformation'],explain:'In the passive, the receiver of an action becomes the grammatical subject and a form of “be” combines with the past participle. Modals add meanings such as ability, possibility, permission, advice or obligation.',example:'Active: “The prefect opened the gate.” Passive: “The gate was opened by the prefect.”',check:'What meaning difference is created by “must leave” versus “may leave”?'},
 {title:'Clauses, phrases and sentence relationships',terms:[['phrase','group of words without a complete subject–finite-verb relationship'],['clause','group of words containing a subject and predicate'],['main clause','clause able to stand as a sentence'],['subordinate clause','clause depending on another clause']],why:'Understanding clause structure helps with grammar, punctuation, comprehension and writing.',prerequisites:['subject','verb'],outcomes:['identify phrases and clauses','separate main/subordinate clauses','understand cause, condition, contrast and time relationships'],explain:'Do not classify by length. Look for the grammatical structure and the job the group performs. Connecting words such as because, although, if and when often signal the relationship between clauses.',example:'“Although it rained, we played.” “Although it rained” is subordinate; “we played” is the main clause.',check:'Which part of “When the bell rang, the pupils left” can stand alone, and why?'}
]);

addUnits(beceEnglishPlans['Comprehension'],[
 {title:'Critical reading and evaluating claims',terms:[['claim','statement presented as true'],['evidence','information supporting a claim'],['bias','preference that may influence presentation']],why:'JSS3 reading includes critical evaluation, so learners should judge support rather than accept every sentence automatically.',prerequisites:['main idea','supporting detail'],outcomes:['separate claim from evidence','notice unsupported generalisations','identify likely bias or persuasive language'],explain:'Ask what the writer wants you to believe and what evidence is actually supplied. Strong reading distinguishes fact, opinion, inference and unsupported assertion.',example:'“Everyone agrees this is the best school” is a claim; without data or named evidence, it is not automatically proven.',check:'What evidence would you ask for before accepting a strong claim in a passage?'},
 {title:'Reading for speed and purposeful scanning',terms:[['skimming','reading quickly for overall meaning'],['scanning','searching for a particular fact or word'],['key word','important word guiding where to look']],why:'Exam time is limited. Skilled readers change reading speed according to the task.',prerequisites:['main idea'],outcomes:['skim for gist','scan for specific details','slow down for inference or difficult wording'],explain:'Do not read every question in exactly the same way. For a date or name, scan. For the central idea, skim first and confirm. For inference, return to the relevant sentences and read closely.',example:'If asked “In what year did the programme begin?”, scan for years rather than rereading every sentence slowly.',check:'When should you stop scanning and read a sentence closely?'},
 {title:'Summary reading and compression',terms:[['summary','shorter statement containing essential ideas'],['redundancy','unnecessary repetition'],['point','one distinct relevant idea']],why:'Summary skills strengthen comprehension and formal writing and are explicitly part of JSS3 English work.',prerequisites:['main idea','paraphrase'],outcomes:['identify distinct points','remove examples/repetition','restate ideas accurately in fewer words'],explain:'A good summary preserves the important meaning but removes examples, repetition and decorative detail. Count ideas, not sentences, and avoid adding personal opinion.',example:'“The road flooded because drains were blocked with refuse” can become “Blocked drains caused the flooding.”',check:'What information can be removed from an example without changing its main point?'}
]);

addUnits(beceEnglishPlans['Vocabulary & Lexis'],[
 {title:'Word formation: roots, prefixes and suffixes',terms:[['root/base','core form carrying the central meaning'],['prefix','element added before a base'],['suffix','element added after a base']],why:'Word-building knowledge helps learners infer unfamiliar vocabulary and control spelling.',prerequisites:['basic word classes'],outcomes:['identify common affixes','infer likely meaning from word parts','notice when suffixes change word class'],explain:'Break unfamiliar words into meaningful parts. A prefix often modifies meaning; a suffix may change grammatical function. Always confirm with sentence context because word parts alone are not enough.',example:'“unhelpful” = un- + help + -ful: “not helpful”. “decide” → “decision” changes from verb to noun.',check:'How can the suffix in “careless” help you infer its meaning and word class?'}
]);

addUnits(beceEnglishPlans['Sentence Meaning'],[
 {title:'Idiomatic and figurative sentence interpretation',terms:[['literal meaning','ordinary direct meaning of the words'],['figurative meaning','meaning created beyond the literal words'],['idiomatic expression','fixed phrase understood as a whole']],why:'Exam sentence-meaning items often punish word-for-word interpretation of fixed expressions.',prerequisites:['context clues','vocabulary'],outcomes:['recognise non-literal language','preserve tone and degree when paraphrasing','reject options that are only partly equivalent'],explain:'First decide whether the expression can reasonably be literal in the context. Then identify the intended idea, including strength or attitude. A correct paraphrase must preserve the whole meaning, not merely one familiar word.',example:'“Tola is anything but lazy” means Tola is definitely not lazy.',check:'Why would “Tola is sometimes lazy” be an inaccurate paraphrase?'}
]);

addUnits(beceEnglishPlans['Spelling & Usage'],[
 {title:'Editing for spelling, grammar and usage together',terms:[['edit','review and correct a text'],['proofread','check a final text for errors'],['context','surrounding words that determine the correct form']],why:'Real exam success requires noticing errors inside sentences, not only spelling isolated words.',prerequisites:['basic punctuation','word classes'],outcomes:['spot multiple error types','use context to choose confusable forms','check agreement and punctuation while proofreading'],explain:'Read once for meaning, then again for form. Check each sentence for spelling, verb agreement, punctuation and word choice. Editing is systematic rather than guessing what “looks right”.',example:'“Their going to recieve the prizes” needs “They’re going to receive the prizes.”',check:'What two different errors appear in “Their going to recieve…”?'}
]);

addUnits(beceEnglishPlans['Word Classes'],[
 {title:'Determiners, interjections and function shifts',terms:[['determiner','word placed before a noun to identify or quantify it'],['interjection','word or phrase expressing sudden feeling'],['function','the grammatical job a word performs in its sentence']],why:'Words cannot always be classified from spelling alone; exams may test the same word in different functions.',prerequisites:['noun','verb','adjective','adverb'],outcomes:['identify determiners','recognise interjections','classify a word from its actual sentence function'],explain:'Look at what the word is doing in the sentence. “Before” may behave as a preposition, conjunction or adverb depending on what follows it. This is why function is more reliable than memorising lists.',example:'“Before lunch” uses before as a preposition; “before we ate” uses it as a conjunction.',check:'How would you decide the word class of “fast” in two different sentences?'}
]);

addUnits(beceEnglishPlans['Concord'],[
 {title:'Agreement in relative clauses and special constructions',terms:[['relative pronoun','who, whom, whose, which or that introducing a relative clause'],['head noun','main noun controlling the structure of a noun phrase']],why:'Harder concord questions hide the controlling noun inside longer structures.',prerequisites:['subject','relative clause'],outcomes:['find the true controller of a verb','handle one of/each of structures','avoid attraction to a nearby noun'],explain:'Strip away interrupting phrases and ask which noun the verb is actually making a statement about. In relative clauses, identify the antecedent of who/that before selecting the verb.',example:'“She is one of the pupils who work hard.” “who” refers to pupils, so “work” is plural.',check:'Which noun controls the verb in “The box of books is heavy”, and why?'}
]);

beceEnglishPlans['Oral English']=M(
 'Hear and reason about English speech sounds, stress, rhythm and intonation at JSS3/BECE level.',
 'Listening and speaking are part of the English curriculum. Oral work should teach sound contrasts and meaning, not ask learners to memorise symbols without hearing or understanding them.',[
  {title:'Speech sounds: vowels and consonants',terms:[['phoneme','smallest sound contrast that can distinguish meaning'],['vowel','speech sound made without blocking airflow in the mouth'],['consonant','speech sound made with some narrowing or closure']],why:'Sound discrimination supports pronunciation, spelling and oral-English questions.',prerequisites:['letters are not always identical to sounds'],outcomes:['distinguish selected vowel/consonant contrasts','separate spelling from sound'],explain:'English spelling and sound do not match one-to-one. Listen to the target sound in whole words, compare it with a contrasting sound, and notice where the mouth/tongue changes.',example:'“ship” and “sheep” differ mainly in vowel quality even though both contain the letters “sh…p”.',check:'Why is looking only at spelling unreliable when comparing speech sounds?'},
  {title:'Syllables and word stress',terms:[['syllable','a beat-like unit organised around a vowel sound'],['stress','extra prominence given to a syllable']],why:'Stress can distinguish natural pronunciation and is commonly tested through word patterns.',prerequisites:['hearing syllable beats'],outcomes:['count syllables approximately','identify the stressed syllable in familiar words','avoid stressing every syllable equally'],explain:'Say the word naturally and listen for the syllable that is stronger, clearer or slightly longer. Do not simply choose the first syllable by habit.',example:'In “important”, the second syllable carries the main stress in standard pronunciation.',check:'What clues can help you hear which syllable is stressed?'},
  {title:'Sentence stress, rhythm and intonation',terms:[['rhythm','pattern of stressed and unstressed beats'],['intonation','movement of voice pitch across an utterance'],['contrastive stress','extra stress used to correct or contrast information']],why:'Meaning in speech is carried not only by words but also by prominence and pitch.',prerequisites:['word stress','sentence meaning'],outcomes:['hear emphasis','recognise common rising/falling patterns','explain how stress can change implied meaning'],explain:'Content words often receive stronger stress while grammar words may be weaker. Intonation can signal completion, continuation, attitude or question type. Context decides the interpretation.',example:'Stress in “I asked TOLA” contrasts Tola with another person; stress in “I ASKED Tola” contrasts asking with another action.',check:'How can changing the stressed word change what a speaker is correcting?'}
 ]);

beceEnglishPlans['Writing & Composition']=M(
 'Plan, organise, draft and improve clear examination writing across common JSS3 composition forms.',
 'JSS3 English includes narrative, descriptive, expository and argumentative composition, formal/informal letters and summary writing. AVORA must teach how to produce them, not merely define them.',[
  {title:'Planning before writing',terms:[['purpose','reason for writing'],['audience','person or group the writing is for'],['outline','short plan showing the order of ideas']],why:'Strong writing begins before the first paragraph.',prerequisites:['sentence construction'],outcomes:['identify task/purpose/audience','generate relevant points','arrange points logically'],explain:'Underline the command words and topic. Decide who will read the piece, what they need to know, and the best order for the ideas. A short outline prevents repetition and wandering.',example:'For “Write to your principal requesting a library improvement”, the audience is formal and the purpose is to request with reasons.',check:'What should you decide before writing the opening paragraph?'},
  {title:'Paragraphs, cohesion and development',terms:[['topic sentence','sentence stating or controlling a paragraph’s main point'],['cohesion','clear linking between ideas'],['supporting detail','example, reason or explanation developing a point']],why:'Good ideas lose marks when paragraphs are disorganised or undeveloped.',prerequisites:['complete sentences'],outcomes:['build one clear idea per paragraph','link ideas naturally','support claims with relevant detail'],explain:'A paragraph should usually develop one main idea. Start or establish the point, support it with explanation/examples, then connect naturally to the next idea. Avoid adding unrelated sentences just to increase length.',example:'A paragraph arguing for school sanitation can state the benefit, explain health effects, then give a concrete school example.',check:'How can you tell when one paragraph contains two unrelated main ideas?'},
  {title:'Narrative and descriptive composition',terms:[['narrative','writing that tells events in a meaningful sequence'],['descriptive','writing that creates a clear picture through selected details'],['setting','time and place of events']],why:'These forms require control of sequence, viewpoint and relevant detail rather than random storytelling.',prerequisites:['paragraphing','past tense control'],outcomes:['create a coherent event sequence','use selective sensory detail','maintain consistent viewpoint/tense'],explain:'Plan a beginning, development, turning point and ending for narrative work. In description, choose details that help the reader see, hear or feel the subject; do not list adjectives without purpose.',example:'Instead of “The market was very busy”, show selected evidence: traders calling, baskets moving, buses stopping and people negotiating.',check:'What makes description vivid without becoming a list of unrelated details?'},
  {title:'Expository and argumentative writing',terms:[['expository','writing that explains or informs'],['argument','position supported with reasons and evidence'],['counterargument','reasonable opposing view addressed by the writer']],why:'Academic and examination writing requires logical development of ideas.',prerequisites:['paragraphing','fact versus opinion'],outcomes:['explain processes clearly','state a position','support reasons','address an opposing view fairly'],explain:'Exposition should make a topic easier to understand through ordered explanation. Argumentative writing should state a clear position and support it with reasons, examples and where possible evidence, while avoiding insults or unsupported claims.',example:'An argument for longer library hours might use student access, study schedules and examination preparation as separate supported reasons.',check:'What is the difference between a reason and mere repetition of your opinion?'},
  {title:'Formal and informal letters',terms:[['salutation','greeting opening a letter'],['complimentary close','conventional closing phrase'],['tone','attitude and level of formality']],why:'Letter tasks test both content and correct format/register.',prerequisites:['audience','paragraphing'],outcomes:['choose correct format','maintain suitable tone','include all requested content points'],explain:'The relationship with the recipient controls tone and conventions. Formal letters are respectful, direct and purpose-led; informal letters are personal but still clear and organised.',example:'A request to a principal should not use chat abbreviations or overly casual greetings.',check:'Which parts of a letter change when the recipient changes from a friend to a principal?'},
  {title:'Editing and final examination check',terms:[['revision','improving ideas and organisation'],['proofreading','checking final language/mechanics']],why:'A short final check can recover marks lost through avoidable errors.',prerequisites:['grammar','spelling','punctuation'],outcomes:['check task completion','remove repetition','correct common language errors'],explain:'First verify that every part of the question has been answered. Then inspect paragraph order, tense consistency, agreement, punctuation and spelling. Editing should improve meaning, not merely decorate sentences.',example:'A final check may reveal that a letter gave reasons for a request but forgot the actual request in the closing paragraph.',check:'What should you check before spending time correcting individual spellings?'}
 ]);

beceEnglishPlans['Literature']=M(
 'Read prose, poetry and drama for meaning, technique, character, theme and lesson at JSS level.',
 'The JSS3 English curriculum includes revision of prose, poetry and drama as well as lessons from folktales, myths and legends.',[
  {title:'Prose: plot, character and theme',terms:[['plot','ordered sequence of important events'],['character','person or figure taking part in a text'],['theme','central idea explored by a work']],why:'Literature questions require evidence from the text, not vague personal impressions.',prerequisites:['literal comprehension','inference'],outcomes:['summarise plot','describe character using evidence','identify themes without confusing them with single events'],explain:'Track what happens, why it happens and how characters respond. A theme is broader than one event; it is an idea the text explores repeatedly.',example:'If several events show the cost of dishonesty, “consequences of dishonesty” may be a theme.',check:'What evidence would you use before calling a character courageous?'},
  {title:'Poetry: voice, image, sound and meaning',terms:[['speaker','voice speaking in a poem'],['imagery','language appealing to senses or creating mental pictures'],['rhyme','matching or similar end sounds'],['figurative language','non-literal expression such as metaphor or personification']],why:'Poetry becomes manageable when learners connect technique to meaning instead of only naming devices.',prerequisites:['figurative meaning'],outcomes:['identify the speaker','explain a selected image','connect sound/figure of speech to effect'],explain:'Read the poem for situation and feeling first. Then examine how particular words, images and sounds create that effect. Naming a device earns little understanding unless you explain what it does.',example:'Calling the sun “a golden coin” is a metaphor that creates a bright circular image.',check:'Why is identifying “metaphor” alone not a complete explanation?'},
  {title:'Drama: dialogue, action and stage meaning',terms:[['dialogue','spoken exchange between characters'],['stage direction','instruction describing action, movement or delivery'],['conflict','struggle between opposing forces']],why:'Drama communicates through speech and action, so learners must read beyond dialogue alone.',prerequisites:['character','inference'],outcomes:['use dialogue/action as evidence','identify conflict','interpret basic stage directions'],explain:'Ask what a character says, what the character does and how others respond. Stage directions may reveal tone or action that changes the meaning of the words.',example:'A character saying “I am fine” while turning away and crying suggests the words are not the whole truth.',check:'What evidence besides dialogue can reveal a character’s real feelings?'},
  {title:'Folktales, myths, legends and lessons',terms:[['folktale','traditional story passed through a community'],['myth','traditional story often explaining origins or beliefs'],['legend','traditional story linked to a person/place and historical memory'],['moral/lesson','principle a story encourages readers to consider']],why:'JSS3 revision includes non-African folktales and lessons from myths/legends.',prerequisites:['plot','theme'],outcomes:['distinguish broad traditional forms','infer lessons from events','avoid forcing a moral unsupported by the story'],explain:'Study the recurring choices, consequences and cultural assumptions in the story. A lesson should come from what the narrative demonstrates, not from a random proverb added afterwards.',example:'If greed repeatedly causes loss, the story may warn against greed.',check:'How do consequences in a story help you identify a supported lesson?'}
 ]);

export const nceeMathPlans:Record<string,TutorPlan>={
 'Number Skills':M('Use whole numbers accurately and confidently in Common Entrance calculations and word problems.','Number operations are the foundation underneath most NCEE Mathematics questions.',[
  {title:'Place value and reading large numbers',terms:[['place value','value of a digit because of its position'],['digit','one symbol from 0 to 9']],why:'Accurate place value prevents errors in reading, comparing and calculating with whole numbers.',prerequisites:['counting'],outcomes:['read/write whole numbers','compare/order numbers','identify digit values'],explain:'Read numbers in place-value groups and compare from the greatest place first.',example:'In 348,275, the digit 4 represents 40,000.',check:'What is the value of 7 in 572,406?'},
  {title:'Addition, subtraction, multiplication and division',terms:[['sum','result of addition'],['difference','result of subtraction'],['product','result of multiplication'],['quotient','result of division']],why:'NCEE questions often hide a basic operation inside a sentence.',prerequisites:['place value','times tables'],outcomes:['calculate accurately','choose the operation from context','estimate to check answers'],explain:'First decide what the story is asking: combine, find a difference, form equal groups, or share equally. Then calculate and estimate whether the result is sensible.',example:'Six classes with 45 pupils each means 6 × 45 = 270 pupils.',check:'What wording in a problem usually suggests equal sharing?'},
  {title:'Order of operations and multi-step number work',terms:[['operation','calculation such as +, −, × or ÷'],['brackets','symbols grouping work that should be handled first']],why:'Multi-step items require a deliberate order, not left-to-right guessing.',prerequisites:['four operations'],outcomes:['follow operation order','show steps clearly','check intermediate results'],explain:'Handle brackets first, then multiplication/division, then addition/subtraction, working carefully from left to right within the same level.',example:'20 − 3 × 4 = 20 − 12 = 8.',check:'Why is 20 − 3 × 4 not equal to 68?'}
 ]),
 'Fractions & Decimals':M('Understand fractions and decimals as numbers and use them in calculations.','Common Entrance uses fractions and decimals in direct questions and real-life problems.',[
  {title:'Meaning, equivalence and comparison',terms:[['numerator','top number in a fraction'],['denominator','bottom number showing equal parts'],['equivalent fractions','fractions with the same value']],explain:'A fraction describes equal parts of a whole. Compare using common denominators, equivalent fractions or decimal values.',example:'1/2 = 2/4 = 0.5.',check:'Which is larger, 3/5 or 1/2, and how do you know?'},
  {title:'Operations with fractions',terms:[['common denominator','shared denominator used for addition/subtraction']],explain:'For addition/subtraction, make denominators compatible. For multiplication, multiply corresponding parts and simplify. Explain each change so the learner sees why it is valid.',example:'1/2 + 1/4 = 2/4 + 1/4 = 3/4.',check:'Why can’t you add 1/2 + 1/4 as 2/6?'},
  {title:'Decimals and fraction conversion',terms:[['decimal place','position to the right of the decimal point']],explain:'Connect tenths, hundredths and thousandths with fractions over 10, 100 and 1000.',example:'0.25 = 25/100 = 1/4.',check:'Write 0.7 as a fraction in simplest form.'}
 ]),
 'Measurement':M('Measure and convert length, mass, capacity and time using understood unit relationships.','Many NCEE problems combine arithmetic with units, so the unit must be understood before calculation.',[
  {title:'Length: mm, cm, m and km',terms:[['millimetre','small metric length unit'],['centimetre','100 centimetres make 1 metre'],['metre','standard metric unit of length'],['kilometre','1000 metres']],explain:'Learn the relationships first: 10 mm = 1 cm, 100 cm = 1 m, 1000 m = 1 km. Moving to a smaller unit creates more units.',example:'3 m = 3 × 100 = 300 cm.',check:'Why is 2.5 m equal to 250 cm?'},
  {title:'Mass and capacity',terms:[['gram','metric unit of mass'],['kilogram','1000 grams'],['millilitre','small unit of capacity'],['litre','1000 millilitres']],explain:'Use 1 kg = 1000 g and 1 L = 1000 mL before comparing or calculating quantities written in different units.',example:'2.5 kg = 2500 g.',check:'Convert 3 L 250 mL entirely to millilitres.'},
  {title:'Time and calendar',terms:[['duration','how long an event lasts'],['elapsed time','time between start and finish']],explain:'Use 60 seconds = 1 minute, 60 minutes = 1 hour and 24 hours = 1 day. For calendar questions, track actual dates and days rather than guessing.',example:'2 hours 30 minutes = 150 minutes.',check:'A lesson starts at 9:35 and lasts 45 minutes. When does it end?'}
 ]),
 'Geometry':M('Recognise shapes, angle relationships, perimeter and area at Primary 6 level.','Common Entrance geometry rewards visual understanding before formula use.',[
  {title:'2D and 3D shapes',terms:[['polygon','closed shape with straight sides'],['face','flat surface of a solid'],['edge','line where faces meet'],['vertex','corner point']],explain:'Classify shapes from their properties, not only from how they are rotated or drawn.',example:'A rectangle has four right angles and opposite sides equal.',check:'How is a square also a special rectangle?'},
  {title:'Angles',terms:[['acute','less than 90°'],['right angle','90°'],['obtuse','between 90° and 180°'],['straight angle','180°']],explain:'Estimate the type first, then measure or calculate if needed.',example:'A 65° angle is acute.',check:'What type of angle is 120°?'},
  {title:'Perimeter and area',terms:[['perimeter','distance around a shape'],['area','surface inside a shape']],explain:'Decide whether the question asks around or inside before choosing the operation/formula.',example:'A 7 cm by 3 cm rectangle has perimeter 20 cm and area 21 cm².',check:'Why are the units different for perimeter and area?'}
 ]),
 'Money & Percentage':M('Use money, change, simple percentages and everyday buying situations accurately.','NCEE often connects percentages to practical money problems.',[
  {title:'Naira and kobo calculations',terms:[['cost','amount paid'],['change','money returned after overpayment']],explain:'Align place values and keep the currency unit clear. Decide whether the question asks total cost, difference or change.',example:'₦1,000 − ₦680 = ₦320 change.',check:'You buy items costing ₦475 and ₦225 and pay ₦1,000. What change should you receive?'},
  {title:'Percent means out of 100',terms:[['percentage','number of parts out of 100']],explain:'Connect percentage to familiar fractions: 50% = 1/2, 25% = 1/4, 10% = 1/10. Then use multiplication for other cases.',example:'25% of ₦200 = 1/4 of ₦200 = ₦50.',check:'What is 10% of ₦750, and why?'}
 ]),
 'Data Handling':M('Read tables/charts and calculate simple mean, median, mode and range.','NCEE data questions test careful reading as much as calculation.',[
  {title:'Tables, pictograms and bar charts',terms:[['scale','value represented by each interval or symbol'],['frequency','how often something occurs']],explain:'Read titles, labels and keys before taking values from a display.',example:'If one pictogram symbol means 5 pupils, 4 symbols represent 20 pupils.',check:'Why must you read the key before counting pictogram symbols?'},
  {title:'Mean, median, mode and range',terms:[['mean','total divided by number of values'],['median','middle value after ordering'],['mode','most frequent value'],['range','largest minus smallest']],explain:'Identify which measure the question asks before doing any calculation.',example:'For 2,4,4,7, mean = 17/4, median = 4, mode = 4, range = 5.',check:'Which measure tells you the spread from smallest to largest?'}
 ]),
 'Word Problems':M('Translate real-life wording into the correct sequence of calculations.','Students often know arithmetic but lose marks because they choose the wrong operation or stop too early.',[
  {title:'Read, represent, solve, check',terms:[['given information','facts supplied by the question'],['unknown','quantity the question asks you to find']],explain:'State what you know and what you need. Translate the relationship into arithmetic, solve one step at a time, and reread the question to check the unit and meaning.',example:'5 buses × 48 pupils = 240 pupils.',check:'What should you identify before choosing an operation?'},
  {title:'Two-step problems',terms:[['intermediate result','answer from one step used in the next step']],explain:'Do not rush to use every number at once. Work out the first necessary quantity, label it, then use it in the next relationship.',example:'If 4 boxes contain 24 bottles each and 18 bottles are sold: total = 96, remaining = 78.',check:'Why is it useful to label the result of the first step?'}
 ]),
 'Factors & Multiples':M('Use factors, multiples, primes, HCF and LCM confidently.','These ideas support fractions, grouping and many quantitative problems.',[
  {title:'Factors, multiples and primes',terms:[['factor','number dividing another exactly'],['multiple','result of multiplying a number by an integer'],['prime number','whole number greater than 1 with exactly two positive factors']],explain:'Factors fit exactly into a number; multiples are generated by times tables. A prime has only 1 and itself as factors.',example:'Factors of 12 include 1,2,3,4,6,12. Multiples of 12 include 12,24,36…',check:'Why is 1 not a prime number?'},
  {title:'HCF and LCM',terms:[['HCF','greatest factor shared by numbers'],['LCM','smallest positive multiple shared by numbers']],explain:'Use HCF when finding the largest equal grouping/divisor, and LCM when finding the first time repeating cycles meet.',example:'HCF(12,18)=6; LCM(4,6)=12.',check:'Which idea would you use to find when two repeating schedules next happen together?'}
 ]),
 'Ratio & Proportion':M('Compare quantities and scale relationships with simple ratios and proportion.','Common Entrance ratio questions reward understanding of equal scaling.',[
  {title:'Meaning and simplification of ratio',terms:[['ratio','comparison of quantities by division'],['equivalent ratio','ratio created by multiplying/dividing both parts by the same non-zero factor']],explain:'Put comparable quantities in the same unit, then simplify both parts by the same factor.',example:'6 : 9 = 2 : 3.',check:'Why must both parts be divided by the same factor?'},
  {title:'Sharing in a ratio',terms:[['total parts','sum of ratio numbers']],explain:'Add the ratio parts, find the value of one part, then multiply for each share.',example:'Share 30 in ratio 2:3. Total parts=5, one part=6, shares=12 and 18.',check:'Why do we add 2 + 3 before sharing 30?'}
 ])
};

export const nceeEnglishPlans:Record<string,TutorPlan>={
 'Grammar':M('Build accurate Primary 6 sentence grammar for Common Entrance.','Grammar questions test whether words work together correctly in complete sentences.',[
  {title:'Sentence, subject and verb',terms:[['sentence','complete expression of an idea'],['subject','who/what the sentence is about'],['verb','word or phrase expressing action/state']],explain:'Find the subject and verb first. Many grammar choices become easier once the sentence structure is visible.',example:'“The girl sings.” girl = subject; sings = verb.',check:'What is the subject in “My two brothers play football”?'},
  {title:'Basic tense choices',terms:[['present tense','form used for present/habitual situations'],['past tense','form used for completed past situations'],['future','meaning referring to time ahead']],explain:'Use time words and sentence meaning to choose the verb form.',example:'“Yesterday she went”; “Every day she goes”.',check:'Which time clue tells you to choose a past form?'},
  {title:'Pronouns and sentence completeness',terms:[['pronoun','word replacing a noun'],['object pronoun','pronoun used as an object, such as me/him/her/us/them']],explain:'Choose pronoun forms according to the job they perform in the sentence.',example:'“The teacher called me”, not “called I”.',check:'Complete: “This gift is for ___.” I or me? Why?'}
 ]),
 'Vocabulary':M('Understand word meaning, opposites, relationships and appropriate everyday usage.','Vocabulary questions reward meaning in context, not memorising isolated word lists.',[
  {title:'Synonyms and antonyms',terms:[['synonym','word with similar meaning'],['antonym','word with opposite meaning']],explain:'Check the word inside its sentence because a word may have more than one meaning.',example:'In “The child was glad”, happy is a close synonym for glad.',check:'What is the opposite of “borrow” in a normal lending context?'},
  {title:'Context and word choice',terms:[['context','surrounding words and situation'],['appropriate','suitable for the meaning and situation']],explain:'Use the whole sentence to choose a word that fits both meaning and grammar.',example:'“The baby began to cry loudly” fits the situation and verb position.',check:'What clues in a sentence can help you choose between two similar words?'}
 ]),
 'Comprehension':M('Read short passages for direct detail, cause, sequence and simple inference.','Common Entrance comprehension asks learners to prove answers from what they read.',[
  {title:'Find directly stated information',terms:[['detail','specific information in a text'],['evidence','words in the passage supporting an answer']],explain:'Read the question, locate the relevant sentence, then answer exactly what was asked.',example:'If the passage says “The bell rang and pupils entered”, the action after the bell was entering classrooms.',check:'Why should you return to the passage instead of answering from memory alone?'},
  {title:'Cause, sequence and simple inference',terms:[['cause','reason something happened'],['sequence','order of events'],['inference','reasonable conclusion supported by clues']],explain:'Look for words such as because, after and so. For inference, combine clues but do not invent facts.',example:'Carrying an umbrella under dark clouds suggests the person expects rain.',check:'What clue makes the rain inference reasonable?'}
 ]),
 'Spelling':M('Spell high-frequency school and everyday words accurately using patterns and checking strategies.','Correct spelling matters in objective English and written communication.',[
  {title:'Sound, syllable and visual patterns',terms:[['syllable','beat-like part of a word'],['pattern','repeated arrangement that helps spelling']],explain:'Say the word, break it into useful parts, identify familiar spelling patterns, then check the complete word.',example:'beau-ti-ful helps organise “beautiful” into remembered parts.',check:'What part of “receive” is commonly reversed by mistake?'},
  {title:'Commonly confused spellings',terms:[['confusable','word/spelling easily mixed with another']],explain:'Compare the exact letters and use the word in a sentence before choosing.',example:'friend, because, school and receive each have frequent incorrect variants.',check:'Why is simply choosing what “looks familiar” unreliable?'}
 ]),
 'Punctuation':M('Use capitals, full stops, commas, question marks and apostrophes to make meaning clear.','Punctuation tells a reader how sentence parts relate.',[
  {title:'Capital letters and sentence endings',terms:[['capital letter','uppercase form used at sentence starts and for proper names'],['full stop','mark ending a statement'],['question mark','mark ending a direct question']],explain:'First identify whether the sentence is a statement or question and whether names/proper nouns need capitals.',example:'“Where are you going?” begins with a capital and ends with a question mark.',check:'What punctuation should end a direct question?'},
  {title:'Commas and apostrophes',terms:[['comma','mark separating selected parts of a sentence'],['apostrophe','mark used for possession and contractions']],explain:'Use commas for clear sentence boundaries such as direct address, and apostrophes to show possession or omitted letters.',example:'“Good morning, Musa.” “Tunde’s book.”',check:'What does the apostrophe show in “Amina’s bag”?'}
 ]),
 'Word Classes':M('Identify nouns, verbs, adjectives, adverbs, pronouns and other basic classes from their job in a sentence.','Word-class knowledge supports grammar and sentence construction.',[
  {title:'Nouns, pronouns and verbs',terms:[['noun','naming word'],['pronoun','word replacing a noun'],['verb','action/state word']],explain:'Classify by the word’s job in the sentence.',example:'In “She opened the door”, she = pronoun; opened = verb; door = noun.',check:'Which word is the verb in “The children laughed loudly”?'},
  {title:'Adjectives and adverbs',terms:[['adjective','word describing a noun'],['adverb','word modifying a verb/adjective/adverb']],explain:'Ask what the descriptive word modifies.',example:'“a careful pupil” uses careful as adjective; “worked carefully” uses carefully as adverb.',check:'What does “quickly” modify in “He quickly answered”?'},
  {title:'Prepositions and conjunctions',terms:[['preposition','shows a relationship such as place/time'],['conjunction','joins words or clauses']],explain:'Use sentence function to distinguish relation words from joining words.',example:'“under the chair” uses under; “because it rained” uses because to join ideas.',check:'What job does “and” do in “Tola and Musa arrived”?' }
 ]),
 'Sentence Meaning':M('Recognise the full meaning of simple statements and common expressions.','NCEE may ask learners to choose an equivalent interpretation.',[
  {title:'Restating meaning',terms:[['paraphrase','same idea expressed with different words'],['equivalent','same meaning']],explain:'Keep all important parts of the original meaning and reject options that add, remove or reverse information.',example:'“The test was easy” means it was not difficult.',check:'Why is “The test was short” not necessarily equivalent to “easy”?'},
  {title:'Frequency, order and command meaning',terms:[['frequency','how often something happens'],['instruction','statement telling someone what to do']],explain:'Words such as always, often, seldom, before and after change the exact meaning.',example:'“Ngozi seldom complains” means she does not complain often.',check:'What is the difference between “before” and “after” in event order?'}
 ]),
 'Concord':M('Match subjects and verbs correctly in Primary 6 sentences.','Agreement errors are common when extra words appear between subject and verb.',[
  {title:'Singular and plural agreement',terms:[['singular','one'],['plural','more than one'],['agreement','matching subject and verb forms']],explain:'Find the true subject, then choose the verb form that matches it.',example:'“The boy has”; “The boys have”.',check:'Choose: “The girls ___ ready.” is or are?'},
  {title:'Each, one of and compound subjects',terms:[['compound subject','two subjects joined together']],explain:'“Each” and “one” normally control singular verbs; subjects joined by “and” normally take plural verbs.',example:'“Each pupil has a pencil.” “Mother and father are home.”',check:'Why is “Each pupil have” incorrect in standard English?'}
 ]),
 'Oral English':M('Develop Primary 6 listening, pronunciation, syllable and stress awareness.','Sound awareness supports reading, spelling and spoken confidence.',[
  {title:'Sound contrasts in familiar words',terms:[['sound','what is heard in speech'],['letter','written symbol']],explain:'Letters and sounds are related but not identical. Compare whole words by listening carefully to the changing sound.',example:'ship/sheep and fan/van contain contrasts that change word identity.',check:'Why can two words have similar spelling but different sounds?'},
  {title:'Syllables and stress',terms:[['syllable','beat-like unit of a word'],['stress','stronger beat in a word']],explain:'Clap or tap syllables, then say the word naturally and identify the strongest beat.',example:'“teacher” has two syllables.',check:'How can tapping help you notice syllables?'}
 ]),
 'Writing & Usage':M('Build clear sentences and short organised writing suitable for Primary 6.','Common Entrance success and later secondary-school work depend on correct, purposeful written English.',[
  {title:'Complete sentences and paragraph focus',terms:[['complete sentence','words expressing a complete thought with suitable structure'],['paragraph','group of related sentences about one main idea']],explain:'Make sure each sentence completes an idea and each paragraph stays on one central point.',example:'“Because the rain” is incomplete; “We stayed indoors because of the rain” completes the idea.',check:'What makes a group of words a complete sentence?'},
  {title:'Simple planning and editing',terms:[['plan','decide ideas/order before writing'],['edit','improve and correct writing']],explain:'Before writing, list the main points. After writing, check meaning, capitals, punctuation, spelling and verb agreement.',example:'A short description of your school can be planned as place → buildings → people → what you value about it.',check:'What should you check after you finish a paragraph?'}
 ])
};

export function getTutorPlan(exam:string,subject:string,topic:string):TutorPlan|undefined{
  const name=topicAliases[topic]||topic;
  if(exam==='NCEE') return subject==='English Language'?nceeEnglishPlans[name]:nceeMathPlans[name];
  return subject==='English Language'?beceEnglishPlans[name]:beceTutorPlans[name];
}

export function getTutorTopicNames(exam:string,subject:string):string[]{
 const plans=exam==='NCEE'?(subject==='English Language'?nceeEnglishPlans:nceeMathPlans):(subject==='English Language'?beceEnglishPlans:beceTutorPlans);
 return Object.keys(plans);
}
