import {sql,withDbRetry} from './db';
function status(score:number,evidence:number){if(evidence<1)return 'STARTING';if(score<.4)return 'NEEDS_TEACHING';if(score<.65)return 'DEVELOPING';if(score<.8)return 'PRACTISING';return evidence>=3?'MASTERED':'SECURE'}
export async function syncWeeklyOutcome(sessionId:string){
 const [s]=await withDbRetry(()=>sql`SELECT es.student_id,es.score,es.exam_name,es.submitted_at,b.title,b.term,b.week_number FROM exam_sessions es JOIN weekly_exam_blueprints b ON b.id=es.weekly_exam_blueprint_id WHERE es.id=${sessionId} AND es.status='COMPLETED' AND es.marking_status IN ('NOT_REQUIRED','COMPLETED')`);if(!s)return;
 const marks=await withDbRetry(()=>sql`SELECT m.objective_id,m.subject_name,m.curriculum_topic_id,m.mark_fraction FROM weekly_exam_question_marks m WHERE m.session_id=${sessionId}`);
 const byObj=new Map<string,{earned:number;total:number}>(),byTopic=new Map<string,{subject:string;earned:number;total:number}>();
 for(const m of marks){if(m.objective_id){const o=byObj.get(String(m.objective_id))||{earned:0,total:0};o.earned+=Number(m.mark_fraction);o.total++;byObj.set(String(m.objective_id),o)}const k=String(m.subject_name)+'|'+String(m.curriculum_topic_id),t=byTopic.get(k)||{subject:String(m.subject_name),earned:0,total:0};t.earned+=Number(m.mark_fraction);t.total++;byTopic.set(k,t)}
 await withDbRetry(()=>sql.begin(async tx=>{for(const [objectiveId,v] of byObj){const [old]=await tx`SELECT evidence_count,earned_fraction FROM learner_objective_mastery WHERE student_id=${s.student_id} AND objective_id=${objectiveId}`;const evidence=Number(old?.evidence_count||0)+v.total,earned=Number(old?.earned_fraction||0)+v.earned,score=evidence?earned/evidence:0;await tx`INSERT INTO learner_objective_mastery(student_id,objective_id,evidence_count,earned_fraction,mastery_score,status,last_weekly_session_id) VALUES(${s.student_id},${objectiveId},${evidence},${earned},${score},${status(score,evidence)},${sessionId}) ON CONFLICT(student_id,objective_id) DO UPDATE SET evidence_count=${evidence},earned_fraction=${earned},mastery_score=${score},status=${status(score,evidence)},last_weekly_session_id=${sessionId},updated_at=now()`;}
 for(const [key,v] of byTopic){const topic=key.slice(key.indexOf('|')+1),pct=v.total?v.earned/v.total:0;await tx`INSERT INTO student_topic_mastery(student_id,curriculum_topic_id,status,first_attempted_at,mastered_at,attempts_count,updated_at) VALUES(${s.student_id},${topic},${pct>=.8?'MASTERED':pct<.5?'NEEDS_TEACHING':'DEVELOPING'},now(),${pct>=.8?new Date():null},${v.total},now()) ON CONFLICT(student_id,curriculum_topic_id) DO UPDATE SET status=${pct>=.8?'MASTERED':pct<.5?'NEEDS_TEACHING':'DEVELOPING'},mastered_at=CASE WHEN ${pct>=.8} THEN COALESCE(student_topic_mastery.mastered_at,now()) ELSE student_topic_mastery.mastered_at END,attempts_count=student_topic_mastery.attempts_count+${v.total},updated_at=now()`;}
 }));
 const ranked=[...byTopic.entries()].map(([k,v])=>({topic:k.slice(k.indexOf('|')+1),subject:v.subject,pct:v.total?v.earned/v.total:0,total:v.total})).sort((a,b)=>a.pct-b.pct);const weak=ranked.filter(x=>x.pct<.75),first=weak[0];
 if(first){await withDbRetry(()=>sql`UPDATE remediation_plans SET status='SUPERSEDED',completed_at=now() WHERE student_id=${s.student_id} AND status='ACTIVE'`);await withDbRetry(()=>sql`INSERT INTO remediation_plans(student_id,exam_name,subject_name,source_exam_session_id,weak_topics,recommended_topic,plan_reason) VALUES(${s.student_id},'AVORA_WEEKLY',${first.subject},${sessionId},${JSON.stringify(weak)}::jsonb,${first.topic},${first.pct<.4?first.topic+' needs reteaching from the foundation before fresh independent practice.':first.topic+' is developing but needs targeted revision and fresh independent proof.'})`);}
 const parents=await withDbRetry(()=>sql`SELECT parent_id FROM parent_student_links WHERE student_id=${s.student_id} AND status='ACTIVE'`);const weekStart=new Date();weekStart.setDate(weekStart.getDate()-((weekStart.getDay()+6)%7));weekStart.setHours(0,0,0,0);const weekEnd=new Date(weekStart);weekEnd.setDate(weekEnd.getDate()+6);const strongest=[...ranked].sort((a,b)=>b.pct-a.pct)[0];for(const p of parents){const summary=`AVORA Weekly completed: ${Math.round(Number(s.score||0)*100)}%. ${first?'Priority: '+first.topic+'.':'No urgent weakness detected in this paper.'}`;await withDbRetry(()=>sql`INSERT INTO parent_weekly_reports(parent_id,student_id,week_start,week_end,lessons_completed,attempts,correct_answers,supervised_assessments,supervised_average,mastery_average,strongest_topic,weakest_topic,recommended_next,summary) VALUES(${p.parent_id},${s.student_id},${weekStart.toISOString().slice(0,10)},${weekEnd.toISOString().slice(0,10)},0,${marks.length},${marks.filter((m:any)=>Number(m.mark_fraction)>=.7).length},1,${Math.round(Number(s.score||0)*100)},${Math.round(Number(s.score||0)*100)},${strongest?.topic||null},${first?.topic||null},${first?'Review '+first.topic:'Continue the next curriculum week'},${summary}) ON CONFLICT(parent_id,student_id,week_start) DO UPDATE SET attempts=EXCLUDED.attempts,correct_answers=EXCLUDED.correct_answers,supervised_assessments=EXCLUDED.supervised_assessments,supervised_average=EXCLUDED.supervised_average,mastery_average=EXCLUDED.mastery_average,strongest_topic=EXCLUDED.strongest_topic,weakest_topic=EXCLUDED.weakest_topic,recommended_next=EXCLUDED.recommended_next,summary=EXCLUDED.summary,generated_at=now()`);await withDbRetry(()=>sql`INSERT INTO parent_notifications(parent_id,student_id,kind,title,body,href) VALUES(${p.parent_id},${s.student_id},'WEEKLY_REPORT','Weekly learning report ready',${summary},${'/parent/child/'+s.student_id})`);}
}