import {aiStructured} from './aiGateway';
export type WeeklyGeneratedQuestion={subject:string;topicId:string;objective:string;prompt:string;questionType:'MULTIPLE_CHOICE'|'SHORT_ANSWER';options:string[];correctAnswer:string;solution:string;difficulty:'FOUNDATION'|'STANDARD'|'CHALLENGE';skill:string;misconceptionTested:string};
export type WeeklyGeneratedPaper={questions:WeeklyGeneratedQuestion[];coverageSummary:string};
const schema={type:'object',properties:{questions:{type:'array',items:{type:'object',properties:{subject:{type:'string'},topicId:{type:'string'},objective:{type:'string'},prompt:{type:'string'},questionType:{type:'string',enum:['MULTIPLE_CHOICE','SHORT_ANSWER']},options:{type:'array',items:{type:'string'}},correctAnswer:{type:'string'},solution:{type:'string'},difficulty:{type:'string',enum:['FOUNDATION','STANDARD','CHALLENGE']},skill:{type:'string'},misconceptionTested:{type:'string'}},required:['subject','topicId','objective','prompt','questionType','options','correctAnswer','solution','difficulty','skill','misconceptionTested'],additionalProperties:false}},coverageSummary:{type:'string'}},required:['questions','coverageSummary'],additionalProperties:false};
function valid(q:WeeklyGeneratedQuestion){if(!q.prompt.trim()||!q.solution.trim()||!q.objective.trim()||!q.topicId.trim())return false;if(q.questionType==='MULTIPLE_CHOICE'){if(q.options.length!==4||new Set(q.options.map(x=>x.trim().toLowerCase())).size!==4)return false;if(!q.options.map(x=>x.trim()).includes(q.correctAnswer.trim()))return false;}return true;}
export async function generateWeeklyPaper(args:{classLevel:string;term:number;week:number;questionCount:number;durationMinutes:number;scope:any[];adminInstruction:string}){
 const instructions=['You are AVORA Academic Assessment Engine. Build a rigorous Nigerian junior-secondary weekly assessment strictly from the supplied approved curriculum scope and daily objectives.','Never test a topic or skill outside the supplied scope. Every question must name the exact supplied objective it measures.','Distribute questions according to each scope item targetQuestions. Respect its difficulty target where possible.','Test understanding, application, misconceptions and transfer. Do not merely repeat definitions or clone daily checks.','Mathematics calculations must be independently solvable and the stated correct answer must agree with the worked solution. English questions must have one defensible answer where objective.','For MULTIPLE_CHOICE return exactly four distinct plausible options and correctAnswer must exactly equal one option. For SHORT_ANSWER options must be an empty array.','Solutions must be sufficiently explicit for an academic reviewer to verify.','Do not claim any question is an official NERDC, WAEC, NECO or BECE question unless that provenance is explicitly supplied.'].join(' ');
 const input=JSON.stringify({classLevel:args.classLevel,term:args.term,week:args.week,questionCount:args.questionCount,durationMinutes:args.durationMinutes,approvedWeeklyScope:args.scope,adminInstruction:args.adminInstruction});
 const result=await aiStructured<WeeklyGeneratedPaper>({instructions,input,schema,name:'weekly_exam_paper',maxOutputTokens:12000});if(!result.ok)return result;
 if(!result.json||result.json.questions.length!==args.questionCount||!result.json.questions.every(valid))return {ok:false as const,error:'WEEKLY_PAPER_FAILED_STRUCTURAL_VALIDATION'};
 const allowed=new Map<string,Set<string>>();for(const s of args.scope){allowed.set(String(s.curriculum_topic_id),new Set((s.objectives||[]).map((o:any)=>String(o.objective))))}
 if(result.json.questions.some(q=>!allowed.has(q.topicId)||!allowed.get(q.topicId)!.has(q.objective)))return {ok:false as const,error:'WEEKLY_PAPER_FAILED_SCOPE_VALIDATION'};
 return result;
}
export async function regenerateWeeklyQuestion(args:{classLevel:string;subject:string;topicId:string;objective:string;difficulty:'FOUNDATION'|'STANDARD'|'CHALLENGE';originalPrompt:string;reviewerNote:string;adminInstruction:string}){
 const instructions=['You are replacing exactly one rejected AVORA weekly-exam question.','Stay strictly inside the supplied class, subject, curriculum topic and exact objective. Do not broaden the scope.','Produce a genuinely different question from originalPrompt while measuring the same objective and difficulty.','For MULTIPLE_CHOICE return exactly four distinct plausible options and correctAnswer must exactly equal one option. For SHORT_ANSWER options must be empty.','Provide a worked, independently checkable solution. Address the reviewer concern where supplied.','Do not claim official examination provenance.'].join(' ');
 const input=JSON.stringify(args);
 const result=await aiStructured<WeeklyGeneratedQuestion>({instructions,input,schema:{type:'object',properties:(schema as any).properties.questions.items.properties,required:(schema as any).properties.questions.items.required,additionalProperties:false},name:'weekly_exam_replacement',maxOutputTokens:1800});
 if(!result.ok)return result;
 const q=result.json;if(!q||!valid(q)||q.subject!==args.subject||q.topicId!==args.topicId||q.objective!==args.objective||q.difficulty!==args.difficulty)return {ok:false as const,error:'WEEKLY_REPLACEMENT_FAILED_SCOPE_VALIDATION'};
 return result;
}
