export type WholeNumberSection={id:string;title:string;paragraphs:string[];examples?:string[]};
export const wholeNumbersObjectives=[
 'Explain whole numbers and distinguish digits from numerals.',
 'Use place value and three-digit periods to read and write large numbers correctly.',
 'Count, read and write numbers in millions, billions and trillions.',
 'Use face value, place value, zero placeholders and expanded form accurately.',
 'Compare and order whole numbers and interpret them on a correctly scaled number line.',
 'Apply large numbers to real-life and quantitative-reasoning problems.'
];
export const wholeNumbersSections:WholeNumberSection[]=[
 {id:'meaning',title:'1. What Are Whole Numbers?',paragraphs:['Whole numbers are complete counting quantities beginning with zero: 0, 1, 2, 3, 4, 5, … . They do not contain fractional or decimal parts.','Zero is a whole number. If a basket had four oranges and all four were removed, 0 correctly describes how many remain.'],examples:['Whole numbers: 0, 16, 304, 9,004.','Not whole numbers: 2.7 and 1/2.']},
 {id:'digits',title:'2. Digits and Numerals',paragraphs:['There are ten digits: 0, 1, 2, 3, 4, 5, 6, 7, 8 and 9. We combine digits to form numerals.','In 407,216 the digits are 4, 0, 7, 2, 1 and 6. Zero still occupies a position; removing it changes the number.'],examples:['407,216 is a six-digit numeral.','407,216 is not equal to 47,216.']},
 {id:'place',title:'3. Place Value — Why Position Changes Value',paragraphs:['Our ordinary number system is a base-ten place-value system. Starting from the right, the positions are units, tens, hundreds, thousands, ten thousands, hundred thousands, millions, and so on.','Every move one place to the left makes the place ten times as large: 1 unit = 1; 1 ten = 10; 1 hundred = 100; 1 thousand = 1,000.'],examples:['In 364,218, the digit 6 is in the ten-thousands place, so its place value is 60,000.','In 555, the three 5s have values 500, 50 and 5 because their positions differ.']},
 {id:'periods',title:'4. The Standard Three-Digit Period System',paragraphs:['Long numbers become easier to read when we divide them into groups of three digits called periods. Always start grouping from the RIGHT.','The first group is the Units period, the next is Thousands, then Millions, Billions and Trillions. Inside every period the same pattern repeats: hundreds, tens, units.','A new period is one thousand times the period immediately to its right.'],examples:['584327619 → 584 | 327 | 619 → 584,327,619.','45872631 → 45 | 872 | 631 → 45,872,631. Do not group it as 458 | 726 | 31.']},
 {id:'read',title:'5. Reading Large Whole Numbers Correctly',paragraphs:['Read one period at a time from left to right. Read the three-digit group normally, then say its period name. The final Units period has no period name.','For 584,327,619: 584 is the Millions period, 327 is the Thousands period and 619 is the Units period.'],examples:['584,327,619 = five hundred and eighty-four million, three hundred and twenty-seven thousand, six hundred and nineteen.','27,405,318 = twenty-seven million, four hundred and five thousand, three hundred and eighteen.']},
 {id:'zeros',title:'6. Reading Numbers Containing Zeros',paragraphs:['Zero is often silent when a number is read aloud, but it is not meaningless. It keeps other digits in their correct positions.','An entire period containing 000 is skipped when reading aloud, while its three positions are still preserved in the written numeral.'],examples:['406,072,015 = four hundred and six million, seventy-two thousand and fifteen.','7,020,000,000 = seven billion, twenty million. The 000 thousands and 000 units periods are not spoken.']},
 {id:'billions',title:'7. Millions, Billions and Trillions',paragraphs:['The period pattern continues without changing: Units | Thousands | Millions | Billions | Trillions.','1,000,000 is one million. 1,000,000,000 is one billion. 1,000,000,000,000 is one trillion. Counting periods is safer than trying to guess a long number by sight.'],examples:['3,204,018,506 = three billion, two hundred and four million, eighteen thousand, five hundred and six.','2,015,000,004,030 = two trillion, fifteen billion, four thousand and thirty.']},
 {id:'value',title:'8. Finding Place Value With the Period Table',paragraphs:['Place a long numeral into the period table before finding the value of a difficult digit. This prevents position errors.','In 372,645,918, the digit 7 is in the ten-millions place, so its value is 7 × 10,000,000 = 70,000,000. The digit 4 is in the ten-thousands place, so its value is 40,000.'],examples:['Place value of 9 in 372,645,918 = 900.','Place value of 2 in 372,645,918 = 2,000,000.']},
 {id:'face',title:'9. Face Value and Place Value',paragraphs:['Face value is the digit itself. Place value is the value the digit has because of its position.'],examples:['In 47,582, the face value of 7 is 7, but its place value is 7,000.','In 628,419, the face value of 8 is 8 and its place value is 8,000.']},
 {id:'placeholder',title:'10. Zero as a Placeholder',paragraphs:['Zero can hold an empty position so that every other digit keeps its correct value. Removing a placeholder zero may create a completely different number.'],examples:['305 = 300 + 0 tens + 5. It is not 35.','6,042 = 6 thousands + 0 hundreds + 4 tens + 2 units. It is not 642.']},
 {id:'expanded',title:'11. Expanded Form',paragraphs:['Expanded form writes a numeral as the sum of the place values of its non-zero digits.'],examples:['47,326 = 40,000 + 7,000 + 300 + 20 + 6.','506,214 = 500,000 + 6,000 + 200 + 10 + 4.']},
 {id:'rebuild',title:'12. Forming a Number From Expanded Form',paragraphs:['To reverse expanded form, put every value into its correct position. Missing positions must be represented by zeros.'],examples:['700,000 + 30,000 + 5,000 + 400 + 8 = 735,408.','4,000,000 + 200,000 + 6,000 + 30 + 1 = 4,206,031.']},
 {id:'words',title:'13. Writing Number Names in Figures',paragraphs:['Break the spoken number into named periods, make each inner period three digits when necessary, and then join the periods.'],examples:['Seven hundred and twenty-four thousand, three hundred and eighteen = 724,318.','Four million, sixty-two thousand, five hundred and nine = 4,062,509.','Nine billion, twelve million, six thousand and forty = 9,012,006,040.']},
 {id:'compare',title:'14. Comparing Whole Numbers',paragraphs:['The symbols >, < and = mean greater than, less than and equal to. For positive whole numbers, a number with more digits is greater.','When two numbers have the same number of digits, compare from LEFT to RIGHT. Stop at the first position where the digits differ; that position decides which number is greater.'],examples:['100,000 > 99,999 because it has more digits.','527,184 > 523,996 because the first difference from the left is 7 thousands versus 3 thousands.']},
 {id:'order',title:'15. Ordering Whole Numbers',paragraphs:['Ascending order means smallest to largest. Descending order means largest to smallest. Compare using the highest place values first.'],examples:['Ascending: 6,045 < 6,405 < 6,450 < 6,540.','Descending: 6,540 > 6,450 > 6,405 > 6,045.']},
 {id:'line',title:'16. Understanding a Number Line',paragraphs:['A number line is a straight line on which numbers are placed in order at equal intervals. It helps us SEE position, size, movement and distance.','For whole numbers, values increase as we move right and decrease as we move left. In the diagram below, 7 is to the right of 4, so 7 > 4.','Equal spacing matters: when the scale is 1, every neighbouring tick differs by exactly 1.'],examples:['From 4 to 7 there are three equal intervals: 4→5, 5→6 and 6→7.']},
 {id:'distance',title:'17. Distance on a Number Line',paragraphs:['Distance is measured by the number of equal intervals between two positions, not by counting the labelled points.'],examples:['From 5 to 9 there are four intervals: 5→6, 6→7, 7→8, 8→9. Therefore the distance is 4 units.']},
 {id:'scale',title:'18. Understanding Number-Line Scale',paragraphs:['A number line does not always increase by 1. Before reading it, find the difference between neighbouring labelled ticks. That difference is the scale of each interval.','The second diagram below uses a scale of 10.'],examples:['0, 10, 20, 30, 40, 50 has a scale of 10.','100, 200, 300, 400, 500 has a scale of 100.']},
 {id:'patterns',title:'19. Whole-Number Patterns',paragraphs:['A number pattern follows a rule. Find the difference between consecutive terms before guessing what comes next.'],examples:['120, 130, 140, … uses +10, so the next terms are 150, 160.','2,500, 2,400, 2,300, … uses −100, so the next terms are 2,200, 2,100.','1,250, 1,500, 1,750, … uses +250, so the next terms are 2,000, 2,250.']},
 {id:'real',title:'20. Whole Numbers in Real Life and Quantitative Reasoning',paragraphs:['Large whole numbers are used for populations, budgets, enrolment, quantities, distances and other complete counts. Understanding the periods first allows us to compare and calculate with them safely.','When adding or subtracting large numbers, line up equal place values: units under units, thousands under thousands, millions under millions, and so on.'],examples:['₦8,750,000,000 + ₦3,600,000,000 = ₦12,350,000,000. The difference is ₦5,150,000,000.','125,640 books is greater than 125,604 books because the first differing place from the left is the tens place: 4 tens > 0 tens.']},
 {id:'mistakes',title:'21. Common Mistakes — and Why They Fail',paragraphs:['Do not group a long number from the left; periods are formed from the right.','Do not remove placeholder zeros.','Do not confuse face value with place value.','Do not compare large numbers from the units end; begin at the highest place value.','Do not count tick marks when a question asks for distance; count intervals.','Do not read a number line before identifying its scale.'],examples:['3,005,008 means three million, five thousand and eight — not 3,508.']},
 {id:'mastery',title:'22. Mastery Check',paragraphs:['Before leaving Whole Numbers, you should be able to explain the ideas, not merely recognise an answer. You should be able to group and read unfamiliar long numbers through trillions, write number names in figures, explain zero placeholders, find face and place value, expand and rebuild numerals, compare and order numbers, interpret number-line position/distance/scale, and solve real-life large-number problems.']}
];
export const wholeNumbersAuthoredQuestions=[
 {id:'avora-whole-01',prompt:'Which is NOT a whole number?',options:['0','105','17.5','9,004'],correctAnswer:'17.5',explanation:'17.5 contains a decimal part, so it is not a whole number.'},
 {id:'avora-whole-02',prompt:'Starting from the right, how should 584327619 be grouped into periods?',options:['584 | 327 | 619','58 | 432 | 761 | 9','584 | 3276 | 19','5843 | 276 | 19'],correctAnswer:'584 | 327 | 619',explanation:'Standard periods are groups of three digits formed from the right.'},
 {id:'avora-whole-03',prompt:'What is the place value of 7 in 372,645,918?',options:['7,000','70,000','7,000,000','70,000,000'],correctAnswer:'70,000,000',explanation:'7 is in the ten-millions position, so 7 × 10,000,000 = 70,000,000.'},
 {id:'avora-whole-04',prompt:'What is the face value of 8 in 384,219?',options:['8','800','8,000','80,000'],correctAnswer:'8',explanation:'Face value is the digit itself.'},
 {id:'avora-whole-05',prompt:'Which is the correct expanded form of 604,307?',options:['600,000 + 4,000 + 300 + 7','600,000 + 40,000 + 300 + 7','600,000 + 4,000 + 30 + 7','600,000 + 400 + 30 + 7'],correctAnswer:'600,000 + 4,000 + 300 + 7',explanation:'The non-zero digits occupy hundred-thousands, thousands, hundreds and units places.'},
 {id:'avora-whole-06',prompt:'Write three million, forty-two thousand and sixteen in figures.',options:['3,420,016','3,042,016','3,042,160','3,004,216'],correctAnswer:'3,042,016',explanation:'The periods are 3 | 042 | 016, giving 3,042,016.'},
 {id:'avora-whole-07',prompt:'Which statement is correct?',options:['527,184 < 523,996','527,184 = 523,996','527,184 > 523,996','They cannot be compared'],correctAnswer:'527,184 > 523,996',explanation:'From the left, the first difference is the thousands digit: 7 > 3.'},
 {id:'avora-whole-08',prompt:'A number line is labelled 0, 10, 20, 30, 40, 50. What does each interval represent?',options:['1','5','10','50'],correctAnswer:'10',explanation:'Neighbouring labelled ticks differ by 10, so the scale is 10 per interval.'},
 {id:'avora-whole-09',prompt:'What is the distance between 5 and 9 on a number line whose scale is 1?',options:['3 units','4 units','5 units','14 units'],correctAnswer:'4 units',explanation:'There are four equal intervals: 5→6, 6→7, 7→8 and 8→9.'},
 {id:'avora-whole-10',prompt:'Complete the pattern: 1,250, 1,500, 1,750, __, __',options:['1,800, 1,850','1,900, 2,000','2,000, 2,250','2,250, 2,500'],correctAnswer:'2,000, 2,250',explanation:'The rule is add 250 each time.'}
] as const;
