import {requireAdmin} from '@/lib/admin/access';
import {sql,withDbRetry} from '@/lib/db';
export const dynamic='force-dynamic';
async function safe<T>(work:()=>Promise<T[]>,fallback:T[]=[]){try{return await withDbRetry(work,1)}catch(e){console.error('validation telemetry query failed',e);return fallback}}
export default async function Validation(){await requireAdmin();const [summary,journey,reteach,offline,recent]=await Promise.all([
 safe(()=>sql`SELECT COUNT(*)::int total,COUNT(DISTINCT user_id)::int learners FROM product_validation_events WHERE created_at>now()-interval '7 days'`),
 safe(()=>sql`SELECT event_name,COUNT(*)::int n,COUNT(DISTINCT user_id)::int users FROM product_validation_events WHERE created_at>now()-interval '7 days' AND event_name IN ('TUTOR_LESSON_STARTED','TUTOR_LESSON_COMPLETED','EXAM_TO_TUTOR','MOCK_TO_TUTOR','LIVE_TO_TUTOR','PROGRESS_TO_TUTOR') GROUP BY event_name ORDER BY event_name`),
 safe(()=>sql`SELECT COUNT(*)::int n,COUNT(DISTINCT user_id)::int users FROM product_validation_events WHERE created_at>now()-interval '7 days' AND event_name='TUTOR_RETEACH_TRIGGERED'`),
 safe(()=>sql`SELECT event_name,COUNT(*)::int n,COUNT(DISTINCT user_id)::int users FROM product_validation_events WHERE created_at>now()-interval '7 days' AND event_name IN ('TUTOR_OFFLINE_ENTERED','TUTOR_RECONNECTED','TUTOR_CACHED_LESSON_USED','TUTOR_LESSON_RESTORED') GROUP BY event_name ORDER BY event_name`),
 safe(()=>sql`SELECT event_name,context,created_at FROM product_validation_events WHERE created_at>now()-interval '7 days' ORDER BY created_at DESC LIMIT 40`)
 ]);const s:any=summary[0]||{total:0,learners:0};const r:any=reteach[0]||{n:0,users:0};return <main className="shell admin-validation"><header className="admin-hero"><div><span className="eyebrow">REAL-USER VALIDATION</span><h1>See where AVORA works—and where learners struggle.</h1><p>A privacy-minimized workspace for operational validation. No raw learner answers, chat text, narration, names, emails, IP addresses or device fingerprints are stored here.</p></div></header><section className="admin-kpis"><div><span>7-day events</span><strong>{s.total}</strong><small>validation signals</small></div><div><span>Active learners</span><strong>{s.learners}</strong><small>distinct users represented</small></div><div><span>Re-teaching</span><strong>{r.n}</strong><small>{r.users} learners triggered exact re-guidance</small></div><div><span>Privacy boundary</span><strong>Safe</strong><small>allowlisted metadata only</small></div></section><section className="validation-grid"><article className="admin-panel"><h2>Learning journey signals</h2><p>Use this to test whether assessment evidence is actually turning into teaching and completion.</p>{journey.length?journey.map((x:any)=><div className="validation-row" key={x.event_name}><b>{String(x.event_name).replaceAll('_',' ')}</b><span>{x.n} events</span><small>{x.users} learners</small></div>):<p>No journey telemetry yet.</p>}</article><article className="admin-panel"><h2>Resilience signals</h2><p>These events show whether learners are recovering from real mobile/network interruptions.</p>{offline.length?offline.map((x:any)=><div className="validation-row" key={x.event_name}><b>{String(x.event_name).replaceAll('_',' ')}</b><span>{x.n} events</span><small>{x.users} learners</small></div>):<p>No resilience telemetry yet.</p>}</article></section><section className="admin-panel"><h2>Recent privacy-safe events</h2><div className="validation-events">{recent.map((x:any,i:number)=><div key={i}><b>{String(x.event_name).replaceAll('_',' ')}</b><span>{new Date(x.created_at).toLocaleString('en-NG')}</span><code>{JSON.stringify(x.context||{})}</code></div>)}</div></section></main>}
