import Link from 'next/link';import {requireAdmin} from '@/lib/admin/access';import {sql,withDbRetry} from '@/lib/db';
export const dynamic='force-dynamic';
export default async function AdminSupport({searchParams}:{searchParams:Promise<{status?:string;q?:string}>}){await requireAdmin();const {status='ACTIVE',q=''}=await searchParams;const term=`%${q.trim()}%`;const rows=await withDbRetry(()=>sql`
 SELECT st.id,st.title,st.category,st.subject,st.status,st.priority,st.class_level_snapshot,st.current_topic_snapshot,st.last_message_at,u.full_name,u.email,au.full_name assigned_name,
 (SELECT body FROM support_messages sm WHERE sm.thread_id=st.id ORDER BY sm.created_at DESC LIMIT 1) last_message,
 (SELECT sender_role FROM support_messages sm WHERE sm.thread_id=st.id ORDER BY sm.created_at DESC LIMIT 1) last_sender,
 (SELECT COUNT(*)::int FROM support_messages sm WHERE sm.thread_id=st.id) message_count
 FROM support_threads st JOIN users u ON u.id=st.student_id LEFT JOIN users au ON au.id=st.assigned_admin_id
 WHERE (${status}='ALL' OR (${status}='ACTIVE' AND st.status NOT IN ('RESOLVED','CLOSED')) OR st.status=${status})
 AND (${q.trim()}='' OR u.full_name ILIKE ${term} OR u.email ILIKE ${term} OR st.title ILIKE ${term})
 ORDER BY CASE st.priority WHEN 'URGENT' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'NORMAL' THEN 3 ELSE 4 END,st.last_message_at DESC LIMIT 300`);
 const [counts]=await withDbRetry(()=>sql`SELECT COUNT(*) FILTER(WHERE status NOT IN ('RESOLVED','CLOSED'))::int active,COUNT(*) FILTER(WHERE status='WAITING_ON_SUPPORT')::int waiting,COUNT(*) FILTER(WHERE priority IN ('HIGH','URGENT') AND status NOT IN ('RESOLVED','CLOSED'))::int priority,COUNT(*) FILTER(WHERE status='RESOLVED' AND resolved_at>now()-interval '7 days')::int resolved_week FROM support_threads`);
 return <main className="shell admin-v103 admin-support-page"><header className="admin-section-head"><div><span className="eyebrow">HUMAN ASSISTANCE</span><h1>Support that knows the learner, not just the ticket.</h1><p>See academic context, answer directly, assign ownership and keep every support interaction accountable.</p></div><Link href="/admin">← Admin overview</Link></header><section className="admin-kpis"><div><span>Active</span><strong>{counts?.active||0}</strong><small>open conversations</small></div><div><span>Waiting on us</span><strong>{counts?.waiting||0}</strong><small>need a support reply</small></div><div><span>Priority</span><strong>{counts?.priority||0}</strong><small>high or urgent</small></div><div><span>Resolved</span><strong>{counts?.resolved_week||0}</strong><small>last 7 days</small></div></section><form className="admin-search support-filter"><input name="q" defaultValue={q} placeholder="Search student, email or issue"/><select name="status" defaultValue={status}><option value="ACTIVE">Active</option><option value="WAITING_ON_SUPPORT">Waiting on support</option><option value="WAITING_ON_STUDENT">Waiting on student</option><option value="OPEN">Open</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option><option value="ALL">All</option></select><button>Filter</button></form><div className="support-admin-list">{rows.length?rows.map((r:any)=><Link key={r.id} href={`/admin/support/${r.id}`} className="support-admin-row"><div className="support-admin-person"><b>{r.full_name}</b><small>{r.class_level_snapshot||'Student'} · {r.email}</small></div><div><span className="support-row-kicker">{r.subject||r.category.replaceAll('_',' ')}</span><b>{r.title}</b><p>{r.last_message}</p></div><div><em className={`support-priority priority-${r.priority.toLowerCase()}`}>{r.priority}</em><small>{r.message_count} messages</small></div><div><em className={`support-status support-${r.status.toLowerCase().replaceAll('_','-')}`}>{r.status.replaceAll('_',' ')}</em><small>{r.assigned_name?`Assigned: ${r.assigned_name}`:'Unassigned'}</small></div><div className="support-row-time"><b>{r.last_sender==='STUDENT'?'Student replied':'Support replied'}</b><small>{new Date(r.last_message_at).toLocaleString('en-NG',{dateStyle:'medium',timeStyle:'short'})}</small></div><span className="row-arrow">→</span></Link>):<div className="support-admin-empty"><b>No conversations match this filter.</b><span>The queue is clear for this view.</span></div>}</div></main>}
