'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';

export default function NewSchoolWorkPage(){
 const router=useRouter();const [subject,setSubject]=useState('Mathematics'),[classLevel,setClassLevel]=useState('JSS1'),[label,setLabel]=useState(''),[rawText,setRawText]=useState(''),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function inspect(){setBusy(true);setError('');try{const r=await fetch('/api/assignments/convert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,classLevel,label,rawText})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPreview(d)}catch(e:any){setError(e.message||'Could not inspect this school work.')}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{
  const r=await fetch('/api/assignments/convert',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,classLevel,label,rawText})});
  const d=await r.json();if(!r.ok)throw new Error(d.error);
  const failures:string[]=[];
  for(const questionId of d.questionIds||[]){
   const ar=await fetch('/api/assignments/academic-convert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({questionId})});
   if(!ar.ok){const ad=await ar.json();failures.push(ad.error||'A question could not be academically prepared.')}
  }
  if(failures.length)throw new Error(failures[0]);
  router.push('/school-work/'+encodeURIComponent(d.assignmentId));router.refresh();
 }catch(e:any){setError(e.message||'Could not save this school work.')}finally{setBusy(false)}}
 return <main className="shell school-work-new"><header><span className="section-kicker">ADD SCHOOL WORK</span><h1>Your phone keyboard is enough.</h1><p>Type one question or a whole assignment exactly as your school gave it. You do not need to create A–D options yourself. For suitable objective questions, AVORA prepares the choices, correct answer and worked solution, then opens the prepared work for you immediately.</p></header><section className="school-work-form"><div className="school-work-fields"><label>Class<select value={classLevel} onChange={e=>setClassLevel(e.target.value)}><option>JSS1</option><option>JSS2</option><option>JSS3</option></select></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option>Mathematics</option><option>English Language</option></select></label><label>Assignment name<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="e.g. Monday Mathematics homework"/></label></div><label className="school-work-text"><span>Questions</span><small className="phone-input-help">Type naturally: “Find the HCF of 18 and 24” is enough. For many questions, use 1., 2., 3. or put each question on a new line. You can also paste from WhatsApp or Notes.</small><textarea inputMode="text" autoCapitalize="sentences" autoCorrect="on" spellCheck={subject==='English Language'} enterKeyHint="enter" value={rawText} onChange={e=>{setRawText(e.target.value);setPreview(null)}} rows={14} placeholder={'1. Find the HCF of 18 and 24\n2. Simplify 3/4 + 1/8\n3. Explain why plants need sunlight'} /></label>{error&&<p className="form-error">{error}</p>}<div className="school-work-actions"><button className="premium-secondary" disabled={busy||!rawText.trim()} onClick={inspect}>{busy?'Checking…':'Check questions first'}</button>{preview&&<button className="premium-primary" disabled={busy} onClick={save}>{busy?'Preparing questions…':'Prepare, save & open →'}</button>}</div></section>{preview&&<section className="conversion-preview"><header><span className="section-kicker">BEFORE SAVING</span><h2>{preview.questionCount} questions found</h2><p>AVORA keeps your original wording, prepares each question academically, and keeps uncertain topic matches separate for later confirmation.</p></header>{preview.questions.map((q:any)=><article key={q.index}><b>Question {q.index}</b><p>{q.originalText}</p><div><span>{q.questionType.replace('_',' ')}</span><span>{q.confidence}</span><small>{q.curriculumTopicId||'Topic will need confirmation'}</small>{q.questionType==='MULTIPLE_CHOICE'&&!/(?:^|\n)\s*[A-D][.)]\s+/m.test(q.originalText)&&<small>AVORA will create four answer choices + correct answer + worked solution</small>}{q.questionType==='THEORY'&&<small>AVORA will prepare a marking guide + worked solution</small>}</div></article>)}</section>}</main>
}
