'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';

export default function NewSchoolWorkPage(){
 const router=useRouter();const [subject,setSubject]=useState('Mathematics'),[classLevel,setClassLevel]=useState('JSS1'),[label,setLabel]=useState(''),[rawText,setRawText]=useState(''),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function inspect(){setBusy(true);setError('');try{const r=await fetch('/api/assignments/convert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,classLevel,label,rawText})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPreview(d)}catch(e:any){setError(e.message||'Could not inspect this school work.')}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/assignments/convert',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,classLevel,label,rawText})});const d=await r.json();if(!r.ok)throw new Error(d.error);router.push('/school-work');router.refresh()}catch(e:any){setError(e.message||'Could not save this school work.')}finally{setBusy(false)}}
 return <main className="shell school-work-new"><header><span className="section-kicker">ADD SCHOOL WORK</span><h1>Keep the question exactly as your school gave it.</h1><p>Type or paste the assignment. AVORA separates the questions and suggests curriculum matches, but nothing becomes revision material until it has been academically converted and confirmed.</p></header><section className="school-work-form"><div className="school-work-fields"><label>Class<select value={classLevel} onChange={e=>setClassLevel(e.target.value)}><option>JSS1</option><option>JSS2</option><option>JSS3</option></select></label><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option>Mathematics</option><option>English Language</option></select></label><label>Assignment name<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="e.g. Monday Mathematics homework"/></label></div><label className="school-work-text">Questions<textarea value={rawText} onChange={e=>{setRawText(e.target.value);setPreview(null)}} rows={14} placeholder={'1. Find the HCF of 18 and 24.\n\n2. Explain why...'} /></label>{error&&<p className="form-error">{error}</p>}<div className="school-work-actions"><button className="premium-secondary" disabled={busy||!rawText.trim()} onClick={inspect}>{busy?'Checking…':'Check questions first'}</button>{preview&&<button className="premium-primary" disabled={busy} onClick={save}>Save to my school-work memory →</button>}</div></section>{preview&&<section className="conversion-preview"><header><span className="section-kicker">BEFORE SAVING</span><h2>{preview.questionCount} questions found</h2><p>Low-confidence or unclassified matches stay visibly unresolved; AVORA does not guess silently.</p></header>{preview.questions.map((q:any)=><article key={q.index}><b>Question {q.index}</b><p>{q.originalText}</p><div><span>{q.questionType.replace('_',' ')}</span><span>{q.confidence}</span><small>{q.curriculumTopicId||'Topic needs confirmation'}</small></div></article>)}</section>}</main>
}
