import {NextResponse} from 'next/server';
import {z} from 'zod';
import {getSession} from '@/lib/auth';
import {sql,withDbRetry} from '@/lib/db';
import {subjectSlug} from '@/lib/subjects';

const body=z.object({topic:z.string().min(1).max(120),currentUnit:z.number().int().min(0).max(100),coveredUnits:z.array(z.number().int().min(0).max(100)).max(100),coverageComplete:z.boolean()});
export async function GET(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});try{const topic=new URL(req.url).searchParams.get('topic')?.trim();if(!topic)return NextResponse.json({progress:null});const [p]=await withDbRetry(()=>sql`SELECT target_exam,preferred_subject FROM student_profiles WHERE user_id=${s.userId}`);const exam=p?.target_exam||'BECE',slug=subjectSlug(p?.preferred_subject);const [row]=await withDbRetry(()=>sql`SELECT current_unit,covered_units,coverage_complete FROM tutor_topic_progress WHERE student_id=${s.userId} AND exam_name=${exam} AND subject_slug=${slug} AND lower(topic_name)=lower(${topic})`);return NextResponse.json({progress:row?{currentUnit:row.current_unit,coveredUnits:Array.isArray(row.covered_units)?row.covered_units:[],coverageComplete:row.coverage_complete}:null})}catch(e){console.error('tutor progress GET',e);return NextResponse.json({progress:null})}}
export async function POST(req:Request){const s=await getSession();if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});try{const d=body.parse(await req.json());const [p]=await withDbRetry(()=>sql`SELECT target_exam,preferred_subject FROM student_profiles WHERE user_id=${s.userId}`);const exam=p?.target_exam||'BECE',slug=subjectSlug(p?.preferred_subject);await withDbRetry(()=>sql`INSERT INTO tutor_topic_progress(student_id,exam_name,subject_slug,topic_name,current_unit,covered_units,coverage_complete,updated_at) VALUES(${s.userId},${exam},${slug},${d.topic},${d.currentUnit},${sql.json(d.coveredUnits)},${d.coverageComplete},now()) ON CONFLICT(student_id,exam_name,subject_slug,topic_name) DO UPDATE SET current_unit=EXCLUDED.current_unit,covered_units=EXCLUDED.covered_units,coverage_complete=EXCLUDED.coverage_complete,updated_at=now()`);return NextResponse.json({ok:true})}catch(e){console.error('tutor progress POST',e);return NextResponse.json({error:'Progress could not be saved yet.'},{status:503})}}
