import {NextResponse} from 'next/server';import {requireAdmin} from '@/lib/admin/access';import {sql,withDbRetry} from '@/lib/db';import {regenerateWeeklyQuestion} from '@/lib/weeklyExamGenerator';
export async function PATCH(req:Request,{params}:{params:Promise<{id:string;versionId:string;questionId:string}>}){await requireAdmin();const {id,versionId,questionId}=await params;const b=await req.json();const action=String(b.action||''),note=String(b.note||'').trim().slice(0,1000);
 const [row]=await withDbRetry(()=>sql`SELECT x.question_id,v.status FROM weekly_exam_version_questions x JOIN weekly_exam_versions v ON v.id=x.version_id WHERE x.version_id=${versionId} AND x.question_id=${questionId} AND v.blueprint_id=${id}`);
 if(!row)return NextResponse.json({error:'Paper question not found.'},{status:404});if(!['DRAFT','IN_REVIEW'].includes(String(row.status)))return NextResponse.json({error:'This paper version is no longer editable.'},{status:409});
 if(action==='PASS_RELEVANCE')await withDbRetry(()=>sql`UPDATE weekly_exam_version_questions SET relevance_status='PASSED',reviewer_note=COALESCE(NULLIF(${note},''),reviewer_note) WHERE version_id=${versionId} AND question_id=${questionId}`);
 else if(action==='PASS_ANSWER')await withDbRetry(()=>sql`UPDATE weekly_exam_version_questions SET answer_status='PASSED',reviewer_note=COALESCE(NULLIF(${note},''),reviewer_note) WHERE version_id=${versionId} AND question_id=${questionId}`);
 else if(action==='REJECT'){await withDbRetry(()=>sql`UPDATE weekly_exam_version_questions SET relevance_status='FAILED',answer_status='FAILED',reviewer_note=${note||'Rejected by academic reviewer'} WHERE version_id=${versionId} AND question_id=${questionId}`);await withDbRetry(()=>sql`UPDATE questions SET quality_status='REJECTED' WHERE id=${questionId}`);}
 else if(action==='REGENERATE'){
  const [q]=await withDbRetry(()=>sql`SELECT x.*,q.prompt,q.curriculum_objective,q.skill_id,b.class_level,j.instruction FROM weekly_exam_version_questions x JOIN questions q ON q.id=x.question_id JOIN weekly_exam_versions v ON v.id=x.version_id JOIN weekly_exam_blueprints b ON b.id=v.blueprint_id LEFT JOIN academic_ai_jobs j ON j.id=v.generation_job_id WHERE x.version_id=${versionId} AND x.question_id=${questionId}`);
  const generated=await regenerateWeeklyQuestion({classLevel:String(q.class_level),subject:String(q.subject_name),topicId:String(q.curriculum_topic_id),objective:String(q.curriculum_objective),difficulty:String(q.difficulty_band) as any,originalPrompt:String(q.prompt),reviewerNote:note,adminInstruction:String(q.instruction||'')});
  if(!generated.ok)return NextResponse.json({error:'Replacement failed scope or structural validation. Original question was kept.'},{status:422});
  const nq=generated.json;
  await withDbRetry(()=>sql.begin(async tx=>{const [fresh]=await tx`INSERT INTO questions(skill_id,prompt,question_type,options,correct_answer,explanation,difficulty,status,content_origin,curriculum_objective,quality_status,solution_steps,micro_skill,rights_status,class_level,curriculum_topic_id,assessment_kind,review_version) VALUES(${q.skill_id},${nq.prompt},${nq.questionType}::question_type,${JSON.stringify(nq.options)}::jsonb,${JSON.stringify(nq.correctAnswer)}::jsonb,${nq.solution},${nq.difficulty==='FOUNDATION'?1:nq.difficulty==='STANDARD'?2:3},'DRAFT'::question_status,'AI_WEEKLY_REPLACEMENT',${nq.objective},'DRAFT',${JSON.stringify([nq.solution])}::jsonb,${nq.skill},'ORIGINAL_AI_DRAFT',${q.class_level},${nq.topicId},'WEEKLY_EXAM',${'replacement'}) RETURNING id`;await tx`UPDATE weekly_exam_version_questions SET question_id=${fresh.id},relevance_status='PENDING',answer_status='PENDING',reviewer_note=NULL WHERE version_id=${versionId} AND question_id=${questionId}`;await tx`UPDATE questions SET quality_status='REJECTED' WHERE id=${questionId}`;}));
  return NextResponse.json({message:'Replacement generated. Its relevance and answer approvals were reset for fresh review.'});
 }
 else return NextResponse.json({error:'Unknown review action.'},{status:400});
 return NextResponse.json({ok:true,message:'Academic review saved.'});
}